sst-cpputils: StereoRingBuffer< T, N, MemoryOrder > Class Template Reference
StereoRingBuffer< T, N, MemoryOrder > Class Template Reference
#include <ring_buffer.h>
Public Member Functions
std::optional< std::pair< T, T > > pop ()
std::pair< std::vector< T >, std::vector< T > > popall ()
void push (T unitL, T unitR)
void push (std::pair< T, T > unit)
template<typename U = T>
std::enable_if_t< std::is_copy_constructible_v< U > > push (const T *unitsL, const T *unitsR, std::size_t sz)
template<typename U = T>
std::enable_if_t< std::is_copy_constructible_v< U > > push (const std::vector< T > &vL, const std::vector< T > &vR)
Public Member Functions inherited from RingBufferInternal< N, MemoryOrder >
RingBufferInternal ()
void clear ()
bool empty ()
std::size_t size ()
void subscribe ()
void unsubscribe ()
bool subscribed () const
Additional Inherited Members
Protected Member Functions inherited from RingBufferInternal< N, MemoryOrder >
std::size_t mask (std::size_t val)
std::pair< std::size_t, std::size_t > prepareToRead (std::size_t count) const
std::tuple< std::size_t, std::size_t, std::size_t > prepareToWrite (std::size_t count) const
Protected Attributes inherited from RingBufferInternal< N, MemoryOrder >
std::atomic_bool subscribed_
std::atomic_size_t writePos_
std::size_t readPos_
Member Function Documentation
pop()
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::optional< std::pair< T, T > > pop ()
References RingBufferInternal< N, MemoryOrder >::mask(), RingBufferInternal< N, MemoryOrder >::readPos_, and RingBufferInternal< N, MemoryOrder >::writePos_.
popall()
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::pair< std::vector< T >, std::vector< T > > popall ()
References RingBufferInternal< N, MemoryOrder >::mask(), RingBufferInternal< N, MemoryOrder >::prepareToRead(), RingBufferInternal< N, MemoryOrder >::readPos_, and RingBufferInternal< N, MemoryOrder >::writePos_.
push() [1/4]
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> void push (T unitL, T unitR)
References RingBufferInternal< N, MemoryOrder >::mask(), and RingBufferInternal< N, MemoryOrder >::writePos_.
Referenced by StereoRingBuffer< T, N, MemoryOrder >::push().
push() [2/4]
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> void push (std::pair< T, T > unit)
References StereoRingBuffer< T, N, MemoryOrder >::push().
Referenced by StereoRingBuffer< T, N, MemoryOrder >::push().
push() [3/4]
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> template<typename U = T> std::enable_if_t< std::is_copy_constructible_v< U > > push (const T * unitsL, const T * unitsR, std::size_t sz)
References RingBufferInternal< N, MemoryOrder >::mask(), RingBufferInternal< N, MemoryOrder >::prepareToWrite(), and RingBufferInternal< N, MemoryOrder >::writePos_.
push() [4/4]
template<typename T , std::size_t N, std::memory_order MemoryOrder = std::memory_order_relaxed> template<typename U = T> std::enable_if_t< std::is_copy_constructible_v< U > > push (const std::vector< T > & vL, const std::vector< T > & vR)
References StereoRingBuffer< T, N, MemoryOrder >::push().
The documentation for this class was generated from the following file:
ring_buffer.h