sst-cpputils: DynArray< T, Allocator > Class Template Reference
DynArray< T, Allocator > Class Template Reference
#include <dyn_array.h>
Public Types
using value_type = T
using allocator_type = Allocator
using size_type = std::allocator_traits< Allocator >::size_type
using difference_type = std::allocator_traits< Allocator >::difference_type
using reference = T &
using const_reference = const T &
using pointer = std::allocator_traits< Allocator >::pointer
using const_pointer = std::allocator_traits< Allocator >::const_pointer
using iterator = pointer
using move_iterator = std::move_iterator< iterator >
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
template<typename... ConstructionArgs>
DynArray (std::size_t n, Allocator a, ConstructionArgs &&...args)
template<typename... ConstructionArgs>
DynArray (std::size_t n, ConstructionArgs &&...args)
DynArray (std::size_t n, const T &v, Allocator a=Allocator())
DynArray (std::initializer_list< T > init_list, Allocator a=Allocator())
DynArray (const DynArray &that)
DynArray & operator= (const DynArray &that)
DynArray (const DynArray &that, Allocator a)
template<std::forward_iterator Iterator>
DynArray (Iterator first, Iterator last, Allocator a=Allocator())
DynArray (DynArray &&that)
DynArray & operator= (DynArray &&that)
~DynArray ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
pointer data ()
const_pointer data () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void fill (const value_type &val)
std::size_t size () const
bool empty () const
void reset (std::size_t n)
template<typename... ConstructionArgs>
DynArray (std::size_t n, A a, ConstructionArgs &&...args)
template<std::forward_iterator Iterator>
DynArray (Iterator begin, Iterator end, A a)
Member Typedef Documentation
value_type
template<typename T , class Allocator = std::allocator<T>> using value_type = T
allocator_type
template<typename T , class Allocator = std::allocator<T>> using allocator_type = Allocator
size_type
template<typename T , class Allocator = std::allocator<T>> using size_type = std::allocator_traits<Allocator>::size_type
difference_type
template<typename T , class Allocator = std::allocator<T>> using difference_type = std::allocator_traits<Allocator>::difference_type
reference
template<typename T , class Allocator = std::allocator<T>> using reference = T &
const_reference
template<typename T , class Allocator = std::allocator<T>> using const_reference = const T &
pointer
template<typename T , class Allocator = std::allocator<T>> using pointer = std::allocator_traits<Allocator>::pointer
const_pointer
template<typename T , class Allocator = std::allocator<T>> using const_pointer = std::allocator_traits<Allocator>::const_pointer
iterator
template<typename T , class Allocator = std::allocator<T>> using iterator = pointer
move_iterator
template<typename T , class Allocator = std::allocator<T>> using move_iterator = std::move_iterator<iterator>
const_iterator
template<typename T , class Allocator = std::allocator<T>> using const_iterator = const_pointer
reverse_iterator
template<typename T , class Allocator = std::allocator<T>> using reverse_iterator = std::reverse_iterator<iterator>
const_reverse_iterator
template<typename T , class Allocator = std::allocator<T>> using const_reverse_iterator = std::reverse_iterator<const_iterator>
Constructor & Destructor Documentation
DynArray() [1/10]
template<typename T , class Allocator = std::allocator<T>> template<typename... ConstructionArgs> DynArray (std::size_t n, Allocator a, ConstructionArgs &&... args)
DynArray() [2/10]
template<typename T , class Allocator = std::allocator<T>> template<typename... ConstructionArgs> DynArray (std::size_t n, ConstructionArgs &&... args) explicit
DynArray() [3/10]
template<typename T , class Allocator = std::allocator<T>> DynArray (std::size_t n, const T & v, Allocator a = Allocator())
DynArray() [4/10]
template<typename T , class Allocator = std::allocator<T>> DynArray (std::initializer_list< T > init_list, Allocator a = Allocator())
DynArray() [5/10]
template<typename T , class Allocator = std::allocator<T>> DynArray (const DynArray< T, Allocator > & that)
DynArray() [6/10]
template<typename T , class Allocator = std::allocator<T>> DynArray (const DynArray< T, Allocator > & that, Allocator a)
DynArray() [7/10]
template<typename T , class Allocator = std::allocator<T>> template<std::forward_iterator Iterator> DynArray (Iterator first, Iterator last, Allocator a = Allocator())
DynArray() [8/10]
template<typename T , class Allocator = std::allocator<T>> DynArray (DynArray< T, Allocator > && that)
~DynArray()
template<typename T , class A > ~DynArray ()
DynArray() [9/10]
template<typename T , class Allocator = std::allocator<T>> template<typename... ConstructionArgs> DynArray (std::size_t n, A a, ConstructionArgs &&... args)
DynArray() [10/10]
template<typename T , class Allocator = std::allocator<T>> template<std::forward_iterator Iterator> DynArray (Iterator begin, Iterator end, A a)
References DynArray< T, Allocator >::begin(), and DynArray< T, Allocator >::end().
Member Function Documentation
operator=() [1/2]
template<typename T , class Allocator = std::allocator<T>> DynArray & operator= (const DynArray< T, Allocator > & that)
operator=() [2/2]
template<typename T , class Allocator = std::allocator<T>> DynArray & operator= (DynArray< T, Allocator > && that)
begin() [1/2]
template<typename T , class Allocator = std::allocator<T>> iterator begin ()
Referenced by DynArray< T, Allocator >::cbegin(), DynArray< T, Allocator >::DynArray(), DynArray< T, Allocator >::fill(), DynArray< T, Allocator >::rend(), and DynArray< T, Allocator >::rend().
begin() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_iterator begin () const
cbegin()
template<typename T , class Allocator = std::allocator<T>> const_iterator cbegin () const
References DynArray< T, Allocator >::begin().
end() [1/2]
template<typename T , class Allocator = std::allocator<T>> iterator end ()
Referenced by DynArray< T, Allocator >::cend(), DynArray< T, Allocator >::DynArray(), DynArray< T, Allocator >::fill(), DynArray< T, Allocator >::rbegin(), and DynArray< T, Allocator >::rbegin().
end() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_iterator end () const
cend()
template<typename T , class Allocator = std::allocator<T>> const_iterator cend () const
References DynArray< T, Allocator >::end().
rbegin() [1/2]
template<typename T , class Allocator = std::allocator<T>> reverse_iterator rbegin ()
References DynArray< T, Allocator >::end().
Referenced by DynArray< T, Allocator >::crbegin().
rbegin() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_reverse_iterator rbegin () const
References DynArray< T, Allocator >::end().
crbegin()
template<typename T , class Allocator = std::allocator<T>> const_reverse_iterator crbegin () const
References DynArray< T, Allocator >::rbegin().
rend() [1/2]
template<typename T , class Allocator = std::allocator<T>> reverse_iterator rend ()
References DynArray< T, Allocator >::begin().
Referenced by DynArray< T, Allocator >::crend().
rend() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_reverse_iterator rend () const
References DynArray< T, Allocator >::begin().
crend()
template<typename T , class Allocator = std::allocator<T>> const_reverse_iterator crend () const
References DynArray< T, Allocator >::rend().
data() [1/2]
template<typename T , class Allocator = std::allocator<T>> pointer data ()
data() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_pointer data () const
operator[]() [1/2]
template<typename T , class Allocator = std::allocator<T>> reference operator[] (size_type i)
operator[]() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_reference operator[] (size_type i) const
at() [1/2]
template<typename T , class Allocator = std::allocator<T>> reference at (size_type i)
at() [2/2]
template<typename T , class Allocator = std::allocator<T>> const_reference at (size_type i) const
front() [1/2]
template<typename T , class A > DynArray< T, A >::reference front ()
front() [2/2]
template<typename T , class A > DynArray< T, A >::const_reference front () const
back() [1/2]
template<typename T , class A > DynArray< T, A >::reference back ()
back() [2/2]
template<typename T , class A > DynArray< T, A >::const_reference back () const
fill()
template<typename T , class Allocator = std::allocator<T>> void fill (const value_type & val)
References DynArray< T, Allocator >::begin(), and DynArray< T, Allocator >::end().
size()
template<typename T , class Allocator = std::allocator<T>> std::size_t size () const
empty()
template<typename T , class Allocator = std::allocator<T>> bool empty () const
reset()
template<typename T , class A > void reset (std::size_t n)
The documentation for this class was generated from the following file:
dyn_array.h