sst-cpputils: RingBufferInternal< N, MemoryOrder > Class Template Reference
RingBufferInternal< N, MemoryOrder > Class Template Reference
#include <ring_buffer.h>
Public Member Functions
RingBufferInternal ()
void clear ()
bool empty ()
std::size_t size ()
void subscribe ()
void unsubscribe ()
bool subscribed () const
Protected Member Functions
std::size_t mask (std::size_t val)
std::pair< std::size_t, std::size_t > prepareToRead (std::size_t count) const
std::tuple< std::size_t, std::size_t, std::size_t > prepareToWrite (std::size_t count) const
Protected Attributes
std::atomic_bool subscribed_
std::atomic_size_t writePos_
std::size_t readPos_
Constructor & Destructor Documentation
RingBufferInternal()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> RingBufferInternal ()
Member Function Documentation
clear()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> void clear ()
References RingBufferInternal< N, MemoryOrder >::readPos_, and RingBufferInternal< N, MemoryOrder >::writePos_.
empty()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> bool empty ()
References RingBufferInternal< N, MemoryOrder >::readPos_, and RingBufferInternal< N, MemoryOrder >::writePos_.
size()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::size_t size ()
References RingBufferInternal< N, MemoryOrder >::mask(), RingBufferInternal< N, MemoryOrder >::readPos_, and RingBufferInternal< N, MemoryOrder >::writePos_.
subscribe()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> void subscribe ()
References RingBufferInternal< N, MemoryOrder >::subscribed_.
unsubscribe()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> void unsubscribe ()
References RingBufferInternal< N, MemoryOrder >::subscribed_.
subscribed()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> bool subscribed () const
References RingBufferInternal< N, MemoryOrder >::subscribed_.
mask()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::size_t mask (std::size_t val) protected
Referenced by SimpleRingBuffer< T, N, MemoryOrder >::pop(), StereoRingBuffer< T, N, MemoryOrder >::pop(), SimpleRingBuffer< T, N, MemoryOrder >::popall(), StereoRingBuffer< T, N, MemoryOrder >::popall(), SimpleRingBuffer< T, N, MemoryOrder >::push(), StereoRingBuffer< T, N, MemoryOrder >::push(), SimpleRingBuffer< T, N, MemoryOrder >::push(), StereoRingBuffer< T, N, MemoryOrder >::push(), and RingBufferInternal< N, MemoryOrder >::size().
prepareToRead()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::pair< std::size_t, std::size_t > prepareToRead (std::size_t count) const protected
References RingBufferInternal< N, MemoryOrder >::readPos_.
Referenced by SimpleRingBuffer< T, N, MemoryOrder >::popall(), and StereoRingBuffer< T, N, MemoryOrder >::popall().
prepareToWrite()
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::tuple< std::size_t, std::size_t, std::size_t > prepareToWrite (std::size_t count) const protected
References RingBufferInternal< N, MemoryOrder >::writePos_.
Referenced by SimpleRingBuffer< T, N, MemoryOrder >::push(), and StereoRingBuffer< T, N, MemoryOrder >::push().
Member Data Documentation
subscribed_
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::atomic_bool subscribed_ protected
Referenced by RingBufferInternal< N, MemoryOrder >::subscribe(), RingBufferInternal< N, MemoryOrder >::subscribed(), and RingBufferInternal< N, MemoryOrder >::unsubscribe().
writePos_
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::atomic_size_t writePos_ protected
Referenced by RingBufferInternal< N, MemoryOrder >::clear(), RingBufferInternal< N, MemoryOrder >::empty(), SimpleRingBuffer< T, N, MemoryOrder >::pop(), StereoRingBuffer< T, N, MemoryOrder >::pop(), SimpleRingBuffer< T, N, MemoryOrder >::popall(), StereoRingBuffer< T, N, MemoryOrder >::popall(), RingBufferInternal< N, MemoryOrder >::prepareToWrite(), SimpleRingBuffer< T, N, MemoryOrder >::push(), StereoRingBuffer< T, N, MemoryOrder >::push(), SimpleRingBuffer< T, N, MemoryOrder >::push(), StereoRingBuffer< T, N, MemoryOrder >::push(), and RingBufferInternal< N, MemoryOrder >::size().
readPos_
template<int N, std::memory_order MemoryOrder = std::memory_order_relaxed> std::size_t readPos_ protected
Referenced by RingBufferInternal< N, MemoryOrder >::clear(), RingBufferInternal< N, MemoryOrder >::empty(), SimpleRingBuffer< T, N, MemoryOrder >::pop(), StereoRingBuffer< T, N, MemoryOrder >::pop(), SimpleRingBuffer< T, N, MemoryOrder >::popall(), StereoRingBuffer< T, N, MemoryOrder >::popall(), RingBufferInternal< N, MemoryOrder >::prepareToRead(), and RingBufferInternal< N, MemoryOrder >::size().
The documentation for this class was generated from the following file:
ring_buffer.h