sst-cpputils: SmallHashMap< K, V, InlineCap, Hash > Class Template Reference
SmallHashMap< K, V, InlineCap, Hash > Class Template Reference
#include <small_hash_map.h>
Classes
struct iter_t
Public Types
using iterator = iter_t< false >
using const_iterator = iter_t< true >
Public Member Functions
SmallHashMap ()=default
~SmallHashMap ()
SmallHashMap (const SmallHashMap &o)
SmallHashMap (SmallHashMap &&o) noexcept
SmallHashMap & operator= (const SmallHashMap &o)
SmallHashMap & operator= (SmallHashMap &&o) noexcept
bool empty () const
size_t size () const
size_t capacity () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator find (const K &k)
const_iterator find (const K &k) const
V & operator[] (const K &k)
V & at (const K &k)
const V & at (const K &k) const
void erase (iterator it)
void erase (const K &k)
void clear ()
Member Typedef Documentation
iterator
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> using iterator = iter_t<false>
const_iterator
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> using const_iterator = iter_t<true>
Constructor & Destructor Documentation
SmallHashMap() [1/3]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> SmallHashMap () default
~SmallHashMap()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> ~SmallHashMap ()
SmallHashMap() [2/3]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> SmallHashMap (const SmallHashMap< K, V, InlineCap, Hash > & o)
SmallHashMap() [3/3]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> SmallHashMap (SmallHashMap< K, V, InlineCap, Hash > && o) noexcept
Member Function Documentation
operator=() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> SmallHashMap & operator= (const SmallHashMap< K, V, InlineCap, Hash > & o)
operator=() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> SmallHashMap & operator= (SmallHashMap< K, V, InlineCap, Hash > && o) noexcept
empty()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> bool empty () const
size()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> size_t size () const
capacity()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> size_t capacity () const
begin() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> iterator begin ()
end() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> iterator end ()
Referenced by SmallHashMap< K, V, InlineCap, Hash >::at(), SmallHashMap< K, V, InlineCap, Hash >::at(), SmallHashMap< K, V, InlineCap, Hash >::erase(), SmallHashMap< K, V, InlineCap, Hash >::find(), and SmallHashMap< K, V, InlineCap, Hash >::find().
begin() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> const_iterator begin () const
end() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> const_iterator end () const
find() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> iterator find (const K & k)
References SmallHashMap< K, V, InlineCap, Hash >::end().
Referenced by SmallHashMap< K, V, InlineCap, Hash >::at(), SmallHashMap< K, V, InlineCap, Hash >::at(), and SmallHashMap< K, V, InlineCap, Hash >::erase().
find() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> const_iterator find (const K & k) const
References SmallHashMap< K, V, InlineCap, Hash >::end().
operator[]()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> V & operator[] (const K & k)
at() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> V & at (const K & k)
References SmallHashMap< K, V, InlineCap, Hash >::end(), and SmallHashMap< K, V, InlineCap, Hash >::find().
at() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> const V & at (const K & k) const
References SmallHashMap< K, V, InlineCap, Hash >::end(), and SmallHashMap< K, V, InlineCap, Hash >::find().
erase() [1/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> void erase (iterator it)
References SmallHashMap< K, V, InlineCap, Hash >::end(), and SmallHashMap< K, V, InlineCap, Hash >::iter_t< Const >::p.
erase() [2/2]
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> void erase (const K & k)
References SmallHashMap< K, V, InlineCap, Hash >::erase(), and SmallHashMap< K, V, InlineCap, Hash >::find().
Referenced by SmallHashMap< K, V, InlineCap, Hash >::erase().
clear()
template<typename K , typename V , size_t InlineCap, typename Hash = std::hash<K>> void clear ()
The documentation for this class was generated from the following file:
small_hash_map.h