sst-cpputils: sst::cpputils Namespace Reference
sst::cpputils Namespace Reference
Namespaces
namespace detail
namespace internal
Classes
struct active_set_overlay
active_set_overlay manages a small linked list of 'active' set items of type T which are pre-allocated.
struct fixed_memory_allocator_impl
template<typename T, int N> STLFixedAllocator provides an implementation of the stl Allocator protocol on a fixed array of size N.
class LRU
class SimpleRingBuffer
class StereoRingBuffer
Typedefs
template<typename T , int N>
using fixed_memory_allocator = typename std::allocator_traits< fixed_memory_allocator_impl< T, N > >::template rebind_alloc< T >
Functions
template<class ContainerType , class T >
constexpr bool contains (const ContainerType &container, const T &value)
Wrapper of std::find to check if a container contains a value.
template<class ContainerType , class UnaryPredicate >
constexpr bool contains_if (const ContainerType &container, UnaryPredicate q)
Wrapper of std::find_if to check if a container contains a value for which the predicate returns true.
template<class ContainerType , class UnaryPredicate >
constexpr void nodal_erase_if (ContainerType &container, UnaryPredicate q)
Similar to std::erase_if, but much easier to use for node-based containers (e.g.
template<typename Func , typename... Params>
auto bind_front (Func &&func, Params &&...frontParams)
Temporary replacement for std::bind_front, which is only available in C++20.
template<typename Func , typename... Params>
auto bind_back (Func &&func, Params &&...backParams)
Temporary replacement for std::bind_back, which is only available in C++23.
template<typename T , size_t N, typename... Args>
std::array< T, N > make_array (Args &&...args)
template<typename T , size_t N, typename... Args>
std::array< T, N > make_array_bind_last_index (Args &&...args)
template<typename T , size_t N, typename... Args>
std::array< T, N > make_array_bind_first_index (Args &&...args)
template<typename T , size_t N, typename Maker >
constexpr std::array< T, N > make_array_lambda (Maker &&maker)
Returns an array of size N, with each value initialized by calling the maker lambda with signature [] (size_t index) -> T.
template<typename T , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>()))>
constexpr auto enumerate (T &&iterable)
template<typename T , typename S , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>())), typename SIter = decltype(std::begin(std::declval<S>())), typename = decltype(std::end(std::declval<S>()))>
constexpr auto zip (T &&iterableT, S &&iterableS)
Typedef Documentation
fixed_memory_allocator
template<typename T , int N> using fixed_memory_allocator = typename std::allocator_traits<fixed_memory_allocator_impl<T, N> >::template rebind_alloc<T>
Function Documentation
contains()
template<class ContainerType , class T > constexpr bool contains (const ContainerType & container, const T & value) constexpr
Wrapper of std::find to check if a container contains a value.
contains_if()
template<class ContainerType , class UnaryPredicate > constexpr bool contains_if (const ContainerType & container, UnaryPredicate q) constexpr
Wrapper of std::find_if to check if a container contains a value for which the predicate returns true.
nodal_erase_if()
template<class ContainerType , class UnaryPredicate > constexpr void nodal_erase_if (ContainerType & container, UnaryPredicate q) constexpr
Similar to std::erase_if, but much easier to use for node-based containers (e.g.
std::map).
bind_front()
template<typename Func , typename... Params> auto bind_front (Func && func, Params &&... frontParams)
Temporary replacement for std::bind_front, which is only available in C++20.
bind_back()
template<typename Func , typename... Params> auto bind_back (Func && func, Params &&... backParams)
Temporary replacement for std::bind_back, which is only available in C++23.
make_array()
template<typename T , size_t N, typename... Args> std::array< T, N > make_array (Args &&... args)
References sst::cpputils::detail::make_array_helper().
make_array_bind_last_index()
template<typename T , size_t N, typename... Args> std::array< T, N > make_array_bind_last_index (Args &&... args)
References sst::cpputils::detail::make_array_helper().
make_array_bind_first_index()
template<typename T , size_t N, typename... Args> std::array< T, N > make_array_bind_first_index (Args &&... args)
References sst::cpputils::detail::make_array_helper().
make_array_lambda()
template<typename T , size_t N, typename Maker > constexpr std::array< T, N > make_array_lambda (Maker && maker) constexpr
Returns an array of size N, with each value initialized by calling the maker lambda with signature [] (size_t index) -> T.
References sst::cpputils::detail::make_array_helper().
enumerate()
template<typename T , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>()))> constexpr auto enumerate (T && iterable) constexpr
zip()
template<typename T , typename S , typename TIter = decltype(std::begin(std::declval<T>())), typename = decltype(std::end(std::declval<T>())), typename SIter = decltype(std::begin(std::declval<S>())), typename = decltype(std::end(std::declval<S>()))> constexpr auto zip (T && iterableT, S && iterableS) constexpr