sst-cpputils: active_set_overlay< T > Struct Template Reference
active_set_overlay< T > Struct Template Reference
active_set_overlay manages a small linked list of 'active' set items of type T which are pre-allocated.
#include <active_set_overlay.h>
Classes
struct iterator
struct participant
Public Member Functions
void addToActive (T &s)
void addToActive (T *s)
bool removeFromActive (T &s)
bool removeFromActive (T *s)
void removeAll ()
iterator begin () const
iterator end () const
iterator erase (const iterator &el)
Public Attributes
T * activeHead {nullptr}
size_t activeCount {0}
Detailed Description
template<typename T>
struct sst::cpputils::active_set_overlay< T >
active_set_overlay manages a small linked list of 'active' set items of type T which are pre-allocated.
Think voice, smoother, etc... all sitting in a std::array<T, N> where at any time only a small but non-contiguous subset of them is running.
It provides methods to add and remove to the active set and to traverse the active set using std iterator semantics.
There are a variety of ways to do this, but the way I did it here assumes the class T also contains utility pointers in itself called T* activeSetNext and activeSetPrev which are initialized to nullptr.
Member Function Documentation
addToActive() [1/2]
template<typename T > void addToActive (T & s)
References active_set_overlay< T >::addToActive().
Referenced by active_set_overlay< T >::addToActive().
addToActive() [2/2]
template<typename T > void addToActive (T * s)
References active_set_overlay< T >::activeCount, and active_set_overlay< T >::activeHead.
removeFromActive() [1/2]
template<typename T > bool removeFromActive (T & s)
References active_set_overlay< T >::removeFromActive().
Referenced by active_set_overlay< T >::erase(), active_set_overlay< T >::removeAll(), and active_set_overlay< T >::removeFromActive().
removeFromActive() [2/2]
template<typename T > bool removeFromActive (T * s)
References active_set_overlay< T >::activeCount, and active_set_overlay< T >::activeHead.
removeAll()
template<typename T > void removeAll ()
References active_set_overlay< T >::begin(), active_set_overlay< T >::end(), and active_set_overlay< T >::removeFromActive().
begin()
template<typename T > iterator begin () const
References active_set_overlay< T >::activeHead.
Referenced by active_set_overlay< T >::removeAll().
end()
template<typename T > iterator end () const
Referenced by active_set_overlay< T >::removeAll().
erase()
template<typename T > iterator erase (const iterator & el)
References active_set_overlay< T >::removeFromActive().
Member Data Documentation
activeHead
template<typename T > T* activeHead {nullptr}
Referenced by active_set_overlay< T >::addToActive(), active_set_overlay< T >::begin(), and active_set_overlay< T >::removeFromActive().
activeCount
template<typename T > size_t activeCount {0}
Referenced by active_set_overlay< T >::addToActive(), and active_set_overlay< T >::removeFromActive().
The documentation for this struct was generated from the following file:
active_set_overlay.h