sst-filters: GeneratorWrapper< T > Class Template Reference
GeneratorWrapper< T > Class Template Reference final
#include <catch2.hpp>
Public Member Functions
GeneratorWrapper (std::unique_ptr< IGenerator< T > > generator)
T const & get () const
bool next ()
Constructor & Destructor Documentation
GeneratorWrapper()
template<typename T > GeneratorWrapper (std::unique_ptr< IGenerator< T > > generator)
Member Function Documentation
get()
template<typename T > T const & get () const
Referenced by ChunkGenerator< T >::ChunkGenerator(), FilterGenerator< T, Predicate >::FilterGenerator(), TakeGenerator< T >::get(), FilterGenerator< T, Predicate >::get(), RepeatGenerator< T >::get(), FilterGenerator< T, Predicate >::next(), MapGenerator< T, U, Func >::next(), and ChunkGenerator< T >::next().
next()
template<typename T > bool next ()
Referenced by ChunkGenerator< T >::ChunkGenerator(), TakeGenerator< T >::next(), FilterGenerator< T, Predicate >::next(), RepeatGenerator< T >::next(), MapGenerator< T, U, Func >::next(), and ChunkGenerator< T >::next().
The documentation for this class was generated from the following file:
catch2.hpp