sst-filters: FilterCoefficientMaker< TuningProvider > Class Template Reference
FilterCoefficientMaker< TuningProvider > Class Template Reference
Class for creating filter coefficients.
#include <FilterCoefficientMaker.h>
Public Member Functions
FilterCoefficientMaker ()
Default constructor.
void setSampleRateAndBlockSize (float newSampleRate, int newBlockSize)
Sets the sample rate and block size to use for processing the filters.
void Reset ()
Resets the coefficients to zero, and the tuning provider to nullptr.
void FromDirect (const float(&N)[n_cm_coeffs])
Creates filter coefficients directly from an array.
void MakeCoeffs (float Freq, float Reso, FilterType Type, FilterSubType SubType, TuningProvider *provider, bool tuningAdjusted, float extra=0.f, float extra2=0.f, float extra3=0.f)
Creates filter coefficients for a given set of filter parameters.
template<typename StateType >
void updateState (StateType &state, int channel=-1)
Update the coefficients in a filter state.
template<typename StateType >
void updateCoefficients (StateType &state, int channel=0)
Update the local coefficients with the coefficients from the filter state.
Static Public Member Functions
static float provider_note_to_pitch (TuningProvider *provider, float note)
static float provider_note_to_pitch_ignoring_tuning (TuningProvider *provider, float note)
static float provider_note_to_pitch_inv_ignoring_tuning (TuningProvider *provider, float note)
static void provider_note_to_omega_ignoring_tuning (TuningProvider *provider, float x, float &sinu, float &cosi, float sampleRate)
Public Attributes
float C [n_cm_coeffs] {}
Current filter coefficients.
float dC [n_cm_coeffs] {}
Filter coefficients "delta" to update current coefficients.
float tC [n_cm_coeffs] {}
"Target" filter coefficients
Detailed Description
template<typename TuningProvider = detail::BasicTuningProvider>
class sst::filters::FilterCoefficientMaker< TuningProvider >
Class for creating filter coefficients.
Template Parameters
TuningProvider A 12-TET tuning provider is used by default, but if you would like to support other tunings, you should use a custom tuning provider.
Constructor & Destructor Documentation
FilterCoefficientMaker()
template<typename TuningProvider > FilterCoefficientMaker ()
Default constructor.
Member Function Documentation
setSampleRateAndBlockSize()
template<typename TuningProvider > void setSampleRateAndBlockSize (float newSampleRate, int newBlockSize)
Sets the sample rate and block size to use for processing the filters.
Reset()
template<typename TuningProvider > void Reset ()
Resets the coefficients to zero, and the tuning provider to nullptr.
References sst::filters::n_cm_coeffs.
FromDirect()
template<typename TuningProvider > void FromDirect (const float(&) N[n_cm_coeffs])
Creates filter coefficients directly from an array.
References N, sst::filters::n_cm_coeffs, and sst::filters::smooth.
Referenced by sst::filters::K35Filter::makeCoefficients(), sst::filters::VintageLadder::RK::makeCoefficients(), sst::filters::VintageLadder::Huov::makeCoefficients(), sst::filters::DiodeLadderFilter::makeCoefficients(), sst::filters::ResonanceWarp::makeCoefficients(), sst::filters::CutoffWarp::makeCoefficients(), sst::filters::TriPoleFilter::makeCoefficients(), and sst::filters::OBXDFilter::makeCoefficients().
MakeCoeffs()
template<typename TuningProvider > void MakeCoeffs (float Freq, float Reso, FilterType Type, FilterSubType SubType, TuningProvider * provider, bool tuningAdjusted, float extra = 0.f, float extra2 = 0.f, float extra3 = 0.f)
Creates filter coefficients for a given set of filter parameters.
Note that frequency is expected in units of MIDI note number, with A440 = 0.
References sst::filters::OBXDFilter::FOUR_POLE, sst::filters::fut_apf, sst::filters::fut_bp12, sst::filters::fut_bp24, sst::filters::fut_comb_neg, sst::filters::fut_comb_pos, sst::filters::fut_cutoffwarp_ap, sst::filters::fut_cutoffwarp_bp, sst::filters::fut_cutoffwarp_hp, sst::filters::fut_cutoffwarp_lp, sst::filters::fut_cutoffwarp_n, sst::filters::fut_diode, sst::filters::fut_hp12, sst::filters::fut_hp24, sst::filters::fut_k35_hp, sst::filters::fut_k35_lp, sst::filters::fut_k35_saturations, sst::filters::fut_lp12, sst::filters::fut_lp24, sst::filters::fut_lpmoog, sst::filters::fut_none, sst::filters::fut_notch12, sst::filters::fut_notch24, sst::filters::fut_obxd_2pole_bp, sst::filters::fut_obxd_2pole_hp, sst::filters::fut_obxd_2pole_lp, sst::filters::fut_obxd_2pole_n, sst::filters::fut_obxd_4pole, sst::filters::fut_resonancewarp_ap, sst::filters::fut_resonancewarp_bp, sst::filters::fut_resonancewarp_hp, sst::filters::fut_resonancewarp_lp, sst::filters::fut_resonancewarp_n, sst::filters::fut_SNH, sst::filters::fut_tripole, sst::filters::fut_vintageladder, sst::filters::K35Filter::makeCoefficients(), sst::filters::VintageLadder::RK::makeCoefficients(), sst::filters::VintageLadder::Huov::makeCoefficients(), sst::filters::DiodeLadderFilter::makeCoefficients(), sst::filters::ResonanceWarp::makeCoefficients(), sst::filters::CutoffWarp::makeCoefficients(), sst::filters::TriPoleFilter::makeCoefficients(), sst::filters::OBXDFilter::makeCoefficients(), sst::filters::num_filter_types, sst::filters::st_bp12_LegacyClean, sst::filters::st_bp12_LegacyDriven, sst::filters::st_Clean, sst::filters::st_Driven, sst::filters::st_obxd4pole_broken24db, sst::filters::st_obxd4pole_morph, sst::filters::st_Standard, sst::filters::st_vintage_type1, sst::filters::st_vintage_type1_compensated, sst::filters::st_vintage_type2, sst::filters::st_vintage_type2_compensated, and sst::filters::OBXDFilter::TWO_POLE.
updateState()
template<typename TuningProvider > template<typename StateType > void updateState (StateType & state, int channel = -1)
Update the coefficients in a filter state.
To update the coefficients for a single channel, pass a channel index to the channel argument, otherwise the same coefficients will be used for all channels.
References sst::filters::n_cm_coeffs, and sst::filters::detail::set1f().
updateCoefficients()
template<typename TuningProvider > template<typename StateType > void updateCoefficients (StateType & state, int channel = 0)
Update the local coefficients with the coefficients from the filter state.
This is necessary since the filter state is responsible for smoothing the filter coefficients.
References sst::filters::detail::get1f(), and sst::filters::n_cm_coeffs.
provider_note_to_pitch()
template<typename TuningProvider > float provider_note_to_pitch (TuningProvider * provider, float note) static
provider_note_to_pitch_ignoring_tuning()
template<typename TuningProvider > float provider_note_to_pitch_ignoring_tuning (TuningProvider * provider, float note) static
Referenced by sst::filters::VintageLadder::Common::clampedFrequency().
provider_note_to_pitch_inv_ignoring_tuning()
template<typename TuningProvider > float provider_note_to_pitch_inv_ignoring_tuning (TuningProvider * provider, float note) static
provider_note_to_omega_ignoring_tuning()
template<typename TuningProvider > void provider_note_to_omega_ignoring_tuning (TuningProvider * provider, float x, float & sinu, float & cosi, float sampleRate) static
Member Data Documentation
C
template<typename TuningProvider = detail::BasicTuningProvider> float C[n_cm_coeffs] {}
Current filter coefficients.
dC
template<typename TuningProvider = detail::BasicTuningProvider> float dC[n_cm_coeffs] {}
Filter coefficients "delta" to update current coefficients.
tC
template<typename TuningProvider = detail::BasicTuningProvider> float tC[n_cm_coeffs] {}
"Target" filter coefficients
The documentation for this class was generated from the following files:
FilterCoefficientMaker.h
FilterCoefficientMaker_Impl.h