sst-filters: FilterGenerator< T, Predicate > Class Template Reference
FilterGenerator< T, Predicate > Class Template Reference
Public Member Functions
template<typename P = Predicate>
FilterGenerator (P &&pred, GeneratorWrapper< T > &&generator)
T const & get () const override
bool next () override
Public Member Functions inherited from IGenerator< T >
virtual ~IGenerator ()=default
Public Member Functions inherited from GeneratorUntypedBase
GeneratorUntypedBase ()=default
virtual ~GeneratorUntypedBase ()
Additional Inherited Members
Public Types inherited from IGenerator< T >
using type = T
Constructor & Destructor Documentation
FilterGenerator()
FilterGenerator (P && pred, GeneratorWrapper< T > && generator)
References GeneratorWrapper< T >::get(), and Catch::throw_exception().
Member Function Documentation
get()
T const& get () const override virtual
Implements IGenerator< T >.
References GeneratorWrapper< T >::get().
next()
bool next () override virtual
Implements GeneratorUntypedBase.
References GeneratorWrapper< T >::get(), and GeneratorWrapper< T >::next().
The documentation for this class was generated from the following file:
catch2.hpp