sst-filters: ReusableStringStream Class Reference
ReusableStringStream Class Reference
#include <catch2.hpp>
Public Member Functions
ReusableStringStream ()
~ReusableStringStream ()
auto str () const -> std::string
template<typename T >
auto operator<< (T const &value) -> ReusableStringStream &
auto get () -> std::ostream &
Constructor & Destructor Documentation
ReusableStringStream()
ReusableStringStream ()
~ReusableStringStream()
~ReusableStringStream ()
Member Function Documentation
str()
auto str () const -> std::string
Referenced by StringMaker< T, typename >::convert(), Catch::Detail::rangeToString(), and Catch::rangeToString().
operator<<()
template<typename T > auto operator<< (T const & value) -> ReusableStringStream&
get()
auto get () -> std::ostream&
The documentation for this class was generated from the following file:
catch2.hpp