sst-filters: Butterworth< N, Type > Class Template Reference
Butterworth< N, Type > Class Template Reference
Cascaded TPT state-variable Butterworth filter, even orders only.
#include <ButterworthLPHP.h>
Public Member Functions
Butterworth ()=default
void setCutoffAndSampleRate (float cutoffHz, float sampleRate)
float processSample (float x)
void processBlock (float *data, int numSamples)
void processBlock (const float *in, float *out, int numSamples)
void processSample (float &l, float &r)
void processBlock (float *left, float *right, int numSamples)
void reset ()
Detailed Description
template<int N, ButterworthType Type>
class sst::filters::Butterworth< N, Type >
Cascaded TPT state-variable Butterworth filter, even orders only.
N is the filter order (poles); attenuation is N*6 dB/oct.
Constructor & Destructor Documentation
Butterworth()
template<int N, ButterworthType Type> Butterworth () default
Member Function Documentation
setCutoffAndSampleRate()
template<int N, ButterworthType Type> void setCutoffAndSampleRate (float cutoffHz, float sampleRate)
processSample() [1/2]
template<int N, ButterworthType Type> float processSample (float x)
Referenced by Butterworth< N, Type >::processBlock(), Butterworth< N, Type >::processBlock(), and Butterworth< N, Type >::processBlock().
processBlock() [1/3]
template<int N, ButterworthType Type> void processBlock (float * data, int numSamples)
References Butterworth< N, Type >::processSample().
processBlock() [2/3]
template<int N, ButterworthType Type> void processBlock (const float * in, float * out, int numSamples)
References Butterworth< N, Type >::processSample().
processSample() [2/2]
template<int N, ButterworthType Type> void processSample (float & l, float & r)
processBlock() [3/3]
template<int N, ButterworthType Type> void processBlock (float * left, float * right, int numSamples)
References Butterworth< N, Type >::processSample().
reset()
template<int N, ButterworthType Type> void reset ()
The documentation for this class was generated from the following file:
ButterworthLPHP.h