sst-filters: AssertionHandler Class Reference
AssertionHandler Class Reference
#include <catch2.hpp>
Public Member Functions
AssertionHandler (StringRef const &macroName, SourceLineInfo const &lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler ()
template<typename T >
void handleExpr (ExprLhs< T > const &expr)
void handleExpr (ITransientExpression const &expr)
void handleMessage (ResultWas::OfType resultType, StringRef const &message)
void handleExceptionThrownAsExpected ()
void handleUnexpectedExceptionNotThrown ()
void handleExceptionNotThrownAsExpected ()
void handleThrowingCallSkipped ()
void handleUnexpectedInflightException ()
void complete ()
void setCompleted ()
auto allowThrows () const -> bool
Constructor & Destructor Documentation
AssertionHandler()
AssertionHandler (StringRef const & macroName, SourceLineInfo const & lineInfo, StringRef capturedExpression, ResultDisposition::Flags resultDisposition)
~AssertionHandler()
~AssertionHandler ()
References IResultCapture::handleIncomplete().
Member Function Documentation
handleExpr() [1/2]
template<typename T > void handleExpr (ExprLhs< T > const & expr)
References AssertionHandler::handleExpr(), and ExprLhs< LhsT >::makeUnaryExpr().
Referenced by AssertionHandler::handleExpr().
handleExpr() [2/2]
void handleExpr (ITransientExpression const & expr)
handleMessage()
void handleMessage (ResultWas::OfType resultType, StringRef const & message)
handleExceptionThrownAsExpected()
void handleExceptionThrownAsExpected ()
handleUnexpectedExceptionNotThrown()
void handleUnexpectedExceptionNotThrown ()
handleExceptionNotThrownAsExpected()
void handleExceptionNotThrownAsExpected ()
handleThrowingCallSkipped()
void handleThrowingCallSkipped ()
handleUnexpectedInflightException()
void handleUnexpectedInflightException ()
complete()
void complete ()
setCompleted()
void setCompleted ()
allowThrows()
auto allowThrows () const -> bool
The documentation for this class was generated from the following file:
catch2.hpp