sst-filters: ChunkGenerator< T > Class Template Reference
ChunkGenerator< T > Class Template Reference final
#include <catch2.hpp>
Public Member Functions
ChunkGenerator (size_t size, GeneratorWrapper< T > generator)
std::vector< T > const & get () const override
bool next () override
Public Member Functions inherited from IGenerator< std::vector< T > >
virtual ~IGenerator ()=default
Public Member Functions inherited from GeneratorUntypedBase
GeneratorUntypedBase ()=default
virtual ~GeneratorUntypedBase ()
Additional Inherited Members
Public Types inherited from IGenerator< std::vector< T > >
using type = std::vector< T >
Constructor & Destructor Documentation
ChunkGenerator()
template<typename T > ChunkGenerator (size_t size, GeneratorWrapper< T > generator)
References GeneratorWrapper< T >::get(), GeneratorWrapper< T >::next(), and Catch::throw_exception().
Member Function Documentation
get()
template<typename T > std::vector< T > const & get () const override virtual
Implements IGenerator< std::vector< T > >.
next()
template<typename T > bool next () override virtual
Implements GeneratorUntypedBase.
References GeneratorWrapper< T >::get(), and GeneratorWrapper< T >::next().
The documentation for this class was generated from the following file:
catch2.hpp