sst-filters: HalfRateFilter Class Reference
HalfRateFilter Class Reference
#include <HalfRateFilter.h>
Public Member Functions
HalfRateFilter (uint32_t M, bool steep)
Implement a half rate up/down filter.
void process_block (float *floatL, float *floatR, int nsamples)
void process_block_D2 (float *floatL, float *floatR, int nsamples, float *outL=0, float *outR=0)
template<bool factorOfTwo>
void process_block_U2_impl (float *floatL_in, float *floatR_in, float *floatL, float *floatR, int nsamples)
void process_block_U2 (float *floatL_in, float *floatR_in, float *floatL, float *floatR, int nsamples)
The original surge half rate filter when upsampling cut amplitude by 2.
void process_block_U2_fullscale (float *floatL_in, float *floatR_in, float *floatL, float *floatR, int nsamples)
void process_sample_U2 (float L, float R, float Lout[2], float Rout[2])
void process_sample_D2 (float L[2], float R[2], float &outL, float &outR)
void load_coefficients ()
void set_coefficients (float *cA, float *cB)
void reset ()
Constructor & Destructor Documentation
HalfRateFilter()
HalfRateFilter (uint32_t M, bool steep)
Implement a half rate up/down filter.
Parameters
M The size of the FIR. Range from 1 to halfrate_max_M
steep Steepness. Set false for softer slopes, more attenuation and less stopband ripple
References HalfRateFilter::load_coefficients(), M, and HalfRateFilter::reset().
Member Function Documentation
process_block()
void process_block (float * floatL, float * floatR, int nsamples)
References L, and N.
process_block_D2()
void process_block_D2 (float * floatL, float * floatR, int nsamples, float * outL = 0, float * outR = 0)
References L.
process_block_U2_impl()
template<bool factorOfTwo> void process_block_U2_impl (float * floatL_in, float * floatR_in, float * floatL, float * floatR, int nsamples)
References L.
process_block_U2()
void process_block_U2 (float * floatL_in, float * floatR_in, float * floatL, float * floatR, int nsamples)
The original surge half rate filter when upsampling cut amplitude by 2.
Dont know why. But its annoying. So provide that to not break clients and provide one which doesnt (the _fullscale) in case you dont want that
process_block_U2_fullscale()
void process_block_U2_fullscale (float * floatL_in, float * floatR_in, float * floatL, float * floatR, int nsamples)
process_sample_U2()
void process_sample_U2 (float L, float R, float Lout[2], float Rout[2])
References L.
process_sample_D2()
void process_sample_D2 (float L[2], float R[2], float & outL, float & outR)
References L.
load_coefficients()
void load_coefficients ()
References M, and HalfRateFilter::set_coefficients().
Referenced by HalfRateFilter::HalfRateFilter().
set_coefficients()
void set_coefficients (float * cA, float * cB)
Referenced by HalfRateFilter::load_coefficients().
reset()
void reset ()
Referenced by HalfRateFilter::HalfRateFilter().
The documentation for this class was generated from the following file:
HalfRateFilter.h