sst-filters: sst::filters::CutoffWarp Namespace Reference
sst::filters::CutoffWarp Namespace Reference
This namespace contains an adaptation of the filter found at https://ccrma.stanford.edu/~jatin/ComplexNonlinearities/NLFeedback.html with coefficient calculation from https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html.
Enumerations
enum Saturator { SAT_TANH = 0, SAT_SOFT, SAT_OJD, SAT_SINE }
enum nlf_coeffs {
nlf_a1 = 0, nlf_a2, nlf_b0, nlf_b1,
nlf_b2, nlf_makeup, n_nlf_coeff
}
enum dlf_state {
nlf_z1, nlf_z2, nlf_z3, nlf_z4,
nlf_z5, nlf_z6, nlf_z7, nlf_z8
}
Functions
template<typename TuningProvider >
void makeCoefficients (FilterCoefficientMaker< TuningProvider > *cm, float freq, float reso, int type, int subtype, float sampleRate, TuningProvider *provider)
template<FilterSubType subtype>
__m128 process (QuadFilterUnitState *__restrict f, __m128 input)
Detailed Description
This namespace contains an adaptation of the filter found at https://ccrma.stanford.edu/~jatin/ComplexNonlinearities/NLFeedback.html with coefficient calculation from https://webaudio.github.io/Audio-EQ-Cookbook/audio-eq-cookbook.html.
Enumeration Type Documentation
Saturator
enum Saturator
Enumerator
SAT_TANH
SAT_SOFT
SAT_OJD
SAT_SINE
nlf_coeffs
enum nlf_coeffs
Enumerator
nlf_a1
nlf_a2
nlf_b0
nlf_b1
nlf_b2
nlf_makeup
n_nlf_coeff
dlf_state
enum dlf_state
Enumerator
nlf_z1
nlf_z2
nlf_z3
nlf_z4
nlf_z5
nlf_z6
nlf_z7
nlf_z8
Function Documentation
makeCoefficients()
void sst::filters::CutoffWarp::makeCoefficients (FilterCoefficientMaker< TuningProvider > * cm, float freq, float reso, int type, int subtype, float sampleRate, TuningProvider * provider)
References sst::filters::TriPoleFilter::ResWaveshaper::alpha, C, sst::filters::utilities::DSP::fastcos(), sst::filters::utilities::DSP::fastsin(), FilterCoefficientMaker< TuningProvider >::FromDirect(), sst::filters::fut_cutoffwarp_bp, sst::filters::fut_cutoffwarp_hp, sst::filters::fut_cutoffwarp_lp, sst::filters::fut_cutoffwarp_n, sst::filters::utilities::limit_range(), sst::filters::n_cm_coeffs, nlf_a1, nlf_a2, nlf_b0, nlf_b1, nlf_b2, and nlf_makeup.
Referenced by FilterCoefficientMaker< TuningProvider >::MakeCoeffs().
process()
__m128 sst::filters::CutoffWarp::process (QuadFilterUnitState *__restrict f, __m128 input)
References A, n_nlf_coeff, nlf_a1, nlf_a2, nlf_b0, nlf_b1, nlf_b2, nlf_makeup, nlf_z1, and nlf_z2.