sst-filters: sst::filters::VintageLadder::Huov Namespace Reference
sst::filters::VintageLadder::Huov Namespace Reference
Enumerations
enum huov_coeffs {
h_cutoff = 0, h_res, h_fc, h_gComp,
n_hcoeffs
}
enum huov_regoffsets { h_stage = 0, h_stageTanh = 4, h_delay = 7 }
Functions
template<typename TuningProvider >
void makeCoefficients (FilterCoefficientMaker< TuningProvider > *cm, float freq, float reso, float sampleRate, float sampleRateInv, bool applyGainCompensation, TuningProvider *provider)
__m128 process (QuadFilterUnitState *__restrict f, __m128 in)
Enumeration Type Documentation
huov_coeffs
enum huov_coeffs
Enumerator
h_cutoff
h_res
h_fc
h_gComp
n_hcoeffs
huov_regoffsets
enum huov_regoffsets
Enumerator
h_stage
h_stageTanh
h_delay
Function Documentation
makeCoefficients()
void sst::filters::VintageLadder::Huov::makeCoefficients (FilterCoefficientMaker< TuningProvider > * cm, float freq, float reso, float sampleRate, float sampleRateInv, bool applyGainCompensation, TuningProvider * provider)
References sst::filters::VintageLadder::Common::clampedFrequency(), FilterCoefficientMaker< TuningProvider >::FromDirect(), h_cutoff, h_fc, h_gComp, h_res, sst::filters::utilities::limit_range(), and sst::filters::n_cm_coeffs.
Referenced by FilterCoefficientMaker< TuningProvider >::MakeCoeffs().
process()
__m128 sst::filters::VintageLadder::Huov::process (QuadFilterUnitState *__restrict f, __m128 in)
References A, F, sst::filters::utilities::DSP::fastexpSSE(), sst::filters::utilities::DSP::fasttanhSSEclamped(), h_delay, h_fc, h_gComp, h_res, h_stage, h_stageTanh, M, n_hcoeffs, sst::filters::OBXDFilter::one, and S.
Referenced by sst::filters::GetQFPtrFilterUnit().