sst-filters: Catch::Detail Namespace Reference
Catch::Detail Namespace Reference
Classes
struct EnumInfo
class IsStreamInsertable
class Approx
Functions
std::string rawMemoryToString (const void *object, std::size_t size)
template<typename T >
std::string rawMemoryToString (const T &object)
template<typename E >
std::string convertUnknownEnumToString (E e)
template<typename T >
std::enable_if< !std::is_enum< T >::value &&!std::is_base_of< std::exception, T >::value, std::string >::type convertUnstreamable (T const &)
template<typename T >
std::enable_if< !std::is_enum< T >::value &&std::is_base_of< std::exception, T >::value, std::string >::type convertUnstreamable (T const &ex)
template<typename T >
std::enable_if< std::is_enum< T >::value, std::string >::type convertUnstreamable (T const &value)
template<typename T >
std::string stringify (const T &e)
template<typename InputIterator , typename Sentinel = InputIterator>
std::string rangeToString (InputIterator first, Sentinel last)
Variables
const std::string unprintableString
Function Documentation
rawMemoryToString() [1/2]
std::string Catch::Detail::rawMemoryToString (const void * object, std::size_t size)
Referenced by rawMemoryToString().
rawMemoryToString() [2/2]
std::string Catch::Detail::rawMemoryToString (const T & object)
References rawMemoryToString().
Referenced by StringMaker< R C::* >::convert(), and StringMaker< T * >::convert().
convertUnknownEnumToString()
std::string convertUnknownEnumToString (E e)
References stringify().
Referenced by convertUnstreamable().
convertUnstreamable() [1/3]
std::enable_if< !std::is_enum<T>::value && !std::is_base_of<std::exception, T>::value, std::string>::type Catch::Detail::convertUnstreamable (T const &)
References unprintableString.
Referenced by StringMaker< T, typename >::convert().
convertUnstreamable() [2/3]
std::enable_if< !std::is_enum<T>::value && std::is_base_of<std::exception, T>::value, std::string>::type Catch::Detail::convertUnstreamable (T const & ex)
convertUnstreamable() [3/3]
std::enable_if< std::is_enum<T>::value , std::string>::type Catch::Detail::convertUnstreamable (T const & value)
References convertUnknownEnumToString(), and Catch::Generators::value().
stringify()
std::string Catch::Detail::stringify (const T & e)
Referenced by Capturer::captureValues(), StringMaker< char[SZ]>::convert(), StringMaker< signed char[SZ]>::convert(), StringMaker< unsigned char[SZ]>::convert(), convertUnknownEnumToString(), ContainsElementMatcher< T, Alloc >::describe(), ContainsMatcher< T, AllocComp, AllocMatch >::describe(), EqualsMatcher< T, AllocComp, AllocMatch >::describe(), ApproxMatcher< T, AllocComp, AllocMatch >::describe(), UnorderedEqualsMatcher< T, AllocComp, AllocMatch >::describe(), rangeToString(), Catch::rangeToString(), and MatchExpr< ArgT, MatcherT >::streamReconstructedExpression().
rangeToString()
std::string Catch::Detail::rangeToString (InputIterator first, Sentinel last)
References ReusableStringStream::str(), and stringify().
Variable Documentation
unprintableString
const std::string unprintableString extern
Referenced by convertUnstreamable(), and MatchExpr< ArgT, MatcherT >::streamReconstructedExpression().