sst-filters: sst::filtersplusplus::details Namespace Reference
sst::filtersplusplus::details Namespace Reference
Classes
struct FilterPayload
Functions
bool mcequal (const ModelConfig &mc)
template<is_modelconfig_enum T, typename... Args>
requires (is_modelconfig_enum<Args> && ...)
bool mcequal (const ModelConfig &mc, T val, Args... rest_args)
template<is_modelconfig_enum T, typename... Args>
requires (is_modelconfig_enum<Args> && ...)
std::vector< std::pair< T, bool > > vavpc (const FilterModel &fm, Args... cstr)
template<is_modelconfig_enum T, typename... Args>
requires (is_modelconfig_enum<Args> && ...)
std::vector< T > vapc (const FilterModel &fm, Args... cstr)
Function Documentation
mcequal() [1/2]
bool mcequal (const ModelConfig & mc)
Referenced by sst::filtersplusplus::isPartialMatch(), mcequal(), and vavpc().
mcequal() [2/2]
template<is_modelconfig_enum T, typename... Args> requires (is_modelconfig_enum<Args> && ...) bool mcequal (const ModelConfig & mc, T val, Args... rest_args)
References mcequal().
vavpc()
template<is_modelconfig_enum T, typename... Args> requires (is_modelconfig_enum<Args> && ...) std::vector< std::pair< T, bool > > vavpc (const FilterModel & fm, Args... cstr)
References Filter::availableModelConfigurations(), and mcequal().
vapc()
template<is_modelconfig_enum T, typename... Args> requires (is_modelconfig_enum<Args> && ...) std::vector< T > vapc (const FilterModel & fm, Args... cstr)