sst-filters: sst::filters::VintageLadder::Huov2010 Namespace Reference
sst::filters::VintageLadder::Huov2010 Namespace Reference
Enumerations
enum coeff { h_gres = 1 , h_gonepole = 2 , h_gcomp = 3 , n_hcoeffs }
enum reg { h_onepole_in = 0 , h_onepole_out = 4 , h_delayLine = 9 }
Functions
template<typename TuningProvider >
void makeCoefficients (FilterCoefficientMaker< TuningProvider > *cm, float freq, float reso, float sampleRate, float sampleRateInv, bool applyGainCompensation, TuningProvider *provider)
SIMD_M128 nonlin (SIMD_M128 in)
SIMD_M128 onePole (int idx, QuadFilterUnitState *__restrict f, SIMD_M128 in)
SIMD_M128 process (QuadFilterUnitState *__restrict f, SIMD_M128 in)
Enumeration Type Documentation
coeff
enum coeff
Enumerator
h_gres
h_gonepole
h_gcomp
n_hcoeffs
reg
enum reg
Enumerator
h_onepole_in
h_onepole_out
h_delayLine
Function Documentation
makeCoefficients()
template<typename TuningProvider > void makeCoefficients (FilterCoefficientMaker< TuningProvider > * cm, float freq, float reso, float sampleRate, float sampleRateInv, bool applyGainCompensation, TuningProvider * provider)
References sst::filters::VintageLadder::Common::clampedFrequency(), FilterCoefficientMaker< TuningProvider >::FromDirect(), h_gcomp, h_gonepole, h_gres, and sst::filters::n_cm_coeffs.
Referenced by FilterCoefficientMaker< TuningProvider >::MakeCoeffs().
nonlin()
SIMD_M128 nonlin (SIMD_M128 in)
References F, and M.
Referenced by process().
onePole()
SIMD_M128 onePole (int idx, QuadFilterUnitState *__restrict f, SIMD_M128 in)
References A, F, h_gonepole, h_onepole_in, h_onepole_out, M, and S.
Referenced by process().
process()
SIMD_M128 process (QuadFilterUnitState *__restrict f, SIMD_M128 in)
References A, F, h_delayLine, h_gcomp, h_gres, M, n_hcoeffs, nonlin(), onePole(), and S.
Referenced by sst::filters::GetCompensatedQFPtrFilterUnit().