sst-filters: sst::filters::VintageLadder::RK Namespace Reference
sst::filters::VintageLadder::RK Namespace Reference
Enumerations
enum rkm_coeffs { rkm_cutoff = 0, rkm_reso, rkm_gComp, n_rkcoeff }
Functions
template<typename TuningProvider >
void makeCoefficients (FilterCoefficientMaker< TuningProvider > *cm, float freq, float reso, float sampleRate, bool applyGainCompensation, TuningProvider *provider)
__m128 clip (__m128 value, __m128 _saturation, __m128 _saturationinverse)
void calculateDerivatives (__m128 input, __m128 *dstate, __m128 *state, __m128 cutoff, __m128 resonance, __m128 _saturation, __m128 _saturationInv, __m128 gComp)
__m128 process (QuadFilterUnitState *__restrict f, __m128 input)
Enumeration Type Documentation
rkm_coeffs
enum rkm_coeffs
Enumerator
rkm_cutoff
rkm_reso
rkm_gComp
n_rkcoeff
Function Documentation
makeCoefficients()
void sst::filters::VintageLadder::RK::makeCoefficients (FilterCoefficientMaker< TuningProvider > * cm, float freq, float reso, float sampleRate, bool applyGainCompensation, TuningProvider * provider)
References sst::filters::VintageLadder::Common::clampedFrequency(), FilterCoefficientMaker< TuningProvider >::FromDirect(), sst::filters::utilities::limit_range(), sst::filters::n_cm_coeffs, rkm_cutoff, rkm_gComp, and rkm_reso.
Referenced by FilterCoefficientMaker< TuningProvider >::MakeCoeffs().
clip()
__m128 sst::filters::VintageLadder::RK::clip (__m128 value, __m128 _saturation, __m128 _saturationinverse)
References F, M, sst::filters::OBXDFilter::one, and S.
Referenced by calculateDerivatives().
calculateDerivatives()
void sst::filters::VintageLadder::RK::calculateDerivatives (__m128 input, __m128 * dstate, __m128 * state, __m128 cutoff, __m128 resonance, __m128 _saturation, __m128 _saturationInv, __m128 gComp)
References clip(), M, and S.
Referenced by process().
process()
__m128 sst::filters::VintageLadder::RK::process (QuadFilterUnitState *__restrict f, __m128 input)
References A, calculateDerivatives(), F, M, n_rkcoeff, rkm_cutoff, rkm_gComp, rkm_reso, and sst::filters::OBXDFilter::two.
Referenced by sst::filters::GetQFPtrFilterUnit().