sst-filters: Catch::Matchers Namespace Reference
Catch::Matchers Namespace Reference
Namespaces
namespace Exception
namespace Floating
namespace Generic
namespace Impl
namespace StdString
namespace Vector
Functions
Exception::ExceptionMessageMatcher Message (std::string const &message)
Floating::WithinUlpsMatcher WithinULP (double target, uint64_t maxUlpDiff)
Floating::WithinUlpsMatcher WithinULP (float target, uint64_t maxUlpDiff)
Floating::WithinAbsMatcher WithinAbs (double target, double margin)
Floating::WithinRelMatcher WithinRel (double target, double eps)
Floating::WithinRelMatcher WithinRel (double target)
Floating::WithinRelMatcher WithinRel (float target, float eps)
Floating::WithinRelMatcher WithinRel (float target)
StdString::EqualsMatcher Equals (std::string const &str, CaseSensitive::Choice caseSensitivity=CaseSensitive::Yes)
StdString::ContainsMatcher Contains (std::string const &str, CaseSensitive::Choice caseSensitivity=CaseSensitive::Yes)
StdString::EndsWithMatcher EndsWith (std::string const &str, CaseSensitive::Choice caseSensitivity=CaseSensitive::Yes)
StdString::StartsWithMatcher StartsWith (std::string const &str, CaseSensitive::Choice caseSensitivity=CaseSensitive::Yes)
StdString::RegexMatcher Matches (std::string const &regex, CaseSensitive::Choice caseSensitivity=CaseSensitive::Yes)
Function Documentation
Message()
Exception::ExceptionMessageMatcher Message (std::string const & message)
References Message().
Referenced by Message().
WithinULP() [1/2]
Floating::WithinUlpsMatcher WithinULP (double target, uint64_t maxUlpDiff)
References WithinULP().
Referenced by WithinULP(), and WithinULP().
WithinULP() [2/2]
Floating::WithinUlpsMatcher WithinULP (float target, uint64_t maxUlpDiff)
References WithinULP().
WithinAbs()
Floating::WithinAbsMatcher WithinAbs (double target, double margin)
References WithinAbs().
Referenced by WithinAbs().
WithinRel() [1/4]
Floating::WithinRelMatcher WithinRel (double target, double eps)
References WithinRel().
Referenced by WithinRel(), WithinRel(), WithinRel(), and WithinRel().
WithinRel() [2/4]
Floating::WithinRelMatcher WithinRel (double target)
References WithinRel().
WithinRel() [3/4]
Floating::WithinRelMatcher WithinRel (float target, float eps)
References WithinRel().
WithinRel() [4/4]
Floating::WithinRelMatcher WithinRel (float target)
References WithinRel().
Equals()
StdString::EqualsMatcher Equals (std::string const & str, CaseSensitive::Choice caseSensitivity = CaseSensitive::Yes)
References Equals().
Referenced by Equals().
Contains()
StdString::ContainsMatcher Contains (std::string const & str, CaseSensitive::Choice caseSensitivity = CaseSensitive::Yes)
References Contains().
Referenced by Contains().
EndsWith()
StdString::EndsWithMatcher EndsWith (std::string const & str, CaseSensitive::Choice caseSensitivity = CaseSensitive::Yes)
References EndsWith().
Referenced by EndsWith().
StartsWith()
StdString::StartsWithMatcher StartsWith (std::string const & str, CaseSensitive::Choice caseSensitivity = CaseSensitive::Yes)
References StartsWith().
Referenced by StartsWith().
Matches()
StdString::RegexMatcher Matches (std::string const & regex, CaseSensitive::Choice caseSensitivity = CaseSensitive::Yes)
References Matches().
Referenced by Matches().