sst-filters: sst::filters::cytomic_quadform Namespace Reference
sst::filters::cytomic_quadform Namespace Reference
Classes
struct Coeff
struct Reg
Functions
template<typename TuningProvider >
void makeCoefficients (FilterCoefficientMaker< TuningProvider > *cm, float freq, float res, int subtype, float sampleRate, float sampleRateInv, TuningProvider *provider, float bellShelfAmpPM1)
template<bool lowPassOpt = false>
SIMD_M128 CytomicQuad (QuadFilterUnitState *__restrict f, SIMD_M128 vin)
Function Documentation
makeCoefficients()
template<typename TuningProvider > void makeCoefficients (FilterCoefficientMaker< TuningProvider > * cm, float freq, float res, int subtype, float sampleRate, float sampleRateInv, TuningProvider * provider, float bellShelfAmpPM1)
References A, Coeff::a1, Coeff::a2, Coeff::a3, FilterCoefficientMaker< TuningProvider >::FromDirect(), Coeff::m0, Coeff::m1, Coeff::m2, sst::filters::n_cm_coeffs, FilterCoefficientMaker< TuningProvider >::provider_note_to_pitch_ignoring_tuning(), sst::filters::st_cytomic_allpass, sst::filters::st_cytomic_bell, sst::filters::st_cytomic_bp, sst::filters::st_cytomic_highshelf, sst::filters::st_cytomic_hp, sst::filters::st_cytomic_lowshelf, sst::filters::st_cytomic_lp, sst::filters::st_cytomic_notch, and sst::filters::st_cytomic_peak.
Referenced by FilterCoefficientMaker< TuningProvider >::MakeCoeffs().
CytomicQuad()
template<bool lowPassOpt = false> SIMD_M128 CytomicQuad (QuadFilterUnitState *__restrict f, SIMD_M128 vin)
References Coeff::a1, Coeff::a2, Coeff::a3, ADD, Reg::ic1eq, Reg::ic2eq, Coeff::m0, Coeff::m1, Coeff::m2, MUL, and SUB.
Referenced by sst::filters::GetCompensatedQFPtrFilterUnit().