sst-filters: ApproxMatcher< T, AllocComp, AllocMatch > Struct Template Reference
ApproxMatcher< T, AllocComp, AllocMatch > Struct Template Reference
Public Member Functions
ApproxMatcher (std::vector< T, AllocComp > const &comparator)
bool match (std::vector< T, AllocMatch > const &v) const override
std::string describe () const override
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & epsilon (T const &newEpsilon)
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & margin (T const &newMargin)
template<typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
ApproxMatcher & scale (T const &newScale)
Public Member Functions inherited from MatcherBase< T >
MatchAllOf< T > operator&& (MatcherBase const &other) const
MatchAnyOf< T > operator|| (MatcherBase const &other) const
MatchNotOf< T > operator! () const
Public Member Functions inherited from MatcherUntypedBase
MatcherUntypedBase ()=default
MatcherUntypedBase (MatcherUntypedBase const &)=default
MatcherUntypedBase & operator= (MatcherUntypedBase const &)=delete
std::string toString () const
Public Member Functions inherited from MatcherMethod< T >
virtual bool match (T const &arg) const=0
Public Attributes
std::vector< T, AllocComp > const & m_comparator
Catch::Detail::Approx approx = Catch::Detail::Approx::custom()
Additional Inherited Members
Protected Member Functions inherited from MatcherUntypedBase
virtual ~MatcherUntypedBase ()
Protected Attributes inherited from MatcherUntypedBase
std::string m_cachedToString
Constructor & Destructor Documentation
ApproxMatcher()
ApproxMatcher (std::vector< T, AllocComp > const & comparator)
Member Function Documentation
match()
bool match (std::vector< T, AllocMatch > const & v) const override
describe()
std::string describe () const override virtual
Implements MatcherUntypedBase.
References Catch::Detail::stringify().
epsilon()
ApproxMatcher& epsilon (T const & newEpsilon)
References ApproxMatcher< T, AllocComp, AllocMatch >::epsilon().
Referenced by ApproxMatcher< T, AllocComp, AllocMatch >::epsilon().
margin()
ApproxMatcher& margin (T const & newMargin)
References ApproxMatcher< T, AllocComp, AllocMatch >::margin().
Referenced by ApproxMatcher< T, AllocComp, AllocMatch >::margin().
scale()
ApproxMatcher& scale (T const & newScale)
References ApproxMatcher< T, AllocComp, AllocMatch >::scale().
Referenced by ApproxMatcher< T, AllocComp, AllocMatch >::scale().
Member Data Documentation
m_comparator
std::vector<T, AllocComp> const& m_comparator
approx
Catch::Detail::Approx approx = Catch::Detail::Approx::custom() mutable
The documentation for this struct was generated from the following file:
catch2.hpp