sst-filters: LinkwitzRileyLR4Crossover Struct Reference
LinkwitzRileyLR4Crossover Struct Reference
#include <LinkwitzRiley.h>
Public Member Functions
void init ()
void setCoeff (float crossoverFreq, float srInv)
void step (float L, float R, float &lowL, float &lowR, float &highL, float &highR)
template<int blockSize>
void setCoeffForBlock (float crossoverFreq, float srInv)
template<int blockSize>
void retainCoeffForBlock ()
void processBlockStep (float L, float R, float &lowL, float &lowR, float &highL, float &highR)
template<int blockSize>
void processBlock (const float *const inL, const float *const inR, float *lowL, float *lowR, float *highL, float *highR)
Public Attributes
CytomicSVF stage1
CytomicSVF stage2
SIMD_M128 da1 {SIMD_MM(setzero_ps)()}
SIMD_M128 da2 {SIMD_MM(setzero_ps)()}
SIMD_M128 da3 {SIMD_MM(setzero_ps)()}
bool firstBlock {true}
Static Public Attributes
static constexpr float butterworthRes {0.2928932188134524f}
static constexpr std::array< CytomicSVF::Mode, 4 > crossoverModes
Member Function Documentation
init()
void init ()
References CytomicSVF::init(), LinkwitzRileyLR4Crossover::stage1, and LinkwitzRileyLR4Crossover::stage2.
setCoeff()
void setCoeff (float crossoverFreq, float srInv)
References LinkwitzRileyLR4Crossover::butterworthRes, LinkwitzRileyLR4Crossover::crossoverModes, CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeff(), LinkwitzRileyLR4Crossover::stage1, and LinkwitzRileyLR4Crossover::stage2.
Referenced by LinkwitzRileyLR4Crossover::setCoeffForBlock().
step()
void step (float L, float R, float & lowL, float & lowR, float & highL, float & highR)
References L, LinkwitzRileyLR4Crossover::stage1, LinkwitzRileyLR4Crossover::stage2, and CytomicSVF::stepSSE().
Referenced by LinkwitzRileyLR4Crossover::processBlockStep().
setCoeffForBlock()
template<int blockSize> void setCoeffForBlock (float crossoverFreq, float srInv)
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, LinkwitzRileyLR4Crossover::da1, LinkwitzRileyLR4Crossover::da2, LinkwitzRileyLR4Crossover::da3, LinkwitzRileyLR4Crossover::firstBlock, LR_MUL, LR_SUB, LinkwitzRileyLR4Crossover::setCoeff(), and LinkwitzRileyLR4Crossover::stage1.
retainCoeffForBlock()
template<int blockSize> void retainCoeffForBlock ()
References LinkwitzRileyLR4Crossover::da1, LinkwitzRileyLR4Crossover::da2, and LinkwitzRileyLR4Crossover::da3.
processBlockStep()
void processBlockStep (float L, float R, float & lowL, float & lowR, float & highL, float & highR)
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, LinkwitzRileyLR4Crossover::da1, LinkwitzRileyLR4Crossover::da2, LinkwitzRileyLR4Crossover::da3, L, LR_ADD, LinkwitzRileyLR4Crossover::stage1, and LinkwitzRileyLR4Crossover::step().
Referenced by LinkwitzRileyLR4Crossover::processBlock().
processBlock()
template<int blockSize> void processBlock (const float *const inL, const float *const inR, float * lowL, float * lowR, float * highL, float * highR)
References LinkwitzRileyLR4Crossover::processBlockStep().
Member Data Documentation
stage1
CytomicSVF stage1
Referenced by LinkwitzRileyLR4Crossover::init(), LinkwitzRileyLR4Crossover::processBlockStep(), LinkwitzRileyLR4Crossover::setCoeff(), LinkwitzRileyLR4Crossover::setCoeffForBlock(), and LinkwitzRileyLR4Crossover::step().
stage2
CytomicSVF stage2
Referenced by LinkwitzRileyLR4Crossover::init(), LinkwitzRileyLR4Crossover::setCoeff(), and LinkwitzRileyLR4Crossover::step().
butterworthRes
constexpr float butterworthRes {0.2928932188134524f} static constexpr
Referenced by LinkwitzRileyLR4Crossover::setCoeff().
crossoverModes
constexpr std::array<CytomicSVF::Mode, 4> crossoverModes static constexpr
Initial value:
{
        CytomicSVF::Mode::Lowpass, CytomicSVF::Mode::Lowpass, CytomicSVF::Mode::Highpass,
        CytomicSVF::Mode::Highpass}
Referenced by LinkwitzRileyLR4Crossover::setCoeff().
da1
SIMD_M128 da1 {SIMD_MM(setzero_ps)()}
Referenced by LinkwitzRileyLR4Crossover::processBlockStep(), LinkwitzRileyLR4Crossover::retainCoeffForBlock(), and LinkwitzRileyLR4Crossover::setCoeffForBlock().
da2
SIMD_M128 da2 {SIMD_MM(setzero_ps)()}
Referenced by LinkwitzRileyLR4Crossover::processBlockStep(), LinkwitzRileyLR4Crossover::retainCoeffForBlock(), and LinkwitzRileyLR4Crossover::setCoeffForBlock().
da3
SIMD_M128 da3 {SIMD_MM(setzero_ps)()}
Referenced by LinkwitzRileyLR4Crossover::processBlockStep(), LinkwitzRileyLR4Crossover::retainCoeffForBlock(), and LinkwitzRileyLR4Crossover::setCoeffForBlock().
firstBlock
bool firstBlock {true}
Referenced by LinkwitzRileyLR4Crossover::setCoeffForBlock().
The documentation for this struct was generated from the following file:
LinkwitzRiley.h