sst-filters: SincTable Struct Reference
SincTable Struct Reference
Lookup table for evaluating the Sinc function.
#include <SincTable.h>
Public Member Functions
SincTable ()
Static Public Member Functions
static double sincf (double x)
static double symmetric_blackman (double i, int n)
Public Attributes
float sinctable [(FIRipol_M+1) *FIRipol_N *2] {}
float sinctable1X [(FIRipol_M+1) *FIRipol_N] {}
short sinctableI16 [(FIRipol_M+1) *FIRipolI16_N] {}
Static Public Attributes
static constexpr int FIRipol_M = 256
static constexpr int FIRipol_M_bits = 8
static constexpr int FIRipol_N = 12
static constexpr int FIRoffset = FIRipol_N >> 1
static constexpr int FIRipolI16_N = 8
static constexpr int FIRoffsetI16 = FIRipolI16_N >> 1
Detailed Description
Lookup table for evaluating the Sinc function.
Constructor & Destructor Documentation
SincTable()
SincTable ()
References SincTable::FIRipol_M, SincTable::FIRipol_N, SincTable::FIRipolI16_N, SincTable::sincf(), SincTable::sinctable, SincTable::sinctable1X, SincTable::sinctableI16, and SincTable::symmetric_blackman().
Member Function Documentation
sincf()
static double sincf (double x) static
Referenced by SincTable::SincTable().
symmetric_blackman()
static double symmetric_blackman (double i, int n) static
Referenced by SincTable::SincTable().
Member Data Documentation
FIRipol_M
constexpr int FIRipol_M = 256 static constexpr
Referenced by sst::filters::COMBquad_SSE2(), and SincTable::SincTable().
FIRipol_M_bits
constexpr int FIRipol_M_bits = 8 static constexpr
FIRipol_N
constexpr int FIRipol_N = 12 static constexpr
Referenced by sst::filters::COMBquad_SSE2(), and SincTable::SincTable().
FIRoffset
constexpr int FIRoffset = FIRipol_N >> 1 static constexpr
Referenced by sst::filters::COMBquad_SSE2().
FIRipolI16_N
constexpr int FIRipolI16_N = 8 static constexpr
Referenced by SincTable::SincTable().
FIRoffsetI16
constexpr int FIRoffsetI16 = FIRipolI16_N >> 1 static constexpr
sinctable
float sinctable[(FIRipol_M+1) *FIRipol_N *2] {}
Referenced by SincTable::SincTable().
sinctable1X
float sinctable1X[(FIRipol_M+1) *FIRipol_N] {}
Referenced by SincTable::SincTable().
sinctableI16
short sinctableI16[(FIRipol_M+1) *FIRipolI16_N] {}
Referenced by SincTable::SincTable().
The documentation for this struct was generated from the following file:
SincTable.h