sst-filters: IGeneratorTracker Struct Reference
IGeneratorTracker Struct Reference abstract
#include <catch2.hpp>
Public Member Functions
virtual ~IGeneratorTracker ()
virtual auto hasGenerator () const -> bool=0
virtual auto getGenerator () const -> Generators::GeneratorBasePtr const &=0
virtual void setGenerator (Generators::GeneratorBasePtr &&generator)=0
Constructor & Destructor Documentation
~IGeneratorTracker()
virtual ~IGeneratorTracker () virtual
Member Function Documentation
hasGenerator()
virtual auto hasGenerator () const -> bool pure virtual
Referenced by Catch::Generators::generate().
getGenerator()
virtual auto getGenerator () const -> Generators::GeneratorBasePtr const & pure virtual
Referenced by Catch::Generators::generate().
setGenerator()
virtual void setGenerator (Generators::GeneratorBasePtr && generator) pure virtual
References Catch::throw_exception().
Referenced by Catch::Generators::generate().
The documentation for this struct was generated from the following file:
catch2.hpp