sst-filters: CytomicSVF Struct Reference
CytomicSVF Struct Reference
Public Types
enum Mode {
LP , HP , BP , NOTCH ,
PEAK , ALL , BELL , LOW_SHELF ,
HIGH_SHELF
}
Public Member Functions
void setCoeff (Mode mode, float freq, float res, float srInv, float bellShelfAmp=1.f)
void setCoeff (Mode mode, float freqL, float freqR, float resL, float resR, float srInv, float bellShelfAmpL, float bellShelfAmpR)
void setCoeffPostGK (Mode mode, __m128 bellShelfSSE)
void fetchCoeffs (const CytomicSVF &that)
template<int blockSize>
void setCoeffForBlock (Mode mode, float freq, float res, float srInv, float bellShelfAmp=1.f)
template<int blockSize>
void setCoeffForBlock (Mode mode, float freqL, float freqR, float resL, float resR, float srInv, float bellShelfAmpL, float bellShelfAmpR)
template<int blockSize>
void retainCoeffForBlock ()
void processBlockStep (float &L, float &R)
void processBlockStep (float &L)
template<int blockSize>
void processBlock (const float *const inL, const float *const inR, float *outL, float *outR)
template<int blockSize>
void processBlock (const float *const inL, float *outL)
void init ()
Static Public Member Functions
static void step (CytomicSVF &that, float &L, float &R)
static __m128 stepSSE (CytomicSVF &that, __m128 vin)
Public Attributes
__m128 ic1eq {_mm_setzero_ps()}
__m128 ic2eq {_mm_setzero_ps()}
__m128 g
__m128 k
__m128 gk
__m128 a1
__m128 a2
__m128 a3
__m128 m0
__m128 m1
__m128 m2
__m128 oneSSE {_mm_set1_ps(1.0)}
__m128 negoneSSE {_mm_set1_ps(-1.0)}
__m128 twoSSE {_mm_set1_ps(2.0)}
__m128 negtwoSSE {_mm_set1_ps(-2.0)}
__m128 a1_prior
__m128 a2_prior
__m128 a3_prior
__m128 da1
__m128 da2
__m128 da3
bool firstBlock {true}
Member Enumeration Documentation
Mode
enum Mode
Enumerator
LP
HP
BP
NOTCH
PEAK
ALL
BELL
LOW_SHELF
HIGH_SHELF
Member Function Documentation
setCoeff() [1/2]
void setCoeff (Mode mode, float freq, float res, float srInv, float bellShelfAmp = 1.f)
References CytomicSVF::BELL, CytomicSVF::g, CytomicSVF::k, and CytomicSVF::setCoeffPostGK().
Referenced by CytomicSVF::setCoeffForBlock().
setCoeff() [2/2]
void setCoeff (Mode mode, float freqL, float freqR, float resL, float resR, float srInv, float bellShelfAmpL, float bellShelfAmpR)
References CytomicSVF::BELL, CytomicSVF::g, CytomicSVF::k, CytomicSVF::setCoeffPostGK(), and CytomicSVF::twoSSE.
setCoeffPostGK()
void setCoeffPostGK (Mode mode, __m128 bellShelfSSE)
References A, CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, CytomicSVF::ALL, CytomicSVF::BELL, CytomicSVF::BP, CytomicSVF::g, CytomicSVF::gk, CytomicSVF::HIGH_SHELF, CytomicSVF::HP, CytomicSVF::k, CytomicSVF::LOW_SHELF, CytomicSVF::LP, CytomicSVF::m0, CytomicSVF::m1, CytomicSVF::m2, CytomicSVF::negoneSSE, CytomicSVF::negtwoSSE, CytomicSVF::NOTCH, CytomicSVF::oneSSE, and CytomicSVF::PEAK.
Referenced by CytomicSVF::setCoeff().
fetchCoeffs()
void fetchCoeffs (const CytomicSVF & that)
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, CytomicSVF::g, CytomicSVF::gk, CytomicSVF::k, CytomicSVF::m0, CytomicSVF::m1, and CytomicSVF::m2.
step()
static void step (CytomicSVF & that, float & L, float & R) static
References CytomicSVF::stepSSE().
Referenced by CytomicSVF::processBlockStep().
stepSSE()
static __m128 stepSSE (CytomicSVF & that, __m128 vin) static
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, CytomicSVF::ic1eq, CytomicSVF::ic2eq, CytomicSVF::m0, CytomicSVF::m1, CytomicSVF::m2, and CytomicSVF::twoSSE.
Referenced by CytomicSVF::step().
setCoeffForBlock() [1/2]
void setCoeffForBlock (Mode mode, float freq, float res, float srInv, float bellShelfAmp = 1.f)
References CytomicSVF::a1, CytomicSVF::a1_prior, CytomicSVF::a2, CytomicSVF::a2_prior, CytomicSVF::a3, CytomicSVF::a3_prior, CytomicSVF::da1, CytomicSVF::da2, CytomicSVF::da3, CytomicSVF::firstBlock, and CytomicSVF::setCoeff().
setCoeffForBlock() [2/2]
void setCoeffForBlock (Mode mode, float freqL, float freqR, float resL, float resR, float srInv, float bellShelfAmpL, float bellShelfAmpR)
References CytomicSVF::a1, CytomicSVF::a1_prior, CytomicSVF::a2, CytomicSVF::a2_prior, CytomicSVF::a3, CytomicSVF::a3_prior, CytomicSVF::da1, CytomicSVF::da2, CytomicSVF::da3, CytomicSVF::firstBlock, and CytomicSVF::setCoeff().
retainCoeffForBlock()
void retainCoeffForBlock ()
References CytomicSVF::da1, CytomicSVF::da2, and CytomicSVF::da3.
processBlockStep() [1/2]
void processBlockStep (float & L, float & R)
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, CytomicSVF::da1, CytomicSVF::da2, CytomicSVF::da3, and CytomicSVF::step().
Referenced by CytomicSVF::processBlock().
processBlockStep() [2/2]
void processBlockStep (float & L)
References CytomicSVF::a1, CytomicSVF::a2, CytomicSVF::a3, CytomicSVF::da1, CytomicSVF::da2, CytomicSVF::da3, and CytomicSVF::step().
processBlock() [1/2]
void processBlock (const float *const inL, const float *const inR, float * outL, float * outR)
References CytomicSVF::processBlockStep().
processBlock() [2/2]
void processBlock (const float *const inL, float * outL)
References CytomicSVF::processBlockStep().
init()
void init ()
References CytomicSVF::ic1eq, and CytomicSVF::ic2eq.
Member Data Documentation
ic1eq
__m128 ic1eq {_mm_setzero_ps()}
Referenced by CytomicSVF::init(), and CytomicSVF::stepSSE().
ic2eq
__m128 ic2eq {_mm_setzero_ps()}
Referenced by CytomicSVF::init(), and CytomicSVF::stepSSE().
g
__m128 g
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeff(), and CytomicSVF::setCoeffPostGK().
k
__m128 k
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeff(), and CytomicSVF::setCoeffPostGK().
gk
__m128 gk
Referenced by CytomicSVF::fetchCoeffs(), and CytomicSVF::setCoeffPostGK().
a1
__m128 a1
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::processBlockStep(), CytomicSVF::setCoeffForBlock(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
a2
__m128 a2
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::processBlockStep(), CytomicSVF::setCoeffForBlock(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
a3
__m128 a3
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::processBlockStep(), CytomicSVF::setCoeffForBlock(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
m0
__m128 m0
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
m1
__m128 m1
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
m2
__m128 m2
Referenced by CytomicSVF::fetchCoeffs(), CytomicSVF::setCoeffPostGK(), and CytomicSVF::stepSSE().
oneSSE
__m128 oneSSE {_mm_set1_ps(1.0)}
Referenced by CytomicSVF::setCoeffPostGK().
negoneSSE
__m128 negoneSSE {_mm_set1_ps(-1.0)}
Referenced by CytomicSVF::setCoeffPostGK().
twoSSE
__m128 twoSSE {_mm_set1_ps(2.0)}
Referenced by CytomicSVF::setCoeff(), and CytomicSVF::stepSSE().
negtwoSSE
__m128 negtwoSSE {_mm_set1_ps(-2.0)}
Referenced by CytomicSVF::setCoeffPostGK().
a1_prior
__m128 a1_prior
Referenced by CytomicSVF::setCoeffForBlock().
a2_prior
__m128 a2_prior
Referenced by CytomicSVF::setCoeffForBlock().
a3_prior
__m128 a3_prior
Referenced by CytomicSVF::setCoeffForBlock().
da1
__m128 da1
Referenced by CytomicSVF::processBlockStep(), CytomicSVF::retainCoeffForBlock(), and CytomicSVF::setCoeffForBlock().
da2
__m128 da2
Referenced by CytomicSVF::processBlockStep(), CytomicSVF::retainCoeffForBlock(), and CytomicSVF::setCoeffForBlock().
da3
__m128 da3
Referenced by CytomicSVF::processBlockStep(), CytomicSVF::retainCoeffForBlock(), and CytomicSVF::setCoeffForBlock().
firstBlock
bool firstBlock {true}
Referenced by CytomicSVF::setCoeffForBlock().
The documentation for this struct was generated from the following file:
CytomicSVF.h