sst-voicemanager: VoiceManager< Cfg, Responder, MonoResponder > Struct Template Reference
VoiceManager< Cfg, Responder, MonoResponder > Struct Template Reference
VoiceManager is the main class used for voice management, and the sole public API.
#include <voicemanager.h>
Classes
struct Details
Public Types
enum struct MIDI1Dialect { MIDI1 , MIDI1_MPE }
enum struct RepeatedKeyMode { MULTI_VOICE , PIANO }
If a key is struck twice while still gated or sustained, do we start a new voice or do we re-use the voice (and move the note id) or do we trigger a second voice.
enum struct PlayMode { POLY_VOICES , MONO_NOTES }
The voice manager can either run in a mode where it manages to voice limits in a polyphonic mode (but multi-voice notes still steal together) or can manage to a single note with essentially unlimited voices.
enum struct MonoPlayModeFeatures : uint64_t {
NONE = 0 , MONO_RETRIGGER = 1 << 0 , MONO_LEGATO = 1 << 1 , ON_RELEASE_TO_LATEST = 1 << 2 ,
ON_RELEASE_TO_HIGHEST = 1 << 3 , ON_RELEASE_TO_LOWEST = 1 << 4 , NATURAL_MONO = MONO_RETRIGGER | ON_RELEASE_TO_LATEST , NATURAL_LEGATO = MONO_LEGATO | ON_RELEASE_TO_LATEST
}
Mono Playmode is somewhat ambiguous, meaning many things.
enum struct StealingPriorityMode { OLDEST , HIGHEST , LOWEST }
StealingPriorityMode determines how to pick a voice to steal when an appropriate voice or note limit is met.
enum struct MonoPriorityMode { LATEST , HIGHEST , LOWEST }
MonoPriorityMode determines which note "wins" in MONO_NOTES and MONO_LEGATO modes when a new note-on arrives while a voice is already playing.
typedef VoiceInitInstructionsEntry< Cfg > initInstruction_t
Public Member Functions
VoiceManager (Responder &r, MonoResponder &m)
void registerVoiceEndCallback ()
bool processNoteOnEvent (int16_t port, int16_t channel, int16_t key, int32_t noteid, float velocity, float retune) SST_VOICEMANAGER_NONBLOCKING
void processNoteOffEvent (int16_t port, int16_t channel, int16_t key, int32_t noteid, float velocity) SST_VOICEMANAGER_NONBLOCKING
void updateSustainPedal (int16_t port, int16_t channel, int8_t level) SST_VOICEMANAGER_NONBLOCKING
void routeMIDIPitchBend (int16_t port, int16_t channel, int16_t pb14bit) SST_VOICEMANAGER_NONBLOCKING
void routeMIDI1CC (int16_t port, int16_t channel, int8_t cc, int8_t val) SST_VOICEMANAGER_NONBLOCKING
void routePolyphonicAftertouch (int16_t port, int16_t channel, int16_t key, int8_t pat) SST_VOICEMANAGER_NONBLOCKING
void routeChannelPressure (int16_t port, int16_t channel, int8_t pat) SST_VOICEMANAGER_NONBLOCKING
void routeNoteExpression (int16_t port, int16_t channel, int16_t key, int32_t noteid, int32_t expression, double value) SST_VOICEMANAGER_NONBLOCKING
void routePolyphonicParameterModulation (int16_t port, int16_t channel, int16_t key, int32_t voiceid, uint32_t parameter, double value) SST_VOICEMANAGER_NONBLOCKING
void routeMonophonicParameterModulation (int16_t port, int16_t channel, int16_t key, uint32_t parameter, double value) SST_VOICEMANAGER_NONBLOCKING
size_t getVoiceCount () const SST_VOICEMANAGER_NONBLOCKING
size_t getGatedVoiceCount () const SST_VOICEMANAGER_NONBLOCKING
void allNotesOff () SST_VOICEMANAGER_NONBLOCKING
void allSoundsOff () SST_VOICEMANAGER_NONBLOCKING
void allSoundsOffMatching (std::function< bool(typename Cfg::voice_t *)>) SST_VOICEMANAGER_NONBLOCKING
void guaranteePort (int16_t port)
Pre-allocate the per-port voice-tracking state for port.
void guaranteeGroup (uint64_t groupId)
void setPolyphonyGroupVoiceLimit (uint64_t groupId, int32_t limit)
int32_t getPolyphonyGroupVoiceLimit (uint64_t groupId) const SST_VOICEMANAGER_NONBLOCKING
bool setPolyphonyGroupParent (uint64_t childGroup, uint64_t parentGroup)
Make childGroup count its voices against parentGroup (and every ancestor above it), forming a hierarchy.
bool setPlaymode (uint64_t groupId, PlayMode pm, uint64_t features=static_cast< uint64_t >(MonoPlayModeFeatures::NONE))
Set a group's play mode.
PlayMode getPlaymode (uint64_t groupId) const SST_VOICEMANAGER_NONBLOCKING
void setStealingPriorityMode (uint64_t groupId, StealingPriorityMode pm)
void setMonoPriorityMode (uint64_t groupId, MonoPriorityMode pm)
Public Attributes
enum sst::voicemanager::VoiceManager::MIDI1Dialect MIDI1
enum sst::voicemanager::VoiceManager::RepeatedKeyMode MULTI_VOICE
int8_t mpeGlobalChannel {0}
Responder & responder
MonoResponder & monoResponder
std::array< std::array< bool, 128 >, 16 > heldMIDIKeyByChannel
Static Public Attributes
static constexpr int8_t mpeTimbreCC {74}
static constexpr uint64_t noPolyphonyGroupParent {std::numeric_limits<uint64_t>::max()}
Pass as the parent to setPolyphonyGroupParent to detach a group, making it a root whose only super-constraint is the global voice pool.
Detailed Description
template<typename Cfg, typename Responder, typename MonoResponder>
struct sst::voicemanager::VoiceManager< Cfg, Responder, MonoResponder >
VoiceManager is the main class used for voice management, and the sole public API.
The voice manager has the following features
blah
blah
blah
The VoiceManager collaborates with your synth through three
Template Parameters
Cfg A configuration trait, setting the hard (physical) voice limit and voice type
Responder A class responsible for responding to voice-level activities such as creation, termination, setting of voice level properties, and so forth
MonoResponder A class responsible for responding to monophonic activities such as MIDI CC and Channel PitchBend (which are monophonic in non-MPE mode)
Member Typedef Documentation
initInstruction_t
template<typename Cfg , typename Responder , typename MonoResponder > typedef VoiceInitInstructionsEntry<Cfg> initInstruction_t
Member Enumeration Documentation
MIDI1Dialect
template<typename Cfg , typename Responder , typename MonoResponder > enum struct MIDI1Dialect strong
Enumerator
MIDI1
MIDI1_MPE
RepeatedKeyMode
template<typename Cfg , typename Responder , typename MonoResponder > enum struct RepeatedKeyMode strong
If a key is struck twice while still gated or sustained, do we start a new voice or do we re-use the voice (and move the note id) or do we trigger a second voice.
Enumerator
MULTI_VOICE
PIANO
PlayMode
template<typename Cfg , typename Responder , typename MonoResponder > enum struct PlayMode strong
The voice manager can either run in a mode where it manages to voice limits in a polyphonic mode (but multi-voice notes still steal together) or can manage to a single note with essentially unlimited voices.
This is controlled by the group PlayMode.
Enumerator
POLY_VOICES
The voice manager manages voice counts from any number of keys in piano mode.
MONO_NOTES
The voice manager makes sure the consequence of only one key is playing at a time, independent of voices.
MonoPlayModeFeatures
template<typename Cfg , typename Responder , typename MonoResponder > enum struct MonoPlayModeFeatures : uint64_t strong
Mono Playmode is somewhat ambiguous, meaning many things.
So let's enumerate the features. Hope we have fewer than 64. Even though these are using the bits as features they are not all possible to be active simultaneously. As well as distinct bit values, we provide a few preset | combinations of flags for common use cases.
Enumerator
NONE
MONO_RETRIGGER
A new keypress triggers a new voice.
MONO_LEGATO
A new keypress moves the playing voice.
ON_RELEASE_TO_LATEST
mono release return to latest
ON_RELEASE_TO_HIGHEST
release to highest
ON_RELEASE_TO_LOWEST
release to lowest
NATURAL_MONO
What a 'mono' button would do.
NATURAL_LEGATO
What a 'legato' button would do.
StealingPriorityMode
template<typename Cfg , typename Responder , typename MonoResponder > enum struct StealingPriorityMode strong
StealingPriorityMode determines how to pick a voice to steal when an appropriate voice or note limit is met.
HIGHEST and LOWEST are in midi-key space.
Enumerator
OLDEST
HIGHEST
LOWEST
MonoPriorityMode
template<typename Cfg , typename Responder , typename MonoResponder > enum struct MonoPriorityMode strong
MonoPriorityMode determines which note "wins" in MONO_NOTES and MONO_LEGATO modes when a new note-on arrives while a voice is already playing.
LATEST: the new note always takes over (default). HIGHEST: the new note only takes over if its key is strictly higher than the current voice. LOWEST: the new note only takes over if its key is strictly lower than the current voice.
Enumerator
LATEST
HIGHEST
LOWEST
Constructor & Destructor Documentation
VoiceManager()
template<typename Cfg , typename Responder , typename MonoResponder > VoiceManager (Responder & r, MonoResponder & m)
References VoiceManager< Cfg, Responder, MonoResponder >::heldMIDIKeyByChannel, VoiceManager< Cfg, Responder, MonoResponder >::registerVoiceEndCallback(), and ConstraintsChecker< Cfg, Responder, MonoResponder >::satisfies().
Member Function Documentation
registerVoiceEndCallback()
template<typename Cfg , typename Responder , typename MonoResponder > void registerVoiceEndCallback ()
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::VoiceManager().
processNoteOnEvent()
template<typename Cfg , typename Responder , typename MonoResponder > bool processNoteOnEvent (int16_t port, int16_t channel, int16_t key, int32_t noteid, float velocity, float retune)
References VML.
processNoteOffEvent()
template<typename Cfg , typename Responder , typename MonoResponder > void processNoteOffEvent (int16_t port, int16_t channel, int16_t key, int32_t noteid, float velocity)
References VML.
updateSustainPedal()
template<typename Cfg , typename Responder , typename MonoResponder > void updateSustainPedal (int16_t port, int16_t channel, int8_t level)
References VML.
routeMIDIPitchBend()
template<typename Cfg , typename Responder , typename MonoResponder > void routeMIDIPitchBend (int16_t port, int16_t channel, int16_t pb14bit)
routeMIDI1CC()
template<typename Cfg , typename Responder , typename MonoResponder > void routeMIDI1CC (int16_t port, int16_t channel, int8_t cc, int8_t val)
routePolyphonicAftertouch()
template<typename Cfg , typename Responder , typename MonoResponder > void routePolyphonicAftertouch (int16_t port, int16_t channel, int16_t key, int8_t pat)
routeChannelPressure()
template<typename Cfg , typename Responder , typename MonoResponder > void routeChannelPressure (int16_t port, int16_t channel, int8_t pat)
routeNoteExpression()
template<typename Cfg , typename Responder , typename MonoResponder > void routeNoteExpression (int16_t port, int16_t channel, int16_t key, int32_t noteid, int32_t expression, double value)
routePolyphonicParameterModulation()
template<typename Cfg , typename Responder , typename MonoResponder > void routePolyphonicParameterModulation (int16_t port, int16_t channel, int16_t key, int32_t voiceid, uint32_t parameter, double value)
routeMonophonicParameterModulation()
template<typename Cfg , typename Responder , typename MonoResponder > void routeMonophonicParameterModulation (int16_t port, int16_t channel, int16_t key, uint32_t parameter, double value)
getVoiceCount()
template<typename Cfg , typename Responder , typename MonoResponder > size_t getVoiceCount () const
getGatedVoiceCount()
template<typename Cfg , typename Responder , typename MonoResponder > size_t getGatedVoiceCount () const
allNotesOff()
template<typename Cfg , typename Responder , typename MonoResponder > void allNotesOff ()
References VML.
allSoundsOff()
template<typename Cfg , typename Responder , typename MonoResponder > void allSoundsOff ()
allSoundsOffMatching()
template<typename Cfg , typename Responder , typename MonoResponder > void allSoundsOffMatching (std::function< bool(typename Cfg::voice_t *)> pred)
guaranteePort()
template<typename Cfg , typename Responder , typename MonoResponder > void guaranteePort (int16_t port)
Pre-allocate the per-port voice-tracking state for port.
Port 0 is always pre-allocated. For any other port this MUST be called (off the audio thread) before sending note events to that port: the note-event API is tagged non-blocking and will not lazily create the per-port state, so a note on an unguaranteed port would violate that constraint and allocate.
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::Details::Details().
guaranteeGroup()
template<typename Cfg , typename Responder , typename MonoResponder > void guaranteeGroup (uint64_t groupId)
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::Details::Details().
setPolyphonyGroupVoiceLimit()
template<typename Cfg , typename Responder , typename MonoResponder > void setPolyphonyGroupVoiceLimit (uint64_t groupId, int32_t limit)
getPolyphonyGroupVoiceLimit()
template<typename Cfg , typename Responder , typename MonoResponder > int32_t getPolyphonyGroupVoiceLimit (uint64_t groupId) const
setPolyphonyGroupParent()
template<typename Cfg , typename Responder , typename MonoResponder > bool setPolyphonyGroupParent (uint64_t childGroup, uint64_t parentGroup)
Make childGroup count its voices against parentGroup (and every ancestor above it), forming a hierarchy.
A voice still belongs to exactly one group but is budgeted by the whole ancestor chain. Pass noPolyphonyGroupParent to detach. Returns false (no-op) if it would create a cycle, or if the parent is MONO (only leaf groups may be MONO).
setPlaymode()
template<typename Cfg , typename Responder , typename MonoResponder > bool setPlaymode (uint64_t groupId, PlayMode pm, uint64_t features = static_cast<uint64_t>(MonoPlayModeFeatures::NONE))
Set a group's play mode.
Returns false (leaving the group unchanged) if a MONO mode is requested for a group that has children, since only leaf groups may be MONO.
getPlaymode()
template<typename Cfg , typename Responder , typename MonoResponder > VoiceManager< Cfg, Responder, MonoResponder >::PlayMode getPlaymode (uint64_t groupId) const
setStealingPriorityMode()
template<typename Cfg , typename Responder , typename MonoResponder > void setStealingPriorityMode (uint64_t groupId, StealingPriorityMode pm)
setMonoPriorityMode()
template<typename Cfg , typename Responder , typename MonoResponder > void setMonoPriorityMode (uint64_t groupId, MonoPriorityMode pm)
Member Data Documentation
MIDI1
template<typename Cfg , typename Responder , typename MonoResponder > enum sst::voicemanager::VoiceManager::MIDI1Dialect MIDI1
MULTI_VOICE
template<typename Cfg , typename Responder , typename MonoResponder > enum sst::voicemanager::VoiceManager::RepeatedKeyMode MULTI_VOICE
mpeGlobalChannel
template<typename Cfg , typename Responder , typename MonoResponder > int8_t mpeGlobalChannel {0}
mpeTimbreCC
template<typename Cfg , typename Responder , typename MonoResponder > constexpr int8_t mpeTimbreCC {74} static constexpr
responder
template<typename Cfg , typename Responder , typename MonoResponder > Responder& responder
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::Details::doMonoRetrigger(), VoiceManager< Cfg, Responder, MonoResponder >::Details::doMPEChannelPressure(), VoiceManager< Cfg, Responder, MonoResponder >::Details::doMPEPitchBend(), and VoiceManager< Cfg, Responder, MonoResponder >::Details::stealVoicesFromGroup().
monoResponder
template<typename Cfg , typename Responder , typename MonoResponder > MonoResponder& monoResponder
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::Details::doMonoChannelPressure(), and VoiceManager< Cfg, Responder, MonoResponder >::Details::doMonoPitchBend().
noPolyphonyGroupParent
template<typename Cfg , typename Responder , typename MonoResponder > constexpr uint64_t noPolyphonyGroupParent {std::numeric_limits<uint64_t>::max()} static constexpr
Pass as the parent to setPolyphonyGroupParent to detach a group, making it a root whose only super-constraint is the global voice pool.
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::Details::adjustSubtreeUsedVoices(), and VoiceManager< Cfg, Responder, MonoResponder >::Details::isDescendantOrSelf().
heldMIDIKeyByChannel
template<typename Cfg , typename Responder , typename MonoResponder > std::array<std::array<bool, 128>, 16> heldMIDIKeyByChannel
Referenced by VoiceManager< Cfg, Responder, MonoResponder >::VoiceManager().
The documentation for this struct was generated from the following files:
voicemanager.h
voicemanager_impl.h