sst-basic-blocks: sst::basic_blocks::dsp Namespace Reference
sst::basic_blocks::dsp Namespace Reference
Namespaces
pan_laws
Classes
struct lipol
struct lipol_sse
struct LagSmoothingStrategy
struct BlockInterpSmoothingStrategy
struct NoSmoothingStrategy
struct DPWSawOscillator
struct DPWPulseOscillator
struct LowPassEnvelopeFollower
struct SlewLimiter
struct RunningAverage
struct HilbertTransformMonoFloat
struct HilbertTransformStereoSSE
struct OnePoleLag
SurgeLag is a one simple pole LPF smoother.
struct SurgeLag
OnePoleLag is a better name for SurgeLag.
struct LinearLag
struct UIComponentLagHandler
Linearly lag a float value onto a destination.
struct LanczosResampler
struct DriftLFO
struct CharacterFilter
struct UnisonSetup
struct QuadratureOscillator
The recurrence oscillator from https://vicanek.de/articles/QuadOsc.pdf.
struct SurgeQuadrOsc
The Surge Magic Circle style Oscillator.
struct RNG
struct SSESincDelayLine
struct VUPeak
Functions
SIMD_M128 softclip_ps (SIMD_M128 in)
y = x - (4/27)*x^3, x in [-1.5 .
SIMD_M128 softclip8_ps (SIMD_M128 in)
y = x - (4/27/8^3)*x^3, x in [-12 .
SIMD_M128 tanh7_ps (SIMD_M128 v)
template<size_t blockSize>
void softclip_block (float *__restrict x)
template<size_t blockSize>
void tanh7_block (float *__restrict x)
template<size_t blockSize>
void hardclip_block (float *x)
template<size_t blockSize>
void hardclip_block8 (float *x)
float correlated_noise_o2mk2_supplied_value (float &lastval, float &lastval2, float correlation, const float bipolarUniformRandValue)
float correlated_noise_o2mk2_suppliedrng (float &lastval, float &lastval2, float correlation, std::function< float()> &urng)
float fastsin (float x) noexcept
SIMD_M128 fastsinSSE (SIMD_M128 x) noexcept
float fastcos (float x) noexcept
SIMD_M128 fastcosSSE (SIMD_M128 x) noexcept
float clampToPiRange (float x)
SIMD_M128 clampToPiRangeSSE (SIMD_M128 x)
float fasttanh (float x) noexcept
float fasttan (float x) noexcept
SIMD_M128 fasttanhSSE (SIMD_M128 x)
SIMD_M128 fasttanhSSEclamped (SIMD_M128 x)
float fastexp (float x) noexcept
SIMD_M128 fastexpSSE (SIMD_M128 x) noexcept
float cubic_ipol (float y0, float y1, float y2, float y3, float mu)
float quad_bspline (float y0, float y1, float y2, float mu)
template<size_t blocksize>
void encodeMS (const float *__restrict const L, const float *__restrict const R, float *__restrict M, float *__restrict S)
template<size_t blocksize>
void decodeMS (const float *__restrict const M, const float *__restrict const S, float *__restrict L, float *__restrict R)
double sincf (double x)
double sinc (double x)
double blackman (int i, int n)
double symmetric_blackman (double i, int n)
double blackman (double i, int n)
double blackman_harris (int i, int n)
double symmetric_blackman_harris (double i, int n)
double blackman_harris (double i, int n)
double hanning (int i, int n)
double hamming (int i, int n)
double BESSI0 (double X)
double symmetric_kaiser (double x, uint16_t nint, double Alpha)
Function Documentation
softclip_ps()
SIMD_M128 sst::basic_blocks::dsp::softclip_ps (SIMD_M128 in)
y = x - (4/27)*x^3, x in [-1.5 .
. 1.5], +/-1 otherwise
References SIMD_MM.
Referenced by softclip_block().
softclip8_ps()
SIMD_M128 sst::basic_blocks::dsp::softclip8_ps (SIMD_M128 in)
y = x - (4/27/8^3)*x^3, x in [-12 .
. 12], +/-12 otherwise
References SIMD_MM.
tanh7_ps()
SIMD_M128 sst::basic_blocks::dsp::tanh7_ps (SIMD_M128 v)
References SIMD_MM.
Referenced by tanh7_block().
softclip_block()
void sst::basic_blocks::dsp::softclip_block (float *__restrict x)
References SIMD_MM, and softclip_ps().
tanh7_block()
void sst::basic_blocks::dsp::tanh7_block (float *__restrict x)
References SIMD_MM, and tanh7_ps().
hardclip_block()
void sst::basic_blocks::dsp::hardclip_block (float * x)
References SIMD_MM.
hardclip_block8()
void sst::basic_blocks::dsp::hardclip_block8 (float * x)
References SIMD_MM.
correlated_noise_o2mk2_supplied_value()
float sst::basic_blocks::dsp::correlated_noise_o2mk2_supplied_value (float & lastval, float & lastval2, float correlation, const float bipolarUniformRandValue)
References SIMD_MM.
Referenced by correlated_noise_o2mk2_suppliedrng().
correlated_noise_o2mk2_suppliedrng()
float sst::basic_blocks::dsp::correlated_noise_o2mk2_suppliedrng (float & lastval, float & lastval2, float correlation, std::function< float()> & urng)
References correlated_noise_o2mk2_supplied_value().
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE >::process_block(), and SimpleLFO< SRProvider, BLOCK_SIZE >::SimpleLFO().
fastsin()
float sst::basic_blocks::dsp::fastsin (float x) noexcept
fastsinSSE()
SIMD_M128 sst::basic_blocks::dsp::fastsinSSE (SIMD_M128 x) noexcept
References A, C, F, M, S, and SIMD_MM.
fastcos()
float sst::basic_blocks::dsp::fastcos (float x) noexcept
fastcosSSE()
SIMD_M128 sst::basic_blocks::dsp::fastcosSSE (SIMD_M128 x) noexcept
References A, C, M, S, and SIMD_MM.
clampToPiRange()
float sst::basic_blocks::dsp::clampToPiRange (float x)
clampToPiRangeSSE()
SIMD_M128 sst::basic_blocks::dsp::clampToPiRangeSSE (SIMD_M128 x)
References SIMD_MM.
fasttanh()
float sst::basic_blocks::dsp::fasttanh (float x) noexcept
fasttan()
float sst::basic_blocks::dsp::fasttan (float x) noexcept
fasttanhSSE()
SIMD_M128 sst::basic_blocks::dsp::fasttanhSSE (SIMD_M128 x)
References A, M, and SIMD_MM.
Referenced by fasttanhSSEclamped().
fasttanhSSEclamped()
SIMD_M128 sst::basic_blocks::dsp::fasttanhSSEclamped (SIMD_M128 x)
References fasttanhSSE(), and SIMD_MM.
fastexp()
float sst::basic_blocks::dsp::fastexp (float x) noexcept
fastexpSSE()
SIMD_M128 sst::basic_blocks::dsp::fastexpSSE (SIMD_M128 x) noexcept
References A, F, M, and SIMD_MM.
cubic_ipol()
float sst::basic_blocks::dsp::cubic_ipol (float y0, float y1, float y2, float y3, float mu)
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE >::process_block().
quad_bspline()
float sst::basic_blocks::dsp::quad_bspline (float y0, float y1, float y2, float mu)
encodeMS()
void sst::basic_blocks::dsp::encodeMS (const float *__restrict const L, const float *__restrict const R, float *__restrict M, float *__restrict S)
References M, and S.
decodeMS()
void sst::basic_blocks::dsp::decodeMS (const float *__restrict const M, const float *__restrict const S, float *__restrict L, float *__restrict R)
References M, and S.
sincf()
double sst::basic_blocks::dsp::sincf (double x)
Referenced by ShortcircuitSincTableProvider::init(), and SurgeSincTableProvider::SurgeSincTableProvider().
sinc()
double sst::basic_blocks::dsp::sinc (double x)
blackman() [1/2]
double sst::basic_blocks::dsp::blackman (int i, int n)
symmetric_blackman()
double sst::basic_blocks::dsp::symmetric_blackman (double i, int n)
Referenced by SurgeSincTableProvider::SurgeSincTableProvider().
blackman() [2/2]
double sst::basic_blocks::dsp::blackman (double i, int n)
blackman_harris() [1/2]
double sst::basic_blocks::dsp::blackman_harris (int i, int n)
symmetric_blackman_harris()
double sst::basic_blocks::dsp::symmetric_blackman_harris (double i, int n)
blackman_harris() [2/2]
double sst::basic_blocks::dsp::blackman_harris (double i, int n)
hanning()
double sst::basic_blocks::dsp::hanning (int i, int n)
hamming()
double sst::basic_blocks::dsp::hamming (int i, int n)
BESSI0()
double sst::basic_blocks::dsp::BESSI0 (double X)
Referenced by symmetric_kaiser().
symmetric_kaiser()
double sst::basic_blocks::dsp::symmetric_kaiser (double x, uint16_t nint, double Alpha)
References BESSI0().
Referenced by ShortcircuitSincTableProvider::init().