sst-basic-blocks: sst::basic_blocks::mechanics Namespace Reference
sst::basic_blocks::mechanics Namespace Reference
Namespaces
detail
Functions
template<size_t blocksize>
void clear_block (float *__restrict f)
template<size_t blocksize>
void accumulate_from_to (const float *__restrict src, float *__restrict dst)
template<size_t blocksize>
void scale_accumulate_from_to (const float *__restrict src, float scale, float *__restrict dst)
template<size_t blocksize>
void scale_accumulate_from_to (const float *__restrict srcL, float *__restrict srcR, float scale, float *__restrict dstL, float *__restrict dstR)
template<size_t blocksize>
void copy_from_to (const float *__restrict src, float *__restrict dst)
template<size_t blocksize>
void add_block (const float *__restrict src1, const float *__restrict src2, float *__restrict dst)
template<size_t blocksize>
void add_block (float *__restrict srcdst, const float *__restrict src2)
template<size_t blockSize>
void mul_block (const float *__restrict const src1, const float *const src2, float *__restrict dst)
template<size_t blockSize>
void mul_block (float *__restrict src1, float scalar, float *__restrict dst)
template<size_t blockSize>
void mul_block (float *__restrict srcDst, float *__restrict by)
template<size_t blockSize>
void mul_block (float *__restrict srcDst, float by)
template<size_t blockSize>
void scale_by (const float *__restrict scale, float *__restrict target)
template<size_t blockSize>
void scale_by (const float *__restrict scale, float *__restrict targetL, float *__restrict targetR)
template<size_t blockSize>
void scale_by (const float scale, float *__restrict target)
template<size_t blockSize>
void scale_by (const float scale, float *__restrict targetL, float *__restrict targetR)
template<size_t blockSize>
float blockAbsMax (const float *__restrict d)
uint16_t swap_endian_16 (uint16_t x)
uint32_t swap_endian_32 (uint32_t x)
int endian_write_int32LE (uint32_t t)
auto endian_read_int32LE (uint32_t a)
float endian_write_float32LE (float f)
int endian_write_int32BE (uint32_t t)
auto endian_read_int32BE (uint32_t a)
short endian_write_int16LE (uint16_t t)
auto endian_read_int16LE (uint16_t a)
uint16_t endian_write_int16BE (uint16_t t)
auto endian_read_int16BE (uint16_t a)
auto endian_copyblock16LE (int16_t *dst, int16_t *src, size_t count)
auto endian_copyblock32LE (int32_t *dst, int32_t *src, size_t count)
SIMD_M128 sum_ps_to_ss (SIMD_M128 x)
float sum_ps_to_float (SIMD_M128 x)
SIMD_M128 abs_ps (SIMD_M128 x)
float rcp (float x)
Variables
const auto m128_mask_signbit = SIMD_MM(set1_ps)(detail::i2f_binary_cast(0x80000000))
const auto m128_mask_absval = SIMD_MM(set1_ps)(detail::i2f_binary_cast(0x7fffffff))
Function Documentation
clear_block()
void sst::basic_blocks::mechanics::clear_block (float *__restrict f)
accumulate_from_to()
void sst::basic_blocks::mechanics::accumulate_from_to (const float *__restrict src, float *__restrict dst)
scale_accumulate_from_to() [1/2]
void sst::basic_blocks::mechanics::scale_accumulate_from_to (const float *__restrict src, float scale, float *__restrict dst)
scale_accumulate_from_to() [2/2]
void sst::basic_blocks::mechanics::scale_accumulate_from_to (const float *__restrict srcL, float *__restrict srcR, float scale, float *__restrict dstL, float *__restrict dstR)
copy_from_to()
void sst::basic_blocks::mechanics::copy_from_to (const float *__restrict src, float *__restrict dst)
add_block() [1/2]
void sst::basic_blocks::mechanics::add_block (const float *__restrict src1, const float *__restrict src2, float *__restrict dst)
add_block() [2/2]
void sst::basic_blocks::mechanics::add_block (float *__restrict srcdst, const float *__restrict src2)
mul_block() [1/4]
void sst::basic_blocks::mechanics::mul_block (const float *__restrict const src1, const float *const src2, float *__restrict dst)
mul_block() [2/4]
void sst::basic_blocks::mechanics::mul_block (float *__restrict src1, float scalar, float *__restrict dst)
mul_block() [3/4]
void sst::basic_blocks::mechanics::mul_block (float *__restrict srcDst, float *__restrict by)
mul_block() [4/4]
void sst::basic_blocks::mechanics::mul_block (float *__restrict srcDst, float by)
scale_by() [1/4]
void sst::basic_blocks::mechanics::scale_by (const float *__restrict scale, float *__restrict target)
scale_by() [2/4]
void sst::basic_blocks::mechanics::scale_by (const float *__restrict scale, float *__restrict targetL, float *__restrict targetR)
scale_by() [3/4]
void sst::basic_blocks::mechanics::scale_by (const float scale, float *__restrict target)
scale_by() [4/4]
void sst::basic_blocks::mechanics::scale_by (const float scale, float *__restrict targetL, float *__restrict targetR)
blockAbsMax()
float sst::basic_blocks::mechanics::blockAbsMax (const float *__restrict d)
swap_endian_16()
uint16_t sst::basic_blocks::mechanics::swap_endian_16 (uint16_t x)
swap_endian_32()
uint32_t sst::basic_blocks::mechanics::swap_endian_32 (uint32_t x)
Referenced by endian_write_float32LE(), endian_write_int32BE(), and endian_write_int32LE().
endian_write_int32LE()
int sst::basic_blocks::mechanics::endian_write_int32LE (uint32_t t)
References swap_endian_32().
Referenced by endian_read_int32LE().
endian_read_int32LE()
auto sst::basic_blocks::mechanics::endian_read_int32LE (uint32_t a)
References endian_write_int32LE().
endian_write_float32LE()
float sst::basic_blocks::mechanics::endian_write_float32LE (float f)
References swap_endian_32().
endian_write_int32BE()
int sst::basic_blocks::mechanics::endian_write_int32BE (uint32_t t)
References swap_endian_32().
Referenced by endian_read_int32BE().
endian_read_int32BE()
auto sst::basic_blocks::mechanics::endian_read_int32BE (uint32_t a)
References endian_write_int32BE().
endian_write_int16LE()
short sst::basic_blocks::mechanics::endian_write_int16LE (uint16_t t)
Referenced by endian_read_int16LE().
endian_read_int16LE()
auto sst::basic_blocks::mechanics::endian_read_int16LE (uint16_t a)
References endian_write_int16LE().
endian_write_int16BE()
uint16_t sst::basic_blocks::mechanics::endian_write_int16BE (uint16_t t)
Referenced by endian_read_int16BE().
endian_read_int16BE()
auto sst::basic_blocks::mechanics::endian_read_int16BE (uint16_t a)
References endian_write_int16BE().
endian_copyblock16LE()
auto sst::basic_blocks::mechanics::endian_copyblock16LE (int16_t * dst, int16_t * src, size_t count)
endian_copyblock32LE()
auto sst::basic_blocks::mechanics::endian_copyblock32LE (int32_t * dst, int32_t * src, size_t count)
sum_ps_to_ss()
SIMD_M128 sst::basic_blocks::mechanics::sum_ps_to_ss (SIMD_M128 x)
References SIMD_MM, and SIMD_MM_SHUFFLE.
Referenced by SSESincDelayLine< COMB_SIZE >::read(), and sum_ps_to_float().
sum_ps_to_float()
float sst::basic_blocks::mechanics::sum_ps_to_float (SIMD_M128 x)
References SIMD_MM, and sum_ps_to_ss().
Referenced by LanczosResampler< blockSize >::read().
abs_ps()
SIMD_M128 sst::basic_blocks::mechanics::abs_ps (SIMD_M128 x)
References m128_mask_absval, and SIMD_MM.
rcp()
float sst::basic_blocks::mechanics::rcp (float x)
References SIMD_MM.
Variable Documentation
m128_mask_signbit
const auto m128_mask_signbit = SIMD_MM(set1_ps)(detail::i2f_binary_cast(0x80000000))
m128_mask_absval
const auto m128_mask_absval = SIMD_MM(set1_ps)(detail::i2f_binary_cast(0x7fffffff))
Referenced by abs_ps().