sst-basic-blocks: sst::basic_blocks::tables::temposync::detail Namespace Reference
sst::basic_blocks::tables::temposync::detail Namespace Reference
Functions
constexpr std::array< Note, zNEntries > buildEntries ()
constexpr std::array< int, zNEntries > buildReverse (const std::array< Note, zNEntries > &e)
constexpr std::array< double, zNEntries > buildInverseBeats (const std::array< Note, zNEntries > &e)
Variables
constexpr int zMinExp {-5}
constexpr int zMaxExp {5}
constexpr int zNEntries {(zMaxExp - zMinExp + 1) * 3}
constexpr auto zEntries {buildEntries()}
constexpr auto zReverse {buildReverse(zEntries)}
constexpr auto zInverseBeats {buildInverseBeats(zEntries)}
Function Documentation
buildEntries()
constexpr std::array< Note, zNEntries > buildEntries () constexpr
References Note::Dotted, Note::Straight, Note::Triplet, zMaxExp, and zMinExp.
buildReverse()
constexpr std::array< int, zNEntries > buildReverse (const std::array< Note, zNEntries > & e) constexpr
References zMinExp, and zNEntries.
buildInverseBeats()
constexpr std::array< double, zNEntries > buildInverseBeats (const std::array< Note, zNEntries > & e) constexpr
References zNEntries.
Variable Documentation
zMinExp
constexpr int zMinExp {-5} constexpr
Referenced by buildEntries(), and buildReverse().
zMaxExp
constexpr int zMaxExp {5} constexpr
Referenced by buildEntries().
zNEntries
constexpr int zNEntries {(zMaxExp - zMinExp + 1) * 3} constexpr
Referenced by buildInverseBeats(), and buildReverse().
zEntries
constexpr auto zEntries {buildEntries()} constexpr
zReverse
constexpr auto zReverse {buildReverse(zEntries)} constexpr
Referenced by ZeroOne::indexFor(), and ZeroOne::toFloat().
zInverseBeats
constexpr auto zInverseBeats {buildInverseBeats(zEntries)} constexpr
Referenced by ZeroOne::inverseBeatsFromFloat().