sst-basic-blocks: sst::basic_blocks::tables::temposync Namespace Reference
sst::basic_blocks::tables::temposync Namespace Reference
Namespaces
namespace detail
Classes
struct Note
struct TwoToThe
struct ZeroOne
Enumerations
enum class Flavor { TWO_TO_THE , ZERO_ONE }
Functions
constexpr double secondsFor (const Note &n, double bpm)
std::string toStringCompact (const Note &n)
std::string toString (const Note &n)
std::optional< Note > fromString (const std::string &s)
Enumeration Type Documentation
Flavor
enum class Flavor strong
Enumerator
TWO_TO_THE
ZERO_ONE
Function Documentation
secondsFor()
constexpr double secondsFor (const Note & n, double bpm) constexpr
References Note::beats.
toStringCompact()
std::string toStringCompact (const Note & n)
References Note::Dotted, Note::exponent, Note::isZero(), Note::modifier, Note::Straight, and Note::Triplet.
toString()
std::string toString (const Note & n)
References Note::Dotted, Note::exponent, Note::isZero(), Note::modifier, Note::Straight, and Note::Triplet.
Referenced by ParamMetaData::temposyncNotation().
fromString()
std::optional< Note > fromString (const std::string & s)
References Note::Dotted, Note::Straight, Note::Triplet, and Note::zeroStage().
Referenced by ParamMetaData::valueFromTemposyncNotation().