sst-basic-blocks: FXModControl< blockSize, RB, externalSineTable > Struct Template Reference
FXModControl< blockSize, RB, externalSineTable > Struct Template Reference
#include <FXModControl.h>
Public Types
enum mod_waves {
mod_sine = 0 , mod_tri , mod_saw , mod_ramp ,
mod_square , mod_noise , mod_snh
}
Public Member Functions
FXModControl (float sr, float sri, float *sineTable=nullptr)
FXModControl ()
~FXModControl ()
void setSampleRate (double sr)
void processStartOfBlock (int mwave, float rate, float depth, float phase_offset, float width=1.0)
float value () const noexcept
float nextValueInBlock ()
std::array< float, 2 > valueStereo () const noexcept
std::array< float, 2 > nextStereoValueInBlock ()
std::array< float, 4 > valueQuad () const noexcept
std::array< float, 4 > nextQuadValueInBlock ()
SIMD_M128 valueQuadSSE () const noexcept
SIMD_M128 nextQuadValueInBlockSSE ()
void process ()
std::array< float, 4 > getLastPhase ()
Public Attributes
float samplerate {0}
float samplerate_inv {0}
sst::basic_blocks::dsp::RNG rng
Member Enumeration Documentation
mod_waves
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> enum mod_waves
Enumerator
mod_sine
mod_tri
mod_saw
mod_ramp
mod_square
mod_noise
mod_snh
Constructor & Destructor Documentation
FXModControl() [1/2]
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> FXModControl (float sr, float sri, float * sineTable = nullptr)
FXModControl() [2/2]
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> FXModControl ()
~FXModControl()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> ~FXModControl ()
Member Function Documentation
setSampleRate()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> void setSampleRate (double sr)
References FXModControl< blockSize, RB, externalSineTable >::samplerate, and FXModControl< blockSize, RB, externalSineTable >::samplerate_inv.
processStartOfBlock()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> void processStartOfBlock (int mwave, float rate, float depth, float phase_offset, float width = 1.0)
References ADD, DIV, FXModControl< blockSize, RB, externalSineTable >::mod_noise, FXModControl< blockSize, RB, externalSineTable >::mod_ramp, FXModControl< blockSize, RB, externalSineTable >::mod_saw, FXModControl< blockSize, RB, externalSineTable >::mod_sine, FXModControl< blockSize, RB, externalSineTable >::mod_snh, FXModControl< blockSize, RB, externalSineTable >::mod_square, FXModControl< blockSize, RB, externalSineTable >::mod_tri, MUL, lipol< T, defaultBlockSize, first_run_checks >::newValue(), sst::basic_blocks::modulators::rnd_dual_stereo, sst::basic_blocks::modulators::rnd_quad, sst::basic_blocks::modulators::rnd_single, FXModControl< blockSize, RB, externalSineTable >::rng, FXModControl< blockSize, RB, externalSineTable >::samplerate, SIMD_M128, SIMD_MM, SUB, and RNG::unifPM1().
value()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> float value () const noexcept
References lipol< T, defaultBlockSize, first_run_checks >::v.
Referenced by FXModControl< blockSize, RB, externalSineTable >::nextValueInBlock().
nextValueInBlock()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> float nextValueInBlock ()
References FXModControl< blockSize, RB, externalSineTable >::process(), and FXModControl< blockSize, RB, externalSineTable >::value().
valueStereo()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> std::array< float, 2 > valueStereo () const noexcept
References lipol< T, defaultBlockSize, first_run_checks >::v.
Referenced by FXModControl< blockSize, RB, externalSineTable >::nextStereoValueInBlock().
nextStereoValueInBlock()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> std::array< float, 2 > nextStereoValueInBlock ()
References FXModControl< blockSize, RB, externalSineTable >::process(), and FXModControl< blockSize, RB, externalSineTable >::valueStereo().
valueQuad()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> std::array< float, 4 > valueQuad () const noexcept
References lipol< T, defaultBlockSize, first_run_checks >::v.
Referenced by FXModControl< blockSize, RB, externalSineTable >::nextQuadValueInBlock().
nextQuadValueInBlock()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> std::array< float, 4 > nextQuadValueInBlock ()
References FXModControl< blockSize, RB, externalSineTable >::process(), and FXModControl< blockSize, RB, externalSineTable >::valueQuad().
valueQuadSSE()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> SIMD_M128 valueQuadSSE () const noexcept
References MUL, SIMD_MM, and lipol< T, defaultBlockSize, first_run_checks >::v.
Referenced by FXModControl< blockSize, RB, externalSineTable >::nextQuadValueInBlockSSE().
nextQuadValueInBlockSSE()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> SIMD_M128 nextQuadValueInBlockSSE ()
References FXModControl< blockSize, RB, externalSineTable >::process(), and FXModControl< blockSize, RB, externalSineTable >::valueQuadSSE().
process()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> void process ()
References lipol< T, defaultBlockSize, first_run_checks >::process().
Referenced by FXModControl< blockSize, RB, externalSineTable >::nextQuadValueInBlock(), FXModControl< blockSize, RB, externalSineTable >::nextQuadValueInBlockSSE(), FXModControl< blockSize, RB, externalSineTable >::nextStereoValueInBlock(), and FXModControl< blockSize, RB, externalSineTable >::nextValueInBlock().
getLastPhase()
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> std::array< float, 4 > getLastPhase ()
Member Data Documentation
samplerate
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> float samplerate {0}
Referenced by FXModControl< blockSize, RB, externalSineTable >::processStartOfBlock(), and FXModControl< blockSize, RB, externalSineTable >::setSampleRate().
samplerate_inv
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> float samplerate_inv {0}
Referenced by FXModControl< blockSize, RB, externalSineTable >::setSampleRate().
rng
template<int blockSize, RandomBehavior RB = rnd_dual_stereo, bool externalSineTable = false> sst::basic_blocks::dsp::RNG rng
Referenced by FXModControl< blockSize, RB, externalSineTable >::processStartOfBlock().
The documentation for this struct was generated from the following file:
FXModControl.h