sst-basic-blocks: LagCollection< N >::Lagger Struct Reference
LagCollection< N >::Lagger Struct Reference
#include <LagCollection.h>
Inherits participant.
Public Member Functions
void process ()
void snapToTarget ()
void apply ()
Public Attributes
float * onto {nullptr}
LinearLag< float, true > lag
int index
Member Function Documentation
process()
template<int N> void process ()
References LagCollection< N >::Lagger::apply(), LagCollection< N >::Lagger::lag, and LinearLag< T, first_run >::process().
snapToTarget()
template<int N> void snapToTarget ()
References LagCollection< N >::Lagger::apply(), LagCollection< N >::Lagger::lag, and LinearLag< T, first_run >::snapToTarget().
apply()
template<int N> void apply ()
References LagCollection< N >::Lagger::lag, LagCollection< N >::Lagger::onto, and LinearLag< T, first_run >::v.
Referenced by LagCollection< N >::Lagger::process(), and LagCollection< N >::Lagger::snapToTarget().
Member Data Documentation
onto
template<int N> float* onto {nullptr}
Referenced by LagCollection< N >::Lagger::apply().
lag
template<int N> LinearLag<float, true> lag
Referenced by LagCollection< N >::Lagger::apply(), LagCollection< N >::Lagger::process(), and LagCollection< N >::Lagger::snapToTarget().
index
template<int N> int index
The documentation for this struct was generated from the following file:
LagCollection.h