sst-basic-blocks: LagCollectionBase< N, T > Struct Template Reference
LagCollectionBase< N, T > Struct Template Reference
LagCollectionBase is a bucket of laggers which act as a group and allow you to easily manage the active set.
#include <LagCollection.h>
Classes
struct Lagger
Public Member Functions
T * asT ()
const T * asT () const
LagCollectionBase ()
void setRateInMilliseconds (double rate, double sampleRate, double blockSizeInv)
void setTargetValue (size_t index, float target)
void processAll ()
void snapAllActiveToTarget ()
Public Attributes
std::array< Lagger, N > lags
sst::cpputils::active_set_overlay< Lagger > activeSet
Detailed Description
template<int N, typename T>
struct sst::basic_blocks::dsp::LagCollectionBase< N, T >
LagCollectionBase is a bucket of laggers which act as a group and allow you to easily manage the active set.
Basically use it with <128> to smooth midi ccs and stuff like that
Template Parameters
N how many laggers to have
Constructor & Destructor Documentation
LagCollectionBase()
template<int N, typename T > LagCollectionBase ()
References LagCollectionBase< N, T >::asT(), and LagCollectionBase< N, T >::lags.
Member Function Documentation
asT() [1/2]
template<int N, typename T > T * asT ()
Referenced by LagCollectionBase< N, T >::LagCollectionBase(), LagCollectionBase< N, T >::processAll(), and LagCollectionBase< N, T >::snapAllActiveToTarget().
asT() [2/2]
template<int N, typename T > const T * asT () const
setRateInMilliseconds()
template<int N, typename T > void setRateInMilliseconds (double rate, double sampleRate, double blockSizeInv)
References LagCollectionBase< N, T >::lags.
setTargetValue()
template<int N, typename T > void setTargetValue (size_t index, float target)
References LagCollectionBase< N, T >::activeSet, and LagCollectionBase< N, T >::lags.
processAll()
template<int N, typename T > void processAll ()
References LagCollectionBase< N, T >::activeSet, and LagCollectionBase< N, T >::asT().
snapAllActiveToTarget()
template<int N, typename T > void snapAllActiveToTarget ()
References LagCollectionBase< N, T >::activeSet, and LagCollectionBase< N, T >::asT().
Member Data Documentation
lags
template<int N, typename T > std::array<Lagger, N> lags
Referenced by LagCollectionBase< N, T >::LagCollectionBase(), LagCollectionBase< N, T >::setRateInMilliseconds(), and LagCollectionBase< N, T >::setTargetValue().
activeSet
template<int N, typename T > sst::cpputils::active_set_overlay<Lagger> activeSet
Referenced by LagCollectionBase< N, T >::processAll(), LagCollectionBase< N, T >::setTargetValue(), and LagCollectionBase< N, T >::snapAllActiveToTarget().
The documentation for this struct was generated from the following file:
LagCollection.h