sst-basic-blocks: AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider > Struct Template Reference
AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider > Struct Template Reference
#include <AHDSRShapedSC.h>
Public Types
using base_t = DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
Public Types inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
enum Stage {
s_delay , s_attack , s_hold , s_decay ,
s_sustain , s_release , s_analog_residual_decay , s_analog_residual_release ,
s_eoc , s_complete
}
Public Member Functions
AHDSRShapedSC (const SRProvider *s)
bool isZero (float f)
void attackFromWithDelay (float from, float delay, float attack)
void attackFrom (float fv, bool skipAttack=false)
float dPhase (float x)
double fastPow (double a, double b)
float kernel (float p, float shape)
void processCore (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve, const float rateMul=1.0)
void process (const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive)
void processBlock (const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve)
void processBlockWithDelay (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve)
void processBlockWithDelayAndRateMul (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const float rateMul, const bool gateActive, bool needsCurve)
Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
DiscreteStagesEnvelope ()
void resetCurrent ()
bool preBlockCheck ()
float shapeTarget (float target, int ashape, int dshape, int rshape=0)
void updateBlockTo (float target)
void updateBlockToNoCube (float target)
void step ()
void immediatelySilence ()
float rateFrom01 (float r01)
float rateTo01 (float r)
float deltaTo01 (float d)
Static Public Member Functions
static double timeInSecondsFromParam (double p)
static void initializeLuts ()
Static Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etminV ()
static constexpr float etmaxV ()
Public Attributes
const SRProvider * srProvider {nullptr}
float lastDPhaseX {-1234.56789}
float lastDPhase {0}
float lastSR {0}
float phase {0.f}
float attackStartValue {0.f}
float releaseStartValue {0.f}
float delayValue {0.f}
Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
float output {0}
float outputCubed {0}
float eoc_output {0}
float outputCache [BLOCK_SIZE]
float outBlock0 {0.f}
float outputCacheCubed [BLOCK_SIZE]
int current {BLOCK_SIZE}
int eoc_countdown {0}
enum sst::basic_blocks::modulators::DiscreteStagesEnvelope::Stage s_complete
Static Public Attributes
static constexpr int nTables {64}
static constexpr int nLUTPoints {256}
static float lut [nTables][nLUTPoints]
static bool lutsInitialized {false}
static constexpr size_t expLutSize {1024}
static float expLut [expLutSize]
Static Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etMin {etminV()}
static constexpr float etMax {etmaxV()}
static constexpr float etScale {etMax - etMin}
static constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE}
Member Typedef Documentation
base_t
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> using base_t = DiscreteStagesEnvelope<BLOCK_SIZE, RangeProvider>
Constructor & Destructor Documentation
AHDSRShapedSC()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> AHDSRShapedSC (const SRProvider * s)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::initializeLuts(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::srProvider.
Member Function Documentation
timeInSecondsFromParam()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> static double timeInSecondsFromParam (double p) static
References sst::basic_blocks::modulators::ENVTIME_EXP.
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::initializeLuts().
initializeLuts()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> static void initializeLuts () static
References sst::basic_blocks::modulators::ENVTIME_EXP, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::expLut, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::expLutSize, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::lutsInitialized, and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::timeInSecondsFromParam().
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::AHDSRShapedSC().
isZero()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> bool isZero (float f)
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFromWithDelay(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
attackFromWithDelay()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void attackFromWithDelay (float from, float delay, float attack)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::delayValue, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::isZero(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::phase, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay.
attackFrom()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void attackFrom (float fv, bool skipAttack = false)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackStartValue, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::phase, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_hold.
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFromWithDelay().
dPhase()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float dPhase (float x)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), sst::basic_blocks::modulators::ENVTIME_2TWOX, sst::basic_blocks::modulators::ENVTIME_EXP, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etMin, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::expLut, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::expLutSize, TwoToTheXProvider::init(), TwoToTheXProvider::isInit, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::lastDPhase, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::lastDPhaseX, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::lastSR, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::srProvider, and TwoToTheXProvider::twoToThe().
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
fastPow()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> double fastPow (double a, double b)
kernel()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float kernel (float p, float shape)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::phase.
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
processCore()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void processCore (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve, const float rateMul = 1.0)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackStartValue, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::delayValue, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::isZero(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::kernel(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::phase, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::releaseStartValue, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_complete, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_decay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_hold, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_sustain, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockToNoCube().
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::process(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processBlock(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processBlockWithDelay(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processBlockWithDelayAndRateMul().
process()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void process (const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::lutsInitialized, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step().
processBlock()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void processBlock (const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
processBlockWithDelay()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void processBlockWithDelay (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const bool gateActive, bool needsCurve)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
processBlockWithDelayAndRateMul()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void processBlockWithDelayAndRateMul (const float delay, const float a, const float h, const float d, const float s, const float r, const float ashape, const float dshape, const float rshape, const float rateMul, const bool gateActive, bool needsCurve)
References AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
Member Data Documentation
nTables
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> constexpr int nTables {64} static constexpr
nLUTPoints
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> constexpr int nLUTPoints {256} static constexpr
lut
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float lut[nTables][nLUTPoints] static
lutsInitialized
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> bool lutsInitialized {false} static
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::initializeLuts(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::process().
expLutSize
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> constexpr size_t expLutSize {1024} static constexpr
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::initializeLuts().
expLut
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float expLut[expLutSize] static
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::initializeLuts().
srProvider
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> const SRProvider* srProvider {nullptr}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::AHDSRShapedSC(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase().
lastDPhaseX
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float lastDPhaseX {-1234.56789}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase().
lastDPhase
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float lastDPhase {0}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase().
lastSR
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float lastSR {0}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase().
phase
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float phase {0.f}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFromWithDelay(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::kernel(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
attackStartValue
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float attackStartValue {0.f}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
releaseStartValue
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float releaseStartValue {0.f}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
delayValue
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float delayValue {0.f}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFromWithDelay(), and AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
The documentation for this struct was generated from the following file:
AHDSRShapedSC.h