sst-basic-blocks: quadDelayLine< COMB_SIZE > Struct Template Reference
quadDelayLine< COMB_SIZE > Struct Template Reference
#include <SSESincDelayLine.h>
Public Member Functions
quadDelayLine ()
void write (SIMD_M128 val)
SIMD_M128 read (SIMD_M128 delay)
void clear ()
Public Attributes
float buffer [COMB_SIZE]
SIMD_M128I lineOffsets = SIMD_MM(set_epi32)(lineSize * 3, lineSize * 2, lineSize, 0)
const SIMD_M128I combMaskSSE = SIMD_MM(set1_epi32)(combMask)
SIMD_M128I wpSSE = lineOffsets
const SIMD_M128I ONE = SIMD_MM(set1_epi32)(1)
const SIMD_M128I ZERO = SIMD_MM(setzero_si128)()
const SIMD_M128 ONEF = SIMD_MM(set1_ps)(1.f)
Static Public Attributes
static constexpr int lineSize {COMB_SIZE / 4}
static constexpr int combMask {COMB_SIZE - 1}
Constructor & Destructor Documentation
quadDelayLine()
template<int COMB_SIZE> quadDelayLine ()
References quadDelayLine< COMB_SIZE >::clear().
Member Function Documentation
write()
template<int COMB_SIZE> void write (SIMD_M128 val)
References quadDelayLine< COMB_SIZE >::buffer, quadDelayLine< COMB_SIZE >::combMaskSSE, quadDelayLine< COMB_SIZE >::ONE, SIMD_MM, and quadDelayLine< COMB_SIZE >::wpSSE.
read()
template<int COMB_SIZE> SIMD_M128 read (SIMD_M128 delay)
References ADD, quadDelayLine< COMB_SIZE >::buffer, quadDelayLine< COMB_SIZE >::combMaskSSE, MUL, quadDelayLine< COMB_SIZE >::ONE, quadDelayLine< COMB_SIZE >::ONEF, SIMD_MM, SUB, quadDelayLine< COMB_SIZE >::wpSSE, and quadDelayLine< COMB_SIZE >::ZERO.
clear()
template<int COMB_SIZE> void clear ()
References quadDelayLine< COMB_SIZE >::buffer, quadDelayLine< COMB_SIZE >::lineOffsets, and quadDelayLine< COMB_SIZE >::wpSSE.
Referenced by quadDelayLine< COMB_SIZE >::quadDelayLine().
Member Data Documentation
buffer
template<int COMB_SIZE> float buffer[COMB_SIZE]
Referenced by quadDelayLine< COMB_SIZE >::clear(), quadDelayLine< COMB_SIZE >::read(), and quadDelayLine< COMB_SIZE >::write().
lineSize
template<int COMB_SIZE> constexpr int lineSize {COMB_SIZE / 4} static constexpr
lineOffsets
template<int COMB_SIZE> SIMD_M128I lineOffsets = SIMD_MM(set_epi32)(lineSize * 3, lineSize * 2, lineSize, 0)
Referenced by quadDelayLine< COMB_SIZE >::clear().
combMask
template<int COMB_SIZE> constexpr int combMask {COMB_SIZE - 1} static constexpr
combMaskSSE
template<int COMB_SIZE> const SIMD_M128I combMaskSSE = SIMD_MM(set1_epi32)(combMask)
Referenced by quadDelayLine< COMB_SIZE >::read(), and quadDelayLine< COMB_SIZE >::write().
wpSSE
template<int COMB_SIZE> SIMD_M128I wpSSE = lineOffsets
Referenced by quadDelayLine< COMB_SIZE >::clear(), quadDelayLine< COMB_SIZE >::read(), and quadDelayLine< COMB_SIZE >::write().
ONE
template<int COMB_SIZE> const SIMD_M128I ONE = SIMD_MM(set1_epi32)(1)
Referenced by quadDelayLine< COMB_SIZE >::read(), and quadDelayLine< COMB_SIZE >::write().
ZERO
template<int COMB_SIZE> const SIMD_M128I ZERO = SIMD_MM(setzero_si128)()
Referenced by quadDelayLine< COMB_SIZE >::read().
ONEF
template<int COMB_SIZE> const SIMD_M128 ONEF = SIMD_MM(set1_ps)(1.f)
Referenced by quadDelayLine< COMB_SIZE >::read().
The documentation for this struct was generated from the following file:
SSESincDelayLine.h