sst-basic-blocks: LinearLag< T, first_run > Struct Template Reference
LinearLag< T, first_run > Struct Template Reference
#include <Lag.h>
Public Member Functions
LinearLag ()
void setRateInMilliseconds (double miliSeconds, double sampleRate, double blockSizeInv)
void setTarget (T f)
void snapTo (T f)
void snapToTarget ()
T getTargetValue () const
T getValue () const
void process ()
bool isActive () const
Public Attributes
T v {0}
T target_v {0}
Constructor & Destructor Documentation
LinearLag()
template<typename T , bool first_run> LinearLag ()
Member Function Documentation
setRateInMilliseconds()
template<typename T , bool first_run> void setRateInMilliseconds (double miliSeconds, double sampleRate, double blockSizeInv)
setTarget()
template<typename T , bool first_run> void setTarget (T f)
References LinearLag< T, first_run >::snapToTarget(), LinearLag< T, first_run >::target_v, and LinearLag< T, first_run >::v.
snapTo()
template<typename T , bool first_run> void snapTo (T f)
References LinearLag< T, first_run >::target_v, and LinearLag< T, first_run >::v.
Referenced by LinearLag< T, first_run >::snapToTarget().
snapToTarget()
template<typename T , bool first_run> void snapToTarget ()
References LinearLag< T, first_run >::snapTo(), and LinearLag< T, first_run >::target_v.
Referenced by LinearLag< T, first_run >::setTarget(), and LagCollection< N >::Lagger::snapToTarget().
getTargetValue()
template<typename T , bool first_run> T getTargetValue () const
References LinearLag< T, first_run >::target_v.
getValue()
template<typename T , bool first_run> T getValue () const
References LinearLag< T, first_run >::v.
process()
template<typename T , bool first_run> void process ()
References LinearLag< T, first_run >::target_v, and LinearLag< T, first_run >::v.
Referenced by LagCollection< N >::Lagger::process().
isActive()
template<typename T , bool first_run> bool isActive () const
Member Data Documentation
v
template<typename T , bool first_run> T v {0}
Referenced by LagCollection< N >::Lagger::apply(), LinearLag< T, first_run >::getValue(), LinearLag< T, first_run >::process(), LinearLag< T, first_run >::setTarget(), and LinearLag< T, first_run >::snapTo().
target_v
template<typename T , bool first_run> T target_v {0}
Referenced by LinearLag< T, first_run >::getTargetValue(), LinearLag< T, first_run >::process(), LinearLag< T, first_run >::setTarget(), LinearLag< T, first_run >::snapTo(), and LinearLag< T, first_run >::snapToTarget().
The documentation for this struct was generated from the following file:
Lag.h