sst-basic-blocks: ShortcircuitSincTableProvider Struct Reference
ShortcircuitSincTableProvider Struct Reference
#include <SincTableProvider.h>
Public Member Functions
void init ()
Public Attributes
float SincTableF32 [(FIRipol_M+1) *FIRipol_N]
float SincOffsetF32 [(FIRipol_M) *FIRipol_N]
short SincTableI16 [(FIRipol_M+1) *FIRipol_N]
short SincOffsetI16 [(FIRipol_M) *FIRipol_N]
Static Public Attributes
static constexpr uint32_t FIRipol_M = 256
static constexpr uint32_t FIRipol_N = 16
static constexpr uint32_t FIRipolI16_N = 16
static constexpr uint32_t FIRoffset = 8
Member Function Documentation
init()
void init ()
References ShortcircuitSincTableProvider::FIRipol_M, ShortcircuitSincTableProvider::FIRipol_N, ShortcircuitSincTableProvider::FIRipolI16_N, sst::basic_blocks::dsp::sincf(), ShortcircuitSincTableProvider::SincOffsetF32, ShortcircuitSincTableProvider::SincOffsetI16, ShortcircuitSincTableProvider::SincTableF32, ShortcircuitSincTableProvider::SincTableI16, and sst::basic_blocks::dsp::symmetric_kaiser().
Member Data Documentation
FIRipol_M
constexpr uint32_t FIRipol_M = 256 static constexpr
Referenced by ShortcircuitSincTableProvider::init().
FIRipol_N
constexpr uint32_t FIRipol_N = 16 static constexpr
Referenced by ShortcircuitSincTableProvider::init().
FIRipolI16_N
constexpr uint32_t FIRipolI16_N = 16 static constexpr
Referenced by ShortcircuitSincTableProvider::init().
FIRoffset
constexpr uint32_t FIRoffset = 8 static constexpr
SincTableF32
float SincTableF32[(FIRipol_M+1) *FIRipol_N]
Referenced by ShortcircuitSincTableProvider::init().
SincOffsetF32
float SincOffsetF32[(FIRipol_M) *FIRipol_N]
Referenced by ShortcircuitSincTableProvider::init().
SincTableI16
short SincTableI16[(FIRipol_M+1) *FIRipol_N]
Referenced by ShortcircuitSincTableProvider::init().
SincOffsetI16
short SincOffsetI16[(FIRipol_M) *FIRipol_N]
Referenced by ShortcircuitSincTableProvider::init().
The documentation for this struct was generated from the following file:
SincTableProvider.h