sst-basic-blocks: ZeroOne Struct Reference
ZeroOne Struct Reference
#include <TemposyncSupport.h>
Public Types
using Modifier = Note::Modifier
Static Public Member Functions
static constexpr int indexFromZeroOne (float v)
static constexpr float zeroOneFromIndex (int idx)
static constexpr float snap (float v)
static constexpr Note fromFloat (float v, bool zeroAtBottom=false)
static constexpr float toFloat (const Note &n, bool zeroAtBottom=false)
static constexpr double beatsFromFloat (float v, bool zeroAtBottom=false)
static constexpr double inverseBeatsFromFloat (float v, bool zeroAtBottom=false)
static constexpr double interpolatedBeatsFromFloat (float v, bool zeroAtBottom=false)
static constexpr int baseIndexOf (int idx)
static constexpr Modifier modifierOf (int idx)
static constexpr int indexFor (int baseIndex, Modifier m)
Static Public Attributes
static constexpr int minExp {detail::zMinExp}
static constexpr int maxExp {detail::zMaxExp}
static constexpr int nBases {maxExp - minExp + 1}
static constexpr int nEntries {detail::zNEntries}
static constexpr float denom {nEntries - 1}
static constexpr const std::array< Note, nEntries > & entries {detail::zEntries}
Member Typedef Documentation
Modifier
using Modifier = Note::Modifier
Member Function Documentation
indexFromZeroOne()
static constexpr int indexFromZeroOne (float v) static constexpr
References ZeroOne::denom.
Referenced by ZeroOne::fromFloat(), ZeroOne::inverseBeatsFromFloat(), and ZeroOne::snap().
zeroOneFromIndex()
static constexpr float zeroOneFromIndex (int idx) static constexpr
References ZeroOne::denom.
Referenced by ZeroOne::snap(), and ZeroOne::toFloat().
snap()
static constexpr float snap (float v) static constexpr
References ZeroOne::indexFromZeroOne(), and ZeroOne::zeroOneFromIndex().
fromFloat()
static constexpr Note fromFloat (float v, bool zeroAtBottom = false) static constexpr
References ZeroOne::entries, ZeroOne::indexFromZeroOne(), and Note::zeroStage().
Referenced by ZeroOne::beatsFromFloat().
toFloat()
static constexpr float toFloat (const Note & n, bool zeroAtBottom = false) static constexpr
References Note::exponent, Note::isZero(), ZeroOne::maxExp, ZeroOne::minExp, Note::modifier, ZeroOne::zeroOneFromIndex(), and sst::basic_blocks::tables::temposync::detail::zReverse.
beatsFromFloat()
static constexpr double beatsFromFloat (float v, bool zeroAtBottom = false) static constexpr
References Note::beats, and ZeroOne::fromFloat().
inverseBeatsFromFloat()
static constexpr double inverseBeatsFromFloat (float v, bool zeroAtBottom = false) static constexpr
References ZeroOne::indexFromZeroOne(), and sst::basic_blocks::tables::temposync::detail::zInverseBeats.
interpolatedBeatsFromFloat()
static constexpr double interpolatedBeatsFromFloat (float v, bool zeroAtBottom = false) static constexpr
References ZeroOne::denom, ZeroOne::entries, and ZeroOne::nEntries.
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), and DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase().
baseIndexOf()
static constexpr int baseIndexOf (int idx) static constexpr
References ZeroOne::entries, and ZeroOne::minExp.
modifierOf()
static constexpr Modifier modifierOf (int idx) static constexpr
References ZeroOne::entries.
indexFor()
static constexpr int indexFor (int baseIndex, Modifier m) static constexpr
References sst::basic_blocks::tables::temposync::detail::zReverse.
Member Data Documentation
minExp
constexpr int minExp {detail::zMinExp} static constexpr
Referenced by ZeroOne::baseIndexOf(), and ZeroOne::toFloat().
maxExp
constexpr int maxExp {detail::zMaxExp} static constexpr
Referenced by ZeroOne::toFloat().
nBases
constexpr int nBases {maxExp - minExp + 1} static constexpr
nEntries
constexpr int nEntries {detail::zNEntries} static constexpr
Referenced by ZeroOne::interpolatedBeatsFromFloat().
denom
constexpr float denom {nEntries - 1} static constexpr
Referenced by ZeroOne::indexFromZeroOne(), ZeroOne::interpolatedBeatsFromFloat(), and ZeroOne::zeroOneFromIndex().
entries
constexpr const std::array<Note, nEntries>& entries {detail::zEntries} static constexpr
Referenced by ZeroOne::baseIndexOf(), ZeroOne::fromFloat(), ZeroOne::interpolatedBeatsFromFloat(), and ZeroOne::modifierOf().
The documentation for this struct was generated from the following file:
TemposyncSupport.h