sst-basic-blocks: SurgeQuadrOsc< T > Struct Template Reference
SurgeQuadrOsc< T > Struct Template Reference
The Surge Magic Circle style Oscillator.
#include <QuadratureOscillators.h>
Public Member Functions
SurgeQuadrOsc ()
void set_rate (T w)
void setRate (T w)
void set_phase (T w)
void process ()
void step ()
Public Attributes
T r
T i
Detailed Description
template<typename T = float>
struct sst::basic_blocks::dsp::SurgeQuadrOsc< T >
The Surge Magic Circle style Oscillator.
Constructor & Destructor Documentation
SurgeQuadrOsc()
template<typename T = float> SurgeQuadrOsc ()
References SurgeQuadrOsc< T >::i, and SurgeQuadrOsc< T >::r.
Member Function Documentation
set_rate()
template<typename T = float> void set_rate (T w)
References SurgeQuadrOsc< T >::i, and SurgeQuadrOsc< T >::r.
Referenced by SurgeQuadrOsc< T >::setRate().
setRate()
template<typename T = float> void setRate (T w)
References SurgeQuadrOsc< T >::set_rate().
set_phase()
template<typename T = float> void set_phase (T w)
References SurgeQuadrOsc< T >::i, and SurgeQuadrOsc< T >::r.
process()
template<typename T = float> void process ()
References SurgeQuadrOsc< T >::i, and SurgeQuadrOsc< T >::r.
Referenced by SurgeQuadrOsc< T >::step().
step()
template<typename T = float> void step ()
References SurgeQuadrOsc< T >::process().
Member Data Documentation
r
template<typename T = float> T r
Referenced by SurgeQuadrOsc< T >::process(), SurgeQuadrOsc< T >::set_phase(), SurgeQuadrOsc< T >::set_rate(), and SurgeQuadrOsc< T >::SurgeQuadrOsc().
i
template<typename T = float> T i
Referenced by SurgeQuadrOsc< T >::process(), SurgeQuadrOsc< T >::set_phase(), SurgeQuadrOsc< T >::set_rate(), and SurgeQuadrOsc< T >::SurgeQuadrOsc().
The documentation for this struct was generated from the following file:
QuadratureOscillators.h