sst-basic-blocks: OnePoleLag< T, first_run_checks > Struct Template Reference
OnePoleLag< T, first_run_checks > Struct Template Reference
SurgeLag is a one simple pole LPF smoother.
#include <Lag.h>
Public Member Functions
OnePoleLag ()
OnePoleLag (T rate)
void setRate (T lp)
void setRateInMilliseconds (double miliSeconds, double sampleRate, double blockSizeInv)
void setTarget (T f)
void snapTo (T f)
void snapToTarget ()
T getTargetValue () const
T getValue () const
void process ()
Public Attributes
T v {0}
T target_v {0}
bool first_run {true}
Protected Attributes
T lp {0}
T lpinv {0}
Detailed Description
template<class T, bool first_run_checks>
struct sst::basic_blocks::dsp::OnePoleLag< T, first_run_checks >
SurgeLag is a one simple pole LPF smoother.
Template Parameters
T The underlying data type
first_run_checks check for initialization or the client sets up with instant value at outset
Constructor & Destructor Documentation
OnePoleLag() [1/2]
template<class T , bool first_run_checks> OnePoleLag ()
References OnePoleLag< T, first_run_checks >::setRate().
OnePoleLag() [2/2]
template<class T , bool first_run_checks> OnePoleLag (T rate)
References OnePoleLag< T, first_run_checks >::setRate().
Member Function Documentation
setRate()
template<class T , bool first_run_checks> void setRate (T lp)
References OnePoleLag< T, first_run_checks >::lp, and OnePoleLag< T, first_run_checks >::lpinv.
Referenced by OnePoleLag< T, first_run_checks >::OnePoleLag(), OnePoleLag< T, first_run_checks >::OnePoleLag(), and OnePoleLag< T, first_run_checks >::setRateInMilliseconds().
setRateInMilliseconds()
template<class T , bool first_run_checks> void setRateInMilliseconds (double miliSeconds, double sampleRate, double blockSizeInv)
References OnePoleLag< T, first_run_checks >::setRate().
setTarget()
template<class T , bool first_run_checks> void setTarget (T f)
References OnePoleLag< T, first_run_checks >::first_run, OnePoleLag< T, first_run_checks >::target_v, and OnePoleLag< T, first_run_checks >::v.
Referenced by SurgeLag< T, first_run_checks >::newValue().
snapTo()
template<class T , bool first_run_checks> void snapTo (T f)
References OnePoleLag< T, first_run_checks >::first_run, OnePoleLag< T, first_run_checks >::target_v, and OnePoleLag< T, first_run_checks >::v.
Referenced by OnePoleLag< T, first_run_checks >::snapToTarget(), and SurgeLag< T, first_run_checks >::startValue().
snapToTarget()
template<class T , bool first_run_checks> void snapToTarget ()
References OnePoleLag< T, first_run_checks >::snapTo(), and OnePoleLag< T, first_run_checks >::target_v.
Referenced by SurgeLag< T, first_run_checks >::instantize().
getTargetValue()
template<class T , bool first_run_checks> T getTargetValue () const
References OnePoleLag< T, first_run_checks >::target_v.
getValue()
template<class T , bool first_run_checks> T getValue () const
References OnePoleLag< T, first_run_checks >::v.
process()
template<class T , bool first_run_checks> void process ()
References OnePoleLag< T, first_run_checks >::lp, OnePoleLag< T, first_run_checks >::lpinv, OnePoleLag< T, first_run_checks >::target_v, and OnePoleLag< T, first_run_checks >::v.
Referenced by LagSmoothingStrategy::process().
Member Data Documentation
v
template<class T , bool first_run_checks> T v {0}
Referenced by OnePoleLag< T, first_run_checks >::getValue(), LagSmoothingStrategy::getValue(), OnePoleLag< T, first_run_checks >::process(), OnePoleLag< T, first_run_checks >::setTarget(), and OnePoleLag< T, first_run_checks >::snapTo().
target_v
template<class T , bool first_run_checks> T target_v {0}
Referenced by OnePoleLag< T, first_run_checks >::getTargetValue(), OnePoleLag< T, first_run_checks >::process(), OnePoleLag< T, first_run_checks >::setTarget(), OnePoleLag< T, first_run_checks >::snapTo(), and OnePoleLag< T, first_run_checks >::snapToTarget().
first_run
template<class T , bool first_run_checks> bool first_run {true}
Referenced by LagSmoothingStrategy::resetFirstRun(), OnePoleLag< T, first_run_checks >::setTarget(), and OnePoleLag< T, first_run_checks >::snapTo().
lp
template<class T , bool first_run_checks> T lp {0} protected
Referenced by OnePoleLag< T, first_run_checks >::process(), and OnePoleLag< T, first_run_checks >::setRate().
lpinv
template<class T , bool first_run_checks> T lpinv {0} protected
Referenced by OnePoleLag< T, first_run_checks >::process(), and OnePoleLag< T, first_run_checks >::setRate().
The documentation for this struct was generated from the following file:
Lag.h