sst-basic-blocks: DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider > Struct Template Reference
DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider > Struct Template Reference
The ADSR or DAHD envelope provider.
#include <DAHDEnvelope.h>
Public Types
using base_t = DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
Public Types inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
enum Stage {
s_delay , s_attack , s_hold , s_decay ,
s_sustain , s_release , s_analog_residual_decay , s_analog_residual_release ,
s_eoc , s_complete
}
Public Member Functions
DAHDEnvelope (SRProvider *s)
void onSampleRateChanged ()
void attackFrom (float fv, float attack, int ashp, bool isdig)
float targetDigitalDAHD (const float dly, const float a, const float h, const float d, const int ashape, const int dshape, const int rshape)
float targetAnalogDAHD (const float dly, const float a, const float h, const float d, const int ashape, const int dshape, const int rshape)
void process (const float a, const float d, const float s, const float r, const int ashape, const int dshape, const int rshape, const bool gateActive)
Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
DiscreteStagesEnvelope ()
void resetCurrent ()
bool preBlockCheck ()
float shapeTarget (float target, int ashape, int dshape, int rshape=0)
void updateBlockTo (float target)
void updateBlockToNoCube (float target)
void step ()
void immediatelySilence ()
float rateFrom01 (float r01)
float rateTo01 (float r)
float deltaTo01 (float d)
Public Attributes
SRProvider * srProvider
bool isDigital {true}
float phase {0}
float start {0}
float v_c1 {0}
float v_c1_delayed {0.f}
bool discharge {false}
float coeff_offset {0}
float rFrom {0}
Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
float output {0}
float outputCubed {0}
float eoc_output {0}
float outputCache [BLOCK_SIZE]
float outBlock0 {0.f}
float outputCacheCubed [BLOCK_SIZE]
int current {BLOCK_SIZE}
int eoc_countdown {0}
enum sst::basic_blocks::modulators::DiscreteStagesEnvelope::Stage s_complete
Additional Inherited Members
Static Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etminV ()
static constexpr float etmaxV ()
Static Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etMin {etminV()}
static constexpr float etMax {etmaxV()}
static constexpr float etScale {etMax - etMin}
static constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE}
Detailed Description
template<typename SRProvider, int BLOCK_SIZE, typename RangeProvider = TenSecondRange>
struct sst::basic_blocks::modulators::DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >
The ADSR or DAHD envelope provider.
Template Parameters
SRProvider - a class which provides two functions. ->samplerate is the current sample rate and envelope_rate_linear_nowrap which provides an envelope rate. The rate is BLOCK_SIZE * 2^-v / samplerate but is usually provided by a table lookup, like in SurgeStorage
BLOCK_SIZE the block size
RangeProvider - sets mins and maxes
Member Typedef Documentation
base_t
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> using base_t = DiscreteStagesEnvelope<BLOCK_SIZE, RangeProvider>
Constructor & Destructor Documentation
DAHDEnvelope()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> DAHDEnvelope (SRProvider * s)
References DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::onSampleRateChanged().
Member Function Documentation
onSampleRateChanged()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void onSampleRateChanged ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::BLOCK_SIZE_INV, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::coeff_offset, and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::srProvider.
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::DAHDEnvelope().
attackFrom()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void attackFrom (float fv, float attack, int ashp, bool isdig)
References DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::discharge, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::isDigital, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::phase, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::resetCurrent(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::v_c1, and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::v_c1_delayed.
targetDigitalDAHD()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float targetDigitalDAHD (const float dly, const float a, const float h, const float d, const int ashape, const int dshape, const int rshape)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etMin, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::phase, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_eoc, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_sustain, and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::srProvider.
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process().
targetAnalogDAHD()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float targetAnalogDAHD (const float dly, const float a, const float h, const float d, const int ashape, const int dshape, const int rshape)
References DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::coeff_offset, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::discharge, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etMin, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::phase, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_analog_residual_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_complete, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_eoc, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_sustain, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::srProvider, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::v_c1, and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::v_c1_delayed.
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process().
process()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> void process (const float a, const float d, const float s, const float r, const int ashape, const int dshape, const int rshape, const bool gateActive)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::isDigital, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::shapeTarget(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo().
Member Data Documentation
srProvider
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> SRProvider* srProvider
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::onSampleRateChanged(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD().
isDigital
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> bool isDigital {true}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process().
phase
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float phase {0}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD().
start
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float start {0}
v_c1
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float v_c1 {0}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD().
v_c1_delayed
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float v_c1_delayed {0.f}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD().
discharge
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> bool discharge {false}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD().
coeff_offset
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float coeff_offset {0}
Referenced by DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::onSampleRateChanged(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD().
rFrom
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange> float rFrom {0}
The documentation for this struct was generated from the following file:
DAHDEnvelope.h