sst-basic-blocks: SurgeLag< T, first_run_checks > Struct Template Reference
SurgeLag< T, first_run_checks > Struct Template Reference
Public Member Functions
SurgeLag (T lp)
SurgeLag ()
void setRate (T lp)
void newValue (T f)
void startValue (T f)
void instantize ()
T getTargetValue ()
T getValue ()
void process ()
Public Attributes
T v {0}
T target_v {0}
bool first_run {true}
Constructor & Destructor Documentation
SurgeLag() [1/2]
SurgeLag (T lp)
References SurgeLag< T, first_run_checks >::setRate().
SurgeLag() [2/2]
SurgeLag ()
References SurgeLag< T, first_run_checks >::setRate().
Member Function Documentation
setRate()
void setRate (T lp)
Referenced by SurgeLag< T, first_run_checks >::SurgeLag().
newValue()
void newValue (T f)
References SurgeLag< T, first_run_checks >::first_run, SurgeLag< T, first_run_checks >::target_v, and SurgeLag< T, first_run_checks >::v.
Referenced by LagSmoothingStrategy::setTarget(), and LagSmoothingStrategy::setValueInstant().
startValue()
void startValue (T f)
References SurgeLag< T, first_run_checks >::first_run, SurgeLag< T, first_run_checks >::target_v, and SurgeLag< T, first_run_checks >::v.
instantize()
void instantize ()
References SurgeLag< T, first_run_checks >::target_v, and SurgeLag< T, first_run_checks >::v.
Referenced by LagSmoothingStrategy::setValueInstant().
getTargetValue()
T getTargetValue ()
References SurgeLag< T, first_run_checks >::target_v.
getValue()
T getValue ()
References SurgeLag< T, first_run_checks >::v.
process()
void process ()
References SurgeLag< T, first_run_checks >::target_v, and SurgeLag< T, first_run_checks >::v.
Referenced by LagSmoothingStrategy::process().
Member Data Documentation
v
T v {0}
Referenced by SurgeLag< T, first_run_checks >::getValue(), LagSmoothingStrategy::getValue(), SurgeLag< T, first_run_checks >::instantize(), SurgeLag< T, first_run_checks >::newValue(), SurgeLag< T, first_run_checks >::process(), and SurgeLag< T, first_run_checks >::startValue().
target_v
T target_v {0}
Referenced by SurgeLag< T, first_run_checks >::getTargetValue(), SurgeLag< T, first_run_checks >::instantize(), SurgeLag< T, first_run_checks >::newValue(), SurgeLag< T, first_run_checks >::process(), and SurgeLag< T, first_run_checks >::startValue().
first_run
bool first_run {true}
Referenced by SurgeLag< T, first_run_checks >::newValue(), LagSmoothingStrategy::resetFirstRun(), and SurgeLag< T, first_run_checks >::startValue().
The documentation for this struct was generated from the following file:
Lag.h