sst-basic-blocks: EBSaw< SmoothingStrategy > Struct Template Reference
EBSaw< SmoothingStrategy > Struct Template Reference
#include <EllipticBlepOscillators.h>
Public Member Functions
float step ()
Public Member Functions inherited from EBOscillatorBase< Impl, SmoothingStrategy >
EBOscillatorBase ()
void setSampleRate (double sampleRate)
Set the sample rate; set up the internal blep state.
void reset ()
Reset to initial state.
void setInitialPhase (float ph, float initSRatio=0)
void setFrequency (float freqInHz)
Set the oscillator frequency.
void setSyncRatio (float syncRatio)
Set the sync ratio.
Static Public Member Functions
static float valueAt (float sphase)
Additional Inherited Members
Protected Member Functions inherited from EBOscillatorBase< Impl, SmoothingStrategy >
float csip (float sip)
void syncTurnaroundCorrection (float freq, float srval)
Protected Attributes inherited from EBOscillatorBase< Impl, SmoothingStrategy >
signalsmith::blep::EllipticBlep< float > blep
signalsmith::blep::EllipticBlepAllpass< float > allpass
float phase = 0
float sphase = 0
SmoothingStrategy::smoothValue_t sratio
SmoothingStrategy::smoothValue_t dphase
double sampleRate {1}
double sampleRateInv {1}
Static Protected Attributes inherited from EBOscillatorBase< Impl, SmoothingStrategy >
static std::unordered_map< size_t, bool > poled
Member Function Documentation
step()
template<typename SmoothingStrategy = LagSmoothingStrategy> float step ()
References EBOscillatorBase< Impl, SmoothingStrategy >::allpass, EBOscillatorBase< Impl, SmoothingStrategy >::blep, EBOscillatorBase< Impl, SmoothingStrategy >::csip(), EBOscillatorBase< Impl, SmoothingStrategy >::dphase, EBOscillatorBase< Impl, SmoothingStrategy >::phase, EBOscillatorBase< Impl, SmoothingStrategy >::sphase, EBOscillatorBase< Impl, SmoothingStrategy >::sratio, EBOscillatorBase< Impl, SmoothingStrategy >::syncTurnaroundCorrection(), and EBSaw< SmoothingStrategy >::valueAt().
valueAt()
template<typename SmoothingStrategy = LagSmoothingStrategy> static float valueAt (float sphase) static
References EBOscillatorBase< Impl, SmoothingStrategy >::sphase.
Referenced by EBSaw< SmoothingStrategy >::step().
The documentation for this struct was generated from the following file:
EllipticBlepOscillators.h