sst-basic-blocks: BlockInterpSmoothingStrategy< blockSize > Struct Template Reference
BlockInterpSmoothingStrategy< blockSize > Struct Template Reference
#include <SmoothingStrategies.h>
Public Types
using smoothValue_t = lipol< double, blockSize, true >
Static Public Member Functions
static void setTarget (smoothValue_t &v, float t)
static void setValueInstant (smoothValue_t &v, float t)
static double getValue (smoothValue_t &v)
static void process (smoothValue_t &v)
static void resetFirstRun (smoothValue_t &v)
Member Typedef Documentation
smoothValue_t
template<int blockSize> using smoothValue_t = lipol<double, blockSize, true>
Member Function Documentation
setTarget()
template<int blockSize> static void setTarget (smoothValue_t & v, float t) static
References lipol< T, defaultBlockSize, first_run_checks >::newValue().
setValueInstant()
template<int blockSize> static void setValueInstant (smoothValue_t & v, float t) static
References lipol< T, defaultBlockSize, first_run_checks >::instantize(), and lipol< T, defaultBlockSize, first_run_checks >::newValue().
getValue()
template<int blockSize> static double getValue (smoothValue_t & v) static
References lipol< T, defaultBlockSize, first_run_checks >::v.
process()
template<int blockSize> static void process (smoothValue_t & v) static
References lipol< T, defaultBlockSize, first_run_checks >::process().
resetFirstRun()
template<int blockSize> static void resetFirstRun (smoothValue_t & v) static
References lipol< T, defaultBlockSize, first_run_checks >::first_run.
The documentation for this struct was generated from the following file:
SmoothingStrategies.h