sst-basic-blocks: UnisonSetup< valtype > Struct Template Reference
UnisonSetup< valtype > Struct Template Reference
#include <OscillatorDriftUnisonCharacter.h>
Public Member Functions
UnisonSetup (int nv)
valtype detuneBias () const
valtype detuneOffset () const
valtype detune (int voice) const
void panLaw (int voice, valtype &panL, valtype &panR) const
valtype attenuation () const
valtype attenuation_inv () const
void attenuatedPanLaw (int voice, valtype &panL, valtype &panR) const
Public Attributes
bool odd
valtype mid
int half
int n_unison = 1
double sqrt_uni
double sqrt_uni_inv
double bias
Constructor & Destructor Documentation
UnisonSetup()
template<typename valtype > UnisonSetup (int nv)
References UnisonSetup< valtype >::bias, UnisonSetup< valtype >::half, UnisonSetup< valtype >::mid, UnisonSetup< valtype >::n_unison, UnisonSetup< valtype >::odd, UnisonSetup< valtype >::sqrt_uni, and UnisonSetup< valtype >::sqrt_uni_inv.
Member Function Documentation
detuneBias()
template<typename valtype > valtype detuneBias () const
References UnisonSetup< valtype >::bias.
Referenced by UnisonSetup< valtype >::detune().
detuneOffset()
template<typename valtype > valtype detuneOffset () const
References UnisonSetup< valtype >::n_unison.
Referenced by UnisonSetup< valtype >::detune().
detune()
template<typename valtype > valtype detune (int voice) const
References UnisonSetup< valtype >::detuneBias(), and UnisonSetup< valtype >::detuneOffset().
panLaw()
template<typename valtype > void panLaw (int voice, valtype & panL, valtype & panR) const
References UnisonSetup< valtype >::half, UnisonSetup< valtype >::mid, UnisonSetup< valtype >::n_unison, and UnisonSetup< valtype >::odd.
Referenced by UnisonSetup< valtype >::attenuatedPanLaw().
attenuation()
template<typename valtype > valtype attenuation () const
References UnisonSetup< valtype >::sqrt_uni_inv.
Referenced by UnisonSetup< valtype >::attenuatedPanLaw().
attenuation_inv()
template<typename valtype > valtype attenuation_inv () const
References UnisonSetup< valtype >::sqrt_uni.
attenuatedPanLaw()
template<typename valtype > void attenuatedPanLaw (int voice, valtype & panL, valtype & panR) const
References UnisonSetup< valtype >::attenuation(), and UnisonSetup< valtype >::panLaw().
Member Data Documentation
odd
template<typename valtype > bool odd
Referenced by UnisonSetup< valtype >::panLaw(), and UnisonSetup< valtype >::UnisonSetup().
mid
template<typename valtype > valtype mid
Referenced by UnisonSetup< valtype >::panLaw(), and UnisonSetup< valtype >::UnisonSetup().
half
template<typename valtype > int half
Referenced by UnisonSetup< valtype >::panLaw(), and UnisonSetup< valtype >::UnisonSetup().
n_unison
template<typename valtype > int n_unison = 1
Referenced by UnisonSetup< valtype >::detuneOffset(), UnisonSetup< valtype >::panLaw(), and UnisonSetup< valtype >::UnisonSetup().
sqrt_uni
template<typename valtype > double sqrt_uni
Referenced by UnisonSetup< valtype >::attenuation_inv(), and UnisonSetup< valtype >::UnisonSetup().
sqrt_uni_inv
template<typename valtype > double sqrt_uni_inv
Referenced by UnisonSetup< valtype >::attenuation(), and UnisonSetup< valtype >::UnisonSetup().
bias
template<typename valtype > double bias
Referenced by UnisonSetup< valtype >::detuneBias(), and UnisonSetup< valtype >::UnisonSetup().
The documentation for this struct was generated from the following file:
OscillatorDriftUnisonCharacter.h