sst-basic-blocks: DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample > Struct Template Reference
DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample > Struct Template Reference
DAREnvelope is an gated delay attack sustain-at-one release envelope.
#include <DAHDSREnvelope.h>
Public Types
using base_t = DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
Public Types inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
enum Stage {
s_delay , s_attack , s_hold , s_decay ,
s_sustain , s_release , s_analog_residual_decay , s_analog_residual_release ,
s_eoc , s_complete
}
Public Member Functions
DAHDSREnvelope (SRProvider *s)
void attack (const float d)
template<bool gated>
float stepDigital (const float dl, const float a, const float h, const float dc, const float s, const float r)
void processBlock01AD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
void processBlockScaledAD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
void processScaledAD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
DiscreteStagesEnvelope ()
void resetCurrent ()
bool preBlockCheck ()
float shapeTarget (float target, int ashape, int dshape, int rshape=0)
void updateBlockTo (float target)
void updateBlockToNoCube (float target)
void step ()
void immediatelySilence ()
float rateFrom01 (float r01)
float rateTo01 (float r)
float deltaTo01 (float d)
Public Attributes
SRProvider * srProvider
float phase {0}
float start {0}
float releaseScale {1.f}
Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
float output {0}
float outputCubed {0}
float eoc_output {0}
float outputCache [BLOCK_SIZE]
float outBlock0 {0.f}
float outputCacheCubed [BLOCK_SIZE]
int current {BLOCK_SIZE}
int eoc_countdown {0}
enum sst::basic_blocks::modulators::DiscreteStagesEnvelope::Stage s_complete
Additional Inherited Members
Static Public Member Functions inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etminV ()
static constexpr float etmaxV ()
Static Public Attributes inherited from DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >
static constexpr float etMin {etminV()}
static constexpr float etMax {etmaxV()}
static constexpr float etScale {etMax - etMin}
static constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE}
Detailed Description
template<typename SRProvider, int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true>
struct sst::basic_blocks::modulators::DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >
DAREnvelope is an gated delay attack sustain-at-one release envelope.
Template Parameters
SRProvider See the comments in ADSREnvelope
BLOCK_SIZE Must be a power of 2
RangeProvider Defines the min and max
Member Typedef Documentation
base_t
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> using base_t = DiscreteStagesEnvelope<BLOCK_SIZE, RangeProvider>
Constructor & Destructor Documentation
DAHDSREnvelope()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> DAHDSREnvelope (SRProvider * s)
Member Function Documentation
attack()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> void attack (const float d)
References DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::phase, DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::releaseScale, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::resetCurrent(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay.
stepDigital()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> template<bool gated> float stepDigital (const float dl, const float a, const float h, const float dc, const float s, const float r)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::phase, DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::releaseScale, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_decay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_delay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_eoc, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_hold, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_sustain, and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::srProvider.
processBlock01AD()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> void processBlock01AD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
References DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlockScaledAD(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::rateFrom01().
processBlockScaledAD()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> void processBlockScaledAD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo().
Referenced by DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlock01AD().
processScaledAD()
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> void processScaledAD (const float dl, const float a, const float h, const float dc, const float s, const float r, const bool gateActive)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo().
Member Data Documentation
srProvider
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> SRProvider* srProvider
Referenced by DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::stepDigital().
phase
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> float phase {0}
Referenced by DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::attack(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::stepDigital().
start
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> float start {0}
releaseScale
template<typename SRProvider , int BLOCK_SIZE, typename RangeProvider = TenSecondRange, bool processEverySample = true> float releaseScale {1.f}
Referenced by DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::attack(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::stepDigital().
The documentation for this struct was generated from the following file:
DAHDSREnvelope.h