sst-basic-blocks: ParamMetaData Struct Reference
ParamMetaData Struct Reference
Classes
struct FeatureState
struct ModulationDisplay
Public Types
enum Type { FLOAT , INT , BOOL , NONE }
enum class Polarity {
INFERRED , UNIPOLAR_POSITIVE , UNIPOLAR_NEGATIVE , BIPOLAR ,
NO_POLARITY
}
enum class Quantization { NO_QUANTIZATION , CUSTOM_INTERVAL , CUSTOM_STEP_COUNT }
enum class Features : uint64_t { SUPPORTS_MULTIPLICATIVE_MODULATION = 1 << 0 }
enum DisplayScale {
LINEAR , A_TWO_TO_THE_B , CUBED_AS_DECIBEL , SCALED_OFFSET_EXP ,
DECIBEL , UNORDERED_MAP , MIDI_NOTE , USER_PROVIDED
}
enum AlternateScaleWhen { NO_ALTERNATE , SCALE_BELOW , SCALE_ABOVE }
Public Member Functions
ParamMetaData ()=default
Polarity getPolarity () const
bool isBipolar () const
bool isUnipolar () const
bool supportsQuantization () const
float quantize (float f) const
ParamMetaData withIntegerQuantization () const
ParamMetaData withQuantizedInterval (float interval) const
ParamMetaData withQuantizedStepCount (int steps) const
ParamMetaData withFeature (Features f) const
bool hasFeature (Features f) const
ParamMetaData withSupportsMultiplicativeModulation () const
bool hasSupportsMultiplicativeModulation () const
std::optional< std::string > valueToString (float val, const FeatureState &fs={}) const
std::optional< std::string > valueToAlternateString (float val) const
std::optional< float > valueFromString (std::string_view, std::string &errMsg, const FeatureState &fs={}) const
std::optional< ModulationDisplay > modulationNaturalToString (float naturalBaseVal, float modulationNatural, bool isBipolar, const FeatureState &fs={}) const
std::optional< float > modulationNaturalFromString (std::string_view deltaNatural, float naturalBaseVal, std::string &errMsg) const
float naturalToNormalized01 (float naturalValue) const
float normalized01ToNatural (float normalizedValue) const
ParamMetaData withType (Type t)
ParamMetaData asFloat ()
ParamMetaData asInt ()
ParamMetaData asBool ()
ParamMetaData withName (const std::string t)
ParamMetaData withGroupName (const std::string t)
ParamMetaData withID (const uint32_t id)
ParamMetaData withFlags (const uint32_t f)
ParamMetaData withRange (float mn, float mx)
ParamMetaData withDefault (float t)
ParamMetaData withPolarity (Polarity p)
ParamMetaData withTemposyncMultiplier (float f)
ParamMetaData extendable (bool b=true)
ParamMetaData withExtendFactors (float A, float B=0.f)
ParamMetaData deformable (bool b=true)
ParamMetaData withDeformationCount (int c)
ParamMetaData absolutable (bool b=true)
ParamMetaData temposyncable (bool b=true)
ParamMetaData deactivatable (bool b=true)
ParamMetaData withATwoToTheBFormatting (float A, float B, std::string_view units)
ParamMetaData withATwoToTheBPlusCFormatting (float A, float B, float C, std::string_view units)
ParamMetaData withScaledOffsetExpFormatting (float A, float B, float C, float D, const std::string &units)
ParamMetaData withSemitoneZeroAt400Formatting ()
ParamMetaData withSemitoneZeroAtMIDIZeroFormatting ()
ParamMetaData withLog2SecondsFormatting ()
ParamMetaData withLinearScaleFormatting (std::string units, float scale=1.f)
ParamMetaData withMidiNoteFormatting (int octave)
ParamMetaData withUnorderedMapFormatting (const std::unordered_map< int, std::string > &map, bool scanAndInitParamRange=false)
ParamMetaData withDecimalPlaces (int d)
ParamMetaData withUnit (std::string_view s)
ParamMetaData withCustomMaxDisplay (const std::string &v)
ParamMetaData withCustomMinDisplay (const std::string &v)
ParamMetaData withCustomDefaultDisplay (const std::string &v)
ParamMetaData withDisplayRescalingBelow (const float cutoff, const float rescale, const std::string &units)
ParamMetaData withoutDisplayRescaling ()
ParamMetaData withMilisecondsBelowOneSecond ()
ParamMetaData withDisplayRescalingAbove (const float cutoff, const float rescale, const std::string &units)
ParamMetaData asPercent ()
ParamMetaData asPercentExtendableToBipolar ()
ParamMetaData asPercentBipolar ()
ParamMetaData asDecibelWithRange (float low, float high, float def=0.f)
ParamMetaData asDecibelNarrow ()
ParamMetaData asDecibel ()
ParamMetaData asMIDIPitch ()
ParamMetaData asMIDINote (int octave=1000)
ParamMetaData asLfoRate (float from=-7.f, float to=9.f)
ParamMetaData asSemitoneRange (float lower=-96, float upper=96)
ParamMetaData asLog2SecondsRange (float lower, float upper, float defVal=0)
ParamMetaData asEnvelopeTime ()
ParamMetaData as25SecondExpTime ()
ParamMetaData asAudibleFrequency ()
ParamMetaData asCubicDecibelAttenuation ()
A 0...1 value where the amplitude is the value cubed and the display is in decibels.
ParamMetaData asCubicDecibelAttenuationWithUpperDBBound (float maxDB)
This creates a param with a max val different from 1, such that the value of 1 is still 0db and the max val is the dbs provided.
ParamMetaData asCubicDecibelUpTo (float maxDb)
This assumes you have a 0...1 underlyer and want it to represent a scaled range up to some decibels.
ParamMetaData asLinearDecibel (float lower=-96, float upper=12)
ParamMetaData asPan ()
std::string temposyncNotation (float f) const
float snapToTemposync (float f) const
template<int stringSize, typename IsAClapParamInfo >
void toClapParamInfo (IsAClapParamInfo *info) const
Public Attributes
enum sst::basic_blocks::params::ParamMetaData::Type FLOAT
std::string name
std::string groupName {}
uint32_t id {0}
uint32_t flags {0}
float minVal {0.f}
float maxVal {1.f}
float defaultVal {0.f}
bool canExtend {false}
bool canDeform {false}
bool canAbsolute {false}
bool canTemposync {false}
bool canDeactivate {false}
float temposyncMultiplier {1.f}
int deformationCount {0}
bool supportsStringConversion {false}
enum sst::basic_blocks::params::ParamMetaData::Polarity INFERRED
enum sst::basic_blocks::params::ParamMetaData::Quantization NO_QUANTIZATION
float quantizationParam {0.f}
uint64_t features {0}
enum sst::basic_blocks::params::ParamMetaData::DisplayScale LINEAR
std::string unit
std::string customMinDisplay
std::string customMaxDisplay
std::string customDefaultDisplay
std::unordered_map< int, std::string > discreteValues
int decimalPlaces {2}
int midiNoteOctaveOffset {defaultMidiNoteOctaveOffset}
float svA {0.f}
float svB {0.f}
float svC {0.f}
float svD {0.f}
float exA {1.f}
float exB {0.f}
enum sst::basic_blocks::params::ParamMetaData::AlternateScaleWhen NO_ALTERNATE
double alternateScaleCutoff {0.f}
double alternateScaleRescaling {0.f}
std::string alternateScaleUnits {}
Static Public Attributes
static int defaultMidiNoteOctaveOffset {0}
Member Enumeration Documentation
Type
enum Type
Enumerator
FLOAT
INT
BOOL
NONE
Polarity
enum Polarity strong
Enumerator
INFERRED
UNIPOLAR_POSITIVE
UNIPOLAR_NEGATIVE
BIPOLAR
NO_POLARITY
Quantization
enum Quantization strong
Enumerator
NO_QUANTIZATION
CUSTOM_INTERVAL
CUSTOM_STEP_COUNT
Features
enum Features : uint64_t strong
Enumerator
SUPPORTS_MULTIPLICATIVE_MODULATION
DisplayScale
enum DisplayScale
Enumerator
LINEAR
A_TWO_TO_THE_B
CUBED_AS_DECIBEL
SCALED_OFFSET_EXP
DECIBEL
UNORDERED_MAP
MIDI_NOTE
USER_PROVIDED
AlternateScaleWhen
enum AlternateScaleWhen
Enumerator
NO_ALTERNATE
SCALE_BELOW
SCALE_ABOVE
Constructor & Destructor Documentation
ParamMetaData()
ParamMetaData () default
Member Function Documentation
getPolarity()
Polarity getPolarity () const
References ParamMetaData::BIPOLAR, ParamMetaData::INFERRED, ParamMetaData::maxVal, ParamMetaData::minVal, ParamMetaData::NO_POLARITY, ParamMetaData::UNIPOLAR_NEGATIVE, and ParamMetaData::UNIPOLAR_POSITIVE.
Referenced by ParamMetaData::isBipolar(), and ParamMetaData::isUnipolar().
isBipolar()
bool isBipolar () const
References ParamMetaData::BIPOLAR, and ParamMetaData::getPolarity().
Referenced by ParamMetaData::modulationNaturalToString().
isUnipolar()
bool isUnipolar () const
References ParamMetaData::getPolarity(), ParamMetaData::UNIPOLAR_NEGATIVE, and ParamMetaData::UNIPOLAR_POSITIVE.
supportsQuantization()
bool supportsQuantization () const
References ParamMetaData::NO_QUANTIZATION.
quantize()
float quantize (float f) const
References ParamMetaData::CUBED_AS_DECIBEL, ParamMetaData::CUSTOM_INTERVAL, ParamMetaData::CUSTOM_STEP_COUNT, ParamMetaData::maxVal, ParamMetaData::minVal, ParamMetaData::quantizationParam, and ParamMetaData::svA.
withIntegerQuantization()
ParamMetaData withIntegerQuantization () const
References ParamMetaData::withQuantizedInterval().
Referenced by ParamMetaData::asLfoRate(), ParamMetaData::asLinearDecibel(), ParamMetaData::asMIDINote(), ParamMetaData::asMIDIPitch(), and ParamMetaData::asSemitoneRange().
withQuantizedInterval()
ParamMetaData withQuantizedInterval (float interval) const
References ParamMetaData::CUSTOM_INTERVAL.
Referenced by ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), and ParamMetaData::withIntegerQuantization().
withQuantizedStepCount()
ParamMetaData withQuantizedStepCount (int steps) const
References ParamMetaData::CUSTOM_STEP_COUNT.
withFeature()
ParamMetaData withFeature (Features f) const
References ParamMetaData::features.
Referenced by ParamMetaData::withSupportsMultiplicativeModulation().
hasFeature()
bool hasFeature (Features f) const
References ParamMetaData::features.
Referenced by ParamMetaData::hasSupportsMultiplicativeModulation().
withSupportsMultiplicativeModulation()
ParamMetaData withSupportsMultiplicativeModulation () const
References ParamMetaData::SUPPORTS_MULTIPLICATIVE_MODULATION, and ParamMetaData::withFeature().
Referenced by ParamMetaData::asLinearDecibel().
hasSupportsMultiplicativeModulation()
bool hasSupportsMultiplicativeModulation () const
References ParamMetaData::hasFeature(), and ParamMetaData::SUPPORTS_MULTIPLICATIVE_MODULATION.
valueToString()
std::optional< std::string > valueToString (float val, const FeatureState & fs = {}) const
References ParamMetaData::A_TWO_TO_THE_B, ParamMetaData::alternateScaleCutoff, ParamMetaData::alternateScaleRescaling, ParamMetaData::alternateScaleUnits, ParamMetaData::BOOL, ParamMetaData::CUBED_AS_DECIBEL, ParamMetaData::customDefaultDisplay, ParamMetaData::customMaxDisplay, ParamMetaData::customMinDisplay, ParamMetaData::decimalPlaces, ParamMetaData::defaultVal, ParamMetaData::discreteValues, ParamMetaData::exA, ParamMetaData::exB, ParamMetaData::INT, ParamMetaData::FeatureState::isExtended, ParamMetaData::FeatureState::isHighPrecision, ParamMetaData::FeatureState::isTemposynced, ParamMetaData::LINEAR, ParamMetaData::maxVal, ParamMetaData::MIDI_NOTE, ParamMetaData::midiNoteOctaveOffset, ParamMetaData::minVal, ParamMetaData::NO_ALTERNATE, ParamMetaData::SCALE_ABOVE, ParamMetaData::SCALE_BELOW, ParamMetaData::SCALED_OFFSET_EXP, ParamMetaData::svA, ParamMetaData::svB, ParamMetaData::svC, ParamMetaData::svD, ParamMetaData::temposyncMultiplier, ParamMetaData::temposyncNotation(), ParamMetaData::unit, and ParamMetaData::UNORDERED_MAP.
Referenced by ParamMetaData::modulationNaturalToString(), and ParamMetaData::valueFromString().
valueToAlternateString()
std::optional< std::string > valueToAlternateString (float val) const
valueFromString()
std::optional< float > valueFromString (std::string_view v, std::string & errMsg, const FeatureState & fs = {}) const
References ParamMetaData::A_TWO_TO_THE_B, ParamMetaData::alternateScaleRescaling, ParamMetaData::alternateScaleUnits, ParamMetaData::BOOL, ParamMetaData::CUBED_AS_DECIBEL, ParamMetaData::customMaxDisplay, ParamMetaData::customMinDisplay, ParamMetaData::exA, ParamMetaData::exB, ParamMetaData::INT, ParamMetaData::FeatureState::isExtended, ParamMetaData::LINEAR, ParamMetaData::maxVal, ParamMetaData::MIDI_NOTE, ParamMetaData::midiNoteOctaveOffset, ParamMetaData::minVal, ParamMetaData::NO_ALTERNATE, ParamMetaData::SCALED_OFFSET_EXP, ParamMetaData::svA, ParamMetaData::svB, ParamMetaData::svC, ParamMetaData::svD, and ParamMetaData::valueToString().
modulationNaturalToString()
std::optional< ParamMetaData::ModulationDisplay > modulationNaturalToString (float naturalBaseVal, float modulationNatural, bool isBipolar, const FeatureState & fs = {}) const
References ParamMetaData::A_TWO_TO_THE_B, ParamMetaData::ModulationDisplay::baseValue, ParamMetaData::ModulationDisplay::changeDown, ParamMetaData::ModulationDisplay::changeUp, ParamMetaData::CUBED_AS_DECIBEL, ParamMetaData::decimalPlaces, ParamMetaData::FLOAT, ParamMetaData::isBipolar(), ParamMetaData::FeatureState::isHighPrecision, ParamMetaData::LINEAR, ParamMetaData::maxVal, ParamMetaData::minVal, ParamMetaData::SCALED_OFFSET_EXP, ParamMetaData::ModulationDisplay::singleLineModulationSummary, ParamMetaData::ModulationDisplay::summary, ParamMetaData::svA, ParamMetaData::svB, ParamMetaData::svC, ParamMetaData::svD, ParamMetaData::unit, ParamMetaData::ModulationDisplay::valDown, ParamMetaData::ModulationDisplay::value, ParamMetaData::valueToString(), and ParamMetaData::ModulationDisplay::valUp.
modulationNaturalFromString()
std::optional< float > modulationNaturalFromString (std::string_view deltaNatural, float naturalBaseVal, std::string & errMsg) const
References ParamMetaData::A_TWO_TO_THE_B, ParamMetaData::LINEAR, ParamMetaData::maxVal, ParamMetaData::minVal, ParamMetaData::svA, ParamMetaData::svB, and ParamMetaData::unit.
naturalToNormalized01()
float naturalToNormalized01 (float naturalValue) const
References ParamMetaData::BOOL, ParamMetaData::FLOAT, ParamMetaData::INT, ParamMetaData::maxVal, ParamMetaData::minVal, and ParamMetaData::NONE.
normalized01ToNatural()
float normalized01ToNatural (float normalizedValue) const
References ParamMetaData::BOOL, ParamMetaData::FLOAT, ParamMetaData::INT, ParamMetaData::maxVal, ParamMetaData::minVal, and ParamMetaData::NONE.
withType()
ParamMetaData withType (Type t)
Referenced by ParamMetaData::as25SecondExpTime(), ParamMetaData::asAudibleFrequency(), ParamMetaData::asCubicDecibelUpTo(), ParamMetaData::asDecibelWithRange(), ParamMetaData::asLfoRate(), ParamMetaData::asLinearDecibel(), ParamMetaData::asLog2SecondsRange(), ParamMetaData::asMIDINote(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), and ParamMetaData::asSemitoneRange().
asFloat()
ParamMetaData asFloat ()
References ParamMetaData::FLOAT.
asInt()
ParamMetaData asInt ()
References ParamMetaData::INT.
asBool()
ParamMetaData asBool ()
References ParamMetaData::BOOL.
withName()
ParamMetaData withName (const std::string t)
References ParamMetaData::name.
withGroupName()
ParamMetaData withGroupName (const std::string t)
References ParamMetaData::groupName.
withID()
ParamMetaData withID (const uint32_t id)
References ParamMetaData::id.
withFlags()
ParamMetaData withFlags (const uint32_t f)
References ParamMetaData::flags.
withRange()
ParamMetaData withRange (float mn, float mx)
References ParamMetaData::defaultVal, ParamMetaData::maxVal, and ParamMetaData::minVal.
Referenced by ParamMetaData::as25SecondExpTime(), ParamMetaData::asAudibleFrequency(), ParamMetaData::asCubicDecibelUpTo(), ParamMetaData::asDecibelWithRange(), ParamMetaData::asLfoRate(), ParamMetaData::asLinearDecibel(), ParamMetaData::asLog2SecondsRange(), ParamMetaData::asMIDINote(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), and ParamMetaData::asSemitoneRange().
withDefault()
ParamMetaData withDefault (float t)
References ParamMetaData::defaultVal.
Referenced by ParamMetaData::as25SecondExpTime(), ParamMetaData::asAudibleFrequency(), ParamMetaData::asCubicDecibelUpTo(), ParamMetaData::asDecibelWithRange(), ParamMetaData::asLinearDecibel(), ParamMetaData::asLog2SecondsRange(), ParamMetaData::asMIDINote(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPan(), ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), and ParamMetaData::asSemitoneRange().
withPolarity()
ParamMetaData withPolarity (Polarity p)
withTemposyncMultiplier()
ParamMetaData withTemposyncMultiplier (float f)
References ParamMetaData::temposyncMultiplier.
Referenced by ParamMetaData::asLfoRate().
extendable()
ParamMetaData extendable (bool b = true)
References ParamMetaData::canExtend.
Referenced by ParamMetaData::asPercentExtendableToBipolar().
withExtendFactors()
ParamMetaData withExtendFactors (float A, float B = 0.f)
References A, and ParamMetaData::exA.
Referenced by ParamMetaData::asPercentExtendableToBipolar().
deformable()
ParamMetaData deformable (bool b = true)
References ParamMetaData::canDeform.
withDeformationCount()
ParamMetaData withDeformationCount (int c)
References ParamMetaData::deformationCount.
absolutable()
ParamMetaData absolutable (bool b = true)
References ParamMetaData::canAbsolute.
temposyncable()
ParamMetaData temposyncable (bool b = true)
References ParamMetaData::canTemposync.
Referenced by ParamMetaData::asLfoRate(), and ParamMetaData::asLog2SecondsRange().
deactivatable()
ParamMetaData deactivatable (bool b = true)
References ParamMetaData::canDeactivate.
withATwoToTheBFormatting()
ParamMetaData withATwoToTheBFormatting (float A, float B, std::string_view units)
References A, and ParamMetaData::withATwoToTheBPlusCFormatting().
Referenced by ParamMetaData::asLfoRate(), ParamMetaData::asLog2SecondsRange(), ParamMetaData::withLog2SecondsFormatting(), ParamMetaData::withSemitoneZeroAt400Formatting(), and ParamMetaData::withSemitoneZeroAtMIDIZeroFormatting().
withATwoToTheBPlusCFormatting()
ParamMetaData withATwoToTheBPlusCFormatting (float A, float B, float C, std::string_view units)
References A, ParamMetaData::A_TWO_TO_THE_B, C, and ParamMetaData::svA.
Referenced by ParamMetaData::withATwoToTheBFormatting().
withScaledOffsetExpFormatting()
ParamMetaData withScaledOffsetExpFormatting (float A, float B, float C, float D, const std::string & units)
References A, C, ParamMetaData::SCALED_OFFSET_EXP, and ParamMetaData::svA.
Referenced by ParamMetaData::as25SecondExpTime().
withSemitoneZeroAt400Formatting()
ParamMetaData withSemitoneZeroAt400Formatting ()
References ParamMetaData::withATwoToTheBFormatting().
Referenced by ParamMetaData::asAudibleFrequency().
withSemitoneZeroAtMIDIZeroFormatting()
ParamMetaData withSemitoneZeroAtMIDIZeroFormatting ()
References ParamMetaData::withATwoToTheBFormatting().
withLog2SecondsFormatting()
ParamMetaData withLog2SecondsFormatting ()
References ParamMetaData::withATwoToTheBFormatting().
withLinearScaleFormatting()
ParamMetaData withLinearScaleFormatting (std::string units, float scale = 1.f)
References ParamMetaData::LINEAR, and ParamMetaData::svA.
Referenced by ParamMetaData::asDecibelWithRange(), ParamMetaData::asLinearDecibel(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), and ParamMetaData::asSemitoneRange().
withMidiNoteFormatting()
ParamMetaData withMidiNoteFormatting (int octave)
References ParamMetaData::MIDI_NOTE, and ParamMetaData::unit.
Referenced by ParamMetaData::asMIDINote().
withUnorderedMapFormatting()
ParamMetaData withUnorderedMapFormatting (const std::unordered_map< int, std::string > & map, bool scanAndInitParamRange = false)
References ParamMetaData::discreteValues, ParamMetaData::INT, and ParamMetaData::UNORDERED_MAP.
withDecimalPlaces()
ParamMetaData withDecimalPlaces (int d)
References ParamMetaData::decimalPlaces.
Referenced by ParamMetaData::asMIDINote(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPan(), ParamMetaData::asPercent(), and ParamMetaData::asPercentBipolar().
withUnit()
ParamMetaData withUnit (std::string_view s)
References ParamMetaData::unit.
withCustomMaxDisplay()
ParamMetaData withCustomMaxDisplay (const std::string & v)
References ParamMetaData::customMaxDisplay.
Referenced by ParamMetaData::asPan().
withCustomMinDisplay()
ParamMetaData withCustomMinDisplay (const std::string & v)
References ParamMetaData::customMinDisplay.
Referenced by ParamMetaData::asPan().
withCustomDefaultDisplay()
ParamMetaData withCustomDefaultDisplay (const std::string & v)
References ParamMetaData::customDefaultDisplay.
Referenced by ParamMetaData::asPan().
withDisplayRescalingBelow()
ParamMetaData withDisplayRescalingBelow (const float cutoff, const float rescale, const std::string & units)
References ParamMetaData::SCALE_BELOW.
Referenced by ParamMetaData::withMilisecondsBelowOneSecond().
withoutDisplayRescaling()
ParamMetaData withoutDisplayRescaling ()
References ParamMetaData::NO_ALTERNATE.
withMilisecondsBelowOneSecond()
ParamMetaData withMilisecondsBelowOneSecond ()
References ParamMetaData::withDisplayRescalingBelow().
Referenced by ParamMetaData::as25SecondExpTime(), and ParamMetaData::asLog2SecondsRange().
withDisplayRescalingAbove()
ParamMetaData withDisplayRescalingAbove (const float cutoff, const float rescale, const std::string & units)
References ParamMetaData::SCALE_ABOVE.
asPercent()
ParamMetaData asPercent ()
References ParamMetaData::FLOAT, ParamMetaData::withDecimalPlaces(), ParamMetaData::withDefault(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withQuantizedInterval(), ParamMetaData::withRange(), and ParamMetaData::withType().
Referenced by ParamMetaData::asPercentExtendableToBipolar().
asPercentExtendableToBipolar()
ParamMetaData asPercentExtendableToBipolar ()
References ParamMetaData::asPercent(), ParamMetaData::extendable(), and ParamMetaData::withExtendFactors().
asPercentBipolar()
ParamMetaData asPercentBipolar ()
References ParamMetaData::FLOAT, ParamMetaData::withDecimalPlaces(), ParamMetaData::withDefault(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withQuantizedInterval(), ParamMetaData::withRange(), and ParamMetaData::withType().
Referenced by ParamMetaData::asPan().
asDecibelWithRange()
ParamMetaData asDecibelWithRange (float low, float high, float def = 0.f)
References ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withRange(), and ParamMetaData::withType().
Referenced by ParamMetaData::asDecibel(), and ParamMetaData::asDecibelNarrow().
asDecibelNarrow()
ParamMetaData asDecibelNarrow ()
References ParamMetaData::asDecibelWithRange().
asDecibel()
ParamMetaData asDecibel ()
References ParamMetaData::asDecibelWithRange().
asMIDIPitch()
ParamMetaData asMIDIPitch ()
References ParamMetaData::FLOAT, ParamMetaData::withDecimalPlaces(), ParamMetaData::withDefault(), ParamMetaData::withIntegerQuantization(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withRange(), and ParamMetaData::withType().
asMIDINote()
ParamMetaData asMIDINote (int octave = 1000)
References ParamMetaData::defaultMidiNoteOctaveOffset, ParamMetaData::INT, ParamMetaData::withDecimalPlaces(), ParamMetaData::withDefault(), ParamMetaData::withIntegerQuantization(), ParamMetaData::withMidiNoteFormatting(), ParamMetaData::withRange(), and ParamMetaData::withType().
asLfoRate()
ParamMetaData asLfoRate (float from = -7.f, float to = 9.f)
References ParamMetaData::FLOAT, ParamMetaData::temposyncable(), ParamMetaData::withATwoToTheBFormatting(), ParamMetaData::withIntegerQuantization(), ParamMetaData::withRange(), ParamMetaData::withTemposyncMultiplier(), and ParamMetaData::withType().
asSemitoneRange()
ParamMetaData asSemitoneRange (float lower = -96, float upper = 96)
References ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withIntegerQuantization(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withRange(), and ParamMetaData::withType().
asLog2SecondsRange()
ParamMetaData asLog2SecondsRange (float lower, float upper, float defVal = 0)
References ParamMetaData::FLOAT, ParamMetaData::temposyncable(), ParamMetaData::withATwoToTheBFormatting(), ParamMetaData::withDefault(), ParamMetaData::withMilisecondsBelowOneSecond(), ParamMetaData::withRange(), and ParamMetaData::withType().
Referenced by ParamMetaData::asEnvelopeTime().
asEnvelopeTime()
ParamMetaData asEnvelopeTime ()
References ParamMetaData::asLog2SecondsRange().
as25SecondExpTime()
ParamMetaData as25SecondExpTime ()
References ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withMilisecondsBelowOneSecond(), ParamMetaData::withRange(), ParamMetaData::withScaledOffsetExpFormatting(), and ParamMetaData::withType().
asAudibleFrequency()
ParamMetaData asAudibleFrequency ()
References ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withRange(), ParamMetaData::withSemitoneZeroAt400Formatting(), and ParamMetaData::withType().
asCubicDecibelAttenuation()
ParamMetaData asCubicDecibelAttenuation ()
A 0...1 value where the amplitude is the value cubed and the display is in decibels.
References ParamMetaData::asCubicDecibelUpTo().
Referenced by ParamMetaData::asCubicDecibelAttenuationWithUpperDBBound().
asCubicDecibelAttenuationWithUpperDBBound()
ParamMetaData asCubicDecibelAttenuationWithUpperDBBound (float maxDB)
This creates a param with a max val different from 1, such that the value of 1 is still 0db and the max val is the dbs provided.
Parameters
maxDB Decibels for the top of range
References ParamMetaData::asCubicDecibelAttenuation().
asCubicDecibelUpTo()
ParamMetaData asCubicDecibelUpTo (float maxDb)
This assumes you have a 0...1 underlyer and want it to represent a scaled range up to some decibels.
Parameters
maxDb the decibels represented by the '1' extram
References ParamMetaData::CUBED_AS_DECIBEL, ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withRange(), and ParamMetaData::withType().
Referenced by ParamMetaData::asCubicDecibelAttenuation().
asLinearDecibel()
ParamMetaData asLinearDecibel (float lower = -96, float upper = 12)
References ParamMetaData::FLOAT, ParamMetaData::withDefault(), ParamMetaData::withIntegerQuantization(), ParamMetaData::withLinearScaleFormatting(), ParamMetaData::withRange(), ParamMetaData::withSupportsMultiplicativeModulation(), and ParamMetaData::withType().
asPan()
ParamMetaData asPan ()
References ParamMetaData::asPercentBipolar(), ParamMetaData::withCustomDefaultDisplay(), ParamMetaData::withCustomMaxDisplay(), ParamMetaData::withCustomMinDisplay(), ParamMetaData::withDecimalPlaces(), and ParamMetaData::withDefault().
temposyncNotation()
std::string temposyncNotation (float f) const
References ParamMetaData::A_TWO_TO_THE_B, and ParamMetaData::FLOAT.
Referenced by ParamMetaData::valueToString().
snapToTemposync()
float snapToTemposync (float f) const
References ParamMetaData::A_TWO_TO_THE_B, ParamMetaData::canTemposync, and ParamMetaData::FLOAT.
toClapParamInfo()
void toClapParamInfo (IsAClapParamInfo * info) const
References ParamMetaData::defaultVal, ParamMetaData::flags, ParamMetaData::groupName, ParamMetaData::id, ParamMetaData::maxVal, ParamMetaData::minVal, and ParamMetaData::name.
Member Data Documentation
FLOAT
enum sst::basic_blocks::params::ParamMetaData::Type FLOAT
Referenced by ParamMetaData::as25SecondExpTime(), ParamMetaData::asAudibleFrequency(), ParamMetaData::asCubicDecibelUpTo(), ParamMetaData::asDecibelWithRange(), ParamMetaData::asFloat(), ParamMetaData::asLfoRate(), ParamMetaData::asLinearDecibel(), ParamMetaData::asLog2SecondsRange(), ParamMetaData::asMIDIPitch(), ParamMetaData::asPercent(), ParamMetaData::asPercentBipolar(), ParamMetaData::asSemitoneRange(), ParamMetaData::modulationNaturalToString(), ParamMetaData::naturalToNormalized01(), ParamMetaData::normalized01ToNatural(), ParamMetaData::snapToTemposync(), and ParamMetaData::temposyncNotation().
name
std::string name
Referenced by ParamMetaData::toClapParamInfo(), and ParamMetaData::withName().
groupName
std::string groupName {}
Referenced by ParamMetaData::toClapParamInfo(), and ParamMetaData::withGroupName().
id
uint32_t id {0}
Referenced by ParamMetaData::toClapParamInfo(), and ParamMetaData::withID().
flags
uint32_t flags {0}
Referenced by ParamMetaData::toClapParamInfo(), and ParamMetaData::withFlags().
minVal
float minVal {0.f}
Referenced by ParamMetaData::getPolarity(), ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::naturalToNormalized01(), ParamMetaData::normalized01ToNatural(), ParamMetaData::quantize(), ParamMetaData::toClapParamInfo(), ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withRange().
maxVal
float maxVal {1.f}
Referenced by ParamMetaData::getPolarity(), ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::naturalToNormalized01(), ParamMetaData::normalized01ToNatural(), ParamMetaData::quantize(), ParamMetaData::toClapParamInfo(), ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withRange().
defaultVal
float defaultVal {0.f}
Referenced by ParamMetaData::toClapParamInfo(), ParamMetaData::valueToString(), ParamMetaData::withDefault(), and ParamMetaData::withRange().
canExtend
bool canExtend {false}
Referenced by ParamMetaData::extendable().
canDeform
bool canDeform {false}
Referenced by ParamMetaData::deformable().
canAbsolute
bool canAbsolute {false}
Referenced by ParamMetaData::absolutable().
canTemposync
bool canTemposync {false}
Referenced by ParamMetaData::snapToTemposync(), and ParamMetaData::temposyncable().
canDeactivate
bool canDeactivate {false}
Referenced by ParamMetaData::deactivatable().
temposyncMultiplier
float temposyncMultiplier {1.f}
Referenced by ParamMetaData::valueToString(), and ParamMetaData::withTemposyncMultiplier().
deformationCount
int deformationCount {0}
Referenced by ParamMetaData::withDeformationCount().
supportsStringConversion
bool supportsStringConversion {false}
INFERRED
enum sst::basic_blocks::params::ParamMetaData::Polarity INFERRED
NO_QUANTIZATION
enum sst::basic_blocks::params::ParamMetaData::Quantization NO_QUANTIZATION
quantizationParam
float quantizationParam {0.f}
Referenced by ParamMetaData::quantize().
features
uint64_t features {0}
Referenced by ParamMetaData::hasFeature(), and ParamMetaData::withFeature().
LINEAR
enum sst::basic_blocks::params::ParamMetaData::DisplayScale LINEAR
Referenced by ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withLinearScaleFormatting().
unit
std::string unit
Referenced by ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::valueToString(), ParamMetaData::withMidiNoteFormatting(), and ParamMetaData::withUnit().
customMinDisplay
std::string customMinDisplay
Referenced by ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withCustomMinDisplay().
customMaxDisplay
std::string customMaxDisplay
Referenced by ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withCustomMaxDisplay().
customDefaultDisplay
std::string customDefaultDisplay
Referenced by ParamMetaData::valueToString(), and ParamMetaData::withCustomDefaultDisplay().
discreteValues
std::unordered_map<int, std::string> discreteValues
Referenced by ParamMetaData::valueToString(), and ParamMetaData::withUnorderedMapFormatting().
decimalPlaces
int decimalPlaces {2}
Referenced by ParamMetaData::modulationNaturalToString(), ParamMetaData::valueToString(), and ParamMetaData::withDecimalPlaces().
defaultMidiNoteOctaveOffset
int defaultMidiNoteOctaveOffset {0} static
Referenced by ParamMetaData::asMIDINote().
midiNoteOctaveOffset
int midiNoteOctaveOffset {defaultMidiNoteOctaveOffset}
Referenced by ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
svA
float svA {0.f}
Referenced by ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::quantize(), ParamMetaData::valueFromString(), ParamMetaData::valueToString(), ParamMetaData::withATwoToTheBPlusCFormatting(), ParamMetaData::withLinearScaleFormatting(), and ParamMetaData::withScaledOffsetExpFormatting().
svB
float svB {0.f}
Referenced by ParamMetaData::modulationNaturalFromString(), ParamMetaData::modulationNaturalToString(), ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
svC
float svC {0.f}
Referenced by ParamMetaData::modulationNaturalToString(), ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
svD
float svD {0.f}
Referenced by ParamMetaData::modulationNaturalToString(), ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
exA
float exA {1.f}
Referenced by ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withExtendFactors().
exB
float exB {0.f}
Referenced by ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
NO_ALTERNATE
enum sst::basic_blocks::params::ParamMetaData::AlternateScaleWhen NO_ALTERNATE
Referenced by ParamMetaData::valueFromString(), ParamMetaData::valueToString(), and ParamMetaData::withoutDisplayRescaling().
alternateScaleCutoff
double alternateScaleCutoff {0.f}
Referenced by ParamMetaData::valueToString().
alternateScaleRescaling
double alternateScaleRescaling {0.f}
Referenced by ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
alternateScaleUnits
std::string alternateScaleUnits {}
Referenced by ParamMetaData::valueFromString(), and ParamMetaData::valueToString().
The documentation for this struct was generated from the following file:
ParamMetadata.h