sst-basic-blocks: SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform > Struct Template Reference
SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform > Struct Template Reference
#include <SimpleLFO.h>
Public Types
enum Shape {
SINE , RAMP , DOWN_RAMP , TRI ,
PULSE , SMOOTH_NOISE , SH_NOISE , RANDOM_TRIGGER ,
SAW_TRI_RAMP
}
Public Member Functions
SimpleLFO (SRProvider *s, sst::basic_blocks::dsp::RNG &extRng)
SimpleLFO (SRProvider *s)
void restartRandomSequence (double corr)
float bend1 (float x, float d) const
void attackForDisplay (const int lshape)
void attack (const int lshape)
void applyPhaseOffset (float dPhase)
void setAmplitude (float f)
void freeze ()
void process_block (const float r, const float d, const int lshape, bool reverse=false, float tsScale=1.f, float phaseDeformAngle=0)
Public Attributes
SRProvider * srProvider {nullptr}
sst::basic_blocks::dsp::RNG & objrngRef
sst::basic_blocks::dsp::RNG objrng {0}
std::function< float()> urng = []() { return 0.f; }
float rngState [2] {0, 0}
float rngHistory [4] {0, 0, 0, 0}
float rngCurrent {0}
float lastTarget {0}
float outputBlock [BLOCK_SIZE]
float phase {0}
bool needsRandomRestart {false}
float lastDPhase {0}
float amplitude {1.0}
int rndTrigCountdown {0}
float lastRate {-123485924.0}
float lastFRate {0}
float lastTSScale {-76543.2f}
float lastSR {0}
Static Public Attributes
static constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE}
Member Enumeration Documentation
Shape
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> enum Shape
Enumerator
SINE
RAMP
DOWN_RAMP
TRI
PULSE
SMOOTH_NOISE
SH_NOISE
RANDOM_TRIGGER
SAW_TRI_RAMP
Constructor & Destructor Documentation
SimpleLFO() [1/2]
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> SimpleLFO (SRProvider * s, sst::basic_blocks::dsp::RNG & extRng)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::objrngRef, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence(), RNG::unifPM1(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::urng.
SimpleLFO() [2/2]
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> SimpleLFO (SRProvider * s)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::objrng, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock, RNG::reseedWithClock(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence(), RNG::unifPM1(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::urng.
Member Function Documentation
restartRandomSequence()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void restartRandomSequence (double corr)
References sst::basic_blocks::dsp::correlated_noise_o2mk2_suppliedrng(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngCurrent, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngHistory, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngState, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::urng.
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
bend1()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float bend1 (float x, float d) const
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
attackForDisplay()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void attackForDisplay (const int lshape)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::amplitude, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attack(), sst::basic_blocks::dsp::correlated_noise_o2mk2_suppliedrng(), RNG::forDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastDPhase, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::objrngRef, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngCurrent, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngHistory, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngState, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::urng.
attack()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void attack (const int lshape)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastDPhase, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::needsRandomRestart, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::phase, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SH_NOISE, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SMOOTH_NOISE.
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay().
applyPhaseOffset()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void applyPhaseOffset (float dPhase)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastDPhase, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::needsRandomRestart, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::phase.
setAmplitude()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void setAmplitude (float f)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::amplitude.
freeze()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void freeze ()
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastTarget, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock.
process_block()
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> void process_block (const float r, const float d, const int lshape, bool reverse = false, float tsScale = 1.f, float phaseDeformAngle = 0)
References SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::amplitude, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::bend1(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::BLOCK_SIZE_INV, sst::basic_blocks::dsp::correlated_noise_o2mk2_suppliedrng(), sst::basic_blocks::dsp::cubic_ipol(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::DOWN_RAMP, sst::basic_blocks::dsp::fastsin(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastFRate, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastRate, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastSR, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastTarget, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::lastTSScale, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::needsRandomRestart, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::outputBlock, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::phase, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::PULSE, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::RAMP, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::RANDOM_TRIGGER, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rndTrigCountdown, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngCurrent, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngHistory, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::rngState, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SAW_TRI_RAMP, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SH_NOISE, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SINE, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SMOOTH_NOISE, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::srProvider, SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::TRI, and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::urng.
Member Data Documentation
srProvider
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> SRProvider* srProvider {nullptr}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
objrngRef
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> sst::basic_blocks::dsp::RNG& objrngRef
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
objrng
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> sst::basic_blocks::dsp::RNG objrng {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
urng
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> std::function<float()> urng = []() { return 0.f; }
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
BLOCK_SIZE_INV
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE} static constexpr
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
rngState
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float rngState[2] {0, 0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence().
rngHistory
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float rngHistory[4] {0, 0, 0, 0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence().
rngCurrent
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float rngCurrent {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::restartRandomSequence().
lastTarget
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastTarget {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::freeze(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
outputBlock
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float outputBlock[BLOCK_SIZE]
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attack(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::freeze(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
phase
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float phase {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::applyPhaseOffset(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attack(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
needsRandomRestart
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> bool needsRandomRestart {false}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::applyPhaseOffset(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attack(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
lastDPhase
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastDPhase {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::applyPhaseOffset(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attack(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay().
amplitude
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float amplitude {1.0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::setAmplitude().
rndTrigCountdown
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> int rndTrigCountdown {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
lastRate
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastRate {-123485924.0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
lastFRate
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastFRate {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
lastTSScale
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastTSScale {-76543.2f}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
lastSR
template<typename SRProvider , int BLOCK_SIZE, bool clampDeform = false> float lastSR {0}
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::process_block().
The documentation for this struct was generated from the following file:
SimpleLFO.h