sst-basic-blocks: DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider > Struct Template Reference
DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider > Struct Template Reference
#include <DiscreteStagesEnvelope.h>
Public Types
enum Stage {
s_delay , s_attack , s_hold , s_decay ,
s_sustain , s_release , s_analog_residual_decay , s_analog_residual_release ,
s_eoc , s_complete
}
Public Member Functions
DiscreteStagesEnvelope ()
void resetCurrent ()
bool preBlockCheck ()
float shapeTarget (float target, int ashape, int dshape, int rshape=0)
void updateBlockTo (float target)
void updateBlockToNoCube (float target)
void step ()
void immediatelySilence ()
float rateFrom01 (float r01)
float rateTo01 (float r)
float deltaTo01 (float d)
Static Public Member Functions
static constexpr float etminV ()
static constexpr float etmaxV ()
Public Attributes
float output {0}
float outputCubed {0}
float eoc_output {0}
float outputCache [BLOCK_SIZE]
float outBlock0 {0.f}
float outputCacheCubed [BLOCK_SIZE]
int current {BLOCK_SIZE}
int eoc_countdown {0}
enum sst::basic_blocks::modulators::DiscreteStagesEnvelope::Stage s_complete
Static Public Attributes
static constexpr float etMin {etminV()}
static constexpr float etMax {etmaxV()}
static constexpr float etScale {etMax - etMin}
static constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE}
Member Enumeration Documentation
Stage
template<int BLOCK_SIZE, typename RangeProvider > enum Stage
Enumerator
s_delay
s_attack
s_hold
s_decay
s_sustain
s_release
s_analog_residual_decay
s_analog_residual_release
s_eoc
s_complete
Constructor & Destructor Documentation
DiscreteStagesEnvelope()
template<int BLOCK_SIZE, typename RangeProvider > DiscreteStagesEnvelope ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCacheCubed.
Member Function Documentation
etminV()
template<int BLOCK_SIZE, typename RangeProvider > static constexpr float etminV () static constexpr
References sst::basic_blocks::modulators::ENVTIME_2TWOX.
etmaxV()
template<int BLOCK_SIZE, typename RangeProvider > static constexpr float etmaxV () static constexpr
References sst::basic_blocks::modulators::ENVTIME_2TWOX.
resetCurrent()
template<int BLOCK_SIZE, typename RangeProvider > void resetCurrent ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_output.
Referenced by DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::attack(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attack(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), and ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom().
preBlockCheck()
template<int BLOCK_SIZE, typename RangeProvider > bool preBlockCheck ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_output, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::output, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_analog_residual_decay, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_analog_residual_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_complete, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_eoc.
Referenced by ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlockScaledAD(), DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlockScaledAD(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processScaledAD().
shapeTarget()
template<int BLOCK_SIZE, typename RangeProvider > float shapeTarget (float target, int ashape, int dshape, int rshape = 0)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_analog_residual_release, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_attack, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_decay, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_release.
Referenced by ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), and ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD().
updateBlockTo()
template<int BLOCK_SIZE, typename RangeProvider > void updateBlockTo (float target)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::BLOCK_SIZE_INV, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCacheCubed.
Referenced by ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlockScaledAD(), DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlockScaledAD(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processScaledAD().
updateBlockToNoCube()
template<int BLOCK_SIZE, typename RangeProvider > void updateBlockToNoCube (float target)
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::BLOCK_SIZE_INV, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache.
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore().
step()
template<int BLOCK_SIZE, typename RangeProvider > void step ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::output, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCacheCubed, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCubed.
Referenced by ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlockScaledAD(), DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlockScaledAD(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processScaledAD().
immediatelySilence()
template<int BLOCK_SIZE, typename RangeProvider > void immediatelySilence ()
References DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::current, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_countdown, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::eoc_output, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outBlock0, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::output, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCache, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCacheCubed, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::outputCubed, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::s_complete.
rateFrom01()
template<int BLOCK_SIZE, typename RangeProvider > float rateFrom01 (float r01)
References sst::basic_blocks::modulators::ENVTIME_EXP, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etMin, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale.
Referenced by ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process01AD(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlock01AD(), and DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processBlock01AD().
rateTo01()
template<int BLOCK_SIZE, typename RangeProvider > float rateTo01 (float r)
References sst::basic_blocks::modulators::ENVTIME_EXP, DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etMin, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale.
deltaTo01()
template<int BLOCK_SIZE, typename RangeProvider > float deltaTo01 (float d)
References sst::basic_blocks::modulators::ENVTIME_EXP, and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::etScale.
Member Data Documentation
etMin
template<int BLOCK_SIZE, typename RangeProvider > constexpr float etMin {etminV()} static constexpr
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::rateFrom01(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::rateTo01(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogADSR(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalADSR(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD().
etMax
template<int BLOCK_SIZE, typename RangeProvider > constexpr float etMax {etmaxV()} static
etScale
template<int BLOCK_SIZE, typename RangeProvider > constexpr float etScale {etMax - etMin} static
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::deltaTo01(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::dPhase(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::rateFrom01(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::rateTo01(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogADSR(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalADSR(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD().
BLOCK_SIZE_INV
template<int BLOCK_SIZE, typename RangeProvider > constexpr float BLOCK_SIZE_INV {1.f / BLOCK_SIZE} static constexpr
Referenced by ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::onSampleRateChanged(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::onSampleRateChanged(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockToNoCube().
output
template<int BLOCK_SIZE, typename RangeProvider > float output {0}
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), and ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalADSR().
outputCubed
template<int BLOCK_SIZE, typename RangeProvider > float outputCubed {0}
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step().
eoc_output
template<int BLOCK_SIZE, typename RangeProvider > float eoc_output {0}
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::resetCurrent().
outputCache
template<int BLOCK_SIZE, typename RangeProvider > float outputCache[BLOCK_SIZE]
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::DiscreteStagesEnvelope(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlock(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockToNoCube().
outBlock0
template<int BLOCK_SIZE, typename RangeProvider > float outBlock0 {0.f}
Referenced by AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFrom(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::attackFromWithDelay(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockToNoCube().
outputCacheCubed
template<int BLOCK_SIZE, typename RangeProvider > float outputCacheCubed[BLOCK_SIZE]
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::DiscreteStagesEnvelope(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo().
current
template<int BLOCK_SIZE, typename RangeProvider > int current {BLOCK_SIZE}
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::process(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::process(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlock(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::processScaledAD(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::resetCurrent(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::step(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockTo(), and DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::updateBlockToNoCube().
eoc_countdown
template<int BLOCK_SIZE, typename RangeProvider > int eoc_countdown {0}
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::resetCurrent(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::stepDigital(), DAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::stepDigital(), DAHDSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider, processEverySample >::stepDigital(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogADSR(), DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalADSR(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetDigitalDAHD().
s_complete
template<int BLOCK_SIZE, typename RangeProvider > enum sst::basic_blocks::modulators::DiscreteStagesEnvelope::Stage s_complete
Referenced by DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::immediatelySilence(), DiscreteStagesEnvelope< BLOCK_SIZE, RangeProvider >::preBlockCheck(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processBlock(), AHDSRShapedSC< SRProvider, BLOCK_SIZE, RangeProvider >::processCore(), ADAREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::processScaledAD(), ADSREnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogADSR(), and DAHDEnvelope< SRProvider, BLOCK_SIZE, RangeProvider >::targetAnalogDAHD().
The documentation for this struct was generated from the following file:
DiscreteStagesEnvelope.h