sst-basic-blocks: HilbertTransformStereoSSE Struct Reference
HilbertTransformStereoSSE Struct Reference
#include <HilbertTransform.h>
Classes
struct BQ
Public Member Functions
void setSampleRate (float sr)
void setHilbertCoefs ()
SIMD_M128 stepStereo (float L, float R)
std::pair< std::complex< float >, std::complex< float > > stepToComplex (float L, float R)
std::pair< std::pair< float, float >, std::pair< float, float > > stepToPair (float L, float R)
Public Attributes
struct sst::basic_blocks::dsp::HilbertTransformStereoSSE::BQ allpassSSE [3]
float sampleRate {0}
float hilbertCoefs [12]
Member Function Documentation
setSampleRate()
void setSampleRate (float sr)
References HilbertTransformStereoSSE::sampleRate, and HilbertTransformStereoSSE::setHilbertCoefs().
setHilbertCoefs()
void setHilbertCoefs ()
References HilbertTransformStereoSSE::allpassSSE, HilbertTransformStereoSSE::hilbertCoefs, HilbertTransformStereoSSE::sampleRate, and HilbertTransformStereoSSE::BQ::setCoefs().
Referenced by HilbertTransformStereoSSE::setSampleRate().
stepStereo()
SIMD_M128 stepStereo (float L, float R)
References HilbertTransformStereoSSE::allpassSSE, SIMD_MM, and HilbertTransformStereoSSE::BQ::step().
Referenced by HilbertTransformStereoSSE::stepToComplex(), and HilbertTransformStereoSSE::stepToPair().
stepToComplex()
std::pair< std::complex< float >, std::complex< float > > stepToComplex (float L, float R)
References SIMD_MM, and HilbertTransformStereoSSE::stepStereo().
stepToPair()
std::pair< std::pair< float, float >, std::pair< float, float > > stepToPair (float L, float R)
References SIMD_MM, and HilbertTransformStereoSSE::stepStereo().
Member Data Documentation
allpassSSE
struct sst::basic_blocks::dsp::HilbertTransformStereoSSE::BQ allpassSSE[3]
Referenced by HilbertTransformStereoSSE::setHilbertCoefs(), and HilbertTransformStereoSSE::stepStereo().
sampleRate
float sampleRate {0}
Referenced by HilbertTransformStereoSSE::setHilbertCoefs(), and HilbertTransformStereoSSE::setSampleRate().
hilbertCoefs
float hilbertCoefs[12]
Referenced by HilbertTransformStereoSSE::setHilbertCoefs().
The documentation for this struct was generated from the following file:
HilbertTransform.h