sst-basic-blocks: lipol_sse< maxBlockSize, first_run_checks > Struct Template Reference
lipol_sse< maxBlockSize, first_run_checks > Struct Template Reference
#include <BlockInterpolators.h>
Public Member Functions
lipol_sse ()
void set_target (float f)
void set_target_smoothed (float f)
void instantize ()
void set_target_instantize (float f)
void set_target_instant (float f)
float get_target () const
void multiply_block_to (const float *__restrict const in, float *__restrict out, int bsQuad=-1) const
void multiply_block (float *in, int bsQuad=-1) const
void multiply_2_blocks (float *__restrict in1, float *__restrict in2, int bsQuad=-1) const
void multiply_2_blocks_to (const float *__restrict const inL, const float *__restrict const inR, float *__restrict outL, float *__restrict outR, int bsQuad=-1) const
void MAC_block_to (float *__restrict src, float *__restrict dst, int bsQuad=-1) const
void MAC_2_blocks_to (float *__restrict src1, float *__restrict src2, float *__restrict dst1, float *__restrict dst2, int bsQuad=-1) const
void fade_blocks (float *__restrict inA, float *__restrict inB, float *__restrict out) const
void fade_block_to (float *__restrict src1, float *__restrict src2, float *__restrict dst, int bsQuad=-1) const
void fade_2_blocks_to (float *__restrict src11, float *__restrict src12, float *__restrict src21, float *__restrict src22, float *__restrict dst1, float *__restrict dst2, int bsQuad=-1) const
void fade_blocks_inplace (float *__restrict inAOut, float *__restrict inB) const
void fade_2_blocks_inplace (float *__restrict src11out, float *__restrict src12, float *__restrict src21out, float *__restrict src22, int bsQuad=-1) const
void store_block (float *__restrict out, int bsQuad=-1) const
void trixpan_blocks (float *__restrict L, float *__restrict R, float *__restrict dL, float *__restrict dR, int bsQuad=-1) const
void set_blocksize (size_t bs)
Public Attributes
int numRegisters {maxBlockSize >> 2}
int blockSize {maxBlockSize}
float blockSizeInv {1.f / blockSize}
float registerSizeInv {1.f / (blockSize >> 2)}
float target {0.f}
float current {0.f}
bool first_run {true}
Static Public Attributes
static constexpr int maxRegisters {maxBlockSize >> 2}
Constructor & Destructor Documentation
lipol_sse()
template<int maxBlockSize, bool first_run_checks = true> lipol_sse ()
References SIMD_MM.
Member Function Documentation
set_target()
template<int maxBlockSize, bool first_run_checks = true> void set_target (float f)
References lipol_sse< maxBlockSize, first_run_checks >::current, lipol_sse< maxBlockSize, first_run_checks >::first_run, and lipol_sse< maxBlockSize, first_run_checks >::target.
set_target_smoothed()
template<int maxBlockSize, bool first_run_checks = true> void set_target_smoothed (float f)
References lipol_sse< maxBlockSize, first_run_checks >::current, and lipol_sse< maxBlockSize, first_run_checks >::target.
instantize()
template<int maxBlockSize, bool first_run_checks = true> void instantize ()
References lipol_sse< maxBlockSize, first_run_checks >::set_target_instant(), and lipol_sse< maxBlockSize, first_run_checks >::target.
set_target_instantize()
template<int maxBlockSize, bool first_run_checks = true> void set_target_instantize (float f)
References lipol_sse< maxBlockSize, first_run_checks >::set_target_instant().
set_target_instant()
template<int maxBlockSize, bool first_run_checks = true> void set_target_instant (float f)
References lipol_sse< maxBlockSize, first_run_checks >::current, and lipol_sse< maxBlockSize, first_run_checks >::target.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::instantize(), and lipol_sse< maxBlockSize, first_run_checks >::set_target_instantize().
get_target()
template<int maxBlockSize, bool first_run_checks = true> float get_target () const
References lipol_sse< maxBlockSize, first_run_checks >::target.
multiply_block_to()
template<int maxBlockSize, bool first_run_checks = true> void multiply_block_to (const float *__restrict const in, float *__restrict out, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::multiply_2_blocks_to().
multiply_block()
template<int maxBlockSize, bool first_run_checks = true> void multiply_block (float * in, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::multiply_2_blocks().
multiply_2_blocks()
template<int maxBlockSize, bool first_run_checks = true> void multiply_2_blocks (float *__restrict in1, float *__restrict in2, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::multiply_block().
multiply_2_blocks_to()
template<int maxBlockSize, bool first_run_checks = true> void multiply_2_blocks_to (const float *__restrict const inL, const float *__restrict const inR, float *__restrict outL, float *__restrict outR, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::multiply_block_to().
MAC_block_to()
template<int maxBlockSize, bool first_run_checks = true> void MAC_block_to (float *__restrict src, float *__restrict dst, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::MAC_2_blocks_to().
MAC_2_blocks_to()
template<int maxBlockSize, bool first_run_checks = true> void MAC_2_blocks_to (float *__restrict src1, float *__restrict src2, float *__restrict dst1, float *__restrict dst2, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::MAC_block_to().
fade_blocks()
template<int maxBlockSize, bool first_run_checks = true> void fade_blocks (float *__restrict inA, float *__restrict inB, float *__restrict out) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::fade_block_to().
fade_block_to()
template<int maxBlockSize, bool first_run_checks = true> void fade_block_to (float *__restrict src1, float *__restrict src2, float *__restrict dst, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::fade_blocks(), and lipol_sse< maxBlockSize, first_run_checks >::numRegisters.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::fade_2_blocks_to().
fade_2_blocks_to()
template<int maxBlockSize, bool first_run_checks = true> void fade_2_blocks_to (float *__restrict src11, float *__restrict src12, float *__restrict src21, float *__restrict src22, float *__restrict dst1, float *__restrict dst2, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::fade_block_to().
fade_blocks_inplace()
template<int maxBlockSize, bool first_run_checks = true> void fade_blocks_inplace (float *__restrict inAOut, float *__restrict inB) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
Referenced by lipol_sse< maxBlockSize, first_run_checks >::fade_2_blocks_inplace().
fade_2_blocks_inplace()
template<int maxBlockSize, bool first_run_checks = true> void fade_2_blocks_inplace (float *__restrict src11out, float *__restrict src12, float *__restrict src21out, float *__restrict src22, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::fade_blocks_inplace(), and lipol_sse< maxBlockSize, first_run_checks >::numRegisters.
store_block()
template<int maxBlockSize, bool first_run_checks = true> void store_block (float *__restrict out, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
trixpan_blocks()
template<int maxBlockSize, bool first_run_checks = true> void trixpan_blocks (float *__restrict L, float *__restrict R, float *__restrict dL, float *__restrict dR, int bsQuad = -1) const
References lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and SIMD_MM.
set_blocksize()
template<int maxBlockSize, bool first_run_checks = true> void set_blocksize (size_t bs)
References lipol_sse< maxBlockSize, first_run_checks >::blockSize, lipol_sse< maxBlockSize, first_run_checks >::blockSizeInv, lipol_sse< maxBlockSize, first_run_checks >::numRegisters, and lipol_sse< maxBlockSize, first_run_checks >::registerSizeInv.
Member Data Documentation
maxRegisters
template<int maxBlockSize, bool first_run_checks = true> constexpr int maxRegisters {maxBlockSize >> 2} static constexpr
numRegisters
template<int maxBlockSize, bool first_run_checks = true> int numRegisters {maxBlockSize >> 2}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::fade_2_blocks_inplace(), lipol_sse< maxBlockSize, first_run_checks >::fade_block_to(), lipol_sse< maxBlockSize, first_run_checks >::fade_blocks(), lipol_sse< maxBlockSize, first_run_checks >::fade_blocks_inplace(), lipol_sse< maxBlockSize, first_run_checks >::MAC_block_to(), lipol_sse< maxBlockSize, first_run_checks >::multiply_block(), lipol_sse< maxBlockSize, first_run_checks >::multiply_block_to(), lipol_sse< maxBlockSize, first_run_checks >::set_blocksize(), lipol_sse< maxBlockSize, first_run_checks >::store_block(), and lipol_sse< maxBlockSize, first_run_checks >::trixpan_blocks().
blockSize
template<int maxBlockSize, bool first_run_checks = true> int blockSize {maxBlockSize}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::set_blocksize().
blockSizeInv
template<int maxBlockSize, bool first_run_checks = true> float blockSizeInv {1.f / blockSize}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::set_blocksize().
registerSizeInv
template<int maxBlockSize, bool first_run_checks = true> float registerSizeInv {1.f / (blockSize >> 2)}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::set_blocksize().
target
template<int maxBlockSize, bool first_run_checks = true> float target {0.f}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::get_target(), lipol_sse< maxBlockSize, first_run_checks >::instantize(), lipol_sse< maxBlockSize, first_run_checks >::set_target(), lipol_sse< maxBlockSize, first_run_checks >::set_target_instant(), and lipol_sse< maxBlockSize, first_run_checks >::set_target_smoothed().
current
template<int maxBlockSize, bool first_run_checks = true> float current {0.f}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::set_target(), lipol_sse< maxBlockSize, first_run_checks >::set_target_instant(), and lipol_sse< maxBlockSize, first_run_checks >::set_target_smoothed().
first_run
template<int maxBlockSize, bool first_run_checks = true> bool first_run {true}
Referenced by lipol_sse< maxBlockSize, first_run_checks >::set_target().
The documentation for this struct was generated from the following file:
BlockInterpolators.h