sst-basic-blocks: DPWSawOscillator< SmoothingStrategy > Struct Template Reference
DPWSawOscillator< SmoothingStrategy > Struct Template Reference
#include <DPWSawPulseOscillator.h>
Public Member Functions
void retrigger ()
void setFrequency (double freqInHz, double sampleRateInv)
double step ()
template<int blockSize>
void fillBlock (float out[blockSize])
Static Public Member Functions
static double valueAt (double p, double dp)
Public Attributes
double phase
SmoothingStrategy::smoothValue_t dPhase
Member Function Documentation
retrigger()
template<typename SmoothingStrategy = LagSmoothingStrategy> void retrigger ()
References DPWSawOscillator< SmoothingStrategy >::dPhase, and DPWSawOscillator< SmoothingStrategy >::phase.
setFrequency()
template<typename SmoothingStrategy = LagSmoothingStrategy> void setFrequency (double freqInHz, double sampleRateInv)
References DPWSawOscillator< SmoothingStrategy >::dPhase.
valueAt()
template<typename SmoothingStrategy = LagSmoothingStrategy> static double valueAt (double p, double dp) static
Referenced by DPWSawOscillator< SmoothingStrategy >::step(), and DPWPulseOscillator< SmoothingStrategy >::step().
step()
template<typename SmoothingStrategy = LagSmoothingStrategy> double step ()
References DPWSawOscillator< SmoothingStrategy >::dPhase, DPWSawOscillator< SmoothingStrategy >::phase, and DPWSawOscillator< SmoothingStrategy >::valueAt().
Referenced by DPWSawOscillator< SmoothingStrategy >::fillBlock().
fillBlock()
template<typename SmoothingStrategy = LagSmoothingStrategy> template<int blockSize> void fillBlock (float out[blockSize])
References DPWSawOscillator< SmoothingStrategy >::step().
Member Data Documentation
phase
template<typename SmoothingStrategy = LagSmoothingStrategy> double phase
Referenced by DPWSawOscillator< SmoothingStrategy >::retrigger(), and DPWSawOscillator< SmoothingStrategy >::step().
dPhase
template<typename SmoothingStrategy = LagSmoothingStrategy> SmoothingStrategy::smoothValue_t dPhase
Referenced by DPWSawOscillator< SmoothingStrategy >::retrigger(), DPWSawOscillator< SmoothingStrategy >::setFrequency(), and DPWSawOscillator< SmoothingStrategy >::step().
The documentation for this struct was generated from the following file:
DPWSawPulseOscillator.h