sst-basic-blocks: RNG Struct Reference
RNG Struct Reference
#include <RNG.h>
Public Member Functions
RNG ()
RNG (uint32_t seed)
void reseedWithClock ()
void reseed (uint32_t seed)
float unif01 ()
float unifPM1 ()
float unif (const float min, const float max)
float half01 ()
float normPM1 ()
float half (const float min, const float max)
float norm (const float min, const float max)
uint32_t unifU32 ()
int unifInt (const int min, const int max)
bool boolean ()
float forDisplay ()
Constructor & Destructor Documentation
RNG() [1/2]
RNG ()
RNG() [2/2]
RNG (uint32_t seed)
Member Function Documentation
reseedWithClock()
void reseedWithClock ()
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
reseed()
void reseed (uint32_t seed)
unif01()
float unif01 ()
Referenced by RNG::unif().
unifPM1()
float unifPM1 ()
Referenced by FXModControl< blockSize >::pre_process(), SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO(), and SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::SimpleLFO().
unif()
float unif (const float min, const float max)
References RNG::unif01().
half01()
float half01 ()
normPM1()
float normPM1 ()
half()
float half (const float min, const float max)
norm()
float norm (const float min, const float max)
unifU32()
uint32_t unifU32 ()
unifInt()
int unifInt (const int min, const int max)
boolean()
bool boolean ()
forDisplay()
float forDisplay ()
Referenced by SimpleLFO< SRProvider, BLOCK_SIZE, clampDeform >::attackForDisplay().
The documentation for this struct was generated from the following file:
RNG.h