sst-plugininfra: TiXmlElement Class Reference
TiXmlElement Class Reference
The element is a container class.
Public Member Functions
TiXmlElement (const char *in_value)
Construct an element.
TiXmlElement (const TiXmlElement &)
TiXmlElement & operator= (const TiXmlElement &base)
virtual ~TiXmlElement ()
const char * Attribute (const char *name) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
const char * Attribute (const char *name, int *i) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
const char * Attribute (const char *name, double *d) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
int QueryIntAttribute (const char *name, int *_value) const
QueryIntAttribute examines the attribute - it is an alternative to the Attribute() method with richer error checking.
int QueryUnsignedAttribute (const char *name, unsigned *_value) const
QueryUnsignedAttribute examines the attribute - see QueryIntAttribute().
int QueryBoolAttribute (const char *name, bool *_value) const
QueryBoolAttribute examines the attribute - see QueryIntAttribute().
int QueryDoubleAttribute (const char *name, double *_value) const
QueryDoubleAttribute examines the attribute - see QueryIntAttribute().
int QueryFloatAttribute (const char *name, float *_value) const
QueryFloatAttribute examines the attribute - see QueryIntAttribute().
void SetAttribute (const char *name, const char *_value)
Sets an attribute of name to a given value.
void SetAttribute (const char *name, int value)
Sets an attribute of name to a given value.
void SetDoubleAttribute (const char *name, double value)
Sets an attribute of name to a given value.
void RemoveAttribute (const char *name)
Deletes an attribute with the given name.
const TiXmlAttribute * FirstAttribute () const
Access the first attribute in this element.
TiXmlAttribute * FirstAttribute ()
const TiXmlAttribute * LastAttribute () const
Access the last attribute in this element.
TiXmlAttribute * LastAttribute ()
const char * GetText () const
Convenience function for easy access to the text inside an element.
virtual TiXmlNode * Clone () const
Creates a new Element and returns it - the returned element is a copy.
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'. Will be null if none found. The first child of this node with the matching 'value'. Will be null if none found.
TiXmlNode * FirstChild (const char *_value)
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
void CopyTo (TiXmlElement *target) const
void ClearThis ()
const char * ReadValue (const char *in, TiXmlParsingData *prevData, TiXmlEncoding encoding)
Protected Member Functions inherited from TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Additional Inherited Members
Public Types inherited from TiXmlNode
enum NodeType {
TINYXML_DOCUMENT , TINYXML_ELEMENT , TINYXML_COMMENT , TINYXML_UNKNOWN ,
TINYXML_TEXT , TINYXML_DECLARATION , TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0 , TIXML_ERROR , TIXML_ERROR_OPENING_FILE , TIXML_ERROR_PARSING_ELEMENT ,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME , TIXML_ERROR_READING_ELEMENT_VALUE , TIXML_ERROR_READING_ATTRIBUTES , TIXML_ERROR_PARSING_EMPTY ,
TIXML_ERROR_READING_END_TAG , TIXML_ERROR_PARSING_UNKNOWN , TIXML_ERROR_PARSING_COMMENT , TIXML_ERROR_PARSING_DECLARATION ,
TIXML_ERROR_DOCUMENT_EMPTY , TIXML_ERROR_EMBEDDED_NULL , TIXML_ERROR_PARSING_CDATA , TIXML_ERROR_DOCUMENT_TOP_ONLY ,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
The element is a container class.
It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Constructor & Destructor Documentation
TiXmlElement() [1/2]
TiXmlElement (const char * in_value)
Construct an element.
References TiXmlNode::firstChild, TiXmlNode::lastChild, and TiXmlNode::value.
TiXmlElement() [2/2]
TiXmlElement (const TiXmlElement & copy)
References CopyTo(), TiXmlNode::firstChild, and TiXmlNode::lastChild.
~TiXmlElement()
~TiXmlElement () virtual
References ClearThis().
Member Function Documentation
operator=()
TiXmlElement & operator= (const TiXmlElement & base)
References ClearThis(), and CopyTo().
Attribute() [1/3]
const char * Attribute (const char * name) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
References TiXmlAttributeSet::Find(), and TiXmlAttribute::Value().
Referenced by main().
Attribute() [2/3]
const char * Attribute (const char * name, int * i) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
If the attribute exists and can be converted to an integer, the integer value will be put in the return 'i', if 'i' is non-null.
References TiXmlAttributeSet::Find(), TiXmlAttribute::QueryIntValue(), and TiXmlAttribute::Value().
Attribute() [3/3]
const char * Attribute (const char * name, double * d) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists.
If the attribute exists and can be converted to an double, the double value will be put in the return 'd', if 'd' is non-null.
References TiXmlAttributeSet::Find(), TiXmlAttribute::QueryDoubleValue(), and TiXmlAttribute::Value().
QueryIntAttribute()
int QueryIntAttribute (const char * name, int * _value) const
QueryIntAttribute examines the attribute - it is an alternative to the Attribute() method with richer error checking.
If the attribute is an integer, it is stored in 'value' and the call returns TIXML_SUCCESS. If it is not an integer, it returns TIXML_WRONG_TYPE. If the attribute does not exist, then TIXML_NO_ATTRIBUTE is returned.
References TiXmlAttributeSet::Find(), TiXmlAttribute::QueryIntValue(), and TIXML_NO_ATTRIBUTE.
Referenced by main().
QueryUnsignedAttribute()
int QueryUnsignedAttribute (const char * name, unsigned * _value) const
QueryUnsignedAttribute examines the attribute - see QueryIntAttribute().
References TiXmlAttributeSet::Find(), TiXmlAttribute::QueryIntValue(), TIXML_NO_ATTRIBUTE, and TiXmlNode::value.
QueryBoolAttribute()
int QueryBoolAttribute (const char * name, bool * _value) const
QueryBoolAttribute examines the attribute - see QueryIntAttribute().
Note that '1', 'true', or 'yes' are considered true, while '0', 'false' and 'no' are considered false.
References TiXmlAttributeSet::Find(), TiXmlBase::StringEqual(), TIXML_ENCODING_UNKNOWN, TIXML_NO_ATTRIBUTE, TIXML_SUCCESS, TIXML_WRONG_TYPE, and TiXmlAttribute::Value().
QueryDoubleAttribute()
int QueryDoubleAttribute (const char * name, double * _value) const
QueryDoubleAttribute examines the attribute - see QueryIntAttribute().
References TiXmlAttributeSet::Find(), TiXmlAttribute::QueryDoubleValue(), and TIXML_NO_ATTRIBUTE.
Referenced by main(), and QueryFloatAttribute().
QueryFloatAttribute()
int QueryFloatAttribute (const char * name, float * _value) const
QueryFloatAttribute examines the attribute - see QueryIntAttribute().
References QueryDoubleAttribute(), and TIXML_SUCCESS.
SetAttribute() [1/2]
void SetAttribute (const char * name, const char * _value)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
References TiXmlAttributeSet::FindOrCreate(), and TiXmlAttribute::SetValue().
Referenced by CopyTo(), main(), SetDoubleAttribute(), and KeyMapManager< FUNCS, maxFunc, KEY >::streamToXML().
SetAttribute() [2/2]
void SetAttribute (const char * name, int value)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
References TiXmlAttributeSet::FindOrCreate(), and TiXmlAttribute::SetIntValue().
SetDoubleAttribute()
void SetDoubleAttribute (const char * name, double value)
Sets an attribute of name to a given value.
The attribute will be created if it does not exist, or changed if it does.
References SetAttribute().
Referenced by main().
RemoveAttribute()
void RemoveAttribute (const char * name)
Deletes an attribute with the given name.
References TiXmlAttributeSet::Find(), TiXmlAttributeSet::Remove(), and TIXML_STRING.
FirstAttribute() [1/2]
const TiXmlAttribute* FirstAttribute () const
Access the first attribute in this element.
References TiXmlAttributeSet::First().
Referenced by main().
FirstAttribute() [2/2]
TiXmlAttribute* FirstAttribute ()
References TiXmlAttributeSet::First().
LastAttribute() [1/2]
const TiXmlAttribute* LastAttribute () const
Access the last attribute in this element.
References TiXmlAttributeSet::Last().
LastAttribute() [2/2]
TiXmlAttribute* LastAttribute ()
References TiXmlAttributeSet::Last().
GetText()
const char * GetText () const
Convenience function for easy access to the text inside an element.
Although easy and concise, GetText() is limited compared to getting the TiXmlText child and accessing it directly.
If the first child of 'this' is a TiXmlText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
    <foo>This is text</foo>
    const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
    <foo>This is <b>text</b></foo>
GetText() will return "This is ".
WARNING: GetText() accesses a child node - don't become confused with the similarly named TiXmlHandle::Text() and TiXmlNode::ToText() which are safe type casts on the referenced node.
References TiXmlNode::FirstChild(), TiXmlNode::ToText(), and TiXmlNode::Value().
Referenced by main().
Clone()
TiXmlNode * Clone () const virtual
Creates a new Element and returns it - the returned element is a copy.
Implements TiXmlNode.
References CopyTo(), TiXmlNode::TiXmlElement, and TiXmlNode::Value().
Print()
void Print (FILE * cfile, int depth) const virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements TiXmlBase.
References TiXmlAttributeSet::First(), TiXmlNode::firstChild, TiXmlNode::lastChild, TiXmlAttribute::Next(), TiXmlNode::NextSibling(), TiXmlAttribute::Print(), TiXmlBase::Print(), TiXmlNode::ToText(), and TiXmlNode::value.
Referenced by main().
Parse()
const char * Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements TiXmlBase.
References TiXmlAttributeSet::Add(), TiXmlParsingData::Cursor(), TiXmlAttributeSet::Find(), TiXmlNode::GetDocument(), TiXmlBase::location, TiXmlAttribute::Name(), TiXmlAttribute::NameTStr(), TiXmlAttribute::Parse(), TiXmlBase::ReadName(), ReadValue(), TiXmlAttribute::SetDocument(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlParsingData::Stamp(), TiXmlBase::StringEqual(), TiXmlBase::TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TiXmlBase::TIXML_ERROR_PARSING_ELEMENT, TiXmlBase::TIXML_ERROR_PARSING_EMPTY, TiXmlBase::TIXML_ERROR_READING_ATTRIBUTES, TiXmlBase::TIXML_ERROR_READING_END_TAG, TIXML_STRING, and TiXmlNode::value.
Referenced by main().
ToElement() [1/2]
virtual const TiXmlElement* ToElement () const virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
ToElement() [2/2]
virtual TiXmlElement* ToElement () virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Accept()
bool Accept (TiXmlVisitor * visitor) const virtual
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
References TiXmlAttributeSet::First(), TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), TiXmlVisitor::VisitEnter(), and TiXmlVisitor::VisitExit().
CopyTo()
void CopyTo (TiXmlElement * target) const protected
References TiXmlNode::Clone(), TiXmlNode::CopyTo(), TiXmlAttributeSet::First(), TiXmlNode::firstChild, TiXmlNode::LinkEndChild(), TiXmlAttribute::Name(), TiXmlAttribute::Next(), TiXmlNode::NextSibling(), SetAttribute(), and TiXmlAttribute::Value().
Referenced by Clone(), operator=(), and TiXmlElement().
ClearThis()
void ClearThis () protected
References TiXmlNode::Clear(), TiXmlAttributeSet::First(), and TiXmlAttributeSet::Remove().
Referenced by operator=(), and ~TiXmlElement().
ReadValue()
const char * ReadValue (const char * in, TiXmlParsingData * prevData, TiXmlEncoding encoding) protected
References TiXmlText::Blank(), TiXmlNode::GetDocument(), TiXmlNode::Identify(), TiXmlBase::IsWhiteSpaceCondensed(), TiXmlNode::LinkEndChild(), TiXmlText::Parse(), TiXmlBase::Parse(), TiXmlDocument::SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::StringEqual(), and TiXmlBase::TIXML_ERROR_READING_ELEMENT_VALUE.
Referenced by Parse().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp
tinyxmlparser.cpp