sst-plugininfra: TiXmlHandle Class Reference
TiXmlHandle Class Reference
Public Member Functions
TiXmlHandle (TiXmlNode *_node)
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
TiXmlHandle (const TiXmlHandle &ref)
Copy constructor.
TiXmlHandle operator= (const TiXmlHandle &ref)
TiXmlHandle FirstChild () const
Return a handle to the first child node.
TiXmlHandle FirstChild (const char *value) const
Return a handle to the first child node with the given name.
TiXmlHandle FirstChildElement () const
Return a handle to the first child element.
TiXmlHandle FirstChildElement (const char *value) const
Return a handle to the first child element with the given name.
TiXmlHandle Child (const char *value, int index) const
Return a handle to the "index" child with the given name.
TiXmlHandle Child (int index) const
Return a handle to the "index" child.
TiXmlHandle ChildElement (const char *value, int index) const
Return a handle to the "index" child element with the given name.
TiXmlHandle ChildElement (int index) const
Return a handle to the "index" child element.
TiXmlNode * ToNode () const
Return the handle as a TiXmlNode.
TiXmlElement * ToElement () const
Return the handle as a TiXmlElement.
TiXmlText * ToText () const
Return the handle as a TiXmlText.
TiXmlUnknown * ToUnknown () const
Return the handle as a TiXmlUnknown.
TiXmlNode * Node () const
TiXmlElement * Element () const
TiXmlText * Text () const
TiXmlUnknown * Unknown () const
Detailed Description
 A TiXmlHandle is a class that wraps a node pointer with null checks; this is
 an incredibly useful thing. Note that TiXmlHandle is not part of the TinyXml
 DOM structure. It is a separate utility class.
 Take an example:
 @verbatim
 <Document>
         <Element attributeA = "valueA">
                 <Child attributeB = "value1" />
                 <Child attributeB = "value2" />
         </Element>
 <Document>
Assuming you want the value of "attributeB" in the 2nd "Child" element, it's very easy to write a lot of code that looks like:
 TiXmlElement* root = document.FirstChildElement( "Document" );
 if ( root )
 {
         TiXmlElement* element = root->FirstChildElement( "Element" );
         if ( element )
         {
                 TiXmlElement* child = element->FirstChildElement( "Child" );
                 if ( child )
                 {
                         TiXmlElement* child2 = child->NextSiblingElement( "Child" );
                         if ( child2 )
{
                                 // Finally do something useful.
And that doesn't even cover "else" cases. TiXmlHandle addresses the verbosity of such code. A TiXmlHandle checks for null pointers so it is perfectly safe and correct to use:
 TiXmlHandle docHandle( &document );
 TiXmlElement* child2 = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).Child(
"Child", 1).ToElement(); if (child2) { // do something useful
Which is MUCH more concise and useful.
It is also safe to copy handles - internally they are nothing more than node pointers.
     TiXmlHandle handleCopy = handle;
What they should not be used for is iteration:
     int i=0;
     while ( true )
     {
             TiXmlElement* child = docHandle.FirstChild( "Document" ).FirstChild( "Element"
).Child("Child", i).ToElement(); if (!child) break;
             // do something
             ++i;
     }
It seems reasonable, but it is in fact two embedded while loops. The Child method is a linear walk to find the element, so this code would iterate much more than it needs to. Instead, prefer:
     TiXmlElement* child = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).FirstChild(
"Child").ToElement();
     for( child; child; child=child->NextSiblingElement() )
     {
             // do something
     }
Constructor & Destructor Documentation
TiXmlHandle() [1/2]
TiXmlHandle (TiXmlNode * _node)
Create a handle from any node (at any depth of the tree.) This can be a null pointer.
Referenced by Child(), ChildElement(), FirstChild(), and FirstChildElement().
TiXmlHandle() [2/2]
TiXmlHandle (const TiXmlHandle & ref)
Copy constructor.
Member Function Documentation
operator=()
TiXmlHandle operator= (const TiXmlHandle & ref)
FirstChild() [1/2]
TiXmlHandle FirstChild () const
Return a handle to the first child node.
References TiXmlNode::FirstChild(), and TiXmlHandle().
Referenced by main().
FirstChild() [2/2]
TiXmlHandle FirstChild (const char * value) const
Return a handle to the first child node with the given name.
References TiXmlNode::FirstChild(), TiXmlHandle(), and Catch::Generators::value().
FirstChildElement() [1/2]
TiXmlHandle FirstChildElement () const
Return a handle to the first child element.
References TiXmlNode::FirstChildElement(), and TiXmlHandle().
Referenced by main().
FirstChildElement() [2/2]
TiXmlHandle FirstChildElement (const char * value) const
Return a handle to the first child element with the given name.
References TiXmlNode::FirstChildElement(), TiXmlHandle(), and Catch::Generators::value().
Child() [1/2]
TiXmlHandle Child (const char * value, int index) const
Return a handle to the "index" child with the given name.
The first child is 0, the second 1, etc.
References TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), TiXmlHandle(), and Catch::Generators::value().
Referenced by main().
Child() [2/2]
TiXmlHandle Child (int index) const
Return a handle to the "index" child.
The first child is 0, the second 1, etc.
References TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), and TiXmlHandle().
ChildElement() [1/2]
TiXmlHandle ChildElement (const char * value, int index) const
Return a handle to the "index" child element with the given name.
The first child element is 0, the second 1, etc. Note that only TiXmlElements are indexed: other types are not counted.
References TiXmlNode::FirstChildElement(), TiXmlNode::NextSiblingElement(), TiXmlHandle(), and Catch::Generators::value().
Referenced by main().
ChildElement() [2/2]
TiXmlHandle ChildElement (int index) const
Return a handle to the "index" child element.
The first child element is 0, the second 1, etc. Note that only TiXmlElements are indexed: other types are not counted.
References TiXmlNode::FirstChildElement(), TiXmlNode::NextSiblingElement(), and TiXmlHandle().
ToNode()
TiXmlNode* ToNode () const
Return the handle as a TiXmlNode.
This may return null.
Referenced by Node().
ToElement()
TiXmlElement* ToElement () const
Return the handle as a TiXmlElement.
This may return null.
Referenced by Element().
ToText()
TiXmlText* ToText () const
Return the handle as a TiXmlText.
This may return null.
Referenced by Text().
ToUnknown()
TiXmlUnknown* ToUnknown () const
Return the handle as a TiXmlUnknown.
This may return null.
Referenced by Unknown().
Node()
TiXmlNode* Node () const
Deprecated:
use ToNode.
Return the handle as a TiXmlNode. This may return null.
References ToNode().
Referenced by main().
Element()
TiXmlElement* Element () const
Deprecated:
use ToElement.
Return the handle as a TiXmlElement. This may return null.
References ToElement().
Referenced by main().
Text()
TiXmlText* Text () const
Deprecated:
use ToText() Return the handle as a TiXmlText.
This may return null.
References ToText().
Referenced by main().
Unknown()
TiXmlUnknown* Unknown () const
Deprecated:
use ToUnknown() Return the handle as a TiXmlUnknown.
This may return null.
References ToUnknown().
Referenced by main().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp