sst-plugininfra: TiXmlAttributeSet Class Reference
TiXmlAttributeSet Class Reference
Public Member Functions
TiXmlAttributeSet ()
~TiXmlAttributeSet ()
void Add (TiXmlAttribute *attribute)
void Remove (TiXmlAttribute *attribute)
const TiXmlAttribute * First () const
TiXmlAttribute * First ()
const TiXmlAttribute * Last () const
TiXmlAttribute * Last ()
TiXmlAttribute * Find (const char *_name) const
TiXmlAttribute * FindOrCreate (const char *_name)
Constructor & Destructor Documentation
TiXmlAttributeSet()
TiXmlAttributeSet ()
~TiXmlAttributeSet()
~TiXmlAttributeSet ()
Member Function Documentation
Add()
void Add (TiXmlAttribute * attribute)
References Find(), TiXmlAttribute::Name(), and TIXML_STRING.
Referenced by FindOrCreate(), and TiXmlElement::Parse().
Remove()
void Remove (TiXmlAttribute * attribute)
Referenced by TiXmlElement::ClearThis(), and TiXmlElement::RemoveAttribute().
First() [1/2]
const TiXmlAttribute* First () const
Referenced by TiXmlElement::Accept(), TiXmlElement::ClearThis(), TiXmlElement::CopyTo(), TiXmlElement::FirstAttribute(), and TiXmlElement::Print().
First() [2/2]
TiXmlAttribute* First ()
Last() [1/2]
const TiXmlAttribute* Last () const
Referenced by TiXmlElement::LastAttribute().
Last() [2/2]
TiXmlAttribute* Last ()
Find()
TiXmlAttribute * Find (const char * _name) const
References TiXmlNode::next.
Referenced by Add(), TiXmlElement::Attribute(), FindOrCreate(), TiXmlElement::Parse(), TiXmlElement::QueryBoolAttribute(), TiXmlElement::QueryDoubleAttribute(), TiXmlElement::QueryIntAttribute(), TiXmlElement::QueryUnsignedAttribute(), and TiXmlElement::RemoveAttribute().
FindOrCreate()
TiXmlAttribute * FindOrCreate (const char * _name)
References Add(), Find(), and TiXmlAttribute::SetName().
Referenced by TiXmlElement::SetAttribute().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp