sst-plugininfra: TiXmlPrinter Class Reference
TiXmlPrinter Class Reference
Print to memory functionality.
Public Member Functions
TiXmlPrinter ()
virtual bool VisitEnter (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitExit (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitEnter (const TiXmlElement &element, const TiXmlAttribute *firstAttribute)
Visit an element.
virtual bool VisitExit (const TiXmlElement &element)
Visit an element.
virtual bool Visit (const TiXmlDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const TiXmlText &text)
Visit a text node.
virtual bool Visit (const TiXmlComment &comment)
Visit a comment node.
virtual bool Visit (const TiXmlUnknown &unknown)
Visit an unknown node.
void SetIndent (const char *_indent)
Set the indent characters for printing.
const char * Indent ()
Query the indention string.
void SetLineBreak (const char *_lineBreak)
Set the line breaking string.
const char * LineBreak ()
Query the current line breaking string.
void SetStreamPrinting ()
Switch over to "stream printing" which is the most dense formatting without linebreaks.
const char * CStr ()
Return the result.
size_t Size ()
Return the length of the result string.
Public Member Functions inherited from TiXmlVisitor
virtual ~TiXmlVisitor ()
Detailed Description
Print to memory functionality.
The TiXmlPrinter is useful when you need to:
-# Print to memory (especially in non-STL mode)
-# Control formatting (line endings, etc.)
When constructed, the TiXmlPrinter is in its default "pretty printing" mode.
Before calling Accept() you can call methods to control the printing
of the XML document. After TiXmlNode::Accept() is called, the printed document can
be accessed via the CStr(), Str(), and Size() methods.
TiXmlPrinter uses the Visitor API.
@verbatim
TiXmlPrinter printer;
printer.SetIndent("\t");
doc.Accept(&printer);
fprintf(stdout, "%s", printer.CStr());
Constructor & Destructor Documentation
TiXmlPrinter()
TiXmlPrinter ()
Member Function Documentation
VisitEnter() [1/2]
bool VisitEnter (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from TiXmlVisitor.
VisitExit() [1/2]
bool VisitExit (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from TiXmlVisitor.
VisitEnter() [2/2]
bool VisitEnter (const TiXmlElement & , const TiXmlAttribute *) virtual
Visit an element.
Reimplemented from TiXmlVisitor.
References TiXmlText::CDATA(), TiXmlNode::FirstChild(), TiXmlNode::LastChild(), TiXmlAttribute::Next(), TiXmlAttribute::Print(), TiXmlNode::ToText(), and TiXmlNode::Value().
VisitExit() [2/2]
bool VisitExit (const TiXmlElement &) virtual
Visit an element.
Reimplemented from TiXmlVisitor.
References TiXmlNode::FirstChild(), and TiXmlNode::Value().
Visit() [1/4]
bool Visit (const TiXmlDeclaration &) virtual
Visit a declaration.
Reimplemented from TiXmlVisitor.
References TiXmlDeclaration::Print().
Visit() [2/4]
bool Visit (const TiXmlText &) virtual
Visit a text node.
Reimplemented from TiXmlVisitor.
References TiXmlText::CDATA(), TiXmlBase::EncodeString(), TIXML_STRING, TiXmlNode::Value(), and TiXmlNode::ValueTStr().
Visit() [3/4]
bool Visit (const TiXmlComment &) virtual
Visit a comment node.
Reimplemented from TiXmlVisitor.
References TiXmlNode::Value().
Visit() [4/4]
bool Visit (const TiXmlUnknown &) virtual
Visit an unknown node.
Reimplemented from TiXmlVisitor.
References TiXmlNode::Value().
SetIndent()
void SetIndent (const char * _indent)
Set the indent characters for printing.
By default 4 spaces but tab (\t) is also useful, or null/empty string for no indentation.
Indent()
const char* Indent ()
Query the indention string.
SetLineBreak()
void SetLineBreak (const char * _lineBreak)
Set the line breaking string.
By default set to newline (
). Some operating systems prefer other characters, or can be set to the null/empty string for no indenation.
LineBreak()
const char* LineBreak ()
Query the current line breaking string.
SetStreamPrinting()
void SetStreamPrinting ()
Switch over to "stream printing" which is the most dense formatting without linebreaks.
Common when the XML is needed for network transmission.
Referenced by main().
CStr()
const char* CStr ()
Return the result.
Referenced by main().
Size()
size_t Size ()
Return the length of the result string.
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp