sst-plugininfra: TiXmlDocument Class Reference
TiXmlDocument Class Reference
Always the top level node.
Public Member Functions
TiXmlDocument ()
Create an empty document, that has no name.
TiXmlDocument (const char *documentName)
Create a document with a name. The name of the document is also the filename of the xml.
TiXmlDocument (const TiXmlDocument &copy)
TiXmlDocument & operator= (const TiXmlDocument &copy)
virtual ~TiXmlDocument ()
bool LoadFile (TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
bool LoadFile (const char *filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
bool SaveFile (const char *filename) const
Save a file using the given filename. Returns true if successful.
bool LoadFile (FILE *, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
bool SaveFile (FILE *) const
Save a file using the given FILE*. Returns true if successful.
bool LoadFile (const fs::path &filename, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
bool SaveFile (const fs::path &filename) const
virtual const char * Parse (const char *p, TiXmlParsingData *data=0, TiXmlEncoding encoding=TIXML_DEFAULT_ENCODING)
Parse the given null terminated block of xml data.
const TiXmlElement * RootElement () const
Get the root element – the only top level element – of the document.
TiXmlElement * RootElement ()
bool Error () const
If an error occurs, Error will be set to true.
const char * ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
int ErrorId () const
Generally, you probably want the error string (ErrorDesc()).
int ErrorRow () const
Returns the location (if known) of the error.
int ErrorCol () const
The column where the error occured. See ErrorRow()
void SetTabSize (int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
int TabSize () const
void ClearError ()
If you have handled the error, it can be reset with this call.
void Print () const
Write the document to standard out using formatted printing ("pretty print").
virtual void Print (FILE *cfile, int depth=0) const
Print this Document to a FILE stream.
void SetError (int err, const char *errorLocation, TiXmlParsingData *prevData, TiXmlEncoding encoding)
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'. Will be null if none found. The first child of this node with the matching 'value'. Will be null if none found.
TiXmlNode * FirstChild (const char *_value)
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
virtual TiXmlNode * Clone () const
Create an exact duplicate of this node and return it.
Protected Member Functions inherited from TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Additional Inherited Members
Public Types inherited from TiXmlNode
enum NodeType {
TINYXML_DOCUMENT , TINYXML_ELEMENT , TINYXML_COMMENT , TINYXML_UNKNOWN ,
TINYXML_TEXT , TINYXML_DECLARATION , TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0 , TIXML_ERROR , TIXML_ERROR_OPENING_FILE , TIXML_ERROR_PARSING_ELEMENT ,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME , TIXML_ERROR_READING_ELEMENT_VALUE , TIXML_ERROR_READING_ATTRIBUTES , TIXML_ERROR_PARSING_EMPTY ,
TIXML_ERROR_READING_END_TAG , TIXML_ERROR_PARSING_UNKNOWN , TIXML_ERROR_PARSING_COMMENT , TIXML_ERROR_PARSING_DECLARATION ,
TIXML_ERROR_DOCUMENT_EMPTY , TIXML_ERROR_EMBEDDED_NULL , TIXML_ERROR_PARSING_CDATA , TIXML_ERROR_DOCUMENT_TOP_ONLY ,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
Always the top level node.
A document binds together all the XML pieces. It can be saved, loaded, and printed to the screen. The 'value' of a document node is the xml file name.
Constructor & Destructor Documentation
TiXmlDocument() [1/3]
TiXmlDocument ()
Create an empty document, that has no name.
References ClearError().
Referenced by Clone().
TiXmlDocument() [2/3]
TiXmlDocument (const char * documentName)
Create a document with a name. The name of the document is also the filename of the xml.
References ClearError(), and TiXmlNode::value.
TiXmlDocument() [3/3]
TiXmlDocument (const TiXmlDocument & copy)
~TiXmlDocument()
virtual ~TiXmlDocument () virtual
Member Function Documentation
operator=()
TiXmlDocument & operator= (const TiXmlDocument & copy)
References TiXmlNode::Clear().
LoadFile() [1/4]
bool LoadFile (TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the current document value.
Returns true if successful. Will delete any existing document data before loading.
References TiXmlNode::Value().
Referenced by LoadFile(), main(), and KeyMapManager< FUNCS, maxFunc, KEY >::unstreamFromXML().
SaveFile() [1/4]
bool SaveFile () const
Save a file using the current document value. Returns true if successful.
References TiXmlNode::Value().
Referenced by main(), SaveFile(), and KeyMapManager< FUNCS, maxFunc, KEY >::streamToXML().
LoadFile() [2/4]
bool LoadFile (const char * filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given filename. Returns true if successful.
References LoadFile(), SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_STRING, TiXmlFOpen(), and TiXmlNode::value.
SaveFile() [2/4]
bool SaveFile (const char * filename) const
Save a file using the given filename. Returns true if successful.
References SaveFile(), and TiXmlFOpen().
LoadFile() [3/4]
bool LoadFile (FILE * file, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
Load a file using the given FILE*.
Returns true if successful. Note that this method doesn't stream - the entire object pointed at by the FILE* will be interpreted as an XML file. TinyXML doesn't stream in XML from the current file location. Streaming may be added in the future.
References TiXmlCursor::Clear(), TiXmlNode::Clear(), Error(), TiXmlBase::location, Parse(), SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, and TiXmlBase::TIXML_ERROR_OPENING_FILE.
SaveFile() [3/4]
bool SaveFile (FILE * fp) const
Save a file using the given FILE*. Returns true if successful.
References Print(), TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, and TIXML_UTF_LEAD_2.
LoadFile() [4/4]
bool LoadFile (const fs::path & filename, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING)
References TiXmlCursor::Clear(), TiXmlNode::Clear(), Error(), TiXmlBase::location, Parse(), SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_OPENING_FILE, and TiXmlNode::value.
SaveFile() [4/4]
bool SaveFile (const fs::path & filename) const
Parse()
const char * Parse (const char * p, TiXmlParsingData * data = 0, TiXmlEncoding encoding = TIXML_DEFAULT_ENCODING) virtual
Parse the given null terminated block of xml data.
Passing in an encoding to this method (either TIXML_ENCODING_LEGACY or TIXML_ENCODING_UTF8 will force TinyXml to use that encoding, regardless of what TinyXml might otherwise try to detect.
Implements TiXmlBase.
References TiXmlCursor::Clear(), ClearError(), TiXmlCursor::col, TiXmlParsingData::Cursor(), TiXmlDeclaration::Encoding(), TiXmlNode::firstChild, TiXmlNode::Identify(), TiXmlNode::LinkEndChild(), TiXmlBase::location, TiXmlBase::Parse(), TiXmlCursor::row, SetError(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::StringEqual(), TabSize(), TIXML_ENCODING_LEGACY, TIXML_ENCODING_UNKNOWN, TIXML_ENCODING_UTF8, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, and TiXmlNode::ToDeclaration().
Referenced by LoadFile(), and main().
RootElement() [1/2]
const TiXmlElement* RootElement () const
Get the root element – the only top level element – of the document.
In well formed XML, there should only be one. TinyXml is tolerant of multiple elements at the document level.
References TiXmlNode::FirstChildElement().
Referenced by main().
RootElement() [2/2]
TiXmlElement* RootElement ()
References TiXmlNode::FirstChildElement().
Error()
bool Error () const
If an error occurs, Error will be set to true.
Also,
The ErrorId() will contain the integer identifier of the error (not generally useful)
The ErrorDesc() method will return the name of the error. (very useful)
The ErrorRow() and ErrorCol() will return the location of the error (if known)
Referenced by LoadFile(), and main().
ErrorDesc()
const char* ErrorDesc () const
Contains a textual (english) description of the error if one occurs.
Referenced by main().
ErrorId()
int ErrorId () const
Generally, you probably want the error string (ErrorDesc()).
But if you prefer the ErrorId, this function will fetch it.
Referenced by main().
ErrorRow()
int ErrorRow () const
Returns the location (if known) of the error.
The first column is column 1, and the first row is row 1. A value of 0 means the row and column wasn't applicable (memory errors, for example, have no row/column) or the parser lost the error. (An error in the error reporting, in that case.)
See also
SetTabSize, Row, Column
References TiXmlCursor::row.
Referenced by main().
ErrorCol()
int ErrorCol () const
The column where the error occured. See ErrorRow()
References TiXmlCursor::col.
Referenced by main().
SetTabSize()
void SetTabSize (int _tabsize)
SetTabSize() allows the error reporting functions (ErrorRow() and ErrorCol()) to report the correct values for row and column.
It does not change the output or input in any way.
By calling this method, with a tab size greater than 0, the row and column of each node and attribute is stored when the file is loaded. Very useful for tracking the DOM back in to the source file.
The tab size is required for calculating the location of nodes. If not set, the default of 4 is used. The tabsize is set per document. Setting the tabsize to 0 disables row/column tracking.
Note that row and column tracking is not supported when using operator>>.
The tab size needs to be enabled before the parse or load. Correct usage:
    TiXmlDocument doc;
    doc.SetTabSize( 8 );
    doc.Load( "myfile.xml" );
See also
Row, Column
Referenced by main(), and KeyMapManager< FUNCS, maxFunc, KEY >::streamToXML().
TabSize()
int TabSize () const
Referenced by Parse().
ClearError()
void ClearError ()
If you have handled the error, it can be reset with this call.
The error state is automatically cleared if you Parse a new XML block.
References TiXmlCursor::col, and TiXmlCursor::row.
Referenced by main(), Parse(), and TiXmlDocument().
Print() [1/2]
void Print () const
Write the document to standard out using formatted printing ("pretty print").
References Print().
Referenced by main(), Print(), and SaveFile().
Print() [2/2]
void Print (FILE * cfile, int depth = 0) const virtual
Print this Document to a FILE stream.
Implements TiXmlBase.
References TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), and TiXmlBase::Print().
SetError()
void SetError (int err, const char * errorLocation, TiXmlParsingData * prevData, TiXmlEncoding encoding)
References TiXmlCursor::Clear(), TiXmlParsingData::Cursor(), TiXmlBase::errorString, TiXmlParsingData::Stamp(), and TiXmlBase::TIXML_ERROR_STRING_COUNT.
Referenced by TiXmlNode::InsertAfterChild(), TiXmlNode::InsertBeforeChild(), TiXmlNode::InsertEndChild(), TiXmlNode::LinkEndChild(), LoadFile(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), Parse(), TiXmlElement::ReadValue(), and TiXmlNode::ReplaceChild().
ToDocument() [1/2]
virtual const TiXmlDocument* ToDocument () const virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
ToDocument() [2/2]
virtual TiXmlDocument* ToDocument () virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from TiXmlNode.
Accept()
bool Accept (TiXmlVisitor * content) const virtual
Walk the XML tree visiting this node and all of its children.
Implements TiXmlNode.
References TiXmlNode::Accept(), TiXmlNode::FirstChild(), TiXmlNode::NextSibling(), TiXmlVisitor::VisitEnter(), and TiXmlVisitor::VisitExit().
Referenced by main().
Clone()
TiXmlNode * Clone () const protected virtual
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implements TiXmlNode.
References TiXmlDocument().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp
tinyxmlparser.cpp