sst-plugininfra: TiXmlVisitor Class Reference
TiXmlVisitor Class Reference
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
Public Member Functions
virtual ~TiXmlVisitor ()
virtual bool VisitEnter (const TiXmlDocument &)
Visit a document.
virtual bool VisitExit (const TiXmlDocument &)
Visit a document.
virtual bool VisitEnter (const TiXmlElement &, const TiXmlAttribute *)
Visit an element.
virtual bool VisitExit (const TiXmlElement &)
Visit an element.
virtual bool Visit (const TiXmlDeclaration &)
Visit a declaration.
virtual bool Visit (const TiXmlText &)
Visit a text node.
virtual bool Visit (const TiXmlComment &)
Visit a comment node.
virtual bool Visit (const TiXmlUnknown &)
Visit an unknown node.
Detailed Description
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a TiXmlVisitor class to handle callbacks.
For nodes that contain other nodes (Document, Element) you will get called with a VisitEnter/VisitExit pair. Nodes that are always leaves are simply called with Visit().
If you return 'true' from a Visit method, recursive parsing will continue. If you return false, no children of this node or its sibilings will be Visited.
All flavors of Visit methods have a default implementation that returns 'true' (continue visiting). You need to only override methods that are interesting to you.
Generally Accept() is called on the TiXmlDocument, although all nodes suppert Visiting.
You should never change the document from a callback.
See also
TiXmlNode::Accept()
Constructor & Destructor Documentation
~TiXmlVisitor()
virtual ~TiXmlVisitor () virtual
Member Function Documentation
VisitEnter() [1/2]
virtual bool VisitEnter (const TiXmlDocument &) virtual
Visit a document.
Reimplemented in TiXmlPrinter.
Referenced by TiXmlDocument::Accept(), and TiXmlElement::Accept().
VisitExit() [1/2]
virtual bool VisitExit (const TiXmlDocument &) virtual
Visit a document.
Reimplemented in TiXmlPrinter.
Referenced by TiXmlDocument::Accept(), and TiXmlElement::Accept().
VisitEnter() [2/2]
virtual bool VisitEnter (const TiXmlElement & , const TiXmlAttribute *) virtual
Visit an element.
Reimplemented in TiXmlPrinter.
VisitExit() [2/2]
virtual bool VisitExit (const TiXmlElement &) virtual
Visit an element.
Reimplemented in TiXmlPrinter.
Visit() [1/4]
virtual bool Visit (const TiXmlDeclaration &) virtual
Visit a declaration.
Reimplemented in TiXmlPrinter.
Referenced by TiXmlText::Accept(), TiXmlUnknown::Accept(), TiXmlComment::Accept(), and TiXmlDeclaration::Accept().
Visit() [2/4]
virtual bool Visit (const TiXmlText &) virtual
Visit a text node.
Reimplemented in TiXmlPrinter.
Visit() [3/4]
virtual bool Visit (const TiXmlComment &) virtual
Visit a comment node.
Reimplemented in TiXmlPrinter.
Visit() [4/4]
virtual bool Visit (const TiXmlUnknown &) virtual
Visit an unknown node.
Reimplemented in TiXmlPrinter.
The documentation for this class was generated from the following file:
tinyxml.h