sst-plugininfra: TiXmlString Class Reference
TiXmlString Class Reference
Public Types
typedef size_t size_type
Public Member Functions
TiXmlString ()
TiXmlString (const TiXmlString &copy)
TIXML_EXPLICIT TiXmlString (const char *copy)
TIXML_EXPLICIT TiXmlString (const char *str, size_type len)
~TiXmlString ()
TiXmlString & operator= (const char *copy)
TiXmlString & operator= (const TiXmlString &copy)
TiXmlString & operator+= (const char *suffix)
TiXmlString & operator+= (char single)
TiXmlString & operator+= (const TiXmlString &suffix)
const char * c_str () const
const char * data () const
size_type length () const
size_type size () const
bool empty () const
size_type capacity () const
const char & at (size_type index) const
char & operator[] (size_type index) const
size_type find (char lookup) const
size_type find (char tofind, size_type offset) const
void clear ()
void reserve (size_type cap)
TiXmlString & assign (const char *str, size_type len)
TiXmlString & append (const char *str, size_type len)
void swap (TiXmlString &other)
Static Public Attributes
static const size_type npos = static_cast< TiXmlString::size_type >(-1)
Member Typedef Documentation
size_type
typedef size_t size_type
Constructor & Destructor Documentation
TiXmlString() [1/4]
TiXmlString ()
TiXmlString() [2/4]
TiXmlString (const TiXmlString & copy)
References data(), and length().
TiXmlString() [3/4]
TIXML_EXPLICIT TiXmlString (const char * copy)
References length().
TiXmlString() [4/4]
TIXML_EXPLICIT TiXmlString (const char * str, size_type len)
~TiXmlString()
~TiXmlString ()
Member Function Documentation
operator=() [1/2]
TiXmlString& operator= (const char * copy)
References assign().
operator=() [2/2]
TiXmlString& operator= (const TiXmlString & copy)
References assign(), and length().
operator+=() [1/3]
TiXmlString& operator+= (const char * suffix)
References append().
operator+=() [2/3]
TiXmlString& operator+= (char single)
References append().
operator+=() [3/3]
TiXmlString& operator+= (const TiXmlString & suffix)
References append(), data(), and length().
c_str()
const char* c_str () const
Referenced by find(), main(), operator<(), and operator==().
data()
const char* data () const
Referenced by operator+=(), reserve(), and TiXmlString().
length()
size_type length () const
Referenced by append(), at(), find(), operator+(), operator+=(), operator=(), operator==(), operator[](), reserve(), and TiXmlString().
size()
size_type size () const
empty()
bool empty () const
capacity()
size_type capacity () const
Referenced by append(), assign(), and reserve().
at()
const char& at (size_type index) const
References length().
operator[]()
char& operator[] (size_type index) const
References length().
find() [1/2]
size_type find (char lookup) const
find() [2/2]
size_type find (char tofind, size_type offset) const
References c_str(), length(), and npos.
clear()
void clear ()
reserve()
void reserve (size_type cap)
References capacity(), data(), length(), and swap().
Referenced by append(), and operator+().
assign()
TiXmlString & assign (const char * str, size_type len)
References capacity(), and swap().
Referenced by operator=().
append()
TiXmlString & append (const char * str, size_type len)
References capacity(), length(), and reserve().
Referenced by operator+(), and operator+=().
swap()
void swap (TiXmlString & other)
Referenced by assign(), and reserve().
Member Data Documentation
npos
const TiXmlString::size_type npos = static_cast< TiXmlString::size_type >(-1) static
Referenced by find().
The documentation for this class was generated from the following files:
tinystr.h
tinystr.cpp