sst-plugininfra: TiXmlParsingData Class Reference
TiXmlParsingData Class Reference
Public Member Functions
void Stamp (const char *now, TiXmlEncoding encoding)
const TiXmlCursor & Cursor () const
Member Function Documentation
Stamp()
void Stamp (const char * now, TiXmlEncoding encoding)
References TiXmlCursor::col, TiXmlCursor::row, TIXML_ENCODING_UTF8, TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, and TiXmlBase::utf8ByteTable.
Referenced by TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), and TiXmlDocument::SetError().
Cursor()
const TiXmlCursor& Cursor () const
Referenced by TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlDocument::Parse(), and TiXmlDocument::SetError().
The documentation for this class was generated from the following file:
tinyxmlparser.cpp