sst-plugininfra: TiXmlNode Class Reference
TiXmlNode Class Reference abstract
The parent class for everything in the Document Object Model.
Public Types
enum NodeType {
TINYXML_DOCUMENT , TINYXML_ELEMENT , TINYXML_COMMENT , TINYXML_UNKNOWN ,
TINYXML_TEXT , TINYXML_DECLARATION , TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from TiXmlBase
enum {
TIXML_NO_ERROR = 0 , TIXML_ERROR , TIXML_ERROR_OPENING_FILE , TIXML_ERROR_PARSING_ELEMENT ,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME , TIXML_ERROR_READING_ELEMENT_VALUE , TIXML_ERROR_READING_ATTRIBUTES , TIXML_ERROR_PARSING_EMPTY ,
TIXML_ERROR_READING_END_TAG , TIXML_ERROR_PARSING_UNKNOWN , TIXML_ERROR_PARSING_COMMENT , TIXML_ERROR_PARSING_DECLARATION ,
TIXML_ERROR_DOCUMENT_EMPTY , TIXML_ERROR_EMBEDDED_NULL , TIXML_ERROR_PARSING_CDATA , TIXML_ERROR_DOCUMENT_TOP_ONLY ,
TIXML_ERROR_STRING_COUNT
}
Public Member Functions
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'. Will be null if none found. The first child of this node with the matching 'value'. Will be null if none found.
TiXmlNode * FirstChild (const char *_value)
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlNode * Clone () const =0
Create an exact duplicate of this node and return it.
virtual bool Accept (TiXmlVisitor *visitor) const =0
Accept a hierchical visit the nodes in the TinyXML DOM.
Public Member Functions inherited from TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
virtual void Print (FILE *cfile, int depth) const =0
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)=0
Protected Member Functions
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Protected Attributes
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Additional Inherited Members
Static Public Member Functions inherited from TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Static Protected Attributes inherited from TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
The parent class for everything in the Document Object Model.
(Except for attributes). Nodes have siblings, a parent, and children. A node can be in a document, or stand on its own. The type of a TiXmlNode can be queried, and it can be cast to its more defined type.
Member Enumeration Documentation
NodeType
enum NodeType
The types of XML nodes supported by TinyXml.
(All the unsupported types are picked up by UNKNOWN.)
Enumerator
TINYXML_DOCUMENT
TINYXML_ELEMENT
TINYXML_COMMENT
TINYXML_UNKNOWN
TINYXML_TEXT
TINYXML_DECLARATION
TINYXML_TYPECOUNT
Constructor & Destructor Documentation
~TiXmlNode()
~TiXmlNode () virtual
References firstChild, and next.
TiXmlNode()
TiXmlNode (NodeType _type) protected
References firstChild, lastChild, next, parent, prev, and type.
Member Function Documentation
Value()
const char* Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
    Document:   filename of the xml file
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:       the text string
The subclasses will wrap this function.
References value.
Referenced by TiXmlElement::Clone(), FirstChild(), TiXmlElement::GetText(), LastChild(), TiXmlDocument::LoadFile(), main(), NextSibling(), PreviousSibling(), TiXmlDocument::SaveFile(), TiXmlPrinter::Visit(), TiXmlPrinter::VisitEnter(), and TiXmlPrinter::VisitExit().
ValueTStr()
const TIXML_STRING& ValueTStr () const
References value.
Referenced by TiXmlPrinter::Visit().
SetValue()
void SetValue (const char * _value)
Changes the value of the node.
Defined as:
    Document:   filename of the xml file
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:       the text string
References value.
Referenced by CopyTo(), TiXmlComment::TiXmlComment(), and TiXmlText::TiXmlText().
Clear()
void Clear ()
Delete all the children of this node. Does not affect 'this'.
References firstChild, lastChild, and next.
Referenced by TiXmlElement::ClearThis(), TiXmlDocument::LoadFile(), main(), TiXmlComment::operator=(), TiXmlDeclaration::operator=(), and TiXmlDocument::operator=().
Parent() [1/2]
TiXmlNode* Parent ()
One step up the DOM.
References parent.
Parent() [2/2]
const TiXmlNode* Parent () const
References parent.
FirstChild() [1/4]
const TiXmlNode* FirstChild () const
The first child of this node. Will be null if there are no children.
References firstChild.
Referenced by TiXmlDocument::Accept(), TiXmlElement::Accept(), TiXmlHandle::Child(), TiXmlHandle::FirstChild(), FirstChildElement(), TiXmlElement::GetText(), IterateChildren(), main(), TiXmlDocument::Print(), TiXmlPrinter::VisitEnter(), and TiXmlPrinter::VisitExit().
FirstChild() [2/4]
TiXmlNode* FirstChild ()
References firstChild.
FirstChild() [3/4]
const TiXmlNode * FirstChild (const char * value) const
The first child of this node with the matching 'value'. Will be null if none found. The first child of this node with the matching 'value'. Will be null if none found.
References firstChild, next, and Value().
FirstChild() [4/4]
TiXmlNode* FirstChild (const char * _value)
LastChild() [1/4]
const TiXmlNode* LastChild () const
References lastChild.
Referenced by main(), and TiXmlPrinter::VisitEnter().
LastChild() [2/4]
TiXmlNode* LastChild ()
The last child of this node. Will be null if there are no children.
References lastChild.
LastChild() [3/4]
const TiXmlNode * LastChild (const char * value) const
References lastChild, prev, and Value().
LastChild() [4/4]
TiXmlNode* LastChild (const char * _value)
The last child of this node matching 'value'. Will be null if there are no children.
IterateChildren() [1/4]
const TiXmlNode * IterateChildren (const TiXmlNode * previous) const
An alternate way to walk the children of a node.
One way to iterate over nodes is:
            for( child = parent->FirstChild(); child; child = child->NextSibling() )
IterateChildren does the same thing with the syntax:
            child = 0;
            while( child = parent->IterateChildren( child ) )
IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
References FirstChild(), NextSibling(), and parent.
Referenced by main().
IterateChildren() [2/4]
TiXmlNode* IterateChildren (const TiXmlNode * previous)
IterateChildren() [3/4]
const TiXmlNode * IterateChildren (const char * value, const TiXmlNode * previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
References FirstChild(), NextSibling(), and parent.
IterateChildren() [4/4]
TiXmlNode* IterateChildren (const char * _value, const TiXmlNode * previous)
InsertEndChild()
TiXmlNode * InsertEndChild (const TiXmlNode & addThis)
Add a new node related to this.
Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
References Clone(), GetDocument(), LinkEndChild(), TiXmlDocument::SetError(), TINYXML_DOCUMENT, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by main(), and KeyMapManager< FUNCS, maxFunc, KEY >::streamToXML().
LinkEndChild()
TiXmlNode * LinkEndChild (TiXmlNode * addThis)
Add a new node related to this.
Adds a child past the LastChild.
NOTE: the node to be added is passed by pointer, and will be
henceforth owned (and deleted) by tinyXml. This method is efficient
and avoids an extra copy, but should be used with care as it
uses a different memory model than the other insert functions.
@sa InsertEndChild
References firstChild, GetDocument(), lastChild, next, parent, prev, TiXmlDocument::SetError(), TINYXML_DOCUMENT, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by TiXmlElement::CopyTo(), InsertEndChild(), TiXmlDocument::Parse(), and TiXmlElement::ReadValue().
InsertBeforeChild()
TiXmlNode * InsertBeforeChild (TiXmlNode * beforeThis, const TiXmlNode & addThis)
Add a new node related to this.
Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone(), firstChild, GetDocument(), next, parent, prev, TiXmlDocument::SetError(), TINYXML_DOCUMENT, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by main().
InsertAfterChild()
TiXmlNode * InsertAfterChild (TiXmlNode * afterThis, const TiXmlNode & addThis)
Add a new node related to this.
Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
References Clone(), GetDocument(), lastChild, next, parent, prev, TiXmlDocument::SetError(), TINYXML_DOCUMENT, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by main().
ReplaceChild()
TiXmlNode * ReplaceChild (TiXmlNode * replaceThis, const TiXmlNode & withThis)
Replace a child of this node.
Returns a pointer to the new object or NULL if an error occured.
References Clone(), firstChild, GetDocument(), lastChild, next, parent, prev, TiXmlDocument::SetError(), TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and ToDocument().
RemoveChild()
bool RemoveChild (TiXmlNode * removeThis)
Delete a child of this node.
References firstChild, lastChild, next, parent, and prev.
Referenced by main().
PreviousSibling() [1/4]
const TiXmlNode* PreviousSibling () const
Navigate to a sibling node.
References prev.
Referenced by main().
PreviousSibling() [2/4]
TiXmlNode* PreviousSibling ()
References prev.
PreviousSibling() [3/4]
const TiXmlNode * PreviousSibling (const char * _value) const
Navigate to a sibling node.
References prev, and Value().
PreviousSibling() [4/4]
TiXmlNode* PreviousSibling (const char * _prev)
NextSibling() [1/4]
const TiXmlNode* NextSibling () const
Navigate to a sibling node.
References next.
Referenced by TiXmlDocument::Accept(), TiXmlElement::Accept(), TiXmlHandle::Child(), TiXmlElement::CopyTo(), FirstChildElement(), IterateChildren(), main(), NextSiblingElement(), TiXmlElement::Print(), and TiXmlDocument::Print().
NextSibling() [2/4]
TiXmlNode* NextSibling ()
References next.
NextSibling() [3/4]
const TiXmlNode * NextSibling (const char * _value) const
Navigate to a sibling node with the given 'value'.
References next, and Value().
NextSibling() [4/4]
TiXmlNode* NextSibling (const char * _next)
NextSiblingElement() [1/4]
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling(), and ToElement().
Referenced by TiXmlHandle::ChildElement(), and main().
NextSiblingElement() [2/4]
TiXmlElement* NextSiblingElement ()
NextSiblingElement() [3/4]
const TiXmlElement * NextSiblingElement (const char * _value) const
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
References NextSibling(), and ToElement().
NextSiblingElement() [4/4]
TiXmlElement* NextSiblingElement (const char * _next)
FirstChildElement() [1/4]
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
References FirstChild(), NextSibling(), and ToElement().
Referenced by TiXmlHandle::ChildElement(), TiXmlHandle::FirstChildElement(), main(), TiXmlDocument::RootElement(), and KeyMapManager< FUNCS, maxFunc, KEY >::unstreamFromXML().
FirstChildElement() [2/4]
TiXmlElement* FirstChildElement ()
FirstChildElement() [3/4]
const TiXmlElement * FirstChildElement (const char * _value) const
Convenience function to get through elements.
References FirstChild(), NextSibling(), and ToElement().
FirstChildElement() [4/4]
TiXmlElement* FirstChildElement (const char * _value)
Type()
int Type () const
Query the type (as an enumerated value, above) of this node.
The possible types are: TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN, TINYXML_TEXT, and TINYXML_DECLARATION.
References type.
Referenced by InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and LinkEndChild().
GetDocument() [1/2]
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
Returns null if not in a document.
References parent, and ToDocument().
Referenced by InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), LinkEndChild(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlElement::ReadValue(), and ReplaceChild().
GetDocument() [2/2]
TiXmlDocument* GetDocument ()
NoChildren()
bool NoChildren () const
Returns true if this node has no children.
References firstChild.
ToDocument() [1/2]
virtual const TiXmlDocument* ToDocument () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDocument.
Referenced by GetDocument(), and ReplaceChild().
ToElement() [1/2]
virtual const TiXmlElement* ToElement () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlElement.
Referenced by FirstChildElement(), main(), and NextSiblingElement().
ToComment() [1/2]
virtual const TiXmlComment* ToComment () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlComment.
Referenced by main().
ToUnknown() [1/2]
virtual const TiXmlUnknown* ToUnknown () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlUnknown.
ToText() [1/2]
virtual const TiXmlText* ToText () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlText.
Referenced by TiXmlElement::GetText(), main(), TiXmlElement::Print(), and TiXmlPrinter::VisitEnter().
ToDeclaration() [1/2]
virtual const TiXmlDeclaration* ToDeclaration () const virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDeclaration.
Referenced by main(), and TiXmlDocument::Parse().
ToDocument() [2/2]
virtual TiXmlDocument* ToDocument () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDocument.
ToElement() [2/2]
virtual TiXmlElement* ToElement () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlElement.
ToComment() [2/2]
virtual TiXmlComment* ToComment () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlComment.
ToUnknown() [2/2]
virtual TiXmlUnknown* ToUnknown () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlUnknown.
ToText() [2/2]
virtual TiXmlText* ToText () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlText.
ToDeclaration() [2/2]
virtual TiXmlDeclaration* ToDeclaration () virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in TiXmlDeclaration.
Clone()
virtual TiXmlNode* Clone () const pure virtual
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implemented in TiXmlDocument, TiXmlUnknown, TiXmlDeclaration, TiXmlText, TiXmlComment, and TiXmlElement.
Referenced by TiXmlElement::CopyTo(), InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and ReplaceChild().
Accept()
virtual bool Accept (TiXmlVisitor * visitor) const pure virtual
Accept a hierchical visit the nodes in the TinyXML DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implemented in TiXmlDeclaration, TiXmlComment, TiXmlElement, TiXmlDocument, TiXmlUnknown, and TiXmlText.
Referenced by TiXmlDocument::Accept().
CopyTo()
void CopyTo (TiXmlNode * target) const protected
References TiXmlBase::location, SetValue(), TiXmlBase::userData, and value.
Referenced by TiXmlComment::CopyTo(), TiXmlDeclaration::CopyTo(), TiXmlElement::CopyTo(), TiXmlText::CopyTo(), and TiXmlUnknown::CopyTo().
Identify()
TiXmlNode * Identify (const char * start, TiXmlEncoding encoding) protected
References TiXmlBase::IsAlpha(), parent, TiXmlText::SetCDATA(), TiXmlBase::SkipWhiteSpace(), TiXmlBase::StringEqual(), and TiXmlElement.
Referenced by TiXmlDocument::Parse(), and TiXmlElement::ReadValue().
Member Data Documentation
parent
TiXmlNode* parent protected
Referenced by GetDocument(), Identify(), InsertAfterChild(), InsertBeforeChild(), IterateChildren(), LinkEndChild(), Parent(), RemoveChild(), ReplaceChild(), and TiXmlNode().
type
NodeType type protected
Referenced by TiXmlNode(), and Type().
firstChild
TiXmlNode* firstChild protected
Referenced by Clear(), TiXmlElement::CopyTo(), FirstChild(), InsertBeforeChild(), LinkEndChild(), NoChildren(), TiXmlDocument::Parse(), TiXmlElement::Print(), RemoveChild(), ReplaceChild(), TiXmlElement::TiXmlElement(), TiXmlNode(), and ~TiXmlNode().
lastChild
TiXmlNode* lastChild protected
Referenced by Clear(), InsertAfterChild(), LastChild(), LinkEndChild(), TiXmlElement::Print(), RemoveChild(), ReplaceChild(), TiXmlElement::TiXmlElement(), and TiXmlNode().
value
TIXML_STRING value protected
Referenced by TiXmlText::Blank(), CopyTo(), TiXmlDocument::LoadFile(), TiXmlAttribute::Parse(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlText::Parse(), TiXmlUnknown::Parse(), TiXmlElement::Print(), TiXmlComment::Print(), TiXmlText::Print(), TiXmlUnknown::Print(), TiXmlElement::QueryUnsignedAttribute(), SetValue(), TiXmlDocument::TiXmlDocument(), TiXmlElement::TiXmlElement(), Value(), and ValueTStr().
prev
TiXmlNode* prev protected
Referenced by InsertAfterChild(), InsertBeforeChild(), LastChild(), LinkEndChild(), PreviousSibling(), RemoveChild(), ReplaceChild(), and TiXmlNode().
next
TiXmlNode* next protected
Referenced by Clear(), TiXmlAttributeSet::Find(), FirstChild(), InsertAfterChild(), InsertBeforeChild(), LinkEndChild(), NextSibling(), RemoveChild(), ReplaceChild(), TiXmlNode(), and ~TiXmlNode().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cpp
tinyxmlparser.cpp