sst-plugininfra: sst::plugininfra::paths Namespace Reference
sst::plugininfra::paths Namespace Reference
Functions
fs::path homePath ()
fs::path sharedLibraryBinaryPath ()
fs::path lookupXdgUserPathWithStream (const char *xdgDirId, std::istream &stream)
fs::path lookupXdgUserPath (const char *xdgDirId)
fs::path bestDocumentsFolderPathFor (const std::string &productName)
fs::path bestLibrarySharedFolderPathFor (const std::string &productName, bool userLevel)
fs::path knownFolderPath (REFKNOWNFOLDERID rfid, const std::string &idealName)
Variables
std::string CMAKE_INSTALL_PREFIX
Function Documentation
homePath()
fs::path homePath ()
Referenced by bestDocumentsFolderPathFor(), bestLibrarySharedFolderPathFor(), lookupXdgUserPath(), and lookupXdgUserPathWithStream().
sharedLibraryBinaryPath()
fs::path sharedLibraryBinaryPath ()
lookupXdgUserPathWithStream()
fs::path sst::plugininfra::paths::lookupXdgUserPathWithStream (const char * xdgDirId, std::istream & stream)
References homePath().
Referenced by lookupXdgUserPath().
lookupXdgUserPath()
fs::path sst::plugininfra::paths::lookupXdgUserPath (const char * xdgDirId)
References homePath(), and lookupXdgUserPathWithStream().
Referenced by bestDocumentsFolderPathFor().
bestDocumentsFolderPathFor()
fs::path bestDocumentsFolderPathFor (const std::string & productName)
References homePath(), and lookupXdgUserPath().
bestLibrarySharedFolderPathFor()
fs::path bestLibrarySharedFolderPathFor (const std::string & productName, bool userLevel)
References CMAKE_INSTALL_PREFIX, and homePath().
knownFolderPath()
fs::path sst::plugininfra::paths::knownFolderPath (REFKNOWNFOLDERID rfid, const std::string & idealName)
Variable Documentation
CMAKE_INSTALL_PREFIX
std::string CMAKE_INSTALL_PREFIX extern
Referenced by bestLibrarySharedFolderPathFor().