sst-plugininfra: Provider< E, maxE > Struct Template Reference
Provider< E, maxE > Struct Template Reference
#include <userdefaults.h>
Public Member Functions
Provider (const fs::path &defaultsDirectory, const std::string &productName, const std::function< std::string(E)> &e2S, const std::function< void(const std::string &, const std::string &)> &errHandle)
std::string getUserDefaultValue (const E &key, const std::string &valueIfMissing, bool potentiallyRead=true)
int getUserDefaultValue (const E &key, int valueIfMissing, bool potentiallyRead=true)
std::pair< int, int > getUserDefaultValue (const E &key, const std::pair< int, int > &valueIfMissing, bool potentiallyRead=true)
fs::path getUserDefaultPath (const E &key, const fs::path &valueIfMissing)
bool updateUserDefaultValue (const E &key, const std::string &value)
bool updateUserDefaultValue (const E &key, const int value)
bool updateUserDefaultValue (const E &key, const std::pair< int, int > &value)
bool updateUserDefaultPath (const E &key, const fs::path &path)
void addOverride (E key, const std::string &s)
void addOverride (E key, int i)
void clearOverride (E key)
Constructor & Destructor Documentation
Provider()
template<typename E , int maxE> Provider (const fs::path & defaultsDirectory, const std::string & productName, const std::function< std::string(E)> & e2S, const std::function< void(const std::string &, const std::string &)> & errHandle)
Member Function Documentation
getUserDefaultValue() [1/3]
template<typename E , int maxE> std::string getUserDefaultValue (const E & key, const std::string & valueIfMissing, bool potentiallyRead = true)
Referenced by Provider< E, maxE >::getUserDefaultPath().
getUserDefaultValue() [2/3]
template<typename E , int maxE> int getUserDefaultValue (const E & key, int valueIfMissing, bool potentiallyRead = true)
getUserDefaultValue() [3/3]
template<typename E , int maxE> std::pair< int, int > getUserDefaultValue (const E & key, const std::pair< int, int > & valueIfMissing, bool potentiallyRead = true)
getUserDefaultPath()
template<typename E , int maxE> fs::path getUserDefaultPath (const E & key, const fs::path & valueIfMissing)
References Provider< E, maxE >::getUserDefaultValue().
updateUserDefaultValue() [1/3]
template<typename E , int maxE> bool updateUserDefaultValue (const E & key, const std::string & value)
Referenced by Provider< E, maxE >::updateUserDefaultPath().
updateUserDefaultValue() [2/3]
template<typename E , int maxE> bool updateUserDefaultValue (const E & key, const int value)
updateUserDefaultValue() [3/3]
template<typename E , int maxE> bool updateUserDefaultValue (const E & key, const std::pair< int, int > & value)
updateUserDefaultPath()
template<typename E , int maxE> bool updateUserDefaultPath (const E & key, const fs::path & path)
References Provider< E, maxE >::updateUserDefaultValue().
addOverride() [1/2]
template<typename E , int maxE> void addOverride (E key, const std::string & s)
addOverride() [2/2]
template<typename E , int maxE> void addOverride (E key, int i)
clearOverride()
template<typename E , int maxE> void clearOverride (E key)
The documentation for this struct was generated from the following file:
userdefaults.h