sst-plugininfra: xmltest.cpp File Reference
xmltest.cpp File Reference
Functions
bool XmlTest (const char *testString, const char *expected, const char *found, bool noEcho=false)
bool XmlTest (const char *testString, int expected, int found, bool noEcho=false)
void NullLineEndings (char *p)
int main ()
Function Documentation
XmlTest() [1/2]
bool XmlTest (const char * testString, const char * expected, const char * found, bool noEcho = false)
Referenced by main().
XmlTest() [2/2]
bool XmlTest (const char * testString, int expected, int found, bool noEcho = false)
NullLineEndings()
void NullLineEndings (char * p)
Referenced by main().
main()
int main ()
References TiXmlDocument::Accept(), TiXmlElement::Attribute(), TiXmlString::c_str(), TiXmlHandle::Child(), TiXmlHandle::ChildElement(), TiXmlNode::Clear(), TiXmlDocument::ClearError(), TiXmlBase::Column(), Catch::cout(), TiXmlPrinter::CStr(), TiXmlHandle::Element(), TiXmlDeclaration::Encoding(), TiXmlDocument::Error(), TiXmlDocument::ErrorCol(), TiXmlDocument::ErrorDesc(), TiXmlDocument::ErrorId(), TiXmlDocument::ErrorRow(), TiXmlElement::FirstAttribute(), TiXmlNode::FirstChild(), TiXmlHandle::FirstChild(), TiXmlNode::FirstChildElement(), TiXmlHandle::FirstChildElement(), TiXmlElement::GetText(), TiXmlNode::InsertAfterChild(), TiXmlNode::InsertBeforeChild(), TiXmlNode::InsertEndChild(), TiXmlNode::IterateChildren(), TiXmlNode::LastChild(), TiXmlDocument::LoadFile(), TiXmlNode::NextSibling(), TiXmlNode::NextSiblingElement(), TiXmlHandle::Node(), NullLineEndings(), TiXmlElement::Parse(), TiXmlComment::Parse(), TiXmlDeclaration::Parse(), TiXmlUnknown::Parse(), TiXmlDocument::Parse(), TiXmlNode::PreviousSibling(), TiXmlDocument::Print(), TiXmlElement::Print(), TiXmlElement::QueryDoubleAttribute(), TiXmlElement::QueryIntAttribute(), TiXmlNode::RemoveChild(), TiXmlDocument::RootElement(), TiXmlBase::Row(), TiXmlDocument::SaveFile(), TiXmlElement::SetAttribute(), TiXmlBase::SetCondenseWhiteSpace(), TiXmlElement::SetDoubleAttribute(), TiXmlPrinter::SetStreamPrinting(), TiXmlDocument::SetTabSize(), TiXmlHandle::Text(), TIXML_ENCODING_LEGACY, TIXML_ENCODING_UNKNOWN, TiXmlBase::TIXML_ERROR_DOCUMENT_EMPTY, TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, TiXmlBase::TIXML_ERROR_OPENING_FILE, TIXML_NO_ATTRIBUTE, TIXML_STRING, TIXML_SUCCESS, TIXML_WRONG_TYPE, TiXmlNode::ToComment(), TiXmlNode::ToDeclaration(), TiXmlNode::ToElement(), TiXmlNode::ToText(), TiXmlHandle::Unknown(), TiXmlNode::Value(), and XmlTest().