sst-waveshapers: ExprLhs< LhsT > Class Template Reference
ExprLhs< LhsT > Class Template Reference
Public Member Functions
ExprLhs (LhsT lhs)
template<typename RhsT >
auto operator== (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto operator== (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator!= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
auto operator!= (bool rhs) -> BinaryExpr< LhsT, bool > const
template<typename RhsT >
auto operator> (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator< (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator>= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator<= (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator| (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator& (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator^ (RhsT const &rhs) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator&& (RhsT const &) -> BinaryExpr< LhsT, RhsT const & > const
template<typename RhsT >
auto operator|| (RhsT const &) -> BinaryExpr< LhsT, RhsT const & > const
auto makeUnaryExpr () const -> UnaryExpr< LhsT >
Constructor & Destructor Documentation
ExprLhs()
ExprLhs (LhsT lhs) explicit
Member Function Documentation
operator==() [1/2]
auto operator== (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
References Catch::compareEqual().
operator==() [2/2]
auto operator== (bool rhs) -> BinaryExpr<LhsT, bool> const
operator!=() [1/2]
auto operator!= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
References Catch::compareNotEqual().
operator!=() [2/2]
auto operator!= (bool rhs) -> BinaryExpr<LhsT, bool> const
operator>()
auto operator> (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator<()
auto operator< (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator>=()
auto operator>= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator<=()
auto operator<= (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator|()
auto operator| (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator&()
auto operator& (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator^()
auto operator^ (RhsT const & rhs) -> BinaryExpr<LhsT, RhsT const&> const
operator&&()
auto operator&& (RhsT const &) -> BinaryExpr<LhsT, RhsT const&> const
operator||()
auto operator|| (RhsT const &) -> BinaryExpr<LhsT, RhsT const&> const
makeUnaryExpr()
auto makeUnaryExpr () const -> UnaryExpr<LhsT>
Referenced by AssertionHandler::handleExpr(), and Catch::handleExpression().
The documentation for this class was generated from the following file:
catch2.hpp