sst-waveshapers: Capturer Class Reference
Capturer Class Reference
Public Member Functions
Capturer (StringRef macroName, SourceLineInfo const &lineInfo, ResultWas::OfType resultType, StringRef names)
~Capturer ()
void captureValue (size_t index, std::string const &value)
template<typename T >
void captureValues (size_t index, T const &value)
template<typename T , typename... Ts>
void captureValues (size_t index, T const &value, Ts const &... values)
Constructor & Destructor Documentation
Capturer()
Capturer (StringRef macroName, SourceLineInfo const & lineInfo, ResultWas::OfType resultType, StringRef names)
~Capturer()
~Capturer ()
Member Function Documentation
captureValue()
void captureValue (size_t index, std::string const & value)
captureValues() [1/2]
void captureValues (size_t index, T const & value)
References Catch::Detail::stringify(), and Catch::Generators::value().
captureValues() [2/2]
void captureValues (size_t index, T const & value, Ts const &... values)
References Catch::Detail::stringify(), Catch::Generators::value(), and Catch::Generators::values().
The documentation for this class was generated from the following file:
catch2.hpp