sst-waveshapers: WaveshaperTables Struct Reference
WaveshaperTables Struct Reference
Lookup table for waveshapers.
#include <WaveshaperTables.h>
Public Member Functions
WaveshaperTables ()
Static Public Member Functions
static double shafted_tanh (double x)
Public Attributes
float waveshapers [static_cast< int >(WaveshaperType::n_ws_types)][tableSize]
Static Public Attributes
static constexpr int tableSize = 1024
Detailed Description
Lookup table for waveshapers.
Constructor & Destructor Documentation
WaveshaperTables()
WaveshaperTables ()
References sst::waveshapers::dcBlock(), WaveshaperTables::shafted_tanh(), WaveshaperTables::tableSize, WaveshaperTables::waveshapers, sst::waveshapers::wst_asym, sst::waveshapers::wst_digital, sst::waveshapers::wst_hard, sst::waveshapers::wst_sine, and sst::waveshapers::wst_soft.
Member Function Documentation
shafted_tanh()
static double shafted_tanh (double x) static
References sst::waveshapers::dcBlock().
Referenced by WaveshaperTables::WaveshaperTables().
Member Data Documentation
tableSize
constexpr int tableSize = 1024 static constexpr
Referenced by WaveshaperTables::WaveshaperTables().
waveshapers
float waveshapers[static_cast< int >(WaveshaperType::n_ws_types)][tableSize]
Referenced by WaveshaperTables::WaveshaperTables().
The documentation for this struct was generated from the following file:
WaveshaperTables.h