sst-waveshapers: IMutableEnumValuesRegistry Struct Reference
IMutableEnumValuesRegistry Struct Reference abstract
Public Member Functions
virtual ~IMutableEnumValuesRegistry ()
virtual Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const &values)=0
template<typename E >
Detail::EnumInfo const & registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values)
Constructor & Destructor Documentation
~IMutableEnumValuesRegistry()
virtual ~IMutableEnumValuesRegistry () virtual
Member Function Documentation
registerEnum() [1/2]
virtual Detail::EnumInfo const& registerEnum (StringRef enumName, StringRef allEnums, std::vector< int > const & values) pure virtual
Referenced by IMutableEnumValuesRegistry::registerEnum().
registerEnum() [2/2]
Detail::EnumInfo const& registerEnum (StringRef enumName, StringRef allEnums, std::initializer_list< E > values)
References IMutableEnumValuesRegistry::registerEnum(), and Catch::Generators::values().
The documentation for this struct was generated from the following file:
catch2.hpp