sst-waveshapers: ChebSeries< len > Struct Template Reference
ChebSeries< len > Struct Template Reference
Public Member Functions
constexpr ChebSeries (const std::initializer_list< float > &f)
SIMD_M128 eval (SIMD_M128 x) const
Public Attributes
float weights [len] {}
Constructor & Destructor Documentation
ChebSeries()
constexpr ChebSeries (const std::initializer_list< float > & f) constexpr
References ChebSeries< len >::weights.
Member Function Documentation
eval()
SIMD_M128 eval (SIMD_M128 x) const
References ChebSeries< len >::weights.
Referenced by sst::waveshapers::Plus13(), sst::waveshapers::Plus15(), and sst::waveshapers::PlusSqr3().
Member Data Documentation
weights
float weights[len] {}
Referenced by ChebSeries< len >::ChebSeries(), and ChebSeries< len >::eval().
The documentation for this struct was generated from the following file:
Harmonics.h