shortcircuit-xt: ImporterContext Class Reference
ImporterContext Class Reference
#include <import_harness.h>
Public Member Functions
ImporterContext (engine::Engine &engine, const std::string &activityTitle)
~ImporterContext ()=default
ImporterContext (const ImporterContext &)=delete
ImporterContext & operator= (const ImporterContext &)=delete
engine::Engine & getEngine ()
engine::Part & getPart ()
int getPartIndex () const
void raise (const std::string &title, const std::string &msg)
bool fail (const std::string &title, const std::string &msg)
void software_error (const std::string &where, const std::string &what)
void unsupported (const std::string &category, const std::string &detail)
int addGroup (const std::string &name="")
void addZoneToGroup (int groupIdx, std::unique_ptr< engine::Zone > zone)
std::optional< SampleID > loadSampleFromDisk (std::initializer_list< fs::path > candidates, std::initializer_list< const char * > extensionFallbacks={})
bool finish ()
Constructor & Destructor Documentation
ImporterContext() [1/2]
ImporterContext (engine::Engine & engine, const std::string & activityTitle)
References Engine::getMessageController(), Engine::getPatch(), and Engine::getSelectionManager().
~ImporterContext()
~ImporterContext () default
ImporterContext() [2/2]
ImporterContext (const ImporterContext &) delete
Member Function Documentation
operator=()
ImporterContext & operator= (const ImporterContext &) delete
getEngine()
engine::Engine & getEngine ()
Referenced by scxt::import_support::importZoneFilter().
getPart()
engine::Part & getPart ()
Referenced by scxt::exs_support::importEXS(), and scxt::sfz_support::importSFZ().
getPartIndex()
int getPartIndex () const
raise()
void raise (const std::string & title, const std::string & msg)
References RAISE_ERROR_ENGINE.
Referenced by ImporterContext::fail(), ImporterContext::finish(), scxt::akai_support::importAKP(), scxt::sfz_support::importSFZ(), and ImporterContext::software_error().
fail()
bool fail (const std::string & title, const std::string & msg)
References ImporterContext::raise().
Referenced by scxt::akai_support::importAKP(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), and scxt::sfz_support::importSFZ().
software_error()
void software_error (const std::string & where, const std::string & what)
References ImporterContext::raise(), and SCLOG_IF.
Referenced by scxt::import_support::addImportedModRoute(), scxt::import_support::importZoneFilter(), scxt::import_support::importZoneLFO(), and scxt::import_support::importZoneMapping().
unsupported()
void unsupported (const std::string & category, const std::string & detail)
References SCLOG_IF.
Referenced by scxt::exs_support::importEXS(), scxt::multisample_support::importMultisample(), and scxt::sfz_support::zoneFilter().
addGroup()
int addGroup (const std::string & name = "")
References Part::addGroup(), and Part::getGroup().
Referenced by scxt::import_support::getOrCreateGroup(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), and scxt::sfz_support::importSFZ().
addZoneToGroup()
void addZoneToGroup (int groupIdx, std::unique_ptr< engine::Zone > zone)
References Part::getGroup().
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), and scxt::sfz_support::importSFZ().
loadSampleFromDisk()
std::optional< SampleID > loadSampleFromDisk (std::initializer_list< fs::path > candidates, std::initializer_list< const char * > extensionFallbacks = {})
References Engine::getSampleManager().
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), and scxt::sfz_support::importSFZ().
finish()
bool finish ()
References Engine::getSelectionManager(), ImporterContext::raise(), and SCLOG_IF.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), and scxt::sf2_support::importSF2().
The documentation for this class was generated from the following files:
import_harness.h
import_harness.cpp