shortcircuit-xt: RIFFMemFile Class Reference
RIFFMemFile Class Reference
#include <riff_memfile.h>
Public Member Functions
RIFFMemFile ()
RIFFMemFile (const void *data, int datasize)
size_t readWaveEndianLittle (uint32_t inp)
size_t readWaveEndianBig (uint32_t inp)
virtual char Peek ()
bool Read (void *buffer, size_t s)
bool SkipPSTRING ()
uint32_t ReadDWORD ()
uint32_t ReadDWORDBE ()
void WriteDWORD (uint32_t dw)
void WriteDWORDBE (uint32_t dw)
unsigned short ReadWORD ()
void * ReadPtr (size_t s)
void * GetPtr ()
size_t TellI () const
size_t SeekI (size_t pos, int mode=mf_FromStart)
bool riff_descend_RIFF_or_LIST (int tag, size_t *datasize, unsigned int entry=0)
bool iff_descend_FORM (int tag, int *datasize)
bool riff_descend (int tag, size_t *datasize)
bool riff_descend (int *tag, size_t *datasize)
int32_t int32FromPointer (const char *ptr)
bool RIFFPeekChunk (int *Tag=nullptr, size_t *DataSize=nullptr, bool *HasSubchunks=nullptr, int *LISTTag=nullptr)
void invalid () const
bool RIFFIsContainer ()
void * RIFFReadChunk (int *Tag=nullptr, size_t *DataSize=nullptr)
bool RIFFSkipChunk (int *Tag=nullptr, size_t *DataSize=nullptr)
bool RIFFAscend (bool Rewind=false)
bool RIFFDescend (int *LISTtag=nullptr, size_t *datasize=nullptr)
bool RIFFDescendSearch (int tag, size_t *datasize=nullptr, unsigned int entry=0)
uint32_t RIFFGetFileType ()
bool RIFFCreateChunk (uint32_t tag, void *indata, size_t datasize)
bool RIFFCreateLISTHeader (uint32_t tag, size_t subsize)
bool RIFFCreateTextChunk (uint32_t tag, const char *txt)
bool iff_descend (uint32_t tag, int *datasize)
bool Eof () const
bool Eob () const
void tagToFourCCStr (uint32_t tag, char fcc[5])
Static Public Member Functions
static size_t RIFFTextChunkSize (const char *txt)
static void tagToFourCC (uint32_t tag, char fcc[4])
Public Attributes
bool useWaveEndian {true}
Constructor & Destructor Documentation
RIFFMemFile() [1/2]
RIFFMemFile ()
RIFFMemFile() [2/2]
RIFFMemFile (const void * data, int datasize)
Member Function Documentation
readWaveEndianLittle()
size_t readWaveEndianLittle (uint32_t inp)
References RIFFMemFile::useWaveEndian.
Referenced by RIFFMemFile::iff_descend(), RIFFMemFile::RIFFDescend(), RIFFMemFile::RIFFDescendSearch(), RIFFMemFile::RIFFPeekChunk(), RIFFMemFile::RIFFReadChunk(), and RIFFMemFile::RIFFSkipChunk().
readWaveEndianBig()
size_t readWaveEndianBig (uint32_t inp)
References RIFFMemFile::useWaveEndian.
Referenced by RIFFMemFile::iff_descend().
Peek()
virtual char Peek () virtual
Read()
bool Read (void * buffer, size_t s)
Referenced by RIFFMemFile::iff_descend(), RIFFMemFile::iff_descend_FORM(), Sample::parse_aiff(), Sample::parse_riff_wave(), RIFFMemFile::riff_descend(), RIFFMemFile::riff_descend(), RIFFMemFile::riff_descend_RIFF_or_LIST(), and RIFFMemFile::RIFFDescendSearch().
SkipPSTRING()
bool SkipPSTRING ()
Referenced by Sample::parse_aiff().
ReadDWORD()
uint32_t ReadDWORD ()
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
ReadDWORDBE()
uint32_t ReadDWORDBE ()
WriteDWORD()
void WriteDWORD (uint32_t dw)
WriteDWORDBE()
void WriteDWORDBE (uint32_t dw)
ReadWORD()
unsigned short ReadWORD ()
Referenced by Sample::parse_aiff().
ReadPtr()
void * ReadPtr (size_t s)
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
GetPtr()
void * GetPtr ()
TellI()
size_t TellI () const
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
SeekI()
size_t SeekI (size_t pos, int mode = mf_FromStart)
References scxt::sample::loaders::mf_FromCurrent, scxt::sample::loaders::mf_FromEnd, and scxt::sample::loaders::mf_FromStart.
Referenced by RIFFMemFile::iff_descend(), RIFFMemFile::iff_descend_FORM(), Sample::parse_aiff(), Sample::parse_riff_wave(), RIFFMemFile::riff_descend(), RIFFMemFile::riff_descend_RIFF_or_LIST(), and RIFFMemFile::RIFFDescendSearch().
riff_descend_RIFF_or_LIST()
bool riff_descend_RIFF_or_LIST (int tag, size_t * datasize, unsigned int entry = 0)
References riffheader::datasize, RIFFMemFile::Eob(), riffheader::id, scxt::sample::loaders::mf_FromCurrent, RIFFMemFile::Read(), and RIFFMemFile::SeekI().
Referenced by Sample::parse_riff_wave().
iff_descend_FORM()
bool iff_descend_FORM (int tag, int * datasize)
References riffheader::datasize, RIFFMemFile::Eof(), riffheader::id, scxt::sample::loaders::mf_FromCurrent, RIFFMemFile::Read(), and RIFFMemFile::SeekI().
Referenced by Sample::parse_aiff().
riff_descend() [1/2]
bool riff_descend (int tag, size_t * datasize)
References riffheader::datasize, RIFFMemFile::Eob(), riffheader::id, scxt::sample::loaders::mf_FromCurrent, RIFFMemFile::Read(), and RIFFMemFile::SeekI().
Referenced by Sample::parse_riff_wave().
riff_descend() [2/2]
bool riff_descend (int * tag, size_t * datasize)
References riffheader::datasize, riffheader::id, and RIFFMemFile::Read().
int32FromPointer()
int32_t int32FromPointer (const char * ptr)
Referenced by RIFFMemFile::RIFFDescend(), RIFFMemFile::RIFFIsContainer(), RIFFMemFile::RIFFPeekChunk(), RIFFMemFile::RIFFReadChunk(), and RIFFMemFile::RIFFSkipChunk().
RIFFPeekChunk()
bool RIFFPeekChunk (int * Tag = nullptr, size_t * DataSize = nullptr, bool * HasSubchunks = nullptr, int * LISTTag = nullptr)
References RIFFMemFile::int32FromPointer(), RIFFMemFile::invalid(), and RIFFMemFile::readWaveEndianLittle().
Referenced by Sample::parse_riff_wave().
invalid()
void invalid () const
Referenced by RIFFMemFile::RIFFCreateChunk(), RIFFMemFile::RIFFCreateLISTHeader(), RIFFMemFile::RIFFCreateTextChunk(), RIFFMemFile::RIFFPeekChunk(), RIFFMemFile::RIFFReadChunk(), and RIFFMemFile::RIFFSkipChunk().
RIFFIsContainer()
bool RIFFIsContainer ()
References RIFFMemFile::int32FromPointer().
RIFFReadChunk()
void * RIFFReadChunk (int * Tag = nullptr, size_t * DataSize = nullptr)
References RIFFMemFile::int32FromPointer(), RIFFMemFile::invalid(), and RIFFMemFile::readWaveEndianLittle().
Referenced by Sample::parse_riff_wave().
RIFFSkipChunk()
bool RIFFSkipChunk (int * Tag = nullptr, size_t * DataSize = nullptr)
References RIFFMemFile::int32FromPointer(), RIFFMemFile::invalid(), and RIFFMemFile::readWaveEndianLittle().
Referenced by Sample::parse_riff_wave().
RIFFAscend()
bool RIFFAscend (bool Rewind = false)
Referenced by Sample::parse_riff_wave().
RIFFDescend()
bool RIFFDescend (int * LISTtag = nullptr, size_t * datasize = nullptr)
References RIFFMemFile::int32FromPointer(), and RIFFMemFile::readWaveEndianLittle().
RIFFDescendSearch()
bool RIFFDescendSearch (int tag, size_t * datasize = nullptr, unsigned int entry = 0)
References riffheader::datasize, RIFFMemFile::Eob(), riffheader::id, scxt::sample::loaders::mf_FromCurrent, RIFFMemFile::Read(), RIFFMemFile::readWaveEndianLittle(), and RIFFMemFile::SeekI().
Referenced by Sample::parse_riff_wave().
RIFFGetFileType()
uint32_t RIFFGetFileType ()
RIFFCreateChunk()
bool RIFFCreateChunk (uint32_t tag, void * indata, size_t datasize)
References RIFFMemFile::invalid().
RIFFCreateLISTHeader()
bool RIFFCreateLISTHeader (uint32_t tag, size_t subsize)
References RIFFMemFile::invalid().
RIFFTextChunkSize()
static size_t RIFFTextChunkSize (const char * txt) static
RIFFCreateTextChunk()
bool RIFFCreateTextChunk (uint32_t tag, const char * txt)
References RIFFMemFile::invalid().
iff_descend()
bool iff_descend (uint32_t tag, int * datasize)
References riffheader::datasize, RIFFMemFile::Eof(), riffheader::id, scxt::sample::loaders::mf_FromCurrent, RIFFMemFile::Read(), RIFFMemFile::readWaveEndianBig(), RIFFMemFile::readWaveEndianLittle(), and RIFFMemFile::SeekI().
Referenced by Sample::parse_aiff().
Eof()
bool Eof () const
Referenced by RIFFMemFile::iff_descend(), and RIFFMemFile::iff_descend_FORM().
Eob()
bool Eob () const
Referenced by RIFFMemFile::riff_descend(), RIFFMemFile::riff_descend_RIFF_or_LIST(), and RIFFMemFile::RIFFDescendSearch().
tagToFourCC()
static void tagToFourCC (uint32_t tag, char fcc[4]) static
tagToFourCCStr()
void tagToFourCCStr (uint32_t tag, char fcc[5])
Member Data Documentation
useWaveEndian
bool useWaveEndian {true}
Referenced by Sample::parse_aiff(), RIFFMemFile::readWaveEndianBig(), and RIFFMemFile::readWaveEndianLittle().
The documentation for this class was generated from the following file:
riff_memfile.h