shortcircuit-xt: SCXTProcessor Class Reference
SCXTProcessor Class Reference
Inherits AudioProcessor, and clap_properties.
Public Member Functions
SCXTProcessor ()
~SCXTProcessor ()
void prepareToPlay (double sampleRate, int samplesPerBlock) override
void releaseResources () override
bool isBusesLayoutSupported (const BusesLayout &layouts) const override
void processBlock (juce::AudioBuffer< float > &, juce::MidiBuffer &) override
juce::AudioProcessorEditor * createEditor () override
bool hasEditor () const override
const juce::String getName () const override
bool acceptsMidi () const override
bool producesMidi () const override
bool isMidiEffect () const override
double getTailLengthSeconds () const override
int getNumPrograms () override
int getCurrentProgram () override
void setCurrentProgram (int index) override
const juce::String getProgramName (int index) override
void changeProgramName (int index, const juce::String &newName) override
void getStateInformation (juce::MemoryBlock &destData) override
void setStateInformation (const void *data, int sizeInBytes) override
Constructor & Destructor Documentation
SCXTProcessor()
SCXTProcessor ()
~SCXTProcessor()
~SCXTProcessor ()
References scxt::showLeakLog().
Member Function Documentation
prepareToPlay()
void prepareToPlay (double sampleRate, int samplesPerBlock) override
releaseResources()
void releaseResources () override
isBusesLayoutSupported()
bool isBusesLayoutSupported (const BusesLayout & layouts) const override
processBlock()
void processBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer & midiMessages) override
createEditor()
juce::AudioProcessorEditor * createEditor () override
hasEditor()
bool hasEditor () const override
getName()
const juce::String getName () const override
acceptsMidi()
bool acceptsMidi () const override
producesMidi()
bool producesMidi () const override
isMidiEffect()
bool isMidiEffect () const override
getTailLengthSeconds()
double getTailLengthSeconds () const override
getNumPrograms()
int getNumPrograms () override
getCurrentProgram()
int getCurrentProgram () override
setCurrentProgram()
void setCurrentProgram (int index) override
getProgramName()
const juce::String getProgramName (int index) override
changeProgramName()
void changeProgramName (int index, const juce::String & newName) override
getStateInformation()
void getStateInformation (juce::MemoryBlock & destData) override
References Engine::FOR_DAW, SCLOG, and scxt::json::streamEngineState().
setStateInformation()
void setStateInformation (const void * data, int sizeInBytes) override
References scxt::messaging::client::clientSendToSerialization().
The documentation for this class was generated from the following files:
SCXTProcessor.h
SCXTProcessor.cpp