shortcircuit-xt: FileMapView Class Reference
FileMapView Class Reference
This class provides a mechanism to do a MapViewOfFile/mmap in a portable way.
#include <file_map_view.h>
Classes
struct Impl
Public Member Functions
FileMapView (const fs::path &filename)
Construct a view of a file.
~FileMapView ()
bool isMapped ()
void * data ()
size_t dataSize ()
Public Attributes
std::unique_ptr< Impl > impl
Detailed Description
This class provides a mechanism to do a MapViewOfFile/mmap in a portable way.
The intent is that you would use it with a unique_ptr where you needed the map scope.
fs::path p = string_to_path("foo.bin");
auto mapper = std::make_unique<scxt::FileMapView>(p);
auto d = mapper->data; // valid until mapper is destroyed
auto s = mapper->dataSize;
Constructor & Destructor Documentation
FileMapView()
FileMapView (const fs::path & filename)
Construct a view of a file.
Parameters
filename the path to the file to be mapped. If unavabiable, isMapped will return false
References FileMapView::impl.
~FileMapView()
~FileMapView ()
Member Function Documentation
isMapped()
bool isMapped ()
References scxt::infrastructure::as(), FileMapView::impl, and posixImpl::isMapped.
data()
void * data ()
References scxt::infrastructure::as(), posixImpl::data, and FileMapView::impl.
dataSize()
size_t dataSize ()
References scxt::infrastructure::as(), posixImpl::dataSize, and FileMapView::impl.
Member Data Documentation
impl
std::unique_ptr<Impl> impl
Referenced by FileMapView::data(), FileMapView::dataSize(), FileMapView::FileMapView(), and FileMapView::isMapped().
The documentation for this class was generated from the following files:
file_map_view.h
file_map_view.cpp