shortcircuit-xt: init-maker.cpp File Reference
init-maker.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References Engine::FOR_MULTI, scxt::patch_io::loadMulti(), and SCLOG.
Referenced by scxt::sample::compound::getSFZCompoundList(), SCXTPlugin::process(), and Engine::processAudio().