shortcircuit-xt: modulator_storage.h File Reference
modulator_storage.h File Reference
Classes
struct AdsrStorage
struct CurveLFOStorage
struct EnvLFOStorage
struct PhasorStorage
struct RandomStorage
struct ModulatorStorage
struct MiscSourceStorage
Namespaces
namespace scxt
namespace scxt::modulation
namespace scxt::modulation::modulators
Typedefs
using StepLFOStorage = sst::basic_blocks::modulators::StepLFO< scxt::blockSize >::Storage
Functions
double secondsToNormalizedEnvTime (double s)
scxt::datamodel::pmd envelopeThirtyTwo ()
scxt::datamodel::pmd envTime ()
SC_DESCRIBE (scxt::modulation::modulators::AdsrStorage, { SC_FIELD(dly, envTime().withDefault(0.f).withName("Delay"));SC_FIELD(a, envTime().withName("Attack"));SC_FIELD(h, envTime().withDefault(0.f).withName("Hold"));SC_FIELD(d, envTime().withName("Decay"));SC_FIELD(s, pmd().asPercent().withDefault(1.f).withName("Sustain"));SC_FIELD(r, envTime().withDefault(0.5).withName("Release"));SC_FIELD(aShape, pmd().asPercentBipolar().withName("Attack Shape"));SC_FIELD(dShape, pmd().asPercentBipolar().withName("Decay Shape"));SC_FIELD(rShape, pmd().asPercentBipolar().withName("Release Shape"));SC_FIELD(gateGroupEGOnAnyPlaying, pmd().asOnOffBool().withName("Gated if ungated voices sounding"));}) SC_DESCRIBE(scxt
SC_DESCRIBE (scxt::modulation::modulators::PhasorStorage,.asInt() .withLinearScaleFormatting("") .withDefault(1) .withName("Numerator") .withRange(1, 64))
asInt () .withLinearScaleFormatting("") .withDefault(4) .withName("Denominator") .withRange(1
Function Documentation
envelopeThirtyTwo()
scxt::datamodel::pmd envelopeThirtyTwo ()
envTime()
scxt::datamodel::pmd envTime ()
Referenced by SC_DESCRIBE().
SC_DESCRIBE() [1/2]
SC_DESCRIBE (scxt::modulation::modulators::AdsrStorage , { SC_FIELD(dly, envTime().withDefault(0.f).withName("Delay"));SC_FIELD(a, envTime().withName("Attack"));SC_FIELD(h, envTime().withDefault(0.f).withName("Hold"));SC_FIELD(d, envTime().withName("Decay"));SC_FIELD(s, pmd().asPercent().withDefault(1.f).withName("Sustain"));SC_FIELD(r, envTime().withDefault(0.5).withName("Release"));SC_FIELD(aShape, pmd().asPercentBipolar().withName("Attack Shape"));SC_FIELD(dShape, pmd().asPercentBipolar().withName("Decay Shape"));SC_FIELD(rShape, pmd().asPercentBipolar().withName("Release Shape"));SC_FIELD(gateGroupEGOnAnyPlaying, pmd().asOnOffBool().withName("Gated if ungated voices sounding"));})
References envTime(), SC_FIELD, and withName().
SC_DESCRIBE() [2/2]
SC_DESCRIBE (scxt::modulation::modulators::PhasorStorage , . asInt) .withLinearScaleFormatting("") .withDefault(1) .withName("Numerator") .withRange(1, 64)
asInt()
asInt ()