shortcircuit-xt: scxt::messaging::client::detail Namespace Reference
scxt::messaging::client::detail Namespace Reference
Typedefs
using client_message_value = tao::json::basic_value< client_message_traits >
template<typename VT >
using diffMsg_t = std::tuple< ptrdiff_t, VT >
template<typename VT >
using indexedDiffMsg_t = std::tuple< size_t, ptrdiff_t, VT >
template<typename VT >
using indexedZoneOrGroupDiffMsg_t = std::tuple< bool, size_t, ptrdiff_t, VT >
Functions
template<size_t I, template< typename... > class Traits>
void doExecOnSerialization (tao::json::basic_value< Traits > &o, engine::Engine &e, MessageController &mc)
template<template< typename... > class Traits, size_t... Is>
auto executeOnSerializationFor (size_t ft, typename tao::json::basic_value< Traits > &o, engine::Engine &e, MessageController &mc, std::index_sequence< Is... >)
template<size_t I, typename Client , template< typename... > class Traits>
void doExecOnClient (tao::json::basic_value< Traits > &o, Client *c)
template<typename Client , template< typename... > class Traits, size_t... Is>
auto executeOnClientFor (size_t ft, typename tao::json::basic_value< Traits > &o, Client *c, std::index_sequence< Is... >)
template<typename VT , typename M >
void updateZoneLeadMemberValue (M m, const diffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr)
template<typename VT , typename M >
void updateZoneMemberValue (M m, const diffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr)
template<typename VT , typename M >
void updateGroupMemberValue (M m, const diffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr)
template<typename VT , typename M >
void updateZoneIndexedMemberValue (M m, const indexedDiffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onEngineExtra=nullptr)
template<typename VT , typename M >
void updateGroupIndexedMemberValue (M m, const indexedDiffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onEngineExtra=nullptr)
template<typename VT , typename MZ , typename MG >
void updateZoneOrGroupIndexedMemberValue (MZ mz, MG mg, const indexedZoneOrGroupDiffMsg_t< VT > &payload, const engine::Engine &engine, MessageController &cont, std::function< void(const engine::Engine &)> responseCB=nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onZoneEngineExtra=nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onGroupEngineExtra=nullptr)
Typedef Documentation
client_message_value
using client_message_value = tao::json::basic_value<client_message_traits>
diffMsg_t
template<typename VT > using diffMsg_t = std::tuple<ptrdiff_t, VT>
indexedDiffMsg_t
template<typename VT > using indexedDiffMsg_t = std::tuple<size_t, ptrdiff_t, VT>
indexedZoneOrGroupDiffMsg_t
template<typename VT > using indexedZoneOrGroupDiffMsg_t = std::tuple<bool, size_t, ptrdiff_t, VT>
Function Documentation
doExecOnSerialization()
template<size_t I, template< typename... > class Traits> void doExecOnSerialization (tao::json::basic_value< Traits > & o, engine::Engine & e, MessageController & mc)
executeOnSerializationFor()
template<template< typename... > class Traits, size_t... Is> auto executeOnSerializationFor (size_t ft, typename tao::json::basic_value< Traits > & o, engine::Engine & e, MessageController & mc, std::index_sequence< Is... >)
Referenced by scxt::messaging::client::serializationThreadExecuteClientMessage().
doExecOnClient()
template<size_t I, typename Client , template< typename... > class Traits> void doExecOnClient (tao::json::basic_value< Traits > & o, Client * c)
executeOnClientFor()
template<typename Client , template< typename... > class Traits, size_t... Is> auto executeOnClientFor (size_t ft, typename tao::json::basic_value< Traits > & o, Client * c, std::index_sequence< Is... >)
Referenced by scxt::messaging::client::clientThreadExecuteSerializationMessage().
updateZoneLeadMemberValue()
template<typename VT , typename M > void updateZoneLeadMemberValue (M m, const diffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, and Engine::getSelectionManager().
updateZoneMemberValue()
template<typename VT , typename M > void updateZoneMemberValue (M m, const diffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, and Engine::getSelectionManager().
updateGroupMemberValue()
template<typename VT , typename M > void updateGroupMemberValue (M m, const diffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, and Engine::getSelectionManager().
updateZoneIndexedMemberValue()
template<typename VT , typename M > void updateZoneIndexedMemberValue (M m, const indexedDiffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onEngineExtra = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, and Engine::getSelectionManager().
Referenced by updateZoneOrGroupIndexedMemberValue().
updateGroupIndexedMemberValue()
template<typename VT , typename M > void updateGroupIndexedMemberValue (M m, const indexedDiffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onEngineExtra = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, and Engine::getSelectionManager().
Referenced by updateZoneOrGroupIndexedMemberValue().
updateZoneOrGroupIndexedMemberValue()
template<typename VT , typename MZ , typename MG > void updateZoneOrGroupIndexedMemberValue (MZ mz, MG mg, const indexedZoneOrGroupDiffMsg_t< VT > & payload, const engine::Engine & engine, MessageController & cont, std::function< void(const engine::Engine &)> responseCB = nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onZoneEngineExtra = nullptr, std::function< void(engine::Engine &, const selection::SelectionManager::selectedZones_t &)> onGroupEngineExtra = nullptr)
References scxt::messaging::client::cont, scxt::messaging::client::engine, updateGroupIndexedMemberValue(), and updateZoneIndexedMemberValue().