shortcircuit-xt: scxt::engine Namespace Reference
scxt::engine Namespace Reference
Namespaces
namespace dtl
Classes
struct Bus
struct BusEffect
struct BusEffectStorage
struct Clipboard
struct Engine
struct Group
struct GroupTrigger
Calculate if a group is triggered.
struct GroupTriggerConditions
struct GroupTriggerInstrumentState
Maintain the state of keys ccs etc... for a particular instrument.
struct GroupTriggerStorage
struct GTKeyswitchLatch
struct GTKeyswitchMomentary
struct GTMacro
struct GTMIDI1CC
struct HasGroupZoneProcessors
struct KeyboardRange
A class representing a range of the keyboard with fade zones on either end.
struct Macro
struct MemoryPool
struct MissingResolutionWorkItem
struct Part
struct Patch
struct VelocityRange
struct Zone
Typedefs
using busRemapFn_t = void(*)(int16_t, float *const)
using GroupTriggerBuffer = uint8_t[2048]
Enumerations
enum BusAddress : int16_t {
ERROR_BUS = -2 , DEFAULT_BUS = -1 , MAIN_0 , PART_0 ,
AUX_0 = PART_0 + numParts
}
enum AvailableBusEffects {
none , reverb1 , reverb2 , flanger ,
phaser , delay , treemonster , nimbus ,
rotaryspeaker , floatydelay , bonsai
}
enum GroupZoneFeatures { MISSING_SAMPLE = 1 << 0 , MUTED = 1 << 1 }
enum struct GroupTriggerID : int32_t {
NONE , KEYSWITCH_LATCH , KEYSWITCH_MOMENTARY , MACRO ,
MIDICC = MACRO + scxt::macrosPerPart , LAST_MIDICC = MIDICC + 128
}
Functions
std::string getBusAddressLabel (BusAddress rt, const std::string &defaultName, bool shortName)
DEFINE_BUSFX (reverb1, sst::effects::reverb1::Reverb1)
DEFINE_BUSFX (reverb2, sst::effects::reverb2::Reverb2)
DEFINE_BUSFX (flanger, sst::effects::flanger::Flanger)
DEFINE_BUSFX (phaser, sst::effects::phaser::Phaser)
DEFINE_BUSFX (treemonster, sst::effects::treemonster::TreeMonster)
DEFINE_BUSFX (delay, sst::effects::delay::Delay)
DEFINE_BUSFX (floatydelay, sst::effects::floatydelay::FloatyDelay)
DEFINE_BUSFX (nimbus, sst::effects::nimbus::Nimbus)
DEFINE_BUSFX (rotaryspeaker, sst::effects::rotaryspeaker::RotarySpeaker)
DEFINE_BUSFX (bonsai, sst::effects::bonsai::Bonsai)
std::string getBusEffectStreamingName (AvailableBusEffects p)
int getBusEffectStreamingVersion (AvailableBusEffects p)
std::string getBusEffectDisplayName (AvailableBusEffects p)
std::unique_ptr< BusEffect > createEffect (AvailableBusEffects p, Engine *e, BusEffectStorage *s)
std::pair< int16_t, busRemapFn_t > getBusEffectRemapStreamingFunction (AvailableBusEffects p)
std::string toStringAvailableBusEffects (const AvailableBusEffects &p)
AvailableBusEffects fromStringAvailableBusEffects (const std::string &s)
std::string toStringGroupTriggerID (const GroupTriggerID &p)
GroupTriggerID fromStringGroupTriggerID (const std::string &s)
GroupTrigger * makeGroupTrigger (GroupTriggerID id, GroupTriggerInstrumentState &gis, GroupTriggerStorage &st, GroupTriggerBuffer &bf)
std::string getGroupTriggerDisplayName (GroupTriggerID id)
std::vector< MissingResolutionWorkItem > collectMissingResolutionWorkItems (const Engine &e)
void resolveSingleFileMissingWorkItem (engine::Engine &e, const MissingResolutionWorkItem &mwi, const fs::path &p)
void resolveMultiFileMissingWorkItem (engine::Engine &e, const MissingResolutionWorkItem &mwi, const fs::path &p)
Variables
constexpr int lfosPerGroup {scxt::lfosPerGroup}
constexpr int processorCount {HasGroupZoneProcessors<Zone>::processorCount}
constexpr int lfosPerZone {scxt::lfosPerZone}
Typedef Documentation
busRemapFn_t
using busRemapFn_t = void (*)(int16_t, float *const)
GroupTriggerBuffer
using GroupTriggerBuffer = uint8_t[2048]
Enumeration Type Documentation
BusAddress
enum BusAddress : int16_t
Enumerator
ERROR_BUS
DEFAULT_BUS
MAIN_0
PART_0
AUX_0
AvailableBusEffects
enum AvailableBusEffects
Enumerator
none
reverb1
reverb2
flanger
phaser
delay
treemonster
nimbus
rotaryspeaker
floatydelay
bonsai
GroupZoneFeatures
enum GroupZoneFeatures
Enumerator
MISSING_SAMPLE
MUTED
GroupTriggerID
enum struct GroupTriggerID : int32_t strong
Enumerator
NONE
KEYSWITCH_LATCH
KEYSWITCH_MOMENTARY
MACRO
MIDICC
LAST_MIDICC
Function Documentation
getBusAddressLabel()
std::string getBusAddressLabel (BusAddress rt, const std::string & defaultName, bool shortName)
References AUX_0, DEFAULT_BUS, ERROR_BUS, MAIN_0, and PART_0.
Referenced by RoutingPaneContents< RPTraits >::getRoutingLabel(), Bus::process(), PartSidebarCard::resetFromEditorCache(), and PartSidebarCard::showRoutingMenu().
DEFINE_BUSFX() [1/10]
DEFINE_BUSFX (reverb1 , sst::effects::reverb1::Reverb1)
DEFINE_BUSFX() [2/10]
DEFINE_BUSFX (reverb2 , sst::effects::reverb2::Reverb2)
DEFINE_BUSFX() [3/10]
DEFINE_BUSFX (flanger , sst::effects::flanger::Flanger)
DEFINE_BUSFX() [4/10]
DEFINE_BUSFX (phaser , sst::effects::phaser::Phaser)
DEFINE_BUSFX() [5/10]
DEFINE_BUSFX (treemonster , sst::effects::treemonster::TreeMonster)
DEFINE_BUSFX() [6/10]
DEFINE_BUSFX (delay , sst::effects::delay::Delay)
DEFINE_BUSFX() [7/10]
DEFINE_BUSFX (floatydelay , sst::effects::floatydelay::FloatyDelay)
DEFINE_BUSFX() [8/10]
DEFINE_BUSFX (nimbus , sst::effects::nimbus::Nimbus)
DEFINE_BUSFX() [9/10]
DEFINE_BUSFX (rotaryspeaker , sst::effects::rotaryspeaker::RotarySpeaker)
DEFINE_BUSFX() [10/10]
DEFINE_BUSFX (bonsai , sst::effects::bonsai::Bonsai)
getBusEffectStreamingName()
std::string getBusEffectStreamingName (AvailableBusEffects p)
Referenced by toStringAvailableBusEffects().
getBusEffectStreamingVersion()
int getBusEffectStreamingVersion (AvailableBusEffects p)
getBusEffectDisplayName()
std::string getBusEffectDisplayName (AvailableBusEffects p)
createEffect()
std::unique_ptr< BusEffect > createEffect (AvailableBusEffects p, Engine * e, BusEffectStorage * s)
References BusEffectStorage::type.
Referenced by Bus::initializeAfterUnstream(), Bus::setBusEffectType(), Part::setBusEffectType(), and Part::setupOnUnstream().
getBusEffectRemapStreamingFunction()
std::pair< int16_t, busRemapFn_t > getBusEffectRemapStreamingFunction (AvailableBusEffects p)
toStringAvailableBusEffects()
std::string toStringAvailableBusEffects (const AvailableBusEffects & p)
References getBusEffectStreamingName().
fromStringAvailableBusEffects()
AvailableBusEffects fromStringAvailableBusEffects (const std::string & s)
References none.
toStringGroupTriggerID()
std::string toStringGroupTriggerID (const GroupTriggerID & p)
References KEYSWITCH_LATCH, KEYSWITCH_MOMENTARY, LAST_MIDICC, MACRO, MIDICC, and NONE.
fromStringGroupTriggerID()
GroupTriggerID fromStringGroupTriggerID (const std::string & s)
References LAST_MIDICC, and NONE.
makeGroupTrigger()
GroupTrigger * makeGroupTrigger (GroupTriggerID id, GroupTriggerInstrumentState & gis, GroupTriggerStorage & st, GroupTriggerBuffer & bf)
References CS, KEYSWITCH_LATCH, KEYSWITCH_MOMENTARY, LAST_MIDICC, MACRO, MIDICC, and SCLOG_IF.
Referenced by GroupTriggerConditions::setupOnUnstream().
getGroupTriggerDisplayName()
std::string getGroupTriggerDisplayName (GroupTriggerID id)
References KEYSWITCH_LATCH, KEYSWITCH_MOMENTARY, LAST_MIDICC, MACRO, MIDICC, NONE, and SCLOG_IF.
Referenced by GroupTriggersCard::ConditionRow::setupValuesFromData().
collectMissingResolutionWorkItems()
std::vector< MissingResolutionWorkItem > collectMissingResolutionWorkItems (const Engine & e)
References Engine::getSampleManager().
Referenced by Engine::sendFullRefreshToClient().
resolveSingleFileMissingWorkItem()
void resolveSingleFileMissingWorkItem (engine::Engine & e, const MissingResolutionWorkItem & mwi, const fs::path & p)
References Zone::ENDPOINTS, Engine::getMessageController(), Engine::getPatch(), Engine::getSampleManager(), MissingResolutionWorkItem::missingID, SCLOG_IF, and SampleID::to_string().
Referenced by scxt::messaging::client::doResolveMultiSample(), and scxt::messaging::client::doResolveSample().
resolveMultiFileMissingWorkItem()
void resolveMultiFileMissingWorkItem (engine::Engine & e, const MissingResolutionWorkItem & mwi, const fs::path & p)
References Zone::ENDPOINTS, scxt::extensionMatches(), Engine::getMessageController(), Engine::getPatch(), Engine::getSampleManager(), SampleID::md5, MissingResolutionWorkItem::missingID, and SCLOG_IF.
Referenced by scxt::messaging::client::doResolveMultiSample(), and scxt::messaging::client::doResolveSample().
Variable Documentation
lfosPerGroup
constexpr int lfosPerGroup {scxt::lfosPerGroup} constexpr
Referenced by Group::attack(), Zone::onRoutingChanged(), Group::processWithOS(), Group::rePrepareAndBindGroupMatrix(), and Group::resetLFOs().
processorCount
constexpr int processorCount {HasGroupZoneProcessors<Zone>::processorCount} constexpr
Referenced by Voice::cleanupVoice(), Engine::getProcessorStorage(), Voice::initializeProcessors(), scxt::dsp::processor::processPar1Pattern(), scxt::dsp::processor::processSequential(), Group::processWithOS(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForNoGroupSelected(), SelectionManager::sendDisplayDataForNoZoneSelected(), SelectionManager::sendDisplayDataForZonesBasedOnLead(), and Voice::~Voice().
lfosPerZone
constexpr int lfosPerZone {scxt::lfosPerZone} constexpr
Referenced by Zone::onRoutingChanged(), Voice::processWithOS(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForZonesBasedOnLead(), Group::setupOnUnstream(), and Voice::voiceStarted().