shortcircuit-xt: scxt::infrastructure Namespace Reference
scxt::infrastructure Namespace Reference
Classes
struct DefaultsProvider
class FileMapView
This class provides a mechanism to do a MapViewOfFile/mmap in a portable way.
struct posixImpl
Enumerations
enum DefaultKeys {
zoomLevel , octave0 , invertScroll , showKnobs ,
colormapId , colormapPathIfFile , welcomeScreenSeen , playModeExpanded ,
partSidebarPartExpanded , browserAutoPreviewEnabled , browserPreviewAmplitude , useSoftwareRenderer ,
nKeys
}
Functions
posixImpl * as (FileMapView::Impl *imp)
std::string hexString (unsigned char *digest, int length)
std::string createMD5SumFromFile (const fs::path &path)
std::string defaultKeyToString (DefaultKeys k)
Enumeration Type Documentation
DefaultKeys
enum DefaultKeys
Enumerator
zoomLevel
octave0
invertScroll
showKnobs
colormapId
colormapPathIfFile
welcomeScreenSeen
playModeExpanded
partSidebarPartExpanded
browserAutoPreviewEnabled
browserPreviewAmplitude
useSoftwareRenderer
nKeys
Function Documentation
as()
posixImpl * as (FileMapView::Impl * imp)
Referenced by FileMapView::data(), FileMapView::dataSize(), and FileMapView::isMapped().
hexString()
std::string hexString (unsigned char * digest, int length)
Referenced by createMD5SumFromFile().
createMD5SumFromFile()
std::string createMD5SumFromFile (const fs::path & path)
References hexString().
Referenced by ScanWorker::ScanFile::go(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), and Sample::load().
defaultKeyToString()
std::string defaultKeyToString (DefaultKeys k)
References browserAutoPreviewEnabled, browserPreviewAmplitude, colormapId, colormapPathIfFile, invertScroll, nKeys, octave0, partSidebarPartExpanded, playModeExpanded, showKnobs, useSoftwareRenderer, welcomeScreenSeen, and zoomLevel.
Referenced by Engine::Engine().