shortcircuit-xt: scxt::voice::modulation Namespace Reference
scxt::voice::modulation Namespace Reference
Classes
struct MatrixConfig
struct Matrix
struct MatrixEndpoints
Typedefs
typedef std::pair< std::string, std::string > identifierDisplayName_t
typedef std::pair< MatrixConfig::TargetIdentifier, identifierDisplayName_t > namedTarget_t
typedef std::vector< namedTarget_t > namedTargetVector_t
typedef std::pair< MatrixConfig::SourceIdentifier, identifierDisplayName_t > namedSource_t
typedef std::vector< namedSource_t > namedSourceVector_t
typedef std::pair< MatrixConfig::CurveIdentifier, identifierDisplayName_t > namedCurve_t
typedef std::vector< namedCurve_t > namedCurveVector_t
typedef std::tuple< bool, namedSourceVector_t, namedTargetVector_t, namedCurveVector_t > voiceMatrixMetadata_t
Functions
float randomRoll (bool bipolar, int distribution)
voiceMatrixMetadata_t getVoiceMatrixMetadata (const engine::Zone &z)
Variables
sst::basic_blocks::dsp::RNG rng
Typedef Documentation
identifierDisplayName_t
typedef std::pair<std::string, std::string> identifierDisplayName_t
namedTarget_t
typedef std::pair<MatrixConfig::TargetIdentifier, identifierDisplayName_t> namedTarget_t
namedTargetVector_t
typedef std::vector<namedTarget_t> namedTargetVector_t
namedSource_t
typedef std::pair<MatrixConfig::SourceIdentifier, identifierDisplayName_t> namedSource_t
namedSourceVector_t
typedef std::vector<namedSource_t> namedSourceVector_t
namedCurve_t
typedef std::pair<MatrixConfig::CurveIdentifier, identifierDisplayName_t> namedCurve_t
namedCurveVector_t
typedef std::vector<namedCurve_t> namedCurveVector_t
voiceMatrixMetadata_t
typedef std::tuple<bool, namedSourceVector_t, namedTargetVector_t, namedCurveVector_t> voiceMatrixMetadata_t
Function Documentation
randomRoll()
float scxt::voice::modulation::randomRoll (bool bipolar, int distribution)
References rng.
Referenced by MatrixEndpoints::Sources::bind().
getVoiceMatrixMetadata()
voiceMatrixMetadata_t getVoiceMatrixMetadata (const engine::Zone & z)
References ModulationCurves::allCurves, ModulationCurves::curveNames, Zone::getEngine(), Engine::voiceModSources, and Engine::voiceModTargets.
Referenced by scxt::messaging::client::CLIENT_TO_SERIAL_CONSTRAINED(), SelectionManager::configureAndSendZoneModMatrixMetadata(), scxt::messaging::client::setProcessorType(), and scxt::messaging::client::updateMacroFullState().
Variable Documentation
rng
sst::basic_blocks::dsp::RNG rng
Referenced by StepLFO::assign(), scxt::modulation::modulators::load_lfo_preset(), randomRoll(), and Group::setupOnUnstream().