shortcircuit-xt: scxt::import_support Namespace Reference
scxt::import_support Namespace Reference
Namespaces
namespace cytomic
namespace vember
Classes
struct EGHandle
struct EnvelopeArgs
struct FilterArgs
struct FilterHandle
struct ImportedModRoute
struct ImportedSource
struct ImportedTarget
class ImporterContext
struct LFOArgs
struct LFOHandle
struct LoopArgs
struct MappingArgs
Typedefs
using SR = voice::modulation::MatrixConfig::SourceIdentifier
using TG = voice::modulation::MatrixConfig::TargetIdentifier
Enumerations
enum class FilterType {
Other , LP6 , LP12 , LP18 ,
LP24 , LP36 , LP48 , HP6 ,
HP12 , HP18 , HP24 , HP36 ,
HP48 , BP6 , BP12 , BP24 ,
Notch12 , Notch24 , Peak , Allpass ,
Comb
}
enum class ImportedSourceKind {
LFO , EG , MidiCC , Velocity ,
ReleaseVelocity , ChannelAT , PolyAT , ModWheel ,
PitchBend , KeyTrack
}
enum class FilterParam { Cutoff , Resonance }
enum class EGWhich {
Delay , Attack , Hold , Decay ,
Sustain , Release
}
enum class ImportedTargetKind {
Pitch , FilterParam , EGTime , ZonePan ,
ZoneAmplitude
}
Functions
EGHandle importZoneEnvelope (engine::Zone &zone, ImporterContext &ctx, int egIdx, const EnvelopeArgs &a)
FilterHandle importZoneFilter (engine::Zone &zone, ImporterContext &ctx, int procSlot, const FilterArgs &a)
bool isVirtualSampleName (const std::string &name)
bool installVirtualSample (engine::Zone &zone, ImporterContext &ctx, const std::string &name)
template<typename Map , typename Key , typename NameFn >
int getOrCreateGroup (ImporterContext &ctx, Map &map, const Key &key, NameFn &&nameFn)
LFOHandle importZoneLFO (engine::Zone &zone, ImporterContext &ctx, int lfoSlot, const LFOArgs &a)
void importZoneLoop (engine::Zone &zone, ImporterContext &ctx, int variantIdx, const LoopArgs &a)
void importZoneMapping (engine::Zone &zone, ImporterContext &ctx, const MappingArgs &a)
int addImportedModRoute (engine::Zone &zone, ImporterContext &ctx, const ImportedModRoute &r)
constexpr float centsToSemitones (float cents)
float centibelsToLinear (double cB)
float sf2NormalizedPan (int pan)
float dBToCubicAttenuation (float dB)
Typedef Documentation
SR
using SR = voice::modulation::MatrixConfig::SourceIdentifier
TG
using TG = voice::modulation::MatrixConfig::TargetIdentifier
Enumeration Type Documentation
FilterType
enum class FilterType strong
Enumerator
Other
LP6
LP12
LP18
LP24
LP36
LP48
HP6
HP12
HP18
HP24
HP36
HP48
BP6
BP12
BP24
Notch12
Notch24
Peak
Allpass
Comb
ImportedSourceKind
enum class ImportedSourceKind strong
Enumerator
LFO
EG
MidiCC
Velocity
ReleaseVelocity
ChannelAT
PolyAT
ModWheel
PitchBend
KeyTrack
FilterParam
enum class FilterParam strong
Enumerator
Cutoff
Resonance
EGWhich
enum class EGWhich strong
Enumerator
Delay
Attack
Hold
Decay
Sustain
Release
ImportedTargetKind
enum class ImportedTargetKind strong
Enumerator
Pitch
FilterParam
EGTime
ZonePan
ZoneAmplitude
Function Documentation
importZoneEnvelope()
EGHandle importZoneEnvelope (engine::Zone & zone, ImporterContext & ctx, int egIdx, const EnvelopeArgs & a)
References EnvelopeArgs::attackSeconds, EnvelopeArgs::attackShape, EnvelopeArgs::decaySeconds, EnvelopeArgs::decayShape, EnvelopeArgs::delaySeconds, Zone::egStorage, EnvelopeArgs::holdSeconds, EnvelopeArgs::releaseSeconds, EnvelopeArgs::releaseShape, scxt::modulation::secondsToNormalizedEnvTime(), and EnvelopeArgs::sustainLevel.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::sf2_support::importSF2(), and scxt::sfz_support::zoneEnvelope().
importZoneFilter()
FilterHandle importZoneFilter (engine::Zone & zone, ImporterContext & ctx, int procSlot, const FilterArgs & a)
References FilterArgs::cutoff, ImporterContext::getEngine(), Engine::getMessageController(), HasGroupZoneProcessors< T >::processorStorage, FilterArgs::resonance, HasGroupZoneProcessors< T >::setProcessorType(), ImporterContext::software_error(), and FilterArgs::type.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::sf2_support::importSF2(), and scxt::sfz_support::zoneFilter().
isVirtualSampleName()
bool isVirtualSampleName (const std::string & name)
Referenced by scxt::sfz_support::importSFZ().
installVirtualSample()
bool installVirtualSample (engine::Zone & zone, ImporterContext & ctx, const std::string & name)
References ImporterContext::getEngine(), Engine::getMessageController(), HasGroupZoneProcessors< T >::processorStorage, scxt::dsp::processor::proct_osc_EBWaveforms, scxt::dsp::processor::proct_osc_tiltnoise, and HasGroupZoneProcessors< T >::setProcessorType().
Referenced by scxt::sfz_support::importSFZ().
getOrCreateGroup()
template<typename Map , typename Key , typename NameFn > int getOrCreateGroup (ImporterContext & ctx, Map & map, const Key & key, NameFn && nameFn)
References ImporterContext::addGroup().
Referenced by scxt::akai_support::importAKP(), and scxt::sf2_support::importSF2().
importZoneLFO()
LFOHandle importZoneLFO (engine::Zone & zone, ImporterContext & ctx, int lfoSlot, const LFOArgs & a)
References Zone::modulatorStorage, LFOArgs::rate, LFOArgs::shape, and ImporterContext::software_error().
Referenced by scxt::sf2_support::importSF2().
importZoneLoop()
void importZoneLoop (engine::Zone & zone, ImporterContext & ctx, int variantIdx, const LoopArgs & a)
References LoopArgs::active, LoopArgs::direction, LoopArgs::endSamples, LoopArgs::fadeSamples, LoopArgs::mode, LoopArgs::startSamples, Zone::variantData, and Zone::Variants::variants.
Referenced by scxt::exs_support::importEXS(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), and scxt::sfz_support::importSFZ().
importZoneMapping()
void importZoneMapping (engine::Zone & zone, ImporterContext & ctx, const MappingArgs & a)
References MappingArgs::keyEnd, MappingArgs::keyFadeEnd, MappingArgs::keyFadeStart, MappingArgs::keyStart, Zone::mapping, MappingArgs::pitchOffsetSemitones, Zone::ZoneMappingData::rootKey, MappingArgs::rootKey, ImporterContext::software_error(), MappingArgs::tracking, MappingArgs::velEnd, MappingArgs::velFadeEnd, MappingArgs::velFadeStart, and MappingArgs::velStart.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), and scxt::sfz_support::importSFZ().
addImportedModRoute()
int addImportedModRoute (engine::Zone & zone, ImporterContext & ctx, const ImportedModRoute & r)
References ImportedModRoute::active, Attack, ChannelAT, Decay, Delay, ImportedModRoute::depth, EG, EGTime, FilterParam, Hold, KeyTrack, ImportedTarget::kind, LFO, MidiCC, ModWheel, Zone::onRoutingChanged(), ImportedTarget::paramIdx, Pitch, PitchBend, PolyAT, ImportedTarget::procSlot, Release, ReleaseVelocity, Zone::routingTable, ImporterContext::software_error(), ImportedModRoute::source, Sustain, ImportedModRoute::target, Velocity, ImportedModRoute::via, ZoneAmplitude, and ZonePan.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), scxt::sfz_support::zoneEnvelopeMods(), scxt::sfz_support::zoneParamKeytrack(), and scxt::sfz_support::zoneParamMods().
centsToSemitones()
constexpr float centsToSemitones (float cents) constexpr
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::sf2_support::importSF2(), and scxt::sfz_support::zonePlayback().
centibelsToLinear()
float centibelsToLinear (double cB)
Referenced by scxt::sf2_support::importSF2().
sf2NormalizedPan()
float sf2NormalizedPan (int pan)
Referenced by scxt::sf2_support::importSF2().
dBToCubicAttenuation()
float dBToCubicAttenuation (float dB)
Referenced by scxt::exs_support::importEXS(), and scxt::sf2_support::importSF2().