shortcircuit-xt: scxt::sfz_support Namespace Reference
scxt::sfz_support Namespace Reference
Classes
struct SFZParser
Typedefs
using opCodeMap_t = std::map< std::string, std::pair< std::string, bool > >
Functions
bool exportSFZ (const fs::path &toFile, engine::Engine &e, int partNumber)
int parseMidiNote (const std::string &s, int offset)
std::optional< std::string > consumeOpcode (opCodeMap_t &opCodes, const std::string &key)
void zoneGeometry (std::unique_ptr< engine::Zone > &zn, opCodeMap_t &opCodes, int &loadInfo, const std::function< void(const std::string &, const std::string &)> &onError, int octaveOffset)
void zonePlayback (std::unique_ptr< engine::Zone > &zn, opCodeMap_t &opCodes)
import_support::LoopArgs zoneLoopParse (opCodeMap_t &opCodes, int &loadInfo)
void zoneEnvelope (std::unique_ptr< engine::Zone > &zn, import_support::ImporterContext &ctx, opCodeMap_t &opCodes, int slot, const std::string &prefix)
import_support::FilterHandle zoneFilter (std::unique_ptr< engine::Zone > &zn, import_support::ImporterContext &ctx, opCodeMap_t &opCodes, std::set< std::string > &reportedFilTypes)
std::optional< import_support::ImportedSource > sfzSourceForSuffix (const std::string &name, const std::string &prefix, import_support::ImporterContext &ctx)
void zoneParamKeytrack (opCodeMap_t &opCodes, import_support::ImporterContext &ctx, engine::Zone &zn, const std::string &prefix, const std::function< import_support::ImportedTarget()> &targetMaker, const std::function< float(float)> &perKeyToDepth)
void zoneParamMods (opCodeMap_t &opCodes, import_support::ImporterContext &ctx, engine::Zone &zn, const std::string &prefix, const std::function< import_support::ImportedTarget()> &targetMaker, const std::function< float(float)> &valueToDepth)
float egNormToSeconds (float norm)
float egSecondsToNorm (float secs)
float egSecondsDeltaToDepth (float baseNorm, float deltaSec)
void zoneEnvelopeMods (opCodeMap_t &opCodes, import_support::ImporterContext &ctx, engine::Zone &zn, const std::string &prefix, int egSlot)
bool importSFZ (const fs::path &f, engine::Engine &e)
Typedef Documentation
opCodeMap_t
using opCodeMap_t = std::map<std::string, std::pair<std::string, bool> >
Function Documentation
exportSFZ()
bool exportSFZ (const fs::path & toFile, engine::Engine & e, int partNumber)
References scxt::patch_io::collectSamplesInto(), Engine::getPatch(), Zone::LOOP_WHILE_GATED, RAISE_ERROR_ENGINE, and scxt::dsp::twentyFiveSecondExpTable.
Referenced by scxt::messaging::client::doSavePart().
parseMidiNote()
int parseMidiNote (const std::string & s, int offset)
Referenced by zoneGeometry(), and zoneParamKeytrack().
consumeOpcode()
std::optional< std::string > consumeOpcode (opCodeMap_t & opCodes, const std::string & key)
Referenced by importSFZ(), zoneEnvelope(), zoneEnvelopeMods(), zoneFilter(), zoneGeometry(), zoneLoopParse(), zoneParamKeytrack(), zoneParamMods(), and zonePlayback().
zoneGeometry()
void zoneGeometry (std::unique_ptr< engine::Zone > & zn, opCodeMap_t & opCodes, int & loadInfo, const std::function< void(const std::string &, const std::string &)> & onError, int octaveOffset)
References consumeOpcode(), and parseMidiNote().
Referenced by importSFZ().
zonePlayback()
void zonePlayback (std::unique_ptr< engine::Zone > & zn, opCodeMap_t & opCodes)
References scxt::import_support::centsToSemitones(), and consumeOpcode().
Referenced by importSFZ().
zoneLoopParse()
import_support::LoopArgs zoneLoopParse (opCodeMap_t & opCodes, int & loadInfo)
References LoopArgs::active, consumeOpcode(), LoopArgs::endSamples, Zone::LOOP_DURING_VOICE, LoopArgs::mode, SCLOG_IF, and LoopArgs::startSamples.
Referenced by importSFZ().
zoneEnvelope()
void zoneEnvelope (std::unique_ptr< engine::Zone > & zn, import_support::ImporterContext & ctx, opCodeMap_t & opCodes, int slot, const std::string & prefix)
References EnvelopeArgs::attackSeconds, consumeOpcode(), EnvelopeArgs::decaySeconds, EnvelopeArgs::decayShape, EnvelopeArgs::delaySeconds, EnvelopeArgs::holdSeconds, scxt::import_support::importZoneEnvelope(), EnvelopeArgs::releaseSeconds, EnvelopeArgs::releaseShape, and EnvelopeArgs::sustainLevel.
Referenced by importSFZ().
zoneFilter()
import_support::FilterHandle zoneFilter (std::unique_ptr< engine::Zone > & zn, import_support::ImporterContext & ctx, opCodeMap_t & opCodes, std::set< std::string > & reportedFilTypes)
References scxt::import_support::Allpass, scxt::import_support::BP12, scxt::import_support::BP6, scxt::import_support::Comb, consumeOpcode(), scxt::import_support::HP12, scxt::import_support::HP24, scxt::import_support::HP36, scxt::import_support::HP6, scxt::import_support::importZoneFilter(), scxt::import_support::LP12, scxt::import_support::LP24, scxt::import_support::LP36, scxt::import_support::LP6, scxt::import_support::Notch12, scxt::import_support::Other, scxt::import_support::Peak, and ImporterContext::unsupported().
Referenced by importSFZ().
sfzSourceForSuffix()
std::optional< import_support::ImportedSource > sfzSourceForSuffix (const std::string & name, const std::string & prefix, import_support::ImporterContext & ctx)
References ImportedSource::channelAT(), ImportedSource::midiCC(), ImportedSource::modWheel(), and ImporterContext::unsupported().
Referenced by zoneParamMods().
zoneParamKeytrack()
void zoneParamKeytrack (opCodeMap_t & opCodes, import_support::ImporterContext & ctx, engine::Zone & zn, const std::string & prefix, const std::function< import_support::ImportedTarget()> & targetMaker, const std::function< float(float)> & perKeyToDepth)
References scxt::import_support::addImportedModRoute(), consumeOpcode(), ImportedSource::keyTrack(), Zone::mapping, parseMidiNote(), Zone::ZoneMappingData::rootKey, and ImporterContext::unsupported().
Referenced by importSFZ().
zoneParamMods()
void zoneParamMods (opCodeMap_t & opCodes, import_support::ImporterContext & ctx, engine::Zone & zn, const std::string & prefix, const std::function< import_support::ImportedTarget()> & targetMaker, const std::function< float(float)> & valueToDepth)
References scxt::import_support::addImportedModRoute(), consumeOpcode(), and sfzSourceForSuffix().
Referenced by importSFZ().
egNormToSeconds()
float egNormToSeconds (float norm)
Referenced by egSecondsDeltaToDepth().
egSecondsToNorm()
float egSecondsToNorm (float secs)
Referenced by egSecondsDeltaToDepth().
egSecondsDeltaToDepth()
float egSecondsDeltaToDepth (float baseNorm, float deltaSec)
References egNormToSeconds(), and egSecondsToNorm().
Referenced by zoneEnvelopeMods().
zoneEnvelopeMods()
void zoneEnvelopeMods (opCodeMap_t & opCodes, import_support::ImporterContext & ctx, engine::Zone & zn, const std::string & prefix, int egSlot)
References scxt::import_support::addImportedModRoute(), scxt::import_support::Attack, consumeOpcode(), scxt::import_support::Decay, scxt::import_support::Delay, egSecondsDeltaToDepth(), Zone::egStorage, ImportedTarget::egTime(), scxt::import_support::Hold, ImportedSource::midiCC(), ImportedSource::modWheel(), scxt::import_support::Release, scxt::import_support::Sustain, and ImportedSource::velocity().
Referenced by importSFZ().
importSFZ()
bool importSFZ (const fs::path & f, engine::Engine & e)
References ImporterContext::addGroup(), scxt::import_support::addImportedModRoute(), ImporterContext::addZoneToGroup(), Zone::attachToSample(), consumeOpcode(), SFZParser::Header::control, scxt::import_support::Cutoff, Zone::ENDPOINTS, Zone::engine, ImporterContext::fail(), ImportedTarget::filter(), Part::getGroup(), ImporterContext::getPart(), Engine::getSampleManager(), SFZParser::Header::group, scxt::import_support::importZoneLoop(), scxt::import_support::importZoneMapping(), scxt::isValidUtf(), Zone::ZoneMappingData::keyboardRange, ImporterContext::loadSampleFromDisk(), Zone::LOOP, Zone::MAPPING, Zone::mapping, SFZParser::onError, SFZParser::parse(), ImportedTarget::pitch(), ImporterContext::raise(), SFZParser::Header::region, scxt::import_support::Resonance, Zone::ZoneMappingData::rootKey, SCLOG_IF, ImportedSource::velocity(), Zone::ZoneMappingData::velocityRange, ImportedTarget::zoneAmplitude(), zoneEnvelope(), zoneEnvelopeMods(), zoneFilter(), zoneGeometry(), zoneLoopParse(), ImportedTarget::zonePan(), zoneParamKeytrack(), zoneParamMods(), and zonePlayback().
Referenced by Engine::loadCompoundElementIntoSelectedPartAndGroup(), and Engine::loadSampleIntoSelectedPartAndGroup().