shortcircuit-xt: scxt::messaging::client Namespace Reference
scxt::messaging::client Namespace Reference
Namespaces
namespace detail
Classes
struct ClientToSerializationType
struct DebugActions
struct SerializationToClientType
Typedefs
using previewBrowserSamplePayload_t = std::tuple< bool, std::string >
typedef uint8_t unimpl_t
using debugResponse_t = std::map< std::string, std::string >
using unstreamEngineStatePayload_t = std::string
using stopSounds_t = bool
using activityNotificationPayload_t = std::pair< int, std::string >
using groupOutputInfoUpdate_t = std::pair< bool, engine::Group::GroupOutputInfo >
typedef std::tuple< bool, int, bool, modulation::modulators::AdsrStorage > adsrViewResponsePayload_t
typedef std::pair< std::string, std::string > s2cError_t
typedef std::tuple< int32_t, float, bool > noteOnOff_t
using macroFullState_t = std::tuple< int16_t, int16_t, engine::Macro >
using macroValue_t = std::tuple< int16_t, int16_t, float >
using macroBeginEndEdit_t = std::tuple< bool, int16_t, int16_t >
using resolveSamplePayload_t = std::tuple< engine::MissingResolutionWorkItem, std::string >
using busEffectFullData_t = std::tuple< int, int, std::pair< std::array< sst::basic_blocks::params::ParamMetaData, engine::BusEffectStorage::maxBusEffectParams >, engine::BusEffectStorage > >
using busSendData_t = std::tuple< int, engine::Bus::BusSendStorage >
using setBusEffectToType_t = std::tuple< int, int, int >
using setBusEffectStorage_t = std::tuple< int, int, engine::BusEffectStorage >
using setBusSendStorage_t = std::tuple< int, engine::Bus::BusSendStorage >
typedef std::tuple< int, voice::modulation::Matrix::RoutingTable::Routing, bool > zoneRoutingRowPayload_t
typedef std::tuple< int, modulation::GroupMatrix::RoutingTable::Routing, bool > updateGroupRoutingRowPayload_t
typedef std::tuple< bool, bool, int, modulation::ModulatorStorage > indexedModulatorStorageUpdate_t
using partConfigurationPayload_t = std::pair< int16_t, scxt::engine::Part::PartConfiguration >
using loadPartIntoPayload_t = std::tuple< std::string, int16_t >
typedef std::tuple< bool, int, bool, dsp::processor::ProcessorControlDescription, dsp::processor::ProcessorStorage > processorDataResponsePayload_t
typedef std::tuple< int, int, std::string, std::set< int32_t > > processorMismatchPayload_t
typedef std::tuple< bool, int32_t, int32_t > setProcessorPayload_t
typedef std::pair< int32_t, int32_t > processorPair_t
typedef std::tuple< std::optional< selection::SelectionManager::ZoneAddress >, selection::SelectionManager::selectedZones_t, selection::SelectionManager::selectedZones_t > selectedStateMessage_t
using updateOther_t = std::pair< std::string, std::string >
using editGestureFor_t = bool
using addSampleWithRange_t = std::tuple< std::string, int, int, int, int, int >
using zoneAddressFromTo_t = std::pair< selection::SelectionManager::ZoneAddress, selection::SelectionManager::ZoneAddress >
typedef std::tuple< bool, engine::Zone::ZoneMappingData > mappingSelectedZoneViewResposne_t
typedef std::tuple< bool, engine::Zone::Variants > sampleSelectedZoneViewResposne_t
using updateLeadZoneSingleVariantPayload_t = std::tuple< size_t, engine::Zone::SingleVariant >
using normalizeVariantAmplitudePayload_t = std::tuple< size_t, bool >
using clearVariantAmplitudeNormalizationPayload_t = size_t
using zoneOutputInfoUpdate_t = std::pair< bool, engine::Zone::ZoneOutputInfo >
using addBlankZonePayload_t = std::array< int, 6 >
using deleteVariantPayload_t = int
Enumerations
enum ClientToSerializationMessagesIds {
c2s_register_client , c2s_reset_engine , c2s_unstream_engine_state , c2s_save_multi ,
c2s_save_selected_part , c2s_load_multi , c2s_load_part_into , c2s_apply_select_action ,
c2s_apply_multi_select_action , c2s_select_part , c2s_begin_edit , c2s_end_edit ,
c2s_update_zone_or_group_eg_float_value , c2s_update_zone_or_group_modstorage_float_value , c2s_update_zone_or_group_modstorage_bool_value , c2s_update_zone_or_group_modstorage_int16_t_value ,
c2s_update_lead_zone_mapping , c2s_update_zone_mapping_float , c2s_update_zone_mapping_int16_t , c2s_update_lead_zone_single_variant ,
c2s_update_zone_variants_int16_t , c2s_normalize_variant_amplitude , c2s_clear_variant_amplitude_normalization , c2s_delete_variant ,
c2s_update_zone_output_float_value , c2s_update_zone_output_int16_t_value , c2s_update_zone_output_int16_t_value_then_refresh , c2s_update_zone_routing_row ,
c2s_update_group_routing_row , c2s_update_group_output_float_value , c2s_update_group_output_int16_t_value , c2s_update_group_output_bool_value ,
c2s_update_group_output_info_polyphony , c2s_update_group_trigger_conditions , c2s_request_zone_data_refresh , c2s_request_pgz_structure ,
c2s_update_single_processor_float_value , c2s_update_single_processor_bool_value , c2s_update_single_processor_int32_t_value , c2s_set_processor_type ,
c2s_copy_processor_lead_to_all , c2s_swap_zone_processors , c2s_swap_group_processors , c2s_add_sample ,
c2s_add_sample_with_range , c2s_add_sample_in_zone , c2s_add_compound_element_with_range , c2s_add_compound_element_in_zone ,
c2s_create_group , c2s_move_zone , c2s_delete_zone , c2s_duplicate_zone ,
c2s_copy_zone , c2s_paste_zone , c2s_add_blank_zone , c2s_delete_selected_zones ,
c2s_delete_group , c2s_clear_part , c2s_rename_zone , c2s_rename_group ,
c2s_set_tuning_mode , c2s_noteonoff , c2s_initialize_mixer , c2s_set_mixer_effect ,
c2s_set_mixer_effect_storage , c2s_set_mixer_send_storage , c2s_add_browser_device_location , c2s_remove_browser_device_location ,
c2s_preview_browser_sample , c2s_request_debug_action , c2s_silence_engine , c2s_set_macro_full_state ,
c2s_set_macro_value , c2s_request_host_callback , c2s_macro_begin_end_edit , c2s_set_othertab_selection ,
c2s_send_full_part_config , c2s_resolve_sample , c2s_activate_next_part , c2s_deactivate_part ,
num_clientToSerializationMessages
}
These IDs are used inside a session only and are not streamed, so add whatever you want as long as (1) you keep them contig (so don't assign values) and (2) the num_ enum is the last one.
enum SerializationToClientMessageIds {
s2c_report_error , s2c_send_initial_metadata , s2c_send_debug_info , s2c_send_activity_notification ,
s2c_engine_status , s2c_update_group_or_zone_adsr_view , s2c_respond_zone_mapping , s2c_respond_zone_samples ,
s2c_send_pgz_structure , s2c_send_all_processor_descriptions , s2c_update_zone_matrix_metadata , s2c_update_zone_matrix ,
s2c_update_group_matrix_metadata , s2c_update_group_matrix , s2c_update_group_or_zone_individual_modulator_storage , s2c_update_zone_output_info ,
s2c_update_group_output_info , s2c_send_group_trigger_conditions , s2c_respond_single_processor_metadata_and_data , s2c_notify_mismatched_processors_for_zone ,
s2c_send_part_configuration , s2c_send_selected_part , s2c_send_selected_group_zone_mapping_summary , s2c_send_selection_state ,
s2c_send_othertab_selection , s2c_bus_effect_full_data , s2c_bus_send_data , s2c_refresh_browser ,
s2c_update_macro_full_state , s2c_update_macro_value , s2c_send_missing_resolution_workitem_list , num_serializationToClientMessages
}
Functions
void doAddBrowserDeviceLocation (const fs::path &p, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddBrowserDeviceLocation, c2s_add_browser_device_location, std::string, doAddBrowserDeviceLocation(fs::path(fs::u8path(payload)), engine, cont))
void doRemoveBrowserDeviceLocation (const fs::path &p, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (RemoveBrowserDeviceLocation, c2s_remove_browser_device_location, std::string, doRemoveBrowserDeviceLocation(fs::path(fs::u8path(payload)), engine, cont))
void doPreviewBrowserSample (const previewBrowserSamplePayload_t &p, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (PreviewBrowserSample, c2s_preview_browser_sample, previewBrowserSamplePayload_t, doPreviewBrowserSample(payload, engine, cont))
bool cacheSerializationMessagesAbsentClient (SerializationToClientMessageIds id)
template<typename T >
void clientSendToSerialization (const T &message, MessageController &mc)
template<typename T >
void serializationSendToClient (SerializationToClientMessageIds id, const T &payload, messaging::MessageController &mc)
void serializationThreadExecuteClientMessage (const std::string &msgView, engine::Engine &e, MessageController &mc)
template<typename Client >
void clientThreadExecuteSerializationMessage (const std::string &msgView, Client *c)
SERIAL_TO_CLIENT (DebugInfoGenerated, s2c_send_debug_info, debugResponse_t, onDebugInfoGenerated)
template<template< typename... > class... Transformers, template< typename... > class Traits>
void dbto_pretty_stream (std::ostream &os, const tao::json::basic_value< Traits > &v)
void doDebugAction (const std::string &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (RequestDebugAction, c2s_request_debug_action, std::string, doDebugAction(payload, engine, cont))
SERIAL_TO_CLIENT (EngineStatusUpdate, s2c_engine_status, engine::Engine::EngineStatusMessage, onEngineStatus)
void doUnstreamEngineState (const unstreamEngineStatePayload_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UnstreamEngineState, c2s_unstream_engine_state, unstreamEngineStatePayload_t, doUnstreamEngineState(payload, engine, cont))
void stopSoundsMessage (const stopSounds_t &payload, messaging::MessageController &cont)
CLIENT_TO_SERIAL (StopSounds, c2s_silence_engine, stopSounds_t, stopSoundsMessage(payload, cont))
SERIAL_TO_CLIENT (SendActivityNotification, s2c_send_activity_notification, activityNotificationPayload_t, onActivityNotification)
SERIAL_TO_CLIENT (GroupOutputInfoUpdated, s2c_update_group_output_info, groupOutputInfoUpdate_t, onGroupOutputInfoUpdated)
SERIAL_TO_CLIENT (SendGroupTriggerConditions, s2c_send_group_trigger_conditions, scxt::engine::GroupTriggerConditions, onGroupTriggerConditions) CLIENT_TO_SERIAL_CONSTRAINED(UpdateGroupOutputFloatValue
CLIENT_TO_SERIAL_CONSTRAINED (UpdateGroupOutputInt16TValue, c2s_update_group_output_int16_t_value, detail::diffMsg_t< int16_t >, engine::Group::GroupOutputInfo, detail::updateGroupMemberValue(&engine::Group::outputInfo, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateGroupOutputBoolValue, c2s_update_group_output_bool_value, detail::diffMsg_t< bool >, engine::Group::GroupOutputInfo, detail::updateGroupMemberValue(&engine::Group::outputInfo, payload, engine, cont))
void doUpdateGroupTriggerConditions (const engine::GroupTriggerConditions &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UpdateGroupTriggerConditions, c2s_update_group_trigger_conditions, scxt::engine::GroupTriggerConditions, doUpdateGroupTriggerConditions(payload, engine, cont))
void doUpdateGroupOutputInfoPolyphony (const scxt::engine::Group::GroupOutputInfo payload, const engine::Engine &engine, messaging::MessageController &cont)
CLIENT_TO_SERIAL (UpdateGroupOutputInfoPolyphony, c2s_update_group_output_info_polyphony, scxt::engine::Group::GroupOutputInfo, doUpdateGroupOutputInfoPolyphony(payload, engine, cont))
SERIAL_TO_CLIENT (AdsrGroupOrZoneUpdate, s2c_update_group_or_zone_adsr_view, adsrViewResponsePayload_t, onGroupOrZoneEnvelopeUpdated)
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupEGFloatValue, c2s_update_zone_or_group_eg_float_value, detail::indexedZoneOrGroupDiffMsg_t< float >, modulation::modulators::AdsrStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::egStorage, &engine::Group::gegStorage, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageFloatValue, c2s_update_zone_or_group_modstorage_float_value, detail::indexedZoneOrGroupDiffMsg_t< float >, modulation::ModulatorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::modulatorStorage, &engine::Group::modulatorStorage, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageBoolValue, c2s_update_zone_or_group_modstorage_bool_value, detail::indexedZoneOrGroupDiffMsg_t< bool >, modulation::ModulatorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::modulatorStorage, &engine::Group::modulatorStorage, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageInt16TValue, c2s_update_zone_or_group_modstorage_int16_t_value, detail::indexedZoneOrGroupDiffMsg_t< int16_t >, modulation::ModulatorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::modulatorStorage, &engine::Group::modulatorStorage, payload, engine, cont, [payload](auto &eng) { auto forZone=std::get< 0 >(payload);if(forZone) { auto lz=eng.getSelectionManager() ->currentLeadZone(eng);if(lz.has_value()) { eng.getSelectionManager() ->sendDisplayDataForZonesBasedOnLead(lz->part, lz->group, lz->zone);} } else { auto lg=eng.getSelectionManager() ->currentLeadGroup(eng);} }, nullptr, [payload](auto &engine, const auto &gs) { auto idx=std::get< 1 >(payload);assert(engine.getMessageController() ->threadingChecker.isAudioThread());for(auto[p, g, z] :gs) { auto &grp=engine.getPatch() ->getPart(p) ->getGroup(g);grp->resetLFOs(idx);grp->rePrepareAndBindGroupMatrix();} })) using renameGroupZonePayload_t
void doRenameGroup (const renameGroupZonePayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (RenameGroup, c2s_rename_group, renameGroupZonePayload_t, doRenameGroup(payload, engine, cont))
void doRenameZone (const renameGroupZonePayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (RenameZone, c2s_rename_zone, renameGroupZonePayload_t, doRenameZone(payload, engine, cont))
SERIAL_TO_CLIENT (ReportError, s2c_report_error, s2cError_t, onErrorFromEngine)
CLIENT_TO_SERIAL (SetTuningMode, c2s_set_tuning_mode, int32_t, engine.midikeyRetuner.setTuningMode((tuning::MidikeyRetuner::TuningMode) payload))
void processMidiFromGUI (const noteOnOff_t &g, const engine::Engine &engine, MessageController &cont)
void doHostCallback (uint64_t pl, MessageController &cont)
CLIENT_TO_SERIAL (RequestHostCallback, c2s_request_host_callback, uint64_t, doHostCallback(payload, cont))
void doResetEngine (bool pl, engine::Engine &e, MessageController &cont)
CLIENT_TO_SERIAL (ResetEngine, c2s_reset_engine, bool, doResetEngine(payload, engine, cont))
SERIAL_TO_CLIENT (UpdateMacroFullState, s2c_update_macro_full_state, macroFullState_t, onMacroFullState)
SERIAL_TO_CLIENT (UpdateMacroValue, s2c_update_macro_value, macroValue_t, onMacroValue)
void updateMacroFullState (const macroFullState_t &t, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (SetMacroFullState, c2s_set_macro_full_state, macroFullState_t, updateMacroFullState(payload, engine, cont))
void updateMacroValue (const macroValue_t &t, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (SetMacroValue, c2s_set_macro_value, macroValue_t, updateMacroValue(payload, engine, cont))
void doMacroBeginEndEdit (const macroBeginEndEdit_t &payload, const engine::Engine &e, messaging::MessageController &cont)
CLIENT_TO_SERIAL (MacroBeginEndEdit, c2s_macro_begin_end_edit, macroBeginEndEdit_t, doMacroBeginEndEdit(payload, engine, cont))
SERIAL_TO_CLIENT (SendMissingResolutionWorkItemList, s2c_send_missing_resolution_workitem_list, std::vector< engine::MissingResolutionWorkItem >, onMissingResolutionWorkItemList)
void doResolveSample (const resolveSamplePayload_t &payload, engine::Engine &e, messaging::MessageController &cont)
CLIENT_TO_SERIAL (ResolveSample, c2s_resolve_sample, resolveSamplePayload_t, doResolveSample(payload, engine, cont))
SERIAL_TO_CLIENT (SendBusEffectFullData, s2c_bus_effect_full_data, busEffectFullData_t, onMixerBusEffectFullData)
SERIAL_TO_CLIENT (SendBusSendData, s2c_bus_send_data, busSendData_t, onMixerBusSendData)
void setBusEffectToType (const setBusEffectToType_t &payload, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SetBusEffectToType, c2s_set_mixer_effect, setBusEffectToType_t, setBusEffectToType(payload, cont))
void setBusEffectStorage (const setBusEffectStorage_t &payload, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SetBusEffectStorage, c2s_set_mixer_effect_storage, setBusEffectStorage_t, setBusEffectStorage(payload, cont))
void setBusSendStorage (const setBusSendStorage_t &payload, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SetBusSendStorage, c2s_set_mixer_send_storage, setBusSendStorage_t, setBusSendStorage(payload, cont))
SERIAL_TO_CLIENT (UpdateZoneVoiceMatrixMetadata, s2c_update_zone_matrix_metadata, voice::modulation::voiceMatrixMetadata_t, onZoneVoiceMatrixMetadata)
SERIAL_TO_CLIENT (UpdateZoneVoiceMatrix, s2c_update_zone_matrix, voice::modulation::Matrix::RoutingTable, onZoneVoiceMatrix)
SERIAL_TO_CLIENT (UpdateGroupMatrixMetadata, s2c_update_group_matrix_metadata, scxt::modulation::groupMatrixMetadata_t, onGroupMatrixMetadata)
SERIAL_TO_CLIENT (UpdateGroupMatrix, s2c_update_group_matrix, modulation::GroupMatrix::RoutingTable, onGroupMatrix)
void doUpdateZoneRoutingRow (const zoneRoutingRowPayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UpdateZoneRoutingRow, c2s_update_zone_routing_row, zoneRoutingRowPayload_t, doUpdateZoneRoutingRow(payload, engine, cont))
void doUpdateGroupRoutingRow (const updateGroupRoutingRowPayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UpdateGroupRoutingRow, c2s_update_group_routing_row, updateGroupRoutingRowPayload_t, doUpdateGroupRoutingRow(payload, engine, cont))
SERIAL_TO_CLIENT (UpdateZoneLfo, s2c_update_group_or_zone_individual_modulator_storage, indexedModulatorStorageUpdate_t, onGroupOrZoneModulatorStorageUpdated)
SERIAL_TO_CLIENT (SelectedPart, s2c_send_selected_part, int16_t, onSelectedPart)
SERIAL_TO_CLIENT (SelectedGroupZoneMappingSummary, s2c_send_selected_group_zone_mapping_summary, engine::Part::zoneMappingSummary_t, onGroupZoneMappingSummary)
SERIAL_TO_CLIENT (SendPartConfiguration, s2c_send_part_configuration, partConfigurationPayload_t, onPartConfiguration)
void updatePartFullConfig (const partConfigurationPayload_t &p, const engine::Engine &e, messaging::MessageController &cont)
CLIENT_TO_SERIAL (UpdatePartFullConfig, c2s_send_full_part_config, partConfigurationPayload_t, updatePartFullConfig(payload, engine, cont))
void doSaveMulti (const std::string &s, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (SaveMulti, c2s_save_multi, std::string, doSaveMulti(payload, engine, cont))
CLIENT_TO_SERIAL (LoadMulti, c2s_load_multi, std::string, patch_io::loadMulti(fs::path(fs::u8path(payload)), engine))
void doSaveSelectedPart (const std::string &s, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (SaveSelectedPart, c2s_save_selected_part, std::string, doSaveSelectedPart(payload, engine, cont))
void doLoadPartInto (const loadPartIntoPayload_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (LoadPartInto, c2s_load_part_into, loadPartIntoPayload_t, doLoadPartInto(payload, engine, cont))
SERIAL_TO_CLIENT (ProcessorMetadataAndData, s2c_respond_single_processor_metadata_and_data, processorDataResponsePayload_t, onGroupOrZoneProcessorDataAndMetadata)
SERIAL_TO_CLIENT (ProcessorsMismatched, s2c_notify_mismatched_processors_for_zone, processorMismatchPayload_t, onZoneProcessorDataMismatch)
void setProcessorType (const setProcessorPayload_t &whichToType, const engine::Engine &engine, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SetSelectedProcessorType, c2s_set_processor_type, setProcessorPayload_t, setProcessorType(payload, engine, cont))
CLIENT_TO_SERIAL (CopyProcessorLeadToAll, c2s_copy_processor_lead_to_all, int, engine.getSelectionManager() ->copyZoneProcessorLeadToAll(payload))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorFloatValue, c2s_update_single_processor_float_value, detail::indexedZoneOrGroupDiffMsg_t< float >, dsp::processor::ProcessorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::processorStorage, &engine::Group::processorStorage, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorInt32TValue, c2s_update_single_processor_int32_t_value, detail::indexedZoneOrGroupDiffMsg_t< int32_t >, dsp::processor::ProcessorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::processorStorage, &engine::Group::processorStorage, payload, engine, cont, nullptr, [payload](auto &e, auto &sz) { auto wp=std::get< 1 >(payload);for(const auto &a :sz) { const auto &z=e.getPatch() ->getPart(a.part) ->getGroup(a.group) ->getZone(a.zone);z->checkOrAdjustIntConsistency(wp);} }, [payload](auto &e, auto &sg) { auto wp=std::get< 1 >(payload);for(const auto &a :sg) { const auto &g=e.getPatch() ->getPart(a.part) ->getGroup(a.group);g->checkOrAdjustIntConsistency(wp);} }))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorBoolValue, c2s_update_single_processor_bool_value, detail::indexedZoneOrGroupDiffMsg_t< bool >, dsp::processor::ProcessorStorage, detail::updateZoneOrGroupIndexedMemberValue(&engine::Zone::processorStorage, &engine::Group::processorStorage, payload, engine, cont, nullptr, [payload](auto &e, auto &sz) { auto wp=std::get< 1 >(payload);for(const auto &a :sz) { const auto &z=e.getPatch() ->getPart(a.part) ->getGroup(a.group) ->getZone(a.zone);z->checkOrAdjustBoolConsistency(wp);} }, [payload](auto &e, auto &sg) { auto wp=std::get< 1 >(payload);for(const auto &a :sg) { const auto &g=e.getPatch() ->getPart(a.part) ->getGroup(a.group);g->checkOrAdjustBoolConsistency(wp);} }))
void swapZoneProcessors (const processorPair_t &whichToType, const engine::Engine &engine, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SwapZoneProcessors, c2s_swap_zone_processors, processorPair_t, swapZoneProcessors(payload, engine, cont))
void swapGroupProcessors (const processorPair_t &whichToType, const engine::Engine &engine, messaging::MessageController &cont)
CLIENT_TO_SERIAL (SwapGroupProcessors, c2s_swap_group_processors, processorPair_t, swapGroupProcessors(payload, engine, cont))
void doApplySelectAction (const selection::SelectionManager::SelectActionContents &za, const engine::Engine &engine)
CLIENT_TO_SERIAL (ApplySelectAction, c2s_apply_select_action, selection::SelectionManager::SelectActionContents, doApplySelectAction(payload, engine))
void doApplyMultiSelectAction (const std::vector< selection::SelectionManager::SelectActionContents > &za, const engine::Engine &engine)
CLIENT_TO_SERIAL (ApplyMultiSelectAction, c2s_apply_multi_select_action, std::vector< selection::SelectionManager::SelectActionContents >, doApplyMultiSelectAction(payload, engine))
CLIENT_TO_SERIAL (SelectPart, c2s_select_part, int16_t, engine.getSelectionManager() ->selectPart(payload))
SERIAL_TO_CLIENT (SetSelectionState, s2c_send_selection_state, selectedStateMessage_t, onSelectionState)
SERIAL_TO_CLIENT (SetOtherTabSelection, s2c_send_othertab_selection, scxt::selection::SelectionManager::otherTabSelection_t, onOtherTabSelection)
void doUpdateOtherTabSelection (const updateOther_t &pl, const engine::Engine &engine)
CLIENT_TO_SERIAL (UpdateOtherTabSelection, c2s_set_othertab_selection, updateOther_t, doUpdateOtherTabSelection(payload, engine))
void doBeginEndEdit (bool isBegin, const editGestureFor_t &payload, const engine::Engine &engine, messaging::MessageController &cont)
CLIENT_TO_SERIAL (BeginEdit, c2s_begin_edit, editGestureFor_t, doBeginEndEdit(true, payload, engine, cont))
CLIENT_TO_SERIAL (EndEdit, c2s_end_edit, editGestureFor_t, doBeginEndEdit(false, payload, engine, cont))
void pgzSerialSide (const int &partNum, const engine::Engine &engine, MessageController &cont)
CLIENT_SERIAL_REQUEST_RESPONSE (PartGroupZoneStructure, c2s_request_pgz_structure, int32_t, s2c_send_pgz_structure, engine::Engine::pgzStructure_t, pgzSerialSide(payload, engine, cont), onStructureUpdated)
SERIAL_TO_CLIENT (SendAllProcessorDescriptions, s2c_send_all_processor_descriptions, std::vector< dsp::processor::ProcessorDescription >, onAllProcessorDescriptions)
void doRegisterClient (engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (RegisterClient, c2s_register_client, bool, doRegisterClient(engine, cont))
void addSample (const std::string &payload, engine::Engine &engine, MessageController &cont)
void addSampleWithRange (const addSampleWithRange_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddSampleWithRange, c2s_add_sample_with_range, addSampleWithRange_t, addSampleWithRange(payload, engine, cont);) using addCompoundElementWithRange_t
void addCompoundElementWithRange (const addCompoundElementWithRange_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddCompoundElementWithRange, c2s_add_compound_element_with_range, addCompoundElementWithRange_t, addCompoundElementWithRange(payload, engine, cont);) using addSampleInZone_t
void addSampleInZone (const addSampleInZone_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddSampleInZone, c2s_add_sample_in_zone, addSampleInZone_t, addSampleInZone(payload, engine, cont);) using addCompoundElementInZone_t
void addCompoundElementInZone (const addCompoundElementInZone_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddCompoundElementInZone, c2s_add_compound_element_in_zone, addCompoundElementInZone_t, addCompoundElementInZone(payload, engine, cont);) inline void createGroupIn(int partNumber
SCLOG_IF (groupZoneMutation, "Creating group in part "<< partNumber)
cont scheduleAudioThreadCallbackUnderStructureLock ([p=partNumber](auto &e) { e.getPatch() ->getPart(p) ->addGroup();}, [p=partNumber](auto &engine) { SCLOG_IF(groupZoneMutation, "Responding with part group zone structure in "<< p);serializationSendToClient(s2c_send_pgz_structure, engine.getPartGroupZoneStructure(), *(engine.getMessageController()));serializationSendToClient(s2c_send_selected_group_zone_mapping_summary, engine.getPatch() ->getPart(p) ->getZoneMappingSummary(), *(engine.getMessageController()));if(engine.getSelectionManager() ->currentlySelectedZones().empty()) { SCLOG_IF(selection, "Empty selection when creating group in "<< p);int32_t g=engine.getPatch() ->getPart(p) ->getGroups().size() - 1;engine.getSelectionManager() ->selectAction(selection::SelectionManager::SelectActionContents(p, g, -1, true, true, true));} })
CLIENT_TO_SERIAL (CreateGroup, c2s_create_group, int, createGroupIn(payload, engine, cont))
void removeZone (const selection::SelectionManager::ZoneAddress &a, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (DeleteZone, c2s_delete_zone, selection::SelectionManager::ZoneAddress, removeZone(payload, engine, cont))
CLIENT_TO_SERIAL (DuplicateZone, c2s_duplicate_zone, selection::SelectionManager::ZoneAddress, engine.duplicateZone(payload))
CLIENT_TO_SERIAL (CopyZone, c2s_copy_zone, selection::SelectionManager::ZoneAddress, engine.copyZone(payload))
CLIENT_TO_SERIAL (PasteZone, c2s_paste_zone, selection::SelectionManager::ZoneAddress, engine.pasteZone(payload))
void removeSelectedZones (const bool &, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (DeleteAllSelectedZones, c2s_delete_selected_zones, bool, removeSelectedZones(payload, engine, cont))
void removeGroup (const selection::SelectionManager::ZoneAddress &a, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (DeleteGroup, c2s_delete_group, selection::SelectionManager::ZoneAddress, removeGroup(payload, engine, cont))
void clearPart (const int p, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (ClearPart, c2s_clear_part, int, clearPart(payload, engine, cont))
void moveZoneFromTo (const zoneAddressFromTo_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (MoveZoneFromTo, c2s_move_zone, zoneAddressFromTo_t, moveZoneFromTo(payload, engine, cont))
void doActivateNextPart (messaging::MessageController &cont)
CLIENT_TO_SERIAL (ActivateNextPart, c2s_activate_next_part, bool, doActivateNextPart(cont))
void doDeactivatePart (int part, messaging::MessageController &cont)
CLIENT_TO_SERIAL (DeactivatePart, c2s_deactivate_part, int32_t, doDeactivatePart(payload, cont))
void doRequestZoneDataRefresh (const engine::Engine &eng, messaging::MessageController &cont)
CLIENT_TO_SERIAL (RequestZoneDataRefresh, c2s_request_zone_data_refresh, bool, doRequestZoneDataRefresh(engine, cont))
SERIAL_TO_CLIENT (MappingSelectedZoneView, s2c_respond_zone_mapping, mappingSelectedZoneViewResposne_t, onMappingUpdated)
void doUpdateLeadZoneMapping (const engine::Zone::ZoneMappingData &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UpdateLeadZoneMapping, c2s_update_lead_zone_mapping, engine::Zone::ZoneMappingData, doUpdateLeadZoneMapping(payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneMappingFloatValue, c2s_update_zone_mapping_float, detail::diffMsg_t< float >, engine::Zone::ZoneMappingData, detail::updateZoneLeadMemberValue(&engine::Zone::mapping, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneMappingInt16TValue, c2s_update_zone_mapping_int16_t, detail::diffMsg_t< int16_t >, engine::Zone::ZoneMappingData, detail::updateZoneLeadMemberValue(&engine::Zone::mapping, payload, engine, cont, [](const auto &eng) { auto pt=eng.getSelectionManager() ->currentlySelectedPart(eng);serializationSendToClient(messaging::client::s2c_send_selected_group_zone_mapping_summary, eng.getPatch() ->getPart(pt) ->getZoneMappingSummary(), *(eng.getMessageController()));}))
SERIAL_TO_CLIENT (SampleSelectedZoneView, s2c_respond_zone_samples, sampleSelectedZoneViewResposne_t, onSamplesUpdated)
void doUpdateLeadZoneSingleVariant (const updateLeadZoneSingleVariantPayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (UpdateLeadZoneSingleVariant, c2s_update_lead_zone_single_variant, updateLeadZoneSingleVariantPayload_t, doUpdateLeadZoneSingleVariant(payload, engine, cont))
void doNormalizeVariantAmplitude (const normalizeVariantAmplitudePayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (NormalizeVariantAmplitude, c2s_normalize_variant_amplitude, normalizeVariantAmplitudePayload_t, doNormalizeVariantAmplitude(payload, engine, cont))
void doClearVariantAmplitudeNormalization (const clearVariantAmplitudeNormalizationPayload_t &payload, const engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (ClearVariantAmplitudeNormalization, c2s_clear_variant_amplitude_normalization, clearVariantAmplitudeNormalizationPayload_t, doClearVariantAmplitudeNormalization(payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneVariantsInt16TValue, c2s_update_zone_variants_int16_t, detail::diffMsg_t< int16_t >, engine::Zone::Variants, detail::updateZoneMemberValue(&engine::Zone::variantData, payload, engine, cont))
SERIAL_TO_CLIENT (ZoneOutputInfoUpdated, s2c_update_zone_output_info, zoneOutputInfoUpdate_t, onZoneOutputInfoUpdated)
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputFloatValue, c2s_update_zone_output_float_value, detail::diffMsg_t< float >, engine::Zone::ZoneOutputInfo, detail::updateZoneMemberValue(&engine::Zone::outputInfo, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputInt16TValue, c2s_update_zone_output_int16_t_value, detail::diffMsg_t< int16_t >, engine::Zone::ZoneOutputInfo, detail::updateZoneMemberValue(&engine::Zone::outputInfo, payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputInt16TValueThenRefresh, c2s_update_zone_output_int16_t_value_then_refresh, detail::diffMsg_t< int16_t >, engine::Zone::ZoneOutputInfo, detail::updateZoneMemberValue(&engine::Zone::outputInfo, payload, engine, cont, [](auto const &eng) { auto lz=eng.getSelectionManager() ->currentLeadZone(eng);if(lz.has_value()) { eng.getSelectionManager() ->sendDisplayDataForZonesBasedOnLead(lz->part, lz->group, lz->zone);} }))
void doAddBlankZone (const addBlankZonePayload_t &payload, engine::Engine &engine, MessageController &cont)
CLIENT_TO_SERIAL (AddBlankZone, c2s_add_blank_zone, addBlankZonePayload_t, doAddBlankZone(payload, engine, cont))
void doDeleteVariant (const deleteVariantPayload_t &payload, engine::Engine &engine, MessageController &cont)
Variables
engine::Engine & engine
engine::Engine MessageController & cont
Typedef Documentation
previewBrowserSamplePayload_t
using previewBrowserSamplePayload_t = std::tuple<bool, std::string>
unimpl_t
typedef uint8_t unimpl_t
debugResponse_t
using debugResponse_t = std::map<std::string, std::string>
unstreamEngineStatePayload_t
using unstreamEngineStatePayload_t = std::string
stopSounds_t
using stopSounds_t = bool
activityNotificationPayload_t
using activityNotificationPayload_t = std::pair<int, std::string>
groupOutputInfoUpdate_t
using groupOutputInfoUpdate_t = std::pair<bool, engine::Group::GroupOutputInfo>
adsrViewResponsePayload_t
typedef std::tuple<bool, int, bool, modulation::modulators::AdsrStorage> adsrViewResponsePayload_t
s2cError_t
typedef std::pair<std::string, std::string> s2cError_t
noteOnOff_t
typedef std::tuple<int32_t, float, bool> noteOnOff_t
macroFullState_t
using macroFullState_t = std::tuple<int16_t, int16_t, engine::Macro>
macroValue_t
using macroValue_t = std::tuple<int16_t, int16_t, float>
macroBeginEndEdit_t
using macroBeginEndEdit_t = std::tuple<bool, int16_t, int16_t>
resolveSamplePayload_t
using resolveSamplePayload_t = std::tuple<engine::MissingResolutionWorkItem, std::string>
busEffectFullData_t
using busEffectFullData_t = std::tuple<int, int, std::pair<std::array<sst::basic_blocks::params::ParamMetaData, engine::BusEffectStorage::maxBusEffectParams>, engine::BusEffectStorage> >
busSendData_t
using busSendData_t = std::tuple<int, engine::Bus::BusSendStorage>
setBusEffectToType_t
using setBusEffectToType_t = std::tuple<int, int, int>
setBusEffectStorage_t
using setBusEffectStorage_t = std::tuple<int, int, engine::BusEffectStorage>
setBusSendStorage_t
using setBusSendStorage_t = std::tuple<int, engine::Bus::BusSendStorage>
zoneRoutingRowPayload_t
typedef std::tuple<int, voice::modulation::Matrix::RoutingTable::Routing, bool> zoneRoutingRowPayload_t
updateGroupRoutingRowPayload_t
typedef std::tuple<int, modulation::GroupMatrix::RoutingTable::Routing, bool> updateGroupRoutingRowPayload_t
indexedModulatorStorageUpdate_t
typedef std::tuple<bool, bool, int, modulation::ModulatorStorage> indexedModulatorStorageUpdate_t
partConfigurationPayload_t
using partConfigurationPayload_t = std::pair<int16_t, scxt::engine::Part::PartConfiguration>
loadPartIntoPayload_t
using loadPartIntoPayload_t = std::tuple<std::string, int16_t>
processorDataResponsePayload_t
typedef std::tuple<bool, int, bool, dsp::processor::ProcessorControlDescription, dsp::processor::ProcessorStorage> processorDataResponsePayload_t
processorMismatchPayload_t
typedef std::tuple<int, int, std::string, std::set<int32_t> > processorMismatchPayload_t
setProcessorPayload_t
typedef std::tuple<bool, int32_t, int32_t> setProcessorPayload_t
processorPair_t
typedef std::pair<int32_t, int32_t> processorPair_t
selectedStateMessage_t
typedef std::tuple<std::optional<selection::SelectionManager::ZoneAddress>, selection::SelectionManager::selectedZones_t, selection::SelectionManager::selectedZones_t> selectedStateMessage_t
updateOther_t
using updateOther_t = std::pair<std::string, std::string>
editGestureFor_t
using editGestureFor_t = bool
addSampleWithRange_t
using addSampleWithRange_t = std::tuple<std::string, int, int, int, int, int>
zoneAddressFromTo_t
using zoneAddressFromTo_t = std::pair<selection::SelectionManager::ZoneAddress, selection::SelectionManager::ZoneAddress>
mappingSelectedZoneViewResposne_t
typedef std::tuple<bool, engine::Zone::ZoneMappingData> mappingSelectedZoneViewResposne_t
sampleSelectedZoneViewResposne_t
typedef std::tuple<bool, engine::Zone::Variants> sampleSelectedZoneViewResposne_t
updateLeadZoneSingleVariantPayload_t
using updateLeadZoneSingleVariantPayload_t = std::tuple<size_t, engine::Zone::SingleVariant>
normalizeVariantAmplitudePayload_t
using normalizeVariantAmplitudePayload_t = std::tuple<size_t, bool>
clearVariantAmplitudeNormalizationPayload_t
using clearVariantAmplitudeNormalizationPayload_t = size_t
zoneOutputInfoUpdate_t
using zoneOutputInfoUpdate_t = std::pair<bool, engine::Zone::ZoneOutputInfo>
addBlankZonePayload_t
using addBlankZonePayload_t = std::array<int, 6>
deleteVariantPayload_t
using deleteVariantPayload_t = int
Enumeration Type Documentation
ClientToSerializationMessagesIds
enum ClientToSerializationMessagesIds
These IDs are used inside a session only and are not streamed, so add whatever you want as long as (1) you keep them contig (so don't assign values) and (2) the num_ enum is the last one.
These ids follow a naming convention which matches with the objects created in the CLIENT_TO_SERIAL.. and SERIAL_TO_CLIENT... macros used throughout messaging/client. That naming convention is
S2C:
Prefer the verb "Send", since S2C is sending authoritative state
Use the structure s2c_send_class_thing, for instance s2c_send_selection_state
Name the object a camelcase version of the enum without s2c, so for instance SendSelectionState
Make the SCXT Editor callback names onSelectionState
name the payloads as objectNamePayload_t so selectionStatePayload_t if the payload type is a custom type.
C2S:
Prefer the verb corresponding to the action like set, swap, create delete, etc. Do not use send in a C2S. Prefer set over update.
Class name follows per S2C above as does payload name
If an inline function is used to handle a message use the name 'doObjectName' so 'doSetZoneOrGroupModstorage`
Enumerator
c2s_register_client
c2s_reset_engine
c2s_unstream_engine_state
c2s_save_multi
c2s_save_selected_part
c2s_load_multi
c2s_load_part_into
c2s_apply_select_action
c2s_apply_multi_select_action
c2s_select_part
c2s_begin_edit
c2s_end_edit
c2s_update_zone_or_group_eg_float_value
c2s_update_zone_or_group_modstorage_float_value
c2s_update_zone_or_group_modstorage_bool_value
c2s_update_zone_or_group_modstorage_int16_t_value
c2s_update_lead_zone_mapping
c2s_update_zone_mapping_float
c2s_update_zone_mapping_int16_t
c2s_update_lead_zone_single_variant
c2s_update_zone_variants_int16_t
c2s_normalize_variant_amplitude
c2s_clear_variant_amplitude_normalization
c2s_delete_variant
c2s_update_zone_output_float_value
c2s_update_zone_output_int16_t_value
c2s_update_zone_output_int16_t_value_then_refresh
c2s_update_zone_routing_row
c2s_update_group_routing_row
c2s_update_group_output_float_value
c2s_update_group_output_int16_t_value
c2s_update_group_output_bool_value
c2s_update_group_output_info_polyphony
c2s_update_group_trigger_conditions
c2s_request_zone_data_refresh
c2s_request_pgz_structure
c2s_update_single_processor_float_value
c2s_update_single_processor_bool_value
c2s_update_single_processor_int32_t_value
c2s_set_processor_type
c2s_copy_processor_lead_to_all
c2s_swap_zone_processors
c2s_swap_group_processors
c2s_add_sample
c2s_add_sample_with_range
c2s_add_sample_in_zone
c2s_add_compound_element_with_range
c2s_add_compound_element_in_zone
c2s_create_group
c2s_move_zone
c2s_delete_zone
c2s_duplicate_zone
c2s_copy_zone
c2s_paste_zone
c2s_add_blank_zone
c2s_delete_selected_zones
c2s_delete_group
c2s_clear_part
c2s_rename_zone
c2s_rename_group
c2s_set_tuning_mode
c2s_noteonoff
c2s_initialize_mixer
c2s_set_mixer_effect
c2s_set_mixer_effect_storage
c2s_set_mixer_send_storage
c2s_add_browser_device_location
c2s_remove_browser_device_location
c2s_preview_browser_sample
c2s_request_debug_action
c2s_silence_engine
c2s_set_macro_full_state
c2s_set_macro_value
c2s_request_host_callback
c2s_macro_begin_end_edit
c2s_set_othertab_selection
c2s_send_full_part_config
c2s_resolve_sample
c2s_activate_next_part
c2s_deactivate_part
num_clientToSerializationMessages
SerializationToClientMessageIds
enum SerializationToClientMessageIds
Enumerator
s2c_report_error
s2c_send_initial_metadata
s2c_send_debug_info
s2c_send_activity_notification
s2c_engine_status
s2c_update_group_or_zone_adsr_view
s2c_respond_zone_mapping
s2c_respond_zone_samples
s2c_send_pgz_structure
s2c_send_all_processor_descriptions
s2c_update_zone_matrix_metadata
s2c_update_zone_matrix
s2c_update_group_matrix_metadata
s2c_update_group_matrix
s2c_update_group_or_zone_individual_modulator_storage
s2c_update_zone_output_info
s2c_update_group_output_info
s2c_send_group_trigger_conditions
s2c_respond_single_processor_metadata_and_data
s2c_notify_mismatched_processors_for_zone
s2c_send_part_configuration
s2c_send_selected_part
s2c_send_selected_group_zone_mapping_summary
s2c_send_selection_state
s2c_send_othertab_selection
s2c_bus_effect_full_data
s2c_bus_send_data
s2c_refresh_browser
s2c_update_macro_full_state
s2c_update_macro_value
s2c_send_missing_resolution_workitem_list
num_serializationToClientMessages
Function Documentation
doAddBrowserDeviceLocation()
void doAddBrowserDeviceLocation (const fs::path & p, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getBrowser(), s2c_refresh_browser, and serializationSendToClient().
CLIENT_TO_SERIAL() [1/59]
CLIENT_TO_SERIAL (AddBrowserDeviceLocation , c2s_add_browser_device_location , std::string , doAddBrowserDeviceLocation(fs::path(fs::u8path(payload)), engine, cont))
doRemoveBrowserDeviceLocation()
void doRemoveBrowserDeviceLocation (const fs::path & p, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getBrowser(), s2c_refresh_browser, and serializationSendToClient().
CLIENT_TO_SERIAL() [2/59]
CLIENT_TO_SERIAL (RemoveBrowserDeviceLocation , c2s_remove_browser_device_location , std::string , doRemoveBrowserDeviceLocation(fs::path(fs::u8path(payload)), engine, cont))
doPreviewBrowserSample()
void doPreviewBrowserSample (const previewBrowserSamplePayload_t & p, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSampleManager().
CLIENT_TO_SERIAL() [3/59]
CLIENT_TO_SERIAL (PreviewBrowserSample , c2s_preview_browser_sample , previewBrowserSamplePayload_t , doPreviewBrowserSample(payload, engine, cont))
cacheSerializationMessagesAbsentClient()
bool cacheSerializationMessagesAbsentClient (SerializationToClientMessageIds id)
References s2c_report_error.
Referenced by serializationSendToClient().
clientSendToSerialization()
template<typename T > void clientSendToSerialization (const T & message, messaging::MessageController & mc)
References MessageController::c2sMessageBytes, MessageController::c2sMessageCount, ThreadingChecker::isClientThread(), SCLOG, MessageController::sendRawFromClient(), and MessageController::threadingChecker.
Referenced by DriveFSRowComponent::mouseDoubleClick(), DriveFSRowComponent::mouseDown(), MessageController::registerClient(), SCXTApplicationWindow::SCXTApplicationWindow(), SCXTEditor::sendToSerialization(), SCXTPlugin::stateLoad(), DriveFSRowComponent::stopPreview(), and SCXTPlugin::synchronousEngineUnstream().
serializationSendToClient()
template<typename T > void serializationSendToClient (SerializationToClientMessageIds id, const T & payload, messaging::MessageController & mc)
References cacheSerializationMessagesAbsentClient(), MessageController::clientCallback, ThreadingChecker::isSerialThread(), MessageController::preClientConnectionCache, MessageController::reportErrorToClient(), s2c_report_error, and MessageController::threadingChecker.
Referenced by clearPart(), CLIENT_TO_SERIAL_CONSTRAINED(), doAddBrowserDeviceLocation(), doRemoveBrowserDeviceLocation(), doRenameGroup(), doRenameZone(), doUpdateLeadZoneMapping(), pgzSerialSide(), removeGroup(), removeSelectedZones(), removeZone(), MessageController::reportErrorToClient(), Bus::sendBusEffectInfoToClient(), Bus::sendBusSendStorageToClient(), Engine::sendEngineStatusToClient(), Engine::sendMetadataToClient(), setProcessorType(), and updateMacroFullState().
serializationThreadExecuteClientMessage()
void serializationThreadExecuteClientMessage (const std::string & msgView, engine::Engine & e, MessageController & mc)
References scxt::messaging::client::detail::executeOnSerializationFor(), ThreadingChecker::isSerialThread(), num_clientToSerializationMessages, and MessageController::threadingChecker.
clientThreadExecuteSerializationMessage()
template<typename Client > void clientThreadExecuteSerializationMessage (const std::string & msgView, Client * c)
References scxt::messaging::client::detail::executeOnClientFor(), and num_serializationToClientMessages.
Referenced by SCXTEditor::drainCallbackQueue().
SERIAL_TO_CLIENT() [1/28]
SERIAL_TO_CLIENT (DebugInfoGenerated , s2c_send_debug_info , debugResponse_t , onDebugInfoGenerated)
dbto_pretty_stream()
template<template< typename... > class... Transformers, template< typename... > class Traits> void dbto_pretty_stream (std::ostream & os, const tao::json::basic_value< Traits > & v)
Referenced by doDebugAction().
doDebugAction()
void doDebugAction (const std::string & payload, const engine::Engine & engine, MessageController & cont)
References dbto_pretty_stream(), engine, Engine::FOR_DAW, Engine::FOR_MULTI, Engine::getPatch(), Engine::getSelectionManager(), Engine::IN_PROCESS, DebugActions::pretty_json, DebugActions::pretty_json_daw, DebugActions::pretty_json_multi, DebugActions::pretty_json_part, SCLOG, and scxt::json::streamEngineState().
CLIENT_TO_SERIAL() [4/59]
CLIENT_TO_SERIAL (RequestDebugAction , c2s_request_debug_action , std::string , doDebugAction(payload, engine, cont))
SERIAL_TO_CLIENT() [2/28]
SERIAL_TO_CLIENT (EngineStatusUpdate , s2c_engine_status , engine::Engine::EngineStatusMessage , onEngineStatus)
doUnstreamEngineState()
void doUnstreamEngineState (const unstreamEngineStatePayload_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getMessageController(), Engine::immediatelyTerminateAllVoices(), SCLOG, and scxt::json::unstreamEngineState().
CLIENT_TO_SERIAL() [5/59]
CLIENT_TO_SERIAL (UnstreamEngineState , c2s_unstream_engine_state , unstreamEngineStatePayload_t , doUnstreamEngineState(payload, engine, cont))
stopSoundsMessage()
void stopSoundsMessage (const stopSounds_t & payload, messaging::MessageController & cont)
References cont, and Engine::voiceManager.
CLIENT_TO_SERIAL() [6/59]
CLIENT_TO_SERIAL (StopSounds , c2s_silence_engine , stopSounds_t , stopSoundsMessage(payload, cont))
SERIAL_TO_CLIENT() [3/28]
SERIAL_TO_CLIENT (SendActivityNotification , s2c_send_activity_notification , activityNotificationPayload_t , onActivityNotification)
SERIAL_TO_CLIENT() [4/28]
SERIAL_TO_CLIENT (GroupOutputInfoUpdated , s2c_update_group_output_info , groupOutputInfoUpdate_t , onGroupOutputInfoUpdated)
SERIAL_TO_CLIENT() [5/28]
SERIAL_TO_CLIENT (SendGroupTriggerConditions , s2c_send_group_trigger_conditions , scxt::engine::GroupTriggerConditions , onGroupTriggerConditions)
CLIENT_TO_SERIAL_CONSTRAINED() [1/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateGroupOutputInt16TValue , c2s_update_group_output_int16_t_value , detail::diffMsg_t< int16_t > , engine::Group::GroupOutputInfo , detail::updateGroupMemberValue &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [2/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateGroupOutputBoolValue , c2s_update_group_output_bool_value , detail::diffMsg_t< bool > , engine::Group::GroupOutputInfo , detail::updateGroupMemberValue &::::,,, cont)
doUpdateGroupTriggerConditions()
void doUpdateGroupTriggerConditions (const engine::GroupTriggerConditions & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [7/59]
CLIENT_TO_SERIAL (UpdateGroupTriggerConditions , c2s_update_group_trigger_conditions , scxt::engine::GroupTriggerConditions , doUpdateGroupTriggerConditions(payload, engine, cont))
doUpdateGroupOutputInfoPolyphony()
void doUpdateGroupOutputInfoPolyphony (const scxt::engine::Group::GroupOutputInfo payload, const engine::Engine & engine, messaging::MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [8/59]
CLIENT_TO_SERIAL (UpdateGroupOutputInfoPolyphony , c2s_update_group_output_info_polyphony , scxt::engine::Group::GroupOutputInfo , doUpdateGroupOutputInfoPolyphony(payload, engine, cont))
SERIAL_TO_CLIENT() [6/28]
SERIAL_TO_CLIENT (AdsrGroupOrZoneUpdate , s2c_update_group_or_zone_adsr_view , adsrViewResponsePayload_t , onGroupOrZoneEnvelopeUpdated)
CLIENT_TO_SERIAL_CONSTRAINED() [3/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupEGFloatValue , c2s_update_zone_or_group_eg_float_value , detail::indexedZoneOrGroupDiffMsg_t< float > , modulation::modulators::AdsrStorage , detail::updateZoneOrGroupIndexedMemberValue &::::, &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [4/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageFloatValue , c2s_update_zone_or_group_modstorage_float_value , detail::indexedZoneOrGroupDiffMsg_t< float > , modulation::ModulatorStorage , detail::updateZoneOrGroupIndexedMemberValue &::::, &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [5/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageBoolValue , c2s_update_zone_or_group_modstorage_bool_value , detail::indexedZoneOrGroupDiffMsg_t< bool > , modulation::ModulatorStorage , detail::updateZoneOrGroupIndexedMemberValue &::::, &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [6/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupModStorageInt16TValue , c2s_update_zone_or_group_modstorage_int16_t_value , detail::indexedZoneOrGroupDiffMsg_t< int16_t > , modulation::ModulatorStorage , detail::updateZoneOrGroupIndexedMemberValue(&::::, &::::,,,, [] &eng { auto forZone=std::get< 0 >(payload);if(forZone) { auto lz=eng.getSelectionManager() ->currentLeadZone(eng);if(lz.has_value()) { eng.getSelectionManager() ->sendDisplayDataForZonesBasedOnLead(lz->part, lz->group, lz->zone);} } else { auto lg=eng.getSelectionManager() ->currentLeadGroup(eng);} } , nullptr , [payload] (auto &engine, const auto &gs) { auto idx=std::get< 1 >(payload);assert(engine.getMessageController() ->threadingChecker.isAudioThread());for(auto[p, g, z] :gs) { auto &grp=engine.getPatch() ->getPart(p) ->getGroup(g);grp->resetLFOs(idx);grp->rePrepareAndBindGroupMatrix();} })
doRenameGroup()
void doRenameGroup (const renameGroupZonePayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getPartGroupZoneStructure(), Engine::getPatch(), s2c_send_pgz_structure, and serializationSendToClient().
CLIENT_TO_SERIAL() [9/59]
CLIENT_TO_SERIAL (RenameGroup , c2s_rename_group , renameGroupZonePayload_t , doRenameGroup(payload, engine, cont))
doRenameZone()
void doRenameZone (const renameGroupZonePayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getMessageController(), Engine::getPartGroupZoneStructure(), Engine::getPatch(), s2c_send_pgz_structure, s2c_send_selected_group_zone_mapping_summary, and serializationSendToClient().
CLIENT_TO_SERIAL() [10/59]
CLIENT_TO_SERIAL (RenameZone , c2s_rename_zone , renameGroupZonePayload_t , doRenameZone(payload, engine, cont))
SERIAL_TO_CLIENT() [7/28]
SERIAL_TO_CLIENT (ReportError , s2c_report_error , s2cError_t , onErrorFromEngine)
CLIENT_TO_SERIAL() [11/59]
CLIENT_TO_SERIAL (SetTuningMode , c2s_set_tuning_mode , int32_t , engine.midikeyRetuner. setTuningMode(tuning::MidikeyRetuner::TuningMode) payload)
processMidiFromGUI()
void processMidiFromGUI (const noteOnOff_t & g, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getPatch(), and Engine::getSelectionManager().
doHostCallback()
void doHostCallback (uint64_t pl, MessageController & cont)
References cont.
CLIENT_TO_SERIAL() [12/59]
CLIENT_TO_SERIAL (RequestHostCallback , c2s_request_host_callback , uint64_t , doHostCallback(payload, cont))
doResetEngine()
void doResetEngine (bool pl, engine::Engine & e, MessageController & cont)
References scxt::patch_io::initFromResourceBundle(), and Engine::sendFullRefreshToClient().
CLIENT_TO_SERIAL() [13/59]
CLIENT_TO_SERIAL (ResetEngine , c2s_reset_engine , bool , doResetEngine(payload, engine, cont))
SERIAL_TO_CLIENT() [8/28]
SERIAL_TO_CLIENT (UpdateMacroFullState , s2c_update_macro_full_state , macroFullState_t , onMacroFullState)
SERIAL_TO_CLIENT() [9/28]
SERIAL_TO_CLIENT (UpdateMacroValue , s2c_update_macro_value , macroValue_t , onMacroValue)
updateMacroFullState()
void updateMacroFullState (const macroFullState_t & t, const engine::Engine & engine, MessageController & cont)
References cont, scxt::modulation::getGroupMatrixMetadata(), scxt::voice::modulation::getVoiceMatrixMetadata(), SerializationToAudio::id, Macro::name, scxt::messaging::audio::s2a_param_refresh, s2c_update_group_matrix_metadata, s2c_update_zone_matrix_metadata, SCD, SCLOG, serializationSendToClient(), and Macro::setValueConstrained().
CLIENT_TO_SERIAL() [14/59]
CLIENT_TO_SERIAL (SetMacroFullState , c2s_set_macro_full_state , macroFullState_t , updateMacroFullState(payload, engine, cont))
updateMacroValue()
void updateMacroValue (const macroValue_t & t, const engine::Engine & engine, MessageController & cont)
References cont, SerializationToAudio::FourUintsFourFloats::f, SerializationToAudio::FOUR_FOUR_MIX, SerializationToAudio::id, SerializationToAudio::Payload::mix, Macro::partIndexToMacroID(), SerializationToAudio::payload, scxt::messaging::audio::s2a_param_set_value, and SerializationToAudio::FourUintsFourFloats::u.
CLIENT_TO_SERIAL() [15/59]
CLIENT_TO_SERIAL (SetMacroValue , c2s_set_macro_value , macroValue_t , updateMacroValue(payload, engine, cont))
doMacroBeginEndEdit()
void doMacroBeginEndEdit (const macroBeginEndEdit_t & payload, const engine::Engine & e, messaging::MessageController & cont)
References cont, SerializationToAudio::FourUintsFourFloats::f, SerializationToAudio::FOUR_FOUR_MIX, Engine::getPatch(), SerializationToAudio::id, SerializationToAudio::Payload::mix, Macro::partIndexToMacroID(), SerializationToAudio::payload, scxt::messaging::audio::s2a_param_beginendedit, and SerializationToAudio::FourUintsFourFloats::u.
CLIENT_TO_SERIAL() [16/59]
CLIENT_TO_SERIAL (MacroBeginEndEdit , c2s_macro_begin_end_edit , macroBeginEndEdit_t , doMacroBeginEndEdit(payload, engine, cont))
SERIAL_TO_CLIENT() [10/28]
SERIAL_TO_CLIENT (SendMissingResolutionWorkItemList , s2c_send_missing_resolution_workitem_list , std::vector< engine::MissingResolutionWorkItem > , onMissingResolutionWorkItemList)
doResolveSample()
void doResolveSample (const resolveSamplePayload_t & payload, engine::Engine & e, messaging::MessageController & cont)
References Engine::getSampleManager(), scxt::engine::resolveMultiFileMissingWorkItem(), scxt::engine::resolveSingleFileMissingWorkItem(), and Engine::sendFullRefreshToClient().
CLIENT_TO_SERIAL() [17/59]
CLIENT_TO_SERIAL (ResolveSample , c2s_resolve_sample , resolveSamplePayload_t , doResolveSample(payload, engine, cont))
SERIAL_TO_CLIENT() [11/28]
SERIAL_TO_CLIENT (SendBusEffectFullData , s2c_bus_effect_full_data , busEffectFullData_t , onMixerBusEffectFullData)
SERIAL_TO_CLIENT() [12/28]
SERIAL_TO_CLIENT (SendBusSendData , s2c_bus_send_data , busSendData_t , onMixerBusSendData)
setBusEffectToType()
void setBusEffectToType (const setBusEffectToType_t & payload, messaging::MessageController & cont)
References cont.
CLIENT_TO_SERIAL() [18/59]
CLIENT_TO_SERIAL (SetBusEffectToType , c2s_set_mixer_effect , setBusEffectToType_t , setBusEffectToType(payload, cont))
setBusEffectStorage()
void setBusEffectStorage (const setBusEffectStorage_t & payload, messaging::MessageController & cont)
References cont.
CLIENT_TO_SERIAL() [19/59]
CLIENT_TO_SERIAL (SetBusEffectStorage , c2s_set_mixer_effect_storage , setBusEffectStorage_t , setBusEffectStorage(payload, cont))
setBusSendStorage()
void setBusSendStorage (const setBusSendStorage_t & payload, messaging::MessageController & cont)
References cont.
CLIENT_TO_SERIAL() [20/59]
CLIENT_TO_SERIAL (SetBusSendStorage , c2s_set_mixer_send_storage , setBusSendStorage_t , setBusSendStorage(payload, cont))
SERIAL_TO_CLIENT() [13/28]
SERIAL_TO_CLIENT (UpdateZoneVoiceMatrixMetadata , s2c_update_zone_matrix_metadata , voice::modulation::voiceMatrixMetadata_t , onZoneVoiceMatrixMetadata)
SERIAL_TO_CLIENT() [14/28]
SERIAL_TO_CLIENT (UpdateZoneVoiceMatrix , s2c_update_zone_matrix , voice::modulation::Matrix::RoutingTable , onZoneVoiceMatrix)
SERIAL_TO_CLIENT() [15/28]
SERIAL_TO_CLIENT (UpdateGroupMatrixMetadata , s2c_update_group_matrix_metadata , scxt::modulation::groupMatrixMetadata_t , onGroupMatrixMetadata)
SERIAL_TO_CLIENT() [16/28]
SERIAL_TO_CLIENT (UpdateGroupMatrix , s2c_update_group_matrix , modulation::GroupMatrix::RoutingTable , onGroupMatrix)
doUpdateZoneRoutingRow()
void doUpdateZoneRoutingRow (const zoneRoutingRowPayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [21/59]
CLIENT_TO_SERIAL (UpdateZoneRoutingRow , c2s_update_zone_routing_row , zoneRoutingRowPayload_t , doUpdateZoneRoutingRow(payload, engine, cont))
doUpdateGroupRoutingRow()
void doUpdateGroupRoutingRow (const updateGroupRoutingRowPayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [22/59]
CLIENT_TO_SERIAL (UpdateGroupRoutingRow , c2s_update_group_routing_row , updateGroupRoutingRowPayload_t , doUpdateGroupRoutingRow(payload, engine, cont))
SERIAL_TO_CLIENT() [17/28]
SERIAL_TO_CLIENT (UpdateZoneLfo , s2c_update_group_or_zone_individual_modulator_storage , indexedModulatorStorageUpdate_t , onGroupOrZoneModulatorStorageUpdated)
SERIAL_TO_CLIENT() [18/28]
SERIAL_TO_CLIENT (SelectedPart , s2c_send_selected_part , int16_t , onSelectedPart)
SERIAL_TO_CLIENT() [19/28]
SERIAL_TO_CLIENT (SelectedGroupZoneMappingSummary , s2c_send_selected_group_zone_mapping_summary , engine::Part::zoneMappingSummary_t , onGroupZoneMappingSummary)
SERIAL_TO_CLIENT() [20/28]
SERIAL_TO_CLIENT (SendPartConfiguration , s2c_send_part_configuration , partConfigurationPayload_t , onPartConfiguration)
updatePartFullConfig()
void updatePartFullConfig (const partConfigurationPayload_t & p, const engine::Engine & e, messaging::MessageController & cont)
References cont.
CLIENT_TO_SERIAL() [23/59]
CLIENT_TO_SERIAL (UpdatePartFullConfig , c2s_send_full_part_config , partConfigurationPayload_t , updatePartFullConfig(payload, engine, cont))
doSaveMulti()
void doSaveMulti (const std::string & s, engine::Engine & engine, MessageController & cont)
References engine, scxt::patch_io::saveMulti(), and SCLOG.
CLIENT_TO_SERIAL() [24/59]
CLIENT_TO_SERIAL (SaveMulti , c2s_save_multi , std::string , doSaveMulti(payload, engine, cont))
CLIENT_TO_SERIAL() [25/59]
CLIENT_TO_SERIAL (LoadMulti , c2s_load_multi , std::string , patch_io::loadMulti(fs::path(fs::u8path(payload)), engine))
doSaveSelectedPart()
void doSaveSelectedPart (const std::string & s, engine::Engine & engine, MessageController & cont)
References engine, Engine::getSelectionManager(), scxt::patch_io::savePart(), and SCLOG.
CLIENT_TO_SERIAL() [26/59]
CLIENT_TO_SERIAL (SaveSelectedPart , c2s_save_selected_part , std::string , doSaveSelectedPart(payload, engine, cont))
doLoadPartInto()
void doLoadPartInto (const loadPartIntoPayload_t & payload, engine::Engine & engine, MessageController & cont)
References engine, and scxt::patch_io::loadPartInto().
CLIENT_TO_SERIAL() [27/59]
CLIENT_TO_SERIAL (LoadPartInto , c2s_load_part_into , loadPartIntoPayload_t , doLoadPartInto(payload, engine, cont))
SERIAL_TO_CLIENT() [21/28]
SERIAL_TO_CLIENT (ProcessorMetadataAndData , s2c_respond_single_processor_metadata_and_data , processorDataResponsePayload_t , onGroupOrZoneProcessorDataAndMetadata)
SERIAL_TO_CLIENT() [22/28]
SERIAL_TO_CLIENT (ProcessorsMismatched , s2c_notify_mismatched_processors_for_zone , processorMismatchPayload_t , onZoneProcessorDataMismatch)
setProcessorType()
void setProcessorType (const setProcessorPayload_t & whichToType, const engine::Engine & engine, messaging::MessageController & cont)
References cont, engine, scxt::modulation::getGroupMatrixMetadata(), Engine::getMessageController(), Engine::getPatch(), Engine::getSelectionManager(), scxt::voice::modulation::getVoiceMatrixMetadata(), s2c_respond_single_processor_metadata_and_data, s2c_update_group_matrix_metadata, s2c_update_zone_matrix_metadata, and serializationSendToClient().
CLIENT_TO_SERIAL() [28/59]
CLIENT_TO_SERIAL (SetSelectedProcessorType , c2s_set_processor_type , setProcessorPayload_t , setProcessorType(payload, engine, cont))
CLIENT_TO_SERIAL() [29/59]
CLIENT_TO_SERIAL (CopyProcessorLeadToAll , c2s_copy_processor_lead_to_all , int , engine. getSelectionManager) ->copyZoneProcessorLeadToAll(payload)
CLIENT_TO_SERIAL_CONSTRAINED() [7/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorFloatValue , c2s_update_single_processor_float_value , detail::indexedZoneOrGroupDiffMsg_t< float > , dsp::processor::ProcessorStorage , detail::updateZoneOrGroupIndexedMemberValue &::::, &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [8/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorInt32TValue , c2s_update_single_processor_int32_t_value , detail::indexedZoneOrGroupDiffMsg_t< int32_t > , dsp::processor::ProcessorStorage , detail::updateZoneOrGroupIndexedMemberValue(&::::, &::::,,,,, [] &, &sz { auto wp=std::get< 1 >(payload);for(const auto &a :sz) { const auto &z=e.getPatch() ->getPart(a.part) ->getGroup(a.group) ->getZone(a.zone);z->checkOrAdjustIntConsistency(wp);} } , [payload] (auto &e, auto &sg) { auto wp=std::get< 1 >(payload);for(const auto &a :sg) { const auto &g=e.getPatch() ->getPart(a.part) ->getGroup(a.group);g->checkOrAdjustIntConsistency(wp);} })
CLIENT_TO_SERIAL_CONSTRAINED() [9/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOrGroupProcessorBoolValue , c2s_update_single_processor_bool_value , detail::indexedZoneOrGroupDiffMsg_t< bool > , dsp::processor::ProcessorStorage , detail::updateZoneOrGroupIndexedMemberValue(&::::, &::::,,,,, [] &, &sz { auto wp=std::get< 1 >(payload);for(const auto &a :sz) { const auto &z=e.getPatch() ->getPart(a.part) ->getGroup(a.group) ->getZone(a.zone);z->checkOrAdjustBoolConsistency(wp);} } , [payload] (auto &e, auto &sg) { auto wp=std::get< 1 >(payload);for(const auto &a :sg) { const auto &g=e.getPatch() ->getPart(a.part) ->getGroup(a.group);g->checkOrAdjustBoolConsistency(wp);} })
swapZoneProcessors()
void swapZoneProcessors (const processorPair_t & whichToType, const engine::Engine & engine, messaging::MessageController & cont)
References cont, engine, Engine::getPatch(), and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [30/59]
CLIENT_TO_SERIAL (SwapZoneProcessors , c2s_swap_zone_processors , processorPair_t , swapZoneProcessors(payload, engine, cont))
swapGroupProcessors()
void swapGroupProcessors (const processorPair_t & whichToType, const engine::Engine & engine, messaging::MessageController & cont)
References cont, engine, Engine::getPatch(), and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [31/59]
CLIENT_TO_SERIAL (SwapGroupProcessors , c2s_swap_group_processors , processorPair_t , swapGroupProcessors(payload, engine, cont))
doApplySelectAction()
void doApplySelectAction (const selection::SelectionManager::SelectActionContents & za, const engine::Engine & engine)
References engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [32/59]
CLIENT_TO_SERIAL (ApplySelectAction , c2s_apply_select_action , selection::SelectionManager::SelectActionContents , doApplySelectAction(payload, engine))
doApplyMultiSelectAction()
void doApplyMultiSelectAction (const std::vector< selection::SelectionManager::SelectActionContents > & za, const engine::Engine & engine)
References engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [33/59]
CLIENT_TO_SERIAL (ApplyMultiSelectAction , c2s_apply_multi_select_action , std::vector< selection::SelectionManager::SelectActionContents > , doApplyMultiSelectAction(payload, engine))
CLIENT_TO_SERIAL() [34/59]
CLIENT_TO_SERIAL (SelectPart , c2s_select_part , int16_t , engine. getSelectionManager) ->selectPart(payload)
SERIAL_TO_CLIENT() [23/28]
SERIAL_TO_CLIENT (SetSelectionState , s2c_send_selection_state , selectedStateMessage_t , onSelectionState)
SERIAL_TO_CLIENT() [24/28]
SERIAL_TO_CLIENT (SetOtherTabSelection , s2c_send_othertab_selection , scxt::selection::SelectionManager::otherTabSelection_t , onOtherTabSelection)
doUpdateOtherTabSelection()
void doUpdateOtherTabSelection (const updateOther_t & pl, const engine::Engine & engine)
References engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [35/59]
CLIENT_TO_SERIAL (UpdateOtherTabSelection , c2s_set_othertab_selection , updateOther_t , doUpdateOtherTabSelection(payload, engine))
doBeginEndEdit()
void doBeginEndEdit (bool isBegin, const editGestureFor_t & payload, const engine::Engine & engine, messaging::MessageController & cont)
References engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [36/59]
CLIENT_TO_SERIAL (BeginEdit , c2s_begin_edit , editGestureFor_t , doBeginEndEdit(true, payload, engine, cont))
CLIENT_TO_SERIAL() [37/59]
CLIENT_TO_SERIAL (EndEdit , c2s_end_edit , editGestureFor_t , doBeginEndEdit(false, payload, engine, cont))
pgzSerialSide()
void pgzSerialSide (const int & partNum, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getPartGroupZoneStructure(), s2c_send_pgz_structure, and serializationSendToClient().
CLIENT_SERIAL_REQUEST_RESPONSE()
CLIENT_SERIAL_REQUEST_RESPONSE (PartGroupZoneStructure , c2s_request_pgz_structure , int32_t , s2c_send_pgz_structure , engine::Engine::pgzStructure_t , pgzSerialSide(payload, engine, cont) , onStructureUpdated)
SERIAL_TO_CLIENT() [25/28]
SERIAL_TO_CLIENT (SendAllProcessorDescriptions , s2c_send_all_processor_descriptions , std::vector< dsp::processor::ProcessorDescription > , onAllProcessorDescriptions)
doRegisterClient()
void doRegisterClient (engine::Engine & engine, MessageController & cont)
References cont, SelectionManager::SelectActionContents::distinct, engine, Engine::getSelectionManager(), Engine::sendFullRefreshToClient(), and Engine::sendMetadataToClient().
CLIENT_TO_SERIAL() [38/59]
CLIENT_TO_SERIAL (RegisterClient , c2s_register_client , bool , doRegisterClient(engine, cont))
addSample()
void addSample (const std::string & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::loadSampleIntoSelectedPartAndGroup().
addSampleWithRange()
void addSampleWithRange (const addSampleWithRange_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::loadSampleIntoSelectedPartAndGroup().
CLIENT_TO_SERIAL() [39/59]
CLIENT_TO_SERIAL (AddSampleWithRange , c2s_add_sample_with_range , addSampleWithRange_t , addSampleWithRange(payload, engine, cont);)
addCompoundElementWithRange()
void addCompoundElementWithRange (const addCompoundElementWithRange_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::loadCompoundElementIntoSelectedPartAndGroup().
CLIENT_TO_SERIAL() [40/59]
CLIENT_TO_SERIAL (AddCompoundElementWithRange , c2s_add_compound_element_with_range , addCompoundElementWithRange_t , addCompoundElementWithRange(payload, engine, cont);)
addSampleInZone()
void addSampleInZone (const addSampleInZone_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::loadSampleIntoZone().
CLIENT_TO_SERIAL() [41/59]
CLIENT_TO_SERIAL (AddSampleInZone , c2s_add_sample_in_zone , addSampleInZone_t , addSampleInZone(payload, engine, cont);)
addCompoundElementInZone()
void addCompoundElementInZone (const addCompoundElementInZone_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::loadCompoundElementIntoZone().
CLIENT_TO_SERIAL() [42/59]
CLIENT_TO_SERIAL (AddCompoundElementInZone , c2s_add_compound_element_in_zone , addCompoundElementInZone_t , addCompoundElementInZone(payload, engine, cont);)
SCLOG_IF()
SCLOG_IF (groupZoneMutation , "Creating group in part "<< partNumber)
scheduleAudioThreadCallbackUnderStructureLock()
cont scheduleAudioThreadCallbackUnderStructureLock ([p=partNumber] (auto &e) { e.getPatch() ->getPart(p) ->addGroup();} , [p=partNumber] (auto &engine) { SCLOG_IF(groupZoneMutation, "Responding with part group zone structure in "<< p);serializationSendToClient(s2c_send_pgz_structure, engine.getPartGroupZoneStructure(), *(engine.getMessageController()));serializationSendToClient(s2c_send_selected_group_zone_mapping_summary, engine.getPatch() ->getPart(p) ->getZoneMappingSummary(), *(engine.getMessageController()));if(engine.getSelectionManager() ->currentlySelectedZones().empty()) { SCLOG_IF(selection, "Empty selection when creating group in "<< p);int32_t g=engine.getPatch() ->getPart(p) ->getGroups().size() - 1;engine.getSelectionManager() ->selectAction(selection::SelectionManager::SelectActionContents(p, g, -1, true, true, true));} })
CLIENT_TO_SERIAL() [43/59]
CLIENT_TO_SERIAL (CreateGroup , c2s_create_group , int , createGroupIn(payload, engine, cont))
removeZone()
void removeZone (const selection::SelectionManager::ZoneAddress & a, engine::Engine & engine, MessageController & cont)
References scxt::messaging::audio::a2s_delete_this_pointer, cont, AudioToSerialization::Payload::delThis, engine, AudioToSerialization::ToBeDeleted::engine_Zone, Engine::getMessageController(), Engine::getPartGroupZoneStructure(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), AudioToSerialization::id, AudioToSerialization::payload, AudioToSerialization::ToBeDeleted::ptr, s2c_send_pgz_structure, s2c_send_selected_group_zone_mapping_summary, serializationSendToClient(), AudioToSerialization::TO_BE_DELETED, and AudioToSerialization::ToBeDeleted::type.
CLIENT_TO_SERIAL() [44/59]
CLIENT_TO_SERIAL (DeleteZone , c2s_delete_zone , selection::SelectionManager::ZoneAddress , removeZone(payload, engine, cont))
CLIENT_TO_SERIAL() [45/59]
CLIENT_TO_SERIAL (DuplicateZone , c2s_duplicate_zone , selection::SelectionManager::ZoneAddress , engine. duplicateZonepayload)
CLIENT_TO_SERIAL() [46/59]
CLIENT_TO_SERIAL (CopyZone , c2s_copy_zone , selection::SelectionManager::ZoneAddress , engine. copyZonepayload)
CLIENT_TO_SERIAL() [47/59]
CLIENT_TO_SERIAL (PasteZone , c2s_paste_zone , selection::SelectionManager::ZoneAddress , engine. pasteZonepayload)
removeSelectedZones()
void removeSelectedZones (const bool & , engine::Engine & engine, MessageController & cont)
References scxt::messaging::audio::a2s_delete_this_pointer, cont, AudioToSerialization::Payload::delThis, engine, AudioToSerialization::ToBeDeleted::engine_Zone, Engine::getMessageController(), Engine::getPartGroupZoneStructure(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), AudioToSerialization::id, AudioToSerialization::payload, AudioToSerialization::ToBeDeleted::ptr, s2c_send_pgz_structure, s2c_send_selected_group_zone_mapping_summary, serializationSendToClient(), AudioToSerialization::TO_BE_DELETED, and AudioToSerialization::ToBeDeleted::type.
CLIENT_TO_SERIAL() [48/59]
CLIENT_TO_SERIAL (DeleteAllSelectedZones , c2s_delete_selected_zones , bool , removeSelectedZones(payload, engine, cont))
removeGroup()
void removeGroup (const selection::SelectionManager::ZoneAddress & a, engine::Engine & engine, MessageController & cont)
References scxt::messaging::audio::a2s_delete_this_pointer, cont, AudioToSerialization::Payload::delThis, engine, AudioToSerialization::ToBeDeleted::engine_Group, Engine::getMessageController(), Engine::getPartGroupZoneStructure(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), AudioToSerialization::id, AudioToSerialization::payload, AudioToSerialization::ToBeDeleted::ptr, s2c_send_pgz_structure, s2c_send_selected_group_zone_mapping_summary, serializationSendToClient(), AudioToSerialization::TO_BE_DELETED, and AudioToSerialization::ToBeDeleted::type.
CLIENT_TO_SERIAL() [49/59]
CLIENT_TO_SERIAL (DeleteGroup , c2s_delete_group , selection::SelectionManager::ZoneAddress , removeGroup(payload, engine, cont))
clearPart()
void clearPart (const int p, engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getMessageController(), Engine::getPartGroupZoneStructure(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), s2c_send_pgz_structure, s2c_send_selected_group_zone_mapping_summary, and serializationSendToClient().
CLIENT_TO_SERIAL() [50/59]
CLIENT_TO_SERIAL (ClearPart , c2s_clear_part , int , clearPart(payload, engine, cont))
moveZoneFromTo()
void moveZoneFromTo (const zoneAddressFromTo_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getPatch().
Referenced by CLIENT_TO_SERIAL().
CLIENT_TO_SERIAL() [51/59]
CLIENT_TO_SERIAL (MoveZoneFromTo , c2s_move_zone , zoneAddressFromTo_t , moveZoneFromTo(payload, engine, cont))
References moveZoneFromTo().
doActivateNextPart()
void doActivateNextPart (messaging::MessageController & cont)
References cont, and doActivateNextPart().
Referenced by CLIENT_TO_SERIAL(), and doActivateNextPart().
CLIENT_TO_SERIAL() [52/59]
CLIENT_TO_SERIAL (ActivateNextPart , c2s_activate_next_part , bool , doActivateNextPart(cont))
References doActivateNextPart().
doDeactivatePart()
void doDeactivatePart (int part, messaging::MessageController & cont)
References cont, and doDeactivatePart().
Referenced by CLIENT_TO_SERIAL(), and doDeactivatePart().
CLIENT_TO_SERIAL() [53/59]
CLIENT_TO_SERIAL (DeactivatePart , c2s_deactivate_part , int32_t , doDeactivatePart(payload, cont))
References doDeactivatePart().
doRequestZoneDataRefresh()
void doRequestZoneDataRefresh (const engine::Engine & eng, messaging::MessageController & cont)
References doRequestZoneDataRefresh(), and Engine::getSelectionManager().
Referenced by CLIENT_TO_SERIAL(), and doRequestZoneDataRefresh().
CLIENT_TO_SERIAL() [54/59]
CLIENT_TO_SERIAL (RequestZoneDataRefresh , c2s_request_zone_data_refresh , bool , doRequestZoneDataRefresh(engine, cont))
References doRequestZoneDataRefresh().
SERIAL_TO_CLIENT() [26/28]
SERIAL_TO_CLIENT (MappingSelectedZoneView , s2c_respond_zone_mapping , mappingSelectedZoneViewResposne_t , onMappingUpdated)
doUpdateLeadZoneMapping()
void doUpdateLeadZoneMapping (const engine::Zone::ZoneMappingData & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getSelectionManager(), s2c_send_selected_group_zone_mapping_summary, and serializationSendToClient().
CLIENT_TO_SERIAL() [55/59]
CLIENT_TO_SERIAL (UpdateLeadZoneMapping , c2s_update_lead_zone_mapping , engine::Zone::ZoneMappingData , doUpdateLeadZoneMapping(payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED() [10/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneMappingFloatValue , c2s_update_zone_mapping_float , detail::diffMsg_t< float > , engine::Zone::ZoneMappingData , detail::updateZoneLeadMemberValue &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [11/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneMappingInt16TValue , c2s_update_zone_mapping_int16_t , detail::diffMsg_t< int16_t > , engine::Zone::ZoneMappingData , detail::updateZoneLeadMemberValue(&::::,,,, [] &eng { auto pt=eng.getSelectionManager() ->currentlySelectedPart(eng);serializationSendToClient(messaging::client::s2c_send_selected_group_zone_mapping_summary, eng.getPatch() ->getPart(pt) ->getZoneMappingSummary(), *(eng.getMessageController()));})
References Engine::getSelectionManager(), s2c_send_selected_group_zone_mapping_summary, and serializationSendToClient().
SERIAL_TO_CLIENT() [27/28]
SERIAL_TO_CLIENT (SampleSelectedZoneView , s2c_respond_zone_samples , sampleSelectedZoneViewResposne_t , onSamplesUpdated)
doUpdateLeadZoneSingleVariant()
void doUpdateLeadZoneSingleVariant (const updateLeadZoneSingleVariantPayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [56/59]
CLIENT_TO_SERIAL (UpdateLeadZoneSingleVariant , c2s_update_lead_zone_single_variant , updateLeadZoneSingleVariantPayload_t , doUpdateLeadZoneSingleVariant(payload, engine, cont))
doNormalizeVariantAmplitude()
void doNormalizeVariantAmplitude (const normalizeVariantAmplitudePayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [57/59]
CLIENT_TO_SERIAL (NormalizeVariantAmplitude , c2s_normalize_variant_amplitude , normalizeVariantAmplitudePayload_t , doNormalizeVariantAmplitude(payload, engine, cont))
doClearVariantAmplitudeNormalization()
void doClearVariantAmplitudeNormalization (const clearVariantAmplitudeNormalizationPayload_t & payload, const engine::Engine & engine, MessageController & cont)
References cont, engine, and Engine::getSelectionManager().
CLIENT_TO_SERIAL() [58/59]
CLIENT_TO_SERIAL (ClearVariantAmplitudeNormalization , c2s_clear_variant_amplitude_normalization , clearVariantAmplitudeNormalizationPayload_t , doClearVariantAmplitudeNormalization(payload, engine, cont))
CLIENT_TO_SERIAL_CONSTRAINED() [12/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneVariantsInt16TValue , c2s_update_zone_variants_int16_t , detail::diffMsg_t< int16_t > , engine::Zone::Variants , detail::updateZoneMemberValue &::::,,, cont)
SERIAL_TO_CLIENT() [28/28]
SERIAL_TO_CLIENT (ZoneOutputInfoUpdated , s2c_update_zone_output_info , zoneOutputInfoUpdate_t , onZoneOutputInfoUpdated)
CLIENT_TO_SERIAL_CONSTRAINED() [13/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputFloatValue , c2s_update_zone_output_float_value , detail::diffMsg_t< float > , engine::Zone::ZoneOutputInfo , detail::updateZoneMemberValue &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [14/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputInt16TValue , c2s_update_zone_output_int16_t_value , detail::diffMsg_t< int16_t > , engine::Zone::ZoneOutputInfo , detail::updateZoneMemberValue &::::,,, cont)
CLIENT_TO_SERIAL_CONSTRAINED() [15/15]
CLIENT_TO_SERIAL_CONSTRAINED (UpdateZoneOutputInt16TValueThenRefresh , c2s_update_zone_output_int16_t_value_then_refresh , detail::diffMsg_t< int16_t > , engine::Zone::ZoneOutputInfo , detail::updateZoneMemberValue(&::::,,,, [] &eng { auto lz=eng.getSelectionManager() ->currentLeadZone(eng);if(lz.has_value()) { eng.getSelectionManager() ->sendDisplayDataForZonesBasedOnLead(lz->part, lz->group, lz->zone);} })
References Engine::getSelectionManager().
doAddBlankZone()
void doAddBlankZone (const addBlankZonePayload_t & payload, engine::Engine & engine, MessageController & cont)
References Engine::createEmptyZone(), and engine.
CLIENT_TO_SERIAL() [59/59]
CLIENT_TO_SERIAL (AddBlankZone , c2s_add_blank_zone , addBlankZonePayload_t , doAddBlankZone(payload, engine, cont))
doDeleteVariant()
void doDeleteVariant (const deleteVariantPayload_t & payload, engine::Engine & engine, MessageController & cont)
References cont, engine, Engine::getSelectionManager(), and SCLOG_ONCE.
Variable Documentation
engine
engine::Engine& engine
Referenced by addCompoundElementInZone(), addCompoundElementWithRange(), addSample(), addSampleInZone(), addSampleWithRange(), clearPart(), doAddBlankZone(), doAddBrowserDeviceLocation(), doApplyMultiSelectAction(), doApplySelectAction(), doBeginEndEdit(), doClearVariantAmplitudeNormalization(), doDebugAction(), doDeleteVariant(), doLoadPartInto(), doNormalizeVariantAmplitude(), doPreviewBrowserSample(), doRegisterClient(), doRemoveBrowserDeviceLocation(), doRenameGroup(), doRenameZone(), doSaveMulti(), doSaveSelectedPart(), doUnstreamEngineState(), doUpdateGroupOutputInfoPolyphony(), doUpdateGroupRoutingRow(), doUpdateGroupTriggerConditions(), doUpdateLeadZoneMapping(), doUpdateLeadZoneSingleVariant(), doUpdateOtherTabSelection(), doUpdateZoneRoutingRow(), moveZoneFromTo(), pgzSerialSide(), processMidiFromGUI(), removeGroup(), removeSelectedZones(), removeZone(), setProcessorType(), swapGroupProcessors(), swapZoneProcessors(), scxt::messaging::client::detail::updateGroupIndexedMemberValue(), scxt::messaging::client::detail::updateGroupMemberValue(), scxt::messaging::client::detail::updateZoneIndexedMemberValue(), scxt::messaging::client::detail::updateZoneLeadMemberValue(), scxt::messaging::client::detail::updateZoneMemberValue(), and scxt::messaging::client::detail::updateZoneOrGroupIndexedMemberValue().
cont
engine::Engine MessageController& cont
Initial value:
{
    if (partNumber < 0 || partNumber > numParts)
        partNumber = 0
Referenced by addCompoundElementInZone(), addCompoundElementWithRange(), addSample(), addSampleInZone(), addSampleWithRange(), clearPart(), doActivateNextPart(), doAddBrowserDeviceLocation(), doClearVariantAmplitudeNormalization(), doDeactivatePart(), doDeleteVariant(), doHostCallback(), doMacroBeginEndEdit(), doNormalizeVariantAmplitude(), doPreviewBrowserSample(), doRegisterClient(), doRemoveBrowserDeviceLocation(), doRenameGroup(), doRenameZone(), doUnstreamEngineState(), doUpdateGroupOutputInfoPolyphony(), doUpdateGroupRoutingRow(), doUpdateGroupTriggerConditions(), doUpdateLeadZoneMapping(), doUpdateLeadZoneSingleVariant(), doUpdateZoneRoutingRow(), moveZoneFromTo(), pgzSerialSide(), processMidiFromGUI(), removeGroup(), removeSelectedZones(), removeZone(), setBusEffectStorage(), setBusEffectToType(), setBusSendStorage(), setProcessorType(), stopSoundsMessage(), swapGroupProcessors(), swapZoneProcessors(), scxt::messaging::client::detail::updateGroupIndexedMemberValue(), scxt::messaging::client::detail::updateGroupMemberValue(), updateMacroFullState(), updateMacroValue(), updatePartFullConfig(), scxt::messaging::client::detail::updateZoneIndexedMemberValue(), scxt::messaging::client::detail::updateZoneLeadMemberValue(), scxt::messaging::client::detail::updateZoneMemberValue(), and scxt::messaging::client::detail::updateZoneOrGroupIndexedMemberValue().