shortcircuit-xt: scxt::sf2_support Namespace Reference
scxt::sf2_support Namespace Reference
Functions
bool importSF2 (const fs::path &p, engine::Engine &e, int preset)
Function Documentation
importSF2()
bool importSF2 (const fs::path & p, engine::Engine & e, int preset)
References scxt::import_support::addImportedModRoute(), ImporterContext::addZoneToGroup(), scxt::import_support::centibelsToLinear(), scxt::import_support::centsToSemitones(), ImportedSource::channelAT(), scxt::infrastructure::createMD5SumFromFile(), scxt::import_support::Cutoff, scxt::import_support::dBToCubicAttenuation(), ImporterContext::fail(), ImportedTarget::filter(), ImporterContext::finish(), ImportedSource::fromEG(), ImportedSource::fromLFO(), scxt::import_support::getOrCreateGroup(), Engine::getSampleManager(), scxt::import_support::importZoneEnvelope(), scxt::import_support::importZoneFilter(), scxt::import_support::importZoneLFO(), scxt::import_support::importZoneLoop(), scxt::import_support::importZoneMapping(), ImportedSource::keyTrack(), ModulatorStorage::LFO_SINE, scxt::import_support::LP12, ImportedSource::midiCC(), ImportedSource::modWheel(), ImportedTarget::pitch(), ImportedSource::pitchBend(), FilterHandle::procSlot, SCLOG_IF, scxt::import_support::sf2NormalizedPan(), ImporterContext::unsupported(), ImportedSource::velocity(), and ImportedTarget::zonePan().
Referenced by scxt::perf::applyLoad(), Engine::loadCompoundElementIntoSelectedPartAndGroup(), and Engine::loadSampleIntoSelectedPartAndGroup().