shortcircuit-xt: scxt::multisample_support Namespace Reference
scxt::multisample_support Namespace Reference
Functions
bool importMultisample (const fs::path &p, engine::Engine &engine)
Function Documentation
importMultisample()
bool importMultisample (const fs::path & p, engine::Engine & engine)
References scxt::infrastructure::createMD5SumFromFile(), Engine::getMessageController(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), Zone::LOOP_WHILE_GATED, and SCLOG_IF.
Referenced by Engine::loadSampleIntoSelectedPartAndGroup().