shortcircuit-xt: scxt::ui::connectors Namespace Reference
scxt::ui::connectors Namespace Reference
Namespaces
namespace jsonlayout
namespace resources
Classes
struct BooleanPayloadDataAttachment
struct DirectBooleanPayloadDataAttachment
struct DiscreteFromFloatAdapterAttachment
struct DiscretePayloadDataAttachment
struct DummyContinuous
struct PayloadDataAttachment
struct SamplePointDataAttachment
struct SingleValueFactory
Typedefs
template<typename A , typename Msg >
using BooleanSingleValueFactory = SingleValueFactory< A, Msg, DiscretePayloadDataAttachment< typename A::payload_t, bool > >
Functions
template<typename M , typename P , typename V , typename... Args>
void updateSingleValue (const P &p, V &value, app::HasEditor *e, Args... args)
template<typename M , typename A , typename ABase , typename... Args>
std::function< void(const ABase &)> makeUpdater (A &att, const typename A::payload_t &p, app::HasEditor *e, Args... args)
template<typename M , typename A , typename ABase = A, typename... Args>
void configureUpdater (A &att, const typename A::payload_t &p, app::HasEditor *e, Args... args)
template<typename A , typename F >
void addGuiStepBeforeSend (A &att, F preStep)
template<typename A , typename F >
void addGuiStep (A &att, F andThen)
template<typename T >
std::unique_ptr< T > makeConnectedToDummy (uint32_t index, const std::string &lab, float initVal, bool isBip, std::function< void()> onFirstEdit)
Typedef Documentation
BooleanSingleValueFactory
template<typename A , typename Msg > using BooleanSingleValueFactory = SingleValueFactory<A, Msg, DiscretePayloadDataAttachment<typename A::payload_t, bool> >
Function Documentation
updateSingleValue()
template<typename M , typename P , typename V , typename... Args> void updateSingleValue (const P & p, V & value, app::HasEditor * e, Args... args)
References HasEditor::sendToSerialization().
makeUpdater()
template<typename M , typename A , typename ABase , typename... Args> std::function< void(const ABase &)> makeUpdater (A & att, const typename A::payload_t & p, app::HasEditor * e, Args... args)
References HasEditor::sendToSerialization(), and HasEditor::updateValueTooltip().
configureUpdater()
template<typename M , typename A , typename ABase = A, typename... Args> void configureUpdater (A & att, const typename A::payload_t & p, app::HasEditor * e, Args... args)
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition(), and ProcessorPane::rebuildControlsFromDescription().
addGuiStepBeforeSend()
template<typename A , typename F > void addGuiStepBeforeSend (A & att, F preStep)
Referenced by MappingDisplay::MappingDisplay().
addGuiStep()
template<typename A , typename F > void addGuiStep (A & att, F andThen)
Referenced by HasEditor::addSubscription(), ProcessorPane::attachRebuildToDeactivateAttachment(), ProcessorPane::attachRebuildToIntAttachment(), ProcessorPane::rebuildControlsFromDescription(), and StepLFOPane::StepLFOPane().
makeConnectedToDummy()
template<typename T > std::unique_ptr< T > makeConnectedToDummy (uint32_t index, const std::string & lab, float initVal, bool isBip, std::function< void()> onFirstEdit)