shortcircuit-xt: scxt::datamodel Namespace Reference
scxt::datamodel Namespace Reference
Namespaces
detail
Typedefs
using pmd = sst::basic_blocks::params::ParamMetaData
Functions
template<typename P , typename V >
pmd describeValue (const P &p, const V &l)
Typedef Documentation
pmd
using pmd = sst::basic_blocks::params::ParamMetaData
Function Documentation
describeValue()
pmd scxt::datamodel::describeValue (const P & p, const V & l)
References scxt::datamodel::detail::offV().
Referenced by SingleValueFactory< A, Msg, ABase >::attach(), SingleValueFactory< A, Msg, ABase >::attachAndAdd(), SingleValueFactory< A, Msg, ABase >::attachLabelAndAdd(), scxt::modulation::shared::bindEl(), MatrixEndpoints::LFOTarget::LFOTarget(), ProcessorPane::rebuildControlsFromDescription(), and ProcTab< OTTraits >::updateFromProcessorPanes().