shortcircuit-xt: scxt Namespace Reference
scxt Namespace Reference
Namespaces
namespace akai_support
namespace browser
namespace clap_first
namespace clients
namespace datamodel
namespace dsp
namespace engine
namespace exs_support
namespace gig_support
namespace hasFeature
namespace infrastructure
namespace json
namespace log
namespace messaging
namespace modulation
namespace multisample_support
namespace patch_io
namespace sample
namespace selection
namespace sf2_support
namespace sfz_support
namespace tuning
namespace ui
namespace voice
Classes
struct DebugTimeGuard
struct ID
This is just a little class to make sure we can have IDs for all of our items which are quick to copy but type differentiated so we don't accidentally use a ZoneID on a Sample or some such.
class MoveableOnly
A class which forces move semantics and optionally runs a naive leak detector.
struct SampleID
struct SampleRateSupport
struct SCXTError
struct ThreadingChecker
Typedefs
typedef ID< 2 > PatchID
typedef ID< 3 > PartID
typedef ID< 4 > GroupID
typedef ID< 5 > ZoneID
typedef ID< 7 > EngineID
Functions
void printStackTrace (int fd)
void postToLog (const std::string &s)
std::string getFullLog ()
std::string logTimestamp ()
template<typename E , std::string(*)(const E &) F>
std::unordered_map< std::string, E > makeEnumInverse (const E &from, const E &to)
bool extensionStringMatches (const std::string &pes, const std::string &s)
bool extensionMatches (const fs::path &p, const std::string &s)
std::string humanReadableVersion (uint64_t v)
Variables
std::mutex logMutex
std::deque< std::string > logMessages
Typedef Documentation
PatchID
typedef ID<2> PatchID
PartID
typedef ID<3> PartID
GroupID
typedef ID<4> GroupID
ZoneID
typedef ID<5> ZoneID
EngineID
typedef ID<7> EngineID
Function Documentation
printStackTrace()
void printStackTrace (int fd)
References SCLOG_IF.
Referenced by Part::getGroup().
postToLog()
void postToLog (const std::string & s)
References logMessages, and logMutex.
Referenced by DebugTimeGuard::print().
getFullLog()
std::string getFullLog ()
References logMessages, and logMutex.
Referenced by LogScreen::reshowLog().
logTimestamp()
std::string logTimestamp ()
Referenced by DebugTimeGuard::print().
makeEnumInverse()
template<typename E , std::string(*)(const E &) F> std::unordered_map< std::string, E > makeEnumInverse (const E & from, const E & to)
References makeEnumInverse().
Referenced by GroupTriggerConditions::fromStringConditionsConjunction(), and makeEnumInverse().
extensionStringMatches()
bool extensionStringMatches (const std::string & pes, const std::string & s)
References extensionStringMatches().
Referenced by extensionMatches(), and extensionStringMatches().
extensionMatches()
bool extensionMatches (const fs::path & p, const std::string & s)
References extensionMatches(), and extensionStringMatches().
Referenced by HeaderRegion::addResetMenuItems(), Browser::expandForBrowser(), extensionMatches(), HeaderRegion::filesDropped(), Browser::getMultiInstrumentElements(), scxt::sample::compound::getSFZCompoundList(), Browser::isLoadableMultiSample(), Browser::isLoadableSingleSample(), Browser::isShortCircuitFormatFile(), Sample::load(), Engine::loadCompoundElementIntoSelectedPartAndGroup(), Sample::loadFromSCXTMonolith(), Engine::loadSampleIntoSelectedPartAndGroup(), Engine::loadSampleIntoZone(), scxt::engine::resolveMultiFileMissingWorkItem(), ProcessorPane::showPresetsMenu(), and Sample::sourceTypeFromPath().
humanReadableVersion()
std::string humanReadableVersion (uint64_t v)
References humanReadableVersion().
Referenced by Engine::Engine(), and humanReadableVersion().
Variable Documentation
logMutex
std::mutex logMutex
Referenced by getFullLog(), and postToLog().
logMessages
std::deque<std::string> logMessages
Referenced by getFullLog(), postToLog(), and ConsoleHarness::start().