shortcircuit-xt: scxt::ui::app::shared Namespace Reference
scxt::ui::app::shared Namespace Reference
Classes
struct ActivityDisplay
struct FXSlotBearing
struct HeaderRegion
struct MacroValueAttachment
struct MenuValueTypein
struct MenuValueTypeinBase
struct NarrowVerticalMenu
struct PartEffectsPane
struct PartNameMenuTypein
struct PartSidebarCard
struct PresetProviderAdapter
struct PresetReceiverAdapter
struct SingleMacroEditor
struct spData
Functions
template<typename T >
void doSaveMulti (T *that, std::unique_ptr< juce::FileChooser > &fileChooser, patch_io::SaveStyles style)
template<typename T >
void doLoadMulti (T *that, std::unique_ptr< juce::FileChooser > &fileChooser)
template<typename T >
void doSavePart (T *that, std::unique_ptr< juce::FileChooser > &fileChooser, int part, patch_io::SaveStyles style)
template<typename T >
void doLoadPartInto (T *that, std::unique_ptr< juce::FileChooser > &fileChooser, int part)
fs::path juceStringToFSPath (const juce::String &fullPathName)
fs::path juceFileToFSPath (const juce::File &f)
juce::File fsPathToJuceFile (const fs::path &p)
engine::Engine::pgzStructure_t findOtherGroups (SCXTEditor *e, const selection::SelectionManager::ZoneAddress &forZone={-1, -1, -1})
template<typename SendingComp , typename RenamingComp >
void populateZoneRightMouseMenuForZone (SendingComp *that, RenamingComp *rnThat, juce::PopupMenu &p, const selection::SelectionManager::ZoneAddress &forZone, const std::string &zoneSectionName)
template<typename SendingComp >
void populateZoneRightMouseMenuForSelectedZones (SendingComp *that, juce::PopupMenu &p, int part, const std::string &name="")
Function Documentation
doSaveMulti()
template<typename T > void doSaveMulti (T * that, std::unique_ptr< juce::FileChooser > & fileChooser, patch_io::SaveStyles style)
References scxt::patch_io::AS_SFZ, juceFileToFSPath(), scxt::patch_io::ONLY_COLLECT, and SCLOG_IF.
Referenced by HeaderRegion::doSaveMulti().
doLoadMulti()
template<typename T > void doLoadMulti (T * that, std::unique_ptr< juce::FileChooser > & fileChooser)
References juceFileToFSPath().
Referenced by HeaderRegion::doLoadMulti().
doSavePart()
template<typename T > void doSavePart (T * that, std::unique_ptr< juce::FileChooser > & fileChooser, int part, patch_io::SaveStyles style)
References scxt::patch_io::AS_SFZ, juceFileToFSPath(), and scxt::patch_io::ONLY_COLLECT.
Referenced by HeaderRegion::doSaveSelectedPart(), and PartSidebarCard::showPartIOMenu().
doLoadPartInto()
template<typename T > void doLoadPartInto (T * that, std::unique_ptr< juce::FileChooser > & fileChooser, int part)
References juceFileToFSPath().
Referenced by HeaderRegion::doLoadIntoSelectedPart(), and PartSidebarCard::showPartIOMenu().
juceStringToFSPath()
fs::path juceStringToFSPath (const juce::String & fullPathName)
Referenced by juceFileToFSPath().
juceFileToFSPath()
fs::path juceFileToFSPath (const juce::File & f)
References juceStringToFSPath().
Referenced by doLoadMulti(), doLoadPartInto(), doSaveMulti(), doSavePart(), MissingResolutionScreen::resolveItem(), and DriveArea::DriveAreaRow::showPopup().
fsPathToJuceFile()
juce::File fsPathToJuceFile (const fs::path & p)
Referenced by VariantDisplay::showFileBrowser().
findOtherGroups()
engine::Engine::pgzStructure_t findOtherGroups (SCXTEditor * e, const selection::SelectionManager::ZoneAddress & forZone = {-1, -1, -1})
Referenced by populateZoneRightMouseMenuForSelectedZones(), and populateZoneRightMouseMenuForZone().
populateZoneRightMouseMenuForZone()
template<typename SendingComp , typename RenamingComp > void populateZoneRightMouseMenuForZone (SendingComp * that, RenamingComp * rnThat, juce::PopupMenu & p, const selection::SelectionManager::ZoneAddress & forZone, const std::string & zoneSectionName)
References findOtherGroups(), and Clipboard::ZONE.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), and ZoneLayoutDisplay::showZoneMenu().
populateZoneRightMouseMenuForSelectedZones()
template<typename SendingComp > void populateZoneRightMouseMenuForSelectedZones (SendingComp * that, juce::PopupMenu & p, int part, const std::string & name = "")
References findOtherGroups().
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), and ZoneLayoutDisplay::showZoneMenu().