shortcircuit-xt: scxt::modulation::shared Namespace Reference
scxt::modulation::shared Namespace Reference
Classes
struct EGTargetEndpointData
struct HasModulators
struct LFOSourceBase
struct LFOTargetEndpointData
struct MIDICCBase
struct ProcessorTargetEndpointData
struct RNGSourceBase
struct RoutingExtraPayload
struct SourceIdentifier
struct TargetIdentifier
struct TransportSourceBase
Functions
std::string u2s (uint32_t u)
template<typename Matrix , typename P >
void bindEl (Matrix &m, const P &payload, typename Matrix::TR::TargetIdentifier &tg, float &tgs, const float *&p, std::optional< datamodel::pmd > providedMetadata=std::nullopt)
Function Documentation
u2s()
std::string u2s (uint32_t u)
bindEl()
template<typename Matrix , typename P > void bindEl (Matrix & m, const P & payload, typename Matrix::TR::TargetIdentifier & tg, float & tgs, const float *& p, std::optional< datamodel::pmd > providedMetadata = std::nullopt)
References scxt::datamodel::describeValue(), and SCLOG.
Referenced by EGTargetEndpointData< TG, gn >::baseBind(), LFOTargetEndpointData< TG, gn >::baseBind(), GroupMatrixEndpoints::ProcessorTarget::bind(), GroupMatrixEndpoints::OutputTarget::bind(), MatrixEndpoints::MappingTarget::bind(), MatrixEndpoints::OutputTarget::bind(), and MatrixEndpoints::ProcessorTarget::bind().