shortcircuit-xt: scxt::ui::theme Namespace Reference
scxt::ui::theme Namespace Reference
Namespaces
namespace detail
namespace layout
Classes
struct ColorMap
struct StdMapColormap
struct ThemeApplier
Typedefs
using metadata_t = std::map< std::string, std::string >
using colors_t = std::map< std::string, std::string >
using colormap_t = std::tuple< metadata_t, colors_t >
using sheet_t = jstl::StyleSheet
Functions
std::string keyName (ColorMap::Colors c)
template<template< typename... > class... Transformers, template< typename... > class Traits>
void to_pretty_stream (std::ostream &os, const tao::json::basic_value< Traits > &v)
void populateSharedGroupZoneMultiModulation (jstl::CustomTypeMap &map)
Typedef Documentation
metadata_t
using metadata_t = std::map<std::string, std::string>
colors_t
using colors_t = std::map<std::string, std::string>
colormap_t
using colormap_t = std::tuple<metadata_t, colors_t>
sheet_t
using sheet_t = jstl::StyleSheet
Function Documentation
keyName()
std::string keyName (ColorMap::Colors c)
References C.
Referenced by StdMapColormap::setupFromColormap(), and ColorMap::toJson().
to_pretty_stream()
template<template< typename... > class... Transformers, template< typename... > class Traits> void to_pretty_stream (std::ostream & os, const tao::json::basic_value< Traits > & v)
Referenced by ColorMap::toJson().
populateSharedGroupZoneMultiModulation()
void populateSharedGroupZoneMultiModulation (jstl::CustomTypeMap & map)
Referenced by ThemeApplier::applyGroupMultiScreenModulationTheme(), and ThemeApplier::applyZoneMultiScreenModulationTheme().