shortcircuit-xt: scxt::dsp::processor::detail Namespace Reference
scxt::dsp::processor::detail Namespace Reference
This code blob uses constexpr expansion to allow us to convert a runtime integer to a template argument without a big case statement.
Typedefs
using boolOp_t = bool(*)()
Booleans.
using constCharOp_t = const char *(*)()
using floatOp_t = float(*)()
using int16Op_t = int16_t(*)()
using reampFnOp_t = remapFn_t(*)()
Functions
template<size_t I>
bool implIsProcessorImplemented ()
template<size_t... Is>
auto isProcessorImplemented (size_t ft, std::index_sequence< Is... >)
template<size_t I>
const char * implGetProcessorName ()
template<size_t... Is>
auto getProcessorName (size_t ft, std::index_sequence< Is... >)
template<size_t I>
const char * implGetProcessorStreamingName ()
template<size_t... Is>
auto getProcessorStreamingName (size_t ft, std::index_sequence< Is... >)
template<size_t I>
const char * implGetProcessorDisplayGroup ()
template<size_t I>
float implGetProcessorDefaultMix ()
template<size_t I>
bool implGetForGroupOnly ()
template<size_t I>
int16_t implGetStreamingVersion ()
template<size_t I>
remapFn_t implGetRemapFn ()
template<size_t... Is>
auto getProcessorDisplayGroup (size_t ft, std::index_sequence< Is... >)
template<size_t... Is>
auto getProcessorDefaultMix (size_t ft, std::index_sequence< Is... >)
template<size_t... Is>
auto getProcessorStreamingVersion (size_t ft, std::index_sequence< Is... >)
template<size_t... Is>
auto getProcessorRemapFn (size_t ft, std::index_sequence< Is... >)
template<size_t... Is>
auto getForGroupOnly (size_t ft, std::index_sequence< Is... >)
template<size_t I>
Processor * returnSpawnOnto (uint8_t *m, engine::MemoryPool *mp, const ProcessorStorage &ps, float *f, int *i, bool needsMetadata)
template<size_t... Is>
auto spawnOnto (size_t ft, uint8_t *m, engine::MemoryPool *mp, const ProcessorStorage &ps, float *f, int *i, bool needsMetadata, std::index_sequence< Is... >)
template<size_t I>
Processor * returnSpawnOntoOS (uint8_t *m, engine::MemoryPool *mp, const ProcessorStorage &ps, float *f, int *i, bool needsMetadata)
template<size_t... Is>
auto spawnOntoOS (size_t ft, uint8_t *m, engine::MemoryPool *mp, const ProcessorStorage &ps, float *f, int *i, bool needsMetadata, std::index_sequence< Is... >)
Detailed Description
This code blob uses constexpr expansion to allow us to convert a runtime integer to a template argument without a big case statement.
Typedef Documentation
boolOp_t
using boolOp_t = bool (*)()
Booleans.
constCharOp_t
using constCharOp_t = const char *(*)()
floatOp_t
using floatOp_t = float (*)()
int16Op_t
using int16Op_t = int16_t (*)()
reampFnOp_t
using reampFnOp_t = remapFn_t (*)()
Function Documentation
implIsProcessorImplemented()
template<size_t I> bool implIsProcessorImplemented ()
References scxt::dsp::processor::proct_none.
isProcessorImplemented()
template<size_t... Is> auto isProcessorImplemented (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::isProcessorImplemented().
implGetProcessorName()
template<size_t I> const char * implGetProcessorName ()
References scxt::dsp::processor::proct_none.
getProcessorName()
template<size_t... Is> auto getProcessorName (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorName().
implGetProcessorStreamingName()
template<size_t I> const char * implGetProcessorStreamingName ()
References scxt::dsp::processor::proct_none.
getProcessorStreamingName()
template<size_t... Is> auto getProcessorStreamingName (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorStreamingName().
implGetProcessorDisplayGroup()
template<size_t I> const char * implGetProcessorDisplayGroup ()
References scxt::dsp::processor::proct_none.
implGetProcessorDefaultMix()
template<size_t I> float implGetProcessorDefaultMix ()
implGetForGroupOnly()
template<size_t I> bool implGetForGroupOnly ()
implGetStreamingVersion()
template<size_t I> int16_t implGetStreamingVersion ()
implGetRemapFn()
template<size_t I> remapFn_t implGetRemapFn ()
getProcessorDisplayGroup()
template<size_t... Is> auto getProcessorDisplayGroup (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorDisplayGroup().
getProcessorDefaultMix()
template<size_t... Is> auto getProcessorDefaultMix (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorDefaultMix().
getProcessorStreamingVersion()
template<size_t... Is> auto getProcessorStreamingVersion (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorStreamingVersion().
getProcessorRemapFn()
template<size_t... Is> auto getProcessorRemapFn (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorRemapParametersFromStreamingVersion().
getForGroupOnly()
template<size_t... Is> auto getForGroupOnly (size_t ft, std::index_sequence< Is... >)
Referenced by scxt::dsp::processor::getProcessorGroupOnly().
returnSpawnOnto()
template<size_t I> Processor * returnSpawnOnto (uint8_t * m, engine::MemoryPool * mp, const ProcessorStorage & ps, float * f, int * i, bool needsMetadata)
References scxt::dsp::processor::proct_none.
spawnOnto()
template<size_t... Is> auto spawnOnto (size_t ft, uint8_t * m, engine::MemoryPool * mp, const ProcessorStorage & ps, float * f, int * i, bool needsMetadata, std::index_sequence< Is... >)
returnSpawnOntoOS()
template<size_t I> Processor * returnSpawnOntoOS (uint8_t * m, engine::MemoryPool * mp, const ProcessorStorage & ps, float * f, int * i, bool needsMetadata)
References scxt::dsp::processor::proct_none.
spawnOntoOS()
template<size_t... Is> auto spawnOntoOS (size_t ft, uint8_t * m, engine::MemoryPool * mp, const ProcessorStorage & ps, float * f, int * i, bool needsMetadata, std::index_sequence< Is... >)