shortcircuit-xt: scxt::patch_io Namespace Reference
scxt::patch_io Namespace Reference
Namespaces
namespace riffwav
Classes
struct SCMonolithSampleReader
Enumerations
enum SaveStyles { NO_SAMPLES = 0 , COLLECT_SAMPLES , AS_MONOLITH }
Functions
void addSCManifest (const std::unique_ptr< RIFF::File > &f, const std::string &type)
std::unordered_map< std::string, std::string > readSCManifest (RIFF::File *f)
std::unordered_map< std::string, std::string > readSCManifest (const std::unique_ptr< RIFF::File > &f)
void addSCDataChunk (const std::unique_ptr< RIFF::File > &f, const std::string &msg)
std::string readSCDataChunk (const std::unique_ptr< RIFF::File > &f)
bool addMonolithBinaries (const std::unique_ptr< RIFF::File > &f, const engine::Engine &e, const sample::SampleManager::sampleMap_t &addThese)
bool hasMonolithBinaries (const std::unique_ptr< RIFF::File > &f)
std::vector< fs::path > readMonolithBinaryIndex (const std::unique_ptr< RIFF::File > &f, engine::Engine &e)
std::tuple< fs::path, fs::path, std::string > setupForCollection (const fs::path &path)
fs::path saveSubSample (const engine::Engine &e, sample::SampleManager::sampleMap_t &toCollect, const SampleID &id, const std::shared_ptr< sample::Sample > &sp)
sample::SampleManager::sampleMap_t getSamplePathsFor (const scxt::engine::Engine &e, int part, std::vector< fs::path > &tempFilesCreated)
void collectSamplesInto (const fs::path &collectDir, const scxt::engine::Engine &e, int part)
bool saveMulti (const fs::path &p, const scxt::engine::Engine &e, SaveStyles style)
bool savePart (const fs::path &p, const scxt::engine::Engine &e, int part, patch_io::SaveStyles style)
bool initFromResourceBundle (scxt::engine::Engine &engine, const std::string &file)
bool loadMulti (const fs::path &p, scxt::engine::Engine &engine)
bool loadPartInto (const fs::path &p, scxt::engine::Engine &engine, int part)
Enumeration Type Documentation
SaveStyles
enum SaveStyles
Enumerator
NO_SAMPLES
COLLECT_SAMPLES
AS_MONOLITH
Function Documentation
addSCManifest()
void addSCManifest (const std::unique_ptr< RIFF::File > & f, const std::string & type)
Referenced by saveMulti(), and savePart().
readSCManifest() [1/2]
std::unordered_map< std::string, std::string > readSCManifest (RIFF::File * f)
Referenced by loadMulti(), loadPartInto(), readSCManifest(), and SCMonolithSampleReader::SCMonolithSampleReader().
readSCManifest() [2/2]
std::unordered_map< std::string, std::string > readSCManifest (const std::unique_ptr< RIFF::File > & f)
References readSCManifest().
addSCDataChunk()
void addSCDataChunk (const std::unique_ptr< RIFF::File > & f, const std::string & msg)
Referenced by saveMulti(), and savePart().
readSCDataChunk()
std::string readSCDataChunk (const std::unique_ptr< RIFF::File > & f)
Referenced by loadMulti(), and loadPartInto().
addMonolithBinaries()
bool addMonolithBinaries (const std::unique_ptr< RIFF::File > & f, const engine::Engine & e, const sample::SampleManager::sampleMap_t & addThese)
References Engine::getMessageController(), Browser::isLoadableSingleSample(), SCLOG, and SCLOG_IF.
Referenced by saveMulti(), and savePart().
hasMonolithBinaries()
bool hasMonolithBinaries (const std::unique_ptr< RIFF::File > & f)
Referenced by loadMulti(), and loadPartInto().
readMonolithBinaryIndex()
std::vector< fs::path > readMonolithBinaryIndex (const std::unique_ptr< RIFF::File > & f, engine::Engine & e)
References SCLOG_IF.
Referenced by loadMulti(), and loadPartInto().
setupForCollection()
std::tuple< fs::path, fs::path, std::string > setupForCollection (const fs::path & path)
Referenced by saveMulti(), and savePart().
saveSubSample()
fs::path saveSubSample (const engine::Engine & e, sample::SampleManager::sampleMap_t & toCollect, const SampleID & id, const std::shared_ptr< sample::Sample > & sp)
References Sample::BD_F32, Sample::BD_I16, RIFFWavWriter::closeFile(), RIFFWavWriter::F32, Engine::getSampleManager(), RIFFWavWriter::openFile(), RIFFWavWriter::PCM16, RIFFWavWriter::pushSamplesF32(), RIFFWavWriter::pushSamplesI16(), SCLOG, RIFFWavWriter::startDataChunk(), RIFFWavWriter::writeFMTChunk(), and RIFFWavWriter::writeRIFFHeader().
Referenced by getSamplePathsFor().
getSamplePathsFor()
sample::SampleManager::sampleMap_t getSamplePathsFor (const scxt::engine::Engine & e, int part, std::vector< fs::path > & tempFilesCreated)
References Engine::getPatch(), Engine::getSampleManager(), Sample::isSourceTypeSubSampleFromMonolith(), saveSubSample(), and SCLOG.
Referenced by collectSamplesInto(), saveMulti(), and savePart().
collectSamplesInto()
void collectSamplesInto (const fs::path & collectDir, const scxt::engine::Engine & e, int part)
References Engine::getMessageController(), getSamplePathsFor(), SCLOG, and SCLOG_IF.
Referenced by saveMulti(), and savePart().
saveMulti()
bool saveMulti (const fs::path & p, const scxt::engine::Engine & e, SaveStyles style)
References addMonolithBinaries(), addSCDataChunk(), addSCManifest(), AS_MONOLITH, COLLECT_SAMPLES, collectSamplesInto(), Engine::FOR_MULTI, Engine::getMessageController(), Engine::getSampleManager(), getSamplePathsFor(), SCLOG, and setupForCollection().
Referenced by scxt::messaging::client::doSaveMulti().
savePart()
bool savePart (const fs::path & p, const scxt::engine::Engine & e, int part, patch_io::SaveStyles style)
References addMonolithBinaries(), addSCDataChunk(), addSCManifest(), AS_MONOLITH, COLLECT_SAMPLES, collectSamplesInto(), Engine::FOR_PART, Engine::getMessageController(), Engine::getPatch(), Engine::getSampleManager(), getSamplePathsFor(), SCLOG, and setupForCollection().
Referenced by scxt::messaging::client::doSavePart().
initFromResourceBundle()
bool initFromResourceBundle (scxt::engine::Engine & engine, const std::string & file)
References Engine::getMessageController(), Engine::immediatelyTerminateAllVoices(), SCLOG, and scxt::json::unstreamEngineState().
Referenced by scxt::messaging::client::doResetEngine().
loadMulti()
bool loadMulti (const fs::path & p, scxt::engine::Engine & engine)
References Engine::getMessageController(), hasMonolithBinaries(), Engine::immediatelyTerminateAllVoices(), readMonolithBinaryIndex(), readSCDataChunk(), readSCManifest(), SCLOG, SCLOG_IF, and scxt::json::unstreamEngineState().
Referenced by Engine::loadSampleIntoSelectedPartAndGroup(), and main().
loadPartInto()
bool loadPartInto (const fs::path & p, scxt::engine::Engine & engine, int part)
References Engine::getMessageController(), hasMonolithBinaries(), readMonolithBinaryIndex(), readSCDataChunk(), readSCManifest(), SCLOG, and SCLOG_IF.
Referenced by scxt::messaging::client::doLoadPartInto(), and Engine::loadSampleIntoSelectedPartAndGroup().