shortcircuit-xt: scxt::sample::compound Namespace Reference
scxt::sample::compound Namespace Reference
Classes
struct CompoundElement
Functions
std::vector< CompoundElement > getSF2SampleAddresses (const fs::path &)
std::vector< CompoundElement > getSF2InstrumentAddresses (const fs::path &)
std::vector< CompoundElement > getSFZCompoundList (const fs::path &)
std::vector< CompoundElement > getGIGCompoundList (const fs::path &)
std::vector< CompoundElement > getMultisampleCompoundList (const fs::path &)
Function Documentation
getSF2SampleAddresses()
std::vector< CompoundElement > getSF2SampleAddresses (const fs::path & p)
References CompoundElement::name, CompoundElement::SAMPLE, CompoundElement::sampleAddress, and Sample::SF2_FILE.
Referenced by Browser::expandForBrowser().
getSF2InstrumentAddresses()
std::vector< CompoundElement > getSF2InstrumentAddresses (const fs::path & p)
References CompoundElement::INSTRUMENT, CompoundElement::name, CompoundElement::sampleAddress, and Sample::SF2_FILE.
Referenced by Browser::expandForBrowser(), and Browser::getMultiInstrumentElements().
getSFZCompoundList()
std::vector< CompoundElement > getSFZCompoundList (const fs::path & p)
References scxt::extensionMatches(), Sample::FLAC_FILE, SFZParser::Header::group, CompoundElement::INSTRUMENT, main(), CompoundElement::name, SFZParser::Header::region, CompoundElement::SAMPLE, SCLOG, Sample::SFZ_FILE, and Sample::WAV_FILE.
Referenced by Browser::expandForBrowser().
getGIGCompoundList()
std::vector< CompoundElement > getGIGCompoundList (const fs::path & p)
References Sample::GIG_FILE, CompoundElement::INSTRUMENT, CompoundElement::name, CompoundElement::SAMPLE, and CompoundElement::sampleAddress.
Referenced by Browser::expandForBrowser().
getMultisampleCompoundList()
std::vector< CompoundElement > getMultisampleCompoundList (const fs::path & p)
References Browser::isLoadableSingleSample(), Sample::MULTISAMPLE_FILE, CompoundElement::name, CompoundElement::SAMPLE, CompoundElement::sampleAddress, and SCLOG.
Referenced by Browser::expandForBrowser().