shortcircuit-xt: scxt::json Namespace Reference
scxt::json Namespace Reference
Classes
struct scxt_traits
struct scxt_traits< ID< idType > >
Typedefs
using scxt_value = tao::json::basic_value< scxt_traits >
Functions
SC_STREAMDEF (datamodel::pmd, SC_FROM({ assert(SC_STREAMING_FOR_IN_PROCESS);std::vector< std::pair< int, std::string > > dvStream;for(const auto &[k, mv] :t.discreteValues) dvStream.emplace_back(k, mv);v={{"t",(int) t.type}, {"n", t.name}, {"mn", t.minVal}, {"mx", t.maxVal}, {"df", t.defaultVal}, {"ts", t.canTemposync}, {"ex", t.canExtend}, {"de", t.canDeactivate}, {"ab", t.canAbsolute}, {"enb", t.enabled}, {"tsm", t.temposyncMultiplier}, {"ssc", t.supportsStringConversion}, {"dsc",(int) t.displayScale}, {"unit", t.unit}, {"qt",(int) t.quantization}, {"qtp", t.quantizationParam}, {"cval", t.customValueLabelsWithAccuracy}, {"discv", dvStream}, {"dep", t.decimalPlaces}, {"svA", t.svA}, {"svB", t.svB}, {"svC", t.svC}, {"svD", t.svD}};}), SC_TO({ findEnumIf(v, "t", to.type);findIf(v, "n", to.name);findIf(v, "mn", to.minVal);findIf(v, "mx", to.maxVal);findIf(v, "df", to.defaultVal);findIf(v, "ts", to.canTemposync);findIf(v, "de", to.canDeactivate);findIf(v, "ex", to.canExtend);findIf(v, "ab", to.canAbsolute);findOrSet(v, "enb", true, to.enabled);findIf(v, "tsm", to.temposyncMultiplier);findIf(v, "ssc", to.supportsStringConversion);findEnumIf(v, "dsc", to.displayScale);findEnumIf(v, "qt", to.quantization);findIf(v, "qtp", to.quantizationParam);findIf(v, "unit", to.unit);findIf(v, "cval", to.customValueLabelsWithAccuracy);std::vector< std::pair< int, std::string > > dvStream;findIf(v, "discv", dvStream);for(const auto &[k, mv] :dvStream) to.discreteValues[k]=mv;findIf(v, "dep", to.decimalPlaces);findIf(v, "svA", to.svA);findIf(v, "svB", to.svB);findIf(v, "svC", to.svC);findIf(v, "svD", to.svD);}))
STREAM_ENUM (engine::Engine::TuningZoneResolution, engine::Engine::toStringTuningZoneResolution, engine::Engine::fromStringTuningZoneResolution)
STREAM_ENUM (engine::Engine::TuningMode, engine::Engine::toStringTuningMode, engine::Engine::fromStringTuningMode)
SC_STREAMDEF(scxt::engine::Engine, SC_FROM({ if(SC_STREAMING_FOR_IN_PROCESS) { SCLOG("Warning: Engine is streaming for state 'IN_PROCESS'");} v={{"streamingVersion", scxt::currentStreamingVersion}, {"streamingVersionHumanReadable", scxt::humanReadableVersion(scxt::currentStreamingVersion)}, {"patch", from.getPatch()}, {"runtimeConfig", from.runtimeConfig}, {"selectionManager", from.getSelectionManager()}, {"sampleManager", from.getSampleManager()}};}), SC_TO({ assert(to.getMessageController() ->threadingChecker.isSerialThread());auto sv{0};findIf(v, "streamingVersion", sv);SCLOG("Unstreaming engine state. Stream version : "<< scxt::humanReadableVersion(sv));engine::Engine::UnstreamGuard sg(sv);findIf(v, "sampleManager", *(to.getSampleManager()));findIf(v, "patch", *(to.getPatch()));findIf(v, "selectionManager", *(to.getSelectionManager()));findIf(v, "runtimeConfig", to.runtimeConfig);to.getPatch() ->setupPatchOnUnstream(to);to.onPartConfigurationUpdated();to.resetTuningFromRuntimeConfig();to.getPatch() ->setSampleRate(to.getSampleRate());})) SC_STREAMDEF(scxt SC_STREAMDEF(scxt::engine::Patch, SC_FROM({ v={{"parts", from.getParts()}, {"busses", from.busses}};}), SC_TO({ auto &patch=to;patch.resetToBlankPatch();auto vzones=v.at("parts").get_array();size_t idx{0};for(const auto vz :vzones) { vz.to(*(patch.getPart(idx)));idx++;} findIf(v, "busses", patch.busses);})) SC_STREAMDEF(scxt SC_STREAMDEF (scxt::engine::Macro, SC_FROM({ v={{"p", t.part}, {"i", t.index}, {"v", t.value}};addUnlessDefault< val_t >(v, "bp", false, t.isBipolar);addUnlessDefault< val_t >(v, "st", false, t.isStepped);addUnlessDefault< val_t >(v, "sc",(size_t) 1, t.stepCount);addUnlessDefault< val_t >(v, "nm", scxt::engine::Macro::defaultNameFor(t.index), t.name);}), SC_TO({ findIf(v, "v", result.value);findIf(v, "i", result.index);findIf(v, "p", result.part);findOrSet(v, "bp", false, result.isBipolar);findOrSet(v, "st", false, result.isStepped);findOrSet(v, "sc", 1, result.stepCount);findOrSet(v, "nm", scxt::engine::Macro::defaultNameFor(result.index), result.name);}))
SC_STREAMDEF (scxt::engine::Part::PartConfiguration, SC_FROM(v={{"a", from.active}, {"c", from.channel}, {"m", from.mute}, {"s", from.solo}, {"pv", from.polyLimitVoices}, {"mbr", from.mpePitchBendRange}, {"lv", from.level}, {"pan", from.pan}, {"tun", from.tuning}, {"xps", from.transpose}, {"rt",(int) from.routeTo}, {"nm", std::string(from.name)}, {"bl", std::string(from.blurb)}};), SC_TO({ findOrSet(v, "c", scxt::engine::Part::PartConfiguration::omniChannel, to.channel);findOrSet(v, "a", true, to.active);findOrSet(v, "m", false, to.mute);findOrSet(v, "s", false, to.solo);findOrSet(v, "pv", 0, to.polyLimitVoices);findOrSet(v, "mbr", 24, to.mpePitchBendRange);int rtv;findOrSet(v, "rt", scxt::engine::BusAddress::DEFAULT_BUS, rtv);to.routeTo=(scxt::engine::BusAddress) rtv;findOrSet(v, "lv", 1, to.level);findOrSet(v, "pan", 0, to.pan);findOrSet(v, "tun", 0, to.tuning);findOrSet(v, "xps", 0, to.transpose);std::string bStr;findOrSet(v, "bl", "", bStr);memset(to.blurb, 0, sizeof(to.blurb));strncpy(to.blurb, bStr.c_str(), sizeof(to.blurb) - 1);std::string nStr;findOrSet(v, "nm", "", nStr);if(!nStr.empty()) { memset(to.name, 0, sizeof(to.name));strncpy(to.name, nStr.c_str(), sizeof(to.name) - 1);} }))
SC_STREAMDEF(scxt::engine::Part::ZoneMappingItem, SC_FROM(v={{"a", from.address}, {"kr", from.kr}, {"vr", from.vr}, {"name", from.name}, {"features", from.features}};), SC_TO({ findIf(v, "a", to.address);findIf(v, "kr", to.kr);findIf(v, "vr", to.vr);findIf(v, "name", to.name);findIf(v, "features", to.features);})) SC_STREAMDEF(scxt SC_STREAMDEF (scxt::engine::GroupTriggerStorage, SC_FROM({ v={{"id", from.id}, {"args", from.args}};}), SC_TO({ findIf(v, "id", to.id);findIf(v, "args", to.args);}))
STREAM_ENUM (engine::GroupTriggerConditions::Conjunction, engine::GroupTriggerConditions::toStringGroupConditionsConjunction, engine::GroupTriggerConditions::fromStringConditionsConjunction)
SC_STREAMDEF (scxt::engine::GroupTriggerConditions, SC_FROM({ bool anyConfigured{false};for(const auto &c :from.storage) { anyConfigured|=(c.id !=scxt::engine::GroupTriggerID::NONE);} if(anyConfigured) { v={{"st", from.storage}, {"ac", from.active}, {"conj", from.conjunctions}};} else { v=tao::json::empty_object;} }), SC_TO({ findIf(v, "st", to.storage);findIf(v, "ac", to.active);findIf(v, "conj", to.conjunctions);}))
std::string groupInfoPlayModeTo (uint32_t p)
uint32_t groupInfoPlayModeFrom (const std::string &s)
std::string groupInfoPlayModeFeatureTo (uint64_t x)
uint64_t groupInfoPlayModeFeatureFrom (const std::string &x)
SC_STREAMDEF (scxt::engine::Group::GroupOutputInfo, SC_FROM({ v={{"amplitude", t.amplitude}, {"pan", t.pan}, {"tn", t.tuning}, {"oversample", t.oversample}, {"velocitySensitivity", t.velocitySensitivity}, {"muted", t.muted}, {"procRouting", t.procRouting}, {"prCon", t.procRoutingConsistent}, {"routeTo",(int) t.routeTo}, {"hip", t.hasIndependentPolyLimit}, {"pl", t.polyLimit}, {"mc", t.midiChannel}, {"pbu", t.pbUp}, {"pbd", t.pbDown}, {"vpm", groupInfoPlayModeTo(t.vmPlayModeInt)}, {"vpf", groupInfoPlayModeFeatureTo(t.vmPlayModeFeaturesInt)}};}), SC_TO({ findIf(v, "amplitude", result.amplitude);findIf(v, "pan", result.pan);findOrSet(v, "tn", 0.f, result.tuning);findIf(v, "muted", result.muted);findIf(v, "procRouting", result.procRouting);findIf(v, "velocitySensitivity", result.velocitySensitivity);findIf(v, "oversample", result.oversample);int rt{engine::BusAddress::DEFAULT_BUS};findIf(v, "routeTo", rt);findIf(v, "hip", result.hasIndependentPolyLimit);findIf(v, "pl", result.polyLimit);findOrSet(v, "prCon", true, result.procRoutingConsistent);findOrSet(v, "mc", -1, result.midiChannel);findOrSet(v, "pbu", 2, result.pbUp);findOrSet(v, "pbd", 2, result.pbDown);result.routeTo=(engine::BusAddress)(rt);std::string tmp;findIf(v, "vpm", tmp);result.vmPlayModeInt=groupInfoPlayModeFrom(tmp);findIf(v, "vpf", tmp);result.vmPlayModeFeaturesInt=groupInfoPlayModeFeatureFrom(tmp);}))
SC_STREAMDEF (scxt::engine::Group, SC_FROM({ v={{"zones", t.getZones()}, {"name", t.getName()}, {"outputInfo", t.outputInfo}, {"routingTable", t.routingTable}, {"gegStorage", t.gegStorage}, {"modulatorStorage", t.modulatorStorage}, {"miscSourceStorage", t.miscSourceStorage}, {"processorStorage", t.processorStorage}, {"triggerConditions", t.triggerConditions}};}), SC_TO({ auto &group=to;findIf(v, "name", group.name);findIf(v, "gegStorage", group.gegStorage);findIf(v, "outputInfo", group.outputInfo);findIf(v, "processorStorage", group.processorStorage);findIf(v, "routingTable", group.routingTable);findIf(v, "triggerConditions", group.triggerConditions);findIfArray(v, "modulatorStorage", group.modulatorStorage);findIf(v, "miscSourceStorage", group.miscSourceStorage);group.clearZones();auto vzones=v.at("zones").get_array();for(const auto vz :vzones) { auto idx=group.addZone(std::make_unique< scxt::engine::Zone >()) - 1;vz.to(*(group.getZone(idx)));if(group.parentPart &&group.parentPart->parentPatch &&group.parentPart->parentPatch->parentEngine) { group.getZone(idx) ->setupOnUnstream(*(group.parentPart->parentPatch->parentEngine));} } if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2025 '11 '12)) { for(auto &z :group) { if(z->mapping.pbUp==group.outputInfo.pbUp) { z->mapping.pbUp=-1;} if(z->mapping.pbDown==group.outputInfo.pbDown) { z->mapping.pbDown=-1;} } } group.setupOnUnstream(*(group.parentPart->parentPatch->parentEngine));}))
SC_STREAMDEF (scxt::engine::Zone::ZoneOutputInfo, SC_FROM({ v={{"amp", t.amplitude}, {"pan", t.pan}, {"to",(int) t.routeTo}};addUnlessDefault< val_t >(v, "prc", true, t.procRoutingConsistent);addUnlessDefault< val_t >(v, "prt", engine::Zone::ProcRoutingPath::procRoute_linear, t.procRouting);addUnlessDefault< val_t >(v, "muted", false, t.muted);}), SC_TO({ auto &zo=to;findIf(v, {"amp", "amplitude"}, zo.amplitude);findIf(v, "pan", zo.pan);findOrSet(v, "muted", false, zo.muted);findOrSet(v, "prc", true, zo.procRoutingConsistent);findOrSet(v, {"prt", "procRouting"}, engine::Zone::ProcRoutingPath::procRoute_linear, zo.procRouting);int rt{engine::BusAddress::DEFAULT_BUS};findIf(v, {"to", "routeTo"}, rt);if(rt >=engine::BusAddress::ERROR_BUS &&rt<=engine::BusAddress::AUX_0+numAux) zo.routeTo=(engine::BusAddress)(rt);else zo.routeTo=engine::BusAddress::DEFAULT_BUS;}))
SC_STREAMDEF (scxt::engine::Zone::ZoneMappingData, SC_FROM({ v={{"rootKey", t.rootKey}, {"keyR", t.keyboardRange}, {"velR", t.velocityRange}, {"pbDown", t.pbDown}, {"pbUp", t.pbUp}, {"exclusiveGroup", t.exclusiveGroup}, {"velocitySens", t.velocitySens}, {"amplitude", t.amplitude}, {"pan", t.pan}, {"pitchOffset", t.pitchOffset}, {"tracking", t.tracking}};}), SC_TO({ auto &zmd=to;findOrSet(v, "rootKey", 60, zmd.rootKey);findIf(v, {"keyR", "keyboardRange"}, zmd.keyboardRange);findIf(v, {"velR", "velocityRange"}, zmd.velocityRange);findIf(v, "pbDown", zmd.pbDown);findIf(v, "pbUp", zmd.pbUp);findIf(v, "amplitude", zmd.amplitude);if(SC_UNSTREAMING_FROM_THIS_OR_OLDER(0x2024 '06 '03)) { auto db=20 *std::log10(zmd.amplitude);zmd.amplitude=std::clamp(db, -36.f, 36.f);} findIf(v, "pan", zmd.pan);findIf(v, "pitchOffset", zmd.pitchOffset);findIf(v, "tracking", zmd.tracking);findOrSet(v, "velocitySens", 1.0, zmd.velocitySens);findOrSet(v, "exclusiveGroup", 0, zmd.exclusiveGroup);}))
STREAM_ENUM (engine::Zone::PlayMode, engine::Zone::toStringPlayMode, engine::Zone::fromStringPlayMode)
STREAM_ENUM (engine::Zone::LoopMode, engine::Zone::toStringLoopMode, engine::Zone::fromStringLoopMode)
STREAM_ENUM (engine::Zone::LoopDirection, engine::Zone::toStringLoopDirection, engine::Zone::fromStringLoopDirection)
STREAM_ENUM (engine::Zone::ProcRoutingPath, engine::Zone::toStringProcRoutingPath, engine::Zone::fromStringProcRoutingPath)
STREAM_ENUM (engine::Group::ProcRoutingPath, engine::Group::toStringProcRoutingPath, engine::Group::fromStringProcRoutingPath)
STREAM_ENUM (engine::Zone::VariantPlaybackMode, engine::Zone::toStringVariantPlaybackMode, engine::Zone::fromStringVariantPlaybackMode)
STREAM_ENUM (dsp::InterpolationTypes, dsp::toStringInterpolationTypes, dsp::fromStringInterpolationTypes)
STREAM_ENUM (engine::Clipboard::ContentType, engine::Clipboard::toStringContentType, engine::Clipboard::fromStringContentType)
SC_STREAMDEF (scxt::engine::Zone::SingleVariant, SC_FROM({ auto &s=from;if(s.active) { v={{"active", s.active}, {"id", s.sampleID}, {"startSample", s.startSample}, {"endSample", s.endSample}, {"startLoop", s.startLoop}, {"endLoop", s.endLoop}, {"playMode", s.playMode}, {"loopActive", s.loopActive}, {"playReverse", s.playReverse}, {"loopMode", s.loopMode}, {"loopDirection", s.loopDirection}, {"loopCountWhenCounted", s.loopCountWhenCounted}, {"interpolationType", s.interpolationType}, {"loopFade", s.loopFade}, {"normalizationAmplitude", s.normalizationAmplitude}, {"pitchOffset", s.pitchOffset}, {"amplitude", s.amplitude}, {"pan", s.pan}};} else { v=tao::json::empty_object;} }), SC_TO({ auto &s=to;findOrSet(v, "active", false, s.active);if(s.active) { findIf(v, "id", s.sampleID);findOrSet(v, "startSample", -1, s.startSample);findOrSet(v, "endSample", -1, s.endSample);findOrSet(v, "startLoop", -1, s.startLoop);findOrSet(v, "endLoop", -1, s.endLoop);findOrSet(v, "playMode", engine::Zone::PlayMode::NORMAL, s.playMode);findOrSet(v, "loopActive", false, s.loopActive);findOrSet(v, "playReverse", false, s.playReverse);findOrSet(v, "loopMode", engine::Zone::LoopMode::LOOP_DURING_VOICE, s.loopMode);findOrSet(v, "loopDirection", engine::Zone::LoopDirection::FORWARD_ONLY, s.loopDirection);findOrSet(v, "loopFade", 0, s.loopFade);findOrSet(v, "interpolationType", dsp::InterpolationTypes::Sinc, s.interpolationType);findOrSet(v, "loopCountWhenCounted", 0, s.loopCountWhenCounted);findOrSet(v, "normalizationAmplitude", 1.f, s.normalizationAmplitude);findOrSet(v, "amplitude", 1.f, s.amplitude);if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2025 '06 '19)) { if(s.normalizationAmplitude< 1e-3) s.normalizationAmplitude=1;if(s.amplitude< 1e-3) s.amplitude=1;} findOrSet(v, "pitchOffset", 0.f, s.pitchOffset);findOrSet(v, "pan", 0.f, s.pan);} else { s=scxt::engine::Zone::SingleVariant();assert(!s.active);} }))
SC_STREAMDEF (scxt::engine::Zone::Variants, SC_FROM({ v={{"variants", t.variants}, {"variantPlaybackMode", t.variantPlaybackMode}};}), SC_TO({ findIf(v, {"variants", "samples"}, result.variants);findIf(v, "variantPlaybackMode", result.variantPlaybackMode);}))
SC_STREAMDEF (scxt::engine::Zone, SC_FROM({ auto useGivenName=t.givenName;if(useGivenName.empty() &&!t.variantData.variants[0].active) { SCLOG("Crystalizing given name on stream");useGivenName=t.getName();} v={{"variantData", t.variantData}, {"mappingData", t.mapping}, {"outputInfo", t.outputInfo}, {"processorStorage", t.processorStorage}, {"routingTable", t.routingTable}, {"modulatorStorage", t.modulatorStorage}, {"miscSourceStorage", t.miscSourceStorage}, {"egs", t.egStorage}, {"givenName", useGivenName}};}), SC_TO({ auto &zone=to;findIf(v, {"variantData", "sampleData"}, zone.variantData);findIf(v, "mappingData", zone.mapping);findIf(v, "outputInfo", zone.outputInfo);fromArrayWithSizeDifference< Traits >(v.at("processorStorage"), zone.processorStorage);findIf(v, "routingTable", zone.routingTable);findIfArray(v, "modulatorStorage", zone.modulatorStorage);findIf(v, "miscSourceStorage", zone.miscSourceStorage);if(v.find("aegStorage")) { findOrDefault(v, "aegStorage", zone.egStorage[0]);findOrDefault(v, "eg2Storage", zone.egStorage[1]);} else if(v.find("egs")) { fromArrayWithSizeDifference< Traits >(v.at("egs"), zone.egStorage);} else { SCLOG("Warning: No EG storage in zone");} findOrSet(v, "givenName", "", zone.givenName);zone.onRoutingChanged();}))
SC_STREAMDEF (scxt::engine::KeyboardRange, SC_FROM({ v={{"ks", t.keyStart}, {"ke", t.keyEnd}, {"fs", t.fadeStart}, {"fe", t.fadeEnd}};}), SC_TO({ findIf(v, {"ks", "keyStart"}, to.keyStart);findIf(v, {"ke", "keyEnd"}, to.keyEnd);findIf(v, {"fs", "fadeStart"}, to.fadeStart);findIf(v, {"fe", "fadeEnd"}, to.fadeEnd);}))
SC_STREAMDEF (scxt::engine::VelocityRange, SC_FROM({ v={{"vs", t.velStart}, {"ve", t.velEnd}, {"fs", t.fadeStart}, {"fe", t.fadeEnd}};}), SC_TO({ findIf(v, {"vs", "velStart"}, to.velStart);findIf(v, {"ve", "velEnd"}, to.velEnd);findIf(v, {"fs", "fadeStart"}, to.fadeStart);findIf(v, {"fe", "fadeEnd"}, to.fadeEnd);}))
SC_STREAMDEF (engine::Engine::EngineStatusMessage, SC_FROM({ v={{"isAudioRunning", t.isAudioRunning}, {"sampleRate", t.sampleRate}, {"runningEnvironment", t.runningEnvironment}};}), SC_TO({ findIf(v, "isAudioRunning", to.isAudioRunning);findIf(v, "sampleRate", to.sampleRate);findIf(v, "runningEnvironment", to.runningEnvironment);}))
SC_STREAMDEF (engine::Bus, SC_FROM({ v={{"busSendStorage", t.busSendStorage}, {"busEffectStorage", t.busEffectStorage}};}), SC_TO({ findIf(v, "busSendStorage", to.busSendStorage);findIf(v, "busEffectStorage", to.busEffectStorage);to.resetSendState();}))
STREAM_ENUM_WITH_DEFAULT(engine::Bus::BusSendStorage::AuxLocation, engine::Bus::BusSendStorage::AuxLocation::POST_VCA, engine::Bus::BusSendStorage::toStringAuxLocation, engine::Bus::BusSendStorage::fromStringAuxLocation) SC_STREAMDEF(engine SC_STREAMDEF (engine::BusEffectStorage, SC_FROM({ if(from.type==scxt::engine::AvailableBusEffects::none) { v=tao::json::empty_object;} else { v={{"t", scxt::engine::toStringAvailableBusEffects(from.type)}, {"isActive", from.isActive}, {"p", from.params}, {"deact", from.deact}, {"temposync", from.isTemposync}, {"streamingVersion", from.streamingVersion}};} }), SC_TO({ std::string tp{ scxt::engine::toStringAvailableBusEffects(engine::AvailableBusEffects::none)};findIf(v, {"t", "type"}, tp);to.type=scxt::engine::fromStringAvailableBusEffects(tp);if(to.type==engine::AvailableBusEffects::none) { to=engine::BusEffectStorage();to.type=engine::AvailableBusEffects::none;} else { findIf(v, {"p", "params"}, to.params);findOrSet(v, "isActive", true, to.isActive);findIf(v, "deact", to.deact);findIf(v, "temposync", to.isTemposync);findOrSet(v, "streamingVersion", -1, result.streamingVersion);if(result.streamingVersion > 0) { auto[csv, fn]=scxt::engine::getBusEffectRemapStreamingFunction(result.type);if(csv !=result.streamingVersion) { assert(fn);if(fn) fn(result.streamingVersion, result.params.data());result.streamingVersion=csv;} } } }))
SC_STREAMDEF (engine::Patch::Busses, SC_FROM({ v={{"mainBus", t.mainBus}, {"partBusses", t.partBusses}, {"auxBusses", t.auxBusses}};}), SC_TO({ findIf(v, "mainBus", to.mainBus);findIf(v, "partBusses", to.partBusses);findIf(v, "auxBusses", to.auxBusses);to.reconfigureSolo();to.reconfigureOutputBusses();}))
SC_STREAMDEF (scxt::engine::MissingResolutionWorkItem, SC_FROM({ v={{"i", from.missingID}, {"p", from.path.u8string()}, {"m", from.isMultiUsed}};}), SC_TO({ findIf(v, "i", to.missingID);findOrSet(v, "m", false, to.isMultiUsed);std::string fp;findIf(v, "p", fp);to.path=fs::path(fs::u8path(fp));}))
SC_STREAMDEF(scxt::modulation::modulators::StepLFOStorage, SC_FROM({ v={{"data", t.data}, {"repeat", t.repeat}, {"rateIsForSingleStep", t.rateIsForSingleStep}, {"smooth", t.smooth}};}), SC_TO({ findIf(v, "data", result.data);findIf(v, "repeat", result.repeat);findIf(v, "smooth", result.smooth);findIf(v, "rateIsForSingleStep", result.rateIsForSingleStep);})) SC_STREAMDEF(scxt STREAM_ENUM (modulation::modulators::PhasorStorage::SyncMode, modulation::modulators::PhasorStorage::toStringSyncMode, modulation::modulators::PhasorStorage::fromStringSyncMode)
STREAM_ENUM (modulation::modulators::PhasorStorage::Direction, modulation::modulators::PhasorStorage::toStringDirection, modulation::modulators::PhasorStorage::fromStringDirection)
SC_STREAMDEF (modulation::modulators::PhasorStorage, SC_FROM({ v=tao::json::empty_object;using ps=modulation::modulators::PhasorStorage;addUnlessDefault< val_t >(v, "di", ps::Division::NOTE, from.division);addUnlessDefault< val_t >(v, "sy", ps::SyncMode::VOICEPOS, from.syncMode);addUnlessDefault< val_t >(v, "a", ps::Direction::ASCENDING, from.direction);addUnlessDefault< val_t >(v, "nu", 1, from.numerator);addUnlessDefault< val_t >(v, "de", 4, from.denominator);addUnlessDefault< val_t >(v, "ph", 0.f, from.phase);}), SC_TO({ using ps=modulation::modulators::PhasorStorage;findOrSet(v, "di", ps::Division::NOTE, to.division);findOrSet(v, "sy", ps::SyncMode::VOICEPOS, to.syncMode);findOrSet(v, "a", ps::Direction::ASCENDING, to.direction);findOrSet(v, "nu", 1, to.numerator);findOrSet(v, "de", 4, to.denominator);findOrSet(v, "ph", 0, to.phase);}))
STREAM_ENUM (modulation::modulators::RandomStorage::Style, modulation::modulators::RandomStorage::toStringStyle, modulation::modulators::RandomStorage::fromStringStyle)
SC_STREAMDEF (modulation::modulators::RandomStorage, SC_FROM({ v=tao::json::empty_object;addUnlessDefault< val_t >(v, "st", modulation::modulators::RandomStorage::Style::UNIFORM_01, from.style);}), SC_TO({ findOrSet(v, "st", modulation::modulators::RandomStorage::Style::UNIFORM_01, to.style);}))
SC_STREAMDEF (modulation::MiscSourceStorage, SC_FROM({ v={{"rs", t.randoms}, {"ps", t.phasors}};}), SC_TO({ findIfArray(v, "rs", to.randoms);findIfArray(v, "ps", to.phasors);}))
STREAM_ENUM (modulation::ModulatorStorage::ModulatorShape, modulation::ModulatorStorage::toStringModulatorShape, modulation::ModulatorStorage::fromStringModulatorShape)
STREAM_ENUM (modulation::ModulatorStorage::TriggerMode, modulation::ModulatorStorage::toStringTriggerMode, modulation::ModulatorStorage::fromStringTriggerMode)
SC_STREAMDEF (scxt::modulation::shared::RoutingExtraPayload, SC_FROM({ v={{"selC", t.selConsistent}, {"targetMetadata", t.targetMetadata}, {"targetBaseValue", t.targetBaseValue}};}), SC_TO({ findIf(v, "selC", result.selConsistent);findIf(v, "targetMetadata", result.targetMetadata);findIf(v, "targetBaseValue", result.targetBaseValue);}))
SC_STREAMDEF (scxt::voice::modulation::Matrix::RoutingTable::Routing, SC_FROM({ if(t.hasDefaultValues()) { v=tao::json::empty_object;} else { v={{"active", t.active}, {"source", t.source}, {"sourceVia", t.sourceVia}, {"target", t.target}, {"curve", t.curve}, {"depth", t.depth}, {"srcLMS", t.sourceLagMS}, {"srVLMS", t.sourceViaLagMS}, {"srcLE", t.sourceLagExp}, {"srVLE", t.sourceViaLagExp}, {"appm", t.applicationMode}};if(SC_STREAMING_FOR_IN_PROCESS) addToObject< val_t >(v, "extraPayload", t.extraPayload);} }), SC_TO({ result=rt_t();findIf(v, "active", result.active);findIf(v, "source", result.source);findIf(v, "sourceVia", result.sourceVia);findIf(v, "target", result.target);findIf(v, "curve", result.curve);findIf(v, "depth", result.depth);findIf(v, "extraPayload", result.extraPayload);findOrSet(v, "srcLMS", 0, result.sourceLagMS);findOrSet(v, "srVLMS", 0, result.sourceViaLagMS);findOrSet(v, "srcLE", true, result.sourceLagExp);findOrSet(v, "srVLE", true, result.sourceViaLagExp);findOrSet(v, "appm", 0, result.applicationMode);}))
SC_STREAMDEF (scxt::voice::modulation::Matrix::RoutingTable, SC_FROM({ v={{"routes", t.routes}};}), SC_TO({ const auto &object=v.get_object();std::fill(result.routes.begin(), result.routes.end(), rt_t::Routing());if(v.find("routes")) { fromArrayWithSizeDifference(v.at("routes"), result.routes);} }))
SC_STREAMDEF (scxt::modulation::GroupMatrix::RoutingTable::Routing, SC_FROM({ if(t.hasDefaultValues()) { v=tao::json::empty_object;} else { v={{"active", t.active}, {"source", t.source}, {"sourceVia", t.sourceVia}, {"target", t.target}, {"curve", t.curve}, {"depth", t.depth}, {"srcLMS", t.sourceLagMS}, {"srVLMS", t.sourceViaLagMS}, {"srcLE", t.sourceLagExp}, {"srVLE", t.sourceViaLagExp}, {"appm", t.applicationMode}};if(SC_STREAMING_FOR_IN_PROCESS) addToObject< val_t >(v, "extraPayload", t.extraPayload);} }), SC_TO({ result=rt_t();findIf(v, "active", result.active);findIf(v, "source", result.source);findIf(v, "sourceVia", result.sourceVia);findIf(v, "target", result.target);findIf(v, "curve", result.curve);findIf(v, "depth", result.depth);findOrSet(v, "srcLMS", 0, result.sourceLagMS);findOrSet(v, "srVLMS", 0, result.sourceViaLagMS);findOrSet(v, "srcLE", true, result.sourceLagExp);findOrSet(v, "srVLE", true, result.sourceViaLagExp);findOrSet(v, "appm", 0, result.applicationMode);findIf(v, "extraPayload", result.extraPayload);}))
SC_STREAMDEF (scxt::modulation::GroupMatrix::RoutingTable, SC_FROM({ v={{"routes", t.routes}};}), SC_TO({ const auto &object=v.get_object();std::fill(result.routes.begin(), result.routes.end(), rt_t::Routing());if(v.find("routes")) { fromArrayWithSizeDifference(v.at("routes"), result.routes);} }))
SC_STREAMDEF (scxt::sample::Sample::SourceType, SC_FROM({ static constexpr const char *key="sourceType";switch(from) { case sample::Sample::WAV_FILE:v="wav";break;case sample::Sample::FLAC_FILE:v="flac";break;case sample::Sample::MP3_FILE:v="mp3";break;case sample::Sample::SF2_FILE:v="sf2";break;case sample::Sample::SFZ_FILE:v="sfz";break;case sample::Sample::AIFF_FILE:v="aiff";break;case sample::Sample::MULTISAMPLE_FILE:v="multisample";break;case sample::Sample::GIG_FILE:v="gig";break;case sample::Sample::SCXT_FILE:v="scxt";break;} }), SC_TO({ if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '08 '16)) { static constexpr const char *key="sourceType";std::string k{};findIf(v, key, k);if(k=="wav_file") to=sample::Sample::WAV_FILE;if(k=="sf2_file") to=sample::Sample::SF2_FILE;if(k=="flac_file") to=sample::Sample::FLAC_FILE;if(k=="mp3_file") to=sample::Sample::MP3_FILE;if(k=="aiff_file") to=sample::Sample::AIFF_FILE;if(k=="multisample_file") to=sample::Sample::MULTISAMPLE_FILE;} else { if(!v.is_string()) { throw std::logic_error("Unstreamed non-string");} auto k=v.get_string();if(k=="wav") to=sample::Sample::WAV_FILE;if(k=="sf2") to=sample::Sample::SF2_FILE;if(k=="flac") to=sample::Sample::FLAC_FILE;if(k=="mp3") to=sample::Sample::MP3_FILE;if(k=="aiff") to=sample::Sample::AIFF_FILE;if(k=="multisample") to=sample::Sample::MULTISAMPLE_FILE;if(k=="gig") to=sample::Sample::GIG_FILE;if(k=="scxt") to=sample::Sample::SCXT_FILE;} return;}))
SC_STREAMDEF (sample::Sample::SampleFileAddress, SC_FROM({ auto ppref=from.path;v={{"type", from.type}, {"path", ppref.u8string()}, {"md5sum", from.md5sum}};if(from.type==sample::Sample::SF2_FILE||from.type==sample::Sample::MULTISAMPLE_FILE||from.type==sample::Sample::GIG_FILE||from.type==sample::Sample::SCXT_FILE) { addToObject< val_t >(v, "preset", from.preset);addToObject< val_t >(v, "instrument", from.instrument);addToObject< val_t >(v, "region", from.region);} }), SC_TO({ findOrSet(v, "type", sample::Sample::WAV_FILE, to.type);std::string p;findIf(v, "path", p);to.path=unstreamPathFromString(p);findIf(v, "md5sum", to.md5sum);findOrSet(v, "preset", 0, to.preset);findOrSet(v, "instrument", -1, to.instrument);findOrSet(v, "region", -1, to.region);}))
SC_STREAMDEF (scxt::sample::SampleManager, SC_FROM({ v={{"sampleAddresses", from.getSampleAddressesAndIDs()}};}), SC_TO({ to.reset();sample::SampleManager::sampleAddressesAndIds_t res;findIf(v, "sampleAddresses", res);to.restoreFromSampleAddressesAndIDs(res);}))
SC_STREAMDEF (scxt::sample::compound::CompoundElement, SC_FROM({ v={{"type",(int32_t) from.type}, {"name", from.name}, {"addr", from.sampleAddress}};}), SC_TO({ int t;findOrSet(v, "type", 0, t);to.type=(scxt::sample::compound::CompoundElement::Type) t;findIf(v, "name", to.name);findIf(v, "addr", to.sampleAddress);}))
template<typename V , typename R >
bool findIf (V &v, const std::string &key, R &r)
template<typename V , typename R >
bool findIf (V &v, const std::initializer_list< std::string > &keys, R &r)
template<typename V , typename R >
bool findEnumIf (V &v, const std::string &key, R &r)
template<typename V , typename D , typename R >
void findOrSet (V &v, const std::string &key, const D &d, R &r)
Extract json element key from type v onto r, using d as the default if the key is not.
template<typename V , typename D , typename R >
void findOrSet (V &v, const std::initializer_list< std::string > &keys, const D &d, R &r)
template<typename V , typename R >
void findOrDefault (V &v, const std::string &key, R &r)
template<typename T , typename V , typename R >
void addToObject (V &v, const std::string &key, const R &val)
template<typename T , typename V , typename R >
void addUnlessDefault (V &v, const std::string &key, const R &defVal, const R &val)
fs::path unstreamPathFromString (const std::string &s)
SC_STREAMDEF (scxt::selection::SelectionManager::SelectActionContents, SC_FROM({ auto &e=from;assert(SC_STREAMING_FOR_IN_PROCESS);v={{"p", e.part}, {"g", e.group}, {"z", e.zone}, {"s", e.selecting}, {"d", e.distinct}, {"sl", e.selectingAsLead}, {"fz", e.forZone}};}), SC_TO({ auto &z=to;findIf(v, "p", z.part);findIf(v, "g", z.group);findIf(v, "z", z.zone);findIf(v, "s", z.selecting);findIf(v, "d", z.distinct);findIf(v, "sl", z.selectingAsLead);findIf(v, "fz", z.forZone);}))
SC_STREAMDEF (scxt::selection::SelectionManager::ZoneAddress, SC_FROM({ if(t.part==-1 &&t.group==-1 &&t.zone==-1) { v=tao::json::empty_object;} else { v={{"p", t.part}, {"g", t.group}, {"z", t.zone}};} }), SC_TO({ findOrSet(v, {"p", "part"}, -1, result.part);findOrSet(v, {"g", "group"}, -1, result.group);findOrSet(v, {"z", "zone"}, -1, result.zone);}))
SC_STREAMDEF (selection::SelectionManager, SC_FROM({ auto &e=from;v={{"zones", e.allSelectedZones}, {"leadZone", e.leadZone}, {"groups", e.allSelectedGroups}, {"tabs", e.otherTabSelection}, {"selectedPart", e.selectedPart}};}), SC_TO({ auto &z=to;if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '07 '24)) { z.selectedPart=0;findIf(v, "tabs", z.otherTabSelection);findIf(v, "zones", z.allSelectedZones[0]);findIf(v, "groups", z.allSelectedGroups[0]);findIf(v, "leadZone", z.leadZone[0]);} else { findIf(v, "tabs", z.otherTabSelection);findIf(v, "zones", z.allSelectedZones);findIf(v, "groups", z.allSelectedGroups);findIf(v, "leadZone", z.leadZone);findIf(v, "selectedPart", z.selectedPart);} selection::SelectionManager::ZoneAddress za;if(!z.allSelectedZones[z.selectedPart].empty()) { selection::SelectionManager::SelectActionContents sac{ z.leadZone[z.selectedPart]};sac.distinct=false;sac.selectingAsLead=true;sac.selecting=true;z.applySelectActions({sac});} }))
template<template< typename... > class... Transformers, template< typename... > class Traits>
void to_pretty_stream (std::ostream &os, const tao::json::basic_value< Traits > &v)
template<typename T >
std::string streamValue (const T &v, bool pretty)
std::string streamPatch (const engine::Patch &p, bool pretty)
std::string streamEngineState (const engine::Engine &e, bool pretty)
void unstreamEngineState (engine::Engine &e, const std::string &data, bool msgPack)
void unstreamPartState (engine::Engine &e, int part, const std::string &data, bool msgPack)
SC_STREAMDEF (scxt::SampleID, SC_FROM(v={{"m", from.md5}, {"a", from.multiAddress}, {"p", from.pathHash}});, SC_TO(auto vs=v.find("m");if(vs) { std::string m5;vs->to(m5);strncpy(to.md5, m5.c_str(), scxt::SampleID::md5len+1);findIf(v, "a", to.multiAddress);findIf(v, "p", to.pathHash);} else { std::string legType{"t"}, legID{"i"};if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '08 '06)) { legType="idType";legID="id";} if(6 !=v.at(legType).template as< int32_t >()) { SCLOG("Unstreamed a non-6 type from legacy");} int32_t id;v.at(legID).to(id);to.setAsLegacy(id);}))
Variables
SC_STREAMDEF(scxt::modulation::ModulatorStorage, SC_FROM({ v={{"modulatorShape", t.modulatorShape}, {"triggerMode", t.triggerMode}, {"rate", t.rate}, {"start_phase", t.start_phase}, {"temposync", t.temposync}, {"curveLfoStorage", t.curveLfoStorage}, {"stepLfoStorage", t.stepLfoStorage}, {"envLfoStorage", t.envLfoStorage}};addUnlessDefault< val_t >(v, "cn", true, t.modulatorConsistent);}), SC_TO({ const auto &object=v.get_object();findIf(v, "modulatorShape", result.modulatorShape);findIf(v, "triggerMode", result.triggerMode);findIf(v, "rate", result.rate);findIf(v, "start_phase", result.start_phase);findIf(v, "temposync", result.temposync);findIf(v, "curveLfoStorage", result.curveLfoStorage);findIf(v, "stepLfoStorage", result.stepLfoStorage);findIf(v, "envLfoStorage", result.envLfoStorage);findOrSet(v, "cn", true, result.modulatorConsistent);result.configureCalculatedState();})) SC_STREAMDEF(scxt SC_STREAMDEF (scxt::modulation::shared::SourceIdentifier, SC_FROM({ v={{"g", t.gid}, {"t", t.tid}, {"i", t.index}};}), SC_TO({ findIf(v, "g", result.gid);findIf(v, "t", result.tid);findIf(v, "i", result.index);}))
Typedef Documentation
scxt_value
using scxt_value = tao::json::basic_value<scxt_traits>
Function Documentation
SC_STREAMDEF() [1/35]
SC_STREAMDEF (datamodel::pmd , SC_FROM({ assert(SC_STREAMING_FOR_IN_PROCESS);std::vector< std::pair< int, std::string > > dvStream;for(const auto &[k, mv] :t.discreteValues) dvStream.emplace_back(k, mv);v={{"t",(int) t.type}, {"n", t.name}, {"mn", t.minVal}, {"mx", t.maxVal}, {"df", t.defaultVal}, {"ts", t.canTemposync}, {"ex", t.canExtend}, {"de", t.canDeactivate}, {"ab", t.canAbsolute}, {"enb", t.enabled}, {"tsm", t.temposyncMultiplier}, {"ssc", t.supportsStringConversion}, {"dsc",(int) t.displayScale}, {"unit", t.unit}, {"qt",(int) t.quantization}, {"qtp", t.quantizationParam}, {"cval", t.customValueLabelsWithAccuracy}, {"discv", dvStream}, {"dep", t.decimalPlaces}, {"svA", t.svA}, {"svB", t.svB}, {"svC", t.svC}, {"svD", t.svD}};}) , SC_TO({ findEnumIf(v, "t", to.type);findIf(v, "n", to.name);findIf(v, "mn", to.minVal);findIf(v, "mx", to.maxVal);findIf(v, "df", to.defaultVal);findIf(v, "ts", to.canTemposync);findIf(v, "de", to.canDeactivate);findIf(v, "ex", to.canExtend);findIf(v, "ab", to.canAbsolute);findOrSet(v, "enb", true, to.enabled);findIf(v, "tsm", to.temposyncMultiplier);findIf(v, "ssc", to.supportsStringConversion);findEnumIf(v, "dsc", to.displayScale);findEnumIf(v, "qt", to.quantization);findIf(v, "qtp", to.quantizationParam);findIf(v, "unit", to.unit);findIf(v, "cval", to.customValueLabelsWithAccuracy);std::vector< std::pair< int, std::string > > dvStream;findIf(v, "discv", dvStream);for(const auto &[k, mv] :dvStream) to.discreteValues[k]=mv;findIf(v, "dep", to.decimalPlaces);findIf(v, "svA", to.svA);findIf(v, "svB", to.svB);findIf(v, "svC", to.svC);findIf(v, "svD", to.svD);}))
References SC_STREAMING_FOR_IN_PROCESS.
STREAM_ENUM() [1/16]
STREAM_ENUM (engine::Engine::TuningZoneResolution , engine::Engine::toStringTuningZoneResolution , engine::Engine::fromStringTuningZoneResolution)
STREAM_ENUM() [2/16]
STREAM_ENUM (engine::Engine::TuningMode , engine::Engine::toStringTuningMode , engine::Engine::fromStringTuningMode)
SC_STREAMDEF() [2/35]
SC_STREAMDEF(scxt::engine::Engine, SC_FROM({ if(SC_STREAMING_FOR_IN_PROCESS) { SCLOG("Warning: Engine is streaming for state 'IN_PROCESS'"); } v={{"streamingVersion", scxt::currentStreamingVersion}, {"streamingVersionHumanReadable", scxt::humanReadableVersion(scxt::currentStreamingVersion)}, {"patch", from.getPatch()}, {"runtimeConfig", from.runtimeConfig}, {"selectionManager", from.getSelectionManager()}, {"sampleManager", from.getSampleManager()}}; }), SC_TO({ assert(to.getMessageController() ->threadingChecker.isSerialThread()); auto sv{0}; findIf(v, "streamingVersion", sv); SCLOG("Unstreaming engine state. Stream version : "<< scxt::humanReadableVersion(sv)); engine::Engine::UnstreamGuard sg(sv); findIf(v, "sampleManager", *(to.getSampleManager())); findIf(v, "patch", *(to.getPatch())); findIf(v, "selectionManager", *(to.getSelectionManager())); findIf(v, "runtimeConfig", to.runtimeConfig); to.getPatch() ->setupPatchOnUnstream(to); to.onPartConfigurationUpdated(); to.resetTuningFromRuntimeConfig(); to.getPatch() ->setSampleRate(to.getSampleRate()); })) SC_STREAMDEF(scxt SC_STREAMDEF(scxt::engine::Patch, SC_FROM({ v={{"parts", from.getParts()}, {"busses", from.busses}};}), SC_TO({ auto &patch=to; patch.resetToBlankPatch(); auto vzones=v.at("parts").get_array(); size_t idx{0}; for(const auto vz :vzones) { vz.to(*(patch.getPart(idx))); idx++; } findIf(v, "busses", patch.busses); })) SC_STREAMDEF(scxt SC_STREAMDEF (scxt::engine::Macro , SC_FROM({ v={{"p", t.part}, {"i", t.index}, {"v", t.value}};addUnlessDefault< val_t >(v, "bp", false, t.isBipolar);addUnlessDefault< val_t >(v, "st", false, t.isStepped);addUnlessDefault< val_t >(v, "sc",(size_t) 1, t.stepCount);addUnlessDefault< val_t >(v, "nm", scxt::engine::Macro::defaultNameFor(t.index), t.name);}) , SC_TO({ findIf(v, "v", result.value);findIf(v, "i", result.index);findIf(v, "p", result.part);findOrSet(v, "bp", false, result.isBipolar);findOrSet(v, "st", false, result.isStepped);findOrSet(v, "sc", 1, result.stepCount);findOrSet(v, "nm", scxt::engine::Macro::defaultNameFor(result.index), result.name);}))
References Macro::defaultNameFor().
SC_STREAMDEF() [3/35]
SC_STREAMDEF (scxt::engine::Part::PartConfiguration , SC_FROM(v={{"a", from.active}, {"c", from.channel}, {"m", from.mute}, {"s", from.solo}, {"pv", from.polyLimitVoices}, {"mbr", from.mpePitchBendRange}, {"lv", from.level}, {"pan", from.pan}, {"tun", from.tuning}, {"xps", from.transpose}, {"rt",(int) from.routeTo}, {"nm", std::string(from.name)}, {"bl", std::string(from.blurb)}};) , SC_TO({ findOrSet(v, "c", scxt::engine::Part::PartConfiguration::omniChannel, to.channel);findOrSet(v, "a", true, to.active);findOrSet(v, "m", false, to.mute);findOrSet(v, "s", false, to.solo);findOrSet(v, "pv", 0, to.polyLimitVoices);findOrSet(v, "mbr", 24, to.mpePitchBendRange);int rtv;findOrSet(v, "rt", scxt::engine::BusAddress::DEFAULT_BUS, rtv);to.routeTo=(scxt::engine::BusAddress) rtv;findOrSet(v, "lv", 1, to.level);findOrSet(v, "pan", 0, to.pan);findOrSet(v, "tun", 0, to.tuning);findOrSet(v, "xps", 0, to.transpose);std::string bStr;findOrSet(v, "bl", "", bStr);memset(to.blurb, 0, sizeof(to.blurb));strncpy(to.blurb, bStr.c_str(), sizeof(to.blurb) - 1);std::string nStr;findOrSet(v, "nm", "", nStr);if(!nStr.empty()) { memset(to.name, 0, sizeof(to.name));strncpy(to.name, nStr.c_str(), sizeof(to.name) - 1);} }))
SC_STREAMDEF() [4/35]
SC_STREAMDEF(scxt::engine::Part::ZoneMappingItem, SC_FROM(v={{"a", from.address}, {"kr", from.kr}, {"vr", from.vr}, {"name", from.name}, {"features", from.features}};), SC_TO({ findIf(v, "a", to.address); findIf(v, "kr", to.kr); findIf(v, "vr", to.vr); findIf(v, "name", to.name); findIf(v, "features", to.features); })) SC_STREAMDEF(scxt SC_STREAMDEF (scxt::engine::GroupTriggerStorage , SC_FROM({ v={{"id", from.id}, {"args", from.args}};}) , SC_TO({ findIf(v, "id", to.id);findIf(v, "args", to.args);}))
STREAM_ENUM() [3/16]
STREAM_ENUM (engine::GroupTriggerConditions::Conjunction , engine::GroupTriggerConditions::toStringGroupConditionsConjunction , engine::GroupTriggerConditions::fromStringConditionsConjunction)
SC_STREAMDEF() [5/35]
SC_STREAMDEF (scxt::engine::GroupTriggerConditions , SC_FROM({ bool anyConfigured{false};for(const auto &c :from.storage) { anyConfigured|=(c.id !=scxt::engine::GroupTriggerID::NONE);} if(anyConfigured) { v={{"st", from.storage}, {"ac", from.active}, {"conj", from.conjunctions}};} else { v=tao::json::empty_object;} }) , SC_TO({ findIf(v, "st", to.storage);findIf(v, "ac", to.active);findIf(v, "conj", to.conjunctions);}))
References scxt::engine::NONE.
groupInfoPlayModeTo()
std::string groupInfoPlayModeTo (uint32_t p)
Referenced by SC_STREAMDEF().
groupInfoPlayModeFrom()
uint32_t groupInfoPlayModeFrom (const std::string & s)
groupInfoPlayModeFeatureTo()
std::string groupInfoPlayModeFeatureTo (uint64_t x)
References PMTS.
Referenced by SC_STREAMDEF().
groupInfoPlayModeFeatureFrom()
uint64_t groupInfoPlayModeFeatureFrom (const std::string & x)
References PMTS.
SC_STREAMDEF() [6/35]
SC_STREAMDEF (scxt::engine::Group::GroupOutputInfo , SC_FROM({ v={{"amplitude", t.amplitude}, {"pan", t.pan}, {"tn", t.tuning}, {"oversample", t.oversample}, {"velocitySensitivity", t.velocitySensitivity}, {"muted", t.muted}, {"procRouting", t.procRouting}, {"prCon", t.procRoutingConsistent}, {"routeTo",(int) t.routeTo}, {"hip", t.hasIndependentPolyLimit}, {"pl", t.polyLimit}, {"mc", t.midiChannel}, {"pbu", t.pbUp}, {"pbd", t.pbDown}, {"vpm", groupInfoPlayModeTo(t.vmPlayModeInt)}, {"vpf", groupInfoPlayModeFeatureTo(t.vmPlayModeFeaturesInt)}};}) , SC_TO({ findIf(v, "amplitude", result.amplitude);findIf(v, "pan", result.pan);findOrSet(v, "tn", 0.f, result.tuning);findIf(v, "muted", result.muted);findIf(v, "procRouting", result.procRouting);findIf(v, "velocitySensitivity", result.velocitySensitivity);findIf(v, "oversample", result.oversample);int rt{engine::BusAddress::DEFAULT_BUS};findIf(v, "routeTo", rt);findIf(v, "hip", result.hasIndependentPolyLimit);findIf(v, "pl", result.polyLimit);findOrSet(v, "prCon", true, result.procRoutingConsistent);findOrSet(v, "mc", -1, result.midiChannel);findOrSet(v, "pbu", 2, result.pbUp);findOrSet(v, "pbd", 2, result.pbDown);result.routeTo=(engine::BusAddress)(rt);std::string tmp;findIf(v, "vpm", tmp);result.vmPlayModeInt=groupInfoPlayModeFrom(tmp);findIf(v, "vpf", tmp);result.vmPlayModeFeaturesInt=groupInfoPlayModeFeatureFrom(tmp);}))
References groupInfoPlayModeFeatureTo(), and groupInfoPlayModeTo().
SC_STREAMDEF() [7/35]
SC_STREAMDEF (scxt::engine::Group , SC_FROM({ v={{"zones", t.getZones()}, {"name", t.getName()}, {"outputInfo", t.outputInfo}, {"routingTable", t.routingTable}, {"gegStorage", t.gegStorage}, {"modulatorStorage", t.modulatorStorage}, {"miscSourceStorage", t.miscSourceStorage}, {"processorStorage", t.processorStorage}, {"triggerConditions", t.triggerConditions}};}) , SC_TO({ auto &group=to;findIf(v, "name", group.name);findIf(v, "gegStorage", group.gegStorage);findIf(v, "outputInfo", group.outputInfo);findIf(v, "processorStorage", group.processorStorage);findIf(v, "routingTable", group.routingTable);findIf(v, "triggerConditions", group.triggerConditions);findIfArray(v, "modulatorStorage", group.modulatorStorage);findIf(v, "miscSourceStorage", group.miscSourceStorage);group.clearZones();auto vzones=v.at("zones").get_array();for(const auto vz :vzones) { auto idx=group.addZone(std::make_unique< scxt::engine::Zone >()) - 1;vz.to(*(group.getZone(idx)));if(group.parentPart &&group.parentPart->parentPatch &&group.parentPart->parentPatch->parentEngine) { group.getZone(idx) ->setupOnUnstream(*(group.parentPart->parentPatch->parentEngine));} } if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2025 '11 '12)) { for(auto &z :group) { if(z->mapping.pbUp==group.outputInfo.pbUp) { z->mapping.pbUp=-1;} if(z->mapping.pbDown==group.outputInfo.pbDown) { z->mapping.pbDown=-1;} } } group.setupOnUnstream(*(group.parentPart->parentPatch->parentEngine));}))
SC_STREAMDEF() [8/35]
SC_STREAMDEF (scxt::engine::Zone::ZoneOutputInfo , SC_FROM({ v={{"amp", t.amplitude}, {"pan", t.pan}, {"to",(int) t.routeTo}};addUnlessDefault< val_t >(v, "prc", true, t.procRoutingConsistent);addUnlessDefault< val_t >(v, "prt", engine::Zone::ProcRoutingPath::procRoute_linear, t.procRouting);addUnlessDefault< val_t >(v, "muted", false, t.muted);}) , SC_TO({ auto &zo=to;findIf(v, {"amp", "amplitude"}, zo.amplitude);findIf(v, "pan", zo.pan);findOrSet(v, "muted", false, zo.muted);findOrSet(v, "prc", true, zo.procRoutingConsistent);findOrSet(v, {"prt", "procRouting"}, engine::Zone::ProcRoutingPath::procRoute_linear, zo.procRouting);int rt{engine::BusAddress::DEFAULT_BUS};findIf(v, {"to", "routeTo"}, rt);if(rt >=engine::BusAddress::ERROR_BUS &&rt<=engine::BusAddress::AUX_0+numAux) zo.routeTo=(engine::BusAddress)(rt);else zo.routeTo=engine::BusAddress::DEFAULT_BUS;}))
SC_STREAMDEF() [9/35]
SC_STREAMDEF (scxt::engine::Zone::ZoneMappingData , SC_FROM({ v={{"rootKey", t.rootKey}, {"keyR", t.keyboardRange}, {"velR", t.velocityRange}, {"pbDown", t.pbDown}, {"pbUp", t.pbUp}, {"exclusiveGroup", t.exclusiveGroup}, {"velocitySens", t.velocitySens}, {"amplitude", t.amplitude}, {"pan", t.pan}, {"pitchOffset", t.pitchOffset}, {"tracking", t.tracking}};}) , SC_TO({ auto &zmd=to;findOrSet(v, "rootKey", 60, zmd.rootKey);findIf(v, {"keyR", "keyboardRange"}, zmd.keyboardRange);findIf(v, {"velR", "velocityRange"}, zmd.velocityRange);findIf(v, "pbDown", zmd.pbDown);findIf(v, "pbUp", zmd.pbUp);findIf(v, "amplitude", zmd.amplitude);if(SC_UNSTREAMING_FROM_THIS_OR_OLDER(0x2024 '06 '03)) { auto db=20 *std::log10(zmd.amplitude);zmd.amplitude=std::clamp(db, -36.f, 36.f);} findIf(v, "pan", zmd.pan);findIf(v, "pitchOffset", zmd.pitchOffset);findIf(v, "tracking", zmd.tracking);findOrSet(v, "velocitySens", 1.0, zmd.velocitySens);findOrSet(v, "exclusiveGroup", 0, zmd.exclusiveGroup);}))
STREAM_ENUM() [4/16]
STREAM_ENUM (engine::Zone::PlayMode , engine::Zone::toStringPlayMode , engine::Zone::fromStringPlayMode)
STREAM_ENUM() [5/16]
STREAM_ENUM (engine::Zone::LoopMode , engine::Zone::toStringLoopMode , engine::Zone::fromStringLoopMode)
STREAM_ENUM() [6/16]
STREAM_ENUM (engine::Zone::LoopDirection , engine::Zone::toStringLoopDirection , engine::Zone::fromStringLoopDirection)
STREAM_ENUM() [7/16]
STREAM_ENUM (engine::Zone::ProcRoutingPath , engine::Zone::toStringProcRoutingPath , engine::Zone::fromStringProcRoutingPath)
STREAM_ENUM() [8/16]
STREAM_ENUM (engine::Group::ProcRoutingPath , engine::Group::toStringProcRoutingPath , engine::Group::fromStringProcRoutingPath)
STREAM_ENUM() [9/16]
STREAM_ENUM (engine::Zone::VariantPlaybackMode , engine::Zone::toStringVariantPlaybackMode , engine::Zone::fromStringVariantPlaybackMode)
STREAM_ENUM() [10/16]
STREAM_ENUM (dsp::InterpolationTypes , dsp::toStringInterpolationTypes , dsp::fromStringInterpolationTypes)
STREAM_ENUM() [11/16]
STREAM_ENUM (engine::Clipboard::ContentType , engine::Clipboard::toStringContentType , engine::Clipboard::fromStringContentType)
SC_STREAMDEF() [10/35]
SC_STREAMDEF (scxt::engine::Zone::SingleVariant , SC_FROM({ auto &s=from;if(s.active) { v={{"active", s.active}, {"id", s.sampleID}, {"startSample", s.startSample}, {"endSample", s.endSample}, {"startLoop", s.startLoop}, {"endLoop", s.endLoop}, {"playMode", s.playMode}, {"loopActive", s.loopActive}, {"playReverse", s.playReverse}, {"loopMode", s.loopMode}, {"loopDirection", s.loopDirection}, {"loopCountWhenCounted", s.loopCountWhenCounted}, {"interpolationType", s.interpolationType}, {"loopFade", s.loopFade}, {"normalizationAmplitude", s.normalizationAmplitude}, {"pitchOffset", s.pitchOffset}, {"amplitude", s.amplitude}, {"pan", s.pan}};} else { v=tao::json::empty_object;} }) , SC_TO({ auto &s=to;findOrSet(v, "active", false, s.active);if(s.active) { findIf(v, "id", s.sampleID);findOrSet(v, "startSample", -1, s.startSample);findOrSet(v, "endSample", -1, s.endSample);findOrSet(v, "startLoop", -1, s.startLoop);findOrSet(v, "endLoop", -1, s.endLoop);findOrSet(v, "playMode", engine::Zone::PlayMode::NORMAL, s.playMode);findOrSet(v, "loopActive", false, s.loopActive);findOrSet(v, "playReverse", false, s.playReverse);findOrSet(v, "loopMode", engine::Zone::LoopMode::LOOP_DURING_VOICE, s.loopMode);findOrSet(v, "loopDirection", engine::Zone::LoopDirection::FORWARD_ONLY, s.loopDirection);findOrSet(v, "loopFade", 0, s.loopFade);findOrSet(v, "interpolationType", dsp::InterpolationTypes::Sinc, s.interpolationType);findOrSet(v, "loopCountWhenCounted", 0, s.loopCountWhenCounted);findOrSet(v, "normalizationAmplitude", 1.f, s.normalizationAmplitude);findOrSet(v, "amplitude", 1.f, s.amplitude);if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2025 '06 '19)) { if(s.normalizationAmplitude< 1e-3) s.normalizationAmplitude=1;if(s.amplitude< 1e-3) s.amplitude=1;} findOrSet(v, "pitchOffset", 0.f, s.pitchOffset);findOrSet(v, "pan", 0.f, s.pan);} else { s=scxt::engine::Zone::SingleVariant();assert(!s.active);} }))
SC_STREAMDEF() [11/35]
SC_STREAMDEF (scxt::engine::Zone::Variants , SC_FROM({ v={{"variants", t.variants}, {"variantPlaybackMode", t.variantPlaybackMode}};}) , SC_TO({ findIf(v, {"variants", "samples"}, result.variants);findIf(v, "variantPlaybackMode", result.variantPlaybackMode);}))
SC_STREAMDEF() [12/35]
SC_STREAMDEF (scxt::engine::Zone , SC_FROM({ auto useGivenName=t.givenName;if(useGivenName.empty() &&!t.variantData.variants[0].active) { SCLOG("Crystalizing given name on stream");useGivenName=t.getName();} v={{"variantData", t.variantData}, {"mappingData", t.mapping}, {"outputInfo", t.outputInfo}, {"processorStorage", t.processorStorage}, {"routingTable", t.routingTable}, {"modulatorStorage", t.modulatorStorage}, {"miscSourceStorage", t.miscSourceStorage}, {"egs", t.egStorage}, {"givenName", useGivenName}};}) , SC_TO({ auto &zone=to;findIf(v, {"variantData", "sampleData"}, zone.variantData);findIf(v, "mappingData", zone.mapping);findIf(v, "outputInfo", zone.outputInfo);fromArrayWithSizeDifference< Traits >(v.at("processorStorage"), zone.processorStorage);findIf(v, "routingTable", zone.routingTable);findIfArray(v, "modulatorStorage", zone.modulatorStorage);findIf(v, "miscSourceStorage", zone.miscSourceStorage);if(v.find("aegStorage")) { findOrDefault(v, "aegStorage", zone.egStorage[0]);findOrDefault(v, "eg2Storage", zone.egStorage[1]);} else if(v.find("egs")) { fromArrayWithSizeDifference< Traits >(v.at("egs"), zone.egStorage);} else { SCLOG("Warning: No EG storage in zone");} findOrSet(v, "givenName", "", zone.givenName);zone.onRoutingChanged();}))
SC_STREAMDEF() [13/35]
SC_STREAMDEF (scxt::engine::KeyboardRange , SC_FROM({ v={{"ks", t.keyStart}, {"ke", t.keyEnd}, {"fs", t.fadeStart}, {"fe", t.fadeEnd}};}) , SC_TO({ findIf(v, {"ks", "keyStart"}, to.keyStart);findIf(v, {"ke", "keyEnd"}, to.keyEnd);findIf(v, {"fs", "fadeStart"}, to.fadeStart);findIf(v, {"fe", "fadeEnd"}, to.fadeEnd);}))
SC_STREAMDEF() [14/35]
SC_STREAMDEF (scxt::engine::VelocityRange , SC_FROM({ v={{"vs", t.velStart}, {"ve", t.velEnd}, {"fs", t.fadeStart}, {"fe", t.fadeEnd}};}) , SC_TO({ findIf(v, {"vs", "velStart"}, to.velStart);findIf(v, {"ve", "velEnd"}, to.velEnd);findIf(v, {"fs", "fadeStart"}, to.fadeStart);findIf(v, {"fe", "fadeEnd"}, to.fadeEnd);}))
SC_STREAMDEF() [15/35]
SC_STREAMDEF (engine::Engine::EngineStatusMessage , SC_FROM({ v={{"isAudioRunning", t.isAudioRunning}, {"sampleRate", t.sampleRate}, {"runningEnvironment", t.runningEnvironment}};}) , SC_TO({ findIf(v, "isAudioRunning", to.isAudioRunning);findIf(v, "sampleRate", to.sampleRate);findIf(v, "runningEnvironment", to.runningEnvironment);}))
SC_STREAMDEF() [16/35]
SC_STREAMDEF (engine::Bus , SC_FROM({ v={{"busSendStorage", t.busSendStorage}, {"busEffectStorage", t.busEffectStorage}};}) , SC_TO({ findIf(v, "busSendStorage", to.busSendStorage);findIf(v, "busEffectStorage", to.busEffectStorage);to.resetSendState();}))
SC_STREAMDEF() [17/35]
STREAM_ENUM_WITH_DEFAULT(engine::Bus::BusSendStorage::AuxLocation, engine::Bus::BusSendStorage::AuxLocation::POST_VCA, engine::Bus::BusSendStorage::toStringAuxLocation, engine::Bus::BusSendStorage::fromStringAuxLocation) SC_STREAMDEF(engine SC_STREAMDEF (engine::BusEffectStorage , SC_FROM({ if(from.type==scxt::engine::AvailableBusEffects::none) { v=tao::json::empty_object;} else { v={{"t", scxt::engine::toStringAvailableBusEffects(from.type)}, {"isActive", from.isActive}, {"p", from.params}, {"deact", from.deact}, {"temposync", from.isTemposync}, {"streamingVersion", from.streamingVersion}};} }) , SC_TO({ std::string tp{ scxt::engine::toStringAvailableBusEffects(engine::AvailableBusEffects::none)};findIf(v, {"t", "type"}, tp);to.type=scxt::engine::fromStringAvailableBusEffects(tp);if(to.type==engine::AvailableBusEffects::none) { to=engine::BusEffectStorage();to.type=engine::AvailableBusEffects::none;} else { findIf(v, {"p", "params"}, to.params);findOrSet(v, "isActive", true, to.isActive);findIf(v, "deact", to.deact);findIf(v, "temposync", to.isTemposync);findOrSet(v, "streamingVersion", -1, result.streamingVersion);if(result.streamingVersion > 0) { auto[csv, fn]=scxt::engine::getBusEffectRemapStreamingFunction(result.type);if(csv !=result.streamingVersion) { assert(fn);if(fn) fn(result.streamingVersion, result.params.data());result.streamingVersion=csv;} } } }))
References scxt::engine::none.
SC_STREAMDEF() [18/35]
SC_STREAMDEF (engine::Patch::Busses , SC_FROM({ v={{"mainBus", t.mainBus}, {"partBusses", t.partBusses}, {"auxBusses", t.auxBusses}};}) , SC_TO({ findIf(v, "mainBus", to.mainBus);findIf(v, "partBusses", to.partBusses);findIf(v, "auxBusses", to.auxBusses);to.reconfigureSolo();to.reconfigureOutputBusses();}))
SC_STREAMDEF() [19/35]
SC_STREAMDEF (scxt::engine::MissingResolutionWorkItem , SC_FROM({ v={{"i", from.missingID}, {"p", from.path.u8string()}, {"m", from.isMultiUsed}};}) , SC_TO({ findIf(v, "i", to.missingID);findOrSet(v, "m", false, to.isMultiUsed);std::string fp;findIf(v, "p", fp);to.path=fs::path(fs::u8path(fp));}))
STREAM_ENUM() [12/16]
SC_STREAMDEF(scxt::modulation::modulators::StepLFOStorage, SC_FROM({ v={{"data", t.data}, {"repeat", t.repeat}, {"rateIsForSingleStep", t.rateIsForSingleStep}, {"smooth", t.smooth}}; }), SC_TO({ findIf(v, "data", result.data); findIf(v, "repeat", result.repeat); findIf(v, "smooth", result.smooth); findIf(v, "rateIsForSingleStep", result.rateIsForSingleStep); })) SC_STREAMDEF(scxt STREAM_ENUM (modulation::modulators::PhasorStorage::SyncMode , modulation::modulators::PhasorStorage::toStringSyncMode , modulation::modulators::PhasorStorage::fromStringSyncMode)
STREAM_ENUM() [13/16]
STREAM_ENUM (modulation::modulators::PhasorStorage::Direction , modulation::modulators::PhasorStorage::toStringDirection , modulation::modulators::PhasorStorage::fromStringDirection)
SC_STREAMDEF() [20/35]
SC_STREAMDEF (modulation::modulators::PhasorStorage , SC_FROM({ v=tao::json::empty_object;using ps=modulation::modulators::PhasorStorage;addUnlessDefault< val_t >(v, "di", ps::Division::NOTE, from.division);addUnlessDefault< val_t >(v, "sy", ps::SyncMode::VOICEPOS, from.syncMode);addUnlessDefault< val_t >(v, "a", ps::Direction::ASCENDING, from.direction);addUnlessDefault< val_t >(v, "nu", 1, from.numerator);addUnlessDefault< val_t >(v, "de", 4, from.denominator);addUnlessDefault< val_t >(v, "ph", 0.f, from.phase);}) , SC_TO({ using ps=modulation::modulators::PhasorStorage;findOrSet(v, "di", ps::Division::NOTE, to.division);findOrSet(v, "sy", ps::SyncMode::VOICEPOS, to.syncMode);findOrSet(v, "a", ps::Direction::ASCENDING, to.direction);findOrSet(v, "nu", 1, to.numerator);findOrSet(v, "de", 4, to.denominator);findOrSet(v, "ph", 0, to.phase);}))
STREAM_ENUM() [14/16]
STREAM_ENUM (modulation::modulators::RandomStorage::Style , modulation::modulators::RandomStorage::toStringStyle , modulation::modulators::RandomStorage::fromStringStyle)
SC_STREAMDEF() [21/35]
SC_STREAMDEF (modulation::modulators::RandomStorage , SC_FROM({ v=tao::json::empty_object;addUnlessDefault< val_t >(v, "st", modulation::modulators::RandomStorage::Style::UNIFORM_01, from.style);}) , SC_TO({ findOrSet(v, "st", modulation::modulators::RandomStorage::Style::UNIFORM_01, to.style);}))
References RandomStorage::UNIFORM_01.
SC_STREAMDEF() [22/35]
SC_STREAMDEF (modulation::MiscSourceStorage , SC_FROM({ v={{"rs", t.randoms}, {"ps", t.phasors}};}) , SC_TO({ findIfArray(v, "rs", to.randoms);findIfArray(v, "ps", to.phasors);}))
STREAM_ENUM() [15/16]
STREAM_ENUM (modulation::ModulatorStorage::ModulatorShape , modulation::ModulatorStorage::toStringModulatorShape , modulation::ModulatorStorage::fromStringModulatorShape)
STREAM_ENUM() [16/16]
STREAM_ENUM (modulation::ModulatorStorage::TriggerMode , modulation::ModulatorStorage::toStringTriggerMode , modulation::ModulatorStorage::fromStringTriggerMode)
SC_STREAMDEF() [23/35]
SC_STREAMDEF (scxt::modulation::shared::RoutingExtraPayload , SC_FROM({ v={{"selC", t.selConsistent}, {"targetMetadata", t.targetMetadata}, {"targetBaseValue", t.targetBaseValue}};}) , SC_TO({ findIf(v, "selC", result.selConsistent);findIf(v, "targetMetadata", result.targetMetadata);findIf(v, "targetBaseValue", result.targetBaseValue);}))
SC_STREAMDEF() [24/35]
SC_STREAMDEF (scxt::voice::modulation::Matrix::RoutingTable::Routing , SC_FROM({ if(t.hasDefaultValues()) { v=tao::json::empty_object;} else { v={{"active", t.active}, {"source", t.source}, {"sourceVia", t.sourceVia}, {"target", t.target}, {"curve", t.curve}, {"depth", t.depth}, {"srcLMS", t.sourceLagMS}, {"srVLMS", t.sourceViaLagMS}, {"srcLE", t.sourceLagExp}, {"srVLE", t.sourceViaLagExp}, {"appm", t.applicationMode}};if(SC_STREAMING_FOR_IN_PROCESS) addToObject< val_t >(v, "extraPayload", t.extraPayload);} }) , SC_TO({ result=rt_t();findIf(v, "active", result.active);findIf(v, "source", result.source);findIf(v, "sourceVia", result.sourceVia);findIf(v, "target", result.target);findIf(v, "curve", result.curve);findIf(v, "depth", result.depth);findIf(v, "extraPayload", result.extraPayload);findOrSet(v, "srcLMS", 0, result.sourceLagMS);findOrSet(v, "srVLMS", 0, result.sourceViaLagMS);findOrSet(v, "srcLE", true, result.sourceLagExp);findOrSet(v, "srVLE", true, result.sourceViaLagExp);findOrSet(v, "appm", 0, result.applicationMode);}))
References SC_STREAMING_FOR_IN_PROCESS.
SC_STREAMDEF() [25/35]
SC_STREAMDEF (scxt::voice::modulation::Matrix::RoutingTable , SC_FROM({ v={{"routes", t.routes}};}) , SC_TO({ const auto &object=v.get_object();std::fill(result.routes.begin(), result.routes.end(), rt_t::Routing());if(v.find("routes")) { fromArrayWithSizeDifference(v.at("routes"), result.routes);} }))
SC_STREAMDEF() [26/35]
SC_STREAMDEF (scxt::modulation::GroupMatrix::RoutingTable::Routing , SC_FROM({ if(t.hasDefaultValues()) { v=tao::json::empty_object;} else { v={{"active", t.active}, {"source", t.source}, {"sourceVia", t.sourceVia}, {"target", t.target}, {"curve", t.curve}, {"depth", t.depth}, {"srcLMS", t.sourceLagMS}, {"srVLMS", t.sourceViaLagMS}, {"srcLE", t.sourceLagExp}, {"srVLE", t.sourceViaLagExp}, {"appm", t.applicationMode}};if(SC_STREAMING_FOR_IN_PROCESS) addToObject< val_t >(v, "extraPayload", t.extraPayload);} }) , SC_TO({ result=rt_t();findIf(v, "active", result.active);findIf(v, "source", result.source);findIf(v, "sourceVia", result.sourceVia);findIf(v, "target", result.target);findIf(v, "curve", result.curve);findIf(v, "depth", result.depth);findOrSet(v, "srcLMS", 0, result.sourceLagMS);findOrSet(v, "srVLMS", 0, result.sourceViaLagMS);findOrSet(v, "srcLE", true, result.sourceLagExp);findOrSet(v, "srVLE", true, result.sourceViaLagExp);findOrSet(v, "appm", 0, result.applicationMode);findIf(v, "extraPayload", result.extraPayload);}))
References SC_STREAMING_FOR_IN_PROCESS.
SC_STREAMDEF() [27/35]
SC_STREAMDEF (scxt::modulation::GroupMatrix::RoutingTable , SC_FROM({ v={{"routes", t.routes}};}) , SC_TO({ const auto &object=v.get_object();std::fill(result.routes.begin(), result.routes.end(), rt_t::Routing());if(v.find("routes")) { fromArrayWithSizeDifference(v.at("routes"), result.routes);} }))
SC_STREAMDEF() [28/35]
SC_STREAMDEF (scxt::sample::Sample::SourceType , SC_FROM({ static constexpr const char *key="sourceType";switch(from) { case sample::Sample::WAV_FILE:v="wav";break;case sample::Sample::FLAC_FILE:v="flac";break;case sample::Sample::MP3_FILE:v="mp3";break;case sample::Sample::SF2_FILE:v="sf2";break;case sample::Sample::SFZ_FILE:v="sfz";break;case sample::Sample::AIFF_FILE:v="aiff";break;case sample::Sample::MULTISAMPLE_FILE:v="multisample";break;case sample::Sample::GIG_FILE:v="gig";break;case sample::Sample::SCXT_FILE:v="scxt";break;} }) , SC_TO({ if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '08 '16)) { static constexpr const char *key="sourceType";std::string k{};findIf(v, key, k);if(k=="wav_file") to=sample::Sample::WAV_FILE;if(k=="sf2_file") to=sample::Sample::SF2_FILE;if(k=="flac_file") to=sample::Sample::FLAC_FILE;if(k=="mp3_file") to=sample::Sample::MP3_FILE;if(k=="aiff_file") to=sample::Sample::AIFF_FILE;if(k=="multisample_file") to=sample::Sample::MULTISAMPLE_FILE;} else { if(!v.is_string()) { throw std::logic_error("Unstreamed non-string");} auto k=v.get_string();if(k=="wav") to=sample::Sample::WAV_FILE;if(k=="sf2") to=sample::Sample::SF2_FILE;if(k=="flac") to=sample::Sample::FLAC_FILE;if(k=="mp3") to=sample::Sample::MP3_FILE;if(k=="aiff") to=sample::Sample::AIFF_FILE;if(k=="multisample") to=sample::Sample::MULTISAMPLE_FILE;if(k=="gig") to=sample::Sample::GIG_FILE;if(k=="scxt") to=sample::Sample::SCXT_FILE;} return;}))
References Sample::AIFF_FILE, Sample::FLAC_FILE, Sample::GIG_FILE, Sample::MP3_FILE, Sample::MULTISAMPLE_FILE, Sample::SCXT_FILE, Sample::SF2_FILE, Sample::SFZ_FILE, and Sample::WAV_FILE.
SC_STREAMDEF() [29/35]
SC_STREAMDEF (sample::Sample::SampleFileAddress , SC_FROM({ auto ppref=from.path;v={{"type", from.type}, {"path", ppref.u8string()}, {"md5sum", from.md5sum}};if(from.type==sample::Sample::SF2_FILE||from.type==sample::Sample::MULTISAMPLE_FILE||from.type==sample::Sample::GIG_FILE||from.type==sample::Sample::SCXT_FILE) { addToObject< val_t >(v, "preset", from.preset);addToObject< val_t >(v, "instrument", from.instrument);addToObject< val_t >(v, "region", from.region);} }) , SC_TO({ findOrSet(v, "type", sample::Sample::WAV_FILE, to.type);std::string p;findIf(v, "path", p);to.path=unstreamPathFromString(p);findIf(v, "md5sum", to.md5sum);findOrSet(v, "preset", 0, to.preset);findOrSet(v, "instrument", -1, to.instrument);findOrSet(v, "region", -1, to.region);}))
References Sample::GIG_FILE, Sample::MULTISAMPLE_FILE, Sample::SCXT_FILE, and Sample::SF2_FILE.
SC_STREAMDEF() [30/35]
SC_STREAMDEF (scxt::sample::SampleManager , SC_FROM({ v={{"sampleAddresses", from.getSampleAddressesAndIDs()}};}) , SC_TO({ to.reset();sample::SampleManager::sampleAddressesAndIds_t res;findIf(v, "sampleAddresses", res);to.restoreFromSampleAddressesAndIDs(res);}))
SC_STREAMDEF() [31/35]
SC_STREAMDEF (scxt::sample::compound::CompoundElement , SC_FROM({ v={{"type",(int32_t) from.type}, {"name", from.name}, {"addr", from.sampleAddress}};}) , SC_TO({ int t;findOrSet(v, "type", 0, t);to.type=(scxt::sample::compound::CompoundElement::Type) t;findIf(v, "name", to.name);findIf(v, "addr", to.sampleAddress);}))
findIf() [1/2]
template<typename V , typename R > bool findIf (V & v, const std::string & key, R & r)
Referenced by findOrSet(), and findOrSet().
findIf() [2/2]
template<typename V , typename R > bool findIf (V & v, const std::initializer_list< std::string > & keys, R & r)
findEnumIf()
template<typename V , typename R > bool findEnumIf (V & v, const std::string & key, R & r)
findOrSet() [1/2]
template<typename V , typename D , typename R > void findOrSet (V & v, const std::string & key, const D & d, R & r)
Extract json element key from type v onto r, using d as the default if the key is not.
Parameters
key
d
r
References findIf().
Referenced by findOrDefault().
findOrSet() [2/2]
template<typename V , typename D , typename R > void findOrSet (V & v, const std::initializer_list< std::string > & keys, const D & d, R & r)
References findIf().
findOrDefault()
template<typename V , typename R > void findOrDefault (V & v, const std::string & key, R & r)
References findOrSet().
addToObject()
template<typename T , typename V , typename R > void addToObject (V & v, const std::string & key, const R & val)
addUnlessDefault()
template<typename T , typename V , typename R > void addUnlessDefault (V & v, const std::string & key, const R & defVal, const R & val)
unstreamPathFromString()
fs::path unstreamPathFromString (const std::string & s)
Referenced by scxt::patch_io::readMonolithBinaryIndex().
SC_STREAMDEF() [32/35]
SC_STREAMDEF (scxt::selection::SelectionManager::SelectActionContents , SC_FROM({ auto &e=from;assert(SC_STREAMING_FOR_IN_PROCESS);v={{"p", e.part}, {"g", e.group}, {"z", e.zone}, {"s", e.selecting}, {"d", e.distinct}, {"sl", e.selectingAsLead}, {"fz", e.forZone}};}) , SC_TO({ auto &z=to;findIf(v, "p", z.part);findIf(v, "g", z.group);findIf(v, "z", z.zone);findIf(v, "s", z.selecting);findIf(v, "d", z.distinct);findIf(v, "sl", z.selectingAsLead);findIf(v, "fz", z.forZone);}))
References SC_STREAMING_FOR_IN_PROCESS.
SC_STREAMDEF() [33/35]
SC_STREAMDEF (scxt::selection::SelectionManager::ZoneAddress , SC_FROM({ if(t.part==-1 &&t.group==-1 &&t.zone==-1) { v=tao::json::empty_object;} else { v={{"p", t.part}, {"g", t.group}, {"z", t.zone}};} }) , SC_TO({ findOrSet(v, {"p", "part"}, -1, result.part);findOrSet(v, {"g", "group"}, -1, result.group);findOrSet(v, {"z", "zone"}, -1, result.zone);}))
SC_STREAMDEF() [34/35]
SC_STREAMDEF (selection::SelectionManager , SC_FROM({ auto &e=from;v={{"zones", e.allSelectedZones}, {"leadZone", e.leadZone}, {"groups", e.allSelectedGroups}, {"tabs", e.otherTabSelection}, {"selectedPart", e.selectedPart}};}) , SC_TO({ auto &z=to;if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '07 '24)) { z.selectedPart=0;findIf(v, "tabs", z.otherTabSelection);findIf(v, "zones", z.allSelectedZones[0]);findIf(v, "groups", z.allSelectedGroups[0]);findIf(v, "leadZone", z.leadZone[0]);} else { findIf(v, "tabs", z.otherTabSelection);findIf(v, "zones", z.allSelectedZones);findIf(v, "groups", z.allSelectedGroups);findIf(v, "leadZone", z.leadZone);findIf(v, "selectedPart", z.selectedPart);} selection::SelectionManager::ZoneAddress za;if(!z.allSelectedZones[z.selectedPart].empty()) { selection::SelectionManager::SelectActionContents sac{ z.leadZone[z.selectedPart]};sac.distinct=false;sac.selectingAsLead=true;sac.selecting=true;z.applySelectActions({sac});} }))
to_pretty_stream()
template<template< typename... > class... Transformers, template< typename... > class Traits> void to_pretty_stream (std::ostream & os, const tao::json::basic_value< Traits > & v)
Referenced by streamValue().
streamValue()
template<typename T > std::string streamValue (const T & v, bool pretty)
References to_pretty_stream().
Referenced by streamEngineState(), and streamPatch().
streamPatch()
std::string streamPatch (const engine::Patch & p, bool pretty)
References streamValue().
streamEngineState()
std::string streamEngineState (const engine::Engine & e, bool pretty)
References streamValue().
Referenced by scxt::messaging::client::doDebugAction(), and SCXTPlugin::stateSave().
unstreamEngineState()
void unstreamEngineState (engine::Engine & e, const std::string & data, bool msgPack)
References Engine::clearAll(), and Engine::sendFullRefreshToClient().
Referenced by scxt::messaging::client::doUnstreamEngineState(), scxt::patch_io::initFromResourceBundle(), and scxt::patch_io::loadMulti().
unstreamPartState()
void unstreamPartState (engine::Engine & e, int part, const std::string & data, bool msgPack)
References Engine::getPatch(), and Engine::sendFullRefreshToClient().
SC_STREAMDEF() [35/35]
SC_STREAMDEF (scxt::SampleID , SC_FROM(v={{"m", from.md5}, {"a", from.multiAddress}, {"p", from.pathHash}}); , SC_TO(auto vs=v.find("m");if(vs) { std::string m5;vs->to(m5);strncpy(to.md5, m5.c_str(), scxt::SampleID::md5len+1);findIf(v, "a", to.multiAddress);findIf(v, "p", to.pathHash);} else { std::string legType{"t"}, legID{"i"};if(SC_UNSTREAMING_FROM_PRIOR_TO(0x2024 '08 '06)) { legType="idType";legID="id";} if(6 !=v.at(legType).template as< int32_t >()) { SCLOG("Unstreamed a non-6 type from legacy");} int32_t id;v.at(legID).to(id);to.setAsLegacy(id);}))
Variable Documentation
SC_STREAMDEF
SC_STREAMDEF(scxt::modulation::ModulatorStorage, SC_FROM({ v={{"modulatorShape", t.modulatorShape}, {"triggerMode", t.triggerMode}, {"rate", t.rate}, {"start_phase", t.start_phase}, {"temposync", t.temposync}, {"curveLfoStorage", t.curveLfoStorage}, {"stepLfoStorage", t.stepLfoStorage}, {"envLfoStorage", t.envLfoStorage}}; addUnlessDefault< val_t >(v, "cn", true, t.modulatorConsistent); }), SC_TO({ const auto &object=v.get_object(); findIf(v, "modulatorShape", result.modulatorShape); findIf(v, "triggerMode", result.triggerMode); findIf(v, "rate", result.rate); findIf(v, "start_phase", result.start_phase); findIf(v, "temposync", result.temposync); findIf(v, "curveLfoStorage", result.curveLfoStorage); findIf(v, "stepLfoStorage", result.stepLfoStorage); findIf(v, "envLfoStorage", result.envLfoStorage); findOrSet(v, "cn", true, result.modulatorConsistent); result.configureCalculatedState(); })) SC_STREAMDEF(scxt SC_STREAMDEF(scxt::modulation::shared::SourceIdentifier, SC_FROM({ v={{"g", t.gid}, {"t", t.tid}, {"i", t.index}};}), SC_TO({ findIf(v, "g", result.gid); findIf(v, "t", result.tid); findIf(v, "i", result.index); })) (scxt::modulation::shared::SourceIdentifier , SC_FROM({ v={{"g", t.gid}, {"t", t.tid}, {"i", t.index}};}) , SC_TO({ findIf(v, "g", result.gid); findIf(v, "t", result.tid); findIf(v, "i", result.index); }))