shortcircuit-xt: scxt::dsp::processor Namespace Reference
scxt::dsp::processor Namespace Reference
Adding a processor here.
Namespaces
namespace detail
This code blob uses constexpr expansion to allow us to convert a runtime integer to a template argument without a big case statement.
namespace procimpl
Classes
struct Processor
struct ProcessorControlDescription
struct ProcessorDefaultMix
struct ProcessorDescription
struct ProcessorForGroupOnly
struct ProcessorImplementor
struct ProcessorStorage
struct SCXTVFXConfig
struct SSTVoiceEffectShim
Typedefs
using remapFn_t = void(*)(int16_t, float *const, int *const, uint32_t *const)
typedef std::vector< ProcessorDescription > processorList_t
typedef uint8_t unimpl_t
Enumerations
enum ProcessorType {
proct_none = 0 , proct_CytomicSVF , proct_StaticPhaser , proct_SurgeBiquads ,
proct_VemberClassic , proct_K35 , proct_diodeladder , proct_tripole ,
proct_obx4 , proct_obxpander , proct_cutoffwarp , proct_reswarp ,
proct_vintageladder , proct_snhfilter , proct_comb , proct_utilfilt ,
proct_SurgeFilters , proct_Tremolo , proct_Phaser , proct_shepard ,
proct_Chorus , proct_flanger , proct_volpan , proct_stereotool ,
proct_gainmatrix , proct_Compressor , proct_autowah , proct_stringResonator ,
proct_osc_3op , proct_tetradResonator , proct_eq_3band_parametric_A , proct_eq_6band ,
proct_eq_morph , proct_eq_tilt , proct_fx_bitcrusher , proct_fx_slewer ,
proct_fx_microgate , proct_fx_ringmod , proct_fx_waveshaper , proct_fx_freqshiftmod ,
proct_fx_widener , proct_fx_simple_delay , proct_fmfilter , proct_noise_am ,
proct_osc_phasemod , proct_lifted_reverb1 , proct_lifted_reverb2 , proct_lifted_delay ,
proct_fx_treemonster , proct_osc_EBWaveforms , proct_osc_sineplus , proct_osc_tiltnoise ,
proct_osc_correlatednoise , proct_num_types
}
ProcessorType Type: These are streamed as strings using the toStreamingName / frommStreamingName so we can reorder them.
Functions
bool isProcessorImplemented (ProcessorType id)
const char * getProcessorName (ProcessorType id)
const char * getProcessorStreamingName (ProcessorType id)
remapFn_t getProcessorRemapParametersFromStreamingVersion (ProcessorType id)
const char * getProcessorDisplayGroup (ProcessorType id)
float getProcessorDefaultMix (ProcessorType id)
bool getProcessorGroupOnly (ProcessorType id)
int16_t getProcessorStreamingVersion (ProcessorType id)
int16_t getProcessorFloatParamCount (ProcessorType id)
int16_t getProcessorIntParamCount (ProcessorType id)
std::string getProcessorSSTVoiceDisplayName (ProcessorType id)
std::optional< ProcessorType > fromProcessorStreamingName (const std::string &s)
processorList_t getAllProcessorDescriptions ()
Processor * spawnProcessorInPlace (ProcessorType id, engine::Engine *e, engine::MemoryPool *mp, uint8_t *memory, size_t memorySize, const ProcessorStorage &ps, float *f, int *i, bool oversample, bool needsMetadata)
Spawn with in-place new onto a pre-allocated block.
void unspawnProcessor (Processor *f)
Whetner a Processor is spawned in place or onto fresh memory, release it here.
DEFINE_PROC (ShortDelay, sst::voice_effects::delay::ShortDelay< SCXTVFXConfig< 1 > >, sst::voice_effects::delay::ShortDelay< SCXTVFXConfig< 2 > >, proct_fx_simple_delay, "Simple Delay", "Delay", dsp::surgeSincTable)
PROC_DEFAULT_MIX (proct_fx_simple_delay, 0.3)
DEFINE_PROC (MicroGate, sst::voice_effects::delay::MicroGate< SCXTVFXConfig< 1 > >, sst::voice_effects::delay::MicroGate< SCXTVFXConfig< 2 > >, proct_fx_microgate, "Microgate", "Delay", dsp::surgeSincTable)
DEFINE_PROC (BitCrusher, sst::voice_effects::distortion::BitCrusher< SCXTVFXConfig< 1 > >, sst::voice_effects::distortion::BitCrusher< SCXTVFXConfig< 2 > >, proct_fx_bitcrusher, "Bitcrusher", "Distortion")
DEFINE_PROC (WaveShaper, sst::voice_effects::waveshaper::WaveShaper< SCXTVFXConfig< 1 > >, sst::voice_effects::waveshaper::WaveShaper< SCXTVFXConfig< 2 > >, proct_fx_waveshaper, "WaveShaper", "Distortion")
DEFINE_PROC (Slewer, sst::voice_effects::distortion::Slewer< SCXTVFXConfig< 1 > >, sst::voice_effects::distortion::Slewer< SCXTVFXConfig< 2 > >, proct_fx_slewer, "Slewer", "Distortion")
DEFINE_PROC (TreeMonster, sst::voice_effects::distortion::TreeMonster< SCXTVFXConfig< 1 > >, sst::voice_effects::distortion::TreeMonster< SCXTVFXConfig< 2 > >, proct_fx_treemonster, "Treemonster", "Distortion")
DEFINE_PROC (Compressor, sst::voice_effects::dynamics::Compressor< SCXTVFXConfig< 1 > >, sst::voice_effects::dynamics::Compressor< SCXTVFXConfig< 2 > >, proct_Compressor, "Compressor", "Dynamics")
DEFINE_PROC (AutoWah, sst::voice_effects::dynamics::AutoWah< SCXTVFXConfig< 1 > >, sst::voice_effects::dynamics::AutoWah< SCXTVFXConfig< 2 > >, proct_autowah, "Auto Wah", "Dynamics")
DEFINE_PROC (CytomicSVF, detail::fastSVFImpl, detail::fastSVFImpl_os, proct_CytomicSVF, "Fast SVF", "Filters")
DEFINE_PROC (VemberClassicFilter, procimpl::detail::vemberImpl, procimpl::detail::vemberImpl_os, proct_VemberClassic, "Vember Classic", "Filters")
DEFINE_PROC (K35Filter, procimpl::detail::k35Impl, procimpl::detail::k35Impl_os, proct_K35, "K35", "Filters")
DEFINE_PROC (DiodeLadderFilter, procimpl::detail::diodeLadderImpl, procimpl::detail::diodeLadderImpl_os, proct_diodeladder, "Linear Ladder", "Filters")
DEFINE_PROC (VintageLadder, procimpl::detail::vintageImpl, procimpl::detail::vintageImpl_os, proct_vintageladder, "Vintage Ladder", "Filters")
DEFINE_PROC (OBX4PFilter, procimpl::detail::obx4Impl, procimpl::detail::obx4Impl_os, proct_obx4, "OB-Xd 4-Pole", "Filters")
DEFINE_PROC (OBXpanderFilter, procimpl::detail::obxpandImpl, procimpl::detail::obxpandImpl_os, proct_obxpander, "OB-Xd Xpander", "Filters")
DEFINE_PROC (CutoffWarpFilter, procimpl::detail::cWarpImpl, procimpl::detail::cWarpImpl_os, proct_cutoffwarp, "Cutoff Warp", "Filters")
DEFINE_PROC (ResWarpFilter, procimpl::detail::rWarpImpl, procimpl::detail::rWarpImpl_os, proct_reswarp, "Resonance Warp", "Filters")
DEFINE_PROC (TripoleFilter, procimpl::detail::tripoleImpl, procimpl::detail::tripoleImpl_os, proct_tripole, "Tripole", "Filters")
DEFINE_PROC (SNHFilter, procimpl::detail::SnHImpl, procimpl::detail::SnHImpl_os, proct_snhfilter, "Sample & Hold", "Filters")
DEFINE_PROC (EQ3Band, procimpl::detail::eq3impl, procimpl::detail::eq3impl_os, proct_eq_3band_parametric_A, "3 Band Parametric", "EQ")
DEFINE_PROC (EQGraphic6Band, sst::voice_effects::eq::EqGraphic6Band< SCXTVFXConfig< 1 > >, sst::voice_effects::eq::EqGraphic6Band< SCXTVFXConfig< 2 > >, proct_eq_6band, "6 Band Graphic", "EQ")
DEFINE_PROC (UtilityFilters, sst::voice_effects::filter::UtilityFilters< SCXTVFXConfig< 1 > >, sst::voice_effects::filter::UtilityFilters< SCXTVFXConfig< 2 > >, proct_utilfilt, "Utility Filter", "Filters")
DEFINE_PROC (TiltEQ, sst::voice_effects::eq::TiltEQ< SCXTVFXConfig< 1 > >, sst::voice_effects::eq::TiltEQ< SCXTVFXConfig< 2 > >, proct_eq_tilt, "Tilt EQ", "EQ")
DEFINE_PROC (VolPan, sst::voice_effects::utilities::VolumeAndPan< SCXTVFXConfig< 1 > >, sst::voice_effects::utilities::VolumeAndPan< SCXTVFXConfig< 2 > >, proct_volpan, "Volume & Pan", "Utility")
DEFINE_PROC (StereoTool, sst::voice_effects::utilities::StereoTool< SCXTVFXConfig< 1 > >, sst::voice_effects::utilities::StereoTool< SCXTVFXConfig< 2 > >, proct_stereotool, "Stereo Tool", "Utility")
DEFINE_PROC (GainMatrix, sst::voice_effects::utilities::GainMatrix< SCXTVFXConfig< 1 > >, sst::voice_effects::utilities::GainMatrix< SCXTVFXConfig< 2 > >, proct_gainmatrix, "Gain Matrix", "Utility")
DEFINE_PROC (Widener, sst::voice_effects::delay::Widener< SCXTVFXConfig< 1 > >, sst::voice_effects::delay::Widener< SCXTVFXConfig< 2 > >, proct_fx_widener, "Widener", "Utility", dsp::surgeSincTable)
DEFINE_PROC (EllipticBlepWaveforms, sst::voice_effects::generator::EllipticBlepWaveforms< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::EllipticBlepWaveforms< SCXTVFXConfig< 2 > >, proct_osc_EBWaveforms, "Virtual Analog", "Generators", engine->rng)
PROC_DEFAULT_MIX (proct_osc_EBWaveforms, 0.5)
DEFINE_PROC (SinePlus, sst::voice_effects::generator::SinePlus< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::SinePlus< SCXTVFXConfig< 2 > >, proct_osc_sineplus, "Sine +", "Generators")
PROC_DEFAULT_MIX (proct_osc_sineplus, 0.5)
DEFINE_PROC (GenCorrelatedNoise, sst::voice_effects::generator::GenCorrelatedNoise< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::GenCorrelatedNoise< SCXTVFXConfig< 2 > >, proct_osc_correlatednoise, "Correlated Noise", "Generators", engine->rng)
PROC_DEFAULT_MIX (proct_osc_correlatednoise, 0.5)
DEFINE_PROC (GenTiltNoise, sst::voice_effects::generator::TiltNoise< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::TiltNoise< SCXTVFXConfig< 2 > >, proct_osc_tiltnoise, "Tilt Noise", "Generators", engine->rng)
PROC_DEFAULT_MIX (proct_osc_tiltnoise, 0.5)
DEFINE_PROC (ThreeOpPhaseMod, sst::voice_effects::generator::ThreeOpPhaseMod< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::ThreeOpPhaseMod< SCXTVFXConfig< 2 > >, proct_osc_3op, "3op Phase Mod", "Generators", dsp::twoToTheXTable, dsp::pmSineTable)
DEFINE_PROC (CombFilter, procimpl::detail::combImpl, procimpl::detail::combImpl_os, proct_comb, "Comb", "Resonators")
DEFINE_PROC (StringResonator, sst::voice_effects::generator::StringResonator< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::StringResonator< SCXTVFXConfig< 2 > >, proct_stringResonator, "String Resonator", "Resonators", dsp::surgeSincTable)
DEFINE_PROC (TetradResonator, sst::voice_effects::generator::FourVoiceResonator< SCXTVFXConfig< 1 > >, sst::voice_effects::generator::FourVoiceResonator< SCXTVFXConfig< 2 > >, proct_tetradResonator, "Tetrad Resonator", "Resonators", dsp::simpleSineTable, engine->rng)
DEFINE_PROC (MorphEQ, sst::voice_effects::eq::MorphEQ< SCXTVFXConfig< 1 > >, sst::voice_effects::eq::MorphEQ< SCXTVFXConfig< 2 > >, proct_eq_morph, "Morph", "Filters")
DEFINE_PROC (StaticPhaser, sst::voice_effects::filter::StaticPhaser< SCXTVFXConfig< 1 > >, sst::voice_effects::filter::StaticPhaser< SCXTVFXConfig< 2 > >, proct_StaticPhaser, "Static Phaser", "Filters")
DEFINE_PROC (FreqShiftMod, sst::voice_effects::modulation::FreqShiftMod< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::FreqShiftMod< SCXTVFXConfig< 2 > >, proct_fx_freqshiftmod, "Freqshift Mod", "Audio Rate Mod")
DEFINE_PROC (PhaseMod, sst::voice_effects::modulation::PhaseMod< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::PhaseMod< SCXTVFXConfig< 2 > >, proct_osc_phasemod, "Phase Mod", "Audio Rate Mod")
DEFINE_PROC (FMFilter, sst::voice_effects::modulation::FMFilter< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::FMFilter< SCXTVFXConfig< 2 > >, proct_fmfilter, "FM Filter", "Audio Rate Mod")
DEFINE_PROC (RingMod, sst::voice_effects::modulation::RingMod< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::RingMod< SCXTVFXConfig< 2 > >, proct_fx_ringmod, "Ring Mod", "Audio Rate Mod")
DEFINE_PROC (NoiseAM, sst::voice_effects::modulation::NoiseAM< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::NoiseAM< SCXTVFXConfig< 2 > >, proct_noise_am, "Noise AM", "Audio Rate Mod", engine->rng)
DEFINE_PROC (Tremolo, sst::voice_effects::modulation::Tremolo< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::Tremolo< SCXTVFXConfig< 2 > >, proct_Tremolo, "Tremolo", "Modulation", engine->rng)
DEFINE_PROC (Phaser, sst::voice_effects::modulation::Phaser< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::Phaser< SCXTVFXConfig< 2 > >, proct_Phaser, "Phaser", "Modulation", engine->rng)
DEFINE_PROC (ShepardPhaser, sst::voice_effects::modulation::ShepardPhaser< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::ShepardPhaser< SCXTVFXConfig< 2 > >, proct_shepard, "Shepard Phaser", "Modulation", engine->rng)
DEFINE_PROC (Chorus, sst::voice_effects::modulation::Chorus< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::Chorus< SCXTVFXConfig< 2 > >, proct_Chorus, "Chorus", "Modulation", dsp::surgeSincTable, engine->rng)
DEFINE_PROC (Flanger, sst::voice_effects::modulation::VoiceFlanger< SCXTVFXConfig< 1 > >, sst::voice_effects::modulation::VoiceFlanger< SCXTVFXConfig< 2 > >, proct_flanger, "Circle Flanger", "Modulation", dsp::simpleSineTable, engine->rng)
DEFINE_PROC (LiftedReverb1, sst::voice_effects::liftbus::LiftedReverb1< SCXTVFXConfig< 1 > >, sst::voice_effects::liftbus::LiftedReverb1< SCXTVFXConfig< 2 > >, proct_lifted_reverb1, "Reverb 1", "Reverb")
PROC_FOR_GROUP_ONLY (proct_lifted_reverb1)
PROC_DEFAULT_MIX (proct_lifted_reverb1, 0.333)
DEFINE_PROC (LiftedReverb2, sst::voice_effects::liftbus::LiftedReverb2< SCXTVFXConfig< 1 > >, sst::voice_effects::liftbus::LiftedReverb2< SCXTVFXConfig< 2 > >, proct_lifted_reverb2, "Reverb 2", "Reverb")
PROC_FOR_GROUP_ONLY (proct_lifted_reverb2)
PROC_DEFAULT_MIX (proct_lifted_reverb2, 0.333)
DEFINE_PROC (LiftedDelay, sst::voice_effects::liftbus::LiftedDelay< SCXTVFXConfig< 1 > >, sst::voice_effects::liftbus::LiftedDelay< SCXTVFXConfig< 2 > >, proct_lifted_delay, "Dual Delay", "Delay")
PROC_FOR_GROUP_ONLY (proct_lifted_delay)
PROC_DEFAULT_MIX (proct_lifted_delay, 0.333)
HAS_MEMFN (initVoiceEffect)
HAS_MEMFN (initVoiceEffectParams)
HAS_MEMFN (initVoiceEffectPitch)
HAS_MEMFN (processStereo)
HAS_MEMFN (processMonoToMono)
HAS_MEMFN (processMonoToStereo)
HAS_MEMFN (silentSamplesLength)
HAS_MEMFN (enableKeytrack)
HAS_MEMFN (getKeytrackDefault)
HAS_MEMFN (getKeytrack)
HAS_MEMFN (checkParameterConsistency)
HAS_MEMFN (getMonoToStereoSetting)
HAS_MEMFN (remapParametersForStreamingVersion)
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void runSingleProcessor (int i, float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float input[2][N], float output[2][N])
bool isActive (Processor *processors[engine::processorCount], size_t idx)
template<typename... Indices>
bool anyActive (Processor *processors[engine::processorCount], Indices... idxs)
template<typename... Indices>
bool allActive (Processor *processors[engine::processorCount], Indices... idxs)
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processSequential (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processParallelPair (int A, int B, float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processSer2Pattern (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processSer3Pattern (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processPar1Pattern (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processPar2Pattern (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints >
void processPar3Pattern (float fpitch, Processor *processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix &mix, Mix &outLev, Endpoints *endpoints, bool &chainIsMono, float output[2][N])
Detailed Description
Adding a processor here.
Used to be we had a bunch of case statements. But now we are all driven by templates (see "processor.cpp" for some hairy template code you never need to touch). So to add a processor
Add it in a .c/.hpp as a subtype of Processor
Implement these constexpr values static constexpr const char *processorName{"OSC Pulse"}; static constexpr const char *processorStreamingName{"osc-pulse"}; static constexpr const char *processorDisplayGroup{"Generators"};
The streaming name has to be stable across versions
Specialize the id-to-type structure template <> struct ProcessorImplementor<ProcessorType::proct_osc_pulse_sync> { typedef OscPulseSync T; };
and then include the h here and everything will work
Typedef Documentation
remapFn_t
using remapFn_t = void (*)(int16_t, float *const, int *const, uint32_t *const)
processorList_t
typedef std::vector<ProcessorDescription> processorList_t
unimpl_t
typedef uint8_t unimpl_t
Enumeration Type Documentation
ProcessorType
enum ProcessorType
ProcessorType Type: These are streamed as strings using the toStreamingName / frommStreamingName so we can reorder them.
The only requirement is they are contiguous (so don't assign values) and the last is the proct_num_types
Enumerator
proct_none
proct_CytomicSVF
proct_StaticPhaser
proct_SurgeBiquads
proct_VemberClassic
proct_K35
proct_diodeladder
proct_tripole
proct_obx4
proct_obxpander
proct_cutoffwarp
proct_reswarp
proct_vintageladder
proct_snhfilter
proct_comb
proct_utilfilt
proct_SurgeFilters
proct_Tremolo
proct_Phaser
proct_shepard
proct_Chorus
proct_flanger
proct_volpan
proct_stereotool
proct_gainmatrix
proct_Compressor
proct_autowah
proct_stringResonator
proct_osc_3op
proct_tetradResonator
proct_eq_3band_parametric_A
proct_eq_6band
proct_eq_morph
proct_eq_tilt
proct_fx_bitcrusher
proct_fx_slewer
proct_fx_microgate
proct_fx_ringmod
proct_fx_waveshaper
proct_fx_freqshiftmod
proct_fx_widener
proct_fx_simple_delay
proct_fmfilter
proct_noise_am
proct_osc_phasemod
proct_lifted_reverb1
proct_lifted_reverb2
proct_lifted_delay
proct_fx_treemonster
proct_osc_EBWaveforms
proct_osc_sineplus
proct_osc_tiltnoise
proct_osc_correlatednoise
proct_num_types
Function Documentation
isProcessorImplemented()
bool isProcessorImplemented (ProcessorType id)
Referenced by getAllProcessorDescriptions().
getProcessorName()
const char * getProcessorName (ProcessorType id)
Referenced by getAllProcessorDescriptions(), Processor::getName(), ProcessorPane::loadPreset(), ProcessorPane::savePreset(), and ProcessorPane::showPresetsMenu().
getProcessorStreamingName()
const char * getProcessorStreamingName (ProcessorType id)
Referenced by fromProcessorStreamingName(), getAllProcessorDescriptions(), and ProcessorPane::showPresetsMenu().
getProcessorRemapParametersFromStreamingVersion()
remapFn_t getProcessorRemapParametersFromStreamingVersion (ProcessorType id)
getProcessorDisplayGroup()
const char * getProcessorDisplayGroup (ProcessorType id)
Referenced by getAllProcessorDescriptions().
getProcessorDefaultMix()
float getProcessorDefaultMix (ProcessorType id)
Referenced by HasGroupZoneProcessors< T >::setProcessorType().
getProcessorGroupOnly()
bool getProcessorGroupOnly (ProcessorType id)
Referenced by getAllProcessorDescriptions().
getProcessorStreamingVersion()
int16_t getProcessorStreamingVersion (ProcessorType id)
Referenced by ProcessorPane::applyPresetXML().
getProcessorFloatParamCount()
int16_t getProcessorFloatParamCount (ProcessorType id)
getProcessorIntParamCount()
int16_t getProcessorIntParamCount (ProcessorType id)
getProcessorSSTVoiceDisplayName()
std::string getProcessorSSTVoiceDisplayName (ProcessorType id)
Referenced by getAllProcessorDescriptions(), and ProcessorPane::showPresetsMenu().
fromProcessorStreamingName()
std::optional< ProcessorType > fromProcessorStreamingName (const std::string & s)
References getProcessorStreamingName(), and proct_num_types.
getAllProcessorDescriptions()
processorList_t getAllProcessorDescriptions ()
References getProcessorDisplayGroup(), getProcessorGroupOnly(), getProcessorName(), getProcessorSSTVoiceDisplayName(), getProcessorStreamingName(), isProcessorImplemented(), and proct_num_types.
Referenced by Engine::sendMetadataToClient().
spawnProcessorInPlace()
Processor * spawnProcessorInPlace (ProcessorType id, engine::Engine * e, engine::MemoryPool * mp, uint8_t * memory, size_t memorySize, const ProcessorStorage & ps, float * f, int * i, bool oversample, bool needsMetadata)
Spawn with in-place new onto a pre-allocated block.
The memory must be a 16byte aligned block of at least size processorMemoryBufferSize.
References proct_none, and spawnProcessorInPlace().
Referenced by Voice::initializeProcessors(), Group::onProcessorTypeChanged(), Voice::processWithOS(), spawnProcessorInPlace(), and HasGroupZoneProcessors< T >::spawnTempProcessor().
unspawnProcessor()
void unspawnProcessor (Processor * f)
Whetner a Processor is spawned in place or onto fresh memory, release it here.
Whetner a processor is spawned in place or onto fresh memory, release it here.
We assume that all processors which can spawn placement new did.
References unspawnProcessor(), and Processor::~Processor().
Referenced by HasGroupZoneProcessors< T >::checkOrAdjustIntConsistency(), Voice::cleanupVoice(), Group::onProcessorTypeChanged(), Voice::processWithOS(), Group::setupOnUnstream(), unspawnProcessor(), Group::~Group(), and Voice::~Voice().
DEFINE_PROC() [1/50]
DEFINE_PROC (ShortDelay , sst::voice_effects::delay::ShortDelay< SCXTVFXConfig< 1 > > , sst::voice_effects::delay::ShortDelay< SCXTVFXConfig< 2 > > , proct_fx_simple_delay , "Simple Delay" , "Delay" , dsp::surgeSincTable)
PROC_DEFAULT_MIX() [1/8]
PROC_DEFAULT_MIX (proct_fx_simple_delay , 0. 3)
DEFINE_PROC() [2/50]
DEFINE_PROC (MicroGate , sst::voice_effects::delay::MicroGate< SCXTVFXConfig< 1 > > , sst::voice_effects::delay::MicroGate< SCXTVFXConfig< 2 > > , proct_fx_microgate , "Microgate" , "Delay" , dsp::surgeSincTable)
DEFINE_PROC() [3/50]
DEFINE_PROC (BitCrusher , sst::voice_effects::distortion::BitCrusher< SCXTVFXConfig< 1 > > , sst::voice_effects::distortion::BitCrusher< SCXTVFXConfig< 2 > > , proct_fx_bitcrusher , "Bitcrusher" , "Distortion")
DEFINE_PROC() [4/50]
DEFINE_PROC (WaveShaper , sst::voice_effects::waveshaper::WaveShaper< SCXTVFXConfig< 1 > > , sst::voice_effects::waveshaper::WaveShaper< SCXTVFXConfig< 2 > > , proct_fx_waveshaper , "WaveShaper" , "Distortion")
DEFINE_PROC() [5/50]
DEFINE_PROC (Slewer , sst::voice_effects::distortion::Slewer< SCXTVFXConfig< 1 > > , sst::voice_effects::distortion::Slewer< SCXTVFXConfig< 2 > > , proct_fx_slewer , "Slewer" , "Distortion")
DEFINE_PROC() [6/50]
DEFINE_PROC (TreeMonster , sst::voice_effects::distortion::TreeMonster< SCXTVFXConfig< 1 > > , sst::voice_effects::distortion::TreeMonster< SCXTVFXConfig< 2 > > , proct_fx_treemonster , "Treemonster" , "Distortion")
DEFINE_PROC() [7/50]
DEFINE_PROC (Compressor , sst::voice_effects::dynamics::Compressor< SCXTVFXConfig< 1 > > , sst::voice_effects::dynamics::Compressor< SCXTVFXConfig< 2 > > , proct_Compressor , "Compressor" , "Dynamics")
DEFINE_PROC() [8/50]
DEFINE_PROC (AutoWah , sst::voice_effects::dynamics::AutoWah< SCXTVFXConfig< 1 > > , sst::voice_effects::dynamics::AutoWah< SCXTVFXConfig< 2 > > , proct_autowah , "Auto Wah" , "Dynamics")
DEFINE_PROC() [9/50]
DEFINE_PROC (CytomicSVF , detail::fastSVFImpl , detail::fastSVFImpl_os , proct_CytomicSVF , "Fast SVF" , "Filters")
DEFINE_PROC() [10/50]
DEFINE_PROC (VemberClassicFilter , procimpl::detail::vemberImpl , procimpl::detail::vemberImpl_os , proct_VemberClassic , "Vember Classic" , "Filters")
DEFINE_PROC() [11/50]
DEFINE_PROC (K35Filter , procimpl::detail::k35Impl , procimpl::detail::k35Impl_os , proct_K35 , "K35" , "Filters")
DEFINE_PROC() [12/50]
DEFINE_PROC (DiodeLadderFilter , procimpl::detail::diodeLadderImpl , procimpl::detail::diodeLadderImpl_os , proct_diodeladder , "Linear Ladder" , "Filters")
DEFINE_PROC() [13/50]
DEFINE_PROC (VintageLadder , procimpl::detail::vintageImpl , procimpl::detail::vintageImpl_os , proct_vintageladder , "Vintage Ladder" , "Filters")
DEFINE_PROC() [14/50]
DEFINE_PROC (OBX4PFilter , procimpl::detail::obx4Impl , procimpl::detail::obx4Impl_os , proct_obx4 , "OB-Xd 4-Pole" , "Filters")
DEFINE_PROC() [15/50]
DEFINE_PROC (OBXpanderFilter , procimpl::detail::obxpandImpl , procimpl::detail::obxpandImpl_os , proct_obxpander , "OB-Xd Xpander" , "Filters")
DEFINE_PROC() [16/50]
DEFINE_PROC (CutoffWarpFilter , procimpl::detail::cWarpImpl , procimpl::detail::cWarpImpl_os , proct_cutoffwarp , "Cutoff Warp" , "Filters")
DEFINE_PROC() [17/50]
DEFINE_PROC (ResWarpFilter , procimpl::detail::rWarpImpl , procimpl::detail::rWarpImpl_os , proct_reswarp , "Resonance Warp" , "Filters")
DEFINE_PROC() [18/50]
DEFINE_PROC (TripoleFilter , procimpl::detail::tripoleImpl , procimpl::detail::tripoleImpl_os , proct_tripole , "Tripole" , "Filters")
DEFINE_PROC() [19/50]
DEFINE_PROC (SNHFilter , procimpl::detail::SnHImpl , procimpl::detail::SnHImpl_os , proct_snhfilter , "Sample & Hold" , "Filters")
DEFINE_PROC() [20/50]
DEFINE_PROC (EQ3Band , procimpl::detail::eq3impl , procimpl::detail::eq3impl_os , proct_eq_3band_parametric_A , "3 Band Parametric" , "EQ")
DEFINE_PROC() [21/50]
DEFINE_PROC (EQGraphic6Band , sst::voice_effects::eq::EqGraphic6Band< SCXTVFXConfig< 1 > > , sst::voice_effects::eq::EqGraphic6Band< SCXTVFXConfig< 2 > > , proct_eq_6band , "6 Band Graphic" , "EQ")
DEFINE_PROC() [22/50]
DEFINE_PROC (UtilityFilters , sst::voice_effects::filter::UtilityFilters< SCXTVFXConfig< 1 > > , sst::voice_effects::filter::UtilityFilters< SCXTVFXConfig< 2 > > , proct_utilfilt , "Utility Filter" , "Filters")
DEFINE_PROC() [23/50]
DEFINE_PROC (TiltEQ , sst::voice_effects::eq::TiltEQ< SCXTVFXConfig< 1 > > , sst::voice_effects::eq::TiltEQ< SCXTVFXConfig< 2 > > , proct_eq_tilt , "Tilt EQ" , "EQ")
DEFINE_PROC() [24/50]
DEFINE_PROC (VolPan , sst::voice_effects::utilities::VolumeAndPan< SCXTVFXConfig< 1 > > , sst::voice_effects::utilities::VolumeAndPan< SCXTVFXConfig< 2 > > , proct_volpan , "Volume & Pan" , "Utility")
DEFINE_PROC() [25/50]
DEFINE_PROC (StereoTool , sst::voice_effects::utilities::StereoTool< SCXTVFXConfig< 1 > > , sst::voice_effects::utilities::StereoTool< SCXTVFXConfig< 2 > > , proct_stereotool , "Stereo Tool" , "Utility")
DEFINE_PROC() [26/50]
DEFINE_PROC (GainMatrix , sst::voice_effects::utilities::GainMatrix< SCXTVFXConfig< 1 > > , sst::voice_effects::utilities::GainMatrix< SCXTVFXConfig< 2 > > , proct_gainmatrix , "Gain Matrix" , "Utility")
DEFINE_PROC() [27/50]
DEFINE_PROC (Widener , sst::voice_effects::delay::Widener< SCXTVFXConfig< 1 > > , sst::voice_effects::delay::Widener< SCXTVFXConfig< 2 > > , proct_fx_widener , "Widener" , "Utility" , dsp::surgeSincTable)
DEFINE_PROC() [28/50]
DEFINE_PROC (EllipticBlepWaveforms , sst::voice_effects::generator::EllipticBlepWaveforms< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::EllipticBlepWaveforms< SCXTVFXConfig< 2 > > , proct_osc_EBWaveforms , "Virtual Analog" , "Generators" , engine-> rng)
PROC_DEFAULT_MIX() [2/8]
PROC_DEFAULT_MIX (proct_osc_EBWaveforms , 0. 5)
DEFINE_PROC() [29/50]
DEFINE_PROC (SinePlus , sst::voice_effects::generator::SinePlus< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::SinePlus< SCXTVFXConfig< 2 > > , proct_osc_sineplus , "Sine +" , "Generators")
PROC_DEFAULT_MIX() [3/8]
PROC_DEFAULT_MIX (proct_osc_sineplus , 0. 5)
DEFINE_PROC() [30/50]
DEFINE_PROC (GenCorrelatedNoise , sst::voice_effects::generator::GenCorrelatedNoise< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::GenCorrelatedNoise< SCXTVFXConfig< 2 > > , proct_osc_correlatednoise , "Correlated Noise" , "Generators" , engine-> rng)
PROC_DEFAULT_MIX() [4/8]
PROC_DEFAULT_MIX (proct_osc_correlatednoise , 0. 5)
DEFINE_PROC() [31/50]
DEFINE_PROC (GenTiltNoise , sst::voice_effects::generator::TiltNoise< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::TiltNoise< SCXTVFXConfig< 2 > > , proct_osc_tiltnoise , "Tilt Noise" , "Generators" , engine-> rng)
PROC_DEFAULT_MIX() [5/8]
PROC_DEFAULT_MIX (proct_osc_tiltnoise , 0. 5)
DEFINE_PROC() [32/50]
DEFINE_PROC (ThreeOpPhaseMod , sst::voice_effects::generator::ThreeOpPhaseMod< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::ThreeOpPhaseMod< SCXTVFXConfig< 2 > > , proct_osc_3op , "3op Phase Mod" , "Generators" , dsp::twoToTheXTable , dsp::pmSineTable)
DEFINE_PROC() [33/50]
DEFINE_PROC (CombFilter , procimpl::detail::combImpl , procimpl::detail::combImpl_os , proct_comb , "Comb" , "Resonators")
DEFINE_PROC() [34/50]
DEFINE_PROC (StringResonator , sst::voice_effects::generator::StringResonator< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::StringResonator< SCXTVFXConfig< 2 > > , proct_stringResonator , "String Resonator" , "Resonators" , dsp::surgeSincTable)
DEFINE_PROC() [35/50]
DEFINE_PROC (TetradResonator , sst::voice_effects::generator::FourVoiceResonator< SCXTVFXConfig< 1 > > , sst::voice_effects::generator::FourVoiceResonator< SCXTVFXConfig< 2 > > , proct_tetradResonator , "Tetrad Resonator" , "Resonators" , dsp::simpleSineTable , engine-> rng)
DEFINE_PROC() [36/50]
DEFINE_PROC (MorphEQ , sst::voice_effects::eq::MorphEQ< SCXTVFXConfig< 1 > > , sst::voice_effects::eq::MorphEQ< SCXTVFXConfig< 2 > > , proct_eq_morph , "Morph" , "Filters")
DEFINE_PROC() [37/50]
DEFINE_PROC (StaticPhaser , sst::voice_effects::filter::StaticPhaser< SCXTVFXConfig< 1 > > , sst::voice_effects::filter::StaticPhaser< SCXTVFXConfig< 2 > > , proct_StaticPhaser , "Static Phaser" , "Filters")
DEFINE_PROC() [38/50]
DEFINE_PROC (FreqShiftMod , sst::voice_effects::modulation::FreqShiftMod< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::FreqShiftMod< SCXTVFXConfig< 2 > > , proct_fx_freqshiftmod , "Freqshift Mod" , "Audio Rate Mod")
DEFINE_PROC() [39/50]
DEFINE_PROC (PhaseMod , sst::voice_effects::modulation::PhaseMod< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::PhaseMod< SCXTVFXConfig< 2 > > , proct_osc_phasemod , "Phase Mod" , "Audio Rate Mod")
DEFINE_PROC() [40/50]
DEFINE_PROC (FMFilter , sst::voice_effects::modulation::FMFilter< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::FMFilter< SCXTVFXConfig< 2 > > , proct_fmfilter , "FM Filter" , "Audio Rate Mod")
DEFINE_PROC() [41/50]
DEFINE_PROC (RingMod , sst::voice_effects::modulation::RingMod< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::RingMod< SCXTVFXConfig< 2 > > , proct_fx_ringmod , "Ring Mod" , "Audio Rate Mod")
DEFINE_PROC() [42/50]
DEFINE_PROC (NoiseAM , sst::voice_effects::modulation::NoiseAM< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::NoiseAM< SCXTVFXConfig< 2 > > , proct_noise_am , "Noise AM" , "Audio Rate Mod" , engine-> rng)
DEFINE_PROC() [43/50]
DEFINE_PROC (Tremolo , sst::voice_effects::modulation::Tremolo< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::Tremolo< SCXTVFXConfig< 2 > > , proct_Tremolo , "Tremolo" , "Modulation" , engine-> rng)
DEFINE_PROC() [44/50]
DEFINE_PROC (Phaser , sst::voice_effects::modulation::Phaser< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::Phaser< SCXTVFXConfig< 2 > > , proct_Phaser , "Phaser" , "Modulation" , engine-> rng)
DEFINE_PROC() [45/50]
DEFINE_PROC (ShepardPhaser , sst::voice_effects::modulation::ShepardPhaser< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::ShepardPhaser< SCXTVFXConfig< 2 > > , proct_shepard , "Shepard Phaser" , "Modulation" , engine-> rng)
DEFINE_PROC() [46/50]
DEFINE_PROC (Chorus , sst::voice_effects::modulation::Chorus< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::Chorus< SCXTVFXConfig< 2 > > , proct_Chorus , "Chorus" , "Modulation" , dsp::surgeSincTable , engine-> rng)
DEFINE_PROC() [47/50]
DEFINE_PROC (Flanger , sst::voice_effects::modulation::VoiceFlanger< SCXTVFXConfig< 1 > > , sst::voice_effects::modulation::VoiceFlanger< SCXTVFXConfig< 2 > > , proct_flanger , "Circle Flanger" , "Modulation" , dsp::simpleSineTable , engine-> rng)
DEFINE_PROC() [48/50]
DEFINE_PROC (LiftedReverb1 , sst::voice_effects::liftbus::LiftedReverb1< SCXTVFXConfig< 1 > > , sst::voice_effects::liftbus::LiftedReverb1< SCXTVFXConfig< 2 > > , proct_lifted_reverb1 , "Reverb 1" , "Reverb")
PROC_FOR_GROUP_ONLY() [1/3]
PROC_FOR_GROUP_ONLY (proct_lifted_reverb1)
PROC_DEFAULT_MIX() [6/8]
PROC_DEFAULT_MIX (proct_lifted_reverb1 , 0. 333)
DEFINE_PROC() [49/50]
DEFINE_PROC (LiftedReverb2 , sst::voice_effects::liftbus::LiftedReverb2< SCXTVFXConfig< 1 > > , sst::voice_effects::liftbus::LiftedReverb2< SCXTVFXConfig< 2 > > , proct_lifted_reverb2 , "Reverb 2" , "Reverb")
PROC_FOR_GROUP_ONLY() [2/3]
PROC_FOR_GROUP_ONLY (proct_lifted_reverb2)
PROC_DEFAULT_MIX() [7/8]
PROC_DEFAULT_MIX (proct_lifted_reverb2 , 0. 333)
DEFINE_PROC() [50/50]
DEFINE_PROC (LiftedDelay , sst::voice_effects::liftbus::LiftedDelay< SCXTVFXConfig< 1 > > , sst::voice_effects::liftbus::LiftedDelay< SCXTVFXConfig< 2 > > , proct_lifted_delay , "Dual Delay" , "Delay")
PROC_FOR_GROUP_ONLY() [3/3]
PROC_FOR_GROUP_ONLY (proct_lifted_delay)
PROC_DEFAULT_MIX() [8/8]
PROC_DEFAULT_MIX (proct_lifted_delay , 0. 333)
HAS_MEMFN() [1/13]
HAS_MEMFN (initVoiceEffect)
HAS_MEMFN() [2/13]
HAS_MEMFN (initVoiceEffectParams)
HAS_MEMFN() [3/13]
HAS_MEMFN (initVoiceEffectPitch)
HAS_MEMFN() [4/13]
HAS_MEMFN (processStereo)
HAS_MEMFN() [5/13]
HAS_MEMFN (processMonoToMono)
HAS_MEMFN() [6/13]
HAS_MEMFN (processMonoToStereo)
HAS_MEMFN() [7/13]
HAS_MEMFN (silentSamplesLength)
HAS_MEMFN() [8/13]
HAS_MEMFN (enableKeytrack)
HAS_MEMFN() [9/13]
HAS_MEMFN (getKeytrackDefault)
HAS_MEMFN() [10/13]
HAS_MEMFN (getKeytrack)
HAS_MEMFN() [11/13]
HAS_MEMFN (checkParameterConsistency)
HAS_MEMFN() [12/13]
HAS_MEMFN (getMonoToStereoSetting)
HAS_MEMFN() [13/13]
HAS_MEMFN (remapParametersForStreamingVersion)
runSingleProcessor()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void runSingleProcessor (int i, float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float input[2][N], float output[2][N])
References ProcessorStorage::maxOutputAmp, and proct_none.
isActive()
bool isActive (Processor * processors[engine::processorCount], size_t idx)
Referenced by allActive(), anyActive(), processPar1Pattern(), processPar2Pattern(), processPar3Pattern(), processParallelPair(), processSequential(), and processSer3Pattern().
anyActive()
template<typename... Indices> bool anyActive (Processor * processors[engine::processorCount], Indices... idxs)
References isActive().
Referenced by processPar2Pattern(), processPar3Pattern(), processSer2Pattern(), and processSer3Pattern().
allActive()
template<typename... Indices> bool allActive (Processor * processors[engine::processorCount], Indices... idxs)
References isActive().
processSequential()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processSequential (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References isActive(), and scxt::engine::processorCount.
processParallelPair()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processParallelPair (int A, int B, float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References isActive().
processSer2Pattern()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processSer2Pattern (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References anyActive().
processSer3Pattern()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processSer3Pattern (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References anyActive(), and isActive().
processPar1Pattern()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processPar1Pattern (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References isActive(), and scxt::engine::processorCount.
processPar2Pattern()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processPar2Pattern (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References anyActive(), and isActive().
processPar3Pattern()
template<bool OS, bool forceStereo, int N, typename Mix , typename Endpoints > void processPar3Pattern (float fpitch, Processor * processors[engine::processorCount], bool processorConsumesMono[engine::processorCount], Mix & mix, Mix & outLev, Endpoints * endpoints, bool & chainIsMono, float output[2][N])
References anyActive(), and isActive().