shortcircuit-xt: scxt::undo Namespace Reference
scxt::undo Namespace Reference
Namespaces
namespace payload_detail
Classes
struct BusEffectSpec
struct BusSendSpec
struct EngineStateRestoreItem
struct GroupAudioModSpec
struct GroupChangeItem
struct GroupEgSpec
struct GroupIndexedMemberSpec
struct GroupMemberSpec
struct GroupMiscModSpec
struct GroupModRowSpec
struct GroupModStorageSpec
struct GroupModTableSpec
struct GroupOrderRestoreItem
struct GroupOutputInfoSpec
struct GroupProcessorSpec
struct GroupRenameItem
struct GroupsDeleteOnUndoItem
struct GroupsRestoreItem
struct GroupTriggerConditionsSpec
struct MacroFullStateItem
struct MultiSelectUndoBaseItem
struct PartConfigSpec
struct PartsStateItem
struct PartStreamRestoreItem
struct PayloadUndoableItem
struct ProcessorSwapSpec
struct UndoableItem
struct UndoManager
struct ZoneAudioModSpec
struct ZoneEgSpec
struct ZoneIndexedMemberSpec
struct ZoneMappingSpec
struct ZoneMemberSpec
struct ZoneMiscModSpec
struct ZoneModRowSpec
struct ZoneModStorageSpec
struct ZoneModTableSpec
struct ZoneOrderRestoreItem
struct ZoneOutputInfoSpec
struct ZoneProcessorSpec
struct ZoneRenameItem
struct ZonesDeleteOnUndoItem
struct ZonesRestoreItem
struct ZoneVariantsSpec
Concepts
concept SpecHasRead
concept SpecHasWrite
concept SpecHasPostWrite
concept SpecHasExtraClientRefresh
concept SpecHasExtraClientRefreshAddr
concept SpecSkipsLeadRefresh
Typedefs
using ZoneAddress = selection::SelectionManager::ZoneAddress
using ZoneProcessorSwapSpec = ProcessorSwapSpec< true >
using GroupProcessorSwapSpec = ProcessorSwapSpec< false >
using ZoneMappingDataUndoableItem = PayloadUndoableItem< ZoneMappingSpec >
using ZoneModRowChangeItem = PayloadUndoableItem< ZoneModRowSpec >
using GroupModRowChangeItem = PayloadUndoableItem< GroupModRowSpec >
using ZoneModTableSnapshotItem = PayloadUndoableItem< ZoneModTableSpec >
using GroupModTableSnapshotItem = PayloadUndoableItem< GroupModTableSpec >
using ZoneProcessorTypeChangeItem = PayloadUndoableItem< ZoneProcessorSpec >
using GroupProcessorTypeChangeItem = PayloadUndoableItem< GroupProcessorSpec >
Enumerations
enum struct UndoGesture { Discrete , Begin }
Functions
void refreshLeadDisplay (const engine::Engine &eng, bool forZone)
void resendPGZStructure (const engine::Engine &e)
engine::Zone & zoneAt (engine::Engine &e, const ZoneAddress &a)
engine::Group & groupAt (engine::Engine &e, const ZoneAddress &a)
template<typename Spec >
std::string gestureTag (int32_t index)
template<typename Spec >
void pushPayloadUndoFor (engine::Engine &e, const std::vector< ZoneAddress > &sel, int32_t index=-1, UndoGesture g=UndoGesture::Discrete)
template<typename Spec >
void pushPayloadUndo (engine::Engine &e, int32_t index=-1, UndoGesture g=UndoGesture::Discrete)
template<typename ZSpec , typename GSpec >
void pushZoneOrGroupPayloadUndo (engine::Engine &e, bool forZone, int32_t index=-1, UndoGesture g=UndoGesture::Discrete)
int32_t encodeProcessorPair (int32_t to, int32_t from)
int32_t mixerUndoIndex (int bus, int part, int slot)
void pushZoneAddUndo (engine::Engine &e, int16_t part, int32_t group)
void pushPartStreamUndo (engine::Engine &e, int16_t part, const std::string &label, UndoGesture g)
template<typename Item , typename E , typename... Args>
void pushUndo (E &e, Args &&...args)
template<typename Item , typename E , typename... Args>
void pushUndoTagged (E &e, const std::string &tag, UndoGesture g, Args &&...args)
Typedef Documentation
ZoneAddress
using ZoneAddress = selection::SelectionManager::ZoneAddress
ZoneProcessorSwapSpec
using ZoneProcessorSwapSpec = ProcessorSwapSpec<true>
GroupProcessorSwapSpec
using GroupProcessorSwapSpec = ProcessorSwapSpec<false>
ZoneMappingDataUndoableItem
using ZoneMappingDataUndoableItem = PayloadUndoableItem<ZoneMappingSpec>
ZoneModRowChangeItem
using ZoneModRowChangeItem = PayloadUndoableItem<ZoneModRowSpec>
GroupModRowChangeItem
using GroupModRowChangeItem = PayloadUndoableItem<GroupModRowSpec>
ZoneModTableSnapshotItem
using ZoneModTableSnapshotItem = PayloadUndoableItem<ZoneModTableSpec>
GroupModTableSnapshotItem
using GroupModTableSnapshotItem = PayloadUndoableItem<GroupModTableSpec>
ZoneProcessorTypeChangeItem
using ZoneProcessorTypeChangeItem = PayloadUndoableItem<ZoneProcessorSpec>
GroupProcessorTypeChangeItem
using GroupProcessorTypeChangeItem = PayloadUndoableItem<GroupProcessorSpec>
Enumeration Type Documentation
UndoGesture
enum struct UndoGesture strong
Enumerator
Discrete
Begin
Function Documentation
refreshLeadDisplay()
void refreshLeadDisplay (const engine::Engine & eng, bool forZone)
References Engine::getMessageController(), Engine::getPatch(), Engine::getSelectionManager(), scxt::messaging::client::s2c_send_selected_group_zone_mapping_summary, and scxt::messaging::client::serializationSendToClient().
Referenced by PayloadUndoableItem< Spec >::restore().
resendPGZStructure()
void resendPGZStructure (const engine::Engine & e)
References Engine::getMessageController(), Engine::getPartGroupZoneStructure(), scxt::messaging::client::s2c_send_pgz_structure, and scxt::messaging::client::serializationSendToClient().
Referenced by GroupOutputInfoSpec::extraClientRefresh().
zoneAt()
engine::Zone & zoneAt (engine::Engine & e, const ZoneAddress & a)
References Engine::getPatch(), SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, and SelectionManager::ZoneAddress::zone.
Referenced by ProcessorSwapSpec< ForZone >::owner(), ZoneVariantsSpec::postWrite(), ZoneModRowSpec::postWrite(), ZoneModTableSpec::postWrite(), ZoneIndexedMemberSpec< M >::ref(), ZoneModRowSpec::ref(), ZoneProcessorSpec::ref(), ZoneMemberSpec< M >::ref(), ZoneModTableSpec::ref(), and ZoneProcessorSpec::write().
groupAt()
engine::Group & groupAt (engine::Engine & e, const ZoneAddress & a)
References Engine::getPatch(), SelectionManager::ZoneAddress::group, and SelectionManager::ZoneAddress::part.
Referenced by ProcessorSwapSpec< ForZone >::owner(), GroupModStorageSpec::postWrite(), GroupOutputInfoSpec::postWrite(), GroupModRowSpec::postWrite(), GroupModTableSpec::postWrite(), GroupTriggerConditionsSpec::postWrite(), GroupIndexedMemberSpec< M >::ref(), GroupModRowSpec::ref(), GroupProcessorSpec::ref(), GroupMemberSpec< M >::ref(), GroupModTableSpec::ref(), and GroupProcessorSpec::write().
gestureTag()
template<typename Spec > std::string gestureTag (int32_t index)
pushPayloadUndoFor()
template<typename Spec > void pushPayloadUndoFor (engine::Engine & e, const std::vector< ZoneAddress > & sel, int32_t index = -1, UndoGesture g = UndoGesture::Discrete)
References Discrete, UndoManager::gestureCovers(), UndoManager::storeUndoStepTagged(), and Engine::undoManager.
pushPayloadUndo()
template<typename Spec > void pushPayloadUndo (engine::Engine & e, int32_t index = -1, UndoGesture g = UndoGesture::Discrete)
References Engine::getSelectionManager().
pushZoneOrGroupPayloadUndo()
template<typename ZSpec , typename GSpec > void pushZoneOrGroupPayloadUndo (engine::Engine & e, bool forZone, int32_t index = -1, UndoGesture g = UndoGesture::Discrete)
encodeProcessorPair()
int32_t encodeProcessorPair (int32_t to, int32_t from)
Referenced by scxt::messaging::client::swapGroupProcessors(), and scxt::messaging::client::swapZoneProcessors().
mixerUndoIndex()
int32_t mixerUndoIndex (int bus, int part, int slot)
Referenced by scxt::messaging::client::doBeginEdit(), PartEffectsPane< forBus >::makeBeginEditSender(), scxt::messaging::client::setBusEffectStorage(), scxt::messaging::client::setBusEffectToType(), and scxt::messaging::client::setBusSendStorage().
pushZoneAddUndo()
void pushZoneAddUndo (engine::Engine & e, int16_t part, int32_t group)
References Engine::getPatch(), UndoManager::storeUndoStep(), and Engine::undoManager.
Referenced by Engine::createEmptyZone(), Engine::duplicateZone(), Engine::loadCompoundElementIntoSelectedPartAndGroup(), and Engine::pasteZone().
pushPartStreamUndo()
void pushPartStreamUndo (engine::Engine & e, int16_t part, const std::string & label, UndoGesture g)
References Discrete, UndoManager::gestureCovers(), UndoManager::storeUndoStepTagged(), and Engine::undoManager.
Referenced by scxt::messaging::client::clearPart(), scxt::messaging::client::doBeginEdit(), scxt::messaging::client::doLoadPartInto(), and ImporterContext::ImporterContext().
pushUndo()
template<typename Item , typename E , typename... Args> void pushUndo (E & e, Args &&... args)
pushUndoTagged()
template<typename Item , typename E , typename... Args> void pushUndoTagged (E & e, const std::string & tag, UndoGesture g, Args &&... args)