shortcircuit-xt: scxt::akai_support Namespace Reference
scxt::akai_support Namespace Reference
Classes
struct AKPContext
struct AKPFile
struct EG
struct FILTER
struct GLOBAL_LFO
struct GLOBAL_MODS
struct GLOBAL_OUT
struct GLOBAL_TUNE
struct KEYGROUP
struct KLOC
struct LFO
struct MODULATION
struct ZONE
Functions
std::string fourCC (const char *c)
std::pair< std::string, uint32_t > fourCCSize (const char *c)
bool importAKP (const fs::path &path, engine::Engine &e)
void dumpAkaiToLog (const fs::path &path)
Function Documentation
fourCC()
std::string fourCC (const char * c)
References fourCC().
Referenced by fourCC(), fourCCSize(), and AKPFile::load().
fourCCSize()
std::pair< std::string, uint32_t > fourCCSize (const char * c)
References fourCC().
Referenced by AKPFile::load(), and KEYGROUP::parse().
importAKP()
bool importAKP (const fs::path & path, engine::Engine & e)
References Engine::getMessageController(), Engine::getPatch(), Engine::getSampleManager(), Engine::getSelectionManager(), AKPFile::keygroups, and AKPFile::load().
Referenced by Engine::loadCompoundElementIntoSelectedPartAndGroup(), and Engine::loadSampleIntoSelectedPartAndGroup().
dumpAkaiToLog()
void dumpAkaiToLog (const fs::path & path)
References GLOBAL_TUNE::aftertouch, GLOBAL_OUT::ampMod1, GLOBAL_MODS::ampMod1Src, GLOBAL_OUT::ampMod2, GLOBAL_MODS::ampMod2Src, GLOBAL_TUNE::bendMode, GLOBAL_TUNE::fine, AKPFile::keygroups, GLOBAL_MODS::lfo1DelayModSrc, GLOBAL_MODS::lfo1DepthModSrc, GLOBAL_MODS::lfo1RateModSrc, GLOBAL_MODS::lfo2DelayModSrc, GLOBAL_MODS::lfo2DepthModSrc, GLOBAL_MODS::lfo2RateModSrc, AKPFile::lfos, AKPFile::load(), GLOBAL_OUT::loudness, AKPFile::mods, AKPFile::out, GLOBAL_OUT::panMod1, GLOBAL_MODS::panMod1Src, GLOBAL_OUT::panMod2, GLOBAL_MODS::panMod2Src, GLOBAL_OUT::panMod3, GLOBAL_MODS::panMod3Src, GLOBAL_TUNE::pbDown, GLOBAL_TUNE::pbUp, AKPFile::programName, SCLOG_IF, GLOBAL_TUNE::semi, AKPFile::tune, and GLOBAL_OUT::velSens.
Referenced by main().