shortcircuit-xt: scxt::modulation Namespace Reference
scxt::modulation Namespace Reference
Namespaces
namespace modulators
namespace shared
Classes
struct GroupMatrix
struct GroupMatrixConfig
struct GroupMatrixEndpoints
struct ModulationCurves
struct ModulatorStorage
Typedefs
typedef std::pair< std::string, std::string > identifierDisplayName_t
typedef std::tuple< GroupMatrixConfig::TargetIdentifier, identifierDisplayName_t, bool > namedTarget_t
typedef std::vector< namedTarget_t > namedTargetVector_t
typedef std::pair< GroupMatrixConfig::SourceIdentifier, identifierDisplayName_t > namedSource_t
typedef std::vector< namedSource_t > namedSourceVector_t
typedef std::pair< GroupMatrixConfig::CurveIdentifier, identifierDisplayName_t > namedCurve_t
typedef std::vector< namedCurve_t > namedCurveVector_t
typedef std::tuple< bool, namedSourceVector_t, namedTargetVector_t, namedCurveVector_t > groupMatrixMetadata_t
Functions
groupMatrixMetadata_t getGroupMatrixMetadata (const engine::Group &g)
double secondsToNormalizedEnvTime (double s)
Typedef Documentation
identifierDisplayName_t
typedef std::pair<std::string, std::string> identifierDisplayName_t
namedTarget_t
typedef std::tuple<GroupMatrixConfig::TargetIdentifier, identifierDisplayName_t, bool> namedTarget_t
namedTargetVector_t
typedef std::vector<namedTarget_t> namedTargetVector_t
namedSource_t
typedef std::pair<GroupMatrixConfig::SourceIdentifier, identifierDisplayName_t> namedSource_t
namedSourceVector_t
typedef std::vector<namedSource_t> namedSourceVector_t
namedCurve_t
typedef std::pair<GroupMatrixConfig::CurveIdentifier, identifierDisplayName_t> namedCurve_t
namedCurveVector_t
typedef std::vector<namedCurve_t> namedCurveVector_t
groupMatrixMetadata_t
typedef std::tuple<bool, namedSourceVector_t, namedTargetVector_t, namedCurveVector_t> groupMatrixMetadata_t
Function Documentation
getGroupMatrixMetadata()
groupMatrixMetadata_t getGroupMatrixMetadata (const engine::Group & g)
References ModulationCurves::allCurves, ModulationCurves::curveNames, Group::getEngine(), Engine::groupModSources, and Engine::groupModTargets.
Referenced by SelectionManager::sendDisplayDataForSingleGroup(), scxt::messaging::client::setProcessorType(), and scxt::messaging::client::updateMacroFullState().
secondsToNormalizedEnvTime()
double secondsToNormalizedEnvTime (double s)
Referenced by scxt::sf2_support::importSF2().