shortcircuit-xt: scxt::ui::theme::layout Namespace Reference
scxt::ui::theme::layout Namespace Reference
Namespaces
constants
Typedefs
using coord_t = int
using posn_t = juce::Rectangle< coord_t >
Functions
posn_t belowWithHeight (const posn_t &p, int withHeight)
posn_t belowLabel (const posn_t &p)
posn_t toRightOf (const posn_t &p)
posn_t labelBelow (const posn_t &p)
std::vector< posn_t > columns (const posn_t &p, size_t N)
std::vector< juce::Point< coord_t > > columnCenters (const posn_t &r, int N)
std::vector< coord_t > columnCenterX (const posn_t &r, int N)
template<typename T >
posn_t labeledAt (const sst::jucegui::components::Labeled< T > &lt, const posn_t &p)
template<int size, typename T >
posn_t knob (sst::jucegui::components::Labeled< T > &lt, float x, float y)
template<int size, typename T >
posn_t knobCX (sst::jucegui::components::Labeled< T > &lt, float x, float y)
Typedef Documentation
coord_t
using coord_t = int
posn_t
using posn_t = juce::Rectangle<coord_t>
Function Documentation
belowWithHeight()
posn_t scxt::ui::theme::layout::belowWithHeight (const posn_t & p, int withHeight)
Referenced by labelBelow().
belowLabel()
posn_t scxt::ui::theme::layout::belowLabel (const posn_t & p)
toRightOf()
posn_t scxt::ui::theme::layout::toRightOf (const posn_t & p)
labelBelow()
posn_t scxt::ui::theme::layout::labelBelow (const posn_t & p)
References belowWithHeight().
Referenced by labeledAt().
columns()
std::vector<posn_t> scxt::ui::theme::layout::columns (const posn_t & p, size_t N)
Referenced by columnCenters(), columnCenterX(), ProcessorPane::layoutControlsEQGraphic(), ProcessorPane::layoutControlsEQMorph(), ProcessorPane::layoutControlsEQNBandParm(), and ProcessorPane::layoutControlsSurgeFilters().
columnCenters()
std::vector<juce::Point<coord_t> > scxt::ui::theme::layout::columnCenters (const posn_t & r, int N)
References columns().
columnCenterX()
std::vector<coord_t> scxt::ui::theme::layout::columnCenterX (const posn_t & r, int N)
References columns().
Referenced by OutputTab< OTTraits >::resized().
labeledAt()
posn_t scxt::ui::theme::layout::labeledAt (const sst::jucegui::components::Labeled< T > & lt, const posn_t & p)
References labelBelow().
Referenced by knob().
knob()
posn_t scxt::ui::theme::layout::knob (sst::jucegui::components::Labeled< T > & lt, float x, float y)
References labeledAt().
Referenced by StepLFOPane::resized(), CurveLFOPane::resized(), and ENVLFOPane::resized().
knobCX()
posn_t scxt::ui::theme::layout::knobCX (sst::jucegui::components::Labeled< T > & lt, float x, float y)