shortcircuit-xt: scxt::ui::connectors::jsonlayout Namespace Reference
scxt::ui::connectors::jsonlayout Namespace Reference
Functions
std::optional< std::string > resolveJsonFile (const std::string &nm)
bool isVisible (const sst::jucegui::layouts::json_document::Control &ctrl, std::function< int(int)> indexValue, std::function< void(std::string)> onError)
bool isEnabled (const sst::jucegui::layouts::json_document::Control &ctrl, std::function< int(int)> indexValue, std::function< void(std::string)> onError)
std::unique_ptr< sst::jucegui::components::Label > createControlLabel (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls, sst::jucegui::style::StyleConsumer &sc, juce::Point< int > zeroPoint={0, 0})
std::unique_ptr< sst::jucegui::components::ContinuousParamEditor > createContinuousWidget (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls, const sst::basic_blocks::params::ParamMetaData &pmd)
std::unique_ptr< sst::jucegui::components::DiscreteParamEditor > createDiscreteWidget (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls, std::function< void(std::string)> onError)
std::unique_ptr< juce::Component > createAndPositionNonDataWidget (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls, std::function< void(std::string)> onError, juce::Point< int > zeroPoint={0, 0})
template<typename P , typename W , typename A >
void attachAndPosition (P *parent, const std::unique_ptr< W > &ed, const std::unique_ptr< A > &att, const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls, juce::Point< int > zeroPoint={0, 0})
Function Documentation
resolveJsonFile()
std::optional< std::string > resolveJsonFile (const std::string & nm)
References SCLOG_IF.
Referenced by ColorMap::createColorMap(), PartEffectsPane< forBus >::rebuildWithJsonLayoutEngine(), ProcessorPane::resolveJsonPath(), RoutingPaneContents< RPTraits >::resolveJsonPath(), PartEffectsPane< forBus >::resolveJsonPath(), ProcessorPane::setupJsonTypeMap(), and RoutingPaneContents< RPTraits >::updateFromProcessorPanes().
isVisible()
bool isVisible (const sst::jucegui::layouts::json_document::Control & ctrl, std::function< int(int)> indexValue, std::function< void(std::string)> onError)
Referenced by ProcessorPane::createBindAndPosition().
isEnabled()
bool isEnabled (const sst::jucegui::layouts::json_document::Control & ctrl, std::function< int(int)> indexValue, std::function< void(std::string)> onError)
Referenced by ProcessorPane::createBindAndPosition().
createControlLabel()
std::unique_ptr< sst::jucegui::components::Label > createControlLabel (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls, sst::jucegui::style::StyleConsumer & sc, juce::Point< int > zeroPoint = {0, 0})
Referenced by ProcessorPane::createBindAndPosition(), and RoutingPaneContents< RPTraits >::createBindAndPosition().
createContinuousWidget()
std::unique_ptr< sst::jucegui::components::ContinuousParamEditor > createContinuousWidget (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls, const sst::basic_blocks::params::ParamMetaData & pmd)
Referenced by ProcessorPane::createBindAndPosition(), and RoutingPaneContents< RPTraits >::createBindAndPosition().
createDiscreteWidget()
std::unique_ptr< sst::jucegui::components::DiscreteParamEditor > createDiscreteWidget (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls, std::function< void(std::string)> onError)
References SCLOG_IF.
Referenced by ProcessorPane::createBindAndPosition().
createAndPositionNonDataWidget()
std::unique_ptr< juce::Component > createAndPositionNonDataWidget (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls, std::function< void(std::string)> onError, juce::Point< int > zeroPoint = {0, 0})
Referenced by ProcessorPane::createBindAndPosition(), and RoutingPaneContents< RPTraits >::createBindAndPosition().
attachAndPosition()
template<typename P , typename W , typename A > void attachAndPosition (P * parent, const std::unique_ptr< W > & ed, const std::unique_ptr< A > & att, const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls, juce::Point< int > zeroPoint = {0, 0})
Referenced by ProcessorPane::createBindAndPosition(), and RoutingPaneContents< RPTraits >::createBindAndPosition().