shortcircuit-xt: scxt::modulation::modulators Namespace Reference
scxt::modulation::modulators Namespace Reference
Classes
struct AdsrStorage
struct StepLFOStorage
struct CurveLFOStorage
struct EnvLFOStorage
struct CurveLFO
struct EnvLFO
struct StepLFO
Enumerations
enum LFOPresets {
lp_custom = 0 , lp_clear , lp_sine , lp_tri ,
lp_square , lp_ramp_up , lp_ramp_down , lp_noise ,
lp_noise_mean3 , lp_noise_mean5 , lp_tremolo_tri , lp_tremolo_sin ,
n_lfopresets
}
Functions
void clear_lfo (modulation::ModulatorStorage &settings)
void load_lfo_preset (LFOPresets id, StepLFOStorage &settings, sst::basic_blocks::dsp::RNG &rng)
float CubicInterpolate (float y0, float y1, float y2, float y3, float mu)
float CosineInterpolate (float y1, float y2, float mu)
float QuadSplineInterpolate (float y0, float y1, float y2, float y3, float mu, int odd)
float QuadraticBSpline (float y0, float y1, float y2, float mu)
float lfo_ipol (float *wf_history, float phase, float smooth, int odd)
std::string getLfoPresetName (LFOPresets p)
Enumeration Type Documentation
LFOPresets
enum LFOPresets
Enumerator
lp_custom
lp_clear
lp_sine
lp_tri
lp_square
lp_ramp_up
lp_ramp_down
lp_noise
lp_noise_mean3
lp_noise_mean5
lp_tremolo_tri
lp_tremolo_sin
n_lfopresets
Function Documentation
clear_lfo()
void clear_lfo (modulation::ModulatorStorage & settings)
References StepLFOStorage::repeat, and ModulatorStorage::stepLfoStorage.
Referenced by Zone::initialize().
load_lfo_preset()
void load_lfo_preset (LFOPresets id, StepLFOStorage & settings, sst::basic_blocks::dsp::RNG & rng)
References StepLFOStorage::data, lp_clear, lp_custom, lp_noise, lp_noise_mean3, lp_noise_mean5, lp_ramp_down, lp_ramp_up, lp_sine, lp_square, lp_tremolo_sin, lp_tremolo_tri, lp_tri, n_lfopresets, StepLFOStorage::repeat, scxt::voice::modulation::rng, StepLFOStorage::smooth, and StepLFOStorage::stepLfoSteps.
Referenced by LfoPane::pickPresets().
CubicInterpolate()
float scxt::modulation::modulators::CubicInterpolate (float y0, float y1, float y2, float y3, float mu)
CosineInterpolate()
float scxt::modulation::modulators::CosineInterpolate (float y1, float y2, float mu)
QuadSplineInterpolate()
float scxt::modulation::modulators::QuadSplineInterpolate (float y0, float y1, float y2, float y3, float mu, int odd)
QuadraticBSpline()
float scxt::modulation::modulators::QuadraticBSpline (float y0, float y1, float y2, float mu)
Referenced by lfo_ipol().
lfo_ipol()
float lfo_ipol (float * wf_history, float phase, float smooth, int odd)
References QuadraticBSpline().
Referenced by StepLFO::process().
getLfoPresetName()
std::string scxt::modulation::modulators::getLfoPresetName (LFOPresets p)
References lp_clear, lp_custom, lp_noise, lp_noise_mean3, lp_noise_mean5, lp_ramp_down, lp_ramp_up, lp_sine, lp_square, lp_tremolo_sin, lp_tremolo_tri, lp_tri, and n_lfopresets.
Referenced by LfoPane::pickPresets().