shortcircuit-xt: scxt::dsp Namespace Reference
scxt::dsp Namespace Reference
Namespaces
namespace detail
namespace processor
Adding a processor here.
namespace sample_analytics
Classes
struct GeneratorIO
struct GeneratorState
struct KernelOp
struct KernelOp< InterpolationTypes::Linear, T >
struct KernelOp< InterpolationTypes::Sinc, float >
struct KernelOp< InterpolationTypes::Sinc, int16_t >
struct KernelOp< InterpolationTypes::ZeroOrderHold, T >
struct KernelOp< InterpolationTypes::ZOHAA, T >
struct KernelProcessor
Typedefs
using SincTable = sst::basic_blocks::tables::ShortcircuitSincTableProvider
using SurgeSincTable = sst::basic_blocks::tables::SurgeSincTableProvider
using DbTable = sst::basic_blocks::tables::DbToLinearProvider
using TwoToTheXTable = sst::basic_blocks::tables::TwoToTheXProvider
typedef void(* GeneratorFPtr) (GeneratorState *__restrict, GeneratorIO *__restrict)
Enumerations
enum InterpolationTypes { Sinc , Linear , ZOHAA , ZeroOrderHold }
Functions
float getFadeGainToAmp (float g)
float getFadeGain (int32_t samplePos, int32_t x1, int32_t x2)
float NormalizeSampleToF32 (float val)
float NormalizeSampleToF32 (int16_t val)
template<int compoundConfig>
void GeneratorSample (GeneratorState *__restrict GD, GeneratorIO *__restrict IO)
int toLoopValue (bool active, bool forward, bool whileGated, bool isFloat, bool isStereo)
constexpr std::array< bool, 5 > fromLoopValue (int lv)
GeneratorFPtr GetFPtrGeneratorSample (bool Stereo, bool Float, bool loopActive, bool loopForward, bool loopWhileGated)
DECLARE_ENUM_STRING (InterpolationTypes)
std::string toStringInterpolationTypes (const InterpolationTypes &p)
InterpolationTypes fromStringInterpolationTypes (const std::string &s)
Variables
SincTable sincTable
SurgeSincTable surgeSincTable
DbTable dbTable
TwoToTheXTable twoToTheXTable
constexpr float I16InvScale = (1.f / (16384.f * 32768.f))
constexpr float I16InvScale2 = (1.f / (32768.f))
const auto I16InvScale_m128 = SIMD_MM(set1_ps)(I16InvScale)
Typedef Documentation
SincTable
using SincTable = sst::basic_blocks::tables::ShortcircuitSincTableProvider
SurgeSincTable
using SurgeSincTable = sst::basic_blocks::tables::SurgeSincTableProvider
DbTable
using DbTable = sst::basic_blocks::tables::DbToLinearProvider
TwoToTheXTable
using TwoToTheXTable = sst::basic_blocks::tables::TwoToTheXProvider
GeneratorFPtr
typedef void(* GeneratorFPtr) (GeneratorState *__restrict, GeneratorIO *__restrict)
Enumeration Type Documentation
InterpolationTypes
enum InterpolationTypes
Enumerator
Sinc
Linear
ZOHAA
ZeroOrderHold
Function Documentation
getFadeGainToAmp()
float getFadeGainToAmp (float g)
Referenced by KernelOp< InterpolationTypes::Linear, T >::Process(), KernelOp< InterpolationTypes::Sinc, float >::Process(), KernelOp< InterpolationTypes::Sinc, int16_t >::Process(), KernelOp< InterpolationTypes::ZeroOrderHold, T >::Process(), and KernelOp< InterpolationTypes::ZOHAA, T >::Process().
getFadeGain()
float getFadeGain (int32_t samplePos, int32_t x1, int32_t x2)
Referenced by KernelOp< InterpolationTypes::Linear, T >::Process(), KernelOp< InterpolationTypes::Sinc, float >::Process(), KernelOp< InterpolationTypes::Sinc, int16_t >::Process(), KernelOp< InterpolationTypes::ZeroOrderHold, T >::Process(), and KernelOp< InterpolationTypes::ZOHAA, T >::Process().
NormalizeSampleToF32() [1/2]
float NormalizeSampleToF32 (float val)
Referenced by KernelOp< InterpolationTypes::Linear, T >::Process(), KernelOp< InterpolationTypes::ZeroOrderHold, T >::Process(), and KernelOp< InterpolationTypes::ZOHAA, T >::Process().
NormalizeSampleToF32() [2/2]
float NormalizeSampleToF32 (int16_t val)
References I16InvScale2.
GeneratorSample()
template<int compoundConfig> void GeneratorSample (GeneratorState *__restrict GD, GeneratorIO *__restrict IO)
References fromLoopValue(), KPMono, KPStereo, Linear, SCD, SCLOG, Sinc, ZeroOrderHold, and ZOHAA.
toLoopValue()
int toLoopValue (bool active, bool forward, bool whileGated, bool isFloat, bool isStereo)
Referenced by GetFPtrGeneratorSample().
fromLoopValue()
constexpr std::array< bool, 5 > fromLoopValue (int lv) constexpr
Referenced by GeneratorSample().
GetFPtrGeneratorSample()
GeneratorFPtr GetFPtrGeneratorSample (bool Stereo, bool Float, bool loopActive, bool loopForward, bool loopWhileGated)
References scxt::dsp::detail::generatorGet(), and toLoopValue().
Referenced by Voice::initializeGenerator(), and PreviewVoice::Details::initiateGD().
DECLARE_ENUM_STRING()
DECLARE_ENUM_STRING (InterpolationTypes)
toStringInterpolationTypes()
std::string toStringInterpolationTypes (const InterpolationTypes & p)
References Linear, Sinc, ZeroOrderHold, and ZOHAA.
fromStringInterpolationTypes()
InterpolationTypes fromStringInterpolationTypes (const std::string & s)
References Sinc, and ZeroOrderHold.
Variable Documentation
sincTable
SincTable sincTable
Referenced by Engine::Engine(), KernelOp< InterpolationTypes::Sinc, float >::Process(), and KernelOp< InterpolationTypes::Sinc, int16_t >::Process().
surgeSincTable
SurgeSincTable surgeSincTable
dbTable
DbTable dbTable
Referenced by SCXTVFXConfig< OSFactor >::dbToLinear(), EngineBiquadAdapter::dbToLinear(), Config::dbToLinear(), Engine::Engine(), and Voice::processWithOS().
twoToTheXTable
TwoToTheXTable twoToTheXTable
Referenced by Engine::Engine(), Group::envelope_rate_linear_nowrap(), CurveLFO::envelope_rate_linear_nowrap(), EnvLFO::envelope_rate_linear_nowrap(), Voice::envelope_rate_linear_nowrap(), Config::envelopeRateLinear(), EnvLFO::process(), and Voice::twoToTheXProvider().
I16InvScale
constexpr float I16InvScale = (1.f / (16384.f * 32768.f)) constexpr
I16InvScale2
constexpr float I16InvScale2 = (1.f / (32768.f)) constexpr
Referenced by NormalizeSampleToF32().
I16InvScale_m128
const auto I16InvScale_m128 = SIMD_MM(set1_ps)(I16InvScale)
Referenced by KernelOp< InterpolationTypes::Sinc, int16_t >::Process().