shortcircuit-xt: scxt::perf Namespace Reference
scxt::perf Namespace Reference
Classes
struct BakedSequence
struct Config
struct CustomEvent
struct EngineConfig
struct Fingerprint
struct IterationStats
struct LoadResult
struct LoadStep
struct MidiEvent
struct RunConfig
struct RunResult
struct ScenarioStats
struct SequenceParams
struct SequenceSpec
Functions
Config loadFromFile (const std::filesystem::path &p)
std::string canonicalJson (const Config &c)
uint64_t hashConfig (const Config &c)
void fnv1a (uint64_t &h, const void *data, std::size_t n)
std::uint64_t fnv1a (const void *data, std::size_t n)
BakedSequence bake (const SequenceSpec &spec, double sampleRate, int blockSize, double tailSilenceS)
LoadResult applyLoad (scxt::engine::Engine &engine, const std::vector< LoadStep > &steps)
void writeReport (const std::filesystem::path &out, const Config &cfg, const LoadResult &load, const RunResult &run)
void writeWavFloat32 (const std::filesystem::path &out, const std::vector< float > &interleaved, double sampleRate)
void printConsoleSummary (const Config &cfg, const LoadResult &load, const RunResult &run)
RunResult runMeasure (scxt::engine::Engine &engine, const BakedSequence &seq, const RunConfig &cfg)
void runProfile (scxt::engine::Engine &engine, const BakedSequence &seq, const RunConfig &cfg)
Variables
constexpr uint64_t kFnvOffsetBasis = 0xcbf29ce484222325ULL
constexpr uint64_t kFnvPrime = 0x100000001b3ULL
Function Documentation
loadFromFile()
Config loadFromFile (const std::filesystem::path & p)
References SequenceSpec::custom, Config::description, Config::engine, Config::load, LoadStep::LoadInstrument, Config::name, SequenceSpec::params, Config::run, EngineConfig::sampleRate, and Config::sequence.
Referenced by main().
canonicalJson()
std::string canonicalJson (const Config & c)
References SequenceSpec::ChromaticBlast, SequenceSpec::CMajorChord, Config::description, Config::engine, Config::load, LoadStep::LoadMulti, LoadStep::LoadPartInto, RunConfig::measureIterations, Config::name, SequenceSpec::params, RunConfig::Profile, RunConfig::RealtimePriority, Config::run, EngineConfig::sampleRate, Config::sequence, SequenceSpec::SingleNote, RunConfig::tailSilenceS, and RunConfig::warmupIterations.
Referenced by hashConfig().
hashConfig()
uint64_t hashConfig (const Config & c)
References canonicalJson(), and fnv1a().
Referenced by writeReport().
fnv1a() [1/2]
void fnv1a (uint64_t & h, const void * data, std::size_t n)
References kFnvPrime.
Referenced by Fingerprint::absorbBlock(), applyLoad(), fnv1a(), and hashConfig().
fnv1a() [2/2]
std::uint64_t fnv1a (const void * data, std::size_t n)
References fnv1a(), and kFnvOffsetBasis.
bake()
BakedSequence bake (const SequenceSpec & spec, double sampleRate, int blockSize, double tailSilenceS)
References MidiEvent::channel, SequenceSpec::ChromaticBlast, SequenceSpec::CMajorChord, SequenceSpec::Custom, SequenceSpec::custom, BakedSequence::events, MidiEvent::NoteOff, MidiEvent::NoteOn, SequenceSpec::params, BakedSequence::sampleRate, SequenceSpec::SingleNote, BakedSequence::totalBlocks, and SequenceParams::velocity.
Referenced by main().
applyLoad()
LoadResult applyLoad (scxt::engine::Engine & engine, const std::vector< LoadStep > & steps)
References LoadResult::error, LoadResult::fileHash, fnv1a(), Engine::getMessageController(), scxt::sf2_support::importSF2(), LoadStep::LoadInstrument, LoadStep::LoadMulti, scxt::patch_io::loadMulti(), LoadStep::LoadPartInto, scxt::patch_io::loadPartInto(), Engine::loadSampleIntoSelectedPartAndGroup(), LoadResult::ok, LoadResult::totalFileBytes, and LoadResult::wallMs.
Referenced by main().
writeReport()
void writeReport (const std::filesystem::path & out, const Config & cfg, const LoadResult & load, const RunResult & run)
References ScenarioStats::blockSize, LoadResult::fileHash, RunResult::fingerprint, hashConfig(), RunResult::measureIterations, Config::name, LoadResult::numGroups, LoadResult::numParts, LoadResult::numSamples, LoadResult::numZones, ScenarioStats::sampleRate, RunResult::scenario, ScenarioStats::totalBlocks, LoadResult::totalFileBytes, ScenarioStats::totalSeconds, LoadResult::wallMs, and RunResult::warmupIterations.
Referenced by main().
writeWavFloat32()
void writeWavFloat32 (const std::filesystem::path & out, const std::vector< float > & interleaved, double sampleRate)
Referenced by main().
printConsoleSummary()
void printConsoleSummary (const Config & cfg, const LoadResult & load, const RunResult & run)
References ScenarioStats::blockSize, Fingerprint::exact, RunResult::fingerprint, RunResult::measureIterations, Config::name, LoadResult::numGroups, LoadResult::numParts, LoadResult::numSamples, LoadResult::numZones, Fingerprint::peak, Fingerprint::rms(), ScenarioStats::sampleRate, RunResult::scenario, ScenarioStats::totalBlocks, ScenarioStats::totalSeconds, LoadResult::wallMs, RunResult::warmupIterations, and Fingerprint::zeroCrossings.
Referenced by main().
runMeasure()
RunResult runMeasure (scxt::engine::Engine & engine, const BakedSequence & seq, const RunConfig & cfg)
References ScenarioStats::blockSize, Fingerprint::configure(), Fingerprint::finalize(), RunResult::fingerprint, RunConfig::measureIterations, RunResult::measureIterations, RunConfig::RealtimePriority, BakedSequence::sampleRate, ScenarioStats::sampleRate, RunResult::scenario, BakedSequence::totalBlocks, ScenarioStats::totalBlocks, ScenarioStats::totalSeconds, RunConfig::warmupIterations, RunResult::warmupIterations, RunResult::wavInterleaved, and RunConfig::wavOutputPath.
Referenced by main().
runProfile()
void runProfile (scxt::engine::Engine & engine, const BakedSequence & seq, const RunConfig & cfg)
References RunConfig::profileIterations, RunConfig::RealtimePriority, and RunConfig::waitForKey.
Referenced by main().
Variable Documentation
kFnvOffsetBasis
constexpr uint64_t kFnvOffsetBasis = 0xcbf29ce484222325ULL constexpr
Referenced by fnv1a().
kFnvPrime
constexpr uint64_t kFnvPrime = 0x100000001b3ULL constexpr
Referenced by fnv1a().