shortcircuit-xt: scxt::ui::connectors::resources Namespace Reference
scxt::ui::connectors::resources Namespace Reference
Functions
juce::Typeface::Ptr loadTypeface (const std::string &path)
std::unique_ptr< juce::Drawable > loadImageDrawable (const std::string &path)
std::string loadTextFile (const std::string &path)
Function Documentation
loadTypeface()
juce::Typeface::Ptr loadTypeface (const std::string & path)
References SCLOG.
Referenced by ThemeApplier::anonmyousProRegularFor(), ThemeApplier::interBoldFor(), ThemeApplier::interLightFor(), ThemeApplier::interMediumFor(), ThemeApplier::interRegularFor(), and LogScreen::LogScreen().
loadImageDrawable()
std::unique_ptr< juce::Drawable > loadImageDrawable (const std::string & path)
References SCLOG.
Referenced by AboutScreen::AboutScreen().
loadTextFile()
std::string loadTextFile (const std::string & path)
References SCLOG.
Referenced by AboutScreen::resetInfo().