shortcircuit-xt: scxt::exs_support Namespace Reference
scxt::exs_support Namespace Reference
Classes
struct EXSBlock
struct EXSCompoundElement
struct EXSGroup
struct EXSInfo
struct EXSInstrument
struct ExsModWarnings
struct EXSObject
struct EXSParameters
struct EXSSample
struct EXSZone
Typedefs
using byteData_t = std::vector< uint8_t >
Enumerations
enum class EXSParam : uint16_t {
MASTER_VOLUME = 0x07 , MASTER_PAN = 0x160 , VOLUME_KEYSCALE = 0x08 , PITCH_BEND_UP = 0x03 ,
PITCH_BEND_DOWN = 0x04 , MONO_LEGATO = 0x0a , MIDI_MONO_MODE = 0x116 , MIDI_MONO_MODE_PITCH_RANGE = 0x11a ,
POLYPHONY_VOICES = 0x05 , TRANSPOSE = 0x2d , COARSE_TUNE = 0x0e , FINE_TUNE = 0x0f ,
GLIDE = 0x14 , PORTA_DOWN = 0x48 , PORTA_UP = 0x49 , FILTER1_TOGGLE = 0x2c ,
FILTER1_TYPE = 0xf3 , FILTER1_FAT = 0xaa , FILTER1_CUTOFF = 0x1e , FILTER1_RESO = 0x1d ,
FILTER1_DRIVE = 0x4b , FILTER1_KEYTRACK = 0x2e , FILTER2_TOGGLE = 0x174 , FILTER2_TYPE = 0x186 ,
FILTER2_CUTOFF = 0x177 , FILTER2_RESO = 0x178 , FILTER2_DRIVE = 0x179 , FILTERS_SERIAL_PARALLEL = 0x173 ,
FILTERS_BLEND = 0x17a , LFO_1_FADE = 0x3c , LFO_1_RATE = 0x3d , LFO_1_WAVE_SHAPE = 0x3e ,
LFO_1_KEY_TRIGGER = 0x14c , LFO_1_MONO_POLY = 0x14d , LFO_1_PHASE = 0x14e , LFO_1_POSITIVE_OR_MIDPOINT = 0x14f ,
LFO_1_TEMPO_SYNC = 0x150 , LFO_1_FADE_IN_OR_OUT = 0x187 , LFO_2_RATE = 0x3f , LFO_2_WAVE_SHAPE = 0x40 ,
LFO_2_FADE = 0x151 , LFO_2_KEY_TRIGGER = 0x152 , LFO_2_MONO_POLY = 0x153 , LFO_2_PHASE = 0x154 ,
LFO_2_POSITIVE_OR_MIDPOINT = 0x155 , LFO_2_TEMPO_SYNC = 0x156 , LFO_2_FADE_IN_OR_OUT = 0x188 , LFO_3_RATE = 0xa7 ,
LFO_3_WAVE_SHAPE = 0x158 , LFO_3_FADE = 0x157 , LFO_3_KEY_TRIGGER = 0x159 , LFO_3_MONO_POLY = 0x15a ,
LFO_3_PHASE = 0x15b , LFO_3_POSITIVE_OR_MIDPOINT = 0x15c , LFO_3_TEMPO_SYNC = 0x15d , LFO_3_FADE_IN_OR_OUT = 0x189 ,
ENV2_TYPE = 0x16a , ENV2_VEL_SENS = 0x17d , ENV2_DELAY_START = 0x16c , ENV2_ATK_CURVE = 0x192 ,
ENV2_ATK_HI_VEL = 0x4c , ENV2_ATK_LO_VEL = 0x4d , ENV2_HOLD = 0x38 , ENV2_DECAY = 0x4e ,
ENV2_SUSTAIN = 0x4f , ENV2_RELEASE = 0x50 , ENV2_TIME_CURVE = 0x5b , ENV1_TYPE = 0x6b ,
ENV1_VEL_SENS = 0x5a , ENV1_VOLUME_HIGH = 0x59 , ENV1_DELAY_START = 0x16d , ENV1_ATK_CURVE = 0x195 ,
ENV1_ATK_HI_VEL = 0x52 , ENV1_ATK_LO_VEL = 0x53 , ENV1_HOLD = 0x58 , ENV1_DECAY = 0x54 ,
ENV1_SUSTAIN = 0x51 , ENV1_RELEASE = 0x55 , AMP_VELOCITY_CURVE = 0x183 , VELOCITY_OFFSET = 0x5f ,
RANDOM_VELOCITY = 0xa4 , RANDOM_SAMPLE_SEL = 0xa3 , RANDOM_PITCH = 0x62 , XFADE_AMOUNT = 0x61 ,
XFADE_TYPE = 0xa5 , UNISON_TOGGLE = 0xab , COARSE_TUNE_REMOTE = 0xa6 , HOLD_VIA_CONTROL = 0xac ,
MOD1_DESTINATION = 0xad , MOD1_SOURCE = 0xae , MOD1_VIA = 0xaf , MOD1_AMOUNT_LOW = 0xb0 ,
MOD1_AMOUNT_HIGH = 0xb1 , MOD1_SRC_INVERT = 0xe9 , MOD1_VIA_INVERT = 0xb2 , MOD1_BYPASS = 0xf4 ,
MOD2_DESTINATION = 0xb3 , MOD2_SOURCE = 0xb4 , MOD2_VIA = 0xb5 , MOD2_AMOUNT_LOW = 0xb6 ,
MOD2_AMOUNT_HIGH = 0xb7 , MOD2_SRC_INVERT = 0xea , MOD2_VIA_INVERT = 0xb8 , MOD2_BYPASS = 0xf5 ,
MOD3_DESTINATION = 0xb9 , MOD3_SOURCE = 0xba , MOD3_VIA = 0xbb , MOD3_AMOUNT_LOW = 0xbc ,
MOD3_AMOUNT_HIGH = 0xbd , MOD3_SRC_INVERT = 0xeb , MOD3_VIA_INVERT = 0xbe , MOD3_BYPASS = 0xf6 ,
MOD4_DESTINATION = 0xbf , MOD4_SOURCE = 0xc0 , MOD4_VIA = 0xc1 , MOD4_AMOUNT_LOW = 0xc2 ,
MOD4_AMOUNT_HIGH = 0xc3 , MOD4_SRC_INVERT = 0xec , MOD4_VIA_INVERT = 0xc4 , MOD4_BYPASS = 0xf7 ,
MOD5_DESTINATION = 0xc5 , MOD5_SOURCE = 0xc6 , MOD5_VIA = 0xc7 , MOD5_AMOUNT_LOW = 0xc8 ,
MOD5_AMOUNT_HIGH = 0xc9 , MOD5_SRC_INVERT = 0xed , MOD5_VIA_INVERT = 0xca , MOD5_BYPASS = 0xf8 ,
MOD6_DESTINATION = 0xcb , MOD6_SOURCE = 0xcc , MOD6_VIA = 0xcd , MOD6_AMOUNT_LOW = 0xce ,
MOD6_AMOUNT_HIGH = 0xcf , MOD6_SRC_INVERT = 0xee , MOD6_VIA_INVERT = 0xd0 , MOD6_BYPASS = 0xf9 ,
MOD7_DESTINATION = 0xd1 , MOD7_SOURCE = 0xd2 , MOD7_VIA = 0xd3 , MOD7_AMOUNT_LOW = 0xd4 ,
MOD7_AMOUNT_HIGH = 0xd5 , MOD7_SRC_INVERT = 0xef , MOD7_VIA_INVERT = 0xd6 , MOD7_BYPASS = 0xfa ,
MOD8_DESTINATION = 0xd7 , MOD8_SOURCE = 0xd8 , MOD8_VIA = 0xd9 , MOD8_AMOUNT_LOW = 0xda ,
MOD8_AMOUNT_HIGH = 0xdb , MOD8_SRC_INVERT = 0xf0 , MOD8_VIA_INVERT = 0xdc , MOD8_BYPASS = 0xfb ,
MOD9_DESTINATION = 0xdd , MOD9_SOURCE = 0xde , MOD9_VIA = 0xdf , MOD9_AMOUNT_LOW = 0xe0 ,
MOD9_AMOUNT_HIGH = 0xe1 , MOD9_SRC_INVERT = 0xf1 , MOD9_VIA_INVERT = 0xe2 , MOD9_BYPASS = 0xfc ,
MOD10_DESTINATION = 0xe3 , MOD10_SOURCE = 0xe4 , MOD10_VIA = 0xe5 , MOD10_AMOUNT_LOW = 0xe6 ,
MOD10_AMOUNT_HIGH = 0xe7 , MOD10_SRC_INVERT = 0xf2 , MOD10_VIA_INVERT = 0xe8 , MOD10_BYPASS = 0xfd ,
MOD11_DESTINATION = 0x19b , MOD11_SOURCE = 0x19c , MOD11_VIA = 0x19d , MOD11_AMOUNT_LOW = 0x19e ,
MOD11_AMOUNT_HIGH = 0x19f , MOD11_SRC_INVERT = 0x1a0 , MOD11_VIA_INVERT = 0x1a1 , MOD11_BYPASS = 0x1a2
}
Functions
float exsEnvByteToSeconds (int v)
uint32_t readU32 (std::ifstream &f, bool bigE)
EXSInfo parseEXS (const fs::path &p)
std::vector< EXSCompoundElement > getEXSCompoundElements (const fs::path &p)
std::optional< scxt::SampleID > loadSampleFromEXS (const fs::path &p, int sampleIndex, sample::SampleManager *sm)
bool importEXS (const fs::path &p, engine::Engine &e)
void dumpEXSToLog (const fs::path &p)
Typedef Documentation
byteData_t
using byteData_t = std::vector<uint8_t>
Enumeration Type Documentation
EXSParam
enum class EXSParam : uint16_t strong
Enumerator
MASTER_VOLUME
MASTER_PAN
VOLUME_KEYSCALE
PITCH_BEND_UP
PITCH_BEND_DOWN
MONO_LEGATO
MIDI_MONO_MODE
MIDI_MONO_MODE_PITCH_RANGE
POLYPHONY_VOICES
TRANSPOSE
COARSE_TUNE
FINE_TUNE
GLIDE
PORTA_DOWN
PORTA_UP
FILTER1_TOGGLE
FILTER1_TYPE
FILTER1_FAT
FILTER1_CUTOFF
FILTER1_RESO
FILTER1_DRIVE
FILTER1_KEYTRACK
FILTER2_TOGGLE
FILTER2_TYPE
FILTER2_CUTOFF
FILTER2_RESO
FILTER2_DRIVE
FILTERS_SERIAL_PARALLEL
FILTERS_BLEND
LFO_1_FADE
LFO_1_RATE
LFO_1_WAVE_SHAPE
LFO_1_KEY_TRIGGER
LFO_1_MONO_POLY
LFO_1_PHASE
LFO_1_POSITIVE_OR_MIDPOINT
LFO_1_TEMPO_SYNC
LFO_1_FADE_IN_OR_OUT
LFO_2_RATE
LFO_2_WAVE_SHAPE
LFO_2_FADE
LFO_2_KEY_TRIGGER
LFO_2_MONO_POLY
LFO_2_PHASE
LFO_2_POSITIVE_OR_MIDPOINT
LFO_2_TEMPO_SYNC
LFO_2_FADE_IN_OR_OUT
LFO_3_RATE
LFO_3_WAVE_SHAPE
LFO_3_FADE
LFO_3_KEY_TRIGGER
LFO_3_MONO_POLY
LFO_3_PHASE
LFO_3_POSITIVE_OR_MIDPOINT
LFO_3_TEMPO_SYNC
LFO_3_FADE_IN_OR_OUT
ENV2_TYPE
ENV2_VEL_SENS
ENV2_DELAY_START
ENV2_ATK_CURVE
ENV2_ATK_HI_VEL
ENV2_ATK_LO_VEL
ENV2_HOLD
ENV2_DECAY
ENV2_SUSTAIN
ENV2_RELEASE
ENV2_TIME_CURVE
ENV1_TYPE
ENV1_VEL_SENS
ENV1_VOLUME_HIGH
ENV1_DELAY_START
ENV1_ATK_CURVE
ENV1_ATK_HI_VEL
ENV1_ATK_LO_VEL
ENV1_HOLD
ENV1_DECAY
ENV1_SUSTAIN
ENV1_RELEASE
AMP_VELOCITY_CURVE
VELOCITY_OFFSET
RANDOM_VELOCITY
RANDOM_SAMPLE_SEL
RANDOM_PITCH
XFADE_AMOUNT
XFADE_TYPE
UNISON_TOGGLE
COARSE_TUNE_REMOTE
HOLD_VIA_CONTROL
MOD1_DESTINATION
MOD1_SOURCE
MOD1_VIA
MOD1_AMOUNT_LOW
MOD1_AMOUNT_HIGH
MOD1_SRC_INVERT
MOD1_VIA_INVERT
MOD1_BYPASS
MOD2_DESTINATION
MOD2_SOURCE
MOD2_VIA
MOD2_AMOUNT_LOW
MOD2_AMOUNT_HIGH
MOD2_SRC_INVERT
MOD2_VIA_INVERT
MOD2_BYPASS
MOD3_DESTINATION
MOD3_SOURCE
MOD3_VIA
MOD3_AMOUNT_LOW
MOD3_AMOUNT_HIGH
MOD3_SRC_INVERT
MOD3_VIA_INVERT
MOD3_BYPASS
MOD4_DESTINATION
MOD4_SOURCE
MOD4_VIA
MOD4_AMOUNT_LOW
MOD4_AMOUNT_HIGH
MOD4_SRC_INVERT
MOD4_VIA_INVERT
MOD4_BYPASS
MOD5_DESTINATION
MOD5_SOURCE
MOD5_VIA
MOD5_AMOUNT_LOW
MOD5_AMOUNT_HIGH
MOD5_SRC_INVERT
MOD5_VIA_INVERT
MOD5_BYPASS
MOD6_DESTINATION
MOD6_SOURCE
MOD6_VIA
MOD6_AMOUNT_LOW
MOD6_AMOUNT_HIGH
MOD6_SRC_INVERT
MOD6_VIA_INVERT
MOD6_BYPASS
MOD7_DESTINATION
MOD7_SOURCE
MOD7_VIA
MOD7_AMOUNT_LOW
MOD7_AMOUNT_HIGH
MOD7_SRC_INVERT
MOD7_VIA_INVERT
MOD7_BYPASS
MOD8_DESTINATION
MOD8_SOURCE
MOD8_VIA
MOD8_AMOUNT_LOW
MOD8_AMOUNT_HIGH
MOD8_SRC_INVERT
MOD8_VIA_INVERT
MOD8_BYPASS
MOD9_DESTINATION
MOD9_SOURCE
MOD9_VIA
MOD9_AMOUNT_LOW
MOD9_AMOUNT_HIGH
MOD9_SRC_INVERT
MOD9_VIA_INVERT
MOD9_BYPASS
MOD10_DESTINATION
MOD10_SOURCE
MOD10_VIA
MOD10_AMOUNT_LOW
MOD10_AMOUNT_HIGH
MOD10_SRC_INVERT
MOD10_VIA_INVERT
MOD10_BYPASS
MOD11_DESTINATION
MOD11_SOURCE
MOD11_VIA
MOD11_AMOUNT_LOW
MOD11_AMOUNT_HIGH
MOD11_SRC_INVERT
MOD11_VIA_INVERT
MOD11_BYPASS
Function Documentation
exsEnvByteToSeconds()
float exsEnvByteToSeconds (int v)
Referenced by importEXS().
readU32()
uint32_t readU32 (std::ifstream & f, bool bigE)
Referenced by EXSBlock::read().
parseEXS()
EXSInfo parseEXS (const fs::path & p)
References SCLOG_IF, EXSBlock::TYPE_GROUP, EXSBlock::TYPE_INSTRUMENT, EXSBlock::TYPE_PARAMS, EXSBlock::TYPE_SAMPLE, and EXSBlock::TYPE_ZONE.
Referenced by dumpEXSToLog(), getEXSCompoundElements(), importEXS(), and loadSampleFromEXS().
getEXSCompoundElements()
std::vector< EXSCompoundElement > getEXSCompoundElements (const fs::path & p)
References parseEXS().
Referenced by scxt::sample::compound::getEXSCompoundList().
loadSampleFromEXS()
std::optional< scxt::SampleID > loadSampleFromEXS (const fs::path & p, int sampleIndex, sample::SampleManager * sm)
References SampleManager::loadSampleByPath(), and parseEXS().
Referenced by SampleManager::loadSampleByFileAddress().
importEXS()
bool importEXS (const fs::path & p, engine::Engine & e)
References ImporterContext::addGroup(), scxt::import_support::addImportedModRoute(), ImporterContext::addZoneToGroup(), Zone::ALTERNATE_DIRECTIONS, Zone::ZoneMappingData::amplitude, Zone::attachToSample(), EnvelopeArgs::attackSeconds, scxt::import_support::BP12, scxt::import_support::centsToSemitones(), COARSE_TUNE, Part::configuration, FilterArgs::cutoff, scxt::import_support::Cutoff, scxt::import_support::dBToCubicAttenuation(), EnvelopeArgs::decaySeconds, EnvelopeArgs::delaySeconds, EXSGroup::enableByRoundRobin, Zone::ENDPOINTS, Zone::engine, ENV1_ATK_HI_VEL, ENV1_DECAY, ENV1_DELAY_START, ENV1_HOLD, ENV1_RELEASE, ENV1_SUSTAIN, ENV2_ATK_HI_VEL, ENV2_DECAY, ENV2_DELAY_START, ENV2_HOLD, ENV2_RELEASE, ENV2_SUSTAIN, exsEnvByteToSeconds(), ImportedTarget::filter(), FILTER1_CUTOFF, FILTER1_RESO, FILTER1_TOGGLE, FILTER1_TYPE, FINE_TUNE, ImporterContext::finish(), Zone::FORWARD_ONLY, ImportedSource::fromEG(), Part::getGroup(), ImporterContext::getPart(), Engine::getSampleManager(), EnvelopeArgs::holdSeconds, scxt::import_support::HP12, scxt::import_support::importZoneEnvelope(), scxt::import_support::importZoneFilter(), scxt::import_support::importZoneLoop(), scxt::import_support::importZoneMapping(), ImporterContext::loadSampleFromDisk(), Zone::LOOP_DURING_VOICE, scxt::import_support::LP12, scxt::import_support::LP18, scxt::import_support::LP24, scxt::import_support::LP6, Zone::mapping, EXSGroup::minVelocity, MOD10_DESTINATION, MOD10_SOURCE, MOD11_DESTINATION, MOD11_SOURCE, MOD1_DESTINATION, MOD1_SOURCE, MOD2_DESTINATION, MOD2_SOURCE, MOD3_DESTINATION, MOD3_SOURCE, MOD4_DESTINATION, MOD4_SOURCE, MOD5_DESTINATION, MOD5_SOURCE, MOD6_DESTINATION, MOD6_SOURCE, MOD7_DESTINATION, MOD7_SOURCE, MOD8_DESTINATION, MOD8_SOURCE, MOD9_DESTINATION, MOD9_SOURCE, Group::MONO, Part::PartConfiguration::numExclusiveGroups, Zone::ON_RELEASE, Zone::ONE_SHOT, scxt::import_support::Other, Zone::outputInfo, Zone::ZoneOutputInfo::pan, parseEXS(), PITCH_BEND_DOWN, PITCH_BEND_UP, ImporterContext::raise(), EnvelopeArgs::releaseSeconds, EXSGroup::releaseTrigger, FilterArgs::resonance, EnvelopeArgs::sustainLevel, FilterArgs::type, ImporterContext::unsupported(), Zone::variantData, and Zone::Variants::variants.
Referenced by Engine::loadSampleIntoSelectedPartAndGroup().
dumpEXSToLog()
void dumpEXSToLog (const fs::path & p)
References MOD10_AMOUNT_HIGH, MOD10_AMOUNT_LOW, MOD10_BYPASS, MOD10_DESTINATION, MOD10_SOURCE, MOD10_VIA, MOD11_AMOUNT_HIGH, MOD11_AMOUNT_LOW, MOD11_BYPASS, MOD11_DESTINATION, MOD11_SOURCE, MOD11_VIA, MOD1_AMOUNT_HIGH, MOD1_AMOUNT_LOW, MOD1_BYPASS, MOD1_DESTINATION, MOD1_SOURCE, MOD1_VIA, MOD2_AMOUNT_HIGH, MOD2_AMOUNT_LOW, MOD2_BYPASS, MOD2_DESTINATION, MOD2_SOURCE, MOD2_VIA, MOD3_AMOUNT_HIGH, MOD3_AMOUNT_LOW, MOD3_BYPASS, MOD3_DESTINATION, MOD3_SOURCE, MOD3_VIA, MOD4_AMOUNT_HIGH, MOD4_AMOUNT_LOW, MOD4_BYPASS, MOD4_DESTINATION, MOD4_SOURCE, MOD4_VIA, MOD5_AMOUNT_HIGH, MOD5_AMOUNT_LOW, MOD5_BYPASS, MOD5_DESTINATION, MOD5_SOURCE, MOD5_VIA, MOD6_AMOUNT_HIGH, MOD6_AMOUNT_LOW, MOD6_BYPASS, MOD6_DESTINATION, MOD6_SOURCE, MOD6_VIA, MOD7_AMOUNT_HIGH, MOD7_AMOUNT_LOW, MOD7_BYPASS, MOD7_DESTINATION, MOD7_SOURCE, MOD7_VIA, MOD8_AMOUNT_HIGH, MOD8_AMOUNT_LOW, MOD8_BYPASS, MOD8_DESTINATION, MOD8_SOURCE, MOD8_VIA, MOD9_AMOUNT_HIGH, MOD9_AMOUNT_LOW, MOD9_BYPASS, MOD9_DESTINATION, MOD9_SOURCE, MOD9_VIA, parseEXS(), and SCLOG_IF.
Referenced by main().