shortcircuit-xt: perf_main.cpp File Reference
perf_main.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References scxt::perf::applyLoad(), scxt::perf::bake(), Config::engine, Config::load, scxt::perf::loadFromFile(), RunConfig::Measure, RunConfig::measureIterations, Engine::prepareToPlay(), scxt::perf::printConsoleSummary(), RunConfig::Profile, RunConfig::profileIterations, RunConfig::RealtimePriority, RunConfig::reportPath, Engine::resetTuningFromRuntimeConfig(), Config::run, scxt::perf::runMeasure(), scxt::perf::runProfile(), Engine::runtimeConfig, EngineConfig::sampleRate, Config::sequence, RunConfig::tailSilenceS, Engine::RuntimeConfig::tuningMode, Engine::TWELVE_TET, RunConfig::waitForKey, RunConfig::wavOutputPath, scxt::perf::writeReport(), and scxt::perf::writeWavFloat32().