shortcircuit-xt: GroupMatrixConfig Struct Reference
GroupMatrixConfig Struct Reference
#include <group_matrix.h>
Public Types
using SourceIdentifier = scxt::modulation::shared::SourceIdentifier
using TargetIdentifier = scxt::modulation::shared::TargetIdentifier
using RoutingExtraPayload = scxt::modulation::shared::RoutingExtraPayload
using CurveIdentifier = scxt::modulation::ModulationCurves::CurveIdentifier
using TI = TargetIdentifier
using SI = SourceIdentifier
Static Public Member Functions
static std::function< float(float)> getCurveOperator (CurveIdentifier id)
static bool supportsLag (const SourceIdentifier &s)
static bool isTargetModMatrixDepth (const TargetIdentifier &t)
static size_t getTargetModMatrixElement (const TargetIdentifier &t)
static void setDefaultLagFor (const SourceIdentifier &s, int32_t v)
static int32_t defaultLagFor (const SourceIdentifier &s)
Static Public Attributes
static constexpr bool IsFixedMatrix {true}
static constexpr bool ProvidesNonZeroTargetBases {true}
static constexpr size_t FixedMatrixSize {scxt::modMatrixRowsPerGroup}
static constexpr bool providesTargetRanges {true}
static std::unordered_map< SourceIdentifier, int32_t > defaultLags
Member Typedef Documentation
SourceIdentifier
using SourceIdentifier = scxt::modulation::shared::SourceIdentifier
TargetIdentifier
using TargetIdentifier = scxt::modulation::shared::TargetIdentifier
RoutingExtraPayload
using RoutingExtraPayload = scxt::modulation::shared::RoutingExtraPayload
CurveIdentifier
using CurveIdentifier = scxt::modulation::ModulationCurves::CurveIdentifier
TI
using TI = TargetIdentifier
SI
using SI = SourceIdentifier
Member Function Documentation
getCurveOperator()
static std::function< float(float)> getCurveOperator (CurveIdentifier id) static
References ModulationCurves::getCurveOperator().
supportsLag()
static bool supportsLag (const SourceIdentifier & s) static
isTargetModMatrixDepth()
static bool isTargetModMatrixDepth (const TargetIdentifier & t) static
References TargetIdentifier::gid.
Referenced by GroupMatrixConfig::getTargetModMatrixElement().
getTargetModMatrixElement()
static size_t getTargetModMatrixElement (const TargetIdentifier & t) static
References TargetIdentifier::index, and GroupMatrixConfig::isTargetModMatrixDepth().
setDefaultLagFor()
static void setDefaultLagFor (const SourceIdentifier & s, int32_t v) static
References GroupMatrixConfig::defaultLags.
Referenced by GroupMatrixEndpoints::Sources::MacroSources::MacroSources().
defaultLagFor()
static int32_t defaultLagFor (const SourceIdentifier & s) static
References GroupMatrixConfig::defaultLags.
Member Data Documentation
IsFixedMatrix
constexpr bool IsFixedMatrix {true} static constexpr
ProvidesNonZeroTargetBases
constexpr bool ProvidesNonZeroTargetBases {true} static constexpr
FixedMatrixSize
constexpr size_t FixedMatrixSize {scxt::modMatrixRowsPerGroup} static constexpr
Referenced by GroupMatrixEndpoints::SelfModulationTarget::SelfModulationTarget().
providesTargetRanges
constexpr bool providesTargetRanges {true} static constexpr
defaultLags
std::unordered_map< GroupMatrixConfig::SourceIdentifier, int32_t > defaultLags static
Referenced by GroupMatrixConfig::defaultLagFor(), and GroupMatrixConfig::setDefaultLagFor().
The documentation for this struct was generated from the following files:
group_matrix.h
group_matrix.cpp