shortcircuit-xt: GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent Struct Reference
GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent Struct Reference
#include <GroupZoneTreeControl.h>
Inherits Component.
Public Member Functions
rowTopComponent ()
void enableAdd ()
void enableGZ ()
void resized ()
Public Attributes
std::unique_ptr< rowComponent > gzRow
std::unique_ptr< rowAddComponent > addRow
Constructor & Destructor Documentation
rowTopComponent()
template<typename SidebarParent , bool fz> rowTopComponent ()
Member Function Documentation
enableAdd()
template<typename SidebarParent , bool fz> void enableAdd ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::addRow, GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::gzRow, and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::resized().
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::GroupZoneSidebarWidget().
enableGZ()
template<typename SidebarParent , bool fz> void enableGZ ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::addRow, GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::gzRow, and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::resized().
resized()
template<typename SidebarParent , bool fz> void resized ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::addRow, and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::gzRow.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableAdd(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableGZ().
Member Data Documentation
gzRow
template<typename SidebarParent , bool fz> std::unique_ptr<rowComponent> gzRow
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableAdd(), GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableGZ(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::resized().
addRow
template<typename SidebarParent , bool fz> std::unique_ptr<rowAddComponent> addRow
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableAdd(), GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::enableGZ(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowTopComponent::resized().
The documentation for this struct was generated from the following file:
GroupZoneTreeControl.h