shortcircuit-xt: StdMapColormap Struct Reference
StdMapColormap Struct Reference
Public Member Functions
StdMapColormap (colors_t &c)
void setupFromColormap (colors_t &c)
juce::Colour getImpl (ColorMap::Colors c, float alpha) const override
Public Member Functions inherited from ColorMap
virtual ~ColorMap ()=default
juce::Colour get (Colors c, float alpha=1.f) const
virtual juce::Colour getHover (Colors c, float alpha=1.f) const
std::string toJson () const
Public Attributes
colors_t colorMap
std::array< juce::Colour, ColorMap::lastColor+1 > resolvedMap
Public Attributes inherited from ColorMap
enum scxt::ui::theme::ColorMap::BuiltInColorMaps WIREFRAME
bool hasKnobs {false}
float hoverFactor {0.1f}
Additional Inherited Members
Public Types inherited from ColorMap
enum BuiltInColorMaps : uint32_t { WIREFRAME = 'wire' , LIGHT = 'lite' , HICONTRAST_DARK = 'hico' , TEST = 'test' }
enum Colors : size_t {
accent_1a , accent_1b , accent_1b_alpha_a , accent_1b_alpha_b ,
accent_1b_alpha_c , accent_2a , accent_2a_alpha_a , accent_2a_alpha_b ,
accent_2a_alpha_c , accent_2b , accent_2b_alpha_a , accent_2b_alpha_b ,
accent_2b_alpha_c , bg_1 , bg_2 , bg_3 ,
gutter_2 , gutter_3 , panel_outline_2 , panel_outline_3 ,
knob_fill , generic_content_highest , generic_content_high , generic_content_medium ,
generic_content_low , generic_content_lowest , grid_primary , grid_secondary ,
warning_1a , warning_1b
}
Static Public Member Functions inherited from ColorMap
static std::unique_ptr< ColorMap > createColorMap (BuiltInColorMaps cm)
static std::unique_ptr< ColorMap > jsonToColormap (const std::string &json)
Static Public Attributes inherited from ColorMap
static constexpr uint32_t FILE_COLORMAP_ID {'fcmp'}
static constexpr int lastColor {(int)Colors::warning_1b}
Constructor & Destructor Documentation
StdMapColormap()
StdMapColormap (colors_t & c)
References StdMapColormap::setupFromColormap().
Member Function Documentation
setupFromColormap()
void setupFromColormap (colors_t & c)
References StdMapColormap::colorMap, scxt::ui::theme::keyName(), ColorMap::lastColor, StdMapColormap::resolvedMap, and SCLOG.
Referenced by StdMapColormap::StdMapColormap().
getImpl()
juce::Colour getImpl (ColorMap::Colors c, float alpha) const override virtual
Implements ColorMap.
References StdMapColormap::resolvedMap.
Member Data Documentation
colorMap
colors_t colorMap
Referenced by StdMapColormap::setupFromColormap().
resolvedMap
std::array<juce::Colour, ColorMap::lastColor + 1> resolvedMap
Referenced by StdMapColormap::getImpl(), and StdMapColormap::setupFromColormap().
The documentation for this struct was generated from the following file:
ColorMap.cpp