shortcircuit-xt: SingleValueFactory< A, Msg, ABase > Struct Template Reference
SingleValueFactory< A, Msg, ABase > Struct Template Reference
#include <PayloadDataAttachment.h>
Static Public Member Functions
template<typename W , typename... Args>
static std::pair< std::unique_ptr< A >, std::unique_ptr< W > > attachR (const datamodel::pmd &md, const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, Args... args)
template<typename... Args>
static std::unique_ptr< A > attachOnly (const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, Args... args)
template<typename W , typename... Args>
static void attach (const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, Args... args)
template<typename W , typename... Args>
static void attach (const datamodel::pmd &md, const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, Args... args)
template<typename W , typename... Args>
static void attachAndAdd (const datamodel::pmd &md, const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, Args... args)
template<typename W , typename... Args>
static void attachAndAdd (const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, Args... args)
template<typename W , typename... Args>
static void attachLabelAndAdd (const datamodel::pmd &md, const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, const std::string &lab, Args... args)
template<typename W , typename... Args>
static void attachLabelAndAdd (const typename A::payload_t &p, typename A::value_t &val, app::HasEditor *e, std::unique_ptr< A > &aRes, std::unique_ptr< W > &wRes, const std::string &lab, Args... args)
Member Function Documentation
attachR()
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static std::pair< std::unique_ptr< A >, std::unique_ptr< W > > attachR (const datamodel::pmd & md, const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, Args... args) static
References HasEditor::addSubscription(), HasEditor::setupIntAttachedWidgetForValueMenu(), and HasEditor::setupWidgetForValueTooltip().
attachOnly()
template<typename A , typename Msg , typename ABase = A> template<typename... Args> static std::unique_ptr< A > attachOnly (const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, Args... args) static
References HasEditor::addSubscription(), and scxt::datamodel::describeValue().
attach() [1/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attach (const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, Args... args) static
References scxt::datamodel::describeValue().
attach() [2/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attach (const datamodel::pmd & md, const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, Args... args) static
attachAndAdd() [1/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attachAndAdd (const datamodel::pmd & md, const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, Args... args) static
Referenced by SingleValueFactory< A, Msg, ABase >::attachAndAdd(), and SingleValueFactory< A, Msg, ABase >::attachLabelAndAdd().
attachAndAdd() [2/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attachAndAdd (const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, Args... args) static
References SingleValueFactory< A, Msg, ABase >::attachAndAdd(), and scxt::datamodel::describeValue().
attachLabelAndAdd() [1/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attachLabelAndAdd (const datamodel::pmd & md, const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, const std::string & lab, Args... args) static
References SingleValueFactory< A, Msg, ABase >::attachAndAdd().
Referenced by SingleValueFactory< A, Msg, ABase >::attachLabelAndAdd().
attachLabelAndAdd() [2/2]
template<typename A , typename Msg , typename ABase = A> template<typename W , typename... Args> static void attachLabelAndAdd (const typename A::payload_t & p, typename A::value_t & val, app::HasEditor * e, std::unique_ptr< A > & aRes, std::unique_ptr< W > & wRes, const std::string & lab, Args... args) static
References SingleValueFactory< A, Msg, ABase >::attachLabelAndAdd(), and scxt::datamodel::describeValue().
The documentation for this struct was generated from the following file:
PayloadDataAttachment.h