shortcircuit-xt: ThreadingChecker Struct Reference
ThreadingChecker Struct Reference
#include <utils.h>
Public Member Functions
void addAsAClientThread ()
void addAsAClientThread (std::thread::id tid)
void removeAsAClientThread ()
bool isClientThread () const
void registerAsSerialThread ()
bool isSerialThread () const
void registerAsAudioThread ()
bool isAudioThread () const
std::string threadName ()
Public Attributes
std::atomic< bool > bypassThreadChecks {false}
std::thread::id serialThreadId {}
std::thread::id audioThreadId {}
std::set< std::thread::id > clientThreadIds {}
Member Function Documentation
addAsAClientThread() [1/2]
void addAsAClientThread ()
Referenced by BrowserDB::BrowserDB(), MessageController::registerClient(), ScanWorker::ScanWorker(), and SCXTEditor::SCXTEditor().
addAsAClientThread() [2/2]
void addAsAClientThread (std::thread::id tid)
removeAsAClientThread()
void removeAsAClientThread ()
Referenced by MessageController::unregisterClient().
isClientThread()
bool isClientThread () const
Referenced by scxt::messaging::client::clientSendToSerialization(), and SCXTEditor::drainCallbackQueue().
registerAsSerialThread()
void registerAsSerialThread ()
isSerialThread()
bool isSerialThread () const
Referenced by SampleManager::loadSampleByPath(), MessageController::restartAudioThreadFromSerial(), MessageController::scheduleAudioThreadFunctionCallback(), scxt::messaging::client::serializationSendToClient(), scxt::messaging::client::serializationThreadExecuteClientMessage(), MessageController::stopAudioThreadThenRunOnSerial(), and MessageController::updateAudioRunning().
registerAsAudioThread()
void registerAsAudioThread ()
isAudioThread()
bool isAudioThread () const
Referenced by scxt::messaging::audio::sendStructureRefresh().
threadName()
std::string threadName ()
Member Data Documentation
bypassThreadChecks
std::atomic<bool> bypassThreadChecks {false}
Referenced by MessageController::scheduleAudioThreadFunctionCallback().
serialThreadId
std::thread::id serialThreadId {}
audioThreadId
std::thread::id audioThreadId {}
clientThreadIds
std::set<std::thread::id> clientThreadIds {}
The documentation for this struct was generated from the following file:
utils.h