shortcircuit-xt: EXSSample Struct Reference
EXSSample Struct Reference
Public Member Functions
EXSSample (EXSBlock in)
void parse ()
Public Member Functions inherited from EXSObject
EXSObject (EXSBlock in)
void resetPosition ()
void skip (int S)
int32_t readByteToInt ()
uint8_t readByte ()
int16_t readS16 ()
uint16_t readU16 ()
uint32_t readU32 ()
std::string readStringNoTerm (size_t chars)
std::string readStringNullTerm (size_t chars)
Public Attributes
int waveDataStart
int length
int sampleRate
int bitDepth
int channels
int channels2
std::string type
int size
bool isCompressed = false
std::string filePath
std::string fileName
Public Attributes inherited from EXSObject
EXSBlock within
size_t position {0}
Constructor & Destructor Documentation
EXSSample()
EXSSample (EXSBlock in)
References EXSSample::parse(), EXSBlock::size, EXSBlock::type, and EXSBlock::TYPE_SAMPLE.
Member Function Documentation
parse()
void parse ()
References EXSSample::bitDepth, EXSSample::channels, EXSSample::channels2, EXSSample::fileName, EXSSample::filePath, EXSSample::isCompressed, EXSSample::length, EXSBlock::name, EXSObject::position, EXSObject::readStringNoTerm(), EXSObject::readStringNullTerm(), EXSObject::readU32(), EXSObject::resetPosition(), EXSSample::sampleRate, EXSBlock::size, EXSSample::size, EXSObject::skip(), EXSSample::type, EXSSample::waveDataStart, and EXSObject::within.
Referenced by EXSSample::EXSSample().
Member Data Documentation
waveDataStart
int waveDataStart
Referenced by EXSSample::parse().
length
int length
Referenced by EXSSample::parse().
sampleRate
int sampleRate
Referenced by EXSSample::parse().
bitDepth
int bitDepth
Referenced by EXSSample::parse().
channels
int channels
Referenced by EXSSample::parse().
channels2
int channels2
Referenced by EXSSample::parse().
type
std::string type
Referenced by EXSSample::parse().
size
int size
Referenced by EXSSample::parse().
isCompressed
bool isCompressed = false
Referenced by EXSSample::parse().
filePath
std::string filePath
Referenced by EXSSample::parse().
fileName
std::string fileName
Referenced by EXSSample::parse().
The documentation for this struct was generated from the following file:
exs_import.cpp