shortcircuit-xt: MemoryPool Struct Reference
MemoryPool Struct Reference
Public Types
typedef uint8_t data_t
Public Member Functions
~MemoryPool ()
void preReservePool (size_t blockSize)
data_t * checkoutBlock (size_t blockSize)
void returnBlock (data_t *block, size_t blockSize)
Public Member Functions inherited from MoveableOnly< MemoryPool >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< MemoryPool >
MoveableOnly ()
~MoveableOnly ()=default
Member Typedef Documentation
data_t
typedef uint8_t data_t
Constructor & Destructor Documentation
~MemoryPool()
~MemoryPool ()
Member Function Documentation
preReservePool()
void preReservePool (size_t blockSize)
Referenced by SCXTVFXConfig< OSFactor >::preReservePool(), and Processor::setupProcessor().
checkoutBlock()
MemoryPool::data_t * checkoutBlock (size_t blockSize)
Referenced by SCXTVFXConfig< OSFactor >::checkoutBlock().
returnBlock()
void returnBlock (data_t * block, size_t blockSize)
Referenced by SCXTVFXConfig< OSFactor >::returnBlock().
The documentation for this struct was generated from the following files:
memory_pool.h
memory_pool.cpp