shortcircuit-xt: MixerScreen Struct Reference
MixerScreen Struct Reference
#include <MixerScreen.h>
Public Types
using partFXMD_t = std::array< datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams >
using partFXStorage_t = std::pair< partFXMD_t, engine::BusEffectStorage >
using busPartsFX_t = std::array< partFXStorage_t, engine::Bus::maxEffectsPerBus >
using busFX_t = std::array< busPartsFX_t, scxt::maxOutputs >
using busSend_t = std::array< engine::Bus::BusSendStorage, scxt::maxBusses >
Public Member Functions
MixerScreen (SCXTEditor *e)
~MixerScreen ()
void visibilityChanged () override
void resized () override
void selectBus (int index)
void onBusEffectFullData (int bus, int slot, const std::array< datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams > &, const engine::BusEffectStorage &)
void onBusSendData (int bus, const engine::Bus::BusSendStorage &s)
std::string effectDisplayName (engine::AvailableBusEffects, bool forMenu)
void setFXSlotToType (int bus, int slot, engine::AvailableBusEffects t)
void showFXSelectionMenu (int bus, int slot)
void sendBusSendStorage (int bus)
void setVULevelForBusses (const std::array< std::array< std::atomic< float >, 2 >, engine::Patch::Busses::busCount > &x)
void onOtherTabSelection ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::unique_ptr< browser_ui::BrowserPane > browser
std::array< std::unique_ptr< mixer_screen::PartEffectsPane >, engine::Bus::maxEffectsPerBus > partPanes
std::unique_ptr< mixer_screen::BusPane > busPane
busFX_t busEffectsData
busSend_t busSendData
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int sideWidths = 196
Member Typedef Documentation
partFXMD_t
using partFXMD_t = std::array<datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams>
partFXStorage_t
using partFXStorage_t = std::pair<partFXMD_t, engine::BusEffectStorage>
busPartsFX_t
using busPartsFX_t = std::array<partFXStorage_t, engine::Bus::maxEffectsPerBus>
busFX_t
using busFX_t = std::array<busPartsFX_t, scxt::maxOutputs>
busSend_t
using busSend_t = std::array<engine::Bus::BusSendStorage, scxt::maxBusses>
Constructor & Destructor Documentation
MixerScreen()
MixerScreen (SCXTEditor * e)
References MixerScreen::browser, MixerScreen::busPane, HasEditor::editor, MixerScreen::partPanes, and MixerScreen::selectBus().
~MixerScreen()
~MixerScreen ()
Member Function Documentation
visibilityChanged()
void visibilityChanged () override
resized()
void resized () override
References MixerScreen::browser, MixerScreen::busPane, MixerScreen::partPanes, and MixerScreen::sideWidths.
selectBus()
void selectBus (int index)
References MixerScreen::busPane, HasEditor::editor, MixerScreen::partPanes, and SCXTEditor::setTabSelection().
Referenced by MixerScreen::MixerScreen(), ChannelStrip::mouseDown(), and MixerScreen::onOtherTabSelection().
onBusEffectFullData()
void onBusEffectFullData (int bus, int slot, const std::array< datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams > & pmd, const engine::BusEffectStorage & bes)
References MixerScreen::busEffectsData, MixerScreen::busPane, and MixerScreen::partPanes.
onBusSendData()
void onBusSendData (int bus, const engine::Bus::BusSendStorage & s)
References MixerScreen::busPane, and MixerScreen::busSendData.
effectDisplayName()
std::string effectDisplayName (engine::AvailableBusEffects t, bool forMenu)
References scxt::engine::bonsai, scxt::engine::delay, scxt::engine::flanger, scxt::engine::floatydelay, scxt::engine::nimbus, scxt::engine::none, scxt::engine::phaser, scxt::engine::reverb1, scxt::engine::reverb2, scxt::engine::rotaryspeaker, and scxt::engine::treemonster.
Referenced by ChannelStrip::effectsChanged(), PartEffectsPane::rebuild(), and MixerScreen::showFXSelectionMenu().
setFXSlotToType()
void setFXSlotToType (int bus, int slot, engine::AvailableBusEffects t)
References MixerScreen::busPane, and HasEditor::sendToSerialization().
showFXSelectionMenu()
void showFXSelectionMenu (int bus, int slot)
References scxt::engine::bonsai, SCXTEditor::defaultPopupMenuOptions(), scxt::engine::delay, HasEditor::editor, MixerScreen::effectDisplayName(), scxt::engine::flanger, scxt::engine::floatydelay, scxt::engine::nimbus, scxt::engine::none, scxt::engine::phaser, scxt::engine::reverb1, scxt::engine::reverb2, and scxt::engine::treemonster.
Referenced by PartEffectsPane::showHamburger().
sendBusSendStorage()
void sendBusSendStorage (int bus)
References MixerScreen::busSendData, and HasEditor::sendToSerialization().
setVULevelForBusses()
void setVULevelForBusses (const std::array< std::array< std::atomic< float >, 2 >, engine::Patch::Busses::busCount > & x)
References MixerScreen::busPane.
onOtherTabSelection()
void onOtherTabSelection ()
References HasEditor::editor, SCXTEditor::queryTabSelection(), and MixerScreen::selectBus().
Member Data Documentation
sideWidths
constexpr int sideWidths = 196 static constexpr
Referenced by MixerScreen::resized().
browser
std::unique_ptr<browser_ui::BrowserPane> browser
Referenced by MixerScreen::MixerScreen(), and MixerScreen::resized().
partPanes
std::array<std::unique_ptr<mixer_screen::PartEffectsPane>, engine::Bus::maxEffectsPerBus> partPanes
Referenced by MixerScreen::MixerScreen(), MixerScreen::onBusEffectFullData(), MixerScreen::resized(), and MixerScreen::selectBus().
busPane
std::unique_ptr<mixer_screen::BusPane> busPane
Referenced by MixerScreen::MixerScreen(), MixerScreen::onBusEffectFullData(), MixerScreen::onBusSendData(), MixerScreen::resized(), MixerScreen::selectBus(), MixerScreen::setFXSlotToType(), and MixerScreen::setVULevelForBusses().
busEffectsData
busFX_t busEffectsData
Referenced by PartEffectsPane::attachMenuButtonToInt(), PartEffectsPane::attachWidgetToFloat(), ChannelStrip::ChannelStrip(), ChannelStrip::effectsChanged(), MixerScreen::onBusEffectFullData(), PartEffectsPane::paintMetadata(), and PartEffectsPane::rebuild().
busSendData
busSend_t busSendData
Referenced by ChannelStrip::ChannelStrip(), ChannelStrip::labelPluginOutput(), MixerScreen::onBusSendData(), ChannelStrip::resetAuxRoutingGlyph(), MixerScreen::sendBusSendStorage(), ChannelStrip::showAuxRouting(), and ChannelStrip::showPluginOutput().
The documentation for this struct was generated from the following files:
MixerScreen.h
MixerScreen.cpp