shortcircuit-xt: UndoManager Struct Reference
UndoManager Struct Reference
#include <undo.h>
Public Member Functions
void storeUndoStep (std::unique_ptr< UndoableItem > item)
void storeUndoStepTagged (std::unique_ptr< UndoableItem > item, const std::string &tag, UndoGesture g)
bool applyUndoStep (engine::Engine &e)
bool applyRedoStep (engine::Engine &e)
void clear ()
bool hasUndoSteps () const
bool hasRedoSteps () const
size_t undoStackSize () const
size_t redoStackSize () const
void openGesture (const std::string &tag)
void closeGesture ()
bool gestureCovers (const std::string &tag) const
void beginCoalescing ()
void endCoalescing ()
Member Function Documentation
storeUndoStep()
void storeUndoStep (std::unique_ptr< UndoableItem > item)
References UndoManager::closeGesture(), and SCLOG_IF.
Referenced by scxt::messaging::client::moveZonesFromTo(), scxt::undo::pushZoneAddUndo(), and UndoManager::storeUndoStepTagged().
storeUndoStepTagged()
void storeUndoStepTagged (std::unique_ptr< UndoableItem > item, const std::string & tag, UndoGesture g)
References scxt::undo::Begin, scxt::undo::Discrete, UndoManager::gestureCovers(), UndoManager::openGesture(), SCLOG_IF, and UndoManager::storeUndoStep().
Referenced by scxt::undo::pushPartStreamUndo(), and scxt::undo::pushPayloadUndoFor().
applyUndoStep()
bool applyUndoStep (engine::Engine & e)
References UndoManager::closeGesture(), UndoManager::endCoalescing(), Engine::getMessageController(), and SCLOG_IF.
Referenced by scxt::messaging::client::doUndo().
applyRedoStep()
bool applyRedoStep (engine::Engine & e)
References UndoManager::closeGesture(), UndoManager::endCoalescing(), Engine::getMessageController(), and SCLOG_IF.
Referenced by scxt::messaging::client::doRedo().
clear()
void clear ()
References UndoManager::closeGesture(), UndoManager::endCoalescing(), and SCLOG_IF.
Referenced by scxt::messaging::client::doResetEngine(), and scxt::messaging::client::doUnstreamEngineState().
hasUndoSteps()
bool hasUndoSteps () const
hasRedoSteps()
bool hasRedoSteps () const
undoStackSize()
size_t undoStackSize () const
redoStackSize()
size_t redoStackSize () const
openGesture()
void openGesture (const std::string & tag)
Referenced by UndoManager::storeUndoStepTagged().
closeGesture()
void closeGesture ()
Referenced by UndoManager::applyRedoStep(), UndoManager::applyUndoStep(), UndoManager::clear(), scxt::messaging::client::doEndEdit(), scxt::messaging::client::doMacroBeginEndEdit(), and UndoManager::storeUndoStep().
gestureCovers()
bool gestureCovers (const std::string & tag) const
Referenced by scxt::undo::pushPartStreamUndo(), scxt::undo::pushPayloadUndoFor(), and UndoManager::storeUndoStepTagged().
beginCoalescing()
void beginCoalescing ()
Referenced by scxt::messaging::client::doBeginEdit().
endCoalescing()
void endCoalescing ()
Referenced by UndoManager::applyRedoStep(), UndoManager::applyUndoStep(), UndoManager::clear(), and scxt::messaging::client::doEndEdit().
The documentation for this struct was generated from the following files:
undo.h
undo.cpp