shortcircuit-xt: MiscPanel::NumDenQuantAtt Struct Reference
MiscPanel::NumDenQuantAtt Struct Reference
Inherits Continuous.
Public Member Functions
NumDenQuantAtt (intatt_t &n, intatt_t &d)
float getValue () const override
float getDefaultValue () const override
std::string getLabel () const override
void syncValue ()
void setValueFromGUI (const float &f) override
void setValueFromModel (const float &f) override
std::string getValueAsStringFor (float f) const override
void setValueAsString (const std::string &s) override
float getMin () const override
float getMax () const override
Public Attributes
intatt_t & num
intatt_t & den
float value {0}
Constructor & Destructor Documentation
NumDenQuantAtt()
NumDenQuantAtt (intatt_t & n, intatt_t & d)
Member Function Documentation
getValue()
float getValue () const override
References MiscPanel::NumDenQuantAtt::value.
getDefaultValue()
float getDefaultValue () const override
getLabel()
std::string getLabel () const override
syncValue()
void syncValue ()
References MiscPanel::NumDenQuantAtt::den, PayloadDataAttachment< Payload, ValueType >::getValue(), MiscPanel::NumDenQuantAtt::num, and MiscPanel::NumDenQuantAtt::value.
setValueFromGUI()
void setValueFromGUI (const float & f) override
References MiscPanel::NumDenQuantAtt::den, MiscPanel::NumDenQuantAtt::num, PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), and MiscPanel::NumDenQuantAtt::value.
Referenced by MiscPanel::NumDenQuantAtt::setValueAsString().
setValueFromModel()
void setValueFromModel (const float & f) override
References MiscPanel::NumDenQuantAtt::value.
getValueAsStringFor()
std::string getValueAsStringFor (float f) const override
setValueAsString()
void setValueAsString (const std::string & s) override
References MiscPanel::NumDenQuantAtt::getMax(), and MiscPanel::NumDenQuantAtt::setValueFromGUI().
getMin()
float getMin () const override
getMax()
float getMax () const override
Referenced by MiscPanel::NumDenQuantAtt::setValueAsString().
Member Data Documentation
num
intatt_t& num
Referenced by MiscPanel::NumDenQuantAtt::setValueFromGUI(), and MiscPanel::NumDenQuantAtt::syncValue().
den
intatt_t & den
Referenced by MiscPanel::NumDenQuantAtt::setValueFromGUI(), and MiscPanel::NumDenQuantAtt::syncValue().
value
float value {0}
Referenced by MiscPanel::NumDenQuantAtt::getValue(), MiscPanel::NumDenQuantAtt::setValueFromGUI(), MiscPanel::NumDenQuantAtt::setValueFromModel(), and MiscPanel::NumDenQuantAtt::syncValue().
The documentation for this struct was generated from the following file:
LFOPane.cpp