shortcircuit-xt: Patch Struct Reference
Patch Struct Reference
Classes
struct Busses
Public Types
typedef std::array< std::unique_ptr< Part >, numParts > partContainer_t
Public Member Functions
Patch ()
void process (Engine &e)
void resetToBlankPatch ()
bool usesOutputBus (int bus)
void setupBussesOnUnstream (Engine &e)
const std::unique_ptr< Part > & getPart (int i) const
Get a part by the index in array.
int getPartIndex (const PartID &pid) const
Get the index of a part by the PartID.
const std::unique_ptr< Part > & getPart (const PartID &pid) const
Get the part by part ID.
void onSampleRateChanged () override
partContainer_t::iterator begin () noexcept
partContainer_t::const_iterator cbegin () const noexcept
partContainer_t::iterator end () noexcept
partContainer_t::const_iterator cend () const noexcept
const partContainer_t & getParts () const
Public Member Functions inherited from MoveableOnly< Patch >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Public Attributes
struct scxt::engine::Patch::Busses busses
PatchID id
uint64_t streamingVersion {0}
Engine * parentEngine {nullptr}
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Patch >
MoveableOnly ()
~MoveableOnly ()=default
Protected Member Functions inherited from LeakDetected< T >
LeakDetected ()
LeakDetected (LeakDetected &&)
LeakDetected (const LeakDetected &)
~LeakDetected ()
void leakDetect (int dir)
Member Typedef Documentation
partContainer_t
typedef std::array<std::unique_ptr<Part>, numParts> partContainer_t
Constructor & Destructor Documentation
Patch()
Patch ()
References Patch::resetToBlankPatch().
Member Function Documentation
process()
void process (Engine & e)
References Patch::Busses::auxBusses, Patch::busses, Bus::clear(), Patch::Busses::mainBus, and Patch::Busses::partBusses.
resetToBlankPatch()
void resetToBlankPatch ()
References SampleRateSupport::setSampleRate(), and Patch::streamingVersion.
Referenced by Patch::Patch().
usesOutputBus()
bool usesOutputBus (int bus)
References Patch::busses, and Patch::Busses::usesOutput.
setupBussesOnUnstream()
void setupBussesOnUnstream (Engine & e)
References Patch::Busses::auxBusses, Bus::busSendStorage, Patch::busses, Bus::initializeAfterUnstream(), Patch::Busses::mainBus, Patch::Busses::partBusses, and Bus::BusSendStorage::supportsSends.
getPart() [1/2]
const std::unique_ptr<Part>& getPart (int i) const
Get a part by the index in array.
getPartIndex()
int getPartIndex (const PartID & pid) const
Get the index of a part by the PartID.
Referenced by Patch::getPart().
getPart() [2/2]
const std::unique_ptr<Part>& getPart (const PartID & pid) const
Get the part by part ID.
May throw.
References Patch::getPartIndex(), and ID< idType_v >::to_string().
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References Patch::Busses::auxBusses, Patch::busses, SampleRateSupport::getSampleRate(), Patch::Busses::mainBus, Patch::Busses::partBusses, SampleRateSupport::samplerate, and SampleRateSupport::setSampleRate().
begin()
partContainer_t::iterator begin () noexcept
cbegin()
partContainer_t::const_iterator cbegin () const noexcept
end()
partContainer_t::iterator end () noexcept
cend()
partContainer_t::const_iterator cend () const noexcept
getParts()
const partContainer_t& getParts () const
Member Data Documentation
busses
struct scxt::engine::Patch::Busses busses
Referenced by Patch::onSampleRateChanged(), Patch::process(), Patch::setupBussesOnUnstream(), and Patch::usesOutputBus().
id
PatchID id
streamingVersion
uint64_t streamingVersion {0}
Referenced by Patch::resetToBlankPatch().
parentEngine
Engine* parentEngine {nullptr}
Referenced by Group::getEngine(), Zone::getEngine(), and scxt_traits< scxt::engine::Group >::to().
The documentation for this struct was generated from the following files:
patch.h
patch.cpp