shortcircuit-xt: ModulatorStorage Struct Reference
ModulatorStorage Struct Reference
#include <modulator_storage.h>
Public Types
enum ModulatorShape : int16_t {
STEP , LFO_SINE , LFO_RAMP , LFO_TRI ,
LFO_SAW_TRI_RAMP , LFO_PULSE , LFO_SMOOTH_NOISE , LFO_SH_NOISE ,
LFO_ENV , MSEG
}
enum TriggerMode : int16_t {
KEYTRIGGER , FREERUN , RANDOM , RELEASE ,
ONESHOT
}
Public Member Functions
DECLARE_ENUM_STRING (ModulatorShape)
DECLARE_ENUM_STRING (TriggerMode)
void configureCalculatedState ()
bool isStep () const
bool isMSEG () const
bool isEnv () const
bool isCurve () const
Public Attributes
enum scxt::modulation::ModulatorStorage::ModulatorShape LFO_SINE
enum scxt::modulation::ModulatorStorage::TriggerMode KEYTRIGGER
float rate {0.f}
float start_phase {0.f}
float amplitude {1.f}
bool temposync {false}
modulators::StepLFOStorage stepLfoStorage
modulators::CurveLFOStorage curveLfoStorage
modulators::EnvLFOStorage envLfoStorage
bool modulatorConsistent {true}
Member Enumeration Documentation
ModulatorShape
enum ModulatorShape : int16_t
Enumerator
STEP
LFO_SINE
LFO_RAMP
LFO_TRI
LFO_SAW_TRI_RAMP
LFO_PULSE
LFO_SMOOTH_NOISE
LFO_SH_NOISE
LFO_ENV
MSEG
TriggerMode
enum TriggerMode : int16_t
Enumerator
KEYTRIGGER
FREERUN
RANDOM
RELEASE
ONESHOT
Member Function Documentation
DECLARE_ENUM_STRING() [1/2]
DECLARE_ENUM_STRING (ModulatorShape)
DECLARE_ENUM_STRING() [2/2]
DECLARE_ENUM_STRING (TriggerMode)
configureCalculatedState()
void configureCalculatedState ()
isStep()
bool isStep () const
References ModulatorStorage::STEP.
Referenced by ModulatorStorage::isCurve().
isMSEG()
bool isMSEG () const
References ModulatorStorage::MSEG.
Referenced by ModulatorStorage::isCurve().
isEnv()
bool isEnv () const
References ModulatorStorage::LFO_ENV.
Referenced by ModulatorStorage::isCurve().
isCurve()
bool isCurve () const
References ModulatorStorage::isEnv(), ModulatorStorage::isMSEG(), and ModulatorStorage::isStep().
Member Data Documentation
LFO_SINE
enum scxt::modulation::ModulatorStorage::ModulatorShape LFO_SINE
Referenced by CurveLFO::attack(), and scxt::sf2_support::importSF2().
KEYTRIGGER
enum scxt::modulation::ModulatorStorage::TriggerMode KEYTRIGGER
rate
float rate {0.f}
start_phase
float start_phase {0.f}
Referenced by StepLFO::assign().
amplitude
float amplitude {1.f}
temposync
bool temposync {false}
Referenced by StepLFO::assign(), CurveLFO::process(), and StepLFO::process().
stepLfoStorage
modulators::StepLFOStorage stepLfoStorage
Referenced by StepLFO::assign(), and StepLFOPane::StepRender::recalcCurve().
curveLfoStorage
modulators::CurveLFOStorage curveLfoStorage
envLfoStorage
modulators::EnvLFOStorage envLfoStorage
Referenced by ENVLFOPane::ENVPlotData::recalculateCurvePath().
modulatorConsistent
bool modulatorConsistent {true}
The documentation for this struct was generated from the following file:
modulator_storage.h