shortcircuit-xt: WelcomeScreen Struct Reference
WelcomeScreen Struct Reference
Public Member Functions
WelcomeScreen (SCXTEditor *e)
void visibilityChanged () override
void mouseDown (const juce::MouseEvent &e) override
void paint (juce::Graphics &g) override
bool keyPressed (const juce::KeyPress &key) override
void okGotItDontShowAgain ()
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (WelcomeScreen)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (const W &widget, const A &attachment)
Static Public Attributes
static constexpr int welcomeVersion {2}
Additional Inherited Members
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
WelcomeScreen()
WelcomeScreen (SCXTEditor * e)
Member Function Documentation
visibilityChanged()
void visibilityChanged () override
mouseDown()
void mouseDown (const juce::MouseEvent & e) override
References WelcomeScreen::okGotItDontShowAgain().
paint()
void paint (juce::Graphics & g) override
References ColorMap::bg_1, HasEditor::editor, ColorMap::generic_content_high, ColorMap::generic_content_highest, ColorMap::generic_content_medium, ThemeApplier::interBoldFor(), ThemeApplier::interLightFor(), SCXTEditor::themeApplier, SCXTEditor::themeColor(), scxt::ui::app::other_screens::txt, and ColorMap::warning_1a.
keyPressed()
bool keyPressed (const juce::KeyPress & key) override
References WelcomeScreen::okGotItDontShowAgain().
okGotItDontShowAgain()
void okGotItDontShowAgain ()
References SCXTEditor::defaultsProvider, HasEditor::editor, scxt::infrastructure::welcomeScreenSeen, and WelcomeScreen::welcomeVersion.
Referenced by WelcomeScreen::keyPressed(), and WelcomeScreen::mouseDown().
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR()
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (WelcomeScreen)
Member Data Documentation
welcomeVersion
constexpr int welcomeVersion {2} static constexpr
Referenced by SCXTEditor::idle(), and WelcomeScreen::okGotItDontShowAgain().
The documentation for this struct was generated from the following files:
WelcomeScreen.h
WelcomeScreen.cpp