shortcircuit-xt: KEYGROUP Struct Reference
KEYGROUP Struct Reference
Public Member Functions
void parse (const char *data, uint32_t size)
Public Attributes
KLOC kloc
std::vector< ZONE > zones
std::vector< EG > egs
std::vector< FILTER > filters
std::vector< LFO > lfos
std::vector< MODULATION > modulations
Member Function Documentation
parse()
void parse (const char * data, uint32_t size)
References KEYGROUP::egs, KEYGROUP::filters, scxt::akai_support::fourCCSize(), KEYGROUP::kloc, KEYGROUP::lfos, KLOC::load(), ZONE::load(), EG::load(), FILTER::load(), LFO::load(), MODULATION::load(), KEYGROUP::modulations, and KEYGROUP::zones.
Referenced by AKPFile::load().
Member Data Documentation
kloc
KLOC kloc
Referenced by KEYGROUP::parse().
zones
std::vector<ZONE> zones
Referenced by KEYGROUP::parse().
egs
std::vector<EG> egs
Referenced by KEYGROUP::parse().
filters
std::vector<FILTER> filters
Referenced by KEYGROUP::parse().
lfos
std::vector<LFO> lfos
Referenced by KEYGROUP::parse().
modulations
std::vector<MODULATION> modulations
Referenced by KEYGROUP::parse().
The documentation for this struct was generated from the following file:
akai_import.cpp