shortcircuit-xt: MissingResolutionScreen Struct Reference
MissingResolutionScreen Struct Reference
#include <MissingResolutionScreen.h>
Public Member Functions
MissingResolutionScreen (SCXTEditor *e)
~MissingResolutionScreen ()
void paint (juce::Graphics &g) override
void resized () override
void mouseUp (const juce::MouseEvent &) override
void setWorkItemList (const std::vector< engine::MissingResolutionWorkItem > &l)
void resolveItem (int idx)
void applyResolution (int idx, const fs::path &toThis)
void applyDirectoryResolution (std::vector< engine::MissingResolutionWorkItem > indexes, const fs::path &newParent)
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MissingResolutionScreen)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::unique_ptr< sst::jucegui::components::NamedPanel > contentsArea
std::unique_ptr< juce::FileChooser > fileChooser
std::vector< engine::MissingResolutionWorkItem > workItems
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
MissingResolutionScreen()
MissingResolutionScreen (SCXTEditor * e)
References MissingResolutionScreen::contentsArea.
~MissingResolutionScreen()
~MissingResolutionScreen ()
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
References MissingResolutionScreen::contentsArea.
mouseUp()
void mouseUp (const juce::MouseEvent &) override
setWorkItemList()
void setWorkItemList (const std::vector< engine::MissingResolutionWorkItem > & l)
References MissingResolutionScreen::contentsArea, Contents::rebuildContents(), and MissingResolutionScreen::workItems.
resolveItem()
void resolveItem (int idx)
References MissingResolutionScreen::fileChooser, scxt::ui::app::shared::juceFileToFsPath(), and MissingResolutionScreen::workItems.
Referenced by WorkItemLineItem::doCallback().
applyResolution()
void applyResolution (int idx, const fs::path & toThis)
References MissingResolutionScreen::applyDirectoryResolution(), MissingResolutionScreen::contentsArea, HasEditor::sendToSerialization(), and MissingResolutionScreen::workItems.
applyDirectoryResolution()
void applyDirectoryResolution (std::vector< engine::MissingResolutionWorkItem > indexes, const fs::path & newParent)
References SCLOG, and HasEditor::sendToSerialization().
Referenced by MissingResolutionScreen::applyResolution().
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR()
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MissingResolutionScreen)
Member Data Documentation
contentsArea
std::unique_ptr<sst::jucegui::components::NamedPanel> contentsArea
Referenced by MissingResolutionScreen::applyResolution(), MissingResolutionScreen::MissingResolutionScreen(), MissingResolutionScreen::resized(), and MissingResolutionScreen::setWorkItemList().
fileChooser
std::unique_ptr<juce::FileChooser> fileChooser
Referenced by MissingResolutionScreen::resolveItem().
workItems
std::vector<engine::MissingResolutionWorkItem> workItems
Referenced by MissingResolutionScreen::applyResolution(), WorkItemLineItem::paint(), Contents::rebuildContents(), MissingResolutionScreen::resolveItem(), and MissingResolutionScreen::setWorkItemList().
The documentation for this struct was generated from the following files:
MissingResolutionScreen.h
MissingResolutionScreen.cpp