shortcircuit-xt: Exception Struct Reference
Exception Struct Reference
Public Member Functions
Exception (sqlite3 *h)
Exception (int rc, const std::string &msg)
const char * what () const noexcept override
Public Attributes
int rc
Constructor & Destructor Documentation
Exception() [1/2]
Exception (sqlite3 * h) explicit
Exception() [2/2]
Exception (int rc, const std::string & msg)
Member Function Documentation
what()
const char* what () const override noexcept
References Exception::rc.
Referenced by WriterWorker::addDebug(), WriterWorker::addDeviceLocation(), BrowserDB::getDeviceLocations(), WriterWorker::loadQueueFunction(), and WriterWorker::setupDatabase().
Member Data Documentation
rc
int rc
Referenced by Exception::what().
The documentation for this struct was generated from the following file:
browser_db.cpp