shortcircuit-xt: DriveArea Struct Reference
DriveArea Struct Reference
Classes
struct DriveAreaRow
Public Member Functions
DriveArea (BrowserPane *b, SCXTEditor *e)
~DriveArea ()
void paint (juce::Graphics &g) override
void resized () override
std::unique_ptr< juce::Component > makeComponent ()
void assignComponentToRow (const std::unique_ptr< juce::Component > &c, int r)
void setRowSelection (const std::unique_ptr< juce::Component > &c, bool r)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
BrowserPane * browserPane {nullptr}
std::unique_ptr< sst::jucegui::components::ListView > listView
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
DriveArea()
DriveArea (BrowserPane * b, SCXTEditor * e)
References DriveArea::assignComponentToRow(), DriveArea::browserPane, DriveArea::listView, DriveArea::makeComponent(), BrowserPane::roots, and DriveArea::setRowSelection().
~DriveArea()
~DriveArea ()
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References DriveArea::browserPane.
resized()
void resized () override
References DriveArea::listView.
makeComponent()
std::unique_ptr< juce::Component > makeComponent ()
Referenced by DriveArea::DriveArea().
assignComponentToRow()
void assignComponentToRow (const std::unique_ptr< juce::Component > & c, int r)
References DriveArea::DriveAreaRow::rowNumber.
Referenced by DriveArea::DriveArea().
setRowSelection()
void setRowSelection (const std::unique_ptr< juce::Component > & c, bool r)
References DriveArea::DriveAreaRow::selected.
Referenced by DriveArea::DriveArea().
Member Data Documentation
browserPane
BrowserPane* browserPane {nullptr}
Referenced by DriveArea::DriveArea(), DriveArea::DriveAreaRow::paint(), DriveArea::paint(), and DriveArea::DriveAreaRow::showPopup().
listView
std::unique_ptr<sst::jucegui::components::ListView> listView
Referenced by DriveArea::DriveArea(), and DriveArea::resized().
The documentation for this struct was generated from the following file:
BrowserPane.cpp