shortcircuit-xt: Browser Struct Reference
Browser Struct Reference
#include <browser.h>
Classes
struct LoadableFile
Public Types
using errorReporter_t = std::function< void(const std::string &, const std::string &)>
using indexedRootPath_t = std::tuple< fs::path, std::string, bool >
Public Member Functions
Browser (BrowserDB &, const infrastructure::DefaultsProvider &, const fs::path &userDirectory, errorReporter_t reportError)
std::vector< indexedRootPath_t > getRootPathsForDeviceView () const
void addRootPathForDeviceView (const fs::path &, bool indexed, messaging::MessageController &)
void removeRootPathForDeviceView (const fs::path &, messaging::MessageController &)
void reindexLocation (const fs::path &)
std::vector< std::pair< fs::path, std::string > > getOSDefaultRootPathsForDeviceView () const
Static Public Member Functions
static bool isLoadableFile (const fs::path &)
static bool isLoadableSample (const fs::path &)
static bool isLoadableSingleSample (const fs::path &)
static bool isLoadableMultiSample (const fs::path &)
static bool isShortCircuitFormatFile (const fs::path &)
static bool isExpandableInBrowser (const fs::path &p)
static std::vector< sample::compound::CompoundElement > expandForBrowser (const fs::path &p)
static std::vector< sample::compound::CompoundElement > getMultiInstrumentElements (const fs::path &)
Public Attributes
fs::path userDirectory
fs::path patchIODirectory
fs::path themeDirectory
fs::path modulatorPresetDirectory
const infrastructure::DefaultsProvider & defaultsProvider
BrowserDB & browserDb
errorReporter_t errorReporter
Member Typedef Documentation
errorReporter_t
using errorReporter_t = std::function<void(const std::string &, const std::string &)>
indexedRootPath_t
using indexedRootPath_t = std::tuple<fs::path, std::string, bool>
Constructor & Destructor Documentation
Browser()
Browser (BrowserDB & db, const infrastructure::DefaultsProvider & dp, const fs::path & userDirectory, errorReporter_t reportError)
References Browser::errorReporter, Browser::modulatorPresetDirectory, Browser::patchIODirectory, Browser::themeDirectory, and Browser::userDirectory.
Member Function Documentation
getRootPathsForDeviceView()
std::vector< Browser::indexedRootPath_t > getRootPathsForDeviceView () const
References Browser::browserDb, BrowserDB::getBrowserLocations(), Browser::getOSDefaultRootPathsForDeviceView(), and Browser::patchIODirectory.
Referenced by BrowserPane::resetRoots().
addRootPathForDeviceView()
void addRootPathForDeviceView (const fs::path & p, bool indexed, messaging::MessageController & mc)
References BrowserDB::addClientToSerialCallback(), BrowserDB::addRemoveBrowserLocation(), and Browser::browserDb.
removeRootPathForDeviceView()
void removeRootPathForDeviceView (const fs::path & p, messaging::MessageController & mc)
References BrowserDB::addClientToSerialCallback(), BrowserDB::addRemoveBrowserLocation(), and Browser::browserDb.
reindexLocation()
void reindexLocation (const fs::path & p)
References Browser::browserDb, and BrowserDB::reindexLocation().
isLoadableFile()
bool isLoadableFile (const fs::path & p) static
References Browser::isLoadableSample(), and Browser::isShortCircuitFormatFile().
Referenced by ScanWorker::ScanDir::go(), and DriveFSArea::recalcContents().
isLoadableSample()
bool isLoadableSample (const fs::path & p) static
References Browser::isLoadableMultiSample(), and Browser::isLoadableSingleSample().
Referenced by Browser::isLoadableFile().
isLoadableSingleSample()
bool isLoadableSingleSample (const fs::path & p) static
References scxt::extensionMatches(), and Browser::LoadableFile::singleSample.
Referenced by scxt::patch_io::addMonolithBinaries(), scxt::sample::compound::getMultisampleCompoundList(), Browser::isLoadableSample(), VariantDisplay::MyTabbedComponent::itemDropped(), and VariantDisplay::selectNextFile().
isLoadableMultiSample()
bool isLoadableMultiSample (const fs::path & p) static
References scxt::extensionMatches(), and Browser::LoadableFile::multiSample.
Referenced by Browser::isExpandableInBrowser(), and Browser::isLoadableSample().
isShortCircuitFormatFile()
bool isShortCircuitFormatFile (const fs::path & p) static
References scxt::extensionMatches(), and Browser::LoadableFile::shortcircuitFormats.
Referenced by Browser::isLoadableFile().
isExpandableInBrowser()
static bool isExpandableInBrowser (const fs::path & p) static
References Browser::isLoadableMultiSample().
expandForBrowser()
std::vector< sample::compound::CompoundElement > expandForBrowser (const fs::path & p) static
References scxt::extensionMatches(), scxt::sample::compound::getGIGCompoundList(), scxt::sample::compound::getMultisampleCompoundList(), scxt::sample::compound::getSF2InstrumentAddresses(), scxt::sample::compound::getSF2SampleAddresses(), and scxt::sample::compound::getSFZCompoundList().
Referenced by DriveFSArea::expandMultifile().
getMultiInstrumentElements()
std::vector< sample::compound::CompoundElement > getMultiInstrumentElements (const fs::path & p) static
References scxt::extensionMatches(), and scxt::sample::compound::getSF2InstrumentAddresses().
Referenced by MappingDisplay::filesDropped(), and MappingDisplay::itemDropped().
getOSDefaultRootPathsForDeviceView()
std::vector< std::pair< fs::path, std::string > > getOSDefaultRootPathsForDeviceView () const
Referenced by Browser::getRootPathsForDeviceView().
Member Data Documentation
userDirectory
fs::path userDirectory
Referenced by Browser::Browser(), and KeyBindings::KeyBindings().
patchIODirectory
fs::path patchIODirectory
Referenced by Browser::Browser(), and Browser::getRootPathsForDeviceView().
themeDirectory
fs::path themeDirectory
Referenced by Browser::Browser().
modulatorPresetDirectory
fs::path modulatorPresetDirectory
Referenced by Browser::Browser(), LfoPane::doLoadPreset(), and LfoPane::doSavePreset().
defaultsProvider
const infrastructure::DefaultsProvider& defaultsProvider
browserDb
BrowserDB& browserDb
Referenced by Browser::addRootPathForDeviceView(), Browser::getRootPathsForDeviceView(), Browser::reindexLocation(), and Browser::removeRootPathForDeviceView().
errorReporter
errorReporter_t errorReporter
Referenced by Browser::Browser().
The documentation for this struct was generated from the following files:
browser.h
browser.cpp
browser_lin.cpp
browser_macos.mm
browser_win.cpp