shortcircuit-xt: BrowserDB Struct Reference
BrowserDB Struct Reference
#include <browser_db.h>
Public Member Functions
BrowserDB (const fs::path &, messaging::MessageController &)
~BrowserDB ()
void writeDebugMessage (const std::string &)
void addRemoveBrowserLocation (const fs::path &, bool index, bool add)
void reindexLocation (const fs::path &)
template<typename T >
void addClientToSerialCallback (const T &)
std::vector< std::pair< fs::path, bool > > getBrowserLocations ()
int numberOfJobsOutstanding () const
int waitForJobsOutstandingComplete (int maxWaitInMS) const
void scanToUpdateSamples ()
Constructor & Destructor Documentation
BrowserDB()
BrowserDB (const fs::path & p, messaging::MessageController & m)
References ThreadingChecker::addAsAClientThread(), and MessageController::threadingChecker.
~BrowserDB()
~BrowserDB ()
Member Function Documentation
writeDebugMessage()
void writeDebugMessage (const std::string & s)
addRemoveBrowserLocation()
void addRemoveBrowserLocation (const fs::path & p, bool index, bool add)
Referenced by Browser::addRootPathForDeviceView(), and Browser::removeRootPathForDeviceView().
reindexLocation()
void reindexLocation (const fs::path & p)
Referenced by Browser::reindexLocation().
addClientToSerialCallback()
template<typename T > void addClientToSerialCallback (const T & msg)
Referenced by Browser::addRootPathForDeviceView(), and Browser::removeRootPathForDeviceView().
getBrowserLocations()
std::vector< std::pair< fs::path, bool > > getBrowserLocations ()
References SCLOG, and Exception::what().
Referenced by Browser::getRootPathsForDeviceView().
numberOfJobsOutstanding()
int numberOfJobsOutstanding () const
Referenced by BrowserDB::waitForJobsOutstandingComplete().
waitForJobsOutstandingComplete()
int waitForJobsOutstandingComplete (int maxWaitInMS) const
References BrowserDB::numberOfJobsOutstanding().
scanToUpdateSamples()
void scanToUpdateSamples ()
The documentation for this struct was generated from the following files:
browser_db.h
browser_db.cpp
browser_db_impl.h