shortcircuit-xt: RoutingPaneContents< RPTraits > Struct Template Reference
RoutingPaneContents< RPTraits > Struct Template Reference
Classes
struct RC
struct RoutingBox
struct SvgPaths
Public Types
typedef connectors::DiscretePayloadDataAttachment< typename RPTraits::info_t, typename RPTraits::route_t > int_attachment_t
typedef connectors::PayloadDataAttachment< typename RPTraits::info_t > attachment_t
typedef connectors::BooleanPayloadDataAttachment< typename RPTraits::info_t > bool_attachment_t
Public Member Functions
RoutingPaneContents (SCXTEditor *e, RoutingPane< RPTraits > *pane)
std::string resolveJsonPath (const std::string &path) const override
std::string getRoutingLabel (scxt::engine::BusAddress rt)
void selectNewRouting ()
void createBindAndPosition (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls) override
void resized () override
std::string getRoutingName (typename RPTraits::route_t r)
void updateProcRoutingFromInfo ()
void updateFromProcessorPanes ()
void updateRoutingLabel ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
RoutingPane< RPTraits > * outputPane {nullptr}
std::unique_ptr< jcmp::TextPushButton > consistentButton
std::unique_ptr< jcmp::Label > consistentLabel
std::unique_ptr< int_attachment_t > routingA
std::unique_ptr< jcmp::MultiSwitch > multiW
std::unique_ptr< attachment_t > outputAttachment
std::unique_ptr< attachment_t > panAttachment
std::unique_ptr< attachment_t > velocitySensitivityAttachment
std::unique_ptr< jcmp::MenuButton > outputRouting
std::unique_ptr< jcmp::Knob > outputKnob
std::unique_ptr< jcmp::Knob > panKnob
std::unique_ptr< jcmp::HSliderFilled > velocitySensitivitySlider
std::unique_ptr< jcmp::Label > velocitySensitivityLabel
std::unique_ptr< bool_attachment_t > oversampleAttachment
std::unique_ptr< jcmp::ToggleButton > oversampleButton
std::unique_ptr< juce::Component > routingLayoutComp
std::array< std::unique_ptr< ProcessorPane::attachment_t >, nOuts > levelA
std::vector< std::unique_ptr< juce::Component > > jsonComponents
std::unique_ptr< SvgPaths > svgPaths
RPTraits::info_t & info
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int nOuts {scxt::processorsPerZoneAndGroup}
Member Typedef Documentation
int_attachment_t
template<typename RPTraits > typedef connectors::DiscretePayloadDataAttachment<typename RPTraits::info_t, typename RPTraits::route_t> int_attachment_t
attachment_t
template<typename RPTraits > typedef connectors::PayloadDataAttachment<typename RPTraits::info_t> attachment_t
bool_attachment_t
template<typename RPTraits > typedef connectors::BooleanPayloadDataAttachment<typename RPTraits::info_t> bool_attachment_t
Constructor & Destructor Documentation
RoutingPaneContents()
template<typename RPTraits > RoutingPaneContents (SCXTEditor * e, RoutingPane< RPTraits > * pane)
References RoutingPaneContents< RPTraits >::info, RoutingPaneContents< RPTraits >::multiW, and RoutingPaneContents< RPTraits >::routingA.
Member Function Documentation
resolveJsonPath()
template<typename RPTraits > std::string resolveJsonPath (const std::string & path) const override
References SCXTEditor::displayError(), HasEditor::editor, and scxt::ui::connectors::jsonlayout::resolveJsonFile().
getRoutingLabel()
template<typename RPTraits > std::string getRoutingLabel (scxt::engine::BusAddress rt)
References scxt::engine::getBusAddressLabel().
Referenced by RoutingPaneContents< RPTraits >::selectNewRouting(), RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo(), and RoutingPaneContents< RPTraits >::updateRoutingLabel().
selectNewRouting()
template<typename RPTraits > void selectNewRouting ()
References scxt::engine::AUX_0, scxt::engine::DEFAULT_BUS, SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, and RoutingPaneContents< RPTraits >::getRoutingLabel().
createBindAndPosition()
template<typename RPTraits > void createBindAndPosition (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls) override
References scxt::ui::connectors::jsonlayout::attachAndPosition(), scxt::ui::connectors::configureUpdater(), scxt::ui::connectors::jsonlayout::createAndPositionNonDataWidget(), scxt::ui::connectors::jsonlayout::createContinuousWidget(), scxt::ui::connectors::jsonlayout::createControlLabel(), scxt::datamodel::describeValue(), SCXTEditor::displayError(), HasEditor::editor, RoutingPaneContents< RPTraits >::jsonComponents, RoutingPaneContents< RPTraits >::levelA, RoutingPaneContents< RPTraits >::outputPane, scxt::dsp::processor::proct_none, RoutingPaneContents< RPTraits >::routingLayoutComp, and SCLOG_IF.
resized()
template<typename RPTraits > void resized () override
References RoutingPaneContents< RPTraits >::consistentButton, RoutingPaneContents< RPTraits >::consistentLabel, RoutingPaneContents< RPTraits >::multiW, RoutingPaneContents< RPTraits >::outputKnob, RoutingPaneContents< RPTraits >::outputRouting, RoutingPaneContents< RPTraits >::oversampleButton, RoutingPaneContents< RPTraits >::panKnob, RoutingPaneContents< RPTraits >::routingLayoutComp, RoutingPaneContents< RPTraits >::svgPaths, RoutingPaneContents< RPTraits >::velocitySensitivityLabel, and RoutingPaneContents< RPTraits >::velocitySensitivitySlider.
getRoutingName()
template<typename RPTraits > std::string getRoutingName (typename RPTraits::route_t r)
References HasGroupZoneProcessors< Group >::getProcRoutingPathDisplayName(), and HasGroupZoneProcessors< Zone >::getProcRoutingPathDisplayName().
Referenced by RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
updateProcRoutingFromInfo()
template<typename RPTraits > void updateProcRoutingFromInfo ()
References RoutingPaneContents< RPTraits >::consistentButton, RoutingPaneContents< RPTraits >::consistentLabel, RoutingPaneContents< RPTraits >::getRoutingLabel(), RoutingPaneContents< RPTraits >::getRoutingName(), RoutingPaneContents< RPTraits >::info, RoutingPaneContents< RPTraits >::multiW, RoutingPaneContents< RPTraits >::outputRouting, RoutingPaneContents< RPTraits >::routingLayoutComp, RoutingPaneContents< RPTraits >::svgPaths, and RoutingPaneContents< RPTraits >::updateFromProcessorPanes().
updateFromProcessorPanes()
template<typename RPTraits > void updateFromProcessorPanes ()
References SCXTEditor::displayError(), HasEditor::editor, RoutingPaneContents< RPTraits >::info, RoutingPaneContents< RPTraits >::jsonComponents, scxt::ui::connectors::jsonlayout::resolveJsonFile(), RoutingPaneContents< RPTraits >::routingLayoutComp, and RoutingPaneContents< RPTraits >::svgPaths.
Referenced by RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
updateRoutingLabel()
template<typename RPTraits > void updateRoutingLabel ()
References RoutingPaneContents< RPTraits >::getRoutingLabel(), RoutingPaneContents< RPTraits >::info, and RoutingPaneContents< RPTraits >::outputRouting.
Member Data Documentation
outputPane
template<typename RPTraits > RoutingPane<RPTraits>* outputPane {nullptr}
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition(), and RoutingPaneContents< RPTraits >::RoutingBox::mouseDoubleClick().
consistentButton
template<typename RPTraits > std::unique_ptr<jcmp::TextPushButton> consistentButton
Referenced by RoutingPaneContents< RPTraits >::resized(), and RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
consistentLabel
template<typename RPTraits > std::unique_ptr<jcmp::Label> consistentLabel
Referenced by RoutingPaneContents< RPTraits >::resized(), and RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
routingA
template<typename RPTraits > std::unique_ptr<int_attachment_t> routingA
Referenced by RoutingPaneContents< RPTraits >::RoutingPaneContents().
multiW
template<typename RPTraits > std::unique_ptr<jcmp::MultiSwitch> multiW
Referenced by RoutingPaneContents< RPTraits >::resized(), RoutingPaneContents< RPTraits >::RoutingPaneContents(), and RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
outputAttachment
template<typename RPTraits > std::unique_ptr<attachment_t> outputAttachment
panAttachment
template<typename RPTraits > std::unique_ptr<attachment_t> panAttachment
velocitySensitivityAttachment
template<typename RPTraits > std::unique_ptr<attachment_t> velocitySensitivityAttachment
outputRouting
template<typename RPTraits > std::unique_ptr<jcmp::MenuButton> outputRouting
Referenced by RoutingPaneContents< RPTraits >::resized(), RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo(), and RoutingPaneContents< RPTraits >::updateRoutingLabel().
outputKnob
template<typename RPTraits > std::unique_ptr<jcmp::Knob> outputKnob
Referenced by RoutingPaneContents< RPTraits >::resized().
panKnob
template<typename RPTraits > std::unique_ptr<jcmp::Knob> panKnob
Referenced by RoutingPaneContents< RPTraits >::resized().
velocitySensitivitySlider
template<typename RPTraits > std::unique_ptr<jcmp::HSliderFilled> velocitySensitivitySlider
Referenced by RoutingPaneContents< RPTraits >::resized().
velocitySensitivityLabel
template<typename RPTraits > std::unique_ptr<jcmp::Label> velocitySensitivityLabel
Referenced by RoutingPaneContents< RPTraits >::resized().
oversampleAttachment
template<typename RPTraits > std::unique_ptr<bool_attachment_t> oversampleAttachment
oversampleButton
template<typename RPTraits > std::unique_ptr<jcmp::ToggleButton> oversampleButton
Referenced by RoutingPaneContents< RPTraits >::resized().
routingLayoutComp
template<typename RPTraits > std::unique_ptr<juce::Component> routingLayoutComp
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition(), RoutingPaneContents< RPTraits >::resized(), RoutingPaneContents< RPTraits >::updateFromProcessorPanes(), and RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
nOuts
template<typename RPTraits > constexpr int nOuts {scxt::processorsPerZoneAndGroup} static constexpr
levelA
template<typename RPTraits > std::array<std::unique_ptr<ProcessorPane::attachment_t>, nOuts> levelA
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition().
jsonComponents
template<typename RPTraits > std::vector<std::unique_ptr<juce::Component> > jsonComponents
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition(), and RoutingPaneContents< RPTraits >::updateFromProcessorPanes().
svgPaths
template<typename RPTraits > std::unique_ptr<SvgPaths> svgPaths
Referenced by RoutingPaneContents< RPTraits >::resized(), RoutingPaneContents< RPTraits >::updateFromProcessorPanes(), and RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo().
info
template<typename RPTraits > RPTraits::info_t& info
Referenced by RoutingPaneContents< RPTraits >::RoutingPaneContents(), RoutingPaneContents< RPTraits >::updateFromProcessorPanes(), RoutingPaneContents< RPTraits >::updateProcRoutingFromInfo(), and RoutingPaneContents< RPTraits >::updateRoutingLabel().
The documentation for this struct was generated from the following file:
RoutingPane.cpp