shortcircuit-xt: SampleDropSource Struct Reference
SampleDropSource Struct Reference
#include <SampleDropHandler.h>
Public Types
enum class Kind {
None , MultiFile , PartFile , Instrument ,
Sample
}
Public Member Functions
bool isNone () const
bool isMultiFile () const
bool isPartFile () const
bool isInstrumentWhichCanReplace () const
bool isSingleSample () const
bool showsReplaceSplit () const
bool showsFullSidebarHighlight () const
bool isDroppableOnGroup () const
void dropOnPart (int targetPart, bool replace, HasEditor *editor) const
void dropAsZoneInCurrentGroup (HasEditor *editor) const
void dropAsZoneInGroup (int part, int group, HasEditor *editor) const
Static Public Member Functions
static SampleDropSource fromPath (const fs::path &p)
static SampleDropSource fromBrowserItem (browser_ui::WithSampleInfo *wsi)
Public Attributes
Kind kind {Kind::None}
juce::String displayName
std::string pathStr
std::optional< sample::compound::CompoundElement > element
Member Enumeration Documentation
Kind
enum class Kind strong
Enumerator
None
MultiFile
PartFile
Instrument
Sample
Member Function Documentation
isNone()
bool isNone () const
References SampleDropSource::kind, and SampleDropSource::None.
Referenced by PartSidebar::filesDropped(), ZoneLayoutDisplay::paint(), MappingDisplay::paintOverChildren(), and PartSidebar::updateDragFromSource().
isMultiFile()
bool isMultiFile () const
References SampleDropSource::kind, and SampleDropSource::MultiFile.
Referenced by MappingDisplay::filesDropped(), PartSidebar::filesDropped(), MappingDisplay::paintOverChildren(), and SampleDropSource::showsFullSidebarHighlight().
isPartFile()
bool isPartFile () const
References SampleDropSource::kind, and SampleDropSource::PartFile.
Referenced by MappingDisplay::filesDropped(), MappingDisplay::paintOverChildren(), and PartSidebar::updateDragFromSource().
isInstrumentWhichCanReplace()
bool isInstrumentWhichCanReplace () const
References SampleDropSource::Instrument, and SampleDropSource::kind.
Referenced by MappingDisplay::fileDragEnter(), MappingDisplay::fileDragMove(), MappingDisplay::itemDragEnter(), MappingDisplay::itemDragMove(), MappingDisplay::paintOverChildren(), and SampleDropSource::showsReplaceSplit().
isSingleSample()
bool isSingleSample () const
References SampleDropSource::kind, and SampleDropSource::Sample.
Referenced by PartSidebar::filesDropped(), GroupZoneSidebarBase< T, forZone >::filesDropped(), SampleDropSource::isDroppableOnGroup(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isInterestedInDragSource(), ZoneLayoutDisplay::paint(), and PartSidebar::updateDragFromSource().
showsReplaceSplit()
bool showsReplaceSplit () const
References SampleDropSource::isInstrumentWhichCanReplace().
Referenced by PartSidebar::filesDropped(), and PartSidebar::updateDragFromSource().
showsFullSidebarHighlight()
bool showsFullSidebarHighlight () const
References SampleDropSource::isMultiFile().
Referenced by PartSidebar::updateDragFromSource().
isDroppableOnGroup()
bool isDroppableOnGroup () const
References SampleDropSource::isSingleSample().
fromPath()
static SampleDropSource fromPath (const fs::path & p) static
References SampleDropSource::displayName, SampleDropSource::Instrument, Browser::isLoadableMultiSample(), Browser::isLoadableSingleSample(), SampleDropSource::kind, SampleDropSource::MultiFile, SampleDropSource::PartFile, SampleDropSource::pathStr, and SampleDropSource::Sample.
Referenced by MappingDisplay::fileDragEnter(), PartSidebar::fileDragEnter(), PartSidebar::fileDragMove(), MappingDisplay::filesDropped(), PartSidebar::filesDropped(), GroupZoneSidebarBase< T, forZone >::filesDropped(), and SampleDropSource::fromBrowserItem().
fromBrowserItem()
static SampleDropSource fromBrowserItem (browser_ui::WithSampleInfo * wsi) static
References SampleDropSource::displayName, SampleDropSource::element, WithSampleInfo::encompassesMultipleSampleInfos(), SampleDropSource::fromPath(), WithSampleInfo::getCompoundElement(), WithSampleInfo::getDirEnt(), CompoundElement::INSTRUMENT, SampleDropSource::Instrument, SampleDropSource::kind, and SampleDropSource::Sample.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isInterestedInDragSource(), MappingDisplay::itemDragEnter(), PartSidebar::itemDragEnter(), PartSidebar::itemDragMove(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDropped(), MappingDisplay::itemDropped(), and PartSidebar::itemDropped().
dropOnPart()
void dropOnPart (int targetPart, bool replace, HasEditor * editor) const
References SampleDropSource::element, Browser::getMultiInstrumentElements(), SampleDropSource::Instrument, SampleDropSource::kind, SampleDropSource::MultiFile, SampleDropSource::PartFile, SampleDropSource::pathStr, scxt::ui::app::shared::promptForMultiInstrument(), SampleDropSource::Sample, and HasEditor::sendToSerialization().
Referenced by PartSidebar::filesDropped().
dropAsZoneInCurrentGroup()
void dropAsZoneInCurrentGroup (HasEditor * editor) const
References HasEditor::sendToSerialization().
Referenced by GroupZoneSidebarBase< T, forZone >::filesDropped().
dropAsZoneInGroup()
void dropAsZoneInGroup (int part, int group, HasEditor * editor) const
References HasEditor::sendToSerialization().
Referenced by GroupZoneSidebarBase< T, forZone >::filesDropped().
Member Data Documentation
kind
Kind kind {Kind::None}
Referenced by SampleDropSource::dropOnPart(), SampleDropSource::fromBrowserItem(), SampleDropSource::fromPath(), SampleDropSource::isInstrumentWhichCanReplace(), SampleDropSource::isMultiFile(), SampleDropSource::isNone(), SampleDropSource::isPartFile(), and SampleDropSource::isSingleSample().
displayName
juce::String displayName
Referenced by SampleDropSource::fromBrowserItem(), SampleDropSource::fromPath(), MappingDisplay::paintOverChildren(), and PartSidebar::updateDragFromSource().
pathStr
std::string pathStr
Referenced by SampleDropSource::dropOnPart(), MappingDisplay::filesDropped(), and SampleDropSource::fromPath().
element
std::optional<sample::compound::CompoundElement> element
Referenced by SampleDropSource::dropOnPart(), and SampleDropSource::fromBrowserItem().
The documentation for this struct was generated from the following file:
SampleDropHandler.h