shortcircuit-xt: Zone Struct Reference
Zone Struct Reference
#include <zone.h>
Classes
struct SingleVariant
struct Variants
struct ZoneMappingData
struct ZoneOutputInfo
Public Types
enum VariantPlaybackMode : uint16_t {
FORWARD_RR , TRUE_RANDOM , RANDOM_NOREPEAT , RANDOM_CYCLE ,
UNISON
}
enum PlayMode { NORMAL , ONE_SHOT , ON_RELEASE }
enum LoopMode { LOOP_DURING_VOICE , LOOP_WHILE_GATED , LOOP_COUNT }
enum LoopDirection { FORWARD_ONLY , ALTERNATE_DIRECTIONS }
enum SampleInformationRead : int32_t {
NONE = 0 , MAPPING = 1 << 0 , LOOP = 1 << 1 , ENDPOINTS = 1 << 2 ,
ALL = MAPPING | LOOP | ENDPOINTS
}
enum ChangeDimension {
NO_CHANGE = 0 , MOVE_CTR_NO_ROOTKEY = 1 , MOVE_ROOTKEY = 1 << 1 , MOVE_CTR = MOVE_CTR_NO_ROOTKEY | MOVE_ROOTKEY ,
KEY_RANGE_START = 1 << 2 , KEY_RANGE_END = 1 << 3 , VEL_RANGE_START = 1 << 4 , VEL_RANGE_END = 1 << 5 ,
KEY_FADE_START = 1 << 6 , KEY_FADE_END = 1 << 7 , VEL_FADE_START = 1 << 8 , VEL_FADE_END = 1 << 9
}
Public Types inherited from HasGroupZoneProcessors< Zone >
enum ProcRoutingPath
Public Member Functions
Zone ()
Zone (SampleID sid)
Zone (Zone &&)=default
virtual ~Zone ()
DECLARE_ENUM_STRING (VariantPlaybackMode)
DECLARE_ENUM_STRING (PlayMode)
DECLARE_ENUM_STRING (LoopMode)
DECLARE_ENUM_STRING (LoopDirection)
auto getNumSampleLoaded () const
void deleteVariant (int idx)
void process (Engine &onto)
template<bool OS>
void processWithOS (Engine &onto)
std::string getName () const
size_t getNumOutputs () const
bool attachToSample (const sample::SampleManager &manager, int index=0, int32_t sir=ALL)
bool attachToSampleAtVariation (const sample::SampleManager &manager, const SampleID &sid, int16_t variation, int32_t sir=ALL)
void setNormalizedSampleLevel (bool usePeak=false, int associatedSampleID=-1)
void clearNormalizedSampleLevel (int associatedSampleID=-1)
int16_t missingSampleCount () const
bool isActive ()
void terminateAllVoices ()
void initialize ()
void addVoice (voice::Voice *)
void removeVoice (voice::Voice *)
void onRoutingChanged ()
void onProcessorTypeChanged (int, dsp::processor::ProcessorType)
void setupOnUnstream (const engine::Engine &e)
engine::Engine * getEngine ()
const engine::Engine * getEngine () const
bool canApplyChange (ChangeDimension dim, int deltaX, int deltaY) const
void applyChange (ChangeDimension dim, int deltaX, int deltaY)
bool canApplyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY) const
void applyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY)
void onSampleRateChanged () override
Public Member Functions inherited from MoveableOnly< Zone >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from HasGroupZoneProcessors< Zone >
DECLARE_ENUM_STRING (ProcRoutingPath)
Zone * asT ()
void setProcessorType (int whichProcessor, dsp::processor::ProcessorType type)
void setupProcessorControlDescriptions (int whichProcessor, dsp::processor::ProcessorType, dsp::processor::Processor *tmpProcessor=nullptr, bool reClampFloatValues=false)
dsp::processor::Processor * spawnTempProcessor (int whichProcessor, dsp::processor::ProcessorType type, uint8_t *mem, float *pfp, int *ifp, bool initFromDefaults)
bool checkOrAdjustIntConsistency (int whichProcessor)
bool checkOrAdjustBoolConsistency (int whichProcessor)
void updateRoutingTableAfterProcessorSwap (size_t f, size_t t)
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Static Public Member Functions
static bool canApplyChange (ChangeDimension dim, int deltaX, int deltaY, const KeyboardRange &kr, const VelocityRange &vr)
static void applyChange (ChangeDimension dim, int deltaX, int deltaY, Zone::ZoneMappingData &md)
static bool canApplyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY, const KeyboardRange &kr, const VelocityRange &vr)
static void applyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY, KeyboardRange &kr, VelocityRange &vr)
Static Public Member Functions inherited from HasGroupZoneProcessors< Zone >
static std::string getProcRoutingPathDisplayName (ProcRoutingPath p)
static std::string getProcRoutingPathShortName (ProcRoutingPath p)
Public Attributes
ZoneID id
struct scxt::engine::Zone::Variants variantData
std::array< std::shared_ptr< sample::Sample >, maxVariantsPerZone > samplePointers
int8_t sampleIndex {-1}
int numAvail {0}
int setupFor {0}
int lastPlayed {-1}
std::array< int, maxVariantsPerZone > rrs {}
struct scxt::engine::Zone::ZoneOutputInfo outputInfo
float output [2][blockSize<< 1]
std::string givenName {}
struct scxt::engine::Zone::ZoneMappingData mapping
Group * parentGroup {nullptr}
uint32_t activeVoices {0}
std::array< voice::Voice *, maxVoices > voiceWeakPointers
int gatedVoiceCount {0}
bool terminateOnNextProcess {false}
voice::modulation::Matrix::RoutingTable routingTable
std::array< modulation::ModulatorStorage, lfosPerZone > modulatorStorage
modulation::MiscSourceStorage miscSourceStorage
std::array< bool, lfosPerZone > lfosActive {}
std::array< bool, lfosPerGroup > glfosActive {}
std::array< bool, egsPerZone > egsActive {}
bool phasorsActive {}
std::array< modulation::modulators::AdsrStorage, egsPerZone > egStorage
engine::Engine * engine {nullptr}
sst::basic_blocks::dsp::UIComponentLagHandler mUILag
Public Attributes inherited from HasGroupZoneProcessors< Zone >
std::array< dsp::processor::ProcessorStorage, processorCount > processorStorage
std::array< dsp::processor::ProcessorControlDescription, processorCount > processorDescription
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Static Public Attributes
static constexpr int maxVariantsPerZone {scxt::maxVariantsPerZone}
Static Public Attributes inherited from HasGroupZoneProcessors< Zone >
static constexpr bool forGroup
static constexpr bool forZone
static constexpr int processorCount
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Zone >
MoveableOnly ()
~MoveableOnly ()=default
Member Enumeration Documentation
VariantPlaybackMode
enum VariantPlaybackMode : uint16_t
Enumerator
FORWARD_RR
TRUE_RANDOM
RANDOM_NOREPEAT
RANDOM_CYCLE
UNISON
PlayMode
enum PlayMode
Enumerator
NORMAL
ONE_SHOT
ON_RELEASE
LoopMode
enum LoopMode
Enumerator
LOOP_DURING_VOICE
LOOP_WHILE_GATED
LOOP_COUNT
LoopDirection
enum LoopDirection
Enumerator
FORWARD_ONLY
ALTERNATE_DIRECTIONS
SampleInformationRead
enum SampleInformationRead : int32_t
Enumerator
NONE
MAPPING
LOOP
ENDPOINTS
ALL
ChangeDimension
enum ChangeDimension
Enumerator
NO_CHANGE
MOVE_CTR_NO_ROOTKEY
MOVE_ROOTKEY
MOVE_CTR
KEY_RANGE_START
KEY_RANGE_END
VEL_RANGE_START
VEL_RANGE_END
KEY_FADE_START
KEY_FADE_END
VEL_FADE_START
VEL_FADE_END
Constructor & Destructor Documentation
Zone() [1/3]
Zone ()
References Zone::initialize().
Zone() [2/3]
Zone (SampleID sid)
References Zone::initialize(), Zone::variantData, and Zone::Variants::variants.
Zone() [3/3]
Zone (Zone &&) default
~Zone()
virtual ~Zone () virtual
References Zone::terminateAllVoices().
Member Function Documentation
DECLARE_ENUM_STRING() [1/4]
DECLARE_ENUM_STRING (VariantPlaybackMode)
DECLARE_ENUM_STRING() [2/4]
DECLARE_ENUM_STRING (PlayMode)
DECLARE_ENUM_STRING() [3/4]
DECLARE_ENUM_STRING (LoopMode)
DECLARE_ENUM_STRING() [4/4]
DECLARE_ENUM_STRING (LoopDirection)
getNumSampleLoaded()
auto getNumSampleLoaded () const
References Zone::variantData, and Zone::Variants::variants.
Referenced by Zone::setupOnUnstream(), and Voice::Voice().
deleteVariant()
void deleteVariant (int idx)
References Zone::maxVariantsPerZone, Zone::samplePointers, Zone::terminateOnNextProcess, Zone::variantData, and Zone::Variants::variants.
process()
void process (Engine & onto)
References Group::outputInfo, Group::GroupOutputInfo::oversample, and Zone::parentGroup.
processWithOS()
template<bool OS> void processWithOS (Engine & onto)
References scxt::engine::DEFAULT_BUS, Zone::gatedVoiceCount, Zone::getEngine(), Engine::getPatch(), Zone::mUILag, Zone::output, Zone::outputInfo, Zone::ZoneOutputInfo::routeTo, SCD, SCLOG_IF, Zone::terminateAllVoices(), Zone::terminateOnNextProcess, and Zone::voiceWeakPointers.
getName()
std::string getName () const
References Zone::givenName, Zone::samplePointers, Zone::variantData, and Zone::Variants::variants.
Referenced by Zone::attachToSample(), and Zone::setupOnUnstream().
getNumOutputs()
size_t getNumOutputs () const
attachToSample()
bool attachToSample (const sample::SampleManager & manager, int index = 0, int32_t sir = ALL)
References Zone::ENDPOINTS, Zone::getName(), SampleManager::getSample(), Zone::ZoneMappingData::keyboardRange, Zone::LOOP, Zone::MAPPING, Zone::mapping, Zone::ZoneMappingData::rootKey, Zone::samplePointers, SCLOG_IF, Zone::variantData, Zone::Variants::variants, and Zone::ZoneMappingData::velocityRange.
Referenced by Zone::attachToSampleAtVariation(), and Zone::setupOnUnstream().
attachToSampleAtVariation()
bool attachToSampleAtVariation (const sample::SampleManager & manager, const SampleID & sid, int16_t variation, int32_t sir = ALL)
References Zone::attachToSample(), Zone::variantData, and Zone::Variants::variants.
setNormalizedSampleLevel()
void setNormalizedSampleLevel (bool usePeak = false, int associatedSampleID = -1)
References scxt::dsp::sample_analytics::computeMaxRMSInBlock(), scxt::dsp::sample_analytics::computePeak(), Zone::maxVariantsPerZone, Zone::samplePointers, Zone::variantData, and Zone::Variants::variants.
clearNormalizedSampleLevel()
void clearNormalizedSampleLevel (int associatedSampleID = -1)
References Zone::maxVariantsPerZone, Zone::samplePointers, Zone::variantData, and Zone::Variants::variants.
missingSampleCount()
int16_t missingSampleCount () const
References Zone::samplePointers, Zone::variantData, and Zone::Variants::variants.
isActive()
bool isActive ()
References Zone::activeVoices.
terminateAllVoices()
void terminateAllVoices ()
References SCLOG_IF, and Zone::voiceWeakPointers.
Referenced by Zone::processWithOS(), Engine::terminateVoicesForZone(), and Zone::~Zone().
initialize()
void initialize ()
References Zone::voiceWeakPointers.
Referenced by Zone::Zone(), and Zone::Zone().
addVoice()
void addVoice (voice::Voice * v)
References Zone::activeVoices, Group::addActiveZone(), Zone::parentGroup, and Zone::voiceWeakPointers.
Referenced by Voice::voiceStarted().
removeVoice()
void removeVoice (voice::Voice * v)
References Zone::activeVoices, Zone::mUILag, Zone::parentGroup, Group::removeActiveZone(), and Zone::voiceWeakPointers.
Referenced by Voice::cleanupVoice().
onRoutingChanged()
void onRoutingChanged ()
References Zone::egsActive, MatrixEndpoints::Sources::egSources, Zone::glfosActive, MatrixEndpoints::Sources::glfoSources, Zone::lfosActive, MatrixEndpoints::Sources::lfoSources, scxt::engine::lfosPerGroup, scxt::engine::lfosPerZone, Zone::parentGroup, Zone::phasorsActive, Group::rePrepareAndBindGroupMatrix(), Zone::routingTable, and MatrixEndpoints::Sources::transportSources.
onProcessorTypeChanged()
void onProcessorTypeChanged (int idx, dsp::processor::ProcessorType)
References HasGroupZoneProcessors< Zone >::processorDescription, and Zone::routingTable.
setupOnUnstream()
void setupOnUnstream (const engine::Engine & e)
References Zone::attachToSample(), Engine::getMessageController(), Zone::getName(), Zone::getNumSampleLoaded(), Engine::getSampleManager(), Zone::NONE, HasGroupZoneProcessors< Zone >::processorCount, HasGroupZoneProcessors< Zone >::processorStorage, SCLOG_IF, HasGroupZoneProcessors< Zone >::setupProcessorControlDescriptions(), Zone::variantData, and Zone::Variants::variants.
getEngine() [1/2]
engine::Engine * getEngine ()
References Zone::engine.
Referenced by Voice::calculateVoicePitch(), scxt::voice::modulation::getVoiceMatrixMetadata(), Voice::initializeProcessors(), Voice::processWithOS(), Zone::processWithOS(), and Voice::voiceStarted().
getEngine() [2/2]
const engine::Engine * getEngine () const
References Zone::engine.
canApplyChange() [1/2]
bool canApplyChange (ChangeDimension dim, int deltaX, int deltaY, const KeyboardRange & kr, const VelocityRange & vr) static
References KeyboardRange::fadeEnd, VelocityRange::fadeEnd, KeyboardRange::fadeStart, VelocityRange::fadeStart, Zone::KEY_FADE_END, Zone::KEY_FADE_START, Zone::KEY_RANGE_END, Zone::KEY_RANGE_START, KeyboardRange::keyEnd, KeyboardRange::keyStart, Zone::MOVE_CTR, Zone::NO_CHANGE, Zone::VEL_FADE_END, Zone::VEL_FADE_START, Zone::VEL_RANGE_END, Zone::VEL_RANGE_START, VelocityRange::velEnd, and VelocityRange::velStart.
Referenced by Zone::applyChange(), Zone::canApplyChange(), and MappingDisplay::evaluateCanApplyUISide().
applyChange() [1/2]
void applyChange (ChangeDimension dim, int deltaX, int deltaY, Zone::ZoneMappingData & md) static
References Zone::canApplyChange(), Zone::KEY_FADE_END, Zone::KEY_FADE_START, Zone::KEY_RANGE_END, Zone::KEY_RANGE_START, Zone::ZoneMappingData::keyboardRange, Zone::MOVE_CTR_NO_ROOTKEY, Zone::MOVE_ROOTKEY, Zone::NO_CHANGE, Zone::ZoneMappingData::rootKey, Zone::VEL_FADE_END, Zone::VEL_FADE_START, Zone::VEL_RANGE_END, Zone::VEL_RANGE_START, Zone::ZoneMappingData::velocityRange, and VelocityRange::velStart.
Referenced by Zone::applyChange(), and MappingDisplay::applyDeltaToSelectedZones().
canApplyAbsoluteBoundEdit() [1/2]
bool canApplyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY, const KeyboardRange & kr, const VelocityRange & vr) static
References KeyboardRange::fadeEnd, VelocityRange::fadeEnd, KeyboardRange::fadeStart, VelocityRange::fadeStart, Zone::KEY_FADE_END, Zone::KEY_FADE_START, Zone::KEY_RANGE_END, Zone::KEY_RANGE_START, KeyboardRange::keyEnd, KeyboardRange::keyStart, Zone::NO_CHANGE, Zone::VEL_FADE_END, Zone::VEL_FADE_START, Zone::VEL_RANGE_END, Zone::VEL_RANGE_START, VelocityRange::velEnd, and VelocityRange::velStart.
Referenced by Zone::applyAbsoluteBoundEdit(), MappingDisplay::applyAbsoluteToSelectedZones(), and Zone::canApplyAbsoluteBoundEdit().
applyAbsoluteBoundEdit() [1/2]
void applyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY, KeyboardRange & kr, VelocityRange & vr) static
References Zone::canApplyAbsoluteBoundEdit(), KeyboardRange::fadeEnd, VelocityRange::fadeEnd, KeyboardRange::fadeStart, VelocityRange::fadeStart, Zone::KEY_FADE_END, Zone::KEY_FADE_START, Zone::KEY_RANGE_END, Zone::KEY_RANGE_START, KeyboardRange::keyEnd, KeyboardRange::keyStart, Zone::VEL_FADE_END, Zone::VEL_FADE_START, Zone::VEL_RANGE_END, Zone::VEL_RANGE_START, VelocityRange::velEnd, and VelocityRange::velStart.
Referenced by Zone::applyAbsoluteBoundEdit().
canApplyChange() [2/2]
bool canApplyChange (ChangeDimension dim, int deltaX, int deltaY) const
References Zone::canApplyChange(), Zone::ZoneMappingData::keyboardRange, Zone::mapping, and Zone::ZoneMappingData::velocityRange.
applyChange() [2/2]
void applyChange (ChangeDimension dim, int deltaX, int deltaY)
References Zone::applyChange(), and Zone::mapping.
canApplyAbsoluteBoundEdit() [2/2]
bool canApplyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY) const
References Zone::canApplyAbsoluteBoundEdit(), Zone::ZoneMappingData::keyboardRange, Zone::mapping, and Zone::ZoneMappingData::velocityRange.
applyAbsoluteBoundEdit() [2/2]
void applyAbsoluteBoundEdit (ChangeDimension dim, int deltaX, int deltaY)
References Zone::applyAbsoluteBoundEdit(), Zone::ZoneMappingData::keyboardRange, Zone::mapping, and Zone::ZoneMappingData::velocityRange.
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References Zone::mUILag, and SampleRateSupport::sampleRate.
Member Data Documentation
maxVariantsPerZone
constexpr int maxVariantsPerZone {scxt::maxVariantsPerZone} static constexpr
Referenced by Zone::clearNormalizedSampleLevel(), Zone::deleteVariant(), and Zone::setNormalizedSampleLevel().
id
ZoneID id
variantData
struct scxt::engine::Zone::Variants variantData
Referenced by Zone::attachToSample(), Zone::attachToSampleAtVariation(), Voice::calculateGeneratorRatio(), Zone::clearNormalizedSampleLevel(), Zone::deleteVariant(), Zone::getName(), Zone::getNumSampleLoaded(), Voice::initializeGenerator(), Zone::missingSampleCount(), Voice::processWithOS(), Voice::sampleIndexRange(), Zone::setNormalizedSampleLevel(), Zone::setupOnUnstream(), and Zone::Zone().
samplePointers
std::array<std::shared_ptr<sample::Sample>, maxVariantsPerZone> samplePointers
Referenced by Zone::attachToSample(), Voice::calculateGeneratorRatio(), Zone::clearNormalizedSampleLevel(), Zone::deleteVariant(), Zone::getName(), Voice::initializeGenerator(), Zone::missingSampleCount(), Voice::processWithOS(), and Zone::setNormalizedSampleLevel().
sampleIndex
int8_t sampleIndex {-1}
numAvail
int numAvail {0}
setupFor
int setupFor {0}
lastPlayed
int lastPlayed {-1}
rrs
std::array<int, maxVariantsPerZone> rrs {}
outputInfo
struct scxt::engine::Zone::ZoneOutputInfo outputInfo
Referenced by MatrixEndpoints::OutputTarget::bind(), Voice::processWithOS(), and Zone::processWithOS().
output
float output[2][blockSize<< 1]
Referenced by Zone::processWithOS().
givenName
std::string givenName {}
Referenced by Zone::getName().
mapping
struct scxt::engine::Zone::ZoneMappingData mapping
Referenced by Zone::applyAbsoluteBoundEdit(), Zone::applyChange(), Zone::attachToSample(), MatrixEndpoints::MappingTarget::bind(), MatrixEndpoints::SampleTarget::bind(), Voice::calculateGeneratorRatio(), Voice::calculateVoicePitch(), Zone::canApplyAbsoluteBoundEdit(), and Zone::canApplyChange().
parentGroup
Group* parentGroup {nullptr}
Referenced by Zone::addVoice(), MatrixEndpoints::Sources::bind(), Voice::calculateGeneratorRatio(), Voice::calculateVoicePitch(), Voice::initiateGlide(), Zone::onRoutingChanged(), Zone::process(), Voice::processWithOS(), Group::processWithOS(), Zone::removeVoice(), Engine::VoiceManagerResponder::setVoiceMIDIMPEChannelPitchBend(), Engine::VoiceManagerResponder::setVoiceMIDIMPEChannelPressure(), Engine::VoiceManagerResponder::setVoiceMIDIMPETimbre(), Voice::updateGlide(), and Voice::voiceStarted().
activeVoices
uint32_t activeVoices {0}
Referenced by Zone::addVoice(), Zone::isActive(), and Zone::removeVoice().
voiceWeakPointers
std::array<voice::Voice *, maxVoices> voiceWeakPointers
Referenced by Zone::addVoice(), Zone::initialize(), Zone::processWithOS(), Zone::removeVoice(), and Zone::terminateAllVoices().
gatedVoiceCount
int gatedVoiceCount {0}
Referenced by Zone::processWithOS().
terminateOnNextProcess
bool terminateOnNextProcess {false}
Referenced by Zone::deleteVariant(), and Zone::processWithOS().
routingTable
voice::modulation::Matrix::RoutingTable routingTable
Referenced by Zone::onProcessorTypeChanged(), Zone::onRoutingChanged(), and Voice::voiceStarted().
modulatorStorage
std::array<modulation::ModulatorStorage, lfosPerZone> modulatorStorage
Referenced by Voice::processWithOS(), and Voice::voiceStarted().
miscSourceStorage
modulation::MiscSourceStorage miscSourceStorage
Referenced by Voice::processWithOS(), and Voice::voiceStarted().
lfosActive
std::array<bool, lfosPerZone> lfosActive {}
Referenced by Zone::onRoutingChanged(), and Voice::voiceStarted().
glfosActive
std::array<bool, lfosPerGroup> glfosActive {}
Referenced by Zone::onRoutingChanged().
egsActive
std::array<bool, egsPerZone> egsActive {}
Referenced by Zone::onRoutingChanged(), and Voice::voiceStarted().
phasorsActive
bool phasorsActive {}
Referenced by Zone::onRoutingChanged(), and Voice::voiceStarted().
egStorage
std::array<modulation::modulators::AdsrStorage, egsPerZone> egStorage
Referenced by MatrixEndpoints::EGTarget::bind(), and Voice::processWithOS().
engine
engine::Engine* engine {nullptr}
Referenced by Zone::getEngine(), and Zone::getEngine().
mUILag
sst::basic_blocks::dsp::UIComponentLagHandler mUILag
Referenced by Zone::onSampleRateChanged(), Zone::processWithOS(), and Zone::removeVoice().
The documentation for this struct was generated from the following files:
zone.h
zone.cpp