shortcircuit-xt: scxt_traits< scxt::engine::Group > Struct Reference
scxt_traits< scxt::engine::Group > Struct Reference
Static Public Member Functions
template<template< typename... > class Traits>
static void assign (tao::json::basic_value< Traits > &v, const scxt::engine::Group &t)
template<template< typename... > class Traits>
static void to (const tao::json::basic_value< Traits > &v, scxt::engine::Group &group)
Member Function Documentation
assign()
static void assign (tao::json::basic_value< Traits > & v, const scxt::engine::Group & t) static
References Group::gegStorage, Group::getName(), Group::getZones(), Group::modulatorStorage, Group::outputInfo, HasGroupZoneProcessors< T >::processorStorage, and Group::routingTable.
to()
static void to (const tao::json::basic_value< Traits > & v, scxt::engine::Group & group) static
References Group::addZone(), Group::clearZones(), scxt::json::findIf(), findIfArray(), Group::gegStorage, Group::getZone(), Group::modulatorStorage, Group::name, Group::outputInfo, Patch::parentEngine, Group::parentPart, Part::parentPatch, HasGroupZoneProcessors< T >::processorStorage, Group::routingTable, and Group::setupOnUnstream().
The documentation for this struct was generated from the following file:
engine_traits.h