shortcircuit-xt: PhasorEvaluator Struct Reference
PhasorEvaluator Struct Reference
#include <phasor_evaluator.h>
Public Member Functions
void attack (sst::basic_blocks::modulators::Transport &transport, modulation::MiscSourceStorage &rs, sst::basic_blocks::dsp::RNG &rng)
void step (sst::basic_blocks::modulators::Transport &transport, modulation::MiscSourceStorage &rs)
Public Attributes
std::array< float, scxt::phasorsPerGroupOrZone > outputs
double lastAttackTime {0}
std::array< float, scxt::phasorsPerGroupOrZone > rphase
Member Function Documentation
attack()
void attack (sst::basic_blocks::modulators::Transport & transport, modulation::MiscSourceStorage & rs, sst::basic_blocks::dsp::RNG & rng)
References PhasorEvaluator::lastAttackTime, and PhasorEvaluator::rphase.
Referenced by Group::resetLFOs(), and Voice::voiceStarted().
step()
void step (sst::basic_blocks::modulators::Transport & transport, modulation::MiscSourceStorage & rs)
References PhasorStorage::ASCENDING, PhasorStorage::DESCENDING, PhasorStorage::DOTTED, PhasorEvaluator::lastAttackTime, PhasorStorage::NOTE, PhasorEvaluator::outputs, MiscSourceStorage::phasors, PhasorEvaluator::rphase, PhasorStorage::TRIPLET, PhasorStorage::VOICEPOS, and PhasorStorage::X_BPM.
Referenced by Voice::processWithOS(), and Group::processWithOS().
Member Data Documentation
outputs
std::array<float, scxt::phasorsPerGroupOrZone> outputs
Referenced by GroupMatrixEndpoints::Sources::bind(), MatrixEndpoints::Sources::bind(), and PhasorEvaluator::step().
lastAttackTime
double lastAttackTime {0}
Referenced by PhasorEvaluator::attack(), and PhasorEvaluator::step().
rphase
std::array<float, scxt::phasorsPerGroupOrZone> rphase
Referenced by PhasorEvaluator::attack(), and PhasorEvaluator::step().
The documentation for this struct was generated from the following file:
phasor_evaluator.h