shortcircuit-xt: Config Struct Reference
Config Struct Reference
Public Types
using BaseClass = BusEffect
using GlobalStorage = Engine
using EffectStorage = BusEffectStorage
using ValueStorage = float
using BiquadAdapter = EngineBiquadAdapter
Static Public Member Functions
static float floatValueAt (const BaseClass *const e, const ValueStorage *const v, int idx)
static int intValueAt (const BaseClass *const e, const ValueStorage *const v, int idx)
static float envelopeRateLinear (GlobalStorage *s, float f)
static float temposyncRatio (GlobalStorage *s, EffectStorage *e, int idx)
static bool isDeactivated (EffectStorage *e, int idx)
static bool isExtended (EffectStorage *e, int idx)
static float rand01 (GlobalStorage *s)
static double sampleRate (GlobalStorage *s)
static float noteToPitch (GlobalStorage *s, float p)
static float noteToPitchIgnoringTuning (GlobalStorage *s, float p)
static float noteToPitchInv (GlobalStorage *s, float p)
static float dbToLinear (GlobalStorage *s, float f)
Static Public Attributes
static constexpr int blockSize {scxt::blockSize}
static constexpr bool widthIsLinear {true}
Member Typedef Documentation
BaseClass
using BaseClass = BusEffect
GlobalStorage
using GlobalStorage = Engine
EffectStorage
using EffectStorage = BusEffectStorage
ValueStorage
using ValueStorage = float
BiquadAdapter
using BiquadAdapter = EngineBiquadAdapter
Member Function Documentation
floatValueAt()
static float floatValueAt (const BaseClass *const e, const ValueStorage *const v, int idx) static
intValueAt()
static int intValueAt (const BaseClass *const e, const ValueStorage *const v, int idx) static
envelopeRateLinear()
static float envelopeRateLinear (GlobalStorage * s, float f) static
References Config::blockSize, SampleRateSupport::getSampleRateInv(), and scxt::dsp::twoToTheXTable.
temposyncRatio()
static float temposyncRatio (GlobalStorage * s, EffectStorage * e, int idx) static
References BusEffectStorage::isTemposync, and Engine::transport.
isDeactivated()
static bool isDeactivated (EffectStorage * e, int idx) static
References BusEffectStorage::isExtended().
isExtended()
static bool isExtended (EffectStorage * e, int idx) static
References BusEffectStorage::isExtended().
rand01()
static float rand01 (GlobalStorage * s) static
References Engine::rng.
sampleRate()
static double sampleRate (GlobalStorage * s) static
References SampleRateSupport::getSampleRate().
noteToPitch()
static float noteToPitch (GlobalStorage * s, float p) static
References Config::noteToPitchIgnoringTuning().
noteToPitchIgnoringTuning()
static float noteToPitchIgnoringTuning (GlobalStorage * s, float p) static
References scxt::tuning::equalTuning.
Referenced by Config::noteToPitch().
noteToPitchInv()
static float noteToPitchInv (GlobalStorage * s, float p) static
References scxt::tuning::equalTuning.
dbToLinear()
static float dbToLinear (GlobalStorage * s, float f) static
References scxt::dsp::dbTable.
Member Data Documentation
blockSize
constexpr int blockSize {scxt::blockSize} static constexpr
Referenced by Config::envelopeRateLinear().
widthIsLinear
constexpr bool widthIsLinear {true} static constexpr
The documentation for this struct was generated from the following file:
bus.cpp