shortcircuit-xt: EnvLFO Struct Reference
EnvLFO Struct Reference
#include <envlfo.h>
Public Types
using env_t = sst::basic_blocks::modulators::AHDSRShapedSC< EnvLFO, blockSize, sst::basic_blocks::modulators::TwentyFiveSecondExp >
Public Member Functions
float envelope_rate_linear_nowrap (float f)
void attack (float delay, float attack)
void attackFrom (float level, float delay, float attack)
void process (float delay, float attack, float hold, float decay, float sustain, float release, float aShape, float dShape, float rShape, float rateMul, bool isGated)
float timeTakenBy (float stage)
float timeTakenBy (float delay, float attack, float hold, float decay, float release)
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
virtual void onSampleRateChanged ()
Public Attributes
env_t envelope {this}
float output {0.f}
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Member Typedef Documentation
env_t
using env_t = sst::basic_blocks::modulators::AHDSRShapedSC< EnvLFO, blockSize, sst::basic_blocks::modulators::TwentyFiveSecondExp>
Member Function Documentation
envelope_rate_linear_nowrap()
float envelope_rate_linear_nowrap (float f)
References SampleRateSupport::sampleRateInv, and scxt::dsp::twoToTheXTable.
attack()
void attack (float delay, float attack)
References EnvLFO::attack(), and EnvLFO::envelope.
Referenced by EnvLFO::attack(), EnvLFO::attackFrom(), EnvLFO::process(), ENVLFOPane::ENVPlotData::recalculateCurvePath(), and EnvLFO::timeTakenBy().
attackFrom()
void attackFrom (float level, float delay, float attack)
References EnvLFO::attack(), and EnvLFO::envelope.
process()
void process (float delay, float attack, float hold, float decay, float sustain, float release, float aShape, float dShape, float rShape, float rateMul, bool isGated)
References EnvLFO::attack(), EnvLFO::envelope, EnvLFO::output, and scxt::dsp::twoToTheXTable.
Referenced by ENVLFOPane::ENVPlotData::recalculateCurvePath().
timeTakenBy() [1/2]
float timeTakenBy (float stage)
References EnvLFO::envelope.
Referenced by ENVLFOPane::ENVPlotData::recalculateCurvePath(), and EnvLFO::timeTakenBy().
timeTakenBy() [2/2]
float timeTakenBy (float delay, float attack, float hold, float decay, float release)
References EnvLFO::attack(), and EnvLFO::timeTakenBy().
Member Data Documentation
envelope
env_t envelope {this}
Referenced by EnvLFO::attack(), EnvLFO::attackFrom(), EnvLFO::process(), and EnvLFO::timeTakenBy().
output
float output {0.f}
Referenced by EnvLFO::process(), and ENVLFOPane::ENVPlotData::recalculateCurvePath().
The documentation for this struct was generated from the following file:
envlfo.h