shortcircuit-xt: GroupTriggersCard Struct Reference
GroupTriggersCard Struct Reference
#include <GroupTriggersCard.h>
Classes
struct ConditionRow
Public Member Functions
GroupTriggersCard (SCXTEditor *e)
~GroupTriggersCard ()
void paint (juce::Graphics &g) override
void resized () override
void setGroupTriggerConditions (const scxt::engine::GroupTriggerConditions &)
void pushUpdate ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::array< std::unique_ptr< ConditionRow >, scxt::triggerConditionsPerGroup > rows
scxt::engine::GroupTriggerConditions cond
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
GroupTriggersCard()
GroupTriggersCard (SCXTEditor * e)
References GroupTriggersCard::rows.
~GroupTriggersCard()
~GroupTriggersCard () default
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References HasEditor::editor, ColorMap::generic_content_low, ThemeApplier::interMediumFor(), SCXTEditor::themeApplier, and SCXTEditor::themeColor().
resized()
void resized () override
References GroupTriggersCard::rows.
setGroupTriggerConditions()
void setGroupTriggerConditions (const scxt::engine::GroupTriggerConditions & c)
References GroupTriggersCard::cond, and GroupTriggersCard::rows.
pushUpdate()
void pushUpdate ()
References GroupTriggersCard::cond, and HasEditor::sendToSerialization().
Referenced by GroupTriggersCard::ConditionRow::ConditionRow(), and GroupTriggersCard::ConditionRow::setupValuesFromData().
Member Data Documentation
rows
std::array<std::unique_ptr<ConditionRow>, scxt::triggerConditionsPerGroup> rows
Referenced by GroupTriggersCard::GroupTriggersCard(), GroupTriggersCard::resized(), and GroupTriggersCard::setGroupTriggerConditions().
cond
scxt::engine::GroupTriggerConditions cond
Referenced by GroupTriggersCard::ConditionRow::ConditionRow(), GroupTriggersCard::pushUpdate(), GroupTriggersCard::setGroupTriggerConditions(), and GroupTriggersCard::ConditionRow::setupValuesFromData().
The documentation for this struct was generated from the following files:
GroupTriggersCard.h
GroupTriggersCard.cpp