shortcircuit-xt: MatrixEndpoints Struct Reference
MatrixEndpoints Struct Reference
#include <voice_matrix.h>
Classes
struct EGTarget
struct LFOTarget
struct MappingTarget
struct OutputTarget
struct ProcessorTarget
struct SampleTarget
struct SelfModulationTarget
struct Sources
Public Types
using TG = MatrixConfig::TargetIdentifier
using SR = MatrixConfig::SourceIdentifier
Public Member Functions
MatrixEndpoints (engine::Engine *e)
void bindTargetBaseValues (Matrix &m, engine::Zone &z)
Static Public Member Functions
static void registerVoiceModSource (engine::Engine *e, const MatrixConfig::SourceIdentifier &t, const std::string &path, const std::string &name)
static void registerVoiceModTarget (engine::Engine *e, const MatrixConfig::TargetIdentifier &t, const std::string &path, const std::string &name, bool supportsMultiplicative=false)
static void registerVoiceModTarget (engine::Engine *e, const MatrixConfig::TargetIdentifier &t, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> nameFn, bool supportsMultiplicative=false)
static void registerVoiceModTarget (engine::Engine *e, const MatrixConfig::TargetIdentifier &, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> nameFn, std::function< int32_t(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> additiveFn, std::function< bool(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> enabledFn=[](const engine::Zone &, const MatrixConfig::TargetIdentifier &) { return true;})
static void registerVoiceModSource (engine::Engine *e, const MatrixConfig::SourceIdentifier &, std::function< std::string(const engine::Zone &, const MatrixConfig::SourceIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::SourceIdentifier &)> nameFn)
Public Attributes
std::array< LFOTarget, scxt::lfosPerZone > lfo
std::array< EGTarget, scxt::egsPerZone > egTarget
struct scxt::voice::modulation::MatrixEndpoints::MappingTarget mappingTarget
struct scxt::voice::modulation::MatrixEndpoints::OutputTarget outputTarget
std::array< ProcessorTarget, scxt::processorsPerZoneAndGroup > processorTarget
struct scxt::voice::modulation::MatrixEndpoints::SelfModulationTarget selfModulation
struct scxt::voice::modulation::MatrixEndpoints::SampleTarget sampleTarget
struct scxt::voice::modulation::MatrixEndpoints::Sources sources
Member Typedef Documentation
TG
using TG = MatrixConfig::TargetIdentifier
SR
using SR = MatrixConfig::SourceIdentifier
Constructor & Destructor Documentation
MatrixEndpoints()
MatrixEndpoints (engine::Engine * e)
Member Function Documentation
registerVoiceModSource() [1/2]
static void registerVoiceModSource (engine::Engine * e, const MatrixConfig::SourceIdentifier & t, const std::string & path, const std::string & name) static
References MatrixEndpoints::registerVoiceModSource().
Referenced by MatrixEndpoints::Sources::MacroSources::MacroSources(), and MatrixEndpoints::registerVoiceModSource().
bindTargetBaseValues()
void bindTargetBaseValues (Matrix & m, engine::Zone & z)
References MatrixEndpoints::MappingTarget::bind(), MatrixEndpoints::OutputTarget::bind(), MatrixEndpoints::SampleTarget::bind(), MatrixEndpoints::egTarget, MatrixEndpoints::lfo, MatrixEndpoints::mappingTarget, MatrixEndpoints::outputTarget, MatrixEndpoints::processorTarget, and MatrixEndpoints::sampleTarget.
Referenced by SelectionManager::configureAndSendZoneOrGroupModMatrixMetadata().
registerVoiceModTarget() [1/3]
static void registerVoiceModTarget (engine::Engine * e, const MatrixConfig::TargetIdentifier & t, const std::string & path, const std::string & name, bool supportsMultiplicative = false) static
Referenced by MatrixEndpoints::EGTarget::EGTarget(), MatrixEndpoints::LFOTarget::LFOTarget(), MatrixEndpoints::MappingTarget::MappingTarget(), MatrixEndpoints::OutputTarget::OutputTarget(), MatrixEndpoints::ProcessorTarget::ProcessorTarget(), MatrixEndpoints::SampleTarget::SampleTarget(), and MatrixEndpoints::SelfModulationTarget::SelfModulationTarget().
registerVoiceModTarget() [2/3]
static void registerVoiceModTarget (engine::Engine * e, const MatrixConfig::TargetIdentifier & t, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> nameFn, bool supportsMultiplicative = false) static
registerVoiceModTarget() [3/3]
void registerVoiceModTarget (engine::Engine * e, const MatrixConfig::TargetIdentifier & t, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> nameFn, std::function< int32_t(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> additiveFn, std::function< bool(const engine::Zone &, const MatrixConfig::TargetIdentifier &)> enabledFn = [](const engine::Zone &, const MatrixConfig::TargetIdentifier &) { return true; }) static
References Engine::registerVoiceModTarget().
registerVoiceModSource() [2/2]
void registerVoiceModSource (engine::Engine * e, const MatrixConfig::SourceIdentifier & t, std::function< std::string(const engine::Zone &, const MatrixConfig::SourceIdentifier &)> pathFn, std::function< std::string(const engine::Zone &, const MatrixConfig::SourceIdentifier &)> nameFn) static
References Engine::registerVoiceModSource().
Member Data Documentation
lfo
std::array<LFOTarget, scxt::lfosPerZone> lfo
Referenced by MatrixEndpoints::bindTargetBaseValues().
egTarget
std::array<EGTarget, scxt::egsPerZone> egTarget
Referenced by MatrixEndpoints::bindTargetBaseValues().
mappingTarget
struct scxt::voice::modulation::MatrixEndpoints::MappingTarget mappingTarget
Referenced by MatrixEndpoints::bindTargetBaseValues().
outputTarget
struct scxt::voice::modulation::MatrixEndpoints::OutputTarget outputTarget
Referenced by MatrixEndpoints::bindTargetBaseValues().
processorTarget
std::array<ProcessorTarget, scxt::processorsPerZoneAndGroup> processorTarget
Referenced by MatrixEndpoints::bindTargetBaseValues().
selfModulation
struct scxt::voice::modulation::MatrixEndpoints::SelfModulationTarget selfModulation
sampleTarget
struct scxt::voice::modulation::MatrixEndpoints::SampleTarget sampleTarget
Referenced by MatrixEndpoints::bindTargetBaseValues().
sources
struct scxt::voice::modulation::MatrixEndpoints::Sources sources
The documentation for this struct was generated from the following files:
voice_matrix.h
voice_matrix.cpp