shortcircuit-xt: EXSObject Struct Reference
EXSObject Struct Reference
Public Member Functions
EXSObject (EXSBlock in)
void resetPosition ()
void skip (int S)
int32_t readByteToInt ()
uint8_t readByte ()
uint16_t readU16 ()
uint32_t readU32 ()
std::string readStringNoTerm (size_t chars)
std::string readStringNullTerm (size_t chars)
Public Attributes
EXSBlock within
size_t position {0}
Constructor & Destructor Documentation
EXSObject()
EXSObject (EXSBlock in)
Member Function Documentation
resetPosition()
void resetPosition ()
References EXSObject::position.
Referenced by EXSZone::parse(), EXSGroup::parse(), and EXSSample::parse().
skip()
void skip (int S)
References EXSObject::position, EXSBlock::size, and EXSObject::within.
Referenced by EXSZone::parse(), EXSGroup::parse(), and EXSSample::parse().
readByteToInt()
int32_t readByteToInt ()
References EXSBlock::content, EXSObject::position, EXSBlock::size, and EXSObject::within.
Referenced by EXSZone::parse(), and EXSGroup::parse().
readByte()
uint8_t readByte ()
References EXSBlock::content, EXSObject::position, EXSBlock::size, and EXSObject::within.
Referenced by EXSZone::parse().
readU16()
uint16_t readU16 ()
References EXSBlock::content, EXSBlock::isBigEndian, EXSObject::position, EXSBlock::size, and EXSObject::within.
Referenced by EXSGroup::parse().
readU32()
uint32_t readU32 ()
References EXSBlock::content, EXSBlock::isBigEndian, EXSObject::position, EXSBlock::size, and EXSObject::within.
Referenced by EXSZone::parse(), EXSGroup::parse(), and EXSSample::parse().
readStringNoTerm()
std::string readStringNoTerm (size_t chars)
References EXSBlock::content, EXSObject::position, and EXSObject::within.
Referenced by EXSSample::parse().
readStringNullTerm()
std::string readStringNullTerm (size_t chars)
References EXSBlock::content, EXSObject::position, and EXSObject::within.
Referenced by EXSSample::parse().
Member Data Documentation
within
EXSBlock within
Referenced by EXSGroup::EXSGroup(), EXSZone::EXSZone(), EXSGroup::parse(), EXSSample::parse(), EXSObject::readByte(), EXSObject::readByteToInt(), EXSObject::readStringNoTerm(), EXSObject::readStringNullTerm(), EXSObject::readU16(), EXSObject::readU32(), and EXSObject::skip().
position
size_t position {0}
Referenced by EXSGroup::parse(), EXSSample::parse(), EXSObject::readByte(), EXSObject::readByteToInt(), EXSObject::readStringNoTerm(), EXSObject::readStringNullTerm(), EXSObject::readU16(), EXSObject::readU32(), EXSObject::resetPosition(), and EXSObject::skip().
The documentation for this struct was generated from the following file:
exs_import.cpp