shortcircuit-xt: ZoneLayoutDisplay Struct Reference
ZoneLayoutDisplay Struct Reference
Public Types
enum MouseState {
NONE , DRAG_VELOCITY , DRAG_KEY , DRAG_KEY_AND_VEL ,
DRAG_SELECTED_ZONE , MULTI_SELECT , CREATE_EMPTY_ZONE
}
enum DragFrom { FROM_START , FROM_END }
Public Member Functions
ZoneLayoutDisplay (MappingDisplay *d)
void paint (juce::Graphics &g) override
void resized () override
std::array< int16_t, 3 > rootAndRangeForPosition (const juce::Point< int > &)
juce::Rectangle< float > rectangleForZone (const engine::Part::zoneMappingItem_t &sum)
juce::Rectangle< float > rectangleForRange (int kL, int kH, int vL, int vH)
juce::Rectangle< float > rectangleForRangeSkipEnd (int kL, int kH, int vL, int vH)
void labelZoneRectangle (juce::Graphics &g, const juce::Rectangle< float > &, const std::string &, const juce::Colour &)
void mouseDown (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseMove (const juce::MouseEvent &e) override
void mouseDoubleClick (const juce::MouseEvent &e) override
void resetLeadZoneBounds ()
void setLeadZoneBounds (const engine::Part::zoneMappingItem_t &az)
void showZoneMenu (const selection::SelectionManager::ZoneAddress &za)
void setHorizontalZoom (float pctStart, float zoomFactor)
void setVerticalZoom (float pctStart, float zoomFactor)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
Public Attributes
MappingDisplay * display {nullptr}
std::optional< engine::Part::zoneMappingItem_t > cacheLastZone
enum scxt::ui::app::edit_screen::ZoneLayoutDisplay::MouseState NONE
enum scxt::ui::app::edit_screen::ZoneLayoutDisplay::DragFrom dragFrom [2]
std::vector< juce::Rectangle< float > > velocityHotZones
std::vector< juce::Rectangle< float > > keyboardHotZones
std::vector< juce::Rectangle< float > > bothHotZones
std::vector< juce::Rectangle< float > > lastSelectedZone
juce::Point< float > firstMousePos {0.f, 0.f}
juce::Point< float > lastMousePos {0.f, 0.f}
float hPct {0.0}
float hZoom {1.0}
float vPct {0.0}
float vZoom {1.0}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Member Enumeration Documentation
MouseState
enum MouseState
Enumerator
NONE
DRAG_VELOCITY
DRAG_KEY
DRAG_KEY_AND_VEL
DRAG_SELECTED_ZONE
MULTI_SELECT
CREATE_EMPTY_ZONE
DragFrom
enum DragFrom
Enumerator
FROM_START
FROM_END
Constructor & Destructor Documentation
ZoneLayoutDisplay()
ZoneLayoutDisplay (MappingDisplay * d)
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_1b, ColorMap::accent_2a, ColorMap::accent_2b, ZoneLayoutDisplay::CREATE_EMPTY_ZONE, MappingDisplay::currentDragPoint, SCXTEditor::currentLeadZoneSelection, ZoneLayoutDisplay::display, HasEditor::editor, ZoneLayoutDisplay::firstMousePos, ColorMap::generic_content_high, ColorMap::generic_content_highest, ColorMap::generic_content_low, ZoneLayoutDisplay::hPct, ZoneLayoutDisplay::hZoom, SCXTEditor::isAnyZoneFromGroupSelected(), SCXTEditor::isSelected(), MappingDisplay::isUndertakingDrop, ZoneLayoutDisplay::labelZoneRectangle(), ZoneLayoutDisplay::lastMousePos, ZoneLayoutDisplay::MULTI_SELECT, ZoneLayoutDisplay::rectangleForRange(), ZoneLayoutDisplay::rectangleForRangeSkipEnd(), ZoneLayoutDisplay::rectangleForZone(), ZoneLayoutDisplay::rootAndRangeForPosition(), MappingDisplay::summary, SCXTEditor::themeColor(), MappingDisplay::voiceCountFor(), ZoneLayoutDisplay::vPct, and ZoneLayoutDisplay::vZoom.
resized()
void resized () override
rootAndRangeForPosition()
std::array< int16_t, 3 > rootAndRangeForPosition (const juce::Point< int > & p)
References ZoneLayoutKeyboard::firstMidiNote, and ZoneLayoutKeyboard::lastMidiNote.
Referenced by MappingDisplay::filesDropped(), MappingDisplay::itemDropped(), and ZoneLayoutDisplay::paint().
rectangleForZone()
juce::Rectangle< float > rectangleForZone (const engine::Part::zoneMappingItem_t & sum)
References ZoneLayoutDisplay::rectangleForRange().
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseUp(), ZoneLayoutDisplay::paint(), and ZoneLayoutDisplay::setLeadZoneBounds().
rectangleForRange()
juce::Rectangle< float > rectangleForRange (int kL, int kH, int vL, int vH)
References ZoneLayoutDisplay::rectangleForRangeSkipEnd().
Referenced by ZoneLayoutDisplay::paint(), and ZoneLayoutDisplay::rectangleForZone().
rectangleForRangeSkipEnd()
juce::Rectangle< float > rectangleForRangeSkipEnd (int kL, int kH, int vL, int vH)
References ZoneLayoutKeyboard::firstMidiNote, ZoneLayoutDisplay::hPct, ZoneLayoutDisplay::hZoom, ZoneLayoutKeyboard::lastMidiNote, ZoneLayoutDisplay::vPct, and ZoneLayoutDisplay::vZoom.
Referenced by ZoneLayoutDisplay::paint(), and ZoneLayoutDisplay::rectangleForRange().
labelZoneRectangle()
void labelZoneRectangle (juce::Graphics & g, const juce::Rectangle< float > & rIn, const std::string & txt, const juce::Colour & col)
References ColorMap::bg_2, HasEditor::editor, ThemeApplier::interRegularFor(), SCXTEditor::themeApplier, SCXTEditor::themeColor(), and scxt::ui::app::other_screens::txt.
Referenced by ZoneLayoutDisplay::paint().
mouseDown()
void mouseDown (const juce::MouseEvent & e) override
References ZoneLayoutDisplay::bothHotZones, ZoneLayoutDisplay::CREATE_EMPTY_ZONE, SCXTEditor::currentLeadZoneSelection, ZoneLayoutDisplay::display, SCXTEditor::doSelectionAction(), ZoneLayoutDisplay::DRAG_KEY, ZoneLayoutDisplay::DRAG_KEY_AND_VEL, ZoneLayoutDisplay::DRAG_SELECTED_ZONE, ZoneLayoutDisplay::DRAG_VELOCITY, ZoneLayoutDisplay::dragFrom, HasEditor::editor, ZoneLayoutDisplay::firstMousePos, ZoneLayoutDisplay::FROM_END, ZoneLayoutDisplay::FROM_START, SCXTEditor::isAnyZoneFromGroupSelected(), SCXTEditor::isSelected(), ZoneLayoutDisplay::keyboardHotZones, ZoneLayoutDisplay::lastMousePos, ZoneLayoutDisplay::lastSelectedZone, ZoneLayoutDisplay::MULTI_SELECT, ZoneLayoutDisplay::NONE, ZoneLayoutDisplay::rectangleForZone(), ZoneLayoutDisplay::showZoneMenu(), MappingDisplay::summary, and ZoneLayoutDisplay::velocityHotZones.
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
References ZoneLayoutDisplay::CREATE_EMPTY_ZONE, SCXTEditor::currentLeadZoneSelection, ZoneLayoutDisplay::display, SCXTEditor::doSelectionAction(), HasEditor::editor, ZoneLayoutKeyboard::firstMidiNote, ZoneLayoutDisplay::firstMousePos, ZoneLayoutKeyboard::lastMidiNote, ZoneLayoutDisplay::MULTI_SELECT, ZoneLayoutDisplay::NONE, ZoneLayoutDisplay::rectangleForZone(), HasEditor::sendToSerialization(), and MappingDisplay::summary.
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
References scxt::ui::app::edit_screen::constrainMappingFade(), ZoneLayoutDisplay::CREATE_EMPTY_ZONE, ZoneLayoutDisplay::display, ZoneLayoutDisplay::DRAG_KEY, ZoneLayoutDisplay::DRAG_KEY_AND_VEL, ZoneLayoutDisplay::DRAG_SELECTED_ZONE, ZoneLayoutDisplay::DRAG_VELOCITY, ZoneLayoutDisplay::dragFrom, ZoneLayoutKeyboard::firstMidiNote, ZoneLayoutDisplay::FROM_START, ZoneLayoutDisplay::hPct, ZoneLayoutDisplay::hZoom, Zone::ZoneMappingData::keyboardRange, KeyboardRange::keyEnd, ZoneLayoutKeyboard::lastMidiNote, ZoneLayoutDisplay::lastMousePos, MappingDisplay::mappingChangedFromGUI(), MappingDisplay::mappingView, ZoneLayoutDisplay::MULTI_SELECT, Zone::ZoneMappingData::rootKey, Zone::ZoneMappingData::velocityRange, VelocityRange::velStart, ZoneLayoutDisplay::vPct, and ZoneLayoutDisplay::vZoom.
mouseMove()
void mouseMove (const juce::MouseEvent & e) override
References ZoneLayoutDisplay::bothHotZones, ZoneLayoutDisplay::keyboardHotZones, and ZoneLayoutDisplay::velocityHotZones.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & e) override
References ZoneLayoutDisplay::display, ZoneLayoutDisplay::lastSelectedZone, and MappingDisplay::parentPane.
resetLeadZoneBounds()
void resetLeadZoneBounds ()
References ZoneLayoutDisplay::cacheLastZone, and ZoneLayoutDisplay::setLeadZoneBounds().
Referenced by ZoneLayoutDisplay::setHorizontalZoom(), and ZoneLayoutDisplay::setVerticalZoom().
setLeadZoneBounds()
void setLeadZoneBounds (const engine::Part::zoneMappingItem_t & az)
References ZoneLayoutDisplay::bothHotZones, ZoneLayoutDisplay::cacheLastZone, ZoneLayoutDisplay::keyboardHotZones, ZoneLayoutDisplay::lastSelectedZone, ZoneLayoutDisplay::rectangleForZone(), and ZoneLayoutDisplay::velocityHotZones.
Referenced by ZoneLayoutDisplay::resetLeadZoneBounds(), and MappingDisplay::setLeadSelection().
showZoneMenu()
void showZoneMenu (const selection::SelectionManager::ZoneAddress & za)
References SCXTEditor::defaultPopupMenuOptions(), and HasEditor::editor.
Referenced by ZoneLayoutDisplay::mouseDown().
setHorizontalZoom()
void setHorizontalZoom (float pctStart, float zoomFactor)
References ZoneLayoutDisplay::hPct, ZoneLayoutDisplay::hZoom, and ZoneLayoutDisplay::resetLeadZoneBounds().
Referenced by MappingDisplay::LayoutAndKeyboard::setHorizontalZoom().
setVerticalZoom()
void setVerticalZoom (float pctStart, float zoomFactor)
References ZoneLayoutDisplay::resetLeadZoneBounds(), ZoneLayoutDisplay::vPct, and ZoneLayoutDisplay::vZoom.
Referenced by MappingDisplay::LayoutAndKeyboard::setVerticalZoom().
Member Data Documentation
display
MappingDisplay* display {nullptr}
Referenced by ZoneLayoutDisplay::mouseDoubleClick(), ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseDrag(), ZoneLayoutDisplay::mouseUp(), and ZoneLayoutDisplay::paint().
cacheLastZone
std::optional<engine::Part::zoneMappingItem_t> cacheLastZone
Referenced by ZoneLayoutDisplay::resetLeadZoneBounds(), and ZoneLayoutDisplay::setLeadZoneBounds().
NONE
enum scxt::ui::app::edit_screen::ZoneLayoutDisplay::MouseState NONE
Referenced by ZoneLayoutDisplay::mouseDown(), and ZoneLayoutDisplay::mouseUp().
dragFrom
enum scxt::ui::app::edit_screen::ZoneLayoutDisplay::DragFrom dragFrom[2]
Referenced by ZoneLayoutDisplay::mouseDown(), and ZoneLayoutDisplay::mouseDrag().
velocityHotZones
std::vector<juce::Rectangle<float> > velocityHotZones
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseMove(), and ZoneLayoutDisplay::setLeadZoneBounds().
keyboardHotZones
std::vector<juce::Rectangle<float> > keyboardHotZones
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseMove(), and ZoneLayoutDisplay::setLeadZoneBounds().
bothHotZones
std::vector<juce::Rectangle<float> > bothHotZones
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseMove(), and ZoneLayoutDisplay::setLeadZoneBounds().
lastSelectedZone
std::vector<juce::Rectangle<float> > lastSelectedZone
Referenced by ZoneLayoutDisplay::mouseDoubleClick(), ZoneLayoutDisplay::mouseDown(), and ZoneLayoutDisplay::setLeadZoneBounds().
firstMousePos
juce::Point<float> firstMousePos {0.f, 0.f}
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseUp(), and ZoneLayoutDisplay::paint().
lastMousePos
juce::Point<float> lastMousePos {0.f, 0.f}
Referenced by ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseDrag(), and ZoneLayoutDisplay::paint().
hPct
float hPct {0.0}
Referenced by ZoneLayoutDisplay::mouseDrag(), ZoneLayoutDisplay::paint(), ZoneLayoutDisplay::rectangleForRangeSkipEnd(), and ZoneLayoutDisplay::setHorizontalZoom().
hZoom
float hZoom {1.0}
Referenced by ZoneLayoutDisplay::mouseDrag(), ZoneLayoutDisplay::paint(), ZoneLayoutDisplay::rectangleForRangeSkipEnd(), and ZoneLayoutDisplay::setHorizontalZoom().
vPct
float vPct {0.0}
Referenced by ZoneLayoutDisplay::mouseDrag(), ZoneLayoutDisplay::paint(), ZoneLayoutDisplay::rectangleForRangeSkipEnd(), and ZoneLayoutDisplay::setVerticalZoom().
vZoom
float vZoom {1.0}
Referenced by ZoneLayoutDisplay::mouseDrag(), ZoneLayoutDisplay::paint(), ZoneLayoutDisplay::rectangleForRangeSkipEnd(), and ZoneLayoutDisplay::setVerticalZoom().
The documentation for this struct was generated from the following files:
ZoneLayoutDisplay.h
ZoneLayoutDisplay.cpp