shortcircuit-xt: scxt_traits< scxt::engine::Zone > Struct Reference
scxt_traits< scxt::engine::Zone > Struct Reference
Static Public Member Functions
template<template< typename... > class Traits>
static void assign (tao::json::basic_value< Traits > &v, const scxt::engine::Zone &t)
template<template< typename... > class Traits>
static void to (const tao::json::basic_value< Traits > &v, scxt::engine::Zone &zone)
Member Function Documentation
assign()
static void assign (tao::json::basic_value< Traits > & v, const scxt::engine::Zone & t) static
References Zone::egStorage, Zone::mapping, Zone::modulatorStorage, Zone::outputInfo, HasGroupZoneProcessors< T >::processorStorage, Zone::routingTable, and Zone::sampleData.
to()
static void to (const tao::json::basic_value< Traits > & v, scxt::engine::Zone & zone) static
References Zone::egStorage, scxt::json::findIf(), findIfArray(), scxt::json::findOrDefault(), Zone::mapping, Zone::modulatorStorage, Zone::outputInfo, HasGroupZoneProcessors< T >::processorStorage, Zone::routingTable, and Zone::sampleData.
The documentation for this struct was generated from the following file:
engine_traits.h