shortcircuit-xt: ProcTab< OTTraits > Struct Template Reference
ProcTab< OTTraits > Struct Template Reference
Classes
struct RC
Public Types
typedef connectors::DiscretePayloadDataAttachment< typename OTTraits::info_t, typename OTTraits::route_t > int_attachment_t
Public Member Functions
ProcTab (SCXTEditor *e, OutputPane< OTTraits > *pane)
std::string resolveJsonPath (const std::string &path) const override
void createBindAndPosition (const sst::jucegui::layouts::json_document::Control &ctrl, const sst::jucegui::layouts::json_document::Class &cls) override
void resized () override
std::string getRoutingName (typename OTTraits::route_t r)
void updateProcRoutingFromInfo ()
void updateFromProcessorPanes ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
OutputPane< OTTraits > * outputPane {nullptr}
std::unique_ptr< jcmp::TextPushButton > consistentButton
std::unique_ptr< jcmp::Label > consistentLabel
std::unique_ptr< int_attachment_t > routingA
std::unique_ptr< jcmp::MultiSwitch > multiW
std::unique_ptr< juce::Component > routingLayoutComp
std::array< std::unique_ptr< ProcessorPane::attachment_t >, nOuts > levelA
std::vector< std::unique_ptr< juce::Component > > jsonComponents
OTTraits::info_t & info
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int nOuts {scxt::processorsPerZoneAndGroup}
Member Typedef Documentation
int_attachment_t
template<typename OTTraits > typedef connectors::DiscretePayloadDataAttachment<typename OTTraits::info_t, typename OTTraits::route_t> int_attachment_t
Constructor & Destructor Documentation
ProcTab()
template<typename OTTraits > ProcTab (SCXTEditor * e, OutputPane< OTTraits > * pane)
Member Function Documentation
resolveJsonPath()
template<typename OTTraits > std::string resolveJsonPath (const std::string & path) const override
References SCXTEditor::displayError(), HasEditor::editor, and scxt::ui::connectors::jsonlayout::resolveJsonFile().
createBindAndPosition()
template<typename OTTraits > void createBindAndPosition (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls) override
References scxt::ui::connectors::jsonlayout::attachAndPosition(), scxt::ui::connectors::configureUpdater(), scxt::ui::connectors::jsonlayout::createAndPositionNonDataWidget(), scxt::ui::connectors::jsonlayout::createContinuousWidget(), scxt::ui::connectors::jsonlayout::createControlLabel(), scxt::datamodel::describeValue(), SCXTEditor::displayError(), HasEditor::editor, ProcTab< OTTraits >::jsonComponents, ProcTab< OTTraits >::levelA, ProcTab< OTTraits >::outputPane, scxt::dsp::processor::proct_none, and ProcTab< OTTraits >::routingLayoutComp.
resized()
template<typename OTTraits > void resized () override
References ProcTab< OTTraits >::consistentButton, ProcTab< OTTraits >::consistentLabel, ProcTab< OTTraits >::multiW, and ProcTab< OTTraits >::routingLayoutComp.
getRoutingName()
template<typename OTTraits > std::string getRoutingName (typename OTTraits::route_t r)
References HasGroupZoneProcessors< Group >::getProcRoutingPathDisplayName(), and HasGroupZoneProcessors< Zone >::getProcRoutingPathDisplayName().
Referenced by ProcTab< OTTraits >::updateProcRoutingFromInfo().
updateProcRoutingFromInfo()
template<typename OTTraits > void updateProcRoutingFromInfo ()
References ProcTab< OTTraits >::consistentButton, ProcTab< OTTraits >::consistentLabel, ProcTab< OTTraits >::getRoutingName(), ProcTab< OTTraits >::info, ProcTab< OTTraits >::multiW, ProcTab< OTTraits >::routingLayoutComp, and ProcTab< OTTraits >::updateFromProcessorPanes().
updateFromProcessorPanes()
template<typename OTTraits > void updateFromProcessorPanes ()
References SCXTEditor::displayError(), HasEditor::editor, ProcTab< OTTraits >::info, ProcTab< OTTraits >::jsonComponents, scxt::ui::connectors::jsonlayout::resolveJsonFile(), and ProcTab< OTTraits >::routingLayoutComp.
Referenced by ProcTab< OTTraits >::updateProcRoutingFromInfo().
Member Data Documentation
outputPane
template<typename OTTraits > OutputPane<OTTraits>* outputPane {nullptr}
Referenced by ProcTab< OTTraits >::createBindAndPosition().
consistentButton
template<typename OTTraits > std::unique_ptr<jcmp::TextPushButton> consistentButton
Referenced by ProcTab< OTTraits >::resized(), and ProcTab< OTTraits >::updateProcRoutingFromInfo().
consistentLabel
template<typename OTTraits > std::unique_ptr<jcmp::Label> consistentLabel
Referenced by ProcTab< OTTraits >::resized(), and ProcTab< OTTraits >::updateProcRoutingFromInfo().
routingA
template<typename OTTraits > std::unique_ptr<int_attachment_t> routingA
multiW
template<typename OTTraits > std::unique_ptr<jcmp::MultiSwitch> multiW
Referenced by ProcTab< OTTraits >::resized(), and ProcTab< OTTraits >::updateProcRoutingFromInfo().
routingLayoutComp
template<typename OTTraits > std::unique_ptr<juce::Component> routingLayoutComp
Referenced by ProcTab< OTTraits >::createBindAndPosition(), ProcTab< OTTraits >::resized(), ProcTab< OTTraits >::updateFromProcessorPanes(), and ProcTab< OTTraits >::updateProcRoutingFromInfo().
nOuts
template<typename OTTraits > constexpr int nOuts {scxt::processorsPerZoneAndGroup} static constexpr
levelA
template<typename OTTraits > std::array<std::unique_ptr<ProcessorPane::attachment_t>, nOuts> levelA
Referenced by ProcTab< OTTraits >::createBindAndPosition().
jsonComponents
template<typename OTTraits > std::vector<std::unique_ptr<juce::Component> > jsonComponents
Referenced by ProcTab< OTTraits >::createBindAndPosition(), and ProcTab< OTTraits >::updateFromProcessorPanes().
info
template<typename OTTraits > OTTraits::info_t& info
Referenced by ProcTab< OTTraits >::updateFromProcessorPanes(), and ProcTab< OTTraits >::updateProcRoutingFromInfo().
The documentation for this struct was generated from the following file:
OutputPane.cpp