shortcircuit-xt: ZoneSidebar Struct Reference
ZoneSidebar Struct Reference
Public Member Functions
ZoneSidebar (PartGroupSidebar *p)
~ZoneSidebar ()=default
void updateSelection ()
void resized () override
void processRowsChanged ()
void onRowClicked (const selection::SelectionManager::ZoneAddress &rowZone, bool isSelected, const juce::ModifierKeys &mods)
Public Member Functions inherited from GroupZoneSidebarBase< ZoneSidebar, true >
ZoneSidebar * asT ()
GroupZoneSidebarBase (PartGroupSidebar *p)
~GroupZoneSidebarBase ()
void postInit ()
void showPartSelectorMenu ()
void showSelectedPart (int part)
juce::Rectangle< int > baseResize ()
void addGroup ()
void updateSelectionFrom (const selection::SelectionManager::selectedZones_t &sel)
bool isLeadZone (const selection::SelectionManager::ZoneAddress &za)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
selection::SelectionManager::ZoneAddress lastZoneClicked {0, 0, 0}
Public Attributes inherited from GroupZoneSidebarBase< ZoneSidebar, true >
PartGroupSidebar * partGroupSidebar
std::unique_ptr< juce::ListBox > listBox
std::unique_ptr< GroupZoneListBoxModel< ZoneSidebar, forZone > > listBoxModel
std::unique_ptr< jcmp::MenuButton > partSelector
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
ZoneSidebar()
ZoneSidebar (PartGroupSidebar * p)
~ZoneSidebar()
~ZoneSidebar () default
Member Function Documentation
updateSelection()
void updateSelection ()
References SCXTEditor::allZoneSelections, SCXTEditor::currentLeadZoneSelection, HasEditor::editor, ZoneSidebar::lastZoneClicked, GroupZoneSidebarBase< ZoneSidebar, true >::partGroupSidebar, and GroupZoneSidebarBase< ZoneSidebar, true >::updateSelectionFrom().
resized()
void resized () override
References GroupZoneSidebarBase< ZoneSidebar, true >::baseResize(), and GroupZoneSidebarBase< ZoneSidebar, true >::listBox.
processRowsChanged()
void processRowsChanged ()
References SCXTEditor::doMultiSelectionAction(), HasEditor::editor, GroupZoneSidebarBase< ZoneSidebar, true >::listBox, GroupZoneSidebarBase< ZoneSidebar, true >::listBoxModel, SCLOG, and SCLOG_UNIMPL.
onRowClicked()
void onRowClicked (const selection::SelectionManager::ZoneAddress & rowZone, bool isSelected, const juce::ModifierKeys & mods)
References SCXTEditor::doSelectionAction(), HasEditor::editor, SelectionManager::ZoneAddress::group, ZoneSidebar::lastZoneClicked, SCLOG, and SelectionManager::ZoneAddress::zone.
Member Data Documentation
lastZoneClicked
selection::SelectionManager::ZoneAddress lastZoneClicked {0, 0, 0}
Referenced by ZoneSidebar::onRowClicked(), and ZoneSidebar::updateSelection().
The documentation for this struct was generated from the following file:
PartGroupSidebar.cpp