shortcircuit-xt: WriterWorker Struct Reference
WriterWorker Struct Reference
#include <writer_worker.h>
Classes
struct EnQAble
struct EnQAddSampleInfo
struct EnQBrowserLocation
struct EnQClientCallback
struct EnQDebugMsg
struct EnQSetup
Public Member Functions
void openDb ()
void closeDb ()
WriterWorker (const fs::path &p, messaging::MessageController &m)
void setupDatabase ()
void openForWrite ()
~WriterWorker ()
void loadQueueFunction ()
void addDebug (const std::string &m)
void addRemoveBrowserLocation (const fs::path &m, bool index, bool add)
void enqueueWorkItem (EnQAble *p)
sqlite3 * getReadOnlyConn (bool notifyOnError=true)
Public Attributes
std::string dbname
fs::path dbpath
messaging::MessageController & mc
std::atomic< bool > hasSetup {false}
bool haveOpenedForWriteOnce {false}
std::atomic< bool > waiting {false}
std::thread qThread
std::mutex qLock
std::condition_variable qCV
std::deque< EnQAble * > pathQ
std::atomic< bool > keepRunning {true}
Static Public Attributes
static constexpr const char * schema_version
static constexpr const char * setup_sql
Constructor & Destructor Documentation
WriterWorker()
WriterWorker (const fs::path & p, messaging::MessageController & m) explicit
References WriterWorker::dbname, and WriterWorker::dbpath.
~WriterWorker()
~WriterWorker ()
References WriterWorker::haveOpenedForWriteOnce, WriterWorker::keepRunning, WriterWorker::qCV, and WriterWorker::qThread.
Member Function Documentation
openDb()
void openDb ()
References WriterWorker::dbname, and SCLOG_IF.
Referenced by WriterWorker::loadQueueFunction().
closeDb()
void closeDb ()
References SCLOG_IF.
Referenced by WriterWorker::loadQueueFunction().
setupDatabase()
void setupDatabase ()
References WriterWorker::dbname, scxt::browser::SQL::Exec(), WriterWorker::hasSetup, WriterWorker::schema_version, SCLOG_IF, WriterWorker::setup_sql, and Exception::what().
Referenced by WriterWorker::EnQSetup::go().
openForWrite()
void openForWrite ()
References WriterWorker::haveOpenedForWriteOnce, WriterWorker::loadQueueFunction(), WriterWorker::pathQ, WriterWorker::qCV, WriterWorker::qLock, WriterWorker::qThread, and WriterWorker::waiting.
loadQueueFunction()
void loadQueueFunction ()
References scxt::messaging::client::clientSendToSerialization(), WriterWorker::closeDb(), TxnGuard::end(), WriterWorker::keepRunning, WriterWorker::mc, WriterWorker::openDb(), WriterWorker::pathQ, WriterWorker::qCV, WriterWorker::qLock, SCLOG_IF, WriterWorker::waiting, Exception::what(), and LockedException::what().
Referenced by WriterWorker::openForWrite().
addDebug()
void addDebug (const std::string & m)
References SCLOG_IF, and Exception::what().
Referenced by WriterWorker::EnQDebugMsg::go().
addRemoveBrowserLocation()
void addRemoveBrowserLocation (const fs::path & m, bool index, bool add)
References SCLOG_IF, and Exception::what().
Referenced by WriterWorker::EnQBrowserLocation::go().
enqueueWorkItem()
void enqueueWorkItem (EnQAble * p)
References WriterWorker::pathQ, WriterWorker::qCV, and WriterWorker::qLock.
Referenced by ScanWorker::ScanFile::go().
getReadOnlyConn()
sqlite3 * getReadOnlyConn (bool notifyOnError = true)
References WriterWorker::dbname, and SCLOG_IF.
Member Data Documentation
schema_version
constexpr const char* schema_version static constexpr
Initial value:
=
        "1011"
Referenced by WriterWorker::setupDatabase().
setup_sql
constexpr const char* setup_sql static constexpr
Referenced by WriterWorker::setupDatabase().
dbname
std::string dbname
Referenced by WriterWorker::getReadOnlyConn(), WriterWorker::openDb(), WriterWorker::setupDatabase(), and WriterWorker::WriterWorker().
dbpath
fs::path dbpath
Referenced by WriterWorker::WriterWorker().
mc
messaging::MessageController& mc
Referenced by WriterWorker::EnQClientCallback< T >::go(), and WriterWorker::loadQueueFunction().
hasSetup
std::atomic<bool> hasSetup {false}
Referenced by WriterWorker::setupDatabase().
haveOpenedForWriteOnce
bool haveOpenedForWriteOnce {false}
Referenced by WriterWorker::openForWrite(), and WriterWorker::~WriterWorker().
waiting
std::atomic<bool> waiting {false}
Referenced by WriterWorker::loadQueueFunction(), and WriterWorker::openForWrite().
qThread
std::thread qThread
Referenced by WriterWorker::openForWrite(), and WriterWorker::~WriterWorker().
qLock
std::mutex qLock
Referenced by WriterWorker::enqueueWorkItem(), WriterWorker::loadQueueFunction(), and WriterWorker::openForWrite().
qCV
std::condition_variable qCV
Referenced by WriterWorker::enqueueWorkItem(), WriterWorker::loadQueueFunction(), WriterWorker::openForWrite(), and WriterWorker::~WriterWorker().
pathQ
std::deque<EnQAble *> pathQ
Referenced by WriterWorker::enqueueWorkItem(), WriterWorker::loadQueueFunction(), and WriterWorker::openForWrite().
keepRunning
std::atomic<bool> keepRunning {true}
Referenced by WriterWorker::loadQueueFunction(), and WriterWorker::~WriterWorker().
The documentation for this struct was generated from the following file:
writer_worker.h