shortcircuit-xt: SinePlusDisplay< Proc > Struct Template Reference
SinePlusDisplay< Proc > Struct Template Reference
#include <EQDisplay.h>
Public Member Functions
SinePlusDisplay (ProcessorPane &p)
void rebuildWaveform ()
void paint (juce::Graphics &g) override
Public Attributes
ProcessorPane & mProcessorPane
Proc mProcessor
std::vector< float > curve
bool waveformBuilt {false}
Additional Inherited Members
Static Public Member Functions inherited from fxAdapter
static void setFloatParam (BaseClass *bc, int idx, float val)
static float getFloatParam (const BaseClass *bc, int idx)
static void setIntParam (BaseClass *, int, int)
static int getIntParam (const BaseClass *bc, int idx)
static float dbToLinear (const BaseClass *that, float f)
static float equalNoteToPitch (const BaseClass *that, float f)
static float getSampleRate (const BaseClass *)
static float getSampleRateInv (const BaseClass *)
static void preReservePool (BaseClass *, size_t)
static uint8_t * checkoutBlock (BaseClass *, size_t)
static void returnBlock (BaseClass *, uint8_t *, size_t)
Static Public Attributes inherited from fxAdapter
static constexpr int blockSize {scxt::blockSize}
Constructor & Destructor Documentation
SinePlusDisplay()
template<typename Proc > SinePlusDisplay (ProcessorPane & p) explicit
References SinePlusDisplay< Proc >::mProcessor, ProcessorPane::processorView, and SinePlusDisplay< Proc >::rebuildWaveform().
Member Function Documentation
rebuildWaveform()
template<typename Proc > void rebuildWaveform ()
References fxAdapter::blockSize, SinePlusDisplay< Proc >::curve, fxAdapter::getSampleRate(), SinePlusDisplay< Proc >::mProcessor, and SinePlusDisplay< Proc >::waveformBuilt.
Referenced by SinePlusDisplay< Proc >::paint(), and SinePlusDisplay< Proc >::SinePlusDisplay().
paint()
template<typename Proc > void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_2b, ColorMap::bg_1, SinePlusDisplay< Proc >::curve, HasEditor::editor, SinePlusDisplay< Proc >::mProcessorPane, ColorMap::panel_outline_2, SinePlusDisplay< Proc >::rebuildWaveform(), and SinePlusDisplay< Proc >::waveformBuilt.
Member Data Documentation
mProcessorPane
template<typename Proc > ProcessorPane& mProcessorPane
Referenced by SinePlusDisplay< Proc >::paint().
mProcessor
template<typename Proc > Proc mProcessor
Referenced by SinePlusDisplay< Proc >::rebuildWaveform(), and SinePlusDisplay< Proc >::SinePlusDisplay().
curve
template<typename Proc > std::vector<float> curve
Referenced by SinePlusDisplay< Proc >::paint(), and SinePlusDisplay< Proc >::rebuildWaveform().
waveformBuilt
template<typename Proc > bool waveformBuilt {false}
Referenced by SinePlusDisplay< Proc >::paint(), and SinePlusDisplay< Proc >::rebuildWaveform().
The documentation for this struct was generated from the following file:
EQDisplay.h