shortcircuit-xt: GroupSidebar Struct Reference
GroupSidebar Struct Reference
Public Member Functions
GroupSidebar (PartGroupSidebar *p)
~GroupSidebar ()=default
void updateSelection ()
void resized () override
void processRowsChanged ()
void onRowClicked (const selection::SelectionManager::ZoneAddress &rowZone, bool isSelected, const juce::ModifierKeys &mods)
Public Member Functions inherited from GroupZoneSidebarBase< GroupSidebar, false >
GroupSidebar * asT ()
GroupZoneSidebarBase (PartGroupSidebar *p)
~GroupZoneSidebarBase ()
void postInit ()
void showPartSelectorMenu ()
void showSelectedPart (int part)
juce::Rectangle< int > baseResize ()
void addGroup ()
void updateSelectionFrom (const selection::SelectionManager::selectedZones_t &sel)
bool isLeadZone (const selection::SelectionManager::ZoneAddress &za)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (const W &widget, const A &attachment)
Public Attributes
std::unique_ptr< GroupControls > groupControls
Public Attributes inherited from GroupZoneSidebarBase< GroupSidebar, false >
PartGroupSidebar * partGroupSidebar
std::unique_ptr< juce::ListBox > listBox
std::unique_ptr< GroupZoneListBoxModel< GroupSidebar, forZone > > listBoxModel
std::unique_ptr< jcmp::MenuButton > partSelector
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
GroupSidebar()
GroupSidebar (PartGroupSidebar * p)
References GroupSidebar::groupControls.
~GroupSidebar()
~GroupSidebar () default
Member Function Documentation
updateSelection()
void updateSelection ()
References SCXTEditor::allGroupSelections, HasEditor::editor, GroupZoneSidebarBase< GroupSidebar, false >::partGroupSidebar, and GroupZoneSidebarBase< GroupSidebar, false >::updateSelectionFrom().
resized()
void resized () override
References GroupZoneSidebarBase< GroupSidebar, false >::baseResize(), GroupSidebar::groupControls, and GroupZoneSidebarBase< GroupSidebar, false >::listBox.
processRowsChanged()
void processRowsChanged ()
References GroupZoneSidebarBase< GroupSidebar, false >::listBox, and SCLOG.
onRowClicked()
void onRowClicked (const selection::SelectionManager::ZoneAddress & rowZone, bool isSelected, const juce::ModifierKeys & mods)
References SCXTEditor::doMultiSelectionAction(), HasEditor::editor, and SelectionManager::ZoneAddress::zone.
Member Data Documentation
groupControls
std::unique_ptr<GroupControls> groupControls
Referenced by GroupSidebar::GroupSidebar(), and GroupSidebar::resized().
The documentation for this struct was generated from the following file:
PartGroupSidebar.cpp