shortcircuit-xt: EngineStateRestoreItem Struct Reference
EngineStateRestoreItem Struct Reference
#include <structure_undoable_items.h>
Public Member Functions
void store (engine::Engine &e)
void restore (engine::Engine &e) override
std::unique_ptr< UndoableItem > makeRedo (engine::Engine &e) override
std::string describe () const override
Public Member Functions inherited from UndoableItem
virtual ~UndoableItem ()=default
Public Attributes
std::string engineJSON
Member Function Documentation
store()
void store (engine::Engine & e)
References EngineStateRestoreItem::engineJSON, Engine::prepareToStream(), and scxt::json::streamEngineState().
restore()
void restore (engine::Engine & e) override virtual
Implements UndoableItem.
References EngineStateRestoreItem::engineJSON, Engine::getMessageController(), Engine::immediatelyTerminateAllVoices(), RAISE_ERROR_ENGINE, Engine::stopEngineRequests, and scxt::json::unstreamEngineState().
makeRedo()
std::unique_ptr< UndoableItem > makeRedo (engine::Engine & e) override virtual
Implements UndoableItem.
describe()
std::string describe () const override virtual
Implements UndoableItem.
Member Data Documentation
engineJSON
std::string engineJSON
Referenced by EngineStateRestoreItem::restore(), and EngineStateRestoreItem::store().
The documentation for this struct was generated from the following files:
structure_undoable_items.h
structure_undoable_items.cpp