shortcircuit-xt: SCXTPlugin Struct Reference
SCXTPlugin Struct Reference
#include <scxt-plugin.h>
Inherits plugHelper_t, and EditorProvider.
Public Member Functions
SCXTPlugin (const clap_host *h)
~SCXTPlugin ()
bool implementsGui () const noexcept override
std::unique_ptr< juce::Component > createEditor () override
bool registerOrUnregisterTimer (clap_id &id, int ms, bool reg) override
bool registerOrUnregisterPosixFd (int fd, clap_posix_fd_flags_t flags, bool reg) override
Static Public Member Functions
static bool synchronousEngineUnstream (const std::unique_ptr< scxt::engine::Engine > &e, const std::string &payload)
Public Attributes
std::unique_ptr< scxt::engine::Engine > engine
size_t blockPos {0}
std::unique_ptr< sst::clap_juce_shim::ClapJuceShim > clapJuceShim
Protected Types
enum MainThreadActions : uint64_t { RESCAN_PARAM_IVT = 1 << 0 }
Protected Member Functions
bool activate (double sampleRate, uint32_t minFrameCount, uint32_t maxFrameCount) noexcept override
void onMainThread () noexcept override
bool implementsAudioPorts () const noexcept override
uint32_t audioPortsCount (bool isInput) const noexcept override
bool audioPortsInfo (uint32_t index, bool isInput, clap_audio_port_info *info) const noexcept override
bool implementsNotePorts () const noexcept override
uint32_t notePortsCount (bool isInput) const noexcept override
bool notePortsInfo (uint32_t index, bool isInput, clap_note_port_info *info) const noexcept override
clap_process_status process (const clap_process *process) noexcept override
bool handleEvent (const clap_event_header_t *)
bool implementsState () const noexcept override
bool stateSave (const clap_ostream *stream) noexcept override
bool stateLoad (const clap_istream *stream) noexcept override
bool implementsParams () const noexcept override
uint32_t paramsCount () const noexcept override
bool paramsInfo (uint32_t paramIndex, clap_param_info *info) const noexcept override
bool paramsValue (clap_id paramId, double *value) noexcept override
bool paramsValueToText (clap_id paramId, double value, char *display, uint32_t size) noexcept override
bool paramsTextToValue (clap_id paramId, const char *display, double *value) noexcept override
void paramsFlush (const clap_input_events *in, const clap_output_events *out) noexcept override
const scxt::engine::Macro & macroFor (uint32_t paramId) const
void handleParamValueEvent (const clap_event_param_value *)
Protected Attributes
std::atomic< uint64_t > nextMainThreadAction
Member Enumeration Documentation
MainThreadActions
enum MainThreadActions : uint64_t protected
Enumerator
RESCAN_PARAM_IVT
Constructor & Destructor Documentation
SCXTPlugin()
SCXTPlugin (const clap_host * h)
References SCXTPlugin::clapJuceShim, SCXTPlugin::engine, and SCXTPlugin::nextMainThreadAction.
~SCXTPlugin()
~SCXTPlugin ()
References SCXTPlugin::engine.
Member Function Documentation
activate()
bool activate (double sampleRate, uint32_t minFrameCount, uint32_t maxFrameCount) override protected noexcept
References Engine::prepareToPlay().
onMainThread()
void onMainThread () override protected noexcept
References SCXTPlugin::nextMainThreadAction, and SCXTPlugin::RESCAN_PARAM_IVT.
implementsAudioPorts()
bool implementsAudioPorts () const override protected noexcept
audioPortsCount()
uint32_t audioPortsCount (bool isInput) const override protected noexcept
audioPortsInfo()
bool audioPortsInfo (uint32_t index, bool isInput, clap_audio_port_info * info) const override protected noexcept
implementsNotePorts()
bool implementsNotePorts () const override protected noexcept
notePortsCount()
uint32_t notePortsCount (bool isInput) const override protected noexcept
notePortsInfo()
bool notePortsInfo (uint32_t index, bool isInput, clap_note_port_info * info) const override protected noexcept
process()
clap_process_status process (const clap_process * process) override protected noexcept
References Engine::getMessageController(), Engine::getPatch(), SampleRateSupport::getSampleRateInv(), main(), Engine::onTransportUpdated(), Engine::processAudio(), scxt::messaging::audio::s2a_param_beginendedit, scxt::messaging::audio::s2a_param_refresh, scxt::messaging::audio::s2a_param_set_value, SCLOG_IF, and Engine::transport.
handleEvent()
bool handleEvent (const clap_event_header_t * nextEvent) protected
References SCXTPlugin::engine, and SCXTPlugin::handleParamValueEvent().
implementsState()
bool implementsState () const override protected noexcept
stateSave()
bool stateSave (const clap_ostream * stream) override protected noexcept
References Engine::FOR_DAW, Engine::getSampleManager(), Engine::prepareToStream(), SCLOG_IF, and scxt::json::streamEngineState().
stateLoad()
bool stateLoad (const clap_istream * stream) override protected noexcept
References scxt::messaging::client::clientSendToSerialization(), Engine::getMessageController(), and SCLOG_IF.
implementsParams()
bool implementsParams () const override protected noexcept
paramsCount()
uint32_t paramsCount () const override protected noexcept
paramsInfo()
bool paramsInfo (uint32_t paramIndex, clap_param_info * info) const override protected noexcept
References Engine::getPatch(), Macro::macroIDToIndex(), Macro::macroIDToPart(), and Macro::partIndexToMacroID().
paramsValue()
bool paramsValue (clap_id paramId, double * value) override protected noexcept
References Macro::isMacroID().
paramsValueToText()
bool paramsValueToText (clap_id paramId, double value, char * display, uint32_t size) override protected noexcept
References Macro::isMacroID().
paramsTextToValue()
bool paramsTextToValue (clap_id paramId, const char * display, double * value) override protected noexcept
References Macro::isMacroID().
paramsFlush()
void paramsFlush (const clap_input_events * in, const clap_output_events * out) override protected noexcept
macroFor()
const scxt::engine::Macro & macroFor (uint32_t paramId) const protected
References SCXTPlugin::engine, Macro::macroIDToIndex(), and Macro::macroIDToPart().
handleParamValueEvent()
void handleParamValueEvent (const clap_event_param_value * pev) protected
References SCXTPlugin::engine, Macro::isMacroID(), Macro::macroIDToIndex(), and Macro::macroIDToPart().
Referenced by SCXTPlugin::handleEvent().
implementsGui()
bool implementsGui () const override noexcept
References SCXTPlugin::clapJuceShim.
createEditor()
std::unique_ptr< juce::Component > createEditor () override
References SCXTPlugin::clapJuceShim, SCXTEditor::edHeight, SCXTEditor::edWidth, and SCXTPlugin::engine.
registerOrUnregisterTimer()
bool registerOrUnregisterTimer (clap_id & id, int ms, bool reg) override
registerOrUnregisterPosixFd()
bool registerOrUnregisterPosixFd (int fd, clap_posix_fd_flags_t flags, bool reg) override
synchronousEngineUnstream()
bool synchronousEngineUnstream (const std::unique_ptr< scxt::engine::Engine > & e, const std::string & payload) static
References scxt::messaging::client::clientSendToSerialization(), SCXTPlugin::engine, Engine::getMessageController(), and SCLOG_IF.
Member Data Documentation
engine
std::unique_ptr<scxt::engine::Engine> engine
Referenced by SCXTPlugin::createEditor(), SCXTPlugin::handleEvent(), SCXTPlugin::handleParamValueEvent(), SCXTPlugin::macroFor(), SCXTPlugin::SCXTPlugin(), SCXTPlugin::synchronousEngineUnstream(), and SCXTPlugin::~SCXTPlugin().
blockPos
size_t blockPos {0}
nextMainThreadAction
std::atomic<uint64_t> nextMainThreadAction protected
Referenced by SCXTPlugin::onMainThread(), and SCXTPlugin::SCXTPlugin().
clapJuceShim
std::unique_ptr<sst::clap_juce_shim::ClapJuceShim> clapJuceShim
Referenced by SCXTPlugin::createEditor(), SCXTPlugin::implementsGui(), and SCXTPlugin::SCXTPlugin().
The documentation for this struct was generated from the following files:
scxt-plugin.h
scxt-plugin.cpp