shortcircuit-xt: GroupMatrixEndpoints::OutputTarget Struct Reference
GroupMatrixEndpoints::OutputTarget Struct Reference
Public Member Functions
OutputTarget (engine::Engine *e)
void bind (GroupMatrix &m, engine::Group &z)
Public Attributes
TG panT
TG ampT
const float * panP {nullptr}
const float * ampP {nullptr}
Constructor & Destructor Documentation
OutputTarget()
OutputTarget (engine::Engine * e)
References GroupMatrixEndpoints::OutputTarget::ampT, GroupMatrixEndpoints::OutputTarget::panT, and GroupMatrixEndpoints::registerGroupModTarget().
Member Function Documentation
bind()
void bind (GroupMatrix & m, engine::Group & z)
References Group::GroupOutputInfo::amplitude, scxt::modulation::shared::bindEl(), Group::outputInfo, and Group::GroupOutputInfo::pan.
Referenced by GroupMatrixEndpoints::bindTargetBaseValues().
Member Data Documentation
panT
TG panT
Referenced by GroupMatrixEndpoints::OutputTarget::OutputTarget().
ampT
TG ampT
Referenced by GroupMatrixEndpoints::OutputTarget::OutputTarget().
panP
const float* panP {nullptr}
ampP
const float * ampP {nullptr}
The documentation for this struct was generated from the following files:
group_matrix.h
group_matrix.cpp