shortcircuit-xt: MacroToggleAttachment Struct Reference
MacroToggleAttachment Struct Reference
Public Member Functions
MacroToggleAttachment (SCXTEditor *e, int p, int i)
const engine::Macro & macro () const
engine::Macro & macro ()
std::string getLabel () const override
int getValue () const override
void setValueFromGUI (const int &f) override
void setValueFromModel (const int &) override
int getMin () const override
int getMax () const override
std::string getValueAsStringFor (int i) const override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupFloatWidget (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntWidget (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
void reportError (const std::string &title, const std::string &message) const
template<typename A >
void wireErrorReporter (A &att)
Public Attributes
int part {-1}
int index {-1}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
MacroToggleAttachment()
MacroToggleAttachment (SCXTEditor * e, int p, int i)
Member Function Documentation
macro() [1/2]
const engine::Macro & macro () const
References HasEditor::editor, MacroToggleAttachment::index, SCXTEditor::macroCache, and MacroToggleAttachment::part.
Referenced by MacroToggleAttachment::getLabel(), MacroToggleAttachment::getValue(), and MacroToggleAttachment::setValueFromGUI().
macro() [2/2]
engine::Macro & macro ()
References HasEditor::editor, MacroToggleAttachment::index, SCXTEditor::macroCache, and MacroToggleAttachment::part.
getLabel()
std::string getLabel () const override
References MacroToggleAttachment::macro(), and Macro::name.
getValue()
int getValue () const override
References MacroToggleAttachment::macro(), and Macro::value.
setValueFromGUI()
void setValueFromGUI (const int & f) override
References MacroToggleAttachment::index, MacroToggleAttachment::macro(), MacroToggleAttachment::part, HasEditor::sendToSerialization(), Macro::setValueConstrained(), and Macro::value.
setValueFromModel()
void setValueFromModel (const int &) override
getMin()
int getMin () const override
getMax()
int getMax () const override
getValueAsStringFor()
std::string getValueAsStringFor (int i) const override
Member Data Documentation
part
int part {-1}
Referenced by MacroToggleAttachment::macro(), MacroToggleAttachment::macro(), and MacroToggleAttachment::setValueFromGUI().
index
int index {-1}
Referenced by MacroToggleAttachment::macro(), MacroToggleAttachment::macro(), and MacroToggleAttachment::setValueFromGUI().
The documentation for this struct was generated from the following file:
SingleMacroEditor.cpp