shortcircuit-xt: SCXTEditor Struct Reference
SCXTEditor Struct Reference
Inherits WindowPanel, and DragAndDropContainer.
Classes
struct IdleTimer
Public Types
enum ActiveScreen { PLAY , MULTI , MIXER }
Public Member Functions
juce::Colour themeColor (scxt::ui::theme::ColorMap::Colors, float alpha=1.f)
SCXTEditor (messaging::MessageController &e, infrastructure::DefaultsProvider &d, const sample::SampleManager &s, const scxt::browser::Browser &b, const engine::Engine::SharedUIMemoryState &state)
virtual ~SCXTEditor () noexcept
void setActiveScreen (ActiveScreen s)
void showAboutOverlay ()
void showLogOverlay ()
void showWelcomeOverlay ()
void setZoomFactor (float zoomFactor)
void resized () override
void parentHierarchyChanged () override
void idle ()
void drainCallbackQueue ()
juce::PopupMenu::Options defaultPopupMenuOptions (juce::Component *on=nullptr)
void configureHasDiscreteMenuBuilder (sst::jucegui::components::HasDiscreteParamMenuBuilder *)
void onErrorFromEngine (const scxt::messaging::client::s2cError_t &)
void onEngineStatus (const engine::Engine::EngineStatusMessage &e)
void onMappingUpdated (const scxt::messaging::client::mappingSelectedZoneViewResposne_t &)
void onSamplesUpdated (const scxt::messaging::client::sampleSelectedZoneViewResposne_t &)
void onStructureUpdated (const engine::Engine::pgzStructure_t &)
void onGroupOrZoneEnvelopeUpdated (const scxt::messaging::client::adsrViewResponsePayload_t &payload)
void onGroupOrZoneProcessorDataAndMetadata (const scxt::messaging::client::processorDataResponsePayload_t &d)
void onZoneProcessorDataMismatch (const scxt::messaging::client::processorMismatchPayload_t &)
void onZoneVoiceMatrixMetadata (const scxt::voice::modulation::voiceMatrixMetadata_t &)
void onZoneVoiceMatrix (const scxt::voice::modulation::Matrix::RoutingTable &)
void onGroupMatrixMetadata (const scxt::modulation::groupMatrixMetadata_t &)
void onGroupMatrix (const scxt::modulation::GroupMatrix::RoutingTable &)
void onGroupOrZoneModulatorStorageUpdated (const scxt::messaging::client::indexedModulatorStorageUpdate_t &)
void onZoneOutputInfoUpdated (const scxt::messaging::client::zoneOutputInfoUpdate_t &p)
void onGroupOutputInfoUpdated (const scxt::messaging::client::groupOutputInfoUpdate_t &p)
void onGroupZoneMappingSummary (const scxt::engine::Part::zoneMappingSummary_t &)
void onSelectionState (const scxt::messaging::client::selectedStateMessage_t &)
void onSelectedPart (const int16_t)
int16_t getSelectedPart () const
void onMixerBusEffectFullData (const scxt::messaging::client::busEffectFullData_t &)
void onMixerBusSendData (const scxt::messaging::client::busSendData_t &)
void onBrowserRefresh (const bool)
void onDebugInfoGenerated (const scxt::messaging::client::debugResponse_t &)
void onAllProcessorDescriptions (const std::vector< dsp::processor::ProcessorDescription > &v)
void onMacroFullState (const scxt::messaging::client::macroFullState_t &)
void onMacroValue (const scxt::messaging::client::macroValue_t &)
void doSelectionAction (const selection::SelectionManager::ZoneAddress &, bool selecting, bool distinct, bool asLead)
void doSelectionAction (const selection::SelectionManager::SelectActionContents &)
void doMultiSelectionAction (const std::vector< selection::SelectionManager::SelectActionContents > &)
bool isAnyZoneFromGroupSelected (int groupIdx)
bool isSelected (const selection::SelectionManager::ZoneAddress &a)
void showTooltip (const juce::Component &relativeTo)
void hideTooltip ()
void setTooltipContents (const std::string &title, const std::vector< std::string > &display)
void setTooltipContents (const std::string &title, const std::string &display)
void showMainMenu ()
void addTuningMenu (juce::PopupMenu &into, bool addTitle=true)
void addZoomMenu (juce::PopupMenu &into, bool addTitle=true)
void addUIThemesMenu (juce::PopupMenu &p, bool addTitle=true)
Public Attributes
messaging::MessageController & msgCont
const sample::SampleManager & sampleManager
infrastructure::DefaultsProvider & defaultsProvider
const scxt::browser::Browser & browser
const engine::Engine::SharedUIMemoryState & sharedUiMemoryState
theme::ThemeApplier themeApplier
sst::basic_blocks::dsp::RNG rng
std::unique_ptr< SCXTJuceLookAndFeel > lnf
std::unique_ptr< IdleTimer > idleTimer
std::unique_ptr< HeaderRegion > headerRegion
std::unique_ptr< MultiScreen > multiScreen
std::unique_ptr< MixerScreen > mixerScreen
std::unique_ptr< PlayScreen > playScreen
std::unique_ptr< AboutScreen > aboutScreen
std::unique_ptr< WelcomeScreen > welcomeScreen
std::unique_ptr< LogScreen > logScreen
std::unique_ptr< sst::jucegui::components::ToolTip > toolTip
std::unique_ptr< sst::jucegui::accessibility::FocusDebugger > focusDebugger
enum scxt::ui::SCXTEditor::ActiveScreen MULTI
int32_t checkWelcomeCountdown {20}
float zoomFactor {1.f}
std::function< void(float)> onZoomChanged {nullptr}
uint64_t inboundMessageCount {0}
uint64_t inboundMessageBytes {0}
std::vector< dsp::processor::ProcessorDescription > allProcessors
std::array< std::array< scxt::engine::Macro, scxt::macrosPerPart >, scxt::numParts > macroCache
std::optional< selection::SelectionManager::ZoneAddress > currentLeadZoneSelection
selection::SelectionManager::selectedZones_t allZoneSelections
selection::SelectionManager::selectedZones_t allGroupSelections
int16_t selectedPart {0}
std::set< int > groupsWithSelectedZones
std::mutex callbackMutex
std::queue< std::string > callbackQueue
engine::Engine::EngineStatusMessage engineStatus
int64_t lastVoiceDisplayWriteCounter {-1}
float lastProcessMemoryInMegabytes {0}
Static Public Attributes
static constexpr int edWidth {1186}
static constexpr int edHeight {816}
Protected Member Functions
template<typename T >
void sendToSerialization (const T &msg)
template<typename A >
void beginEditNotifyEngine (const A &a)
template<typename A >
void endEditNotifyEngine (const A &a)
Protected Attributes
std::unique_ptr< melatonin::Inspector > melatoninInspector
Member Enumeration Documentation
ActiveScreen
enum ActiveScreen
Enumerator
PLAY
MULTI
MIXER
Constructor & Destructor Documentation
SCXTEditor()
SCXTEditor (messaging::MessageController & e, infrastructure::DefaultsProvider & d, const sample::SampleManager & s, const scxt::browser::Browser & b, const engine::Engine::SharedUIMemoryState & state)
References SCXTEditor::aboutScreen, SCXTEditor::callbackMutex, SCXTEditor::callbackQueue, scxt::infrastructure::colormapId, ColorMap::createColorMap(), SCXTEditor::defaultsProvider, SCXTEditor::drainCallbackQueue(), SCXTEditor::focusDebugger, SCXTEditor::headerRegion, SCXTEditor::idleTimer, SCXTEditor::lnf, SCXTEditor::logScreen, SCXTEditor::mixerScreen, SCXTEditor::msgCont, SCXTEditor::multiScreen, scxt::infrastructure::octave0, SCXTEditor::playScreen, ThemeApplier::recolorStylesheetWith(), MessageController::registerClient(), SCXTEditor::setZoomFactor(), scxt::infrastructure::showKnobs, SCXTEditor::themeApplier, SCXTEditor::toolTip, SCXTEditor::welcomeScreen, ColorMap::WIREFRAME, and scxt::infrastructure::zoomLevel.
~SCXTEditor()
~SCXTEditor () virtual noexcept
References SCXTEditor::idleTimer, SCXTEditor::msgCont, and MessageController::unregisterClient().
Member Function Documentation
themeColor()
juce::Colour themeColor (scxt::ui::theme::ColorMap::Colors c, float alpha = 1.f)
References SCXTEditor::themeApplier.
Referenced by SingleMacroEditor::onStyleChanged(), StepLFOPane::StepRender::paint(), Keyboard::paint(), MappingZones::paint(), NarrowVerticalMenu::paint(), and WelcomeScreen::paint().
setActiveScreen()
void setActiveScreen (ActiveScreen s)
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::MIXER, SCXTEditor::mixerScreen, SCXTEditor::MULTI, SCXTEditor::multiScreen, SCXTEditor::PLAY, SCXTEditor::playScreen, and SCXTEditor::resized().
Referenced by spData::setValueFromGUI().
showAboutOverlay()
void showAboutOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
showLogOverlay()
void showLogOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
showWelcomeOverlay()
void showWelcomeOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
Referenced by SCXTEditor::idle().
setZoomFactor()
void setZoomFactor (float zoomFactor)
References SCXTEditor::defaultsProvider, SCXTEditor::onZoomChanged, SCXTEditor::zoomFactor, and scxt::infrastructure::zoomLevel.
Referenced by SCXTEditor::parentHierarchyChanged(), and SCXTEditor::SCXTEditor().
resized()
void resized () override
References SCXTEditor::aboutScreen, SCXTEditor::headerRegion, SCXTEditor::logScreen, SCXTEditor::mixerScreen, SCXTEditor::multiScreen, SCXTEditor::playScreen, and SCXTEditor::welcomeScreen.
Referenced by SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
parentHierarchyChanged()
void parentHierarchyChanged () override
References SCXTEditor::setZoomFactor(), and SCXTEditor::zoomFactor.
idle()
void idle ()
References Engine::SharedUIMemoryState::busVULevels, SCXTEditor::checkWelcomeCountdown, Engine::SharedUIMemoryState::cpuLevel, SCXTEditor::currentLeadZoneSelection, SCXTEditor::defaultsProvider, SCXTEditor::headerRegion, SCXTEditor::lastVoiceDisplayWriteCounter, SCXTEditor::mixerScreen, SCXTEditor::multiScreen, SCXTEditor::sampleManager, SampleManager::sampleMemoryInBytes, SCXTEditor::sharedUiMemoryState, SCXTEditor::showWelcomeOverlay(), Engine::SharedUIMemoryState::voiceCount, Engine::SharedUIMemoryState::voiceDisplayItems, Engine::SharedUIMemoryState::voiceDisplayStateWriteCounter, scxt::infrastructure::welcomeScreenSeen, and WelcomeScreen::welcomeVersion.
Referenced by SCXTEditor::IdleTimer::timerCallback().
drainCallbackQueue()
void drainCallbackQueue ()
References SCXTEditor::callbackMutex, SCXTEditor::callbackQueue, scxt::messaging::client::clientThreadExecuteSerializationMessage(), SCXTEditor::inboundMessageBytes, SCXTEditor::inboundMessageCount, ThreadingChecker::isClientThread(), SCXTEditor::msgCont, SCLOG, and MessageController::threadingChecker.
Referenced by SCXTEditor::SCXTEditor().
defaultPopupMenuOptions()
juce::PopupMenu::Options defaultPopupMenuOptions (juce::Component * on = nullptr)
Referenced by LfoPane::pickPresets(), ProcTab< OTTraits >::selectNewProcRouting(), ChannelStrip::showAuxRouting(), ModRow< GZTrait >::showCurveMenu(), DriveFSListBoxRow::showDirectoryPopup(), MixerScreen::showFXSelectionMenu(), AdsrPane::showHamburgerMenu(), SCXTEditor::showMainMenu(), GroupZoneSidebarBase< T, forZone >::showPartSelectorMenu(), ModRow< GZTrait >::showSourceMenu(), and ModRow< GZTrait >::showTargetMenu().
configureHasDiscreteMenuBuilder()
void configureHasDiscreteMenuBuilder (sst::jucegui::components::HasDiscreteParamMenuBuilder * wss)
onErrorFromEngine()
void onErrorFromEngine (const scxt::messaging::client::s2cError_t & e)
onEngineStatus()
void onEngineStatus (const engine::Engine::EngineStatusMessage & e)
References SCXTEditor::aboutScreen, and SCXTEditor::engineStatus.
onMappingUpdated()
void onMappingUpdated (const scxt::messaging::client::mappingSelectedZoneViewResposne_t & payload)
References SCXTEditor::multiScreen.
onSamplesUpdated()
void onSamplesUpdated (const scxt::messaging::client::sampleSelectedZoneViewResposne_t & payload)
References SCXTEditor::multiScreen.
onStructureUpdated()
void onStructureUpdated (const engine::Engine::pgzStructure_t & s)
References SCXTEditor::multiScreen.
onGroupOrZoneEnvelopeUpdated()
void onGroupOrZoneEnvelopeUpdated (const scxt::messaging::client::adsrViewResponsePayload_t & payload)
References SCXTEditor::multiScreen.
onGroupOrZoneProcessorDataAndMetadata()
void onGroupOrZoneProcessorDataAndMetadata (const scxt::messaging::client::processorDataResponsePayload_t & d)
References SCXTEditor::multiScreen, and MultiScreen::numProcessorDisplays.
onZoneProcessorDataMismatch()
void onZoneProcessorDataMismatch (const scxt::messaging::client::processorMismatchPayload_t & pl)
References SCXTEditor::multiScreen.
onZoneVoiceMatrixMetadata()
void onZoneVoiceMatrixMetadata (const scxt::voice::modulation::voiceMatrixMetadata_t & d)
References SCXTEditor::multiScreen.
onZoneVoiceMatrix()
void onZoneVoiceMatrix (const scxt::voice::modulation::Matrix::RoutingTable & rt)
References SCXTEditor::multiScreen.
onGroupMatrixMetadata()
void onGroupMatrixMetadata (const scxt::modulation::groupMatrixMetadata_t & d)
References SCXTEditor::multiScreen.
onGroupMatrix()
void onGroupMatrix (const scxt::modulation::GroupMatrix::RoutingTable & t)
References SCXTEditor::multiScreen.
onGroupOrZoneModulatorStorageUpdated()
void onGroupOrZoneModulatorStorageUpdated (const scxt::messaging::client::indexedModulatorStorageUpdate_t & payload)
References SCXTEditor::multiScreen.
onZoneOutputInfoUpdated()
void onZoneOutputInfoUpdated (const scxt::messaging::client::zoneOutputInfoUpdate_t & p)
References SCXTEditor::multiScreen.
onGroupOutputInfoUpdated()
void onGroupOutputInfoUpdated (const scxt::messaging::client::groupOutputInfoUpdate_t & p)
References SCXTEditor::multiScreen.
onGroupZoneMappingSummary()
void onGroupZoneMappingSummary (const scxt::engine::Part::zoneMappingSummary_t & d)
References SCXTEditor::multiScreen, and SCLOG.
onSelectionState()
void onSelectionState (const scxt::messaging::client::selectedStateMessage_t & a)
References SCXTEditor::allGroupSelections, SCXTEditor::allZoneSelections, SCXTEditor::currentLeadZoneSelection, SCXTEditor::groupsWithSelectedZones, SCXTEditor::multiScreen, and SCLOG.
onSelectedPart()
void onSelectedPart (const int16_t p)
References SCXTEditor::multiScreen, SCLOG, and SCXTEditor::selectedPart.
getSelectedPart()
int16_t getSelectedPart () const
References SCXTEditor::selectedPart.
Referenced by SinglePart::paint().
onMixerBusEffectFullData()
void onMixerBusEffectFullData (const scxt::messaging::client::busEffectFullData_t & d)
References SCXTEditor::mixerScreen.
onMixerBusSendData()
void onMixerBusSendData (const scxt::messaging::client::busSendData_t & d)
References SCXTEditor::mixerScreen.
onBrowserRefresh()
void onBrowserRefresh (const bool)
References SCXTEditor::mixerScreen, and SCXTEditor::multiScreen.
onDebugInfoGenerated()
void onDebugInfoGenerated (const scxt::messaging::client::debugResponse_t & resp)
References SCLOG.
onAllProcessorDescriptions()
void onAllProcessorDescriptions (const std::vector< dsp::processor::ProcessorDescription > & v)
References SCXTEditor::allProcessors.
onMacroFullState()
void onMacroFullState (const scxt::messaging::client::macroFullState_t & s)
References SCXTEditor::macroCache, and SCXTEditor::multiScreen.
onMacroValue()
void onMacroValue (const scxt::messaging::client::macroValue_t &)
References SCLOG_WFUNC.
doSelectionAction() [1/2]
void doSelectionAction (const selection::SelectionManager::ZoneAddress & a, bool selecting, bool distinct, bool asLead)
References SCXTEditor::currentLeadZoneSelection, SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, SCXTEditor::sendToSerialization(), and SelectionManager::ZoneAddress::zone.
Referenced by MappingZones::mouseDown(), MappingZones::mouseUp(), and ZoneSidebar::onRowClicked().
doSelectionAction() [2/2]
void doSelectionAction (const selection::SelectionManager::SelectActionContents & p)
References SCXTEditor::sendToSerialization().
doMultiSelectionAction()
void doMultiSelectionAction (const std::vector< selection::SelectionManager::SelectActionContents > & p)
References SCXTEditor::sendToSerialization().
Referenced by GroupSidebar::onRowClicked(), and ZoneSidebar::processRowsChanged().
isAnyZoneFromGroupSelected()
bool isAnyZoneFromGroupSelected (int groupIdx)
References SCXTEditor::groupsWithSelectedZones.
Referenced by MappingZones::mouseDown(), and MappingZones::paint().
isSelected()
bool isSelected (const selection::SelectionManager::ZoneAddress & a)
References SCXTEditor::allZoneSelections.
Referenced by MappingZones::mouseDown(), and MappingZones::paint().
showTooltip()
void showTooltip (const juce::Component & relativeTo)
References SCXTEditor::toolTip.
Referenced by HasEditor::setupWidgetForValueTooltip().
hideTooltip()
void hideTooltip ()
References SCXTEditor::toolTip.
Referenced by HasEditor::setupWidgetForValueTooltip().
setTooltipContents() [1/2]
void setTooltipContents (const std::string & title, const std::vector< std::string > & display)
References SCXTEditor::toolTip.
Referenced by SCXTEditor::setTooltipContents(), MacroValueAttachment::setValueFromGUI(), ModRow< GZTrait >::updateTooltip(), and HasEditor::updateValueTooltip().
setTooltipContents() [2/2]
void setTooltipContents (const std::string & title, const std::string & display)
References SCXTEditor::setTooltipContents().
showMainMenu()
void showMainMenu ()
References SCXTEditor::addTuningMenu(), SCXTEditor::addUIThemesMenu(), SCXTEditor::addZoomMenu(), SCXTEditor::defaultPopupMenuOptions(), SCXTEditor::headerRegion, SCXTEditor::melatoninInspector, DebugActions::pretty_json, and DebugActions::pretty_json_part.
addTuningMenu()
void addTuningMenu (juce::PopupMenu & into, bool addTitle = true)
References MidikeyRetuner::MTS_ESP, and MidikeyRetuner::TWELVE_TET.
Referenced by SCXTEditor::showMainMenu().
addZoomMenu()
void addZoomMenu (juce::PopupMenu & into, bool addTitle = true)
References SCXTEditor::defaultsProvider, and scxt::infrastructure::invertScroll.
Referenced by SCXTEditor::showMainMenu().
addUIThemesMenu()
void addUIThemesMenu (juce::PopupMenu & p, bool addTitle = true)
References scxt::infrastructure::colormapId, ColorMap::createColorMap(), ColorMap::HICONTRAST_DARK, scxt::infrastructure::octave0, scxt::infrastructure::showKnobs, ColorMap::TEST, SCXTEditor::themeApplier, and ColorMap::WIREFRAME.
Referenced by SCXTEditor::showMainMenu().
sendToSerialization()
void sendToSerialization (const T & msg) protected
References scxt::messaging::client::clientSendToSerialization(), and SCXTEditor::msgCont.
Referenced by SCXTEditor::beginEditNotifyEngine(), SCXTEditor::doMultiSelectionAction(), SCXTEditor::doSelectionAction(), SCXTEditor::endEditNotifyEngine(), and HasEditor::sendToSerialization().
beginEditNotifyEngine()
void beginEditNotifyEngine (const A & a) protected
References SCXTEditor::sendToSerialization().
Referenced by HasEditor::setupWidgetForValueTooltip().
endEditNotifyEngine()
void endEditNotifyEngine (const A & a) protected
References SCXTEditor::sendToSerialization().
Referenced by HasEditor::setupWidgetForValueTooltip().
Member Data Documentation
msgCont
messaging::MessageController& msgCont
Referenced by GroupZoneSidebarBase< T, forZone >::addGroup(), SCXTEditor::drainCallbackQueue(), DriveFSListBoxRow::mouseDoubleClick(), SCXTEditor::SCXTEditor(), SCXTEditor::sendToSerialization(), and SCXTEditor::~SCXTEditor().
sampleManager
const sample::SampleManager& sampleManager
Referenced by SCXTEditor::idle(), SampleWaveform::paint(), SampleWaveform::pathForSample(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), and SampleWaveform::xPixelForSample().
defaultsProvider
infrastructure::DefaultsProvider& defaultsProvider
Referenced by SCXTEditor::addZoomMenu(), SCXTEditor::idle(), WelcomeScreen::okGotItDontShowAgain(), SCXTEditor::SCXTEditor(), and SCXTEditor::setZoomFactor().
browser
const scxt::browser::Browser& browser
Referenced by DriveFSArea::recalcContents(), and BrowserPane::resetRoots().
sharedUiMemoryState
const engine::Engine::SharedUIMemoryState& sharedUiMemoryState
Referenced by SCXTEditor::idle(), Keyboard::paint(), and MappingDisplay::voiceCountFor().
themeApplier
theme::ThemeApplier themeApplier
Referenced by SCXTEditor::addUIThemesMenu(), HeaderRegion::HeaderRegion(), SingleMacroEditor::onStyleChanged(), Keyboard::paint(), MappingZones::paint(), WelcomeScreen::paint(), LfoPane::rebuildPanelComponents(), SCXTEditor::SCXTEditor(), SCXTEditor::themeColor(), and MultiScreen::ZoneOrGroupElements< ZGTrait >::ZoneOrGroupElements().
rng
sst::basic_blocks::dsp::RNG rng
edWidth
constexpr int edWidth {1186} static constexpr
Referenced by SCXTPlugin::createEditor(), SCXTApplicationWindow::Intermediate::resized(), SCXTApplicationWindow::SCXTApplicationWindow(), and SCXTPluginEditor::SCXTPluginEditor().
edHeight
constexpr int edHeight {816} static
Referenced by SCXTPlugin::createEditor(), SCXTApplicationWindow::Intermediate::resized(), SCXTApplicationWindow::SCXTApplicationWindow(), and SCXTPluginEditor::SCXTPluginEditor().
lnf
std::unique_ptr<SCXTJuceLookAndFeel> lnf
Referenced by SCXTEditor::SCXTEditor().
idleTimer
std::unique_ptr<IdleTimer> idleTimer
Referenced by SCXTEditor::SCXTEditor(), and SCXTEditor::~SCXTEditor().
headerRegion
std::unique_ptr<HeaderRegion> headerRegion
Referenced by SCXTEditor::idle(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::showMainMenu().
multiScreen
std::unique_ptr<MultiScreen> multiScreen
Referenced by SCXTEditor::idle(), SCXTEditor::onBrowserRefresh(), SCXTEditor::onGroupMatrix(), SCXTEditor::onGroupMatrixMetadata(), SCXTEditor::onGroupOrZoneEnvelopeUpdated(), SCXTEditor::onGroupOrZoneModulatorStorageUpdated(), SCXTEditor::onGroupOrZoneProcessorDataAndMetadata(), SCXTEditor::onGroupOutputInfoUpdated(), SCXTEditor::onGroupZoneMappingSummary(), SCXTEditor::onMacroFullState(), SCXTEditor::onMappingUpdated(), SCXTEditor::onSamplesUpdated(), SCXTEditor::onSelectedPart(), SCXTEditor::onSelectionState(), SCXTEditor::onStructureUpdated(), SCXTEditor::onZoneOutputInfoUpdated(), SCXTEditor::onZoneProcessorDataMismatch(), SCXTEditor::onZoneVoiceMatrix(), SCXTEditor::onZoneVoiceMatrixMetadata(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::setActiveScreen().
mixerScreen
std::unique_ptr<MixerScreen> mixerScreen
Referenced by SCXTEditor::idle(), SCXTEditor::onBrowserRefresh(), SCXTEditor::onMixerBusEffectFullData(), SCXTEditor::onMixerBusSendData(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::setActiveScreen().
playScreen
std::unique_ptr<PlayScreen> playScreen
Referenced by SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::setActiveScreen().
aboutScreen
std::unique_ptr<AboutScreen> aboutScreen
Referenced by SCXTEditor::onEngineStatus(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
welcomeScreen
std::unique_ptr<WelcomeScreen> welcomeScreen
Referenced by SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
logScreen
std::unique_ptr<LogScreen> logScreen
Referenced by SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
toolTip
std::unique_ptr<sst::jucegui::components::ToolTip> toolTip
Referenced by SCXTEditor::hideTooltip(), SCXTEditor::SCXTEditor(), SCXTEditor::setTooltipContents(), and SCXTEditor::showTooltip().
focusDebugger
std::unique_ptr<sst::jucegui::accessibility::FocusDebugger> focusDebugger
Referenced by SCXTEditor::SCXTEditor().
MULTI
enum scxt::ui::SCXTEditor::ActiveScreen MULTI
Referenced by spData::getValueAsStringFor(), and SCXTEditor::setActiveScreen().
checkWelcomeCountdown
int32_t checkWelcomeCountdown {20}
Referenced by SCXTEditor::idle().
zoomFactor
float zoomFactor {1.f}
Referenced by SCXTEditor::parentHierarchyChanged(), and SCXTEditor::setZoomFactor().
onZoomChanged
std::function<void(float)> onZoomChanged {nullptr}
Referenced by SCXTEditor::setZoomFactor().
inboundMessageCount
uint64_t inboundMessageCount {0}
Referenced by SCXTEditor::drainCallbackQueue().
inboundMessageBytes
uint64_t inboundMessageBytes {0}
Referenced by SCXTEditor::drainCallbackQueue().
allProcessors
std::vector<dsp::processor::ProcessorDescription> allProcessors
Referenced by SCXTEditor::onAllProcessorDescriptions(), and ProcessorPane::showHamburgerMenu().
macroCache
std::array<std::array<scxt::engine::Macro, scxt::macrosPerPart>, scxt::numParts> macroCache
Referenced by MacroValueAttachment::macro(), SCXTEditor::onMacroFullState(), SingleMacroEditor::textEditorEscapeKeyPressed(), SingleMacroEditor::textEditorFocusLost(), SingleMacroEditor::textEditorReturnKeyPressed(), and SingleMacroEditor::updateFromEditorData().
currentLeadZoneSelection
std::optional<selection::SelectionManager::ZoneAddress> currentLeadZoneSelection
Referenced by SCXTEditor::doSelectionAction(), MappingPane::editorSelectionChanged(), SampleDisplay::MyTabbedComponent::filesDropped(), SCXTEditor::idle(), GroupZoneSidebarBase< T, forZone >::isLeadZone(), SampleDisplay::MyTabbedComponent::itemDropped(), MappingZones::mouseDown(), MappingZones::mouseUp(), SCXTEditor::onSelectionState(), MappingZones::paint(), MappingDisplay::setGroupZoneMappingSummary(), and ZoneSidebar::updateSelection().
allZoneSelections
selection::SelectionManager::selectedZones_t allZoneSelections
Referenced by SCXTEditor::isSelected(), SCXTEditor::onSelectionState(), and ZoneSidebar::updateSelection().
allGroupSelections
selection::SelectionManager::selectedZones_t allGroupSelections
Referenced by SCXTEditor::onSelectionState(), and GroupSidebar::updateSelection().
selectedPart
int16_t selectedPart {0}
Referenced by GroupZoneSidebarBase< T, forZone >::addGroup(), SCXTEditor::getSelectedPart(), MacroDisplay::macroDataChanged(), MappingPane::macroDataChanged(), MacroDisplay::MacroDisplay(), SCXTEditor::onSelectedPart(), MacroDisplay::selectedPartChanged(), PartGroupSidebar::selectedPartChanged(), and GroupZoneSidebarBase< T, forZone >::showPartSelectorMenu().
groupsWithSelectedZones
std::set<int> groupsWithSelectedZones
Referenced by SCXTEditor::isAnyZoneFromGroupSelected(), and SCXTEditor::onSelectionState().
callbackMutex
std::mutex callbackMutex
Referenced by SCXTEditor::drainCallbackQueue(), and SCXTEditor::SCXTEditor().
callbackQueue
std::queue<std::string> callbackQueue
Referenced by SCXTEditor::drainCallbackQueue(), and SCXTEditor::SCXTEditor().
engineStatus
engine::Engine::EngineStatusMessage engineStatus
Referenced by SCXTEditor::onEngineStatus(), and AboutScreen::resetInfo().
lastVoiceDisplayWriteCounter
int64_t lastVoiceDisplayWriteCounter {-1}
Referenced by SCXTEditor::idle().
lastProcessMemoryInMegabytes
float lastProcessMemoryInMegabytes {0}
melatoninInspector
std::unique_ptr<melatonin::Inspector> melatoninInspector protected
Referenced by SCXTEditor::showMainMenu().
The documentation for this struct was generated from the following files:
SCXTEditor.h
SCXTEditor.cpp
SCXTEditorMenus.cpp
SCXTEditorResponseHandlers.cpp