shortcircuit-xt: MenuValueTypeinBase Struct Reference
MenuValueTypeinBase Struct Reference abstract
#include <MenuValueTypein.h>
Public Member Functions
MenuValueTypeinBase (SCXTEditor *editor)
void getIdealSize (int &w, int &h) override
void resized () override
void visibilityChanged () override
virtual std::string getInitialText () const =0
virtual void setValueString (const std::string &)=0
virtual juce::Colour getValueColour () const
void setupTextEditorStyle ()
void textEditorReturnKeyPressed (juce::TextEditor &ed) override
void textEditorEscapeKeyPressed (juce::TextEditor &) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::unique_ptr< juce::TextEditor > textEditor
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
MenuValueTypeinBase()
MenuValueTypeinBase (SCXTEditor * editor)
References MenuValueTypeinBase::textEditor.
Member Function Documentation
getIdealSize()
void getIdealSize (int & w, int & h) override
resized()
void resized () override
References MenuValueTypeinBase::textEditor.
visibilityChanged()
void visibilityChanged () override
References MenuValueTypeinBase::textEditor.
getInitialText()
virtual std::string getInitialText () const pure virtual
Implemented in StepLFOPane::StepRender::StepMenuTypein, ModRow< GZTrait >::ModDepthTypein, and MenuValueTypein.
setValueString()
virtual void setValueString (const std::string &) pure virtual
Implemented in StepLFOPane::StepRender::StepMenuTypein, ModRow< GZTrait >::ModDepthTypein, and MenuValueTypein.
Referenced by MenuValueTypeinBase::textEditorReturnKeyPressed().
getValueColour()
juce::Colour getValueColour () const virtual
Reimplemented in StepLFOPane::StepRender::StepMenuTypein, ModRow< GZTrait >::ModDepthTypein, and MenuValueTypein.
References HasEditor::editor.
Referenced by MenuValueTypein::getValueColour(), and MenuValueTypeinBase::setupTextEditorStyle().
setupTextEditorStyle()
void setupTextEditorStyle ()
References HasEditor::editor, ColorMap::generic_content_high, MenuValueTypeinBase::getValueColour(), ThemeApplier::interMediumFor(), MenuValueTypeinBase::textEditor, SCXTEditor::themeApplier, and SCXTEditor::themeColor().
textEditorReturnKeyPressed()
void textEditorReturnKeyPressed (juce::TextEditor & ed) override
References MenuValueTypeinBase::setValueString().
textEditorEscapeKeyPressed()
void textEditorEscapeKeyPressed (juce::TextEditor &) override
Member Data Documentation
textEditor
std::unique_ptr<juce::TextEditor> textEditor
Referenced by MenuValueTypeinBase::MenuValueTypeinBase(), MenuValueTypeinBase::resized(), MenuValueTypeinBase::setupTextEditorStyle(), and MenuValueTypeinBase::visibilityChanged().
The documentation for this struct was generated from the following files:
MenuValueTypein.h
MenuValueTypein.cpp