shortcircuit-xt: BusEffectSpec Struct Reference
BusEffectSpec Struct Reference
#include <payload_undoable_items.h>
Public Types
using value_t = engine::BusEffectStorage
Static Public Member Functions
static std::string name ()
static value_t & ref (engine::Engine &e, const ZoneAddress &a, int32_t)
static void write (engine::Engine &e, const ZoneAddress &a, int32_t, const value_t &v)
static void extraClientRefresh (const engine::Engine &e, const std::vector< ZoneAddress > &sel, int32_t)
Static Public Attributes
static constexpr bool forZone {false}
static constexpr bool skipLeadRefresh {true}
Member Typedef Documentation
value_t
using value_t = engine::BusEffectStorage
Member Function Documentation
name()
static std::string name () static
ref()
static value_t & ref (engine::Engine & e, const ZoneAddress & a, int32_t) static
References Engine::getPatch(), SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, and SelectionManager::ZoneAddress::zone.
write()
static void write (engine::Engine & e, const ZoneAddress & a, int32_t , const value_t & v) static
References Engine::getPatch(), SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, BusEffectStorage::type, and SelectionManager::ZoneAddress::zone.
extraClientRefresh()
void extraClientRefresh (const engine::Engine & e, const std::vector< ZoneAddress > & sel, int32_t) static
References Engine::getPatch().
Member Data Documentation
forZone
constexpr bool forZone {false} static constexpr
skipLeadRefresh
constexpr bool skipLeadRefresh {true} static constexpr
The documentation for this struct was generated from the following files:
payload_undoable_items.h
payload_undoable_items.cpp