shortcircuit-xt: PartStreamRestoreItem Struct Reference
PartStreamRestoreItem Struct Reference
#include <structure_undoable_items.h>
Public Member Functions
void store (engine::Engine &e, int16_t pt, const std::string &lbl)
void restore (engine::Engine &e) override
std::unique_ptr< UndoableItem > makeRedo (engine::Engine &e) override
std::string describe () const override
Public Member Functions inherited from UndoableItem
virtual ~UndoableItem ()=default
Public Attributes
int16_t part {-1}
std::string label {"Load Part"}
std::string partJSON
Member Function Documentation
store()
void store (engine::Engine & e, int16_t pt, const std::string & lbl)
References Engine::FOR_PART, Engine::getPatch(), PartStreamRestoreItem::label, PartStreamRestoreItem::part, PartStreamRestoreItem::partJSON, and Engine::prepareToStream().
restore()
void restore (engine::Engine & e) override virtual
Implements UndoableItem.
References Engine::getMessageController(), Engine::getSelectionManager(), Engine::immediatelyTerminateAllVoices(), PartStreamRestoreItem::part, PartStreamRestoreItem::partJSON, RAISE_ERROR_ENGINE, and scxt::json::unstreamPartState().
makeRedo()
std::unique_ptr< UndoableItem > makeRedo (engine::Engine & e) override virtual
Implements UndoableItem.
References PartStreamRestoreItem::label, and PartStreamRestoreItem::part.
describe()
std::string describe () const override virtual
Implements UndoableItem.
References PartStreamRestoreItem::label, and PartStreamRestoreItem::part.
Member Data Documentation
part
int16_t part {-1}
Referenced by PartStreamRestoreItem::describe(), PartStreamRestoreItem::makeRedo(), PartStreamRestoreItem::restore(), and PartStreamRestoreItem::store().
label
std::string label {"Load Part"}
Referenced by PartStreamRestoreItem::describe(), PartStreamRestoreItem::makeRedo(), and PartStreamRestoreItem::store().
partJSON
std::string partJSON
Referenced by PartStreamRestoreItem::restore(), and PartStreamRestoreItem::store().
The documentation for this struct was generated from the following files:
structure_undoable_items.h
structure_undoable_items.cpp