shortcircuit-xt: MacroValueAttachment Struct Reference
MacroValueAttachment Struct Reference
Public Member Functions
MacroValueAttachment (SCXTEditor *e, int p, int i)
const engine::Macro & macro () const
engine::Macro & macro ()
std::string getLabel () const override
float getValue () const override
void setValueFromGUI (const float &f) override
void setValueFromModel (const float &) override
float getDefaultValue () const override
bool isBipolar () const override
float getMin () const override
float getMax () const override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
int part {-1}
int index {-1}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
MacroValueAttachment()
MacroValueAttachment (SCXTEditor * e, int p, int i)
Member Function Documentation
macro() [1/2]
const engine::Macro & macro () const
References HasEditor::editor, MacroValueAttachment::index, SCXTEditor::macroCache, and MacroValueAttachment::part.
Referenced by MacroValueAttachment::getLabel(), MacroValueAttachment::getMin(), MacroValueAttachment::getValue(), MacroValueAttachment::isBipolar(), and MacroValueAttachment::setValueFromGUI().
macro() [2/2]
engine::Macro & macro ()
References HasEditor::editor, MacroValueAttachment::index, SCXTEditor::macroCache, and MacroValueAttachment::part.
getLabel()
std::string getLabel () const override
References MacroValueAttachment::macro(), and Macro::name.
Referenced by MacroValueAttachment::setValueFromGUI().
getValue()
float getValue () const override
References MacroValueAttachment::macro(), and Macro::value.
setValueFromGUI()
void setValueFromGUI (const float & f) override
References HasEditor::editor, MacroValueAttachment::getLabel(), MacroValueAttachment::index, MacroValueAttachment::macro(), MacroValueAttachment::part, HasEditor::sendToSerialization(), SCXTEditor::setTooltipContents(), Macro::setValueConstrained(), and Macro::value.
setValueFromModel()
void setValueFromModel (const float &) override
getDefaultValue()
float getDefaultValue () const override
isBipolar()
bool isBipolar () const override
References Macro::isBipolar, and MacroValueAttachment::macro().
Referenced by MacroValueAttachment::getMin().
getMin()
float getMin () const override
References MacroValueAttachment::isBipolar(), and MacroValueAttachment::macro().
getMax()
float getMax () const override
Member Data Documentation
part
int part {-1}
Referenced by MacroValueAttachment::macro(), MacroValueAttachment::macro(), and MacroValueAttachment::setValueFromGUI().
index
int index {-1}
Referenced by MacroValueAttachment::macro(), MacroValueAttachment::macro(), and MacroValueAttachment::setValueFromGUI().
The documentation for this struct was generated from the following file:
SingleMacroEditor.cpp