shortcircuit-xt: GroupTriggerConditionsSpec Struct Reference
GroupTriggerConditionsSpec Struct Reference
#include <payload_undoable_items.h>
Static Public Member Functions
static std::string name ()
static void postWrite (engine::Engine &e, const ZoneAddress &a, int32_t)
Static Public Member Functions inherited from GroupMemberSpec<&engine::Group::triggerConditions >
static value_t & ref (engine::Engine &e, const ZoneAddress &a, int32_t)
Additional Inherited Members
Public Types inherited from GroupMemberSpec<&engine::Group::triggerConditions >
using value_t = payload_detail::member_value_t< engine::Group, M >
Static Public Attributes inherited from GroupMemberSpec<&engine::Group::triggerConditions >
static constexpr bool forZone
Member Function Documentation
name()
static std::string name () static
postWrite()
static void postWrite (engine::Engine & e, const ZoneAddress & a, int32_t) static
References Engine::getPatch(), scxt::undo::groupAt(), SelectionManager::ZoneAddress::part, GroupTriggerConditions::setupOnUnstream(), and Group::triggerConditions.
The documentation for this struct was generated from the following file:
payload_undoable_items.h