shortcircuit-xt: EqualTuningProvider Struct Reference
EqualTuningProvider Struct Reference
Public Member Functions
void init ()
float note_to_pitch (float note)
note is float offset from note 69 / A440 return is 2^(note * 12), namely frequency / 440.0
Protected Attributes
float table_pitch [tuning_table_size]
float table_pitch_inv [tuning_table_size]
float table_note_omega [2][tuning_table_size]
float table_two_to_the [1001]
float table_two_to_the_minus [1001]
Static Protected Attributes
static constexpr size_t tuning_table_size = 512
Member Function Documentation
init()
void init ()
References EqualTuningProvider::table_pitch, EqualTuningProvider::table_pitch_inv, EqualTuningProvider::table_two_to_the, EqualTuningProvider::table_two_to_the_minus, and EqualTuningProvider::tuning_table_size.
Referenced by Engine::Engine().
note_to_pitch()
float note_to_pitch (float note)
note is float offset from note 69 / A440 return is 2^(note * 12), namely frequency / 440.0
References EqualTuningProvider::table_pitch, EqualTuningProvider::table_two_to_the, and EqualTuningProvider::tuning_table_size.
Referenced by Voice::calculateGeneratorRatio(), SCXTVFXConfig< OSFactor >::equalNoteToPitch(), EngineBiquadAdapter::noteToPitchIgnoringTuning(), Config::noteToPitchIgnoringTuning(), Config::noteToPitchInv(), and StepLFO::UpdatePhaseIncrement().
Member Data Documentation
tuning_table_size
constexpr size_t tuning_table_size = 512 static constexpr protected
Referenced by EqualTuningProvider::init(), and EqualTuningProvider::note_to_pitch().
table_pitch
float table_pitch[tuning_table_size] protected
Referenced by EqualTuningProvider::init(), and EqualTuningProvider::note_to_pitch().
table_pitch_inv
float table_pitch_inv[tuning_table_size] protected
Referenced by EqualTuningProvider::init().
table_note_omega
float table_note_omega[2][tuning_table_size] protected
table_two_to_the
float table_two_to_the[1001] protected
Referenced by EqualTuningProvider::init(), and EqualTuningProvider::note_to_pitch().
table_two_to_the_minus
float table_two_to_the_minus[1001] protected
Referenced by EqualTuningProvider::init().
The documentation for this struct was generated from the following files:
equal.h
equal.cpp