shortcircuit-xt: SCXTVFXConfig< OSFactor > Struct Template Reference
SCXTVFXConfig< OSFactor > Struct Template Reference
#include <processor_impl.h>
Public Types
using BaseClass = Processor
Static Public Member Functions
static void preReservePool (BaseClass *b, size_t s)
static void preReserveSingleInstancePool (BaseClass *b, size_t s)
static uint8_t * checkoutBlock (BaseClass *b, size_t s)
static void returnBlock (BaseClass *b, uint8_t *d, size_t s)
static void setFloatParam (BaseClass *b, size_t index, float val)
static float getFloatParam (const BaseClass *b, size_t index)
static void setIntParam (BaseClass *b, size_t index, int val)
static int getIntParam (const BaseClass *b, size_t index)
static bool isTemposync (const BaseClass *c)
static bool isDeactivated (const BaseClass *c, int index)
static double * getTempoPointer (const BaseClass *c)
static float dbToLinear (BaseClass *b, float db)
static float getSampleRate (const BaseClass *b)
static float getSampleRateInv (const BaseClass *b)
static float equalNoteToPitch (const BaseClass *b, float f)
Static Public Attributes
static constexpr int blockSize {scxt::blockSize * OSFactor}
static constexpr int16_t oversamplingRatio {OSFactor}
Member Typedef Documentation
BaseClass
template<int OSFactor> using BaseClass = Processor
Member Function Documentation
preReservePool()
template<int OSFactor> static void preReservePool (BaseClass * b, size_t s) static
References Processor::memoryPool, MemoryPool::preReservePool(), and Processor::preReserveSize.
preReserveSingleInstancePool()
template<int OSFactor> static void preReserveSingleInstancePool (BaseClass * b, size_t s) static
References Processor::memoryPool, MemoryPool::preReserveSingleInstancePool(), and Processor::preReserveSingleInstanceSize.
checkoutBlock()
template<int OSFactor> static uint8_t * checkoutBlock (BaseClass * b, size_t s) static
References MemoryPool::checkoutBlock(), and Processor::memoryPool.
returnBlock()
template<int OSFactor> static void returnBlock (BaseClass * b, uint8_t * d, size_t s) static
References Processor::memoryPool, and MemoryPool::returnBlock().
setFloatParam()
template<int OSFactor> static void setFloatParam (BaseClass * b, size_t index, float val) static
References Processor::param.
getFloatParam()
template<int OSFactor> static float getFloatParam (const BaseClass * b, size_t index) static
References Processor::param.
setIntParam()
template<int OSFactor> static void setIntParam (BaseClass * b, size_t index, int val) static
References Processor::iparam.
getIntParam()
template<int OSFactor> static int getIntParam (const BaseClass * b, size_t index) static
References Processor::iparam.
isTemposync()
template<int OSFactor> static bool isTemposync (const BaseClass * c) static
References Processor::temposync.
isDeactivated()
template<int OSFactor> static bool isDeactivated (const BaseClass * c, int index) static
References Processor::deactivated.
getTempoPointer()
template<int OSFactor> static double * getTempoPointer (const BaseClass * c) static
References Processor::getTempoPointer().
dbToLinear()
template<int OSFactor> static float dbToLinear (BaseClass * b, float db) static
References scxt::dsp::dbTable.
getSampleRate()
template<int OSFactor> static float getSampleRate (const BaseClass * b) static
References SampleRateSupport::getSampleRate().
getSampleRateInv()
template<int OSFactor> static float getSampleRateInv (const BaseClass * b) static
References SampleRateSupport::getSampleRateInv().
equalNoteToPitch()
template<int OSFactor> static float equalNoteToPitch (const BaseClass * b, float f) static
References scxt::tuning::equalTuning.
Member Data Documentation
blockSize
template<int OSFactor> constexpr int blockSize {scxt::blockSize * OSFactor} static constexpr
oversamplingRatio
template<int OSFactor> constexpr int16_t oversamplingRatio {OSFactor} static constexpr
The documentation for this struct was generated from the following file:
processor_impl.h