shortcircuit-xt: RIFFWavWriter Struct Reference
RIFFWavWriter Struct Reference
#include <RIFFWavWriter.hpp>
Public Types
enum Format { PCM16 , F32 }
Public Member Functions
RIFFWavWriter ()
RIFFWavWriter (const fs::path &p, uint16_t chan, Format fmt)
~RIFFWavWriter ()
void writeRIFFHeader ()
void writeFMTChunk (int32_t samplerate)
void writeINSTChunk (char keyroot, char keylow, char keyhigh, char vellow, char velhigh)
void startDataChunk ()
void pushSamplesF32 (float d[2])
void pushSamplesI16 (int16_t d[2])
void pushc4 (char a, char b, char c, char d)
void pushc4 (char f[4])
void pushi32 (int32_t i)
void pushi16 (int16_t i)
void pushi8 (char i)
bool openFile ()
bool isOpen ()
bool closeFile ()
size_t getSampleCount () const
Public Attributes
fs::path outPath {}
FILE * outf {nullptr}
size_t elementsWritten {0}
size_t fileSizeLocation {0}
size_t dataSizeLocation {0}
size_t dataLen {0}
uint16_t nChannels {2}
std::string errMsg {}
enum scxt::patch_io::riffwav::RIFFWavWriter::Format PCM16
Member Enumeration Documentation
Format
enum Format
Enumerator
PCM16
F32
Constructor & Destructor Documentation
RIFFWavWriter() [1/2]
RIFFWavWriter ()
RIFFWavWriter() [2/2]
RIFFWavWriter (const fs::path & p, uint16_t chan, Format fmt)
~RIFFWavWriter()
~RIFFWavWriter ()
References RIFFWavWriter::closeFile().
Member Function Documentation
writeRIFFHeader()
void writeRIFFHeader ()
References RIFFWavWriter::elementsWritten, RIFFWavWriter::fileSizeLocation, RIFFWavWriter::pushc4(), and RIFFWavWriter::pushi32().
Referenced by scxt::patch_io::saveSubSample().
writeFMTChunk()
void writeFMTChunk (int32_t samplerate)
References RIFFWavWriter::F32, RIFFWavWriter::nChannels, RIFFWavWriter::pushc4(), RIFFWavWriter::pushi16(), and RIFFWavWriter::pushi32().
Referenced by scxt::patch_io::saveSubSample().
writeINSTChunk()
void writeINSTChunk (char keyroot, char keylow, char keyhigh, char vellow, char velhigh)
References RIFFWavWriter::pushc4(), RIFFWavWriter::pushi32(), and RIFFWavWriter::pushi8().
startDataChunk()
void startDataChunk ()
References RIFFWavWriter::dataSizeLocation, RIFFWavWriter::elementsWritten, RIFFWavWriter::pushc4(), and RIFFWavWriter::pushi32().
Referenced by scxt::patch_io::saveSubSample().
pushSamplesF32()
void pushSamplesF32 (float d[2])
References RIFFWavWriter::dataLen, RIFFWavWriter::elementsWritten, RIFFWavWriter::nChannels, and RIFFWavWriter::outf.
Referenced by scxt::patch_io::saveSubSample().
pushSamplesI16()
void pushSamplesI16 (int16_t d[2])
References RIFFWavWriter::dataLen, RIFFWavWriter::elementsWritten, RIFFWavWriter::nChannels, and RIFFWavWriter::outf.
Referenced by scxt::patch_io::saveSubSample().
pushc4() [1/2]
void pushc4 (char a, char b, char c, char d)
References RIFFWavWriter::pushc4().
Referenced by RIFFWavWriter::pushc4(), RIFFWavWriter::startDataChunk(), RIFFWavWriter::writeFMTChunk(), RIFFWavWriter::writeINSTChunk(), and RIFFWavWriter::writeRIFFHeader().
pushc4() [2/2]
void pushc4 (char f[4])
References RIFFWavWriter::elementsWritten, and RIFFWavWriter::outf.
pushi32()
void pushi32 (int32_t i)
References RIFFWavWriter::elementsWritten, and RIFFWavWriter::outf.
Referenced by RIFFWavWriter::startDataChunk(), RIFFWavWriter::writeFMTChunk(), RIFFWavWriter::writeINSTChunk(), and RIFFWavWriter::writeRIFFHeader().
pushi16()
void pushi16 (int16_t i)
References RIFFWavWriter::elementsWritten, and RIFFWavWriter::outf.
Referenced by RIFFWavWriter::writeFMTChunk().
pushi8()
void pushi8 (char i)
References RIFFWavWriter::elementsWritten, and RIFFWavWriter::outf.
Referenced by RIFFWavWriter::writeINSTChunk().
openFile()
bool openFile ()
References RIFFWavWriter::dataLen, RIFFWavWriter::dataSizeLocation, RIFFWavWriter::elementsWritten, RIFFWavWriter::errMsg, RIFFWavWriter::fileSizeLocation, RIFFWavWriter::outf, and RIFFWavWriter::outPath.
Referenced by scxt::patch_io::saveSubSample().
isOpen()
bool isOpen ()
References RIFFWavWriter::outf.
closeFile()
bool closeFile ()
References RIFFWavWriter::dataLen, RIFFWavWriter::dataSizeLocation, RIFFWavWriter::elementsWritten, RIFFWavWriter::fileSizeLocation, and RIFFWavWriter::outf.
Referenced by scxt::patch_io::saveSubSample(), and RIFFWavWriter::~RIFFWavWriter().
getSampleCount()
size_t getSampleCount () const
References RIFFWavWriter::dataLen, RIFFWavWriter::F32, RIFFWavWriter::nChannels, and RIFFWavWriter::PCM16.
Member Data Documentation
outPath
fs::path outPath {}
Referenced by RIFFWavWriter::openFile().
outf
FILE* outf {nullptr}
Referenced by RIFFWavWriter::closeFile(), RIFFWavWriter::isOpen(), RIFFWavWriter::openFile(), RIFFWavWriter::pushc4(), RIFFWavWriter::pushi16(), RIFFWavWriter::pushi32(), RIFFWavWriter::pushi8(), RIFFWavWriter::pushSamplesF32(), and RIFFWavWriter::pushSamplesI16().
elementsWritten
size_t elementsWritten {0}
Referenced by RIFFWavWriter::closeFile(), RIFFWavWriter::openFile(), RIFFWavWriter::pushc4(), RIFFWavWriter::pushi16(), RIFFWavWriter::pushi32(), RIFFWavWriter::pushi8(), RIFFWavWriter::pushSamplesF32(), RIFFWavWriter::pushSamplesI16(), RIFFWavWriter::startDataChunk(), and RIFFWavWriter::writeRIFFHeader().
fileSizeLocation
size_t fileSizeLocation {0}
Referenced by RIFFWavWriter::closeFile(), RIFFWavWriter::openFile(), and RIFFWavWriter::writeRIFFHeader().
dataSizeLocation
size_t dataSizeLocation {0}
Referenced by RIFFWavWriter::closeFile(), RIFFWavWriter::openFile(), and RIFFWavWriter::startDataChunk().
dataLen
size_t dataLen {0}
Referenced by RIFFWavWriter::closeFile(), RIFFWavWriter::getSampleCount(), RIFFWavWriter::openFile(), RIFFWavWriter::pushSamplesF32(), and RIFFWavWriter::pushSamplesI16().
nChannels
uint16_t nChannels {2}
Referenced by RIFFWavWriter::getSampleCount(), RIFFWavWriter::pushSamplesF32(), RIFFWavWriter::pushSamplesI16(), and RIFFWavWriter::writeFMTChunk().
errMsg
std::string errMsg {}
Referenced by RIFFWavWriter::openFile().
PCM16
enum scxt::patch_io::riffwav::RIFFWavWriter::Format PCM16
Referenced by scxt::patch_io::saveSubSample().
The documentation for this struct was generated from the following file:
RIFFWavWriter.hpp