shortcircuit-xt: SampleWaveform Struct Reference
SampleWaveform Struct Reference
#include <SampleWaveform.h>
Public Types
enum struct MouseState {
NONE , HZ_DRAG_SAMPSTART , HZ_DRAG_SAMPEND , HZ_DRAG_LOOPSTART ,
HZ_DRAG_LOOPEND
}
Public Member Functions
SampleWaveform (VariantDisplay *d)
void paint (juce::Graphics &g) override
void resized () override
void visibilityChanged () override
void rebuildHotZones ()
void addSamplePlaybackPosition (int64_t samplePos)
void clearSamplePlaybackPositions ()
void rebuildPaths ()
void rebuildEnvelopePaths ()
int64_t sampleForXPixel (float xpos)
int xPixelForSample (int64_t samplePos, bool doClamp=true)
int yPixelForAmplitude (float amp, float zeroPoint, float extraScale)
int xPixelForSampleDistance (int64_t sampleDistance)
void mouseDown (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseMove (const juce::MouseEvent &e) override
void mouseDoubleClick (const juce::MouseEvent &e) override
Component * associatedComponent () override
bool supportsVerticalZoom () const override
bool supportsHorizontalZoom () const override
juce::Rectangle< int > getInsetBounds ()
void setHorizontalZoom (float ps, float zf) override
void setVerticalZoom (float ps, float zf) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
VariantDisplay * display {nullptr}
juce::Rectangle< int > startSampleHZ
juce::Rectangle< int > endSampleHZ
juce::Rectangle< int > startLoopHZ
juce::Rectangle< int > endLoopHZ
juce::Rectangle< int > fadeLoopHz
std::vector< std::pair< int, int > > slicePixelAndSamplePositions
enum scxt::ui::app::edit_screen::SampleWaveform::MouseState NONE
std::set< int64_t > playbackPositions
int usedChannels {1}
juce::Path upperStroke [2]
juce::Path lowerStroke [2]
juce::Path upperFill [2]
juce::Path lowerFill [2]
float pctStart {0.f}
float zoomFactor {1.f}
std::function< void()> onPopupMenu {nullptr}
float vStart {0.f}
float vZoom {1.f}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int sliceSnapZoneInPixels {4}
Member Enumeration Documentation
MouseState
enum struct MouseState strong
Enumerator
NONE
HZ_DRAG_SAMPSTART
HZ_DRAG_SAMPEND
HZ_DRAG_LOOPSTART
HZ_DRAG_LOOPEND
Constructor & Destructor Documentation
SampleWaveform()
SampleWaveform (VariantDisplay * d)
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_1b, ColorMap::accent_2a, ColorMap::accent_2b, VariantDisplay::active, ColorMap::bg_1, ColorMap::bg_2, ColorMap::bg_3, SampleWaveform::display, HasEditor::editor, SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, ColorMap::generic_content_high, ColorMap::generic_content_low, ColorMap::generic_content_medium, SampleWaveform::getInsetBounds(), SampleManager::getSample(), ColorMap::grid_primary, ColorMap::grid_secondary, ThemeApplier::interBoldFor(), ThemeApplier::interMediumFor(), SampleWaveform::lowerFill, SampleWaveform::lowerStroke, SampleWaveform::playbackPositions, SCXTEditor::sampleManager, VariantDisplay::selectedVariation, SampleWaveform::startLoopHZ, SampleWaveform::startSampleHZ, SCXTEditor::themeApplier, SCXTEditor::themeColor(), SampleWaveform::upperFill, SampleWaveform::upperStroke, SampleWaveform::usedChannels, Zone::Variants::variants, VariantDisplay::variantView, SampleWaveform::vStart, SampleWaveform::vZoom, and SampleWaveform::xPixelForSample().
resized()
void resized () override
References SampleWaveform::rebuildHotZones().
visibilityChanged()
void visibilityChanged () override
References SampleWaveform::rebuildEnvelopePaths().
rebuildHotZones()
void rebuildHotZones ()
References SampleWaveform::display, HasEditor::editor, SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::fadeLoopHz, SampleWaveform::getInsetBounds(), SampleManager::getSample(), SampleWaveform::rebuildEnvelopePaths(), SCXTEditor::sampleManager, VariantDisplay::selectedVariation, SampleWaveform::slicePixelAndSamplePositions, SampleWaveform::startLoopHZ, SampleWaveform::startSampleHZ, Zone::Variants::variants, VariantDisplay::variantView, SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
Referenced by SampleWaveform::resized(), SampleWaveform::setHorizontalZoom(), and SampleWaveform::setVerticalZoom().
addSamplePlaybackPosition()
void addSamplePlaybackPosition (int64_t samplePos)
References SampleWaveform::playbackPositions.
clearSamplePlaybackPositions()
void clearSamplePlaybackPositions ()
References SampleWaveform::playbackPositions.
rebuildPaths()
void rebuildPaths ()
rebuildEnvelopePaths()
void rebuildEnvelopePaths ()
References Sample::BD_F32, Sample::BD_I16, SampleWaveform::display, HasEditor::editor, SampleWaveform::getInsetBounds(), SampleManager::getSample(), SampleWaveform::lowerFill, SampleWaveform::lowerStroke, SampleWaveform::pctStart, SCXTEditor::sampleManager, VariantDisplay::selectedVariation, SampleWaveform::upperFill, SampleWaveform::upperStroke, SampleWaveform::usedChannels, Zone::Variants::variants, VariantDisplay::variantView, SampleWaveform::xPixelForSample(), SampleWaveform::yPixelForAmplitude(), and SampleWaveform::zoomFactor.
Referenced by SampleWaveform::rebuildHotZones(), and SampleWaveform::visibilityChanged().
sampleForXPixel()
int64_t sampleForXPixel (float xpos)
References SampleWaveform::display, HasEditor::editor, SampleWaveform::getInsetBounds(), SampleManager::getSample(), SampleWaveform::pctStart, SCXTEditor::sampleManager, VariantDisplay::selectedVariation, Zone::Variants::variants, VariantDisplay::variantView, and SampleWaveform::zoomFactor.
Referenced by SampleWaveform::mouseDrag().
xPixelForSample()
int xPixelForSample (int64_t samplePos, bool doClamp = true)
References SampleWaveform::display, HasEditor::editor, SampleWaveform::getInsetBounds(), SampleManager::getSample(), SampleWaveform::pctStart, SCXTEditor::sampleManager, VariantDisplay::selectedVariation, Zone::Variants::variants, VariantDisplay::variantView, and SampleWaveform::zoomFactor.
Referenced by SampleWaveform::paint(), SampleWaveform::rebuildEnvelopePaths(), and SampleWaveform::rebuildHotZones().
yPixelForAmplitude()
int yPixelForAmplitude (float amp, float zeroPoint, float extraScale)
References SampleWaveform::vStart, and SampleWaveform::vZoom.
Referenced by SampleWaveform::rebuildEnvelopePaths().
xPixelForSampleDistance()
int xPixelForSampleDistance (int64_t sampleDistance)
References SampleWaveform::display, HasEditor::editor, SampleWaveform::getInsetBounds(), SampleManager::getSample(), SCXTEditor::sampleManager, VariantDisplay::selectedVariation, Zone::Variants::variants, VariantDisplay::variantView, and SampleWaveform::zoomFactor.
Referenced by SampleWaveform::rebuildHotZones().
mouseDown()
void mouseDown (const juce::MouseEvent & e) override
References SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::HZ_DRAG_LOOPEND, SampleWaveform::HZ_DRAG_LOOPSTART, SampleWaveform::HZ_DRAG_SAMPEND, SampleWaveform::HZ_DRAG_SAMPSTART, SampleWaveform::NONE, SampleWaveform::onPopupMenu, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
References SampleWaveform::display, SampleWaveform::NONE, SampleWaveform::onPopupMenu, and VariantDisplay::onSamplePointChangedFromGUI().
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
References SampleWaveform::display, SampleWaveform::HZ_DRAG_LOOPEND, SampleWaveform::HZ_DRAG_LOOPSTART, SampleWaveform::HZ_DRAG_SAMPEND, SampleWaveform::HZ_DRAG_SAMPSTART, SampleWaveform::NONE, VariantDisplay::onSamplePointChangedFromGUI(), SampleWaveform::sampleForXPixel(), VariantDisplay::selectedVariation, SampleWaveform::slicePixelAndSamplePositions, SampleWaveform::sliceSnapZoneInPixels, Zone::Variants::variants, and VariantDisplay::variantView.
mouseMove()
void mouseMove (const juce::MouseEvent & e) override
References SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & e) override
References SampleWaveform::display, and VariantDisplay::parentPane.
associatedComponent()
Component * associatedComponent () override
supportsVerticalZoom()
bool supportsVerticalZoom () const override
supportsHorizontalZoom()
bool supportsHorizontalZoom () const override
getInsetBounds()
juce::Rectangle< int > getInsetBounds ()
Referenced by SampleWaveform::paint(), SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
setHorizontalZoom()
void setHorizontalZoom (float ps, float zf) override
References SampleWaveform::pctStart, SampleWaveform::rebuildHotZones(), and SampleWaveform::zoomFactor.
setVerticalZoom()
void setVerticalZoom (float ps, float zf) override
References SampleWaveform::rebuildHotZones(), SampleWaveform::vStart, and SampleWaveform::vZoom.
Member Data Documentation
display
VariantDisplay* display {nullptr}
Referenced by SampleWaveform::mouseDoubleClick(), SampleWaveform::mouseDrag(), SampleWaveform::mouseUp(), SampleWaveform::paint(), SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
startSampleHZ
juce::Rectangle<int> startSampleHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
endSampleHZ
juce::Rectangle<int> endSampleHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
startLoopHZ
juce::Rectangle<int> startLoopHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
endLoopHZ
juce::Rectangle<int> endLoopHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
fadeLoopHz
juce::Rectangle<int> fadeLoopHz
Referenced by SampleWaveform::rebuildHotZones().
slicePixelAndSamplePositions
std::vector<std::pair<int, int> > slicePixelAndSamplePositions
Referenced by SampleWaveform::mouseDrag(), and SampleWaveform::rebuildHotZones().
sliceSnapZoneInPixels
constexpr int sliceSnapZoneInPixels {4} static constexpr
Referenced by SampleWaveform::mouseDrag().
NONE
enum scxt::ui::app::edit_screen::SampleWaveform::MouseState NONE
playbackPositions
std::set<int64_t> playbackPositions
Referenced by SampleWaveform::addSamplePlaybackPosition(), SampleWaveform::clearSamplePlaybackPositions(), and SampleWaveform::paint().
usedChannels
int usedChannels {1}
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildEnvelopePaths().
upperStroke
juce::Path upperStroke[2]
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildEnvelopePaths().
lowerStroke
juce::Path lowerStroke[2]
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildEnvelopePaths().
upperFill
juce::Path upperFill[2]
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildEnvelopePaths().
lowerFill
juce::Path lowerFill[2]
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildEnvelopePaths().
pctStart
float pctStart {0.f}
Referenced by SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::sampleForXPixel(), SampleWaveform::setHorizontalZoom(), and SampleWaveform::xPixelForSample().
zoomFactor
float zoomFactor {1.f}
Referenced by SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::sampleForXPixel(), SampleWaveform::setHorizontalZoom(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
onPopupMenu
std::function<void()> onPopupMenu {nullptr}
Referenced by SampleWaveform::mouseDown(), and SampleWaveform::mouseUp().
vStart
float vStart {0.f}
Referenced by SampleWaveform::paint(), SampleWaveform::setVerticalZoom(), and SampleWaveform::yPixelForAmplitude().
vZoom
float vZoom {1.f}
Referenced by SampleWaveform::paint(), SampleWaveform::setVerticalZoom(), and SampleWaveform::yPixelForAmplitude().
The documentation for this struct was generated from the following files:
SampleWaveform.h
SampleWaveform.cpp