shortcircuit-xt: MatrixEndpoints::MappingTarget Struct Reference
MatrixEndpoints::MappingTarget Struct Reference
#include <voice_matrix.h>
Public Member Functions
MappingTarget (engine::Engine *e)
void bind (Matrix &m, engine::Zone &z)
Public Attributes
TG pitchOffsetT
TG panT
TG ampT
TG playbackRatioT
const float * pitchOffsetP {nullptr}
const float * panP {nullptr}
const float * ampP {nullptr}
const float * playbackRatioP {nullptr}
float zeroBase {0.f}
Static Public Attributes
static constexpr TG pitchOffsetA {'zmap', 'ptof', 0}
Constructor & Destructor Documentation
MappingTarget()
MappingTarget (engine::Engine * e)
References MatrixEndpoints::MappingTarget::ampT, MatrixEndpoints::MappingTarget::panT, MatrixEndpoints::MappingTarget::pitchOffsetT, MatrixEndpoints::MappingTarget::playbackRatioT, and MatrixEndpoints::registerVoiceModTarget().
Member Function Documentation
bind()
void bind (Matrix & m, engine::Zone & z)
References scxt::modulation::shared::bindEl(), and Zone::mapping.
Referenced by MatrixEndpoints::bindTargetBaseValues().
Member Data Documentation
pitchOffsetA
constexpr TG pitchOffsetA {'zmap', 'ptof', 0} static constexpr
Referenced by scxt::sf2_support::importSF2().
pitchOffsetT
TG pitchOffsetT
Referenced by MatrixEndpoints::MappingTarget::MappingTarget().
panT
TG panT
Referenced by MatrixEndpoints::MappingTarget::MappingTarget().
ampT
TG ampT
Referenced by MatrixEndpoints::MappingTarget::MappingTarget().
playbackRatioT
TG playbackRatioT
Referenced by MatrixEndpoints::MappingTarget::MappingTarget().
pitchOffsetP
const float* pitchOffsetP {nullptr}
panP
const float * panP {nullptr}
ampP
const float * ampP {nullptr}
playbackRatioP
const float * playbackRatioP {nullptr}
zeroBase
float zeroBase {0.f}
The documentation for this struct was generated from the following files:
voice_matrix.h
voice_matrix.cpp