shortcircuit-xt: SelectionManager Struct Reference
SelectionManager Struct Reference
#include <selection_manager.h>
Classes
struct SelectActionContents
struct ZoneAddress
Public Types
enum MainSelection { MULTI , PART }
typedef std::unordered_set< ZoneAddress, ZoneAddress::Hash > selectedZones_t
using otherTabSelection_t = std::unordered_map< std::string, std::string >
Public Member Functions
SelectionManager (engine::Engine &e)
void applySelectActions (const std::vector< SelectActionContents > &v)
void applySelectActions (const SelectActionContents &v)
void guaranteeConsistencyAfterDeletes (const engine::Engine &, bool zoneDeleted, const ZoneAddress &addressDeleted)
void selectPart (int16_t part)
void clearAllSelections ()
selectedZones_t currentlySelectedZones ()
selectedZones_t currentlySelectedGroups ()
std::optional< ZoneAddress > currentLeadZone (const engine::Engine &e) const
std::optional< ZoneAddress > currentLeadGroup (const engine::Engine &e) const
std::pair< int, int > bestPartGroupForNewSample (const engine::Engine &e)
int currentlySelectedPart (const engine::Engine &e) const
void sendSelectedZonesToClient ()
void sendGroupZoneMappingForSelectedPart ()
void sendClientDataForLeadSelectionState ()
void sendDisplayDataForZonesBasedOnLead (int part, int group, int zone)
void sendDisplayDataForNoZoneSelected ()
void sendDisplayDataForGroupsBasedOnLead (int part, int group)
void sendDisplayDataForNoGroupSelected ()
void sendSelectedPartMacrosToClient ()
void sendOtherTabsSelectionToClient ()
void configureAndSendZoneModMatrixMetadata (int p, int g, int z)
void copyZoneProcessorLeadToAll (int which)
Public Attributes
engine::Engine & engine
int16_t selectedPart {0}
otherTabSelection_t otherTabSelection
std::array< selectedZones_t, scxt::numParts > allSelectedZones
std::array< selectedZones_t, scxt::numParts > allSelectedGroups
std::array< ZoneAddress, scxt::numParts > leadZone
std::array< ZoneAddress, scxt::numParts > leadGroup
Protected Types
enum ConsistencyCheck { PROCESSOR_TYPE , MATRIX_ROW , PROC_ROUTING , LFO_SHAPE }
Protected Member Functions
bool acrossSelectionConsistency (bool forZone, ConsistencyCheck whichCheck, int index)
std::vector< SelectActionContents > transformSelectionActions (const std::vector< SelectActionContents > &)
void adjustInternalStateForAction (const SelectActionContents &)
void guaranteeSelectedLead ()
void guaranteeSelectedLeadSomewhereIn (int part, int group, int zone)
void debugDumpSelectionState ()
Member Typedef Documentation
selectedZones_t
typedef std::unordered_set<ZoneAddress, ZoneAddress::Hash> selectedZones_t
otherTabSelection_t
using otherTabSelection_t = std::unordered_map<std::string, std::string>
Member Enumeration Documentation
MainSelection
enum MainSelection
Enumerator
MULTI
PART
ConsistencyCheck
enum ConsistencyCheck protected
Enumerator
PROCESSOR_TYPE
MATRIX_ROW
PROC_ROUTING
LFO_SHAPE
Constructor & Destructor Documentation
SelectionManager()
SelectionManager (engine::Engine & e)
Member Function Documentation
applySelectActions() [1/2]
void applySelectActions (const std::vector< SelectActionContents > & v)
References SelectionManager::adjustInternalStateForAction(), SelectionManager::debugDumpSelectionState(), SelectionManager::engine, SelectionManager::guaranteeSelectedLead(), SCLOG, SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendSelectedZonesToClient(), and SelectionManager::transformSelectionActions().
Referenced by SelectionManager::applySelectActions().
applySelectActions() [2/2]
void applySelectActions (const SelectActionContents & v)
References SelectionManager::applySelectActions().
guaranteeConsistencyAfterDeletes()
void guaranteeConsistencyAfterDeletes (const engine::Engine & engine, bool zoneDeleted, const ZoneAddress & addressDeleted)
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::debugDumpSelectionState(), SelectionManager::engine, SelectionManager::guaranteeSelectedLeadSomewhereIn(), SelectionManager::leadGroup, SelectionManager::leadZone, SCLOG_IF, SelectionManager::selectedPart, SelectionManager::sendClientDataForLeadSelectionState(), and SelectionManager::sendSelectedZonesToClient().
selectPart()
void selectPart (int16_t part)
References SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeSelectedLead(), SCLOG, SelectionManager::selectedPart, SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendSelectedPartMacrosToClient(), and SelectionManager::sendSelectedZonesToClient().
clearAllSelections()
void clearAllSelections ()
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::leadGroup, SelectionManager::leadZone, and SelectionManager::selectedPart.
acrossSelectionConsistency()
bool acrossSelectionConsistency (bool forZone, ConsistencyCheck whichCheck, int index) protected
References SelectionManager::allSelectedZones, SelectionManager::engine, Engine::getPatch(), SelectionManager::leadZone, SelectionManager::LFO_SHAPE, SelectionManager::MATRIX_ROW, SelectionManager::PROC_ROUTING, SelectionManager::PROCESSOR_TYPE, SCLOG_UNIMPL, and SelectionManager::selectedPart.
Referenced by SelectionManager::configureAndSendZoneModMatrixMetadata(), and SelectionManager::sendDisplayDataForZonesBasedOnLead().
transformSelectionActions()
std::vector< SelectionManager::SelectActionContents > transformSelectionActions (const std::vector< SelectActionContents > & inEls) protected
References SelectionManager::engine, and Engine::getPatch().
Referenced by SelectionManager::applySelectActions().
adjustInternalStateForAction()
void adjustInternalStateForAction (const SelectActionContents & z) protected
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::SelectActionContents::distinct, SelectionManager::engine, SelectionManager::SelectActionContents::forZone, Engine::getPatch(), SelectionManager::SelectActionContents::group, SelectionManager::leadGroup, SelectionManager::leadZone, SCLOG_IF, SCLOG_WFUNC, SelectionManager::selectedPart, SelectionManager::SelectActionContents::selecting, and SelectionManager::SelectActionContents::selectingAsLead.
Referenced by SelectionManager::applySelectActions().
guaranteeSelectedLead()
void guaranteeSelectedLead () protected
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::engine, Engine::getPatch(), SelectionManager::leadGroup, SelectionManager::leadZone, SCLOG_IF, and SelectionManager::selectedPart.
Referenced by SelectionManager::applySelectActions(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), and SelectionManager::selectPart().
guaranteeSelectedLeadSomewhereIn()
void guaranteeSelectedLeadSomewhereIn (int part, int group, int zone) protected
References SelectionManager::engine, Engine::getPatch(), SelectionManager::guaranteeSelectedLead(), SelectionManager::leadGroup, SelectionManager::leadZone, and SelectionManager::selectedPart.
Referenced by SelectionManager::guaranteeConsistencyAfterDeletes().
debugDumpSelectionState()
void debugDumpSelectionState () protected
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::leadGroup, SelectionManager::leadZone, SCLOG, and SelectionManager::selectedPart.
Referenced by SelectionManager::applySelectActions(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::selectPart(), and SelectionManager::sendSelectedZonesToClient().
currentlySelectedZones()
selectedZones_t currentlySelectedZones ()
References SelectionManager::allSelectedZones, and SelectionManager::selectedPart.
currentlySelectedGroups()
selectedZones_t currentlySelectedGroups ()
References SelectionManager::allSelectedGroups, and SelectionManager::selectedPart.
currentLeadZone()
std::optional< ZoneAddress > currentLeadZone (const engine::Engine & e) const
References SelectionManager::leadZone, and SelectionManager::selectedPart.
Referenced by SelectionManager::bestPartGroupForNewSample(), and SelectionManager::copyZoneProcessorLeadToAll().
currentLeadGroup()
std::optional< ZoneAddress > currentLeadGroup (const engine::Engine & e) const
References SelectionManager::leadGroup, and SelectionManager::selectedPart.
Referenced by SelectionManager::sendClientDataForLeadSelectionState().
bestPartGroupForNewSample()
std::pair< int, int > bestPartGroupForNewSample (const engine::Engine & e)
References SelectionManager::allSelectedZones, SelectionManager::currentLeadZone(), and SelectionManager::selectedPart.
currentlySelectedPart()
int currentlySelectedPart (const engine::Engine & e) const
References SelectionManager::selectedPart.
sendSelectedZonesToClient()
void sendSelectedZonesToClient ()
References SelectionManager::allSelectedGroups, SelectionManager::allSelectedZones, SelectionManager::debugDumpSelectionState(), SelectionManager::engine, Engine::getMessageController(), SelectionManager::leadGroup, SelectionManager::leadZone, scxt::messaging::client::s2c_send_selection_state, SCLOG, and SelectionManager::selectedPart.
Referenced by SelectionManager::applySelectActions(), SelectionManager::guaranteeConsistencyAfterDeletes(), and SelectionManager::selectPart().
sendGroupZoneMappingForSelectedPart()
void sendGroupZoneMappingForSelectedPart ()
References SelectionManager::engine, Engine::getMessageController(), Engine::getPatch(), scxt::messaging::client::s2c_send_selected_group_zone_mapping_summary, and SelectionManager::selectedPart.
sendClientDataForLeadSelectionState()
void sendClientDataForLeadSelectionState ()
References SelectionManager::currentLeadGroup(), SelectionManager::engine, Engine::getMessageController(), Engine::getPatch(), SelectionManager::leadZone, scxt::messaging::client::s2c_send_selected_group_zone_mapping_summary, scxt::messaging::client::s2c_send_selected_part, SCLOG, SelectionManager::selectedPart, SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForNoGroupSelected(), SelectionManager::sendDisplayDataForNoZoneSelected(), and SelectionManager::sendDisplayDataForZonesBasedOnLead().
Referenced by SelectionManager::applySelectActions(), SelectionManager::guaranteeConsistencyAfterDeletes(), and SelectionManager::selectPart().
sendDisplayDataForZonesBasedOnLead()
void sendDisplayDataForZonesBasedOnLead (int part, int group, int zone)
References SelectionManager::acrossSelectionConsistency(), SelectionManager::configureAndSendZoneModMatrixMetadata(), SelectionManager::engine, Engine::getMessageController(), Engine::getPatch(), SelectionManager::LFO_SHAPE, scxt::engine::lfosPerZone, SelectionManager::PROC_ROUTING, SelectionManager::PROCESSOR_TYPE, scxt::engine::processorCount, scxt::messaging::client::s2c_respond_single_processor_metadata_and_data, scxt::messaging::client::s2c_respond_zone_mapping, scxt::messaging::client::s2c_respond_zone_samples, scxt::messaging::client::s2c_update_group_or_zone_adsr_view, scxt::messaging::client::s2c_update_group_or_zone_individual_modulator_storage, scxt::messaging::client::s2c_update_group_or_zone_miscmod_storage, and scxt::messaging::client::s2c_update_zone_output_info.
Referenced by SelectionManager::copyZoneProcessorLeadToAll(), and SelectionManager::sendClientDataForLeadSelectionState().
sendDisplayDataForNoZoneSelected()
void sendDisplayDataForNoZoneSelected ()
References SelectionManager::engine, Engine::getMessageController(), scxt::engine::processorCount, scxt::messaging::client::s2c_respond_single_processor_metadata_and_data, scxt::messaging::client::s2c_respond_zone_mapping, scxt::messaging::client::s2c_respond_zone_samples, scxt::messaging::client::s2c_update_group_or_zone_adsr_view, scxt::messaging::client::s2c_update_zone_matrix_metadata, and scxt::messaging::client::s2c_update_zone_output_info.
Referenced by SelectionManager::sendClientDataForLeadSelectionState().
sendDisplayDataForGroupsBasedOnLead()
void sendDisplayDataForGroupsBasedOnLead (int part, int group)
References SelectionManager::allSelectedGroups, SelectionManager::engine, scxt::modulation::getGroupMatrixMetadata(), Engine::getMessageController(), Engine::getPatch(), scxt::engine::lfosPerZone, scxt::engine::processorCount, scxt::messaging::client::s2c_respond_single_processor_metadata_and_data, scxt::messaging::client::s2c_send_group_trigger_conditions, scxt::messaging::client::s2c_update_group_matrix, scxt::messaging::client::s2c_update_group_matrix_metadata, scxt::messaging::client::s2c_update_group_or_zone_adsr_view, scxt::messaging::client::s2c_update_group_or_zone_individual_modulator_storage, scxt::messaging::client::s2c_update_group_or_zone_miscmod_storage, scxt::messaging::client::s2c_update_group_output_info, and SCLOG_UNIMPL_ONCE.
Referenced by SelectionManager::sendClientDataForLeadSelectionState().
sendDisplayDataForNoGroupSelected()
void sendDisplayDataForNoGroupSelected ()
References SelectionManager::engine, Engine::getMessageController(), scxt::engine::processorCount, scxt::messaging::client::s2c_respond_single_processor_metadata_and_data, and scxt::messaging::client::s2c_update_group_or_zone_adsr_view.
Referenced by SelectionManager::sendClientDataForLeadSelectionState().
sendSelectedPartMacrosToClient()
void sendSelectedPartMacrosToClient ()
References SelectionManager::engine, Engine::getMessageController(), Engine::getPatch(), scxt::messaging::client::s2c_update_macro_full_state, and SelectionManager::selectedPart.
Referenced by SelectionManager::selectPart().
sendOtherTabsSelectionToClient()
void sendOtherTabsSelectionToClient ()
References SelectionManager::engine, Engine::getMessageController(), SelectionManager::otherTabSelection, and scxt::messaging::client::s2c_send_othertab_selection.
configureAndSendZoneModMatrixMetadata()
void configureAndSendZoneModMatrixMetadata (int p, int g, int z)
References SelectionManager::acrossSelectionConsistency(), Matrix::activeTargetsToBaseValue, Matrix::activeTargetsToPMD, MatrixEndpoints::bindTargetBaseValues(), SelectionManager::engine, Matrix::forUIMode, Engine::getMessageController(), Engine::getPatch(), SampleRateSupport::getSampleRate(), MatrixConfig::getTargetModMatrixElement(), scxt::voice::modulation::getVoiceMatrixMetadata(), MatrixConfig::isTargetModMatrixDepth(), SelectionManager::MATRIX_ROW, scxt::messaging::client::s2c_update_zone_matrix, and scxt::messaging::client::s2c_update_zone_matrix_metadata.
Referenced by SelectionManager::sendDisplayDataForZonesBasedOnLead().
copyZoneProcessorLeadToAll()
void copyZoneProcessorLeadToAll (int which)
References SelectionManager::allSelectedZones, SelectionManager::currentLeadZone(), SelectionManager::engine, Engine::getMessageController(), SelectionManager::selectedPart, and SelectionManager::sendDisplayDataForZonesBasedOnLead().
Member Data Documentation
engine
engine::Engine& engine
Referenced by SelectionManager::acrossSelectionConsistency(), SelectionManager::adjustInternalStateForAction(), SelectionManager::applySelectActions(), SelectionManager::configureAndSendZoneModMatrixMetadata(), SelectionManager::copyZoneProcessorLeadToAll(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForNoGroupSelected(), SelectionManager::sendDisplayDataForNoZoneSelected(), SelectionManager::sendDisplayDataForZonesBasedOnLead(), SelectionManager::sendGroupZoneMappingForSelectedPart(), SelectionManager::sendOtherTabsSelectionToClient(), SelectionManager::sendSelectedPartMacrosToClient(), SelectionManager::sendSelectedZonesToClient(), and SelectionManager::transformSelectionActions().
selectedPart
int16_t selectedPart {0}
Referenced by SelectionManager::acrossSelectionConsistency(), SelectionManager::adjustInternalStateForAction(), SelectionManager::bestPartGroupForNewSample(), SelectionManager::clearAllSelections(), SelectionManager::copyZoneProcessorLeadToAll(), SelectionManager::currentLeadGroup(), SelectionManager::currentLeadZone(), SelectionManager::currentlySelectedGroups(), SelectionManager::currentlySelectedPart(), SelectionManager::currentlySelectedZones(), SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), SelectionManager::selectPart(), SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendGroupZoneMappingForSelectedPart(), SelectionManager::sendSelectedPartMacrosToClient(), and SelectionManager::sendSelectedZonesToClient().
otherTabSelection
otherTabSelection_t otherTabSelection
Referenced by SelectionManager::sendOtherTabsSelectionToClient().
allSelectedZones
std::array<selectedZones_t, scxt::numParts> allSelectedZones
Referenced by SelectionManager::acrossSelectionConsistency(), SelectionManager::adjustInternalStateForAction(), SelectionManager::bestPartGroupForNewSample(), SelectionManager::clearAllSelections(), SelectionManager::copyZoneProcessorLeadToAll(), SelectionManager::currentlySelectedZones(), SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), and SelectionManager::sendSelectedZonesToClient().
allSelectedGroups
std::array<selectedZones_t, scxt::numParts> allSelectedGroups
Referenced by SelectionManager::adjustInternalStateForAction(), SelectionManager::clearAllSelections(), SelectionManager::currentlySelectedGroups(), SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), and SelectionManager::sendSelectedZonesToClient().
leadZone
std::array<ZoneAddress, scxt::numParts> leadZone
Referenced by SelectionManager::acrossSelectionConsistency(), SelectionManager::adjustInternalStateForAction(), SelectionManager::clearAllSelections(), SelectionManager::currentLeadZone(), SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), SelectionManager::sendClientDataForLeadSelectionState(), and SelectionManager::sendSelectedZonesToClient().
leadGroup
std::array<ZoneAddress, scxt::numParts> leadGroup
Referenced by SelectionManager::adjustInternalStateForAction(), SelectionManager::clearAllSelections(), SelectionManager::currentLeadGroup(), SelectionManager::debugDumpSelectionState(), SelectionManager::guaranteeConsistencyAfterDeletes(), SelectionManager::guaranteeSelectedLead(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), and SelectionManager::sendSelectedZonesToClient().
The documentation for this struct was generated from the following files:
selection_manager.h
selection_manager.cpp