shortcircuit-xt: Macro Struct Reference
Macro Struct Reference
Public Member Functions
void setIsBipolar (bool b)
void setValueConstrained (float f)
void setValue01 (float f)
float getValue01 () const
float valueFromString (const std::string &s) const
float value01FromString (const std::string &s) const
std::string value01ToString (float dv) const
std::string pluginParameterNameFor (int p, int i) const
Static Public Member Functions
static std::string defaultNameFor (int index)
static bool isMacroID (uint32_t id)
static int macroIDToPart (uint32_t id)
static int macroIDToIndex (uint32_t id)
static uint32_t partIndexToMacroID (uint32_t pt, uint32_t id)
Public Attributes
float value {0.f}
int16_t part {-1}
int16_t index {-1}
bool isBipolar {false}
bool isStepped {false}
size_t stepCount {1}
std::string name {}
Static Public Attributes
static constexpr uint32_t firstMacroParam {0x30000}
static constexpr uint32_t macroParamPartStride {0x100}
Member Function Documentation
setIsBipolar()
void setIsBipolar (bool b)
References Macro::isBipolar, Macro::setValueConstrained(), and Macro::value.
setValueConstrained()
void setValueConstrained (float f)
References Macro::isBipolar, and Macro::value.
Referenced by Macro::setIsBipolar(), Macro::setValue01(), MacroValueAttachment::setValueFromGUI(), and scxt::messaging::client::updateMacroFullState().
setValue01()
void setValue01 (float f)
References Macro::isBipolar, and Macro::setValueConstrained().
getValue01()
float getValue01 () const
References Macro::isBipolar, and Macro::value.
valueFromString()
float valueFromString (const std::string & s) const
References Macro::isBipolar.
Referenced by Macro::value01FromString().
value01FromString()
float value01FromString (const std::string & s) const
References Macro::isBipolar, and Macro::valueFromString().
value01ToString()
std::string value01ToString (float dv) const
References Macro::isBipolar.
defaultNameFor()
static std::string defaultNameFor (int index) static
References Macro::index.
Referenced by Part::Part(), Macro::pluginParameterNameFor(), ModRow< GZTrait >::refreshRow(), ModRow< GZTrait >::showSourceMenu(), SingleMacroEditor::textEditorFocusLost(), and SingleMacroEditor::textEditorReturnKeyPressed().
pluginParameterNameFor()
std::string pluginParameterNameFor (int p, int i) const
References Macro::defaultNameFor(), and Macro::name.
isMacroID()
static bool isMacroID (uint32_t id) static
References Macro::firstMacroParam, and Macro::macroParamPartStride.
Referenced by SCXTPlugin::handleParamValueEvent(), SCXTPlugin::paramsTextToValue(), SCXTPlugin::paramsValue(), and SCXTPlugin::paramsValueToText().
macroIDToPart()
static int macroIDToPart (uint32_t id) static
References Macro::firstMacroParam, and Macro::macroParamPartStride.
Referenced by SCXTPlugin::handleParamValueEvent(), SCXTPlugin::macroFor(), and SCXTPlugin::paramsInfo().
macroIDToIndex()
static int macroIDToIndex (uint32_t id) static
References Macro::firstMacroParam, and Macro::macroParamPartStride.
Referenced by SCXTPlugin::handleParamValueEvent(), SCXTPlugin::macroFor(), and SCXTPlugin::paramsInfo().
partIndexToMacroID()
static uint32_t partIndexToMacroID (uint32_t pt, uint32_t id) static
References Macro::firstMacroParam, and Macro::macroParamPartStride.
Referenced by scxt::messaging::client::doMacroBeginEndEdit(), SCXTPlugin::paramsInfo(), and scxt::messaging::client::updateMacroValue().
Member Data Documentation
value
float value {0.f}
Referenced by MacroValueAttachment::getValue(), Macro::getValue01(), Macro::setIsBipolar(), Macro::setValueConstrained(), and MacroValueAttachment::setValueFromGUI().
part
int16_t part {-1}
index
int16_t index {-1}
Referenced by Macro::defaultNameFor().
isBipolar
bool isBipolar {false}
Referenced by Macro::getValue01(), MacroValueAttachment::isBipolar(), Macro::setIsBipolar(), Macro::setValue01(), Macro::setValueConstrained(), Macro::value01FromString(), Macro::value01ToString(), and Macro::valueFromString().
isStepped
bool isStepped {false}
stepCount
size_t stepCount {1}
name
std::string name {}
Referenced by MacroValueAttachment::getLabel(), Macro::pluginParameterNameFor(), and scxt::messaging::client::updateMacroFullState().
firstMacroParam
constexpr uint32_t firstMacroParam {0x30000} static constexpr
Referenced by Macro::isMacroID(), Macro::macroIDToIndex(), Macro::macroIDToPart(), and Macro::partIndexToMacroID().
macroParamPartStride
constexpr uint32_t macroParamPartStride {0x100} static constexpr
Referenced by Macro::isMacroID(), Macro::macroIDToIndex(), Macro::macroIDToPart(), and Macro::partIndexToMacroID().
The documentation for this struct was generated from the following file:
macros.h