shortcircuit-xt: Bus Struct Reference
Bus Struct Reference
Classes
struct BusSendStorage
Public Member Functions
Bus ()
Bus (BusAddress a)
void resetBus ()
void clear ()
void process ()
void setAuxSendLevel (int idx, float slevel)
void resetSendState ()
void setBusEffectType (Engine &e, int idx, AvailableBusEffects t)
void initializeAfterUnstream (Engine &e)
void sendAllBusEffectInfoToClient (const Engine &e)
void sendBusEffectInfoToClient (const Engine &, int slot)
void sendBusSendStorageToClient (const Engine &e)
void onSampleRateChanged () override
Public Member Functions inherited from MoveableOnly< Bus >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Public Attributes
BusAddress address
float output [2][blockSize]
float outputOS [2][blockSize<< 1]
bool hasOSSignal {false}
bool previousHadOSSignal {false}
float auxoutputPreFX [2][blockSize]
float auxoutputPreVCA [2][blockSize]
float auxoutputPostVCA [2][blockSize]
float vuLevel [2] {0.f, 0.f}
float vuFalloff {0.f}
sst::filters::HalfRate::HalfRateFilter downsampleFilter
struct scxt::engine::Bus::BusSendStorage busSendStorage
bool mutedDueToSoloAway {false}
std::array< BusEffectStorage, maxEffectsPerBus > busEffectStorage
std::array< std::unique_ptr< BusEffect >, maxEffectsPerBus > busEffects
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Static Public Attributes
static constexpr int maxEffectsPerBus {scxt::maxEffectsPerBus}
static constexpr int maxSendsPerBus {scxt::maxSendsPerBus}
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Bus >
MoveableOnly ()
~MoveableOnly ()=default
Constructor & Destructor Documentation
Bus() [1/2]
Bus ()
Bus() [2/2]
Bus (BusAddress a)
References Bus::address, scxt::engine::DEFAULT_BUS, and scxt::engine::ERROR_BUS.
Member Function Documentation
resetBus()
void resetBus ()
References Bus::busEffects, Bus::busEffectStorage, Bus::busSendStorage, and Bus::maxEffectsPerBus.
Referenced by Patch::Busses::initialize().
clear()
void clear ()
References Bus::hasOSSignal, Bus::output, and Bus::outputOS.
Referenced by Patch::Busses::clear(), and Patch::process().
process()
void process ()
References Bus::downsampleFilter, Bus::hasOSSignal, Bus::outputOS, and Bus::previousHadOSSignal.
setAuxSendLevel()
void setAuxSendLevel (int idx, float slevel)
References Bus::busSendStorage, Bus::maxSendsPerBus, Bus::resetSendState(), Bus::BusSendStorage::sendLevels, and Bus::BusSendStorage::supportsSends.
resetSendState()
void resetSendState ()
References Bus::busSendStorage, Bus::BusSendStorage::hasSends, and Bus::BusSendStorage::sendLevels.
Referenced by Bus::setAuxSendLevel().
setBusEffectType()
void setBusEffectType (Engine & e, int idx, AvailableBusEffects t)
References Bus::busEffects, Bus::busEffectStorage, scxt::engine::createEffect(), and Bus::maxEffectsPerBus.
initializeAfterUnstream()
void initializeAfterUnstream (Engine & e)
References Bus::busEffects, Bus::busEffectStorage, scxt::engine::createEffect(), Bus::maxEffectsPerBus, and Bus::sendBusEffectInfoToClient().
Referenced by Patch::setupBussesOnUnstream().
sendAllBusEffectInfoToClient()
void sendAllBusEffectInfoToClient (const Engine & e)
References Bus::maxEffectsPerBus, and Bus::sendBusEffectInfoToClient().
Referenced by Patch::Busses::sendInitialBusInfo().
sendBusEffectInfoToClient()
void sendBusEffectInfoToClient (const Engine & e, int slot)
References Bus::address, Bus::busEffects, Bus::busEffectStorage, Engine::getMessageController(), BusEffectStorage::maxBusEffectParams, scxt::messaging::client::s2c_bus_effect_full_data, and scxt::messaging::client::serializationSendToClient().
Referenced by Bus::initializeAfterUnstream(), and Bus::sendAllBusEffectInfoToClient().
sendBusSendStorageToClient()
void sendBusSendStorageToClient (const Engine & e)
References Bus::address, Bus::busSendStorage, Engine::getMessageController(), scxt::messaging::client::s2c_bus_send_data, and scxt::messaging::client::serializationSendToClient().
Referenced by Patch::Busses::sendInitialBusInfo().
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References Bus::busEffects.
Member Data Documentation
maxEffectsPerBus
constexpr int maxEffectsPerBus {scxt::maxEffectsPerBus} static constexpr
Referenced by Bus::initializeAfterUnstream(), Bus::resetBus(), Bus::sendAllBusEffectInfoToClient(), and Bus::setBusEffectType().
maxSendsPerBus
constexpr int maxSendsPerBus {scxt::maxSendsPerBus} static constexpr
Referenced by Bus::setAuxSendLevel().
address
BusAddress address
Referenced by Bus::Bus(), Bus::sendBusEffectInfoToClient(), and Bus::sendBusSendStorageToClient().
output
float output[2][blockSize]
Referenced by Bus::clear().
outputOS
float outputOS[2][blockSize<< 1]
Referenced by Bus::clear(), and Bus::process().
hasOSSignal
bool hasOSSignal {false}
Referenced by Bus::clear(), and Bus::process().
previousHadOSSignal
bool previousHadOSSignal {false}
Referenced by Bus::process().
auxoutputPreFX
float auxoutputPreFX[2][blockSize]
auxoutputPreVCA
float auxoutputPreVCA[2][blockSize]
auxoutputPostVCA
float auxoutputPostVCA[2][blockSize]
vuLevel
float vuLevel[2] {0.f, 0.f}
vuFalloff
float vuFalloff {0.f}
downsampleFilter
sst::filters::HalfRate::HalfRateFilter downsampleFilter
Referenced by Bus::process().
busSendStorage
struct scxt::engine::Bus::BusSendStorage busSendStorage
Referenced by Bus::resetBus(), Bus::resetSendState(), Bus::sendBusSendStorageToClient(), Bus::setAuxSendLevel(), and Patch::setupBussesOnUnstream().
mutedDueToSoloAway
bool mutedDueToSoloAway {false}
Referenced by Patch::Busses::reconfigureSolo().
busEffectStorage
std::array<BusEffectStorage, maxEffectsPerBus> busEffectStorage
Referenced by Bus::initializeAfterUnstream(), Bus::resetBus(), Bus::sendBusEffectInfoToClient(), and Bus::setBusEffectType().
busEffects
std::array<std::unique_ptr<BusEffect>, maxEffectsPerBus> busEffects
Referenced by Bus::initializeAfterUnstream(), Bus::onSampleRateChanged(), Bus::resetBus(), Bus::sendBusEffectInfoToClient(), and Bus::setBusEffectType().
The documentation for this struct was generated from the following files:
bus.h
bus.cpp