shortcircuit-xt: Engine Struct Reference
Engine Struct Reference
#include <engine.h>
Classes
struct EngineStatusMessage
struct MonoVoiceManagerResponder
struct pathToZone_t
struct PGZStructureBundle
struct RuntimeConfig
struct SharedUIMemoryState
struct StreamGuard
struct UnstreamGuard
struct VMConfig
struct VoiceManagerResponder
Public Types
enum struct TuningMode { TWELVE_TET , MTS_CONTINOUS , MTS_NOTE_ON }
enum struct TuningZoneResolution { RESOLVE_KEY , RESOLVE_TUNED_PITCH }
enum struct OmniFlavor { OMNI , MPE , CHOCT }
enum struct MidiZoneAction {
NONE , SELECT , SET_KEY_BOUNDS_START , SET_KEY_BOUNDS_SECOND ,
SET_VEL_BOUNDS_START , SET_VEL_BOUNDS_SECOND
}
enum StreamReason { IN_PROCESS , FOR_MULTI , FOR_PART , FOR_DAW }
using voiceManager_t = sst::voicemanager::VoiceManager< VMConfig, VoiceManagerResponder, MonoVoiceManagerResponder >
typedef std::tuple< int32_t, int32_t, int32_t, int32_t > processorAddress_t
typedef std::vector< PGZStructureBundle > pgzStructure_t
using vmodTgtStrFn_t = std::function< std::string(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
using gmodTgtStrFn_t = std::function< std::string(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
using vmodTgtBoolFn_t = std::function< bool(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
using gmodTgtBoolFn_t = std::function< bool(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
using vmodTgtIntFn_t = std::function< int32_t(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
using gmodTgtIntFn_t = std::function< int32_t(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
using vmodSrcStrFn_t = std::function< std::string(const Zone &, const voice::modulation::MatrixConfig::SourceIdentifier &)>
using gmodSrcStrFn_t = std::function< std::string(const Group &, const voice::modulation::MatrixConfig::SourceIdentifier &)>
Public Member Functions
Engine ()
~Engine ()
const std::unique_ptr< Patch > & getPatch () const
const std::unique_ptr< sample::SampleManager > & getSampleManager () const
const std::unique_ptr< browser::Browser > & getBrowser () const
int getStereoOutputs () const
Audio processing.
void setStereoOutputs (int s)
bool processAudio ()
Process into an array of size stereoOutputs * 2 * blocksize.
void onTransportUpdated ()
void updateTransportPhasors ()
void processMIDI1Event (uint16_t midiPort, const uint8_t data[3])
Midi-style events.
void processNoteOnEvent (int16_t port, int16_t channel, int16_t key, int32_t note_id, double velocity, float retune)
void processNoteOffEvent (int16_t port, int16_t channel, int16_t key, int32_t note_id, double velocity)
size_t findZone (int16_t channel, int16_t key, int32_t noteId, int16_t velocity, std::array< pathToZone_t, maxVoices > &res)
void onPartConfigurationUpdated ()
DECLARE_ENUM_STRING (TuningMode)
DECLARE_ENUM_STRING (TuningZoneResolution)
DECLARE_ENUM_STRING (OmniFlavor)
void resetTuningFromRuntimeConfig ()
void setMpeTuningAwareness (bool a)
void setPBTuningAwareness (bool a)
void setOmniFlavor (const OmniFlavor &of)
void onSampleRateChanged () override
const std::unique_ptr< Zone > & zoneByPath (const pathToZone_t &path) const
voice::Voice * initiateVoice (const pathToZone_t &path)
void releaseVoice (int16_t channel, int16_t key, int32_t noteid, int32_t releaseVelocity)
void immediatelyTerminateAllVoices ()
void assertActiveVoiceCount ()
const std::unique_ptr< messaging::MessageController > & getMessageController () const
const std::unique_ptr< selection::SelectionManager > & getSelectionManager () const
void prepareToPlay (double sampleRate)
Prepare to play sets up the internal state to prepare us to play.
void loadSampleIntoSelectedPartAndGroup (const fs::path &, int16_t rootKey, KeyboardRange krange, VelocityRange vrange, bool sampleRangeInfoOverridesArguments=false)
void loadSampleIntoSelectedPartAndGroup (const fs::path &p)
void loadCompoundElementIntoSelectedPartAndGroup (const scxt::sample::compound::CompoundElement &, int16_t rootKey=60, KeyboardRange krange={48, 72}, VelocityRange vrange={0, 127})
void loadSampleIntoZone (const fs::path &, int16_t part, int16_t group, int16_t zone, int variantID)
void loadCompoundElementIntoZone (const sample::compound::CompoundElement &, int16_t part, int16_t group, int16_t zone, int variantID)
void createEmptyZone (int part, int group, KeyboardRange krange={48, 72}, VelocityRange vrange={0, 127})
void duplicateZone (const selection::SelectionManager::ZoneAddress &)
void copyZone (const selection::SelectionManager::ZoneAddress &)
void pasteZone (const selection::SelectionManager::ZoneAddress &)
void sendMetadataToClient () const
void sendFullRefreshToClient () const
void sendEngineStatusToClient () const
void clearAll (bool purgeSamples=true)
const std::optional< dsp::processor::ProcessorStorage > getProcessorStorage (const processorAddress_t &addr) const
pgzStructure_t getPartGroupZoneStructure () const
Get the Part/Group/Zone structure as a set o fzone addreses.
const std::unique_ptr< MemoryPool > & getMemoryPool ()
void registerVoiceModTarget (const voice::modulation::MatrixConfig::TargetIdentifier &, vmodTgtStrFn_t pathFn, vmodTgtStrFn_t nameFn, vmodTgtIntFn_t additiveFn, vmodTgtBoolFn_t enabledFn=[](const auto &, const auto &) { return true;})
void registerVoiceModSource (const voice::modulation::MatrixConfig::SourceIdentifier &, vmodSrcStrFn_t pathFn, vmodSrcStrFn_t nameFn)
void registerGroupModTarget (const modulation::GroupMatrixConfig::TargetIdentifier &, gmodTgtStrFn_t pathFn, gmodTgtStrFn_t nameFn, gmodTgtIntFn_t additiveFn, gmodTgtBoolFn_t enabledFn=[](const auto &, const auto &) { return true;})
void registerGroupModSource (const modulation::GroupMatrixConfig::SourceIdentifier &, gmodSrcStrFn_t pathFn, gmodSrcStrFn_t nameFn)
void remapZonesToNewSample (const SampleID &oldId, const SampleID &newId, int forPart)
void terminateVoicesForZone (Zone &z)
void terminateVoicesForGroup (Group &g)
void setMacro01ValueFromPlugin (int part, int index, float value01)
std::optional< fs::path > setupUserStorageDirectory ()
void prepareToStream ()
Public Member Functions inherited from MoveableOnly< Engine >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Public Attributes
EngineID id
std::unique_ptr< infrastructure::DefaultsProvider > defaults
std::string runningEnvironment {"Unknown"}
An option to add a description of your running environment, like "VST3 in Reaper".
sst::basic_blocks::modulators::Transport transport
tuning::MidikeyRetuner midikeyRetuner
struct scxt::engine::Engine::RuntimeConfig runtimeConfig
enum scxt::engine::Engine::MidiZoneAction NONE
struct scxt::engine::Engine::VoiceManagerResponder * this
struct scxt::engine::Engine::MonoVoiceManagerResponder * this
voiceManager_t voiceManager {voiceManagerResponder, monoVoiceManagerResponder}
std::atomic< uint32_t > activeVoices {0}
uint64_t nextVoiceCreationId {1}
std::unique_ptr< voice::PreviewVoice > previewVoice
std::mutex modifyStructureMutex
This is a mutex which we lock when modifying the structure in the engine.
struct scxt::engine::Engine::SharedUIMemoryState sharedUIMemoryState
int32_t updateVoiceDisplayStateEvery {10000000}
The VoiceDisplayState structure is updated at some relatively low (like 30hz) frequency by the engine for communication to a potential client if the message controller has a client connected.
int32_t lastUpdateVoiceDisplayState {0}
int64_t midiNoteStateCounter {0}
int64_t lastMidiNoteStateCounter {0}
bool forceVoiceUpdate {false}
bool sendSamplePosition {true}
sst::basic_blocks::dsp::RNG rng
Clipboard clipboard
std::atomic< int32_t > stopEngineRequests {0}
std::unordered_map< voice::modulation::MatrixConfig::TargetIdentifier, std::tuple< vmodTgtStrFn_t, vmodTgtStrFn_t, vmodTgtIntFn_t, vmodTgtBoolFn_t > > voiceModTargets
std::unordered_map< modulation::GroupMatrixConfig::TargetIdentifier, std::tuple< gmodTgtStrFn_t, gmodTgtStrFn_t, gmodTgtIntFn_t, gmodTgtBoolFn_t > > groupModTargets
std::unordered_map< voice::modulation::MatrixConfig::SourceIdentifier, std::pair< vmodSrcStrFn_t, vmodSrcStrFn_t > > voiceModSources
std::unordered_map< modulation::GroupMatrixConfig::SourceIdentifier, std::pair< gmodSrcStrFn_t, gmodSrcStrFn_t > > groupModSources
undo::UndoManager undoManager
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Static Public Attributes
static thread_local bool isFullEngineUnstream {false}
static thread_local StreamReason streamReason {StreamReason::IN_PROCESS}
static thread_local uint64_t fullEngineUnstreamStreamingVersion {0}
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Engine >
MoveableOnly ()
~MoveableOnly ()=default
Member Typedef Documentation
voiceManager_t
using voiceManager_t = sst::voicemanager::VoiceManager<VMConfig, VoiceManagerResponder, MonoVoiceManagerResponder>
processorAddress_t
typedef std::tuple<int32_t, int32_t, int32_t, int32_t> processorAddress_t
pgzStructure_t
typedef std::vector<PGZStructureBundle> pgzStructure_t
vmodTgtStrFn_t
using vmodTgtStrFn_t = std::function<std::string(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
gmodTgtStrFn_t
using gmodTgtStrFn_t = std::function<std::string(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
vmodTgtBoolFn_t
using vmodTgtBoolFn_t = std::function<bool(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
gmodTgtBoolFn_t
using gmodTgtBoolFn_t = std::function<bool(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
vmodTgtIntFn_t
using vmodTgtIntFn_t = std::function<int32_t(const Zone &, const voice::modulation::MatrixConfig::TargetIdentifier &)>
gmodTgtIntFn_t
using gmodTgtIntFn_t = std::function<int32_t(const Group &, const modulation::GroupMatrixConfig::TargetIdentifier &)>
vmodSrcStrFn_t
using vmodSrcStrFn_t = std::function<std::string(const Zone &, const voice::modulation::MatrixConfig::SourceIdentifier &)>
gmodSrcStrFn_t
using gmodSrcStrFn_t = std::function<std::string(const Group &, const voice::modulation::MatrixConfig::SourceIdentifier &)>
Member Enumeration Documentation
TuningMode
enum struct TuningMode strong
Enumerator
TWELVE_TET
MTS_CONTINOUS
MTS_NOTE_ON
TuningZoneResolution
enum struct TuningZoneResolution strong
Enumerator
RESOLVE_KEY
RESOLVE_TUNED_PITCH
OmniFlavor
enum struct OmniFlavor strong
Enumerator
OMNI
MPE
CHOCT
MidiZoneAction
enum struct MidiZoneAction strong
Enumerator
NONE
SELECT
SET_KEY_BOUNDS_START
SET_KEY_BOUNDS_SECOND
SET_VEL_BOUNDS_START
SET_VEL_BOUNDS_SECOND
StreamReason
enum StreamReason
Enumerator
IN_PROCESS
FOR_MULTI
FOR_PART
FOR_DAW
Constructor & Destructor Documentation
Engine()
Engine ()
References scxt::infrastructure::applyOmniToAllOnSelect, Engine::RuntimeConfig::applyOmniToAllPartsOnSelect, scxt::dsp::dbTable, scxt::infrastructure::defaultKeyToString(), Engine::RuntimeConfig::defaultOmniFlavor, Engine::defaults, scxt::tuning::equalTuning, scxt::humanReadableVersion(), ModulationCurves::initializeCurves(), Engine::RuntimeConfig::omniFlavor, scxt::infrastructure::omniFlavor, Engine::onPartConfigurationUpdated(), Engine::previewVoice, Engine::rng, Engine::runtimeConfig, SCLOG_IF, Engine::setStereoOutputs(), Engine::setupUserStorageDirectory(), scxt::dsp::sincTable, scxt::dsp::twentyFiveSecondExpTable, and scxt::dsp::twoToTheXTable.
~Engine()
~Engine ()
References Engine::getPatch().
Member Function Documentation
getPatch()
const std::unique_ptr< Patch > & getPatch () const
Referenced by SelectionManager::acrossSelectionConsistency(), SelectionManager::adjustInternalStateForAction(), scxt::messaging::client::clearPart(), SelectionManager::configureAndSendZoneOrGroupModMatrixMetadata(), scxt::messaging::client::doBusSwapFX(), scxt::messaging::client::doDebugAction(), scxt::messaging::client::doFullAdsrStorageUpdateForGroupsOrZones(), scxt::messaging::client::doFullModStorageUpdateForGroupsOrZones(), scxt::messaging::client::doMacroBeginEndEdit(), scxt::messaging::client::doMiscmodUpdate(), scxt::messaging::client::doPartSwapFX(), scxt::messaging::client::doRenameGroup(), scxt::messaging::client::doRenameZone(), scxt::messaging::client::doRequestZoneMapping(), scxt::sfz_support::exportSFZ(), Engine::getProcessorStorage(), scxt::patch_io::getSamplePathsFor(), SelectionManager::guaranteeSelectedLead(), SelectionManager::guaranteeSelectedLeadSomewhereIn(), scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), SelectionManager::ZoneAddress::isIn(), SelectionManager::ZoneAddress::isInPartGroup(), SelectionManager::ZoneAddress::isInWithPartials(), scxt::messaging::client::moveGroupTo(), scxt::messaging::client::moveZonesFromTo(), SCXTPlugin::paramsInfo(), Engine::prepareToPlay(), SCXTPlugin::process(), Part::process(), Engine::processAudio(), scxt::messaging::client::processMidiFromGUI(), Zone::processWithOS(), scxt::messaging::client::removeGroup(), scxt::messaging::client::removeSelectedZones(), scxt::messaging::client::removeZone(), scxt::engine::resolveMultiFileMissingWorkItem(), scxt::engine::resolveSingleFileMissingWorkItem(), GroupChangeItem::restore(), GroupRenameItem::restore(), scxt::patch_io::savePart(), SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForZonesBasedOnLead(), SelectionManager::sendGroupZoneMappingForSelectedPart(), SelectionManager::sendSelectedPartMacrosToClient(), scxt::messaging::client::setFullProcessorStorage(), Engine::MonoVoiceManagerResponder::setMIDI1CC(), Engine::MonoVoiceManagerResponder::setMIDIChannelPressure(), Engine::MonoVoiceManagerResponder::setMIDIPitchBend(), scxt::messaging::client::setProcessorType(), ZoneMappingDataUndoableItem::store(), GroupModRowChangeItem::store(), ZoneModRowChangeItem::store(), GroupChangeItem::store(), GroupRenameItem::store(), MacroFullStateItem::store(), GroupProcessorTypeChangeItem::store(), ZoneProcessorTypeChangeItem::store(), scxt::messaging::client::swapGroupProcessors(), scxt::messaging::client::swapZoneProcessors(), SelectionManager::transformSelectionActions(), scxt::json::unstreamPartState(), and Engine::~Engine().
getSampleManager()
const std::unique_ptr< sample::SampleManager > & getSampleManager () const
Referenced by scxt::messaging::client::clearPart(), scxt::engine::collectMissingResolutionWorkItems(), scxt::messaging::client::doPreviewBrowserSample(), scxt::messaging::client::doResolveMultiSample(), scxt::messaging::client::doResolveSample(), scxt::patch_io::getSamplePathsFor(), scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), Engine::loadCompoundElementIntoSelectedPartAndGroup(), scxt::messaging::client::removeGroup(), scxt::messaging::client::removeSelectedZones(), scxt::messaging::client::removeZone(), scxt::engine::resolveMultiFileMissingWorkItem(), scxt::engine::resolveSingleFileMissingWorkItem(), scxt::patch_io::saveMulti(), scxt::patch_io::savePart(), scxt::patch_io::saveSubSample(), Zone::setupOnUnstream(), and scxt::json::unstreamEngineState().
getBrowser()
const std::unique_ptr< browser::Browser > & getBrowser () const
Referenced by scxt::messaging::client::doAddBrowserDeviceLocation(), scxt::messaging::client::doReindexBrowserLocation(), and scxt::messaging::client::doRemoveBrowserDeviceLocation().
getStereoOutputs()
int getStereoOutputs () const
Audio processing.
setStereoOutputs()
void setStereoOutputs (int s)
Referenced by Engine::Engine().
processAudio()
bool processAudio ()
Process into an array of size stereoOutputs * 2 * blocksize.
Returns true if processing should continue
References scxt::messaging::audio::a2s_pointer_complete, scxt::messaging::audio::a2s_schedule_sample_purge, Engine::activeVoices, Engine::assertActiveVoiceCount(), Engine::SharedUIMemoryState::busVULevels, Engine::SharedUIMemoryState::cpuLevel, MessageController::AudioThreadCallback::exec(), Engine::forceVoiceUpdate, Engine::getMessageController(), Engine::getPatch(), AudioToSerialization::id, Engine::lastMidiNoteStateCounter, Engine::lastUpdateVoiceDisplayState, main(), Engine::midiNoteStateCounter, Engine::modifyStructureMutex, AudioToSerialization::NONE, AudioToSerialization::Payload::p, AudioToSerialization::payload, Engine::previewVoice, scxt::messaging::audio::s2a_dispatch_to_pointer, scxt::messaging::audio::s2a_dispatch_to_pointer_under_structurelock, scxt::messaging::audio::s2a_none, scxt::messaging::audio::s2a_param_beginendedit, scxt::messaging::audio::s2a_param_refresh, scxt::messaging::audio::s2a_param_set_value, SampleRateSupport::sampleRate, Engine::sendSamplePosition, Engine::sharedUIMemoryState, Engine::stopEngineRequests, Engine::updateTransportPhasors(), Engine::updateVoiceDisplayStateEvery, Engine::SharedUIMemoryState::voiceCount, Engine::SharedUIMemoryState::voiceDisplayItems, Engine::SharedUIMemoryState::voiceDisplayStateWriteCounter, and AudioToSerialization::VOID_STAR.
Referenced by SCXTPlugin::process().
onTransportUpdated()
void onTransportUpdated ()
Referenced by SCXTPlugin::process().
updateTransportPhasors()
void updateTransportPhasors ()
Referenced by Engine::processAudio().
processMIDI1Event()
void processMIDI1Event (uint16_t midiPort, const uint8_t data[3])
Midi-style events.
Each event is assumed to be at the top of the blockSize sample block
processNoteOnEvent()
void processNoteOnEvent (int16_t port, int16_t channel, int16_t key, int32_t note_id, double velocity, float retune)
processNoteOffEvent()
void processNoteOffEvent (int16_t port, int16_t channel, int16_t key, int32_t note_id, double velocity)
findZone()
size_t findZone (int16_t channel, int16_t key, int32_t noteId, int16_t velocity, std::array< pathToZone_t, maxVoices > & res)
References SCLOG_IF.
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction().
onPartConfigurationUpdated()
void onPartConfigurationUpdated ()
Referenced by Engine::Engine().
DECLARE_ENUM_STRING() [1/3]
DECLARE_ENUM_STRING (TuningMode)
DECLARE_ENUM_STRING() [2/3]
DECLARE_ENUM_STRING (TuningZoneResolution)
DECLARE_ENUM_STRING() [3/3]
DECLARE_ENUM_STRING (OmniFlavor)
resetTuningFromRuntimeConfig()
void resetTuningFromRuntimeConfig ()
References MidikeyRetuner::MTS_ESP, and MidikeyRetuner::TWELVE_TET.
Referenced by scxt::messaging::client::applyTuningStatusPayload().
setMpeTuningAwareness()
void setMpeTuningAwareness (bool a)
Referenced by scxt::messaging::client::applyMPETuningAwarenessPayload().
setPBTuningAwareness()
void setPBTuningAwareness (bool a)
Referenced by scxt::messaging::client::applyPitchBendTuningAwarenessPayload().
setOmniFlavor()
void setOmniFlavor (const OmniFlavor & of)
References Part::PartConfiguration::chPerOctaveChannel, Part::PartConfiguration::mpeChannel, and Part::PartConfiguration::omniChannel.
Referenced by scxt::messaging::client::applyOmniFlavorPayload().
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References scxt::dsp::pmSineTable.
zoneByPath()
const std::unique_ptr< Zone > & zoneByPath (const pathToZone_t & path) const
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction(), Engine::VoiceManagerResponder::initializeMultipleVoices(), and Engine::initiateVoice().
initiateVoice()
voice::Voice * initiateVoice (const pathToZone_t & path)
References Engine::activeVoices, Engine::pathToZone_t::channel, Engine::pathToZone_t::key, Engine::nextVoiceCreationId, Engine::pathToZone_t::noteid, SampleRateSupport::sampleRate, SampleRateSupport::sampleRateInv, SCD, SCLOG_IF, and Engine::zoneByPath().
Referenced by Engine::VoiceManagerResponder::initializeMultipleVoices().
releaseVoice()
void releaseVoice (int16_t channel, int16_t key, int32_t noteid, int32_t releaseVelocity)
References SCLOG_IF.
immediatelyTerminateAllVoices()
void immediatelyTerminateAllVoices ()
References Engine::forceVoiceUpdate.
Referenced by scxt::messaging::client::doUnstreamEngineState(), scxt::patch_io::initFromResourceBundle(), and scxt::patch_io::loadMulti().
assertActiveVoiceCount()
void assertActiveVoiceCount ()
References Engine::activeVoices.
Referenced by Engine::processAudio().
getMessageController()
const std::unique_ptr< messaging::MessageController > & getMessageController () const
Referenced by scxt::patch_io::addMonolithBinaries(), UndoManager::applyRedoStep(), scxt::messaging::client::applyTuningStatusPayload(), UndoManager::applyUndoStep(), scxt::messaging::client::clearPart(), scxt::patch_io::collectSamplesInto(), SelectionManager::configureAndSendZoneOrGroupModMatrixMetadata(), SelectionManager::copyZoneOrGroupProcessorLeadToAll(), scxt::messaging::client::doBrowserQueueRefresh(), scxt::messaging::client::doMiscmodUpdate(), scxt::messaging::client::doMuteOrSoloGroup(), scxt::messaging::client::doRenameZone(), scxt::messaging::client::doRequestZoneMapping(), scxt::messaging::client::doUnstreamEngineState(), MessageController::AudioThreadCallback::exec(), MessageController::AudioThreadCallback::execCompleteOnSer(), scxt::sfz_support::exportSFZ(), scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), scxt::patch_io::initFromResourceBundle(), scxt::patch_io::loadMulti(), scxt::patch_io::loadPartInto(), scxt::messaging::client::moveGroupTo(), scxt::messaging::client::moveZonesFromTo(), scxt::patch_io::onlyCollect(), SCXTPlugin::process(), Engine::processAudio(), scxt::messaging::client::removeGroup(), scxt::messaging::client::removeSelectedZones(), scxt::messaging::client::removeZone(), scxt::engine::resolveMultiFileMissingWorkItem(), scxt::engine::resolveSingleFileMissingWorkItem(), GroupChangeItem::restore(), GroupRenameItem::restore(), MacroFullStateItem::restore(), ZoneModRowChangeItem::restore(), GroupModRowChangeItem::restore(), ZoneProcessorTypeChangeItem::restore(), GroupProcessorTypeChangeItem::restore(), ZoneMappingDataUndoableItem::restore(), scxt::patch_io::saveMulti(), scxt::patch_io::savePart(), Bus::sendBusEffectInfoToClient(), Part::sendBusEffectInfoToClient(), Bus::sendBusSendStorageToClient(), SelectionManager::sendClientDataForLeadSelectionState(), SelectionManager::sendDisplayDataForGroupsBasedOnLead(), SelectionManager::sendDisplayDataForNoGroupSelected(), SelectionManager::sendDisplayDataForNoZoneSelected(), SelectionManager::sendDisplayDataForZonesBasedOnLead(), SelectionManager::sendGroupZoneMappingForSelectedPart(), SelectionManager::sendOtherTabsSelectionToClient(), SelectionManager::sendSelectedPartMacrosToClient(), SelectionManager::sendSelectedZonesToClient(), scxt::messaging::client::setFullProcessorStorage(), scxt::messaging::client::setProcessorType(), Zone::setupOnUnstream(), SCXTPlugin::stateLoad(), SCXTPlugin::synchronousEngineUnstream(), and MessageController::updateClientActivityNotification().
getSelectionManager()
const std::unique_ptr< selection::SelectionManager > & getSelectionManager () const
Referenced by scxt::messaging::client::clearPart(), scxt::messaging::client::CLIENT_TO_SERIAL_CONSTRAINED(), scxt::messaging::client::CLIENT_TO_SERIAL_CONSTRAINED(), scxt::messaging::client::copyProcessorLeadToAll(), scxt::messaging::client::doApplySelectActions(), scxt::messaging::client::doApplyZoneDelta(), scxt::messaging::client::doBeginEndEdit(), scxt::messaging::client::doClearVariantAmplitudeNormalization(), scxt::messaging::client::doDebugAction(), scxt::messaging::client::doDeleteVariant(), scxt::messaging::client::doFullAdsrStorageUpdateForGroupsOrZones(), scxt::messaging::client::doFullModStorageUpdateForGroupsOrZones(), scxt::messaging::client::doMiscmodUpdate(), scxt::messaging::client::doMuteOrSoloGroup(), scxt::messaging::client::doNormalizeVariantAmplitude(), scxt::messaging::client::doRequestZoneDataRefresh(), scxt::messaging::client::doSavePart(), scxt::messaging::client::doUpdateGroupOutputInfoMidiChannel(), scxt::messaging::client::doUpdateGroupOutputInfoPolyphony(), scxt::messaging::client::doUpdateGroupRoutingRow(), scxt::messaging::client::doUpdateGroupTriggerConditions(), scxt::messaging::client::doUpdateLeadZoneMapping(), scxt::messaging::client::doUpdateLeadZoneSingleVariant(), scxt::messaging::client::doUpdateOtherTabSelection(), scxt::messaging::client::doUpdateZoneRoutingRow(), scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), Engine::loadCompoundElementIntoZone(), Engine::loadSampleIntoZone(), scxt::messaging::client::moveZonesFromTo(), scxt::messaging::client::processMidiFromGUI(), scxt::messaging::client::removeGroup(), scxt::messaging::client::removeSelectedZones(), scxt::messaging::client::removeZone(), scxt::messaging::client::setFullProcessorStorage(), scxt::messaging::client::setProcessorType(), ZoneMappingDataUndoableItem::store(), scxt::messaging::client::swapGroupProcessors(), scxt::messaging::client::swapZoneProcessors(), scxt::messaging::client::detail::updateGroupIndexedMemberValue(), scxt::messaging::client::detail::updateGroupMemberValue(), scxt::messaging::client::detail::updateZoneIndexedMemberValue(), scxt::messaging::client::detail::updateZoneLeadMemberValue(), and scxt::messaging::client::detail::updateZoneMemberValue().
prepareToPlay()
void prepareToPlay (double sampleRate)
Prepare to play sets up the internal state to prepare us to play.
Call it in your interfaces pre-playing once.
References Engine::getPatch(), Engine::lastUpdateVoiceDisplayState, SampleRateSupport::sampleRate, SampleRateSupport::samplerate, SampleRateSupport::setSampleRate(), Engine::sharedUIMemoryState, Engine::updateVoiceDisplayStateEvery, and Engine::SharedUIMemoryState::voiceDisplayStateWriteCounter.
Referenced by SCXTPlugin::activate().
loadSampleIntoSelectedPartAndGroup() [1/2]
void loadSampleIntoSelectedPartAndGroup (const fs::path & p, int16_t rootKey, KeyboardRange krange, VelocityRange vrange, bool sampleRangeInfoOverridesArguments = false)
References scxt::extensionMatches(), scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), scxt::gig_support::importGIG(), scxt::multisample_support::importMultisample(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), scxt::patch_io::loadMulti(), scxt::patch_io::loadPartInto(), and scxt::messaging::client::s2c_send_pgz_structure.
Referenced by scxt::messaging::client::addSample(), scxt::messaging::client::addSampleWithRange(), and Engine::loadSampleIntoSelectedPartAndGroup().
loadSampleIntoSelectedPartAndGroup() [2/2]
void loadSampleIntoSelectedPartAndGroup (const fs::path & p)
References Engine::loadSampleIntoSelectedPartAndGroup().
loadCompoundElementIntoSelectedPartAndGroup()
void loadCompoundElementIntoSelectedPartAndGroup (const scxt::sample::compound::CompoundElement & p, int16_t rootKey = 60, KeyboardRange krange = {48, 72}, VelocityRange vrange = {0, 127})
References CompoundElement::emsg, CompoundElement::ERROR_SENTINEL, scxt::extensionMatches(), Engine::getPartGroupZoneStructure(), Engine::getSampleManager(), scxt::akai_support::importAKP(), scxt::gig_support::importGIG(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), CompoundElement::INSTRUMENT, CompoundElement::name, Sample::SampleFileAddress::path, Sample::SampleFileAddress::preset, scxt::messaging::client::s2c_send_pgz_structure, and CompoundElement::sampleAddress.
Referenced by scxt::messaging::client::addCompoundElementWithRange().
loadSampleIntoZone()
void loadSampleIntoZone (const fs::path & p, int16_t part, int16_t group, int16_t zone, int variantID)
References Zone::ENDPOINTS, scxt::extensionMatches(), Engine::getSelectionManager(), and Zone::LOOP.
Referenced by scxt::messaging::client::addSampleInZone().
loadCompoundElementIntoZone()
void loadCompoundElementIntoZone (const sample::compound::CompoundElement & p, int16_t part, int16_t group, int16_t zone, int variantID)
References CompoundElement::emsg, Zone::ENDPOINTS, CompoundElement::ERROR_SENTINEL, Engine::getSelectionManager(), Zone::LOOP, CompoundElement::name, Sample::SampleFileAddress::path, and CompoundElement::sampleAddress.
Referenced by scxt::messaging::client::addCompoundElementInZone().
createEmptyZone()
void createEmptyZone (int part, int group, KeyboardRange krange = {48, 72}, VelocityRange vrange = {0, 127})
References KeyboardRange::keyEnd, and KeyboardRange::keyStart.
Referenced by scxt::messaging::client::doAddBlankZone().
duplicateZone()
void duplicateZone (const selection::SelectionManager::ZoneAddress & s)
References SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, and SelectionManager::ZoneAddress::zone.
copyZone()
void copyZone (const selection::SelectionManager::ZoneAddress & s)
References SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, scxt::messaging::client::s2c_send_clipboard_type, scxt::messaging::client::serializationSendToClient(), and SelectionManager::ZoneAddress::zone.
pasteZone()
void pasteZone (const selection::SelectionManager::ZoneAddress & a)
References SelectionManager::ZoneAddress::group, and SelectionManager::ZoneAddress::part.
sendMetadataToClient()
void sendMetadataToClient () const
References scxt::dsp::processor::getAllProcessorDescriptions(), scxt::messaging::client::s2c_send_all_processor_descriptions, and scxt::messaging::client::serializationSendToClient().
sendFullRefreshToClient()
void sendFullRefreshToClient () const
References scxt::engine::collectMissingResolutionWorkItems(), SelectionManager::SelectActionContents::distinct, scxt::messaging::client::s2c_send_missing_resolution_workitem_list, scxt::messaging::client::s2c_send_part_configuration, scxt::messaging::client::s2c_send_pgz_structure, scxt::messaging::client::s2c_send_tuning_status, scxt::messaging::client::s2c_update_macro_full_state, scxt::messaging::client::s2c_update_mpe_tuning_awareness, scxt::messaging::client::s2c_update_omni_flavor, scxt::messaging::client::s2c_update_pitchbend_tuning_awareness, and scxt::messaging::client::serializationSendToClient().
Referenced by scxt::messaging::client::doRegisterClient(), scxt::messaging::client::doResendFullState(), scxt::messaging::client::doResetEngine(), scxt::messaging::client::doResolveMultiSample(), scxt::messaging::client::doResolveSample(), GroupChangeItem::restore(), scxt::json::unstreamEngineState(), and scxt::json::unstreamPartState().
sendEngineStatusToClient()
void sendEngineStatusToClient () const
References Engine::EngineStatusMessage::isAudioRunning, Engine::EngineStatusMessage::runningEnvironment, scxt::messaging::client::s2c_engine_status, Engine::EngineStatusMessage::sampleRate, and scxt::messaging::client::serializationSendToClient().
clearAll()
void clearAll (bool purgeSamples = true)
Referenced by scxt::json::unstreamEngineState().
getProcessorStorage()
const std::optional< dsp::processor::ProcessorStorage > getProcessorStorage (const processorAddress_t & addr) const
References Engine::getPatch(), and scxt::engine::processorCount.
getPartGroupZoneStructure()
Engine::pgzStructure_t getPartGroupZoneStructure () const
Get the Part/Group/Zone structure as a set o fzone addreses.
A part with no groups will be (p,-1,-1); a group with no zones will be (p,g,-1).
Returns
The vector of zones in the running engine independent of selection.
References scxt::engine::MISSING_SAMPLE, scxt::engine::MUTED, and SCLOG_IF.
Referenced by scxt::messaging::client::clearPart(), scxt::messaging::client::doMuteOrSoloGroup(), scxt::messaging::client::doRenameGroup(), scxt::messaging::client::doRenameZone(), Engine::loadCompoundElementIntoSelectedPartAndGroup(), scxt::messaging::client::moveGroupTo(), scxt::messaging::client::moveZonesFromTo(), scxt::messaging::client::pgzSerialSide(), scxt::messaging::client::removeGroup(), scxt::messaging::client::removeSelectedZones(), scxt::messaging::client::removeZone(), and GroupRenameItem::restore().
getMemoryPool()
const std::unique_ptr< MemoryPool > & getMemoryPool ()
Referenced by Voice::initializeProcessors(), and Voice::processWithOS().
registerVoiceModTarget()
void registerVoiceModTarget (const voice::modulation::MatrixConfig::TargetIdentifier & t, vmodTgtStrFn_t pathFn, vmodTgtStrFn_t nameFn, vmodTgtIntFn_t additiveFn, vmodTgtBoolFn_t enabledFn = [](const auto &, const auto &) { return true; })
Referenced by MatrixEndpoints::registerVoiceModTarget().
registerVoiceModSource()
void registerVoiceModSource (const voice::modulation::MatrixConfig::SourceIdentifier & t, vmodSrcStrFn_t pathFn, vmodSrcStrFn_t nameFn)
Referenced by MatrixEndpoints::registerVoiceModSource().
registerGroupModTarget()
void registerGroupModTarget (const modulation::GroupMatrixConfig::TargetIdentifier & t, gmodTgtStrFn_t pathFn, gmodTgtStrFn_t nameFn, gmodTgtIntFn_t additiveFn, gmodTgtBoolFn_t enabledFn = [](const auto &, const auto &) { return true; })
Referenced by GroupMatrixEndpoints::registerGroupModTarget().
registerGroupModSource()
void registerGroupModSource (const modulation::GroupMatrixConfig::SourceIdentifier & t, gmodSrcStrFn_t pathFn, gmodSrcStrFn_t nameFn)
Referenced by GroupMatrixEndpoints::registerGroupModSource().
remapZonesToNewSample()
void remapZonesToNewSample (const SampleID & oldId, const SampleID & newId, int forPart)
terminateVoicesForZone()
void terminateVoicesForZone (Zone & z)
References Zone::terminateAllVoices().
terminateVoicesForGroup()
void terminateVoicesForGroup (Group & g)
setMacro01ValueFromPlugin()
void setMacro01ValueFromPlugin (int part, int index, float value01)
References scxt::messaging::audio::a2s_macro_updated, AudioToSerialization::Payload::i, AudioToSerialization::id, AudioToSerialization::INT, and AudioToSerialization::payload.
setupUserStorageDirectory()
std::optional< fs::path > setupUserStorageDirectory ()
References SCLOG_IF.
Referenced by Engine::Engine().
prepareToStream()
void prepareToStream ()
Referenced by scxt::patch_io::saveMulti(), scxt::patch_io::savePart(), and SCXTPlugin::stateSave().
Member Data Documentation
id
EngineID id
defaults
std::unique_ptr<infrastructure::DefaultsProvider> defaults
Referenced by Engine::Engine().
runningEnvironment
std::string runningEnvironment {"Unknown"}
An option to add a description of your running environment, like "VST3 in Reaper".
transport
sst::basic_blocks::modulators::Transport transport
Referenced by Voice::initializeProcessors(), Group::onProcessorTypeChanged(), SCXTPlugin::process(), Voice::processWithOS(), Group::processWithOS(), Group::resetLFOs(), Config::temposyncRatio(), Voice::updateTransportPhasors(), and Voice::voiceStarted().
midikeyRetuner
tuning::MidikeyRetuner midikeyRetuner
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction(), Voice::calculateVoicePitch(), Part::getChannelBasedTransposition(), and Voice::voiceStarted().
runtimeConfig
struct scxt::engine::Engine::RuntimeConfig runtimeConfig
Referenced by scxt::messaging::client::applyTuningStatusPayload(), Voice::calculateVoicePitch(), Engine::Engine(), and Voice::voiceStarted().
NONE
enum scxt::engine::Engine::MidiZoneAction NONE
this [1/2]
struct scxt::engine::Engine::VoiceManagerResponder* this
this [2/2]
struct scxt::engine::Engine::MonoVoiceManagerResponder* this
voiceManager
voiceManager_t voiceManager {voiceManagerResponder, monoVoiceManagerResponder}
Referenced by GTKeyswitchMomentary::groupShouldPlay(), Group::processWithOS(), Group::resetPolyAndPlaymode(), and scxt::messaging::client::stopSoundsMessage().
activeVoices
std::atomic<uint32_t> activeVoices {0}
Referenced by Engine::assertActiveVoiceCount(), Voice::cleanupVoice(), Engine::initiateVoice(), and Engine::processAudio().
nextVoiceCreationId
uint64_t nextVoiceCreationId {1}
Referenced by Engine::initiateVoice().
previewVoice
std::unique_ptr<voice::PreviewVoice> previewVoice
Referenced by Engine::Engine(), and Engine::processAudio().
modifyStructureMutex
std::mutex modifyStructureMutex
This is a mutex which we lock when modifying the structure in the engine.
The structure will only be modified in one of two situations
On the audio thread (wav load for instance)
On the serialization thread after the audio thread has been paused (which is how we do SFZ)
As a result this mutex needs to be locked when serialization reads the structure or when engine changes it but not when engine traverses it so note on and the like can avoid a mutex lock.
Referenced by Engine::processAudio().
sharedUIMemoryState
struct scxt::engine::Engine::SharedUIMemoryState sharedUIMemoryState
Referenced by Engine::prepareToPlay(), and Engine::processAudio().
isFullEngineUnstream
thread_local bool isFullEngineUnstream {false} static
Referenced by Engine::UnstreamGuard::UnstreamGuard(), and Engine::UnstreamGuard::~UnstreamGuard().
streamReason
thread_local Engine::StreamReason streamReason {StreamReason::IN_PROCESS} static
Referenced by Engine::StreamGuard::StreamGuard(), and Engine::StreamGuard::~StreamGuard().
fullEngineUnstreamStreamingVersion
thread_local uint64_t fullEngineUnstreamStreamingVersion {0} static
Referenced by Engine::UnstreamGuard::UnstreamGuard(), and Engine::UnstreamGuard::~UnstreamGuard().
updateVoiceDisplayStateEvery
int32_t updateVoiceDisplayStateEvery {10000000}
The VoiceDisplayState structure is updated at some relatively low (like 30hz) frequency by the engine for communication to a potential client if the message controller has a client connected.
Updates will occur only if the read pointer and write pointer are the same so the client needs to update the write pointer.
Referenced by Engine::prepareToPlay(), and Engine::processAudio().
lastUpdateVoiceDisplayState
int32_t lastUpdateVoiceDisplayState {0}
Referenced by Engine::prepareToPlay(), and Engine::processAudio().
midiNoteStateCounter
int64_t midiNoteStateCounter {0}
Referenced by Engine::VoiceManagerResponder::initializeMultipleVoices(), and Engine::processAudio().
lastMidiNoteStateCounter
int64_t lastMidiNoteStateCounter {0}
Referenced by Engine::processAudio().
forceVoiceUpdate
bool forceVoiceUpdate {false}
Referenced by Engine::immediatelyTerminateAllVoices(), and Engine::processAudio().
sendSamplePosition
bool sendSamplePosition {true}
Referenced by Engine::processAudio().
rng
sst::basic_blocks::dsp::RNG rng
Referenced by Part::addGroup(), Engine::Engine(), Engine::VoiceManagerResponder::initializeMultipleVoices(), Config::rand01(), Group::resetLFOs(), and Voice::voiceStarted().
clipboard
Clipboard clipboard
stopEngineRequests
std::atomic<int32_t> stopEngineRequests {0}
Referenced by scxt::messaging::client::doUnstreamEngineState(), Engine::processAudio(), MessageController::restartAudioThreadFromSerial(), and MessageController::stopAudioThreadThenRunOnSerial().
voiceModTargets
std::unordered_map<voice::modulation::MatrixConfig::TargetIdentifier, std::tuple<vmodTgtStrFn_t, vmodTgtStrFn_t, vmodTgtIntFn_t, vmodTgtBoolFn_t> > voiceModTargets
Referenced by scxt::voice::modulation::getVoiceMatrixMetadata().
groupModTargets
std::unordered_map<modulation::GroupMatrixConfig::TargetIdentifier, std::tuple<gmodTgtStrFn_t, gmodTgtStrFn_t, gmodTgtIntFn_t, gmodTgtBoolFn_t> > groupModTargets
Referenced by scxt::modulation::getGroupMatrixMetadata().
voiceModSources
std::unordered_map<voice::modulation::MatrixConfig::SourceIdentifier, std::pair<vmodSrcStrFn_t, vmodSrcStrFn_t> > voiceModSources
Referenced by scxt::voice::modulation::getVoiceMatrixMetadata().
groupModSources
std::unordered_map<modulation::GroupMatrixConfig::SourceIdentifier, std::pair<gmodSrcStrFn_t, gmodSrcStrFn_t> > groupModSources
Referenced by scxt::modulation::getGroupMatrixMetadata().
undoManager
undo::UndoManager undoManager
Referenced by scxt::messaging::client::doBeginZoneMappingModification(), scxt::messaging::client::doMacroBeginEndEdit(), scxt::messaging::client::doRedo(), scxt::messaging::client::doRenameGroup(), scxt::messaging::client::doUndo(), scxt::messaging::client::doUpdateGroupRoutingRow(), scxt::messaging::client::doUpdateZoneRoutingRow(), scxt::messaging::client::setProcessorType(), and scxt::messaging::client::updateMacroFullState().
The documentation for this struct was generated from the following files:
engine.h
engine.cpp