shortcircuit-xt: MidikeyRetuner Struct Reference
MidikeyRetuner Struct Reference
#include <midikey_retuner.h>
Public Types
enum TuningMode { TWELVE_TET , MTS_ESP }
Public Member Functions
MidikeyRetuner ()
~MidikeyRetuner ()
void setTuningMode (TuningMode)
int getRepetitionInterval () const
float offsetKeyBy (int channel, int key)
int remapKeyTo (int channel, int key)
float retuneRemappedKey (int channel, int key, int preRemappedKey)
Public Attributes
enum scxt::tuning::MidikeyRetuner::TuningMode TWELVE_TET
Member Enumeration Documentation
TuningMode
enum TuningMode
Enumerator
TWELVE_TET
MTS_ESP
Constructor & Destructor Documentation
MidikeyRetuner()
MidikeyRetuner ()
References MidikeyRetuner::MTS_ESP.
~MidikeyRetuner()
~MidikeyRetuner ()
Member Function Documentation
setTuningMode()
void setTuningMode (TuningMode tm)
getRepetitionInterval()
int getRepetitionInterval () const
References MidikeyRetuner::MTS_ESP, and MidikeyRetuner::TWELVE_TET.
Referenced by Part::getChannelBasedTransposition().
offsetKeyBy()
float offsetKeyBy (int channel, int key)
References MidikeyRetuner::MTS_ESP, and MidikeyRetuner::TWELVE_TET.
Referenced by MidikeyRetuner::remapKeyTo(), and MidikeyRetuner::retuneRemappedKey().
remapKeyTo()
int remapKeyTo (int channel, int key)
References MidikeyRetuner::offsetKeyBy().
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction().
retuneRemappedKey()
float retuneRemappedKey (int channel, int key, int preRemappedKey)
References MidikeyRetuner::offsetKeyBy().
Referenced by Voice::calculateVoicePitch(), and Voice::voiceStarted().
Member Data Documentation
TWELVE_TET
enum scxt::tuning::MidikeyRetuner::TuningMode TWELVE_TET
Referenced by MidikeyRetuner::getRepetitionInterval(), MidikeyRetuner::offsetKeyBy(), and Engine::resetTuningFromRuntimeConfig().
The documentation for this struct was generated from the following files:
midikey_retuner.h
midikey_retuner.cpp