shortcircuit-xt: SCMonolithSampleReader Struct Reference
SCMonolithSampleReader Struct Reference
#include <patch_io.h>
Classes
struct SampleData
Public Member Functions
SCMonolithSampleReader (RIFF::File *f)
~SCMonolithSampleReader ()
size_t getSampleCount ()
bool getSampleData (size_t index, SampleData &data)
void resetErrorString ()
void addError (const std::string &msg)
std::string getErrorString () const
Constructor & Destructor Documentation
SCMonolithSampleReader()
SCMonolithSampleReader (RIFF::File * f)
References scxt::patch_io::readSCManifest().
~SCMonolithSampleReader()
~SCMonolithSampleReader ()
Member Function Documentation
getSampleCount()
size_t getSampleCount ()
getSampleData()
bool getSampleData (size_t index, SampleData & data)
References SCMonolithSampleReader::addError(), SCMonolithSampleReader::SampleData::data, and SCMonolithSampleReader::SampleData::filename.
resetErrorString()
void resetErrorString ()
addError()
void addError (const std::string & msg)
Referenced by SCMonolithSampleReader::getSampleData().
getErrorString()
std::string getErrorString () const
The documentation for this struct was generated from the following files:
patch_io.h
patch_io.cpp