shortcircuit-xt: RandomEvaluator Struct Reference
RandomEvaluator Struct Reference
#include <random_evaluator.h>
Public Member Functions
void evaluate (sst::basic_blocks::dsp::RNG &rng, const modulation::MiscSourceStorage &rs)
Public Attributes
std::array< float, scxt::randomsPerGroupOrZone > outputs
Member Function Documentation
evaluate()
void evaluate (sst::basic_blocks::dsp::RNG & rng, const modulation::MiscSourceStorage & rs)
References RandomStorage::HALF_NORMAL, RandomStorage::NORMAL, RandomEvaluator::outputs, MiscSourceStorage::randoms, RandomStorage::UNIFORM_01, and RandomStorage::UNIFORM_BIPOLAR.
Referenced by Group::attack(), Group::resetLFOs(), and Voice::voiceStarted().
Member Data Documentation
outputs
std::array<float, scxt::randomsPerGroupOrZone> outputs
Referenced by GroupMatrixEndpoints::Sources::bind(), MatrixEndpoints::Sources::bind(), and RandomEvaluator::evaluate().
The documentation for this struct was generated from the following file:
random_evaluator.h