shortcircuit-xt: PartSidebar Struct Reference
PartSidebar Struct Reference
Public Member Functions
PartSidebar (PartGroupSidebar *p)
void resetParts ()
void visibilityChanged () override
void resized () override
void restackForActive ()
bool isInterestedInFileDrag (const juce::StringArray &files) override
int partAtPosition (int x, int y) const
void showSampleWarn ()
void updateDragFromSource (const shared::SampleDropSource &src, int x, int y)
void clearAllDragState ()
void fileDragEnter (const juce::StringArray &files, int x, int y) override
void fileDragMove (const juce::StringArray &files, int x, int y) override
void fileDragExit (const juce::StringArray &) override
void filesDropped (const juce::StringArray &files, int x, int y) override
bool isInterestedInDragSource (const SourceDetails &sd) override
void itemDragEnter (const SourceDetails &sd) override
void itemDragMove (const SourceDetails &sd) override
void itemDragExit (const SourceDetails &) override
void itemDropped (const SourceDetails &sd) override
void paintOverChildren (juce::Graphics &g) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
PartGroupSidebar * partGroupSidebar {nullptr}
std::unique_ptr< jcmp::Viewport > viewport
std::unique_ptr< juce::Component > viewportContents
std::array< std::unique_ptr< shared::PartSidebarCard >, scxt::numParts > parts
std::unique_ptr< jcmp::TextPushButton > addPartButton
bool tallMode {false}
std::unique_ptr< sst::jucegui::util::VisibilityParentWatcher > psbw
bool scmDragActive {false}
juce::String scmDragFileName
bool sampleWarnActive {false}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
PartSidebar()
PartSidebar (PartGroupSidebar * p)
References PartSidebar::addPartButton, SCXTEditor::defaultsProvider, HasEditor::editor, PartSidebar::parts, scxt::infrastructure::partSidebarPartExpanded, PartSidebar::psbw, PartSidebar::tallMode, PartSidebar::viewport, and PartSidebar::viewportContents.
Member Function Documentation
resetParts()
void resetParts ()
References PartSidebar::parts, PartSidebar::resized(), and PartSidebar::tallMode.
Referenced by PartSidebar::visibilityChanged().
visibilityChanged()
void visibilityChanged () override
References SCXTEditor::defaultsProvider, HasEditor::editor, scxt::infrastructure::partSidebarPartExpanded, PartSidebar::resetParts(), and PartSidebar::tallMode.
resized()
void resized () override
References PartSidebar::addPartButton, PartSidebarCard::height, PartSidebar::parts, PartSidebarCard::tallHeight, PartSidebar::tallMode, PartSidebar::viewport, PartSidebar::viewportContents, and PartSidebarCard::width.
Referenced by PartSidebar::resetParts(), and PartSidebar::restackForActive().
restackForActive()
void restackForActive ()
References PartSidebar::addPartButton, HasEditor::editor, SCXTEditor::partConfigurations, PartSidebar::parts, and PartSidebar::resized().
isInterestedInFileDrag()
bool isInterestedInFileDrag (const juce::StringArray & files) override
References Browser::isLoadableMultiSample(), and Browser::isLoadableSingleSample().
partAtPosition()
int partAtPosition (int x, int y) const
References PartSidebar::parts, and PartSidebar::viewport.
Referenced by PartSidebar::filesDropped(), PartSidebar::itemDropped(), and PartSidebar::updateDragFromSource().
showSampleWarn()
void showSampleWarn ()
References PartSidebar::parts, PartSidebar::sampleWarnActive, and PartSidebar::scmDragActive.
Referenced by PartSidebar::fileDragEnter(), PartSidebar::fileDragMove(), PartSidebar::itemDragEnter(), PartSidebar::itemDragMove(), and PartSidebar::updateDragFromSource().
updateDragFromSource()
void updateDragFromSource (const shared::SampleDropSource & src, int x, int y)
References SampleDropSource::displayName, SampleDropSource::isNone(), SampleDropSource::isPartFile(), SampleDropSource::isSingleSample(), PartSidebar::partAtPosition(), PartSidebar::parts, PartSidebar::sampleWarnActive, PartSidebar::scmDragActive, PartSidebar::scmDragFileName, PartSidebar::showSampleWarn(), SampleDropSource::showsFullSidebarHighlight(), SampleDropSource::showsReplaceSplit(), and PartSidebar::viewport.
Referenced by PartSidebar::fileDragEnter(), PartSidebar::fileDragMove(), PartSidebar::itemDragEnter(), and PartSidebar::itemDragMove().
clearAllDragState()
void clearAllDragState ()
References PartSidebar::parts, PartSidebar::sampleWarnActive, and PartSidebar::scmDragActive.
Referenced by PartSidebar::fileDragExit(), PartSidebar::filesDropped(), PartSidebar::itemDragExit(), and PartSidebar::itemDropped().
fileDragEnter()
void fileDragEnter (const juce::StringArray & files, int x, int y) override
References SampleDropSource::fromPath(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
fileDragMove()
void fileDragMove (const juce::StringArray & files, int x, int y) override
References SampleDropSource::fromPath(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
fileDragExit()
void fileDragExit (const juce::StringArray &) override
References PartSidebar::clearAllDragState().
filesDropped()
void filesDropped (const juce::StringArray & files, int x, int y) override
References PartSidebar::clearAllDragState(), SampleDropSource::dropOnPart(), SampleDropSource::fromPath(), SampleDropSource::isMultiFile(), SampleDropSource::isNone(), SampleDropSource::isSingleSample(), PartSidebar::partAtPosition(), PartSidebar::parts, SampleDropSource::showsReplaceSplit(), and PartSidebar::viewport.
isInterestedInDragSource()
bool isInterestedInDragSource (const SourceDetails & sd) override
itemDragEnter()
void itemDragEnter (const SourceDetails & sd) override
References SampleDropSource::fromBrowserItem(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
itemDragMove()
void itemDragMove (const SourceDetails & sd) override
References SampleDropSource::fromBrowserItem(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
itemDragExit()
void itemDragExit (const SourceDetails &) override
References PartSidebar::clearAllDragState().
itemDropped()
void itemDropped (const SourceDetails & sd) override
References PartSidebar::clearAllDragState(), SampleDropSource::fromBrowserItem(), PartSidebar::partAtPosition(), PartSidebar::parts, and PartSidebar::viewport.
paintOverChildren()
void paintOverChildren (juce::Graphics & g) override
References ColorMap::accent_1b, ColorMap::bg_1, HasEditor::editor, ColorMap::generic_content_high, SCXTEditor::occludeRegionWithText(), PartSidebar::sampleWarnActive, PartSidebar::scmDragActive, PartSidebar::scmDragFileName, PartSidebar::viewport, and ColorMap::warning_1b.
Member Data Documentation
partGroupSidebar
PartGroupSidebar* partGroupSidebar {nullptr}
viewport
std::unique_ptr<jcmp::Viewport> viewport
Referenced by PartSidebar::filesDropped(), PartSidebar::itemDropped(), PartSidebar::paintOverChildren(), PartSidebar::partAtPosition(), PartSidebar::PartSidebar(), PartSidebar::resized(), and PartSidebar::updateDragFromSource().
viewportContents
std::unique_ptr<juce::Component> viewportContents
Referenced by PartSidebar::PartSidebar(), and PartSidebar::resized().
parts
std::array<std::unique_ptr<shared::PartSidebarCard>, scxt::numParts> parts
Referenced by PartSidebar::clearAllDragState(), PartSidebar::filesDropped(), PartSidebar::itemDropped(), PartSidebar::partAtPosition(), PartSidebar::PartSidebar(), PartSidebar::resetParts(), PartSidebar::resized(), PartSidebar::restackForActive(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
addPartButton
std::unique_ptr<jcmp::TextPushButton> addPartButton
Referenced by PartSidebar::PartSidebar(), PartSidebar::resized(), and PartSidebar::restackForActive().
tallMode
bool tallMode {false}
Referenced by PartSidebar::PartSidebar(), PartSidebar::resetParts(), PartSidebar::resized(), and PartSidebar::visibilityChanged().
psbw
std::unique_ptr<sst::jucegui::util::VisibilityParentWatcher> psbw
Referenced by PartSidebar::PartSidebar().
scmDragActive
bool scmDragActive {false}
Referenced by PartSidebar::clearAllDragState(), PartSidebar::paintOverChildren(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
scmDragFileName
juce::String scmDragFileName
Referenced by PartSidebar::paintOverChildren(), and PartSidebar::updateDragFromSource().
sampleWarnActive
bool sampleWarnActive {false}
Referenced by PartSidebar::clearAllDragState(), PartSidebar::paintOverChildren(), PartSidebar::showSampleWarn(), and PartSidebar::updateDragFromSource().
The documentation for this struct was generated from the following file:
PartGroupSidebar.cpp