shortcircuit-xt: MessageController::AudioThreadCallback Struct Reference
MessageController::AudioThreadCallback Struct Reference
#include <messaging.h>
Public Member Functions
void setFunction (std::function< void(engine::Engine &)> &to)
void setSerialCompleteFunction (std::function< void(const engine::Engine &)> &q)
void nullSerialCompleteFunction ()
void exec (engine::Engine &e)
void execCompleteOnSer (const engine::Engine &e)
Member Function Documentation
setFunction()
void setFunction (std::function< void(engine::Engine &)> & to)
setSerialCompleteFunction()
void setSerialCompleteFunction (std::function< void(const engine::Engine &)> & q)
nullSerialCompleteFunction()
void nullSerialCompleteFunction ()
exec()
void exec (engine::Engine & e)
References Engine::getMessageController().
Referenced by Engine::processAudio().
execCompleteOnSer()
void execCompleteOnSer (const engine::Engine & e)
References Engine::getMessageController().
The documentation for this struct was generated from the following file:
messaging.h