shortcircuit-xt: AboutLink Struct Reference
AboutLink Struct Reference
Public Member Functions
AboutLink (SCXTEditor *e, const std::string &url, const std::string tx)
void mouseEnter (const juce::MouseEvent &event) override
void mouseExit (const juce::MouseEvent &event) override
void mouseDown (const juce::MouseEvent &event) override
void paint (juce::Graphics &g) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::string url
std::string txt
bool isHovered {false}
juce::Font font {juce::FontOptions()}
theme::ColorMap::Colors hoverColor {theme::ColorMap::accent_2a}
theme::ColorMap::Colors displayColor {theme::ColorMap::generic_content_medium}
std::function< void()> onClick {nullptr}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
AboutLink()
AboutLink (SCXTEditor * e, const std::string & url, const std::string tx)
References HasEditor::editor, AboutLink::font, ThemeApplier::interLightFor(), and SCXTEditor::themeApplier.
Member Function Documentation
mouseEnter()
void mouseEnter (const juce::MouseEvent & event) override
References AboutLink::isHovered.
mouseExit()
void mouseExit (const juce::MouseEvent & event) override
References AboutLink::isHovered.
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References AboutLink::onClick, and AboutLink::url.
paint()
void paint (juce::Graphics & g) override
References AboutLink::displayColor, HasEditor::editor, AboutLink::font, AboutLink::hoverColor, AboutLink::isHovered, SCXTEditor::themeColor(), and AboutLink::txt.
Member Data Documentation
url
std::string url
Referenced by AboutLink::mouseDown().
txt
std::string txt
Referenced by AboutLink::paint().
isHovered
bool isHovered {false}
Referenced by AboutLink::mouseEnter(), AboutLink::mouseExit(), and AboutLink::paint().
font
juce::Font font {juce::FontOptions()}
Referenced by AboutLink::AboutLink(), and AboutLink::paint().
hoverColor
theme::ColorMap::Colors hoverColor {theme::ColorMap::accent_2a}
Referenced by AboutLink::paint().
displayColor
theme::ColorMap::Colors displayColor {theme::ColorMap::generic_content_medium}
Referenced by AboutLink::paint().
onClick
std::function<void()> onClick {nullptr}
Referenced by AboutLink::mouseDown().
The documentation for this struct was generated from the following file:
AboutScreen.cpp