shortcircuit-xt: ExplicitMenuOrder Struct Reference
ExplicitMenuOrder Struct Reference
#include <matrix_shared.h>
Public Member Functions
ExplicitMenuOrder (scxt::engine::Engine *e)
~ExplicitMenuOrder ()
void separator ()
ExplicitMenuOrder (const ExplicitMenuOrder &)=delete
ExplicitMenuOrder & operator= (const ExplicitMenuOrder &)=delete
Public Attributes
scxt::engine::Engine * engine {nullptr}
Constructor & Destructor Documentation
ExplicitMenuOrder() [1/2]
ExplicitMenuOrder (scxt::engine::Engine * e) explicit
References Engine::beginExplicitMenuOrder(), and ExplicitMenuOrder::engine.
~ExplicitMenuOrder()
~ExplicitMenuOrder ()
References Engine::endExplicitMenuOrder(), and ExplicitMenuOrder::engine.
ExplicitMenuOrder() [2/2]
ExplicitMenuOrder (const ExplicitMenuOrder &) delete
Member Function Documentation
separator()
void separator ()
References ExplicitMenuOrder::engine, and Engine::requestMenuSeparator().
operator=()
ExplicitMenuOrder & operator= (const ExplicitMenuOrder &) delete
Member Data Documentation
engine
scxt::engine::Engine* engine {nullptr}
Referenced by ExplicitMenuOrder::ExplicitMenuOrder(), ExplicitMenuOrder::separator(), and ExplicitMenuOrder::~ExplicitMenuOrder().
The documentation for this struct was generated from the following files:
matrix_shared.h
matrix_shared.cpp