shortcircuit-xt: ScanWorker::ScanDir Struct Reference
ScanWorker::ScanDir Struct Reference
Public Member Functions
ScanDir (const fs::path &p, uint64_t mtime)
void go (ScanWorker &w) override
Public Member Functions inherited from ScanWorker::EnQAble
virtual ~EnQAble ()=default
Public Attributes
fs::path path
uint64_t afterMtime
Constructor & Destructor Documentation
ScanDir()
ScanDir (const fs::path & p, uint64_t mtime)
Member Function Documentation
go()
void go (ScanWorker & w) override virtual
Implements ScanWorker::EnQAble.
References ScanWorker::ScanDir::afterMtime, ScanWorker::enqueueWorkItem(), ScanWorker::enqueueWorkLowPri(), Browser::isLoadableFile(), and ScanWorker::ScanDir::path.
Member Data Documentation
path
fs::path path
Referenced by ScanWorker::ScanDir::go().
afterMtime
uint64_t afterMtime
Referenced by ScanWorker::ScanDir::go().
The documentation for this struct was generated from the following file:
scanner.cpp