shortcircuit-xt: AboutScreen Struct Reference
AboutScreen Struct Reference
#include <AboutScreen.h>
Classes
struct AboutInfo
Public Member Functions
AboutScreen (SCXTEditor *e)
~AboutScreen ()
void paint (juce::Graphics &g) override
juce::Font FT (titleFont)
juce::Font FT (subtitleFont)
juce::Font FT (infoFont)
juce::Font FT (aboutFont)
void resetInfo ()
void copyInfo ()
void resized () override
void visibilityChanged () override
void mouseUp (const juce::MouseEvent &e) override
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AboutScreen)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::vector< AboutInfo > info
std::unique_ptr< juce::Drawable > icon
std::unique_ptr< sst::jucegui::components::TextPushButton > copyButton
std::string openSourceText
std::vector< std::pair< std::string, std::string > > openSourceInfo
std::vector< std::unique_ptr< AboutLink > > openSourceLinkWidgets
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int infoh = 23
static constexpr int openSourceStartY {210}
static constexpr int openSourceX {25}
Constructor & Destructor Documentation
AboutScreen()
AboutScreen (SCXTEditor * e) explicit
References HasEditor::editor, AboutScreen::icon, ThemeApplier::interMediumFor(), scxt::ui::connectors::resources::loadImageDrawable(), AboutScreen::resetInfo(), and SCXTEditor::themeApplier.
~AboutScreen()
~AboutScreen ()
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::bg_1, HasEditor::editor, ColorMap::generic_content_high, ColorMap::generic_content_highest, ColorMap::generic_content_medium, AboutScreen::icon, AboutScreen::info, AboutScreen::infoh, AboutScreen::openSourceStartY, AboutScreen::openSourceX, and SCXTEditor::themeColor().
FT() [1/4]
juce::Font FT (titleFont)
FT() [2/4]
juce::Font FT (subtitleFont)
FT() [3/4]
juce::Font FT (infoFont)
FT() [4/4]
juce::Font FT (aboutFont)
resetInfo()
void resetInfo ()
References AboutScreen::copyButton, AboutScreen::copyInfo(), HasEditor::editor, SCXTEditor::engineStatus, AboutScreen::info, scxt::ui::connectors::resources::loadTextFile(), AboutScreen::openSourceInfo, AboutScreen::openSourceLinkWidgets, AboutScreen::openSourceText, Engine::EngineStatusMessage::runningEnvironment, and Engine::EngineStatusMessage::sampleRate.
Referenced by AboutScreen::AboutScreen(), and AboutScreen::visibilityChanged().
copyInfo()
void copyInfo ()
References AboutScreen::info.
Referenced by AboutScreen::resetInfo().
resized()
void resized () override
References AboutScreen::copyButton, AboutScreen::info, AboutScreen::infoh, AboutScreen::openSourceLinkWidgets, AboutScreen::openSourceStartY, and AboutScreen::openSourceX.
visibilityChanged()
void visibilityChanged () override
References AboutScreen::resetInfo().
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR()
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AboutScreen)
Member Data Documentation
info
std::vector<AboutInfo> info
Referenced by AboutScreen::copyInfo(), AboutScreen::paint(), AboutScreen::resetInfo(), and AboutScreen::resized().
icon
std::unique_ptr<juce::Drawable> icon
Referenced by AboutScreen::AboutScreen(), and AboutScreen::paint().
copyButton
std::unique_ptr<sst::jucegui::components::TextPushButton> copyButton
Referenced by AboutScreen::resetInfo(), and AboutScreen::resized().
infoh
constexpr int infoh = 23 static constexpr
Referenced by AboutScreen::paint(), and AboutScreen::resized().
openSourceStartY
constexpr int openSourceStartY {210} static constexpr
Referenced by AboutScreen::paint(), and AboutScreen::resized().
openSourceX
constexpr int openSourceX {25} static
Referenced by AboutScreen::paint(), and AboutScreen::resized().
openSourceText
std::string openSourceText
Referenced by AboutScreen::resetInfo().
openSourceInfo
std::vector<std::pair<std::string, std::string> > openSourceInfo
Referenced by AboutScreen::resetInfo().
openSourceLinkWidgets
std::vector<std::unique_ptr<AboutLink> > openSourceLinkWidgets
Referenced by AboutScreen::resetInfo(), and AboutScreen::resized().
The documentation for this struct was generated from the following files:
AboutScreen.h
AboutScreen.cpp