shortcircuit-xt: GroupProcessorTypeChangeItem Struct Reference
GroupProcessorTypeChangeItem Struct Reference
#include <processor_undoable_items.h>
Public Member Functions
void store (engine::Engine &e, int32_t which, const std::vector< selection::SelectionManager::ZoneAddress > &groups)
void restore (engine::Engine &e) override
std::unique_ptr< UndoableItem > makeRedo (engine::Engine &e) override
std::string describe () const override
Public Member Functions inherited from UndoableItem
virtual ~UndoableItem ()=default
Public Attributes
int32_t whichProcessor {-1}
std::vector< dsp::processor::ProcessorStorage > cachedStorage
Public Attributes inherited from MultiSelectUndoBaseItem
bool forZone {false}
std::vector< selection::SelectionManager::ZoneAddress > selectionList
Member Function Documentation
store()
void store (engine::Engine & e, int32_t which, const std::vector< selection::SelectionManager::ZoneAddress > & groups)
References GroupProcessorTypeChangeItem::cachedStorage, MultiSelectUndoBaseItem::forZone, Engine::getPatch(), MultiSelectUndoBaseItem::selectionList, and GroupProcessorTypeChangeItem::whichProcessor.
restore()
void restore (engine::Engine & e) override virtual
Implements UndoableItem.
References GroupProcessorTypeChangeItem::cachedStorage, scxt::modulation::getGroupMatrixMetadata(), Engine::getMessageController(), scxt::messaging::client::s2c_respond_single_processor_metadata_and_data, scxt::messaging::client::s2c_update_group_matrix_metadata, MultiSelectUndoBaseItem::selectionList, scxt::messaging::client::serializationSendToClient(), and GroupProcessorTypeChangeItem::whichProcessor.
makeRedo()
std::unique_ptr< UndoableItem > makeRedo (engine::Engine & e) override virtual
Implements UndoableItem.
References MultiSelectUndoBaseItem::selectionList, and GroupProcessorTypeChangeItem::whichProcessor.
describe()
std::string describe () const override virtual
Implements UndoableItem.
References GroupProcessorTypeChangeItem::whichProcessor.
Member Data Documentation
whichProcessor
int32_t whichProcessor {-1}
Referenced by GroupProcessorTypeChangeItem::describe(), GroupProcessorTypeChangeItem::makeRedo(), GroupProcessorTypeChangeItem::restore(), and GroupProcessorTypeChangeItem::store().
cachedStorage
std::vector<dsp::processor::ProcessorStorage> cachedStorage
Referenced by GroupProcessorTypeChangeItem::restore(), and GroupProcessorTypeChangeItem::store().
The documentation for this struct was generated from the following files:
processor_undoable_items.h
processor_undoable_items.cpp