shortcircuit-xt: ModulationCurves Struct Reference
ModulationCurves Struct Reference
Public Types
using CurveIdentifier = uint32_t
Static Public Member Functions
static void initializeCurves ()
static std::function< float(float)> getCurveOperator (CurveIdentifier id)
Static Public Attributes
static std::vector< CurveIdentifier > allCurves
static std::unordered_map< CurveIdentifier, std::pair< std::string, std::string > > curveNames
static std::unordered_map< CurveIdentifier, std::function< float(float)> > curveImpls
Member Typedef Documentation
CurveIdentifier
using CurveIdentifier = uint32_t
Member Function Documentation
initializeCurves()
static void initializeCurves () static
References ModulationCurves::allCurves, ModulationCurves::curveImpls, and ModulationCurves::curveNames.
Referenced by Engine::Engine().
getCurveOperator()
static std::function<float(float)> getCurveOperator (CurveIdentifier id) static
References ModulationCurves::curveImpls.
Referenced by GroupMatrixConfig::getCurveOperator(), and MatrixConfig::getCurveOperator().
Member Data Documentation
allCurves
std::vector< ModulationCurves::CurveIdentifier > allCurves static
Referenced by scxt::modulation::getGroupMatrixMetadata(), scxt::voice::modulation::getVoiceMatrixMetadata(), and ModulationCurves::initializeCurves().
curveNames
std::unordered_map< ModulationCurves::CurveIdentifier, std::pair< std::string, std::string > > curveNames static
Referenced by scxt::modulation::getGroupMatrixMetadata(), scxt::voice::modulation::getVoiceMatrixMetadata(), and ModulationCurves::initializeCurves().
curveImpls
std::unordered_map< ModulationCurves::CurveIdentifier, std::function< float(float)> > curveImpls static
Referenced by ModulationCurves::getCurveOperator(), and ModulationCurves::initializeCurves().
The documentation for this struct was generated from the following files:
mod_curves.h
mod_curves.cpp