shortcircuit-xt: AKPFile Struct Reference
AKPFile Struct Reference
Public Member Functions
bool load (const char *data, size_t size)
Public Attributes
std::string programName
GLOBAL_OUT out
GLOBAL_TUNE tune
std::vector< GLOBAL_LFO > lfos
GLOBAL_MODS mods
std::vector< KEYGROUP > keygroups
Member Function Documentation
load()
bool load (const char * data, size_t size)
References scxt::akai_support::fourCC(), scxt::akai_support::fourCCSize(), AKPFile::keygroups, AKPFile::lfos, GLOBAL_OUT::load(), GLOBAL_TUNE::load(), GLOBAL_MODS::load(), GLOBAL_LFO::load(), AKPFile::mods, AKPFile::out, KEYGROUP::parse(), AKPFile::programName, and AKPFile::tune.
Referenced by scxt::akai_support::dumpAkaiToLog(), and scxt::akai_support::importAKP().
Member Data Documentation
programName
std::string programName
Referenced by scxt::akai_support::dumpAkaiToLog(), and AKPFile::load().
out
GLOBAL_OUT out
Referenced by scxt::akai_support::dumpAkaiToLog(), and AKPFile::load().
tune
GLOBAL_TUNE tune
Referenced by scxt::akai_support::dumpAkaiToLog(), and AKPFile::load().
lfos
std::vector<GLOBAL_LFO> lfos
Referenced by scxt::akai_support::dumpAkaiToLog(), and AKPFile::load().
mods
GLOBAL_MODS mods
Referenced by scxt::akai_support::dumpAkaiToLog(), and AKPFile::load().
keygroups
std::vector<KEYGROUP> keygroups
Referenced by scxt::akai_support::dumpAkaiToLog(), scxt::akai_support::importAKP(), and AKPFile::load().
The documentation for this struct was generated from the following file:
akai_import.cpp