shortcircuit-xt: ImportedSource Struct Reference
ImportedSource Struct Reference
#include <import_modulation.h>
Static Public Member Functions
static ImportedSource fromLFO (LFOHandle h)
static ImportedSource fromEG (EGHandle h)
static ImportedSource midiCC (int cc)
static ImportedSource velocity ()
static ImportedSource releaseVelocity ()
static ImportedSource channelAT ()
static ImportedSource polyAT ()
static ImportedSource modWheel ()
static ImportedSource pitchBend ()
static ImportedSource keyTrack ()
Public Attributes
ImportedSourceKind kind {}
int index {0}
Member Function Documentation
fromLFO()
static ImportedSource fromLFO (LFOHandle h) static
References scxt::import_support::LFO, and LFOHandle::lfoSlot.
Referenced by scxt::sf2_support::importSF2().
fromEG()
static ImportedSource fromEG (EGHandle h) static
References scxt::import_support::EG, and EGHandle::egSlot.
Referenced by scxt::akai_support::importAKP(), scxt::exs_support::importEXS(), and scxt::sf2_support::importSF2().
midiCC()
static ImportedSource midiCC (int cc) static
References scxt::import_support::MidiCC.
Referenced by scxt::sf2_support::importSF2(), scxt::sfz_support::sfzSourceForSuffix(), and scxt::sfz_support::zoneEnvelopeMods().
velocity()
static ImportedSource velocity () static
References scxt::import_support::Velocity.
Referenced by scxt::akai_support::importAKP(), scxt::sf2_support::importSF2(), scxt::sfz_support::importSFZ(), and scxt::sfz_support::zoneEnvelopeMods().
releaseVelocity()
static ImportedSource releaseVelocity () static
References scxt::import_support::ReleaseVelocity.
channelAT()
static ImportedSource channelAT () static
References scxt::import_support::ChannelAT.
Referenced by scxt::akai_support::importAKP(), scxt::sf2_support::importSF2(), and scxt::sfz_support::sfzSourceForSuffix().
polyAT()
static ImportedSource polyAT () static
References scxt::import_support::PolyAT.
modWheel()
static ImportedSource modWheel () static
References scxt::import_support::ModWheel.
Referenced by scxt::akai_support::importAKP(), scxt::sf2_support::importSF2(), scxt::sfz_support::sfzSourceForSuffix(), and scxt::sfz_support::zoneEnvelopeMods().
pitchBend()
static ImportedSource pitchBend () static
References scxt::import_support::PitchBend.
Referenced by scxt::akai_support::importAKP(), and scxt::sf2_support::importSF2().
keyTrack()
static ImportedSource keyTrack () static
References scxt::import_support::KeyTrack.
Referenced by scxt::akai_support::importAKP(), scxt::sf2_support::importSF2(), and scxt::sfz_support::zoneParamKeytrack().
Member Data Documentation
kind
ImportedSourceKind kind {}
index
int index {0}
The documentation for this struct was generated from the following file:
import_modulation.h