shortcircuit-xt: MappingDisplay::LayoutAndKeyboard Struct Reference
MappingDisplay::LayoutAndKeyboard Struct Reference
#include <MappingDisplay.h>
Inherits Component, and ZoomContainerClient.
Public Member Functions
Component * associatedComponent () override
bool supportsVerticalZoom () const override
bool supportsHorizontalZoom () const override
void setHorizontalZoom (float pctStart, float zoomFactor) override
void setVerticalZoom (float pctStart, float zoomFactor) override
LayoutAndKeyboard (MappingDisplay *that)
void resized () override
Public Attributes
std::unique_ptr< ZoneLayoutDisplay > mappingZones
std::unique_ptr< ZoneLayoutKeyboard > keyboard
Constructor & Destructor Documentation
LayoutAndKeyboard()
LayoutAndKeyboard (MappingDisplay * that)
References MappingDisplay::LayoutAndKeyboard::keyboard, and MappingDisplay::LayoutAndKeyboard::mappingZones.
Member Function Documentation
associatedComponent()
Component * associatedComponent () override
supportsVerticalZoom()
bool supportsVerticalZoom () const override
supportsHorizontalZoom()
bool supportsHorizontalZoom () const override
setHorizontalZoom()
void setHorizontalZoom (float pctStart, float zoomFactor) override
References MappingDisplay::keyboard, MappingDisplay::mappingZones, ZoneLayoutDisplay::setHorizontalZoom(), and ZoneLayoutKeyboard::setHorizontalZoom().
setVerticalZoom()
void setVerticalZoom (float pctStart, float zoomFactor) override
References MappingDisplay::mappingZones, and ZoneLayoutDisplay::setVerticalZoom().
resized()
void resized () override
References MappingDisplay::keyboard, ZoneLayoutKeyboard::keyboardHeight, and MappingDisplay::mappingZones.
Member Data Documentation
mappingZones
std::unique_ptr<ZoneLayoutDisplay> mappingZones
Referenced by MappingDisplay::LayoutAndKeyboard::LayoutAndKeyboard().
keyboard
std::unique_ptr<ZoneLayoutKeyboard> keyboard
Referenced by MappingDisplay::LayoutAndKeyboard::LayoutAndKeyboard().
The documentation for this struct was generated from the following files:
MappingDisplay.h
MappingDisplay.cpp