shortcircuit-xt: CurveLFO Struct Reference
CurveLFO Struct Reference
Public Types
using slfo_t = sst::basic_blocks::modulators::SimpleLFO< CurveLFO, scxt::blockSize >
using senv_t = sst::basic_blocks::modulators::DAREnvelope< CurveLFO, scxt::blockSize, sst::basic_blocks::modulators::TwentyFiveSecondExp >
Public Member Functions
float envelope_rate_linear_nowrap (float f)
void attack (float initPhase, ModulatorStorage::ModulatorShape shape)
void process (const float rate, const float deform, const float delay, const float attack, const float release, bool useEnv, bool unipolar, bool isGated)
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
virtual void onSampleRateChanged ()
Public Attributes
float output {0.f}
slfo_t simpleLfo {this}
senv_t simpleEnv {this}
friend slfo_t
slfo_t::Shape curveShape {slfo_t::SINE}
uint32_t smp {0}
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Member Typedef Documentation
slfo_t
using slfo_t = sst::basic_blocks::modulators::SimpleLFO<CurveLFO, scxt::blockSize>
senv_t
using senv_t = sst::basic_blocks::modulators::DAREnvelope< CurveLFO, scxt::blockSize, sst::basic_blocks::modulators::TwentyFiveSecondExp>
Member Function Documentation
envelope_rate_linear_nowrap()
float envelope_rate_linear_nowrap (float f)
References SampleRateSupport::sampleRateInv, and scxt::dsp::twoToTheXTable.
attack()
void attack (float initPhase, ModulatorStorage::ModulatorShape shape)
References CurveLFO::curveShape, ModulatorStorage::LFO_PULSE, ModulatorStorage::LFO_RAMP, ModulatorStorage::LFO_SH_NOISE, ModulatorStorage::LFO_SINE, ModulatorStorage::LFO_SMOOTH_NOISE, ModulatorStorage::LFO_TRI, CurveLFO::simpleEnv, and CurveLFO::simpleLfo.
Referenced by CurveLFO::process(), Group::resetLFOs(), and Voice::voiceStarted().
process()
void process (const float rate, const float deform, const float delay, const float attack, const float release, bool useEnv, bool unipolar, bool isGated)
References CurveLFO::attack(), CurveLFO::curveShape, scxt::engine::delay, CurveLFO::output, CurveLFO::simpleEnv, and CurveLFO::simpleLfo.
Member Data Documentation
output
float output {0.f}
Referenced by CurveLFO::process().
simpleLfo
slfo_t simpleLfo {this}
Referenced by CurveLFO::attack(), and CurveLFO::process().
simpleEnv
senv_t simpleEnv {this}
Referenced by CurveLFO::attack(), and CurveLFO::process().
slfo_t
friend slfo_t
curveShape
slfo_t::Shape curveShape {slfo_t::SINE}
Referenced by CurveLFO::attack(), and CurveLFO::process().
smp
uint32_t smp {0}
The documentation for this struct was generated from the following file:
curvelfo.h