shortcircuit-xt: PartEffectsPane< forBus > Struct Template Reference
PartEffectsPane< forBus > Struct Template Reference
#include <PartEffectsPane.h>
Public Types
using parent_t = std::conditional_t< forBus, mixer_screen::MixerScreen, edit_screen::PartEditScreen >
using partFXMD_t = std::array< datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams >
using partFXStorage_t = std::pair< partFXMD_t, engine::BusEffectStorage >
using attachment_t = connectors::PayloadDataAttachment< engine::BusEffectStorage >
using boolAttachment_t = connectors::BooleanPayloadDataAttachment< engine::BusEffectStorage >
using intProxyAttachment_t = connectors::DiscreteFromFloatAdapterAttachment< attachment_t >
Public Member Functions
PartEffectsPane (SCXTEditor *e, parent_t *ms, int i)
~PartEffectsPane ()
partFXStorage_t & getPartFXStorage ()
void setBusAddress (int ba)
void setSelectedPart (int pt)
void resized () override
void rebuild ()
void showHamburger ()
void paintMetadata (juce::Graphics &g, const juce::Rectangle< int > &into)
void mouseDown (const juce::MouseEvent &event) override
void mouseDrag (const juce::MouseEvent &event) override
bool isInterestedInDragSource (const SourceDetails &dragSourceDetails) override
void itemDragEnter (const SourceDetails &dragSourceDetails) override
void itemDragExit (const SourceDetails &dragSourceDetails) override
void itemDropped (const SourceDetails &dragSourceDetails) override
std::string resolveJsonPath (const std::string &path) const override
void createBindAndPosition (const sst::jucegui::layouts::json_document::Control &, const sst::jucegui::layouts::json_document::Class &) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Member Functions inherited from FXSlotBearing
FXSlotBearing ()
FXSlotBearing (int f, int b, bool fb)
Static Public Member Functions
static void showFXSelectionMenu (parent_t *p, int b, int s)
static std::string effectDisplayName (engine::AvailableBusEffects, bool forMenu)
Public Attributes
parent_t * parent {nullptr}
bool isDragging {false}
bool swapFX {true}
std::unordered_set< std::unique_ptr< juce::Component > > components
std::unordered_set< std::unique_ptr< attachment_t > > floatAttachments
std::array< std::unique_ptr< intProxyAttachment_t >, scxt::maxBusEffectParams > intProxyAttachments
std::unordered_set< std::unique_ptr< boolAttachment_t > > boolAttachments
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Public Attributes inherited from FXSlotBearing
int fxSlot {0}
int busAddressOrPart {0}
bool busEffect {true}
Static Public Attributes
static constexpr int width {198}
static constexpr int height {290}
Protected Member Functions
template<typename T >
T * attachWidgetToFloat (int index)
juce::Component * attachMenuButtonToInt (int index)
template<typename T >
juce::Component * attachWidgetToInt (int index)
juce::Component * attachToggleToDeactivated (int index)
template<typename T >
juce::Component * addTypedLabel (const std::string &txt)
juce::Component * addLabel (const std::string &txt)
template<typename T >
T * layoutWidgetToFloat (const sst::jucegui::layouts::ExplicitLayout &elo, int index, const std::string &lotag)
template<typename T >
T * layoutWidgetToFloat (const sst::jucegui::layouts::ExplicitLayout &elo, int index, const std::string &lotag, const std::string &label)
void rebuildDefaultLayout ()
void rebuildWithJsonLayoutEngine (const std::string &path)
template<typename Att >
void busEffectStorageChangedFromGUI (const Att &at, int idx)
Protected Attributes
std::vector< std::unique_ptr< juce::Component > > jsonLabels
Member Typedef Documentation
parent_t
template<bool forBus> using parent_t = std::conditional_t<forBus, mixer_screen::MixerScreen, edit_screen::PartEditScreen>
partFXMD_t
template<bool forBus> using partFXMD_t = std::array<datamodel::pmd, engine::BusEffectStorage::maxBusEffectParams>
partFXStorage_t
template<bool forBus> using partFXStorage_t = std::pair<partFXMD_t, engine::BusEffectStorage>
attachment_t
template<bool forBus> using attachment_t = connectors::PayloadDataAttachment<engine::BusEffectStorage>
boolAttachment_t
template<bool forBus> using boolAttachment_t = connectors::BooleanPayloadDataAttachment<engine::BusEffectStorage>
intProxyAttachment_t
template<bool forBus> using intProxyAttachment_t = connectors::DiscreteFromFloatAdapterAttachment<attachment_t>
Constructor & Destructor Documentation
PartEffectsPane()
template<bool forBus> PartEffectsPane (SCXTEditor * e, parent_t * ms, int i)
~PartEffectsPane()
template<bool forBus> ~PartEffectsPane ()
Member Function Documentation
getPartFXStorage()
template<bool forBus> PartEffectsPane< forBus >::partFXStorage_t & getPartFXStorage ()
setBusAddress()
template<bool forBus> void setBusAddress (int ba)
References FXSlotBearing::busAddressOrPart, and PartEffectsPane< forBus >::rebuild().
setSelectedPart()
template<bool forBus> void setSelectedPart (int pt)
References FXSlotBearing::busAddressOrPart, and PartEffectsPane< forBus >::rebuild().
resized()
template<bool forBus> void resized () override
References PartEffectsPane< forBus >::rebuild().
rebuild()
template<bool forBus> void rebuild ()
Referenced by PartEffectsPane< forBus >::resized(), PartEffectsPane< forBus >::setBusAddress(), and PartEffectsPane< forBus >::setSelectedPart().
showHamburger()
template<bool forBus> void showHamburger ()
References FXSlotBearing::busAddressOrPart, FXSlotBearing::fxSlot, PartEffectsPane< forBus >::parent, and PartEffectsPane< forBus >::showFXSelectionMenu().
showFXSelectionMenu()
template<bool forBus> void showFXSelectionMenu (parent_t * p, int b, int s) static
References scxt::engine::bonsai, scxt::engine::delay, scxt::engine::flanger, scxt::engine::floatydelay, scxt::engine::nimbus, scxt::engine::none, scxt::engine::phaser, scxt::engine::reverb1, scxt::engine::reverb2, and scxt::engine::treemonster.
Referenced by ChannelStrip::ChannelStrip(), and PartEffectsPane< forBus >::showHamburger().
paintMetadata()
template<bool forBus> void paintMetadata (juce::Graphics & g, const juce::Rectangle< int > & into)
mouseDown()
template<bool forBus> void mouseDown (const juce::MouseEvent & event) override
References PartEffectsPane< forBus >::isDragging, and PartEffectsPane< forBus >::swapFX.
mouseDrag()
template<bool forBus> void mouseDrag (const juce::MouseEvent & event) override
isInterestedInDragSource()
template<bool forBus> bool isInterestedInDragSource (const SourceDetails & dragSourceDetails) override
itemDragEnter()
template<bool forBus> void itemDragEnter (const SourceDetails & dragSourceDetails) override
itemDragExit()
template<bool forBus> void itemDragExit (const SourceDetails & dragSourceDetails) override
itemDropped()
template<bool forBus> void itemDropped (const SourceDetails & dragSourceDetails) override
attachWidgetToFloat()
template<bool forBus> template<typename T > T * attachWidgetToFloat (int index) protected
attachMenuButtonToInt()
template<bool forBus> juce::Component * attachMenuButtonToInt (int index) protected
attachWidgetToInt()
template<bool forBus> template<typename T > juce::Component * attachWidgetToInt (int index) protected
attachToggleToDeactivated()
template<bool forBus> juce::Component * attachToggleToDeactivated (int index) protected
addTypedLabel()
template<bool forBus> template<typename T > juce::Component * addTypedLabel (const std::string & txt) protected
addLabel()
template<bool forBus> juce::Component * addLabel (const std::string & txt) protected
Referenced by PartEffectsPane< forBus >::layoutWidgetToFloat().
layoutWidgetToFloat() [1/2]
template<bool forBus> template<typename T > T * layoutWidgetToFloat (const sst::jucegui::layouts::ExplicitLayout & elo, int index, const std::string & lotag) protected
layoutWidgetToFloat() [2/2]
template<bool forBus> template<typename T > T * layoutWidgetToFloat (const sst::jucegui::layouts::ExplicitLayout & elo, int index, const std::string & lotag, const std::string & label) protected
References PartEffectsPane< forBus >::addLabel().
rebuildDefaultLayout()
template<bool forBus> void rebuildDefaultLayout () protected
References SCLOG.
rebuildWithJsonLayoutEngine()
template<bool forBus> void rebuildWithJsonLayoutEngine (const std::string & path) protected
References scxt::ui::connectors::jsonlayout::resolveJsonFile().
resolveJsonPath()
template<bool forBus> std::string resolveJsonPath (const std::string & path) const override
References scxt::ui::connectors::jsonlayout::resolveJsonFile().
createBindAndPosition()
template<bool forBus> void createBindAndPosition (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls) override
busEffectStorageChangedFromGUI()
template<bool forBus> template<typename Att > void busEffectStorageChangedFromGUI (const Att & at, int idx) protected
effectDisplayName()
template<bool forBus> std::string effectDisplayName (engine::AvailableBusEffects t, bool forMenu) static
Member Data Documentation
width
template<bool forBus> constexpr int width {198} static constexpr
height
template<bool forBus> constexpr int height {290} static
parent
template<bool forBus> parent_t* parent {nullptr}
Referenced by PartEffectsPane< forBus >::showHamburger().
isDragging
template<bool forBus> bool isDragging {false}
Referenced by PartEffectsPane< forBus >::mouseDown().
swapFX
template<bool forBus> bool swapFX {true}
Referenced by PartEffectsPane< forBus >::mouseDown().
components
template<bool forBus> std::unordered_set<std::unique_ptr<juce::Component> > components
floatAttachments
template<bool forBus> std::unordered_set<std::unique_ptr<attachment_t> > floatAttachments
intProxyAttachments
template<bool forBus> std::array<std::unique_ptr<intProxyAttachment_t>, scxt::maxBusEffectParams> intProxyAttachments
boolAttachments
template<bool forBus> std::unordered_set<std::unique_ptr<boolAttachment_t> > boolAttachments
jsonLabels
template<bool forBus> std::vector<std::unique_ptr<juce::Component> > jsonLabels protected
The documentation for this struct was generated from the following files:
PartEditScreen.h
PartEffectsPane.h
PartEffectsPane.cpp