shortcircuit-xt: GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent Struct Reference
GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent Struct Reference
#include <GroupZoneTreeControl.h>
Inherits Component, DragAndDropTarget, and Listener.
Public Types
enum DragOverState { NONE , DRAG_OVER }
Public Member Functions
rowComponent ()
void paint (juce::Graphics &g) override
selection::SelectionManager::ZoneAddress getZoneAddress ()
bool isZone ()
bool isGroup ()
void mouseDown (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &event) override
bool isInterestedInDragSource (const SourceDetails &dragSourceDetails) override
void itemDragEnter (const SourceDetails &dragSourceDetails) override
void itemDragMove (const SourceDetails &dragSourceDetails) override
void itemDragExit (const SourceDetails &dragSourceDetails) override
void itemDropped (const SourceDetails &dragSourceDetails) override
void resized () override
void doGroupRename ()
void doZoneRename (const selection::SelectionManager::ZoneAddress &za)
void textEditorReturnKeyPressed (juce::TextEditor &) override
void textEditorEscapeKeyPressed (juce::TextEditor &) override
void textEditorFocusLost (juce::TextEditor &) override
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (rowComponent)
Public Attributes
int rowNumber {-1}
bool isSelected {false}
GroupZoneSidebarWidget< SidebarParent, forZone > * lbm {nullptr}
SidebarParent * gsb {nullptr}
std::unique_ptr< juce::TextEditor > renameEditor
int zonePad = 16
int grouplabelPad = zonePad
enum scxt::ui::app::edit_screen::GroupZoneSidebarWidget::rowComponent::DragOverState NONE
bool isDragging {false}
bool isPopup {false}
bool isPaintSnapshot {false}
bool isDragMulti {false}
Member Enumeration Documentation
DragOverState
template<typename SidebarParent , bool fz> enum DragOverState
Enumerator
NONE
DRAG_OVER
Constructor & Destructor Documentation
rowComponent()
template<typename SidebarParent , bool fz> rowComponent ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor.
Member Function Documentation
paint()
template<typename SidebarParent , bool fz> void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_1b, ColorMap::bg_2, ColorMap::bg_3, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::DRAG_OVER, GroupZoneSidebarWidget< SidebarParent, fz >::forZone, ColorMap::generic_content_high, ColorMap::generic_content_highest, ColorMap::generic_content_low, ColorMap::generic_content_medium, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::grouplabelPad, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::gzData, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isDragMulti, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isGroup(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isPaintSnapshot, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isSelected, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isZone(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, scxt::engine::MISSING_SAMPLE, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowNumber, GroupZoneSidebarWidget< SidebarParent, fz >::selectedZones, ColorMap::warning_1a, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::zonePad.
getZoneAddress()
template<typename SidebarParent , bool fz> selection::SelectionManager::ZoneAddress getZoneAddress ()
References GroupZoneSidebarWidget< SidebarParent, fz >::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowNumber.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isGroup(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isZone(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDropped(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseUp(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorReturnKeyPressed().
isZone()
template<typename SidebarParent , bool fz> bool isZone ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), and SelectionManager::ZoneAddress::zone.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorReturnKeyPressed().
isGroup()
template<typename SidebarParent , bool fz> bool isGroup ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), and SelectionManager::ZoneAddress::zone.
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
mouseDown()
template<typename SidebarParent , bool fz> void mouseDown (const juce::MouseEvent & e) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::gzData, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isGroup(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isPopup, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isZone(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, scxt::ui::app::shared::populateZoneRightMouseMenuForSelectedZones(), scxt::ui::app::shared::populateZoneRightMouseMenuForZone(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowNumber.
mouseDrag()
template<typename SidebarParent , bool fz> void mouseDrag (const juce::MouseEvent & e) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isDragging, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isDragMulti, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isGroup(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isPaintSnapshot, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isSelected, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isZone(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, and GroupZoneSidebarWidget< SidebarParent, fz >::selectedZones.
mouseUp()
template<typename SidebarParent , bool fz> void mouseUp (const juce::MouseEvent & event) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isDragging, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isPopup, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isSelected.
isInterestedInDragSource()
template<typename SidebarParent , bool fz> bool isInterestedInDragSource (const SourceDetails & dragSourceDetails) override
itemDragEnter()
template<typename SidebarParent , bool fz> void itemDragEnter (const SourceDetails & dragSourceDetails) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::DRAG_OVER.
itemDragMove()
template<typename SidebarParent , bool fz> void itemDragMove (const SourceDetails & dragSourceDetails) override
itemDragExit()
template<typename SidebarParent , bool fz> void itemDragExit (const SourceDetails & dragSourceDetails) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::NONE.
itemDropped()
template<typename SidebarParent , bool fz> void itemDropped (const SourceDetails & dragSourceDetails) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::NONE, and GroupZoneSidebarWidget< SidebarParent, fz >::selectedZones.
resized()
template<typename SidebarParent , bool fz> void resized () override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::zonePad.
doGroupRename()
template<typename SidebarParent , bool fz> void doGroupRename ()
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::gzData, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowNumber.
doZoneRename()
template<typename SidebarParent , bool fz> void doZoneRename (const selection::SelectionManager::ZoneAddress & za)
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::gzData, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::lbm, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor, and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowNumber.
textEditorReturnKeyPressed()
template<typename SidebarParent , bool fz> void textEditorReturnKeyPressed (juce::TextEditor &) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::gsb, GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::isZone(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor.
textEditorEscapeKeyPressed()
template<typename SidebarParent , bool fz> void textEditorEscapeKeyPressed (juce::TextEditor &) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor.
textEditorFocusLost()
template<typename SidebarParent , bool fz> void textEditorFocusLost (juce::TextEditor &) override
References GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::renameEditor.
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR()
template<typename SidebarParent , bool fz> JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (rowComponent)
Member Data Documentation
rowNumber
template<typename SidebarParent , bool fz> int rowNumber {-1}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doGroupRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doZoneRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
isSelected
template<typename SidebarParent , bool fz> bool isSelected {false}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseUp(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
lbm
template<typename SidebarParent , bool fz> GroupZoneSidebarWidget<SidebarParent, forZone>* lbm {nullptr}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doGroupRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doZoneRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::getZoneAddress(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDropped(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
gsb
template<typename SidebarParent , bool fz> SidebarParent* gsb {nullptr}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doGroupRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doZoneRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDropped(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseUp(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorReturnKeyPressed().
renameEditor
template<typename SidebarParent , bool fz> std::unique_ptr<juce::TextEditor> renameEditor
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doGroupRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::doZoneRename(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::resized(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::rowComponent(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorEscapeKeyPressed(), GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorFocusLost(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::textEditorReturnKeyPressed().
zonePad
template<typename SidebarParent , bool fz> int zonePad = 16
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::resized().
grouplabelPad
template<typename SidebarParent , bool fz> int grouplabelPad = zonePad
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
NONE
template<typename SidebarParent , bool fz> enum scxt::ui::app::edit_screen::GroupZoneSidebarWidget::rowComponent::DragOverState NONE
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDragExit(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::itemDropped().
isDragging
template<typename SidebarParent , bool fz> bool isDragging {false}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseUp().
isPopup
template<typename SidebarParent , bool fz> bool isPopup {false}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDown(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseUp().
isPaintSnapshot
template<typename SidebarParent , bool fz> bool isPaintSnapshot {false}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
isDragMulti
template<typename SidebarParent , bool fz> bool isDragMulti {false}
Referenced by GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::mouseDrag(), and GroupZoneSidebarWidget< SidebarParent, fz >::rowComponent::paint().
The documentation for this struct was generated from the following file:
GroupZoneTreeControl.h