shortcircuit-xt: SamplePointDataAttachment Struct Reference
SamplePointDataAttachment Struct Reference
#include <PayloadDataAttachment.h>
Inherits Discrete.
Public Member Functions
SamplePointDataAttachment (int64_t &v, std::function< void(const SamplePointDataAttachment &)> ogc)
int getValue () const override
std::string getValueAsStringFor (int i) const override
void setValueFromGUI (const int &fi) override
std::string getLabel () const override
int getMin () const override
int getMax () const override
int getDefaultValue () const override
void jog (int dir) override
void setValueFromModel (const int &f) override
Public Attributes
int64_t & value
std::string label
int64_t sampleCount {0}
std::function< void(const SamplePointDataAttachment &)> onGuiChanged {nullptr}
std::function< int64_t(int64_t)> precheckGuiAdjust {nullptr}
int64_t jogIncrement {0}
Constructor & Destructor Documentation
SamplePointDataAttachment()
SamplePointDataAttachment (int64_t & v, std::function< void(const SamplePointDataAttachment &)> ogc)
Member Function Documentation
getValue()
int getValue () const override
References SamplePointDataAttachment::value.
getValueAsStringFor()
std::string getValueAsStringFor (int i) const override
setValueFromGUI()
void setValueFromGUI (const int & fi) override
References SamplePointDataAttachment::onGuiChanged, SamplePointDataAttachment::precheckGuiAdjust, and SamplePointDataAttachment::value.
Referenced by SamplePointDataAttachment::jog().
getLabel()
std::string getLabel () const override
References SamplePointDataAttachment::label.
getMin()
int getMin () const override
Referenced by SamplePointDataAttachment::jog().
getMax()
int getMax () const override
References SamplePointDataAttachment::sampleCount.
Referenced by SamplePointDataAttachment::jog().
getDefaultValue()
int getDefaultValue () const override
jog()
void jog (int dir) override
References SamplePointDataAttachment::getMax(), SamplePointDataAttachment::getMin(), SamplePointDataAttachment::jogIncrement, SamplePointDataAttachment::sampleCount, SamplePointDataAttachment::setValueFromGUI(), and SamplePointDataAttachment::value.
setValueFromModel()
void setValueFromModel (const int & f) override
References SamplePointDataAttachment::value.
Member Data Documentation
value
int64_t& value
Referenced by SamplePointDataAttachment::getValue(), SamplePointDataAttachment::jog(), SamplePointDataAttachment::setValueFromGUI(), and SamplePointDataAttachment::setValueFromModel().
label
std::string label
Referenced by SamplePointDataAttachment::getLabel().
sampleCount
int64_t sampleCount {0}
Referenced by SamplePointDataAttachment::getMax(), and SamplePointDataAttachment::jog().
onGuiChanged
std::function<void(const SamplePointDataAttachment &)> onGuiChanged {nullptr}
Referenced by SamplePointDataAttachment::setValueFromGUI().
precheckGuiAdjust
std::function<int64_t(int64_t)> precheckGuiAdjust {nullptr}
Referenced by SamplePointDataAttachment::setValueFromGUI().
jogIncrement
int64_t jogIncrement {0}
Referenced by SamplePointDataAttachment::jog().
The documentation for this struct was generated from the following file:
PayloadDataAttachment.h