shortcircuit-xt: PayloadDataAttachment< Payload, ValueType > Struct Template Reference
PayloadDataAttachment< Payload, ValueType > Struct Template Reference
#include <PayloadDataAttachment.h>
Inherits Continuous.
Public Types
typedef Payload payload_t
typedef ValueType value_t
Public Member Functions
PayloadDataAttachment (const datamodel::pmd &cd, std::function< void(const PayloadDataAttachment &at)> oGVC, ValueType &v)
PayloadDataAttachment (const datamodel::pmd &cd, ValueType &v)
PayloadDataAttachment (const PayloadDataAttachment &other)=delete
PayloadDataAttachment & operator= (const PayloadDataAttachment &other)=delete
PayloadDataAttachment & operator= (PayloadDataAttachment &&other)=delete
std::string getLabel () const override
float getValue () const override
void setValueFromGUIQuantized (const float &f) override
void setValueFromGUI (const float &ff) override
std::string getValueAsStringFor (float f) const override
std::string getValueAsStringWithoutUnitsFor (float f) const override
void setValueAsString (const std::string &s) override
void setValueFromModel (const float &f) override
float getMin () const override
float getMax () const override
float getDefaultValue () const override
bool isBipolar () const override
void andThenOnGui (std::function< void(const PayloadDataAttachment &)> f)
void setTemposyncFunction (std::function< bool(const PayloadDataAttachment &at)> f)
sst::basic_blocks::params::ParamMetaData::FeatureState getFeatureState () const
Public Attributes
ValueType & value
ValueType prevValue
std::string label
std::function< void(const PayloadDataAttachment &at)> onGuiValueChanged {nullptr}
std::function< bool(const PayloadDataAttachment &at)> isTemposynced {nullptr}
datamodel::pmd description
std::function< std::string(float)> valueToString {nullptr}
std::function< std::optional< float >(const std::string &)> stringToValue {nullptr}
Member Typedef Documentation
payload_t
template<typename Payload , typename ValueType = float> typedef Payload payload_t
value_t
template<typename Payload , typename ValueType = float> typedef ValueType value_t
Constructor & Destructor Documentation
PayloadDataAttachment() [1/3]
template<typename Payload , typename ValueType = float> PayloadDataAttachment (const datamodel::pmd & cd, std::function< void(const PayloadDataAttachment< Payload, ValueType > &at)> oGVC, ValueType & v)
PayloadDataAttachment() [2/3]
template<typename Payload , typename ValueType = float> PayloadDataAttachment (const datamodel::pmd & cd, ValueType & v)
PayloadDataAttachment() [3/3]
template<typename Payload , typename ValueType = float> PayloadDataAttachment (const PayloadDataAttachment< Payload, ValueType > & other) delete
Member Function Documentation
operator=() [1/2]
template<typename Payload , typename ValueType = float> PayloadDataAttachment & operator= (const PayloadDataAttachment< Payload, ValueType > & other) delete
operator=() [2/2]
template<typename Payload , typename ValueType = float> PayloadDataAttachment & operator= (PayloadDataAttachment< Payload, ValueType > && other) delete
getLabel()
template<typename Payload , typename ValueType = float> std::string getLabel () const override
References PayloadDataAttachment< Payload, ValueType >::label.
getValue()
template<typename Payload , typename ValueType = float> float getValue () const override
References PayloadDataAttachment< Payload, ValueType >::value.
setValueFromGUIQuantized()
template<typename Payload , typename ValueType = float> void setValueFromGUIQuantized (const float & f) override
References PayloadDataAttachment< Payload, ValueType >::description, PayloadDataAttachment< Payload, ValueType >::isTemposynced, and PayloadDataAttachment< Payload, ValueType >::setValueFromGUI().
setValueFromGUI()
template<typename Payload , typename ValueType = float> void setValueFromGUI (const float & ff) override
References PayloadDataAttachment< Payload, ValueType >::description, PayloadDataAttachment< Payload, ValueType >::isTemposynced, PayloadDataAttachment< Payload, ValueType >::onGuiValueChanged, PayloadDataAttachment< Payload, ValueType >::prevValue, and PayloadDataAttachment< Payload, ValueType >::value.
Referenced by PayloadDataAttachment< Payload, ValueType >::setValueAsString(), and PayloadDataAttachment< Payload, ValueType >::setValueFromGUIQuantized().
getValueAsStringFor()
template<typename Payload , typename ValueType = float> std::string getValueAsStringFor (float f) const override
References PayloadDataAttachment< Payload, ValueType >::description, PayloadDataAttachment< Payload, ValueType >::getFeatureState(), and PayloadDataAttachment< Payload, ValueType >::valueToString.
getValueAsStringWithoutUnitsFor()
template<typename Payload , typename ValueType = float> std::string getValueAsStringWithoutUnitsFor (float f) const override
References PayloadDataAttachment< Payload, ValueType >::description, PayloadDataAttachment< Payload, ValueType >::getFeatureState(), and PayloadDataAttachment< Payload, ValueType >::valueToString.
setValueAsString()
template<typename Payload , typename ValueType = float> void setValueAsString (const std::string & s) override
References PayloadDataAttachment< Payload, ValueType >::description, PayloadDataAttachment< Payload, ValueType >::isTemposynced, PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), and PayloadDataAttachment< Payload, ValueType >::stringToValue.
setValueFromModel()
template<typename Payload , typename ValueType = float> void setValueFromModel (const float & f) override
References PayloadDataAttachment< Payload, ValueType >::prevValue, and PayloadDataAttachment< Payload, ValueType >::value.
getMin()
template<typename Payload , typename ValueType = float> float getMin () const override
References PayloadDataAttachment< Payload, ValueType >::description.
getMax()
template<typename Payload , typename ValueType = float> float getMax () const override
References PayloadDataAttachment< Payload, ValueType >::description.
getDefaultValue()
template<typename Payload , typename ValueType = float> float getDefaultValue () const override
References PayloadDataAttachment< Payload, ValueType >::description.
isBipolar()
template<typename Payload , typename ValueType = float> bool isBipolar () const override
References PayloadDataAttachment< Payload, ValueType >::description.
andThenOnGui()
template<typename Payload , typename ValueType = float> void andThenOnGui (std::function< void(const PayloadDataAttachment< Payload, ValueType > &)> f)
References PayloadDataAttachment< Payload, ValueType >::onGuiValueChanged.
setTemposyncFunction()
template<typename Payload , typename ValueType = float> void setTemposyncFunction (std::function< bool(const PayloadDataAttachment< Payload, ValueType > &at)> f)
References PayloadDataAttachment< Payload, ValueType >::description, and PayloadDataAttachment< Payload, ValueType >::isTemposynced.
getFeatureState()
template<typename Payload , typename ValueType = float> sst::basic_blocks::params::ParamMetaData::FeatureState getFeatureState () const
References PayloadDataAttachment< Payload, ValueType >::isTemposynced.
Referenced by PayloadDataAttachment< Payload, ValueType >::getValueAsStringFor(), and PayloadDataAttachment< Payload, ValueType >::getValueAsStringWithoutUnitsFor().
Member Data Documentation
value
template<typename Payload , typename ValueType = float> ValueType& value
Referenced by PayloadDataAttachment< Payload, ValueType >::getValue(), PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), PayloadDataAttachment< Payload, ValueType >::setValueFromModel(), and ModRow< GZTrait >::updateTooltip().
prevValue
template<typename Payload , typename ValueType = float> ValueType prevValue
Referenced by PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), and PayloadDataAttachment< Payload, ValueType >::setValueFromModel().
label
template<typename Payload , typename ValueType = float> std::string label
Referenced by PayloadDataAttachment< Payload, ValueType >::getLabel().
onGuiValueChanged
template<typename Payload , typename ValueType = float> std::function<void(const PayloadDataAttachment &at)> onGuiValueChanged {nullptr}
Referenced by PayloadDataAttachment< Payload, ValueType >::andThenOnGui(), and PayloadDataAttachment< Payload, ValueType >::setValueFromGUI().
isTemposynced
template<typename Payload , typename ValueType = float> std::function<bool(const PayloadDataAttachment &at)> isTemposynced {nullptr}
Referenced by PayloadDataAttachment< Payload, ValueType >::getFeatureState(), PayloadDataAttachment< Payload, ValueType >::setTemposyncFunction(), PayloadDataAttachment< Payload, ValueType >::setValueAsString(), PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), and PayloadDataAttachment< Payload, ValueType >::setValueFromGUIQuantized().
description
template<typename Payload , typename ValueType = float> datamodel::pmd description
Referenced by PayloadDataAttachment< Payload, ValueType >::getDefaultValue(), PayloadDataAttachment< Payload, ValueType >::getMax(), PayloadDataAttachment< Payload, ValueType >::getMin(), PayloadDataAttachment< Payload, ValueType >::getValueAsStringFor(), PayloadDataAttachment< Payload, ValueType >::getValueAsStringWithoutUnitsFor(), PayloadDataAttachment< Payload, ValueType >::isBipolar(), PayloadDataAttachment< Payload, ValueType >::setTemposyncFunction(), PayloadDataAttachment< Payload, ValueType >::setValueAsString(), PayloadDataAttachment< Payload, ValueType >::setValueFromGUI(), PayloadDataAttachment< Payload, ValueType >::setValueFromGUIQuantized(), and ModRow< GZTrait >::updateTooltip().
valueToString
template<typename Payload , typename ValueType = float> std::function<std::string(float)> valueToString {nullptr}
Referenced by PayloadDataAttachment< Payload, ValueType >::getValueAsStringFor(), and PayloadDataAttachment< Payload, ValueType >::getValueAsStringWithoutUnitsFor().
stringToValue
template<typename Payload , typename ValueType = float> std::function<std::optional<float>(const std::string &)> stringToValue {nullptr}
Referenced by PayloadDataAttachment< Payload, ValueType >::setValueAsString().
The documentation for this struct was generated from the following file:
PayloadDataAttachment.h