shortcircuit-xt: ProcessorSwapSpec< ForZone > Struct Template Reference
ProcessorSwapSpec< ForZone > Struct Template Reference
#include <payload_undoable_items.h>
Public Types
using owner_t = std::conditional_t< ForZone, engine::Zone, engine::Group >
using routes_t = std::conditional_t< ForZone, decltype(voice::modulation::Matrix::RoutingTable::routes), decltype(modulation::GroupMatrix::RoutingTable::routes)>
using value_t = std::tuple< dsp::processor::ProcessorStorage, dsp::processor::ProcessorStorage, routes_t >
Static Public Member Functions
static std::string name ()
static owner_t & owner (engine::Engine &e, const ZoneAddress &a)
static value_t read (engine::Engine &e, const ZoneAddress &a, int32_t idx)
static void write (engine::Engine &e, const ZoneAddress &a, int32_t idx, const value_t &v)
Static Public Attributes
static constexpr bool forZone {ForZone}
Member Typedef Documentation
owner_t
template<bool ForZone> using owner_t = std::conditional_t<ForZone, engine::Zone, engine::Group>
routes_t
template<bool ForZone> using routes_t = std::conditional_t<ForZone, decltype(voice::modulation::Matrix::RoutingTable::routes), decltype(modulation::GroupMatrix::RoutingTable::routes)>
value_t
template<bool ForZone> using value_t = std::tuple<dsp::processor::ProcessorStorage, dsp::processor::ProcessorStorage, routes_t>
Member Function Documentation
name()
template<bool ForZone> static std::string name () static
owner()
template<bool ForZone> static owner_t & owner (engine::Engine & e, const ZoneAddress & a) static
References scxt::undo::groupAt(), and scxt::undo::zoneAt().
Referenced by ProcessorSwapSpec< ForZone >::read(), and ProcessorSwapSpec< ForZone >::write().
read()
template<bool ForZone> static value_t read (engine::Engine & e, const ZoneAddress & a, int32_t idx) static
References ProcessorSwapSpec< ForZone >::owner().
write()
template<bool ForZone> static void write (engine::Engine & e, const ZoneAddress & a, int32_t idx, const value_t & v) static
References ProcessorSwapSpec< ForZone >::owner().
Member Data Documentation
forZone
template<bool ForZone> constexpr bool forZone {ForZone} static constexpr
The documentation for this struct was generated from the following file:
payload_undoable_items.h