shortcircuit-xt: Engine::VoiceManagerResponder Struct Reference
Engine::VoiceManagerResponder Struct Reference
#include <engine.h>
Public Member Functions
VoiceManagerResponder (Engine &e)
void setVoiceEndCallback (std::function< void(voice::Voice *)> vec)
void doVoiceEndCallback (voice::Voice *v)
int32_t beginVoiceCreationTransaction (sst::voicemanager::VoiceBeginBufferEntry< VMConfig >::buffer_t &, uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity)
int32_t initializeMultipleVoices (int32_t voiceCount, const sst::voicemanager::VoiceInitInstructionsEntry< VMConfig >::buffer_t &, sst::voicemanager::VoiceInitBufferEntry< VMConfig >::buffer_t &voiceInitWorkingBuffer, uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity, float retune)
void endVoiceCreationTransaction (uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity)
void releaseVoice (voice::Voice *v, float velocity)
void terminateVoice (voice::Voice *v)
void discardHostVoice (int32_t voiceId)
void retriggerVoiceWithNewNoteID (voice::Voice *v, int32_t noteid, float velocity)
void moveVoice (typename VMConfig::voice_t *, uint16_t, uint16_t, uint16_t, float)
void moveAndRetriggerVoice (typename VMConfig::voice_t *, uint16_t, uint16_t, uint16_t, float)
void setVoiceMIDIMPEChannelPitchBend (voice::Voice *v, uint16_t pb14bit)
void setVoiceMIDIMPEChannelPressure (voice::Voice *v, int8_t val)
void setVoiceMIDIMPETimbre (voice::Voice *v, int8_t val)
void setVoicePolyphonicParameterModulation (voice::Voice *v, uint32_t parameter, double value)
void setVoiceMonophonicParameterModulation (voice::Voice *v, uint32_t parameter, double value)
void setNoteExpression (voice::Voice *v, int32_t expression, double value)
void setPolyphonicAftertouch (voice::Voice *v, int8_t pat)
Public Attributes
Engine & engine
std::array< Engine::pathToZone_t, maxVoices > findZoneWorkingBuffer {}
std::array< std::pair< Engine::pathToZone_t, int32_t >, maxVoices > voiceCreationWorkingBuffer {}
std::function< void(voice::Voice *)> voiceEndCallback {nullptr}
Constructor & Destructor Documentation
VoiceManagerResponder()
VoiceManagerResponder (Engine & e)
Member Function Documentation
setVoiceEndCallback()
void setVoiceEndCallback (std::function< void(voice::Voice *)> vec)
References Engine::VoiceManagerResponder::voiceEndCallback.
doVoiceEndCallback()
void doVoiceEndCallback (voice::Voice * v)
References Engine::VoiceManagerResponder::voiceEndCallback.
beginVoiceCreationTransaction()
int32_t beginVoiceCreationTransaction (sst::voicemanager::VoiceBeginBufferEntry< VMConfig >::buffer_t & buffer, uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity)
References Engine::VoiceManagerResponder::engine, Engine::findZone(), Engine::VoiceManagerResponder::findZoneWorkingBuffer, Engine::midikeyRetuner, MidikeyRetuner::remapKeyTo(), SCD, SCLOG_IF, Engine::VoiceManagerResponder::voiceCreationWorkingBuffer, and Engine::zoneByPath().
initializeMultipleVoices()
int32_t initializeMultipleVoices (int32_t voiceCount, const sst::voicemanager::VoiceInitInstructionsEntry< VMConfig >::buffer_t & voiceInstructionBuffer, sst::voicemanager::VoiceInitBufferEntry< VMConfig >::buffer_t & voiceInitWorkingBuffer, uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity, float retune)
References Zone::FORWARD_RR, Engine::initiateVoice(), Engine::midiNoteStateCounter, Zone::RANDOM_CYCLE, Zone::RANDOM_NOREPEAT, Engine::rng, SCLOG_IF, Zone::TRUE_RANDOM, Zone::UNISON, Voice::velocity, and Engine::zoneByPath().
endVoiceCreationTransaction()
void endVoiceCreationTransaction (uint16_t port, uint16_t channel, uint16_t key, int32_t noteId, float velocity)
References SCLOG_IF.
releaseVoice()
void releaseVoice (voice::Voice * v, float velocity)
References Voice::release(), and Voice::releaseVelocity.
terminateVoice()
void terminateVoice (voice::Voice * v)
References Voice::beginTerminationSequence(), Voice::isGated, Voice::isVoicePlaying, Voice::key, Voice::release(), and SCLOG_IF.
discardHostVoice()
void discardHostVoice (int32_t voiceId)
retriggerVoiceWithNewNoteID()
void retriggerVoiceWithNewNoteID (voice::Voice * v, int32_t noteid, float velocity)
References SCLOG_IF.
moveVoice()
void moveVoice (typename VMConfig::voice_t * v, uint16_t port, uint16_t channel, uint16_t key, float vel)
References Voice::calculateVoicePitch(), Voice::key, and Voice::originalMidiKey.
moveAndRetriggerVoice()
void moveAndRetriggerVoice (typename VMConfig::voice_t * v, uint16_t port, uint16_t channel, uint16_t key, float vel)
References Voice::calculateVoicePitch(), HasModulators< T, egsPerObject >::eg, HasModulators< T, egsPerObject >::egOS, Voice::key, Voice::originalMidiKey, and Voice::setIsGated().
setVoiceMIDIMPEChannelPitchBend()
void setVoiceMIDIMPEChannelPitchBend (voice::Voice * v, uint16_t pb14bit)
References Part::configuration, Voice::isVoiceAssigned, Voice::mpePitchBend, Part::PartConfiguration::mpePitchBendRange, Zone::parentGroup, Group::parentPart, and Voice::zone.
setVoiceMIDIMPEChannelPressure()
void setVoiceMIDIMPEChannelPressure (voice::Voice * v, int8_t val)
References Voice::isVoiceAssigned, Voice::mpePressure, Zone::parentGroup, Group::parentPart, and Voice::zone.
setVoiceMIDIMPETimbre()
void setVoiceMIDIMPETimbre (voice::Voice * v, int8_t val)
References Voice::isVoiceAssigned, Voice::mpeTimbre, Zone::parentGroup, Group::parentPart, and Voice::zone.
setVoicePolyphonicParameterModulation()
void setVoicePolyphonicParameterModulation (voice::Voice * v, uint32_t parameter, double value)
setVoiceMonophonicParameterModulation()
void setVoiceMonophonicParameterModulation (voice::Voice * v, uint32_t parameter, double value)
setNoteExpression()
void setNoteExpression (voice::Voice * v, int32_t expression, double value)
References Voice::BRIGHTNESS, Voice::noteExpressionCount, Voice::noteExpressionLags, and Voice::noteExpressions.
setPolyphonicAftertouch()
void setPolyphonicAftertouch (voice::Voice * v, int8_t pat)
References Voice::polyAT.
Member Data Documentation
engine
Engine& engine
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction().
findZoneWorkingBuffer
std::array<Engine::pathToZone_t, maxVoices> findZoneWorkingBuffer {}
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction().
voiceCreationWorkingBuffer
std::array<std::pair<Engine::pathToZone_t, int32_t>, maxVoices> voiceCreationWorkingBuffer {}
Referenced by Engine::VoiceManagerResponder::beginVoiceCreationTransaction().
voiceEndCallback
std::function<void(voice::Voice *)> voiceEndCallback {nullptr}
Referenced by Engine::VoiceManagerResponder::doVoiceEndCallback(), and Engine::VoiceManagerResponder::setVoiceEndCallback().
The documentation for this struct was generated from the following files:
engine.h
engine_voice_responder.cpp