shortcircuit-xt: SampleManager Struct Reference
SampleManager Struct Reference
#include <sample_manager.h>
Public Types
typedef std::vector< std::pair< SampleID, Sample::SampleFileAddress > > sampleAddressesAndIds_t
using sampleMap_t = std::unordered_map< SampleID, std::shared_ptr< Sample > >
Public Member Functions
SampleManager (const ThreadingChecker &t)
~SampleManager ()
void addSampleAsMissing (const SampleID &id, const Sample::SampleFileAddress &f)
std::optional< SampleID > loadSampleByFileAddress (const Sample::SampleFileAddress &, const SampleID &)
std::optional< SampleID > loadSampleByPath (const fs::path &)
std::optional< SampleID > loadSampleFromSF2 (const fs::path &, sf2::File *f, int preset, int instrument, int region)
int findSF2SampleIndexFor (sf2::File *, int preset, int instrument, int region)
std::optional< SampleID > loadSampleFromGIG (const fs::path &, gig::File *f, int preset, int instrument, int region)
std::optional< SampleID > loadSampleFromSCXTMonolith (const fs::path &, RIFF::File *f, int preset, int instrument, int region)
std::optional< SampleID > setupSampleFromMultifile (const fs::path &, const std::string &md5, int idx, void *data, size_t dataSize)
std::optional< SampleID > loadSampleFromMultiSample (const fs::path &, int idx, const SampleID &id)
std::shared_ptr< Sample > getSample (const SampleID &id) const
void reparentSamplesOnStreamToRelative (const fs::path &newParent)
void clearReparenting ()
void setRelativeRoot (const fs::path &p)
void clearRelativeRoot ()
void setMonolithBinaryIndex (const fs::path &p, const std::vector< fs::path > &idx)
void clearMonolithBinaryIndex ()
sampleAddressesAndIds_t getSampleAddressesAndIDs () const
sampleAddressesAndIds_t getSampleAddressesFor (const std::vector< SampleID > &) const
void restoreFromSampleAddressesAndIDs (const sampleAddressesAndIds_t &)
void purgeUnreferencedSamples ()
void reset ()
void addIdAlias (const SampleID &from, const SampleID &to)
SampleID resolveAlias (const SampleID &a)
sampleMap_t::const_iterator samplesBegin () const
sampleMap_t::const_iterator samplesEnd () const
Public Member Functions inherited from MoveableOnly< SampleManager >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Attributes
const ThreadingChecker & threadingChecker
fs::path reparentPath
fs::path relativeRoot
std::map< fs::path, int > monolithIndex
fs::path monolithPath
uint64_t streamingVersion {0x2112'01'01}
std::atomic< uint64_t > sampleMemoryInBytes {0}
Static Public Attributes
static constexpr const char * relativeSentinel = "SCXT_RELATIVE_PATH_MARKER"
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< SampleManager >
MoveableOnly ()
~MoveableOnly ()=default
Member Typedef Documentation
sampleAddressesAndIds_t
typedef std::vector<std::pair<SampleID, Sample::SampleFileAddress> > sampleAddressesAndIds_t
sampleMap_t
using sampleMap_t = std::unordered_map<SampleID, std::shared_ptr<Sample> >
Constructor & Destructor Documentation
SampleManager()
SampleManager (const ThreadingChecker & t)
~SampleManager()
~SampleManager ()
Member Function Documentation
addSampleAsMissing()
void addSampleAsMissing (const SampleID & id, const Sample::SampleFileAddress & f)
References SampleManager::addIdAlias(), Sample::createMissingPlaceholder(), Sample::SampleFileAddress::path, SCLOG_IF, and SampleID::setPathHash().
Referenced by SampleManager::restoreFromSampleAddressesAndIDs().
loadSampleByFileAddress()
std::optional< SampleID > loadSampleByFileAddress (const Sample::SampleFileAddress & addr, const SampleID & id)
References Sample::AIFF_FILE, Sample::FLAC_FILE, Sample::GIG_FILE, Sample::SampleFileAddress::instrument, SampleManager::loadSampleByPath(), SampleManager::loadSampleFromGIG(), SampleManager::loadSampleFromMultiSample(), SampleManager::loadSampleFromSCXTMonolith(), SampleManager::loadSampleFromSF2(), Sample::MP3_FILE, Sample::MULTISAMPLE_FILE, Sample::SampleFileAddress::path, Sample::SampleFileAddress::preset, Sample::SampleFileAddress::region, SCLOG, Sample::SCXT_FILE, Sample::SF2_FILE, Sample::SFZ_FILE, Sample::SampleFileAddress::type, and Sample::WAV_FILE.
Referenced by SampleManager::restoreFromSampleAddressesAndIDs().
loadSampleByPath()
std::optional< SampleID > loadSampleByPath (const fs::path & p)
References ThreadingChecker::isSerialThread(), SCLOG, SCLOG_IF, and SampleManager::threadingChecker.
Referenced by SampleManager::loadSampleByFileAddress().
loadSampleFromSF2()
std::optional< SampleID > loadSampleFromSF2 (const fs::path & p, sf2::File * f, int preset, int instrument, int region)
References scxt::infrastructure::createMD5SumFromFile(), SampleManager::findSF2SampleIndexFor(), SCLOG_IF, and Sample::SF2_FILE.
Referenced by SampleManager::loadSampleByFileAddress().
findSF2SampleIndexFor()
int findSF2SampleIndexFor (sf2::File * f, int preset, int instrument, int region)
Referenced by SampleManager::loadSampleFromSF2().
loadSampleFromGIG()
std::optional< SampleID > loadSampleFromGIG (const fs::path & p, gig::File * f, int preset, int instrument, int region)
References scxt::infrastructure::createMD5SumFromFile(), Sample::GIG_FILE, and SCLOG_IF.
Referenced by SampleManager::loadSampleByFileAddress().
loadSampleFromSCXTMonolith()
std::optional< SampleID > loadSampleFromSCXTMonolith (const fs::path & p, RIFF::File * f, int preset, int instrument, int region)
References scxt::infrastructure::createMD5SumFromFile(), SCLOG_IF, and Sample::SCXT_FILE.
Referenced by SampleManager::loadSampleByFileAddress().
setupSampleFromMultifile()
std::optional< SampleID > setupSampleFromMultifile (const fs::path & p, const std::string & md5, int idx, void * data, size_t dataSize)
References Sample::MULTISAMPLE_FILE.
loadSampleFromMultiSample()
std::optional< SampleID > loadSampleFromMultiSample (const fs::path & p, int idx, const SampleID & id)
References Sample::MULTISAMPLE_FILE, and SCLOG_IF.
Referenced by SampleManager::loadSampleByFileAddress().
getSample()
std::shared_ptr< Sample > getSample (const SampleID & id) const
References SampleManager::getSample().
Referenced by Zone::attachToSample(), SampleManager::getSample(), SampleManager::getSampleAddressesFor(), SampleWaveform::paint(), VariantDisplay::rebuild(), SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), VariantDisplay::selectNextFile(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
reparentSamplesOnStreamToRelative()
void reparentSamplesOnStreamToRelative (const fs::path & newParent)
References SampleManager::relativeSentinel, and SampleManager::reparentPath.
clearReparenting()
void clearReparenting ()
References SampleManager::reparentPath.
setRelativeRoot()
void setRelativeRoot (const fs::path & p)
References SampleManager::relativeRoot.
clearRelativeRoot()
void clearRelativeRoot ()
References SampleManager::relativeRoot.
setMonolithBinaryIndex()
void setMonolithBinaryIndex (const fs::path & p, const std::vector< fs::path > & idx)
References SampleManager::monolithIndex, and SampleManager::monolithPath.
clearMonolithBinaryIndex()
void clearMonolithBinaryIndex ()
References SampleManager::monolithIndex, and SampleManager::monolithPath.
getSampleAddressesAndIDs()
sampleAddressesAndIds_t getSampleAddressesAndIDs () const
References SampleManager::reparentPath, and SCLOG_IF.
getSampleAddressesFor()
SampleManager::sampleAddressesAndIds_t getSampleAddressesFor (const std::vector< SampleID > & sids) const
References SampleManager::getSample(), and SCLOG.
restoreFromSampleAddressesAndIDs()
void restoreFromSampleAddressesAndIDs (const sampleAddressesAndIds_t & r)
References SampleManager::addIdAlias(), SampleManager::addSampleAsMissing(), SampleManager::loadSampleByFileAddress(), SampleManager::monolithIndex, SampleManager::monolithPath, Sample::SampleFileAddress::path, SampleManager::relativeRoot, SampleManager::relativeSentinel, SCLOG_IF, and Sample::SCXT_FILE.
purgeUnreferencedSamples()
void purgeUnreferencedSamples ()
References SCLOG_IF.
reset()
void reset ()
References SampleManager::streamingVersion.
addIdAlias()
void addIdAlias (const SampleID & from, const SampleID & to)
Referenced by SampleManager::addSampleAsMissing(), and SampleManager::restoreFromSampleAddressesAndIDs().
resolveAlias()
SampleID resolveAlias (const SampleID & a)
References SampleManager::resolveAlias().
Referenced by SampleManager::resolveAlias().
samplesBegin()
sampleMap_t::const_iterator samplesBegin () const
samplesEnd()
sampleMap_t::const_iterator samplesEnd () const
Member Data Documentation
threadingChecker
const ThreadingChecker& threadingChecker
Referenced by SampleManager::loadSampleByPath().
reparentPath
fs::path reparentPath
Referenced by SampleManager::clearReparenting(), SampleManager::getSampleAddressesAndIDs(), and SampleManager::reparentSamplesOnStreamToRelative().
relativeSentinel
constexpr const char* relativeSentinel = "SCXT_RELATIVE_PATH_MARKER" static constexpr
Referenced by SampleManager::reparentSamplesOnStreamToRelative(), and SampleManager::restoreFromSampleAddressesAndIDs().
relativeRoot
fs::path relativeRoot
Referenced by SampleManager::clearRelativeRoot(), SampleManager::restoreFromSampleAddressesAndIDs(), and SampleManager::setRelativeRoot().
monolithIndex
std::map<fs::path, int> monolithIndex
Referenced by SampleManager::clearMonolithBinaryIndex(), SampleManager::restoreFromSampleAddressesAndIDs(), and SampleManager::setMonolithBinaryIndex().
monolithPath
fs::path monolithPath
Referenced by SampleManager::clearMonolithBinaryIndex(), SampleManager::restoreFromSampleAddressesAndIDs(), and SampleManager::setMonolithBinaryIndex().
streamingVersion
uint64_t streamingVersion {0x2112'01'01}
Referenced by SampleManager::reset().
sampleMemoryInBytes
std::atomic<uint64_t> sampleMemoryInBytes {0}
Referenced by SCXTEditor::idle().
The documentation for this struct was generated from the following files:
sample_manager.h
sample_manager.cpp