shortcircuit-xt: Part Struct Reference
Part Struct Reference
#include <part.h>
Classes
struct MacroUILagHandler
struct PartConfiguration
struct ZoneMappingItem
Utility data structures to allow rapid draws and displays of the structure in clients.
Public Types
enum LagIndexes { pitchBend , numLags }
using zoneMappingItem_t = ZoneMappingItem
typedef std::vector< ZoneMappingItem > zoneMappingSummary_t
typedef std::vector< std::unique_ptr< Group > > groupContainer_t
Public Member Functions
Part (int16_t c)
virtual ~Part ()=default
bool respondsToMIDIChannelExcludingGroupMask (int16_t channel) const
bool respondsToMIDIChannel (int16_t channel) const
bool isMPEVoiceChannel (int16_t channel) const
int getChannelBasedTransposition (int16_t channel) const
void rebuildGroupChannelMask ()
void process (Engine &onto)
std::string getName () const
size_t getNumOutputs () const
size_t addGroup ()
void guaranteeGroupCount (size_t count)
zoneMappingSummary_t getZoneMappingSummary ()
const std::unique_ptr< Group > & getGroup (size_t i) const
bool isActive ()
void addActiveGroup ()
void removeActiveGroup ()
void moveGroupToAfter (size_t whichGroup, size_t toAfter)
void swapGroups (size_t groupA, size_t groupB)
void onSampleRateChanged () override
const groupContainer_t & getGroups () const
void clearGroups ()
int getGroupIndex (const GroupID &zid) const
std::unique_ptr< Group > removeGroup (const GroupID &zid)
groupContainer_t::iterator begin () noexcept
groupContainer_t::const_iterator cbegin () const noexcept
groupContainer_t::iterator end () noexcept
groupContainer_t::const_iterator cend () const noexcept
std::vector< SampleID > getSamplesUsedByPart () const
void setBusEffectType (Engine &e, int idx, AvailableBusEffects t)
void initializeAfterUnstream (Engine &e)
void sendAllBusEffectInfoToClient (const Engine &e)
void sendBusEffectInfoToClient (const Engine &, int slot)
void prepareToStream ()
Public Member Functions inherited from MoveableOnly< Part >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Public Attributes
PartID id
int16_t partNumber
Patch * parentPatch {nullptr}
std::array< bool, 16 > groupChannelMask {}
struct scxt::engine::Part::PartConfiguration configuration
GroupTriggerInstrumentState groupTriggerInstrumentState
The state of this part for group trigger caches and so on.
uint32_t activeGroups {0}
size_t silenceTime {0}
size_t silenceMax {0}
std::array< float, 128 > midiCCValues {}
float channelAT {0.f}
float pitchBendValue {0.f}
scxt::engine::Part::MacroUILagHandler * this
sst::basic_blocks::dsp::LagCollection< numLags > externalSignalLag
std::array< Macro, macrosPerPart > macros
std::array< BusEffectStorage, maxEffectsPerPart > partEffectStorage {}
std::array< std::unique_ptr< BusEffect >, maxEffectsPerPart > partEffects {}
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Part >
MoveableOnly ()
~MoveableOnly ()=default
Member Typedef Documentation
zoneMappingItem_t
using zoneMappingItem_t = ZoneMappingItem
zoneMappingSummary_t
typedef std::vector<ZoneMappingItem> zoneMappingSummary_t
groupContainer_t
typedef std::vector<std::unique_ptr<Group> > groupContainer_t
Member Enumeration Documentation
LagIndexes
enum LagIndexes
Enumerator
pitchBend
numLags
Constructor & Destructor Documentation
Part()
Part (int16_t c)
References Part::PartConfiguration::active, Part::PartConfiguration::channel, Part::configuration, Macro::defaultNameFor(), Part::groupChannelMask, Part::macros, Part::PartConfiguration::name, and Part::partNumber.
~Part()
virtual ~Part () virtual default
Member Function Documentation
respondsToMIDIChannelExcludingGroupMask()
bool respondsToMIDIChannelExcludingGroupMask (int16_t channel) const
References Part::PartConfiguration::channel, Part::PartConfiguration::chPerOctaveChannel, Part::configuration, Part::PartConfiguration::mpeChannel, and Part::PartConfiguration::omniChannel.
Referenced by Part::respondsToMIDIChannel().
respondsToMIDIChannel()
bool respondsToMIDIChannel (int16_t channel) const
References Part::groupChannelMask, and Part::respondsToMIDIChannelExcludingGroupMask().
isMPEVoiceChannel()
bool isMPEVoiceChannel (int16_t channel) const
References Part::PartConfiguration::channel, Part::configuration, Part::PartConfiguration::mpeChannel, and Part::PartConfiguration::mpeGlobalChannel.
getChannelBasedTransposition()
int getChannelBasedTransposition (int16_t channel) const
References Part::PartConfiguration::channel, Part::PartConfiguration::chPerOctaveChannel, Part::configuration, MidikeyRetuner::getRepetitionInterval(), Engine::midikeyRetuner, Patch::parentEngine, and Part::parentPatch.
rebuildGroupChannelMask()
void rebuildGroupChannelMask ()
References Part::groupChannelMask.
Referenced by Part::initializeAfterUnstream(), and Group::onGroupMidiChannelSubscriptionChanged().
process()
void process (Engine & onto)
References Part::configuration, scxt::engine::DEFAULT_BUS, Part::externalSignalLag, Engine::getPatch(), Part::isActive(), Part::PartConfiguration::level, Part::PartConfiguration::pan, scxt::engine::PART_0, Part::partEffects, Part::partEffectStorage, Part::partNumber, Part::PartConfiguration::routeTo, Part::silenceMax, and Part::silenceTime.
getName()
std::string getName () const
References Part::PartConfiguration::channel, Part::configuration, and Part::PartConfiguration::omniChannel.
getNumOutputs()
size_t getNumOutputs () const
addGroup()
size_t addGroup ()
References SampleRateSupport::getSampleRate().
Referenced by Part::guaranteeGroupCount().
guaranteeGroupCount()
void guaranteeGroupCount (size_t count)
References Part::addGroup().
getZoneMappingSummary()
Part::zoneMappingSummary_t getZoneMappingSummary ()
References scxt::engine::MISSING_SAMPLE, and Part::partNumber.
getGroup()
const std::unique_ptr< Group > & getGroup (size_t i) const
References scxt::printStackTrace().
isActive()
bool isActive ()
References Part::PartConfiguration::active, Part::activeGroups, Part::configuration, Part::partNumber, SCLOG_IF, Part::silenceMax, and Part::silenceTime.
Referenced by Part::process().
addActiveGroup()
void addActiveGroup ()
References Part::activeGroups.
Referenced by Group::addActiveZone().
removeActiveGroup()
void removeActiveGroup ()
References Part::activeGroups.
Referenced by Group::processWithOS().
moveGroupToAfter()
void moveGroupToAfter (size_t whichGroup, size_t toAfter)
swapGroups()
void swapGroups (size_t groupA, size_t groupB)
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References Part::externalSignalLag, Part::partEffects, and SampleRateSupport::samplerate.
getGroups()
const groupContainer_t & getGroups () const
clearGroups()
void clearGroups ()
getGroupIndex()
int getGroupIndex (const GroupID & zid) const
Referenced by Part::removeGroup().
removeGroup()
std::unique_ptr< Group > removeGroup (const GroupID & zid)
References Part::getGroupIndex().
begin()
groupContainer_t::iterator begin () noexcept
cbegin()
groupContainer_t::const_iterator cbegin () const noexcept
end()
groupContainer_t::iterator end () noexcept
cend()
groupContainer_t::const_iterator cend () const noexcept
getSamplesUsedByPart()
std::vector< SampleID > getSamplesUsedByPart () const
setBusEffectType()
void setBusEffectType (Engine & e, int idx, AvailableBusEffects t)
References scxt::engine::createEffect(), Part::partEffects, and Part::partEffectStorage.
initializeAfterUnstream()
void initializeAfterUnstream (Engine & e)
References scxt::engine::createEffect(), Part::partEffects, Part::partEffectStorage, Part::rebuildGroupChannelMask(), and Part::sendBusEffectInfoToClient().
sendAllBusEffectInfoToClient()
void sendAllBusEffectInfoToClient (const Engine & e)
References Part::sendBusEffectInfoToClient().
sendBusEffectInfoToClient()
void sendBusEffectInfoToClient (const Engine & e, int slot)
References Engine::getMessageController(), BusEffectStorage::maxBusEffectParams, Part::partEffects, Part::partEffectStorage, Part::partNumber, scxt::messaging::client::s2c_bus_effect_full_data, and scxt::messaging::client::serializationSendToClient().
Referenced by Part::initializeAfterUnstream(), and Part::sendAllBusEffectInfoToClient().
prepareToStream()
void prepareToStream ()
Member Data Documentation
id
PartID id
partNumber
int16_t partNumber
Referenced by Part::getZoneMappingSummary(), Part::isActive(), Part::Part(), Part::process(), and Part::sendBusEffectInfoToClient().
parentPatch
Patch* parentPatch {nullptr}
Referenced by Part::getChannelBasedTransposition(), Group::getEngine(), and Group::getEngine().
groupChannelMask
std::array<bool, 16> groupChannelMask {}
Referenced by Part::Part(), Part::rebuildGroupChannelMask(), and Part::respondsToMIDIChannel().
configuration
struct scxt::engine::Part::PartConfiguration configuration
Referenced by Voice::calculateGeneratorRatio(), Part::getChannelBasedTransposition(), Part::getName(), Part::isActive(), Part::isMPEVoiceChannel(), Part::Part(), Part::process(), Part::respondsToMIDIChannelExcludingGroupMask(), and Engine::VoiceManagerResponder::setVoiceMIDIMPEChannelPitchBend().
groupTriggerInstrumentState
GroupTriggerInstrumentState groupTriggerInstrumentState
The state of this part for group trigger caches and so on.
Referenced by Group::setupOnUnstream().
activeGroups
uint32_t activeGroups {0}
Referenced by Part::addActiveGroup(), Part::isActive(), and Part::removeActiveGroup().
silenceTime
size_t silenceTime {0}
Referenced by Part::isActive(), and Part::process().
silenceMax
size_t silenceMax {0}
Referenced by Part::isActive(), and Part::process().
midiCCValues
std::array<float, 128> midiCCValues {}
Referenced by GroupMatrixEndpoints::Sources::bind(), MatrixEndpoints::Sources::bind(), and GTMIDI1CC::value().
channelAT
float channelAT {0.f}
Referenced by GroupMatrixEndpoints::Sources::bind(), and MatrixEndpoints::Sources::bind().
pitchBendValue
float pitchBendValue {0.f}
Referenced by GroupMatrixEndpoints::Sources::bind(), MatrixEndpoints::Sources::bind(), and Voice::calculateVoicePitch().
this
scxt::engine::Part::MacroUILagHandler* this
externalSignalLag
sst::basic_blocks::dsp::LagCollection<numLags> externalSignalLag
Referenced by Part::onSampleRateChanged(), and Part::process().
macros
std::array<Macro, macrosPerPart> macros
Referenced by Part::Part(), Part::MacroUILagHandler::updateDestination(), and GTMacro::value().
partEffectStorage
std::array<BusEffectStorage, maxEffectsPerPart> partEffectStorage {}
Referenced by Part::initializeAfterUnstream(), Part::process(), Part::sendBusEffectInfoToClient(), and Part::setBusEffectType().
partEffects
std::array<std::unique_ptr<BusEffect>, maxEffectsPerPart> partEffects {}
Referenced by Part::initializeAfterUnstream(), Part::onSampleRateChanged(), Part::process(), Part::sendBusEffectInfoToClient(), and Part::setBusEffectType().
The documentation for this struct was generated from the following files:
part.h
part.cpp