shortcircuit-xt: Engine::MonoVoiceManagerResponder Struct Reference
Engine::MonoVoiceManagerResponder Struct Reference
#include <engine.h>
Public Member Functions
MonoVoiceManagerResponder (Engine &e)
void setMIDIPitchBend (int16_t channel, int16_t pb14bit)
void setMIDI1CC (int16_t channel, int16_t cc, int8_t val)
void setMIDIChannelPressure (int16_t channel, int16_t pres)
Public Attributes
Engine & engine
Constructor & Destructor Documentation
MonoVoiceManagerResponder()
MonoVoiceManagerResponder (Engine & e)
Member Function Documentation
setMIDIPitchBend()
void setMIDIPitchBend (int16_t channel, int16_t pb14bit)
References Engine::getPatch(), and Part::pitchBend.
setMIDI1CC()
void setMIDI1CC (int16_t channel, int16_t cc, int8_t val)
References Engine::getPatch().
setMIDIChannelPressure()
void setMIDIChannelPressure (int16_t channel, int16_t pres)
References Engine::getPatch().
Member Data Documentation
engine
Engine& engine
The documentation for this struct was generated from the following files:
engine.h
engine_voice_responder.cpp