shortcircuit-xt: Sample Struct Reference
Sample Struct Reference
Classes
struct SampleFileAddress
Public Types
enum SourceType {
WAV_FILE , SF2_FILE , FLAC_FILE , MP3_FILE ,
AIFF_FILE , MULTISAMPLE_FILE
}
enum BitDepth { BD_I16 , BD_F32 }
enum PlayMode : uint8_t {
pm_forward = 0 , pm_forward_loop , pm_forward_loop_until_release , pm_forward_loop_bidirectional ,
pm_forward_shot , pm_forward_hitpoints , pm_forward_release , n_playmodes ,
pm_forwardRIFF = 0 , pm_forward_loopRIFF = 1 , pm_forward_loop_until_releaseRIFF = 3 , pm_forward_loop_bidirectionalRIFF = 4 ,
pm_forward_shotRIFF = 5 , pm_forward_hitpointsRIFF = 6 , pm_forward_releaseRIFF = 7
}
Public Member Functions
Sample ()
Sample (const SampleID &sid)
virtual ~Sample ()
void dumpInformationToLog ()
std::string getDisplayName () const
bool load (const fs::path &path)
bool loadFromSF2 (const fs::path &path, sf2::File *f, int preset, int inst, int region)
const fs::path & getPath () const
std::string getMD5Sum () const
int getCompoundPreset () const
int getCompoundInstrument () const
int getCompoundRegion () const
SampleFileAddress getSampleFileAddress () const
size_t getDataSize () const
size_t getSampleLength () const
std::string getBitDepthText () const
bool parseFlac (const fs::path &p)
bool parseMP3 (const fs::path &p)
bool parse_riff_wave (void *data, size_t filesize, bool skip_riffchunk=false)
bool parse_aiff (void *data, size_t filesize)
short * GetSamplePtrI16 (int Channel)
float * GetSamplePtrF32 (int Channel)
char * GetName ()
size_t SaveWaveChunk (void *data)
bool save_wave_file (const fs::path &filename)
void init_grains ()
bool allocateI16 (int Channel, int Samples)
bool allocateF32 (int Channel, int Samples)
bool load_data_ui8 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i8 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i16 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i16BE (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i24 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i24BE (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i32 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_i32BE (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_f32 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool load_data_f64 (int channel, void *data, unsigned int samplesize, unsigned int stride)
bool SetMeta (unsigned int channels, unsigned int SampleRate, unsigned int SampleLength)
Public Member Functions inherited from MoveableOnly< Sample >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Static Public Member Functions
static std::string bitDepthName (BitDepth bd)
static constexpr int bitDepthByteSize (BitDepth bd)
Public Attributes
enum scxt::sample::Sample::SourceType WAV_FILE
std::string displayName {}
std::string md5Sum {}
int preset {-1}
int instrument {-1}
int region {-1}
void *__restrict sampleData [2] {nullptr, nullptr}
enum scxt::sample::Sample::BitDepth BD_F32
uint8_t channels {0}
bool Embedded {false}
uint32_t sample_length {0}
uint32_t sample_rate {1}
float InvSampleRate {1}
uint32_t * graintable {nullptr}
int num_grains {0}
bool grains_initialized {false}
char name [64] {'\0'}
struct {
char key_low {0}
char key_high {0}
char key_root {0}
char vel_low {0}
char vel_high {0}
PlayMode playmode {pm_forward}
float detune {0}
unsigned int loop_start {0}
unsigned int loop_end {0}
bool rootkey_present {false}
bool key_present {false}
bool vel_present {false}
bool loop_present {false}
bool playmode_present {false}
int n_slices {0}
int * slice_start {nullptr}
int * slice_end {nullptr}
int n_beats {0}
} meta
bool sample_loaded {false}
fs::path mFileName {}
SampleID id
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< Sample >
MoveableOnly ()
~MoveableOnly ()=default
Member Enumeration Documentation
SourceType
enum SourceType
Enumerator
WAV_FILE
SF2_FILE
FLAC_FILE
MP3_FILE
AIFF_FILE
MULTISAMPLE_FILE
BitDepth
enum BitDepth
Enumerator
BD_I16
BD_F32
PlayMode
enum PlayMode : uint8_t
Enumerator
pm_forward
pm_forward_loop
pm_forward_loop_until_release
pm_forward_loop_bidirectional
pm_forward_shot
pm_forward_hitpoints
pm_forward_release
n_playmodes
pm_forwardRIFF
pm_forward_loopRIFF
pm_forward_loop_until_releaseRIFF
pm_forward_loop_bidirectionalRIFF
pm_forward_shotRIFF
pm_forward_hitpointsRIFF
pm_forward_releaseRIFF
Constructor & Destructor Documentation
Sample() [1/2]
Sample ()
Sample() [2/2]
Sample (const SampleID & sid)
~Sample()
~Sample () virtual
Member Function Documentation
dumpInformationToLog()
void dumpInformationToLog ()
References scxt::dsp::I16InvScale, and SCLOG.
getDisplayName()
std::string getDisplayName () const
References Sample::displayName.
load()
bool load (const fs::path & path)
References scxt::infrastructure::createMD5SumFromFile(), and scxt::extensionMatches().
loadFromSF2()
bool loadFromSF2 (const fs::path & path, sf2::File * f, int preset, int inst, int region)
References SCD, and SCLOG.
getPath()
const fs::path& getPath () const
References Sample::mFileName.
Referenced by Sample::getSampleFileAddress().
getMD5Sum()
std::string getMD5Sum () const
References Sample::md5Sum.
Referenced by Sample::getSampleFileAddress().
getCompoundPreset()
int getCompoundPreset () const
References Sample::preset.
Referenced by Sample::getSampleFileAddress().
getCompoundInstrument()
int getCompoundInstrument () const
References Sample::instrument.
Referenced by Sample::getSampleFileAddress().
getCompoundRegion()
int getCompoundRegion () const
References Sample::region.
Referenced by Sample::getSampleFileAddress().
getSampleFileAddress()
SampleFileAddress getSampleFileAddress () const
References Sample::getCompoundInstrument(), Sample::getCompoundPreset(), Sample::getCompoundRegion(), Sample::getMD5Sum(), Sample::getPath(), and SCLOG.
getDataSize()
size_t getDataSize () const
References Sample::bitDepthByteSize(), Sample::channels, and Sample::sample_length.
getSampleLength()
size_t getSampleLength () const
References Sample::sample_length.
getBitDepthText()
std::string getBitDepthText () const
References Sample::bitDepthName().
parseFlac()
bool parseFlac (const fs::path & p)
parseMP3()
bool parseMP3 (const fs::path & p)
parse_riff_wave()
bool parse_riff_wave (void * data, size_t filesize, bool skip_riffchunk = false)
References Sample::channels, SamplerChunk::cSampleLoops, wave_inst_chunk::detune_cents, SampleLoop::dwEnd, SamplerChunk::dwMIDIUnityNote, CuePoint::dwSampleOffset, SampleLoop::dwStart, SampleLoop::dwType, wave_inst_chunk::key_high, wave_inst_chunk::key_low, wave_inst_chunk::key_root, Sample::load_data_f32(), Sample::load_data_f64(), Sample::load_data_i16(), Sample::load_data_i24(), Sample::load_data_i32(), Sample::load_data_ui8(), Sample::meta, scxt::sample::loaders::mf_FromCurrent, scxt::sample::loaders::mf_FromStart, wave_acid_chunk::n_beats, Sample::name, wavheader::nChannels, wavheader::nSamplesPerSec, Sample::pm_forward_hitpoints, Sample::pm_forward_loop, Sample::pm_forward_loop_bidirectional, RIFFMemFile::Read(), RIFFMemFile::ReadDWORD(), RIFFMemFile::ReadPtr(), RIFFMemFile::riff_descend(), RIFFMemFile::riff_descend_RIFF_or_LIST(), RIFFMemFile::RIFFAscend(), RIFFMemFile::RIFFDescendSearch(), RIFFMemFile::RIFFPeekChunk(), RIFFMemFile::RIFFReadChunk(), RIFFMemFile::RIFFSkipChunk(), Sample::sample_length, Sample::sample_loaded, SCD, SCLOG, RIFFMemFile::SeekI(), Sample::SetMeta(), wave_strc_entry::spos1, wave_strc_header::subchunks, RIFFMemFile::TellI(), wave_acid_chunk::type, wave_inst_chunk::vel_high, wave_inst_chunk::vel_low, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_PCM, wavheader::wBitsPerSample, and wavheader::wFormatTag.
parse_aiff()
bool parse_aiff (void * data, size_t filesize)
References aiff_INST_chunk::baseNote, Sample::channels, scxt::sample::ConvertFromIeeeExtended(), aiff_INST_chunk::detune, aiff_INST_chunk::highNote, aiff_INST_chunk::highvelocity, aiff_marker::id, Sample::id, RIFFMemFile::iff_descend(), RIFFMemFile::iff_descend_FORM(), Sample::load_data_i16BE(), Sample::load_data_i24BE(), Sample::load_data_i32BE(), Sample::load_data_i8(), aiff_INST_chunk::lowNote, aiff_INST_chunk::lowvelocity, aiff_loop::marker_end, aiff_loop::marker_start, Sample::meta, scxt::sample::loaders::mf_FromCurrent, aiff_CommonChunk::numChannels, aiff_CommonChunk::numSampleFrames, aiff_loop::playmode, Sample::pm_forward_loop, Sample::pm_forward_loop_bidirectional, aiff_marker::pos, RIFFMemFile::Read(), RIFFMemFile::ReadDWORD(), RIFFMemFile::ReadPtr(), RIFFMemFile::ReadWORD(), Sample::sample_loaded, Sample::sampleData, aiff_CommonChunk::sampleRate, aiff_CommonChunk::sampleSize, RIFFMemFile::SeekI(), Sample::SetMeta(), RIFFMemFile::SkipPSTRING(), aiff_INST_chunk::sustainLoop, RIFFMemFile::TellI(), and RIFFMemFile::useWaveEndian.
GetSamplePtrI16()
short * GetSamplePtrI16 (int Channel)
Referenced by Sample::SaveWaveChunk().
GetSamplePtrF32()
float * GetSamplePtrF32 (int Channel)
Referenced by Sample::SaveWaveChunk().
GetName()
char* GetName ()
SaveWaveChunk()
size_t SaveWaveChunk (void * data)
References Sample::channels, Sample::GetSamplePtrF32(), Sample::GetSamplePtrI16(), Sample::name, Sample::sample_length, Sample::sample_rate, WAVE_FORMAT_IEEE_FLOAT, and WAVE_FORMAT_PCM.
Referenced by Sample::save_wave_file().
save_wave_file()
bool save_wave_file (const fs::path & filename)
References Sample::SaveWaveChunk().
bitDepthName()
static std::string bitDepthName (BitDepth bd) static
References Sample::BD_F32, and Sample::BD_I16.
Referenced by Sample::getBitDepthText().
bitDepthByteSize()
static constexpr int bitDepthByteSize (BitDepth bd) static constexpr
References Sample::BD_F32, and Sample::BD_I16.
Referenced by Sample::getDataSize().
init_grains()
void init_grains ()
allocateI16()
bool allocateI16 (int Channel, int Samples)
allocateF32()
bool allocateF32 (int Channel, int Samples)
load_data_ui8()
bool load_data_ui8 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
load_data_i8()
bool load_data_i8 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_aiff().
load_data_i16()
bool load_data_i16 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
load_data_i16BE()
bool load_data_i16BE (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_aiff().
load_data_i24()
bool load_data_i24 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
load_data_i24BE()
bool load_data_i24BE (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_aiff().
load_data_i32()
bool load_data_i32 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
load_data_i32BE()
bool load_data_i32BE (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_aiff().
load_data_f32()
bool load_data_f32 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
load_data_f64()
bool load_data_f64 (int channel, void * data, unsigned int samplesize, unsigned int stride)
Referenced by Sample::parse_riff_wave().
SetMeta()
bool SetMeta (unsigned int channels, unsigned int SampleRate, unsigned int SampleLength)
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
Member Data Documentation
WAV_FILE
enum scxt::sample::Sample::SourceType WAV_FILE
Referenced by SampleManager::restoreFromSampleAddressesAndIDs(), and scxt::json::SC_STREAMDEF().
displayName
std::string displayName {}
Referenced by Sample::getDisplayName().
md5Sum
std::string md5Sum {}
Referenced by Sample::getMD5Sum().
preset
int preset {-1}
Referenced by Sample::getCompoundPreset().
instrument
int instrument {-1}
Referenced by Sample::getCompoundInstrument().
region
int region {-1}
Referenced by Sample::getCompoundRegion().
sampleData
void* __restrict sampleData[2] {nullptr, nullptr}
Referenced by Sample::parse_aiff().
BD_F32
enum scxt::sample::Sample::BitDepth BD_F32
Referenced by Sample::bitDepthByteSize(), Sample::bitDepthName(), scxt::dsp::sample_analytics::computePeak(), scxt::dsp::sample_analytics::computeRMS(), Voice::initializeGenerator(), and SampleWaveform::rebuildEnvelopePaths().
channels
uint8_t channels {0}
Referenced by Sample::getDataSize(), Sample::parse_aiff(), Sample::parse_riff_wave(), and Sample::SaveWaveChunk().
Embedded
bool Embedded {false}
sample_length
uint32_t sample_length {0}
Referenced by Sample::getDataSize(), Sample::getSampleLength(), Sample::parse_riff_wave(), and Sample::SaveWaveChunk().
sample_rate
uint32_t sample_rate {1}
Referenced by Sample::SaveWaveChunk().
InvSampleRate
float InvSampleRate {1}
graintable
uint32_t* graintable {nullptr}
num_grains
int num_grains {0}
grains_initialized
bool grains_initialized {false}
name
char name[64] {'\0'}
Referenced by Sample::parse_riff_wave(), and Sample::SaveWaveChunk().
key_low
char key_low {0}
key_high
char key_high {0}
key_root
char key_root {0}
vel_low
char vel_low {0}
vel_high
char vel_high {0}
playmode
PlayMode playmode {pm_forward}
detune
float detune {0}
loop_start
unsigned int loop_start {0}
loop_end
unsigned int loop_end {0}
rootkey_present
bool rootkey_present {false}
key_present
bool key_present {false}
vel_present
bool vel_present {false}
loop_present
bool loop_present {false}
playmode_present
bool playmode_present {false}
n_slices
int n_slices {0}
slice_start
int* slice_start {nullptr}
slice_end
int* slice_end {nullptr}
n_beats
int n_beats {0}
struct { ... } meta
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
sample_loaded
bool sample_loaded {false}
Referenced by Sample::parse_aiff(), and Sample::parse_riff_wave().
mFileName
fs::path mFileName {}
Referenced by Sample::getPath().
id
SampleID id
Referenced by Sample::parse_aiff().
The documentation for this struct was generated from the following files:
sample.h
load_aiff.cpp
load_flac.cpp
load_mp3.cpp
load_riff_wave.cpp
sample.cpp