shortcircuit-xt: EXSParameters Struct Reference
EXSParameters Struct Reference
Public Member Functions
EXSParameters (EXSBlock in)
void parse ()
Public Member Functions inherited from EXSObject
EXSObject (EXSBlock in)
void resetPosition ()
void skip (int S)
int32_t readByteToInt ()
uint8_t readByte ()
int16_t readS16 ()
uint16_t readU16 ()
uint32_t readU32 ()
std::string readStringNoTerm (size_t chars)
std::string readStringNullTerm (size_t chars)
Public Attributes
std::map< uint16_t, int16_t > params
Public Attributes inherited from EXSObject
EXSBlock within
size_t position {0}
Constructor & Destructor Documentation
EXSParameters()
EXSParameters (EXSBlock in)
References EXSParameters::parse(), EXSBlock::size, EXSBlock::type, and EXSBlock::TYPE_PARAMS.
Member Function Documentation
parse()
void parse ()
References EXSBlock::content, EXSParameters::params, EXSObject::position, EXSObject::readS16(), EXSObject::readU16(), EXSObject::readU32(), EXSBlock::size, and EXSObject::within.
Referenced by EXSParameters::EXSParameters().
Member Data Documentation
params
std::map<uint16_t, int16_t> params
Referenced by EXSParameters::parse().
The documentation for this struct was generated from the following file:
exs_import.cpp