shortcircuit-xt: ModRow< GZTrait >::ReScaler Struct Reference
ModRow< GZTrait >::ReScaler Struct Reference
Inherits Continuous.
Public Member Functions
ReScaler (ModRow *parentRow, sst::jucegui::data::Continuous *u)
std::string getLabel () const override
float scaleFromUnder (float f) const
float scaleToUnder (float f) const
float getValue () const override
float getValue01 () override
void setValueFromGUI (const float &f) override
void setValueFromGUIQuantized (const float &f) override
void setValueFromModel (const float &f) override
float getDefaultValue () const override
std::string getValueAsStringFor (float f) const override
float getMin () const override
float getMax () const override
bool isBipolar () const override
Public Attributes
ModRow * parentRow {nullptr}
sst::jucegui::data::Continuous * under {nullptr}
Constructor & Destructor Documentation
ReScaler()
template<typename GZTrait > ReScaler (ModRow * parentRow, sst::jucegui::data::Continuous * u)
Member Function Documentation
getLabel()
template<typename GZTrait > std::string getLabel () const override
References ModRow< GZTrait >::ReScaler::under.
scaleFromUnder()
template<typename GZTrait > float scaleFromUnder (float f) const
References ModRow< GZTrait >::ReScaler::under.
Referenced by ModRow< GZTrait >::ReScaler::getValue().
scaleToUnder()
template<typename GZTrait > float scaleToUnder (float f) const
Referenced by ModRow< GZTrait >::ReScaler::getValueAsStringFor(), ModRow< GZTrait >::ReScaler::setValueFromGUI(), ModRow< GZTrait >::ReScaler::setValueFromGUIQuantized(), and ModRow< GZTrait >::ReScaler::setValueFromModel().
getValue()
template<typename GZTrait > float getValue () const override
References ModRow< GZTrait >::ReScaler::scaleFromUnder(), and ModRow< GZTrait >::ReScaler::under.
Referenced by ModRow< GZTrait >::ReScaler::getValue01().
getValue01()
template<typename GZTrait > float getValue01 () override
References ModRow< GZTrait >::ReScaler::getValue().
setValueFromGUI()
template<typename GZTrait > void setValueFromGUI (const float & f) override
References ModRow< GZTrait >::ReScaler::scaleToUnder(), and ModRow< GZTrait >::ReScaler::under.
setValueFromGUIQuantized()
template<typename GZTrait > void setValueFromGUIQuantized (const float & f) override
References ModRow< GZTrait >::ReScaler::scaleToUnder(), and ModRow< GZTrait >::ReScaler::under.
setValueFromModel()
template<typename GZTrait > void setValueFromModel (const float & f) override
References ModRow< GZTrait >::ReScaler::scaleToUnder(), and ModRow< GZTrait >::ReScaler::under.
getDefaultValue()
template<typename GZTrait > float getDefaultValue () const override
getValueAsStringFor()
template<typename GZTrait > std::string getValueAsStringFor (float f) const override
References ModRow< GZTrait >::ReScaler::scaleToUnder(), and ModRow< GZTrait >::ReScaler::under.
getMin()
template<typename GZTrait > float getMin () const override
getMax()
template<typename GZTrait > float getMax () const override
isBipolar()
template<typename GZTrait > bool isBipolar () const override
Member Data Documentation
parentRow
template<typename GZTrait > ModRow* parentRow {nullptr}
under
template<typename GZTrait > sst::jucegui::data::Continuous* under {nullptr}
Referenced by ModRow< GZTrait >::ReScaler::getLabel(), ModRow< GZTrait >::ReScaler::getValue(), ModRow< GZTrait >::ReScaler::getValueAsStringFor(), ModRow< GZTrait >::ReScaler::scaleFromUnder(), ModRow< GZTrait >::ReScaler::setValueFromGUI(), ModRow< GZTrait >::ReScaler::setValueFromGUIQuantized(), and ModRow< GZTrait >::ReScaler::setValueFromModel().
The documentation for this struct was generated from the following file:
ModPane.cpp