shortcircuit-xt: GroupMatrixEndpoints Struct Reference
GroupMatrixEndpoints Struct Reference
#include <group_matrix.h>
Classes
struct EGTarget
struct LFOTarget
struct OutputTarget
struct ProcessorTarget
struct SelfModulationTarget
struct Sources
Public Types
using TG = GroupMatrixConfig::TargetIdentifier
using SR = GroupMatrixConfig::SourceIdentifier
Public Member Functions
GroupMatrixEndpoints (scxt::engine::Engine *e)
void bindTargetBaseValues (GroupMatrix &m, engine::Group &g)
Static Public Member Functions
static void registerGroupModTarget (engine::Engine *e, const GroupMatrixConfig::TargetIdentifier &t, const std::string &path, const std::string &name, bool supportsMul=false)
static void registerGroupModTarget (engine::Engine *e, const GroupMatrixConfig::TargetIdentifier &t, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> nameFn, bool supportsMul=false)
static void registerGroupModTarget (engine::Engine *e, const GroupMatrixConfig::TargetIdentifier &, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> nameFn, std::function< bool(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> additiveFn)
static void registerGroupModSource (engine::Engine *e, const GroupMatrixConfig::SourceIdentifier &t, const std::string &path, const std::string &name)
static void registerGroupModSource (engine::Engine *e, const GroupMatrixConfig::SourceIdentifier &, std::function< std::string(const engine::Group &, const GroupMatrixConfig::SourceIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::SourceIdentifier &)> nameFn)
Public Attributes
std::array< EGTarget, scxt::egsPerGroup > egTarget
std::array< LFOTarget, scxt::lfosPerGroup > lfo
std::array< ProcessorTarget, scxt::processorsPerZoneAndGroup > processorTarget
struct scxt::modulation::GroupMatrixEndpoints::OutputTarget outputTarget
struct scxt::modulation::GroupMatrixEndpoints::SelfModulationTarget selfModulation
struct scxt::modulation::GroupMatrixEndpoints::Sources sources
Member Typedef Documentation
TG
using TG = GroupMatrixConfig::TargetIdentifier
SR
using SR = GroupMatrixConfig::SourceIdentifier
Constructor & Destructor Documentation
GroupMatrixEndpoints()
GroupMatrixEndpoints (scxt::engine::Engine * e)
Member Function Documentation
bindTargetBaseValues()
void bindTargetBaseValues (GroupMatrix & m, engine::Group & g)
References GroupMatrixEndpoints::OutputTarget::bind(), GroupMatrixEndpoints::egTarget, GroupMatrixEndpoints::lfo, GroupMatrixEndpoints::outputTarget, and GroupMatrixEndpoints::processorTarget.
Referenced by Group::rePrepareAndBindGroupMatrix().
registerGroupModTarget() [1/3]
static void registerGroupModTarget (engine::Engine * e, const GroupMatrixConfig::TargetIdentifier & t, const std::string & path, const std::string & name, bool supportsMul = false) static
References GroupMatrixEndpoints::registerGroupModTarget().
Referenced by GroupMatrixEndpoints::EGTarget::EGTarget(), GroupMatrixEndpoints::LFOTarget::LFOTarget(), GroupMatrixEndpoints::OutputTarget::OutputTarget(), GroupMatrixEndpoints::ProcessorTarget::ProcessorTarget(), GroupMatrixEndpoints::registerGroupModTarget(), GroupMatrixEndpoints::registerGroupModTarget(), and GroupMatrixEndpoints::SelfModulationTarget::SelfModulationTarget().
registerGroupModTarget() [2/3]
static void registerGroupModTarget (engine::Engine * e, const GroupMatrixConfig::TargetIdentifier & t, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> nameFn, bool supportsMul = false) static
References GroupMatrixEndpoints::registerGroupModTarget().
registerGroupModTarget() [3/3]
void registerGroupModTarget (engine::Engine * e, const GroupMatrixConfig::TargetIdentifier & t, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> nameFn, std::function< bool(const engine::Group &, const GroupMatrixConfig::TargetIdentifier &)> additiveFn) static
References Engine::registerGroupModTarget().
registerGroupModSource() [1/2]
static void registerGroupModSource (engine::Engine * e, const GroupMatrixConfig::SourceIdentifier & t, const std::string & path, const std::string & name) static
References GroupMatrixEndpoints::registerGroupModSource().
Referenced by GroupMatrixEndpoints::Sources::MacroSources::MacroSources(), and GroupMatrixEndpoints::registerGroupModSource().
registerGroupModSource() [2/2]
void registerGroupModSource (engine::Engine * e, const GroupMatrixConfig::SourceIdentifier & t, std::function< std::string(const engine::Group &, const GroupMatrixConfig::SourceIdentifier &)> pathFn, std::function< std::string(const engine::Group &, const GroupMatrixConfig::SourceIdentifier &)> nameFn) static
References Engine::registerGroupModSource().
Member Data Documentation
egTarget
std::array<EGTarget, scxt::egsPerGroup> egTarget
Referenced by Group::attack(), GroupMatrixEndpoints::bindTargetBaseValues(), and Group::processWithOS().
lfo
std::array<LFOTarget, scxt::lfosPerGroup> lfo
Referenced by GroupMatrixEndpoints::bindTargetBaseValues(), Group::processWithOS(), Group::resetLFOs(), and Group::setupOnUnstream().
processorTarget
std::array<ProcessorTarget, scxt::processorsPerZoneAndGroup> processorTarget
Referenced by Group::attack(), GroupMatrixEndpoints::bindTargetBaseValues(), and Group::onProcessorTypeChanged().
outputTarget
struct scxt::modulation::GroupMatrixEndpoints::OutputTarget outputTarget
Referenced by GroupMatrixEndpoints::bindTargetBaseValues(), and Group::processWithOS().
selfModulation
struct scxt::modulation::GroupMatrixEndpoints::SelfModulationTarget selfModulation
sources
struct scxt::modulation::GroupMatrixEndpoints::Sources sources
Referenced by Group::rePrepareAndBindGroupMatrix().
The documentation for this struct was generated from the following files:
group_matrix.h
group_matrix.cpp