shortcircuit-xt: EqDisplaySupport< Proc, nSub > Struct Template Reference
EqDisplaySupport< Proc, nSub > Struct Template Reference
Classes
struct pt
Public Types
using ptvec_t = std::vector< pt >
Public Member Functions
EqDisplaySupport (ProcessorPane &p)
void rebuildCurves () override
void paint (juce::Graphics &g) override
Public Attributes
const ProcessorPane & mProcessorPane
Proc mProcessor
std::function< void(Proc &, int)> mPrepareBand {nullptr}
std::array< ptvec_t, nSub+1 > curves
bool curvesBuilt {false}
float centerPoint {0.5f}
Public Attributes inherited from EqDisplayBase
int nBands {0}
std::unique_ptr< BandSelect > bandSelect
Member Typedef Documentation
ptvec_t
template<typename Proc , int nSub> using ptvec_t = std::vector<pt>
Constructor & Destructor Documentation
EqDisplaySupport()
template<typename Proc , int nSub> EqDisplaySupport (ProcessorPane & p)
References EqDisplaySupport< Proc, nSub >::mProcessor, EqDisplayBase::nBands, ProcessorPane::processorView, and EqDisplaySupport< Proc, nSub >::rebuildCurves().
Member Function Documentation
rebuildCurves()
template<typename Proc , int nSub> void rebuildCurves () override virtual
Implements EqDisplayBase.
References EqDisplaySupport< Proc, nSub >::curves, EqDisplaySupport< Proc, nSub >::curvesBuilt, EqDisplaySupport< Proc, nSub >::mPrepareBand, and EqDisplaySupport< Proc, nSub >::mProcessor.
Referenced by EqDisplaySupport< Proc, nSub >::EqDisplaySupport(), ProcessorPane::layoutControlsEQGraphic(), EqDisplaySupport< Proc, nSub >::paint(), and EqNBandDisplay< Proc, nSub >::resized().
paint()
template<typename Proc , int nSub> void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_1b, ColorMap::accent_2b, ColorMap::bg_1, EqDisplaySupport< Proc, nSub >::centerPoint, EqDisplaySupport< Proc, nSub >::curves, EqDisplaySupport< Proc, nSub >::curvesBuilt, HasEditor::editor, EqDisplaySupport< Proc, nSub >::mProcessorPane, ColorMap::panel_outline_2, EqDisplaySupport< Proc, nSub >::rebuildCurves(), EqDisplaySupport< Proc, nSub >::pt::x, and EqDisplaySupport< Proc, nSub >::pt::y.
Member Data Documentation
mProcessorPane
template<typename Proc , int nSub> const ProcessorPane& mProcessorPane
Referenced by EqDisplaySupport< Proc, nSub >::paint().
mProcessor
template<typename Proc , int nSub> Proc mProcessor
Referenced by EqDisplaySupport< Proc, nSub >::EqDisplaySupport(), and EqDisplaySupport< Proc, nSub >::rebuildCurves().
mPrepareBand
template<typename Proc , int nSub> std::function<void(Proc &, int)> mPrepareBand {nullptr}
Referenced by ProcessorPane::layoutControlsEQMorph(), and EqDisplaySupport< Proc, nSub >::rebuildCurves().
curves
template<typename Proc , int nSub> std::array<ptvec_t, nSub + 1> curves
Referenced by EqDisplaySupport< Proc, nSub >::paint(), and EqDisplaySupport< Proc, nSub >::rebuildCurves().
curvesBuilt
template<typename Proc , int nSub> bool curvesBuilt {false}
Referenced by EqDisplaySupport< Proc, nSub >::paint(), and EqDisplaySupport< Proc, nSub >::rebuildCurves().
centerPoint
template<typename Proc , int nSub> float centerPoint {0.5f}
Referenced by EqDisplaySupport< Proc, nSub >::paint().
The documentation for this struct was generated from the following file:
ProcessorPaneEQsFilters.cpp