shortcircuit-xt: SCXTEditorDataCache Struct Reference
SCXTEditorDataCache Struct Reference
The iriginal design of the SC UI (which is still partly that way) has local copies of the data cache right next to the particular panel.
#include <SCXTEditorDataCache.h>
Public Member Functions
void addSubscription (void *el, sst::jucegui::data::Continuous *)
void addSubscription (void *el, sst::jucegui::data::Discrete *)
void fireSubscription (void *el, sst::jucegui::data::Continuous *)
void fireSubscription (void *el, sst::jucegui::data::Discrete *)
void addNotificationCallback (void *el, std::function< void()>)
template<typename P >
void fireAllNotificationsFor (const P &p)
Public Attributes
scxt::engine::Group::GroupOutputInfo groupOutputInfo
scxt::engine::Zone::ZoneOutputInfo zoneOutputInfo
Detailed Description
The iriginal design of the SC UI (which is still partly that way) has local copies of the data cache right next to the particular panel.
This works well until you want to share data across more than one panel, and then it gets clumsy, or if your heirarchy gets deep.
So this class exists to have a place for the SCXTEditorResonder thingy to push data copies and for hte UI to bind to, since the UI will reliably be components which haveeditor.
Member Function Documentation
addSubscription() [1/2]
void addSubscription (void * el, sst::jucegui::data::Continuous * c)
Referenced by HasEditor::addSubscription().
addSubscription() [2/2]
void addSubscription (void * el, sst::jucegui::data::Discrete * d)
fireSubscription() [1/2]
void fireSubscription (void * el, sst::jucegui::data::Continuous * c)
fireSubscription() [2/2]
void fireSubscription (void * el, sst::jucegui::data::Discrete * c)
addNotificationCallback()
void addNotificationCallback (void * el, std::function< void()> f)
Referenced by GroupSettingsCard::GroupSettingsCard().
fireAllNotificationsFor()
template<typename P > void fireAllNotificationsFor (const P & p)
Referenced by SCXTEditor::onGroupOutputInfoUpdated(), and SCXTEditor::onZoneOutputInfoUpdated().
Member Data Documentation
groupOutputInfo
scxt::engine::Group::GroupOutputInfo groupOutputInfo
Referenced by SCXTEditor::onGroupOutputInfoUpdated(), and OutPaneGroupTraits::outputInfo().
zoneOutputInfo
scxt::engine::Zone::ZoneOutputInfo zoneOutputInfo
Referenced by SCXTEditor::onZoneOutputInfoUpdated(), and OutPaneZoneTraits::outputInfo().
The documentation for this struct was generated from the following files:
SCXTEditorDataCache.h
SCXTEditorDataCache.cpp