shortcircuit-xt: JSONAssetLibrary Struct Reference
JSONAssetLibrary Struct Reference
Static Public Member Functions
static std::string jsonForAsset (const std::string &nm)
Member Function Documentation
jsonForAsset()
std::string jsonForAsset (const std::string & nm) static
References SCLOG.
Referenced by ColorMap::createColorMap(), ProcessorPane::layoutControlsFromJSON(), and PartEffectsPane::rebuildFromJSONLibrary().
The documentation for this struct was generated from the following files:
JSONAssetSupport.h
JSONAssetSupport.cpp