shortcircuit-xt: MessageController Struct Reference
MessageController Struct Reference
The SCXT Next messaging model.
#include <messaging.h>
Classes
struct AudioThreadCallback
struct ClientActivityNotificationGuard
Public Types
typedef std::string serialToClientMessage_t
The client callback is a function a client registers which will get called on the serialization thread when there's a message to send to the client.
typedef std::string clientToSerializationMessage_t
typedef std::function< void(const serialToClientMessage_t &)> clientCallback_t
typedef audio::SerializationToAudio serializationToAudioMessage_t
typedef audio::AudioToSerialization audioToSerializationMessage_t
Public Member Functions
MessageController (engine::Engine &e)
~MessageController ()
bool updateAudioRunning (bool includeCountdown)
void start ()
start.
void stop ()
stop.
std::unique_lock< std::mutex > acquireClientCallbackMutex () const
void registerClient (const std::string &nm, clientCallback_t &&f)
Register a client.
void unregisterClient ()
Unregister client.
void sendRawFromClient (const clientToSerializationMessage_t &s)
Allows the client to send a raw message on the client thread.
void sendAudioToSerialization (const audioToSerializationMessage_t &m)
Send a message to the serialization thread from the audio thread.
void sendSerializationToAudio (const serializationToAudioMessage_t &m)
Send a message from the serialization thread to the audio thread.
void scheduleAudioThreadCallback (std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb=nullptr)
Schedule a function on the audio thread from the serialization thread.
void scheduleAudioThreadCallbackUnderStructureLock (std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb=nullptr)
void scheduleAudioThreadFunctionCallback (audio::SerializationToAudioMessageId id, std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb)
void stopAudioThreadThenRunOnSerial (std::function< void(const engine::Engine &)> f)
void restartAudioThreadFromSerial ()
void reportErrorToClient (const std::string &title, const std::string &body)
void sendStreamCompleteNotification ()
void updateClientActivityNotification (const std::string &msg, int idx=-1)
Public Member Functions inherited from MoveableOnly< MessageController >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Attributes
std::atomic< bool > isClientConnected {false}
State variables for connection.
std::atomic< bool > isAudioRunning {false}
std::atomic< int64_t > engineProcessRuns {0}
std::atomic< bool > forceStatusUpdate {false}
clientCallback_t clientCallback {nullptr}
std::mutex clientCallbackMutex
std::vector< std::string > preClientConnectionCache
ThreadingChecker threadingChecker
uint64_t c2sMessageCount {0}
uint64_t c2sMessageBytes {0}
std::function< void(uint64_t)> requestHostCallback {nullptr}
std::mutex streamNotificationMutex
std::condition_variable streamNotificationConditionVariable
uint64_t streamNotificationCount {1743}
std::atomic< bool > passWrapperEventsToWrapperQueue {false}
sst::cpputils::SimpleRingBuffer< serializationToAudioMessage_t, 1024 > engineToPluginWrapperQueue
Additional Inherited Members
Protected Member Functions inherited from MoveableOnly< MessageController >
MoveableOnly ()
~MoveableOnly ()=default
Detailed Description
The SCXT Next messaging model.
We want SCXT "engine" to be able to provide a JSON interface at its edge to a consumer, but obviously we don't want those messages on the audio thread (all that string allocation!! all that parsing time) but also we don't want to require a UI thread to run (what if we want a headless server mode, or an HTTP interface!)
So our messaging strategy ends up with three thread
Engine Audio Thread
Runs ::process
Can't allocate memory
Cant use anything other than lock free data structures
Engine Serialization Thread
Runs its own ::run
Can allocate
Can do read-only access to Engine memrory (same process as the audio thread)
Can use system mutex/cond var etc.. to communicate with anything other than audio
Client Thread (aka UI Thread)
Can do wahtever it wants except...
Talk to the engine audio thread or engine data structures (separate memory)
So that results in the following data structures
Audio <-> Serialization
A pair of lock free queues called "serializationToAudio" and "audioToSeralization"
Fixed data structures only in audioToSerialization (no alloc)
If serializatToAudio has allocated structues, the engine hands them back for future freeing
Engine has an atomic bool (or perhaps int) of client connected (or client count)
in Engine::process
drain serializationToAudio and respond. These will almost exclusively be state mutation operators
send updates back. These will be things like noteon-off display indicates, parameter change displays and so on. Only do this if a client is connected.
Client <-> Serialization
A queue locked by a mutex probably
A condition variable for queue mutation notifications
A callback function to send a response to the client which can be called from the serialization thread. (In the out-of-process model this would be a socket write most likely).
Serialization::run
basically wait on the condition variable if the queues are emtpy
then drain the audioToSerialization queue and generate the associated outbound messages by calling the ui callback (but don't hold the lock while doing this)
The serialization thread blocks for inbound from the UI and does a check of the outbound thread every 50ms or so. If you want a faster outbound process send an idle wakeup message
We encapsulate this in a few objects here.
The MessageController is an object owned by the engine, constructed with an engine. This is the object which can send messages between the various parts. Those messages take a couple of forms
Client <-> Serialization Messages (clients/client_serial.h)
The pattern we use here is to make request and response objects. Request objects are C2S and response are S2C, basically. There is a unique set of IDs for each message.
To be a C2S object you implement an object which has a constecxpr id c2s_id and a typedef to c2s_payload_t. That payload should be json streamable (so should be a basic type supported by jsoncpp or implement a traint in src/json). Finally the object should implement static executeOnSerialization which is called with a payload, an engine, and a controller. A client sends a message with template<T> messaging::client::clientSendToSerialization(T &msg, MessageController &) which uses these template properties to serialize the payload, deliver it to the seralization thread, and execute it.
To be an S2C object you do the inverse. Implement a constexpr s2c_id and typedef an s2c_payload_t which again is json streamable. Then implement template<Client> executeOnClient(Client *, s2c_payload &). This allows the serialization thread to call MessageController::serializationToClient(s2cid, payload) and have that delivered to the client for execution. Obviously the union of the functions called on the Client template type by executeOnClient imply an API for the client object which unpacks messages.
Audio <-> Serlization Messages (audio/audio_serial.h)
The audio thread messaging is more constrained since it has to be non allocating and lock free. As a result the message payloads are fixed sized unions AudiotoSerialization and SerializationToAudio, which you enqueue or dequeue with a type for a switch.
For the specific case of the serialization thread interacting with the audio thread, though, we have used this mechanism to make a fucntion callback which is audio-thread alloc free. The function MessageController::scheduleAudioThreadCallback(cb) hides most of these mechanics by sending a function to the audio thread with all of the required allocation and deallocation happening on the serialization thread.
The other common pattern of the audio thread initiates a message is really just done by explicitly constructing the message on the audio thread, sending it, and then unpacking it in MessageController::praseAudioMessageOnSerializationThread
Member Typedef Documentation
serialToClientMessage_t
typedef std::string serialToClientMessage_t
The client callback is a function a client registers which will get called on the serialization thread when there's a message to send to the client.
A typical implementation would be to lock a queue which the client polls in an idle loop.
clientToSerializationMessage_t
typedef std::string clientToSerializationMessage_t
clientCallback_t
typedef std::function<void(const serialToClientMessage_t &)> clientCallback_t
serializationToAudioMessage_t
typedef audio::SerializationToAudio serializationToAudioMessage_t
audioToSerializationMessage_t
typedef audio::AudioToSerialization audioToSerializationMessage_t
Constructor & Destructor Documentation
MessageController()
MessageController (engine::Engine & e)
~MessageController()
~MessageController ()
Member Function Documentation
updateAudioRunning()
bool updateAudioRunning (bool includeCountdown)
References MessageController::engineProcessRuns, MessageController::forceStatusUpdate, MessageController::isAudioRunning, ThreadingChecker::isSerialThread(), and MessageController::threadingChecker.
start()
void start ()
start.
Called from the startup thread after the engine is created. Will begin a serialization thread.
stop()
void stop ()
stop.
Called from the startup thread when the engine is destroyed. Will end and join the serialization thread. Cannot be called from the serialization thread.
acquireClientCallbackMutex()
std::unique_lock< std::mutex > acquireClientCallbackMutex () const
References MessageController::clientCallbackMutex.
Referenced by MessageController::registerClient(), scxt::messaging::client::serializationSendToClient(), and MessageController::unregisterClient().
registerClient()
void registerClient (const std::string & nm, clientCallback_t && f)
Register a client.
Called from the client thread.
Parameters
nm The client name
f The client callback function
References MessageController::acquireClientCallbackMutex(), ThreadingChecker::addAsAClientThread(), MessageController::clientCallback, scxt::messaging::client::clientSendToSerialization(), MessageController::isClientConnected, MessageController::preClientConnectionCache, and MessageController::threadingChecker.
Referenced by ConsoleUI::ConsoleUI(), and SCXTEditor::SCXTEditor().
unregisterClient()
void unregisterClient ()
Unregister client.
Called from the client thread.
References MessageController::acquireClientCallbackMutex(), MessageController::clientCallback, MessageController::isClientConnected, ThreadingChecker::removeAsAClientThread(), and MessageController::threadingChecker.
Referenced by ConsoleUI::~ConsoleUI(), and SCXTEditor::~SCXTEditor().
sendRawFromClient()
void sendRawFromClient (const clientToSerializationMessage_t & s)
Allows the client to send a raw message on the client thread.
Used in the serialization implementation under the covers. Users should use messaging::client::clientSendToSerialization instead
Parameters
s
References MessageController::c2sMessageBytes, MessageController::c2sMessageCount, and SCLOG_IF.
Referenced by scxt::messaging::client::clientSendToSerialization().
sendAudioToSerialization()
void sendAudioToSerialization (const audioToSerializationMessage_t & m)
Send a message to the serialization thread from the audio thread.
Call from the audio thread.
Parameters
m The message object
Referenced by scxt::messaging::audio::sendStructureRefresh().
sendSerializationToAudio()
void sendSerializationToAudio (const serializationToAudioMessage_t & m)
Send a message from the serialization thread to the audio thread.
Called from the serialization queue.
Parameters
m
scheduleAudioThreadCallback()
void scheduleAudioThreadCallback (std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb = nullptr)
Schedule a function on the audio thread from the serialization thread.
Parameters
f
References scxt::messaging::audio::s2a_dispatch_to_pointer, and MessageController::scheduleAudioThreadFunctionCallback().
scheduleAudioThreadCallbackUnderStructureLock()
void scheduleAudioThreadCallbackUnderStructureLock (std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb = nullptr)
References scxt::messaging::audio::s2a_dispatch_to_pointer_under_structurelock, and MessageController::scheduleAudioThreadFunctionCallback().
Referenced by MessageController::restartAudioThreadFromSerial(), and MessageController::stopAudioThreadThenRunOnSerial().
scheduleAudioThreadFunctionCallback()
void scheduleAudioThreadFunctionCallback (audio::SerializationToAudioMessageId id, std::function< void(engine::Engine &)> f, std::function< void(const engine::Engine &)> cb)
References ThreadingChecker::bypassThreadChecks, ThreadingChecker::isSerialThread(), MessageController::threadingChecker, and SerializationToAudio::VOID_STAR.
Referenced by MessageController::scheduleAudioThreadCallback(), and MessageController::scheduleAudioThreadCallbackUnderStructureLock().
stopAudioThreadThenRunOnSerial()
void stopAudioThreadThenRunOnSerial (std::function< void(const engine::Engine &)> f)
References ThreadingChecker::isSerialThread(), MessageController::scheduleAudioThreadCallbackUnderStructureLock(), Engine::stopEngineRequests, and MessageController::threadingChecker.
restartAudioThreadFromSerial()
void restartAudioThreadFromSerial ()
References ThreadingChecker::isSerialThread(), MessageController::scheduleAudioThreadCallbackUnderStructureLock(), Engine::stopEngineRequests, and MessageController::threadingChecker.
reportErrorToClient()
void reportErrorToClient (const std::string & title, const std::string & body)
References scxt::messaging::client::s2c_report_error, SCLOG_IF, and scxt::messaging::client::serializationSendToClient().
Referenced by BrowserDB::getBrowserLocations(), scxt::messaging::client::raiseDebugError(), and scxt::messaging::client::serializationSendToClient().
sendStreamCompleteNotification()
void sendStreamCompleteNotification ()
References MessageController::streamNotificationConditionVariable, MessageController::streamNotificationCount, and MessageController::streamNotificationMutex.
updateClientActivityNotification()
void updateClientActivityNotification (const std::string & msg, int idx = -1)
References Engine::getMessageController(), and scxt::messaging::client::s2c_send_activity_notification.
Referenced by MessageController::ClientActivityNotificationGuard::ClientActivityNotificationGuard().
Member Data Documentation
isClientConnected
std::atomic<bool> isClientConnected {false}
State variables for connection.
Referenced by MessageController::registerClient(), and MessageController::unregisterClient().
isAudioRunning
std::atomic<bool> isAudioRunning {false}
Referenced by MessageController::updateAudioRunning().
engineProcessRuns
std::atomic<int64_t> engineProcessRuns {0}
Referenced by MessageController::updateAudioRunning().
forceStatusUpdate
std::atomic<bool> forceStatusUpdate {false}
Referenced by MessageController::updateAudioRunning().
clientCallback
clientCallback_t clientCallback {nullptr}
Referenced by MessageController::registerClient(), scxt::messaging::client::serializationSendToClient(), and MessageController::unregisterClient().
clientCallbackMutex
std::mutex clientCallbackMutex mutable
Referenced by MessageController::acquireClientCallbackMutex().
preClientConnectionCache
std::vector<std::string> preClientConnectionCache
Referenced by MessageController::registerClient(), and scxt::messaging::client::serializationSendToClient().
threadingChecker
ThreadingChecker threadingChecker
Referenced by BrowserDB::BrowserDB(), scxt::messaging::client::clientSendToSerialization(), SCXTEditor::drainCallbackQueue(), MessageController::registerClient(), MessageController::restartAudioThreadFromSerial(), ScanWorker::ScanWorker(), MessageController::scheduleAudioThreadFunctionCallback(), SCXTEditor::SCXTEditor(), scxt::messaging::audio::sendStructureRefresh(), scxt::messaging::client::serializationSendToClient(), scxt::messaging::client::serializationThreadExecuteClientMessage(), MessageController::stopAudioThreadThenRunOnSerial(), MessageController::unregisterClient(), and MessageController::updateAudioRunning().
c2sMessageCount
uint64_t c2sMessageCount {0}
Referenced by MessageController::sendRawFromClient().
c2sMessageBytes
uint64_t c2sMessageBytes {0}
Referenced by MessageController::sendRawFromClient().
requestHostCallback
std::function<void(uint64_t)> requestHostCallback {nullptr}
streamNotificationMutex
std::mutex streamNotificationMutex
Referenced by MessageController::sendStreamCompleteNotification().
streamNotificationConditionVariable
std::condition_variable streamNotificationConditionVariable
Referenced by MessageController::sendStreamCompleteNotification().
streamNotificationCount
uint64_t streamNotificationCount {1743}
Referenced by MessageController::sendStreamCompleteNotification().
passWrapperEventsToWrapperQueue
std::atomic<bool> passWrapperEventsToWrapperQueue {false}
engineToPluginWrapperQueue
sst::cpputils::SimpleRingBuffer<serializationToAudioMessage_t, 1024> engineToPluginWrapperQueue
The documentation for this struct was generated from the following files:
messaging.h
messaging.cpp