shortcircuit-xt: MatrixEndpoints::Sources Struct Reference
MatrixEndpoints::Sources Struct Reference
Classes
struct MacroSources
struct MIDISources
struct NoteExpressionSources
struct RNGSources
Public Member Functions
Sources (engine::Engine *e)
void bind (Matrix &m, engine::Zone &z, voice::Voice &v)
Public Attributes
LFOSourceBase< SR, 'znlf', lfosPerZone, registerVoiceModSource > lfoSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::MIDISources midiSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::NoteExpressionSources noteExpressions
TransportSourceBase< SR, 'ztsp', true, registerVoiceModSource > transportSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::RNGSources rngSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::MacroSources macroSources
SR aegSource
SR eg2Source
float zeroSource {0.f}
Constructor & Destructor Documentation
Sources()
Sources (engine::Engine * e)
References MatrixEndpoints::Sources::aegSource, MatrixEndpoints::Sources::eg2Source, and MatrixEndpoints::registerVoiceModSource().
Member Function Documentation
bind()
void bind (Matrix & m, engine::Zone & z, voice::Voice & v)
References Voice::aeg, Voice::BRIGHTNESS, Voice::eg2, Voice::EXPRESSION, Zone::getEngine(), Voice::keytrackPerOct, Part::midiCCValues, Voice::noteExpressions, Voice::PAN, Zone::parentGroup, Group::parentPart, Voice::polyAT, Voice::PRESSURE, scxt::voice::modulation::randomRoll(), Engine::transportPhasors, Voice::transportPhasors, Voice::TUNING, Voice::velocity, Voice::VIBRATO, and Voice::VOLUME.
Member Data Documentation
lfoSources
LFOSourceBase<SR, 'znlf', lfosPerZone, registerVoiceModSource> lfoSources
Referenced by Zone::onRoutingChanged().
midiSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::MIDISources midiSources
noteExpressions
struct scxt::voice::modulation::MatrixEndpoints::Sources::NoteExpressionSources noteExpressions
transportSources
TransportSourceBase<SR, 'ztsp', true, registerVoiceModSource> transportSources
rngSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::RNGSources rngSources
macroSources
struct scxt::voice::modulation::MatrixEndpoints::Sources::MacroSources macroSources
aegSource
SR aegSource
Referenced by Zone::onRoutingChanged(), and MatrixEndpoints::Sources::Sources().
eg2Source
SR eg2Source
Referenced by Zone::onRoutingChanged(), and MatrixEndpoints::Sources::Sources().
zeroSource
float zeroSource {0.f}
The documentation for this struct was generated from the following files:
voice_matrix.h
voice_matrix.cpp