shortcircuit-xt: MappingZones Struct Reference
MappingZones Struct Reference
Public Types
enum MouseState {
NONE , DRAG_VELOCITY , DRAG_KEY , DRAG_KEY_AND_VEL ,
DRAG_SELECTED_ZONE , MULTI_SELECT , CREATE_EMPTY_ZONE
}
enum DragFrom { FROM_START , FROM_END }
Public Member Functions
MappingZones (MappingDisplay *d)
void paint (juce::Graphics &g) override
void resized () override
std::array< int16_t, 3 > rootAndRangeForPosition (const juce::Point< int > &)
juce::Rectangle< float > rectangleForZone (const engine::Part::zoneMappingItem_t &sum)
juce::Rectangle< float > rectangleForRange (int kL, int kH, int vL, int vH)
void mouseDown (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseMove (const juce::MouseEvent &e) override
void mouseDoubleClick (const juce::MouseEvent &e) override
void resetLeadZoneBounds ()
void setLeadZoneBounds (const engine::Part::zoneMappingItem_t &az)
void showZoneMenu (const selection::SelectionManager::ZoneAddress &za)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (const W &widget, const A &attachment)
Public Attributes
MappingDisplay * display {nullptr}
std::optional< engine::Part::zoneMappingItem_t > cacheLastZone
enum scxt::ui::app::edit_screen::MappingZones::MouseState NONE
enum scxt::ui::app::edit_screen::MappingZones::DragFrom dragFrom [2]
std::vector< juce::Rectangle< float > > velocityHotZones
std::vector< juce::Rectangle< float > > keyboardHotZones
std::vector< juce::Rectangle< float > > bothHotZones
std::vector< juce::Rectangle< float > > lastSelectedZone
juce::Point< float > firstMousePos {0.f, 0.f}
juce::Point< float > lastMousePos {0.f, 0.f}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Member Enumeration Documentation
MouseState
enum MouseState
Enumerator
NONE
DRAG_VELOCITY
DRAG_KEY
DRAG_KEY_AND_VEL
DRAG_SELECTED_ZONE
MULTI_SELECT
CREATE_EMPTY_ZONE
DragFrom
enum DragFrom
Enumerator
FROM_START
FROM_END
Constructor & Destructor Documentation
MappingZones()
MappingZones (MappingDisplay * d)
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References ColorMap::accent_1a, ColorMap::accent_1b, ColorMap::accent_2a, ColorMap::accent_2b, MappingZones::CREATE_EMPTY_ZONE, MappingDisplay::currentDragPoint, SCXTEditor::currentLeadZoneSelection, MappingZones::display, HasEditor::editor, MappingZones::firstMousePos, ColorMap::generic_content_high, ColorMap::generic_content_highest, ColorMap::generic_content_low, ColorMap::generic_content_lowest, ThemeApplier::interRegularFor(), SCXTEditor::isAnyZoneFromGroupSelected(), SCXTEditor::isSelected(), MappingDisplay::isUndertakingDrop, Keyboard::keyboardHeight, MappingZones::lastMousePos, MappingZones::MULTI_SELECT, MappingZones::rectangleForRange(), MappingZones::rectangleForZone(), MappingZones::rootAndRangeForPosition(), MappingDisplay::summary, SCXTEditor::themeApplier, SCXTEditor::themeColor(), scxt::ui::app::other_screens::txt, and MappingDisplay::voiceCountFor().
resized()
void resized () override
rootAndRangeForPosition()
std::array< int16_t, 3 > rootAndRangeForPosition (const juce::Point< int > & p)
References Keyboard::firstMidiNote, Keyboard::keyboardHeight, and Keyboard::lastMidiNote.
Referenced by MappingZones::paint().
rectangleForZone()
juce::Rectangle< float > rectangleForZone (const engine::Part::zoneMappingItem_t & sum)
References MappingZones::rectangleForRange().
Referenced by MappingZones::mouseDown(), MappingZones::mouseUp(), MappingZones::paint(), and MappingZones::setLeadZoneBounds().
rectangleForRange()
juce::Rectangle< float > rectangleForRange (int kL, int kH, int vL, int vH)
References Keyboard::firstMidiNote, Keyboard::keyboardHeight, and Keyboard::lastMidiNote.
Referenced by MappingZones::paint(), and MappingZones::rectangleForZone().
mouseDown()
void mouseDown (const juce::MouseEvent & e) override
References MappingZones::bothHotZones, MappingZones::CREATE_EMPTY_ZONE, SCXTEditor::currentLeadZoneSelection, MappingZones::display, SCXTEditor::doSelectionAction(), MappingZones::DRAG_KEY, MappingZones::DRAG_KEY_AND_VEL, MappingZones::DRAG_SELECTED_ZONE, MappingZones::DRAG_VELOCITY, MappingZones::dragFrom, HasEditor::editor, MappingZones::firstMousePos, MappingZones::FROM_END, MappingZones::FROM_START, SCXTEditor::isAnyZoneFromGroupSelected(), SCXTEditor::isSelected(), MappingZones::keyboardHotZones, MappingZones::lastMousePos, MappingZones::lastSelectedZone, MappingZones::MULTI_SELECT, MappingZones::NONE, MappingZones::rectangleForZone(), MappingZones::showZoneMenu(), MappingDisplay::summary, and MappingZones::velocityHotZones.
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
References MappingZones::CREATE_EMPTY_ZONE, SCXTEditor::currentLeadZoneSelection, MappingZones::display, SCXTEditor::doSelectionAction(), HasEditor::editor, Keyboard::firstMidiNote, MappingZones::firstMousePos, Keyboard::keyboardHeight, Keyboard::lastMidiNote, MappingZones::MULTI_SELECT, MappingZones::NONE, MappingZones::rectangleForZone(), HasEditor::sendToSerialization(), and MappingDisplay::summary.
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
References scxt::ui::app::edit_screen::constrainMappingFade(), MappingZones::CREATE_EMPTY_ZONE, MappingZones::display, MappingZones::DRAG_KEY, MappingZones::DRAG_KEY_AND_VEL, MappingZones::DRAG_SELECTED_ZONE, MappingZones::DRAG_VELOCITY, MappingZones::dragFrom, Keyboard::firstMidiNote, MappingZones::FROM_START, Keyboard::keyboardHeight, Zone::ZoneMappingData::keyboardRange, KeyboardRange::keyEnd, Keyboard::lastMidiNote, MappingZones::lastMousePos, MappingDisplay::mappingChangedFromGUI(), MappingDisplay::mappingView, MappingZones::MULTI_SELECT, Zone::ZoneMappingData::rootKey, Zone::ZoneMappingData::velocityRange, and VelocityRange::velStart.
mouseMove()
void mouseMove (const juce::MouseEvent & e) override
References MappingZones::bothHotZones, MappingZones::keyboardHotZones, and MappingZones::velocityHotZones.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & e) override
References MappingZones::display, MappingZones::lastSelectedZone, and MappingDisplay::parentPane.
resetLeadZoneBounds()
void resetLeadZoneBounds ()
References MappingZones::cacheLastZone, and MappingZones::setLeadZoneBounds().
setLeadZoneBounds()
void setLeadZoneBounds (const engine::Part::zoneMappingItem_t & az)
References MappingZones::bothHotZones, MappingZones::cacheLastZone, MappingZones::keyboardHotZones, MappingZones::lastSelectedZone, MappingZones::rectangleForZone(), and MappingZones::velocityHotZones.
Referenced by MappingZones::resetLeadZoneBounds().
showZoneMenu()
void showZoneMenu (const selection::SelectionManager::ZoneAddress & za)
References SCXTEditor::defaultPopupMenuOptions(), and HasEditor::editor.
Referenced by MappingZones::mouseDown().
Member Data Documentation
display
MappingDisplay* display {nullptr}
Referenced by MappingZones::mouseDoubleClick(), MappingZones::mouseDown(), MappingZones::mouseDrag(), MappingZones::mouseUp(), and MappingZones::paint().
cacheLastZone
std::optional<engine::Part::zoneMappingItem_t> cacheLastZone
Referenced by MappingZones::resetLeadZoneBounds(), and MappingZones::setLeadZoneBounds().
NONE
enum scxt::ui::app::edit_screen::MappingZones::MouseState NONE
Referenced by MappingZones::mouseDown(), and MappingZones::mouseUp().
dragFrom
enum scxt::ui::app::edit_screen::MappingZones::DragFrom dragFrom[2]
Referenced by MappingZones::mouseDown(), and MappingZones::mouseDrag().
velocityHotZones
std::vector<juce::Rectangle<float> > velocityHotZones
Referenced by MappingZones::mouseDown(), MappingZones::mouseMove(), and MappingZones::setLeadZoneBounds().
keyboardHotZones
std::vector<juce::Rectangle<float> > keyboardHotZones
Referenced by MappingZones::mouseDown(), MappingZones::mouseMove(), and MappingZones::setLeadZoneBounds().
bothHotZones
std::vector<juce::Rectangle<float> > bothHotZones
Referenced by MappingZones::mouseDown(), MappingZones::mouseMove(), and MappingZones::setLeadZoneBounds().
lastSelectedZone
std::vector<juce::Rectangle<float> > lastSelectedZone
Referenced by MappingZones::mouseDoubleClick(), MappingZones::mouseDown(), and MappingZones::setLeadZoneBounds().
firstMousePos
juce::Point<float> firstMousePos {0.f, 0.f}
Referenced by MappingZones::mouseDown(), MappingZones::mouseUp(), and MappingZones::paint().
lastMousePos
juce::Point<float> lastMousePos {0.f, 0.f}
Referenced by MappingZones::mouseDown(), MappingZones::mouseDrag(), and MappingZones::paint().
The documentation for this struct was generated from the following file:
MappingPane.cpp