shortcircuit-xt: ZoneModTableSpec Struct Reference
ZoneModTableSpec Struct Reference
#include <payload_undoable_items.h>
Public Types
using value_t = decltype(voice::modulation::Matrix::RoutingTable::routes)
Static Public Member Functions
static std::string name ()
static value_t & ref (engine::Engine &e, const ZoneAddress &a, int32_t)
static void postWrite (engine::Engine &e, const ZoneAddress &a, int32_t)
Static Public Attributes
static constexpr bool forZone {true}
Member Typedef Documentation
value_t
using value_t = decltype(voice::modulation::Matrix::RoutingTable::routes)
Member Function Documentation
name()
static std::string name () static
ref()
static value_t & ref (engine::Engine & e, const ZoneAddress & a, int32_t) static
References Zone::routingTable, and scxt::undo::zoneAt().
postWrite()
static void postWrite (engine::Engine & e, const ZoneAddress & a, int32_t) static
References Zone::onRoutingChanged(), and scxt::undo::zoneAt().
Member Data Documentation
forZone
constexpr bool forZone {true} static constexpr
The documentation for this struct was generated from the following file:
payload_undoable_items.h