shortcircuit-xt: DriveFSListBoxRow Struct Reference
DriveFSListBoxRow Struct Reference
Inherits Component.
Public Member Functions
juce::ListBox * enclosingBox ()
void mouseDown (const juce::MouseEvent &event) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &event) override
void mouseDoubleClick (const juce::MouseEvent &event) override
void showDirectoryPopup ()
bool isFile ()
void paint (juce::Graphics &g) override
Public Attributes
bool isSelected
int rowNumber
BrowserPane * browserPane {nullptr}
DriveFSListBoxModel * model {nullptr}
bool isDragging
Member Function Documentation
enclosingBox()
juce::ListBox* enclosingBox ()
References DriveFSListBoxRow::browserPane, and BrowserPane::devicesPane.
Referenced by DriveFSListBoxRow::mouseDown(), and DriveFSListBoxRow::mouseUp().
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References DriveFSListBoxRow::enclosingBox(), DriveFSListBoxRow::isFile(), DriveFSListBoxRow::rowNumber, and DriveFSListBoxRow::showDirectoryPopup().
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
References DriveFSListBoxRow::browserPane, BrowserPane::devicesPane, DriveFSListBoxRow::isDragging, DriveFSListBoxRow::isFile(), and DriveFSListBoxRow::rowNumber.
mouseUp()
void mouseUp (const juce::MouseEvent & event) override
References DriveFSListBoxRow::enclosingBox(), DriveFSListBoxRow::isDragging, and DriveFSListBoxRow::rowNumber.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & event) override
References DriveFSListBoxRow::browserPane, scxt::messaging::client::clientSendToSerialization(), BrowserPane::devicesPane, HasEditor::editor, SCXTEditor::msgCont, and DriveFSListBoxRow::rowNumber.
showDirectoryPopup()
void showDirectoryPopup ()
References DriveFSListBoxRow::browserPane, SCXTEditor::defaultPopupMenuOptions(), BrowserPane::devicesPane, HasEditor::editor, and DriveFSListBoxRow::rowNumber.
Referenced by DriveFSListBoxRow::mouseDown().
isFile()
bool isFile ()
References DriveFSListBoxRow::browserPane, BrowserPane::devicesPane, and DriveFSListBoxRow::rowNumber.
Referenced by DriveFSListBoxRow::mouseDown(), and DriveFSListBoxRow::mouseDrag().
paint()
void paint (juce::Graphics & g) override
References ColorMap::bg_3, DriveFSListBoxRow::browserPane, BrowserPane::devicesPane, HasEditor::editor, ColorMap::generic_content_high, ColorMap::generic_content_medium, ThemeApplier::interMediumFor(), DriveFSListBoxRow::isSelected, DriveFSListBoxRow::rowNumber, SCXTEditor::themeApplier, and SCXTEditor::themeColor().
Member Data Documentation
isSelected
bool isSelected
Referenced by DriveFSListBoxRow::paint().
rowNumber
int rowNumber
Referenced by DriveFSListBoxRow::isFile(), DriveFSListBoxRow::mouseDoubleClick(), DriveFSListBoxRow::mouseDown(), DriveFSListBoxRow::mouseDrag(), DriveFSListBoxRow::mouseUp(), DriveFSListBoxRow::paint(), and DriveFSListBoxRow::showDirectoryPopup().
browserPane
BrowserPane* browserPane {nullptr}
Referenced by DriveFSListBoxRow::enclosingBox(), DriveFSListBoxRow::isFile(), DriveFSListBoxRow::mouseDoubleClick(), DriveFSListBoxRow::mouseDrag(), DriveFSListBoxRow::paint(), and DriveFSListBoxRow::showDirectoryPopup().
model
DriveFSListBoxModel* model {nullptr}
isDragging
bool isDragging
Referenced by DriveFSListBoxRow::mouseDrag(), and DriveFSListBoxRow::mouseUp().
The documentation for this struct was generated from the following file:
BrowserPane.cpp