shortcircuit-xt: EqDisplayBase::BandSelect Struct Reference
EqDisplayBase::BandSelect Struct Reference
Inherits Discrete.
Public Member Functions
BandSelect (int nb)
int getMin () const override
int getMax () const override
std::string getValueAsStringFor (int i) const override
void setValueAsString (const std::string &s) override
int getValue () const override
void setValueFromGUI (const int &f) override
void setValueFromModel (const int &f) override
std::string getLabel () const override
Public Attributes
int nBands {0}
int selBand {0}
std::function< void(int)> onSelChanged {nullptr}
Constructor & Destructor Documentation
BandSelect()
BandSelect (int nb)
Member Function Documentation
getMin()
int getMin () const override
getMax()
int getMax () const override
References EqDisplayBase::BandSelect::nBands.
getValueAsStringFor()
std::string getValueAsStringFor (int i) const override
setValueAsString()
void setValueAsString (const std::string & s) override
References EqDisplayBase::BandSelect::setValueFromGUI().
getValue()
int getValue () const override
References EqDisplayBase::BandSelect::selBand.
setValueFromGUI()
void setValueFromGUI (const int & f) override
References EqDisplayBase::BandSelect::onSelChanged, and EqDisplayBase::BandSelect::selBand.
Referenced by EqDisplayBase::BandSelect::setValueAsString().
setValueFromModel()
void setValueFromModel (const int & f) override
References EqDisplayBase::BandSelect::selBand.
getLabel()
std::string getLabel () const override
Member Data Documentation
nBands
int nBands {0}
Referenced by EqDisplayBase::BandSelect::getMax().
selBand
int selBand {0}
Referenced by EqDisplayBase::BandSelect::getValue(), EqDisplayBase::BandSelect::setValueFromGUI(), and EqDisplayBase::BandSelect::setValueFromModel().
onSelChanged
std::function<void(int)> onSelChanged {nullptr}
Referenced by EqDisplayBase::BandSelect::setValueFromGUI().
The documentation for this struct was generated from the following file:
ProcessorPaneEQsFilters.cpp