shortcircuit-xt: SampleRateSupport Struct Reference
SampleRateSupport Struct Reference
#include <utils.h>
Public Member Functions
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
virtual void onSampleRateChanged ()
Public Attributes
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Member Function Documentation
setSampleRate() [1/2]
void setSampleRate (double sr)
Referenced by Voice::initializeProcessors(), Patch::onSampleRateChanged(), Engine::prepareToPlay(), Voice::processWithOS(), CurveLFOPane::CurveDataSource::recalculateCurvePath(), ENVLFOPane::ENVPlotData::recalculateCurvePath(), and Patch::resetToBlankPatch().
setSampleRate() [2/2]
void setSampleRate (double sr, double sri)
getSampleRate()
double getSampleRate () const
Referenced by Part::addGroup(), SelectionManager::configureAndSendZoneOrGroupModMatrixMetadata(), SCXTVFXConfig< OSFactor >::getSampleRate(), Group::onSampleRateChanged(), Patch::onSampleRateChanged(), Group::rePrepareAndBindGroupMatrix(), Config::sampleRate(), and Voice::voiceStarted().
getSampleRateInv()
double getSampleRateInv () const
Referenced by Config::envelopeRateLinear(), SCXTVFXConfig< OSFactor >::getSampleRateInv(), Group::onSampleRateChanged(), SCXTPlugin::process(), and EngineBiquadAdapter::sampleRateInv().
sync()
void sync ()
isSampleRateSet()
bool isSampleRateSet ()
assertSampleRateSet()
void assertSampleRateSet ()
Referenced by Group::processWithOS().
onSampleRateChanged()
virtual void onSampleRateChanged () virtual
Reimplemented in Bus, Engine, Group, Part, Patch, Zone, StepLFO, and Voice.
Member Data Documentation
dsamplerate
double dsamplerate
dsamplerate_inv
double dsamplerate_inv
sampleRate
double sampleRate {1}
Referenced by StepLFO::assign(), Voice::beginTerminationSequence(), Voice::initializeProcessors(), Engine::initiateVoice(), Group::onProcessorTypeChanged(), Zone::onSampleRateChanged(), StepLFO::onSampleRateChanged(), Engine::prepareToPlay(), Engine::processAudio(), Voice::processWithOS(), Group::processWithOS(), Group::resetLFOs(), Group::setupOnUnstream(), and Voice::voiceStarted().
sampleRateInv
double sampleRateInv {1}
Referenced by StepLFO::assign(), Voice::calculateGeneratorRatio(), Group::envelope_rate_linear_nowrap(), CurveLFO::envelope_rate_linear_nowrap(), EnvLFO::envelope_rate_linear_nowrap(), Voice::envelope_rate_linear_nowrap(), Engine::initiateVoice(), StepLFO::onSampleRateChanged(), Group::resetLFOs(), Group::setupOnUnstream(), and Voice::voiceStarted().
samplerate
double samplerate
Referenced by Part::onSampleRateChanged(), Patch::onSampleRateChanged(), Voice::onSampleRateChanged(), and Engine::prepareToPlay().
samplerate_inv
double samplerate_inv
Referenced by Voice::calculateGeneratorRatio(), PreviewVoice::Details::initiateGD(), and Voice::onSampleRateChanged().
The documentation for this struct was generated from the following file:
utils.h