shortcircuit-xt: SCXTApplicationWindow Struct Reference
SCXTApplicationWindow Struct Reference
Inherits DocumentWindow, and Listener.
Classes
struct AudioCallback
struct Intermediate
class SettingsComponent
Public Member Functions
SCXTApplicationWindow ()
~SCXTApplicationWindow ()
void buttonClicked (juce::Button *button) override
void resized () override
void closeButtonPressed () override
void setupAudio ()
Public Attributes
std::unique_ptr< AudioCallback > audioCB
juce::TextButton optionsButton
AudioDeviceManager deviceManager
std::unique_ptr< scxt::engine::Engine > engine
std::unique_ptr< scxt::ui::app::SCXTEditor > editor
std::unique_ptr< juce::PropertiesFile > properties
std::unique_ptr< Intermediate > editorHolder
Constructor & Destructor Documentation
SCXTApplicationWindow()
SCXTApplicationWindow ()
References Engine::defaults, SCXTEditor::edHeight, SCXTEditor::edWidth, scxt::messaging::client::engine, Engine::getBrowser(), Engine::getMessageController(), Engine::getSampleManager(), Engine::runningEnvironment, Engine::sharedUIMemoryState, and SCXTPlugin::synchronousEngineUnstream().
~SCXTApplicationWindow()
~SCXTApplicationWindow ()
References scxt::messaging::client::engine, Engine::FOR_DAW, Engine::getSampleManager(), SCLOG, and scxt::json::streamEngineState().
Member Function Documentation
buttonClicked()
void buttonClicked (juce::Button * button) override
resized()
void resized () override
closeButtonPressed()
void closeButtonPressed () override
References SCLOG.
setupAudio()
void setupAudio ()
Member Data Documentation
audioCB
std::unique_ptr<AudioCallback> audioCB
optionsButton
juce::TextButton optionsButton
deviceManager
AudioDeviceManager deviceManager
engine
std::unique_ptr<scxt::engine::Engine> engine
Referenced by SCXTApplicationWindow::AudioCallback::audioDeviceAboutToStart(), and SCXTApplicationWindow::AudioCallback::audioDeviceIOCallbackWithContext().
editor
std::unique_ptr<scxt::ui::app::SCXTEditor> editor
properties
std::unique_ptr<juce::PropertiesFile> properties
editorHolder
std::unique_ptr<Intermediate> editorHolder
The documentation for this struct was generated from the following file:
scxt-juce-standalone.cpp