shortcircuit-xt: DriveFSRowComponent Struct Reference
DriveFSRowComponent Struct Reference
Public Member Functions
DriveFSRowComponent (BrowserPane *p, jcmp::ListView *v)
std::optional< fs::directory_entry > getDirEnt () const override
std::optional< sample::compound::CompoundElement > getCompoundElement () const override
void mouseDown (const juce::MouseEvent &event) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &event) override
void mouseUp ()
void mouseEnter (const juce::MouseEvent &) override
void mouseExit (const juce::MouseEvent &) override
void stopPreview ()
void mouseDoubleClick (const juce::MouseEvent &event) override
void showDirectoryPopup ()
bool isFile ()
void paint (juce::Graphics &g) override
Public Member Functions inherited from WithSampleInfo
virtual ~WithSampleInfo ()
Public Attributes
bool isSelected {false}
int rowNumber
BrowserPane * browserPane {nullptr}
jcmp::ListView * listView {nullptr}
bool isDragging {false}
bool isMouseDownWithoutDrag {false}
bool hasStartedPreview {false}
bool isHovered {false}
Static Public Attributes
static constexpr int32_t glyphSize {14}
Constructor & Destructor Documentation
DriveFSRowComponent()
DriveFSRowComponent (BrowserPane * p, jcmp::ListView * v)
Member Function Documentation
getDirEnt()
std::optional< fs::directory_entry > getDirEnt () const override virtual
Implements WithSampleInfo.
getCompoundElement()
std::optional< sample::compound::CompoundElement > getCompoundElement () const override virtual
Implements WithSampleInfo.
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References scxt::messaging::client::clientSendToSerialization().
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
mouseUp() [1/2]
void mouseUp (const juce::MouseEvent & event) override
mouseUp() [2/2]
void mouseUp ()
mouseEnter()
void mouseEnter (const juce::MouseEvent &) override
mouseExit()
void mouseExit (const juce::MouseEvent &) override
stopPreview()
void stopPreview ()
References scxt::messaging::client::clientSendToSerialization().
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & event) override
References scxt::messaging::client::clientSendToSerialization().
showDirectoryPopup()
void showDirectoryPopup ()
isFile()
bool isFile ()
paint()
void paint (juce::Graphics & g) override
Member Data Documentation
isSelected
bool isSelected {false}
Referenced by DriveFSArea::setupListView().
rowNumber
int rowNumber
Referenced by DriveFSArea::setupListView().
browserPane
BrowserPane* browserPane {nullptr}
listView
jcmp::ListView* listView {nullptr}
glyphSize
constexpr int32_t glyphSize {14} static constexpr
isDragging
bool isDragging {false}
isMouseDownWithoutDrag
bool isMouseDownWithoutDrag {false}
hasStartedPreview
bool hasStartedPreview {false}
isHovered
bool isHovered {false}
The documentation for this struct was generated from the following file:
BrowserPane.cpp