shortcircuit-xt: HasModulators< T, egsPerObject >::DoubleRate Struct Reference
HasModulators< T, egsPerObject >::DoubleRate Struct Reference
#include <has_modulators.h>
Public Member Functions
DoubleRate (T *that)
void resetRates ()
Public Attributes
double sampleRate {1}
double sampleRateInv {1}
T * that {nullptr}
Constructor & Destructor Documentation
DoubleRate()
template<typename T , size_t egsPerObject> DoubleRate (T * that) explicit
References HasModulators< T, egsPerObject >::DoubleRate::resetRates().
Member Function Documentation
resetRates()
template<typename T , size_t egsPerObject> void resetRates ()
References HasModulators< T, egsPerObject >::DoubleRate::sampleRate, HasModulators< T, egsPerObject >::DoubleRate::sampleRateInv, and HasModulators< T, egsPerObject >::DoubleRate::that.
Referenced by HasModulators< T, egsPerObject >::DoubleRate::DoubleRate(), and HasModulators< T, egsPerObject >::setHasModulatorsSampleRate().
Member Data Documentation
sampleRate
template<typename T , size_t egsPerObject> double sampleRate {1}
Referenced by HasModulators< T, egsPerObject >::DoubleRate::resetRates().
sampleRateInv
template<typename T , size_t egsPerObject> double sampleRateInv {1}
Referenced by HasModulators< T, egsPerObject >::DoubleRate::resetRates().
that
template<typename T , size_t egsPerObject> T* that {nullptr}
Referenced by HasModulators< T, egsPerObject >::DoubleRate::resetRates().
The documentation for this struct was generated from the following file:
has_modulators.h