shortcircuit-xt: StepLFOPane::StepRender Struct Reference
StepLFOPane::StepRender Struct Reference
Inherits Component.
Classes
struct StepMenuTypein
Public Member Functions
StepRender (LfoPane *p)
void paint (juce::Graphics &g) override
int indexForPosition (const juce::Point< float > &f)
void handleMouseAt (const juce::Point< float > &f)
void showTypeinPopup (const juce::Point< float > &f)
void mouseDown (const juce::MouseEvent &event) override
void mouseDrag (const juce::MouseEvent &event) override
void mouseDoubleClick (const juce::MouseEvent &event) override
void recalcCurve ()
Public Attributes
LfoPane * parent {nullptr}
std::vector< std::pair< float, float > > cycleCurve
Constructor & Destructor Documentation
StepRender()
StepRender (LfoPane * p)
References StepLFOPane::StepRender::recalcCurve().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References ColorMap::accent_2a, ColorMap::accent_2a_alpha_a, ColorMap::accent_2b, ColorMap::accent_2b_alpha_a, HasEditor::editor, ColorMap::generic_content_low, LfoPane::modulatorStorageData, StepLFOPane::StepRender::parent, StepLFOStorage::stepLfoSteps, and SCXTEditor::themeColor().
indexForPosition()
int indexForPosition (const juce::Point< float > & f)
References LfoPane::modulatorStorageData, StepLFOPane::StepRender::parent, and StepLFOStorage::stepLfoSteps.
Referenced by StepLFOPane::StepRender::handleMouseAt(), StepLFOPane::StepRender::mouseDoubleClick(), and StepLFOPane::StepRender::showTypeinPopup().
handleMouseAt()
void handleMouseAt (const juce::Point< float > & f)
References StepLFOPane::StepRender::indexForPosition(), StepLFOPane::StepRender::parent, StepLFOPane::StepRender::recalcCurve(), and LfoPane::stepLfoPane.
Referenced by StepLFOPane::StepRender::mouseDown(), and StepLFOPane::StepRender::mouseDrag().
showTypeinPopup()
void showTypeinPopup (const juce::Point< float > & f)
References SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, StepLFOPane::StepRender::indexForPosition(), and StepLFOPane::StepRender::parent.
Referenced by StepLFOPane::StepRender::mouseDown().
mouseDown()
void mouseDown (const juce::MouseEvent & event) override
References StepLFOPane::StepRender::handleMouseAt(), and StepLFOPane::StepRender::showTypeinPopup().
mouseDrag()
void mouseDrag (const juce::MouseEvent & event) override
References StepLFOPane::StepRender::handleMouseAt().
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & event) override
References StepLFOPane::StepRender::indexForPosition(), StepLFOPane::StepRender::parent, StepLFOPane::StepRender::recalcCurve(), and LfoPane::stepLfoPane.
recalcCurve()
void recalcCurve ()
References StepLFOPane::StepRender::cycleCurve, LfoPane::modulatorStorageData, and StepLFOPane::StepRender::parent.
Referenced by StepLFOPane::StepRender::handleMouseAt(), StepLFOPane::StepRender::mouseDoubleClick(), and StepLFOPane::StepRender::StepRender().
Member Data Documentation
parent
LfoPane* parent {nullptr}
Referenced by StepLFOPane::StepRender::handleMouseAt(), StepLFOPane::StepRender::indexForPosition(), StepLFOPane::StepRender::mouseDoubleClick(), StepLFOPane::StepRender::paint(), StepLFOPane::StepRender::recalcCurve(), and StepLFOPane::StepRender::showTypeinPopup().
cycleCurve
std::vector<std::pair<float, float> > cycleCurve
Referenced by StepLFOPane::StepRender::recalcCurve().
The documentation for this struct was generated from the following file:
LFOPane.cpp