shortcircuit-xt: ColorMap Struct Reference
ColorMap Struct Reference abstract
Public Types
enum BuiltInColorMaps : uint32_t { WIREFRAME = 'wire' , LIGHT = 'lite' , HICONTRAST_DARK = 'hico' , TEST = 'test' }
enum Colors : size_t {
accent_1a , accent_1b , accent_1b_alpha_a , accent_1b_alpha_b ,
accent_1b_alpha_c , accent_2a , accent_2a_alpha_a , accent_2a_alpha_b ,
accent_2a_alpha_c , accent_2b , accent_2b_alpha_a , accent_2b_alpha_b ,
accent_2b_alpha_c , bg_1 , bg_2 , bg_3 ,
gutter_2 , gutter_3 , panel_outline_2 , panel_outline_3 ,
knob_fill , generic_content_highest , generic_content_high , generic_content_medium ,
generic_content_low , generic_content_lowest , grid_primary , grid_secondary ,
warning_1a , warning_1b
}
Public Member Functions
virtual ~ColorMap ()=default
juce::Colour get (Colors c, float alpha=1.f) const
virtual juce::Colour getHover (Colors c, float alpha=1.f) const
virtual juce::Colour getImpl (Colors c, float alpha=1.f) const =0
std::string toJson () const
Static Public Member Functions
static std::unique_ptr< ColorMap > createColorMap (BuiltInColorMaps cm)
static std::unique_ptr< ColorMap > jsonToColormap (const std::string &json)
Public Attributes
enum scxt::ui::theme::ColorMap::BuiltInColorMaps WIREFRAME
bool hasKnobs {false}
float hoverFactor {0.1f}
Static Public Attributes
static constexpr uint32_t FILE_COLORMAP_ID {'fcmp'}
static constexpr int lastColor {(int)Colors::warning_1b}
Member Enumeration Documentation
BuiltInColorMaps
enum BuiltInColorMaps : uint32_t
Enumerator
WIREFRAME
LIGHT
HICONTRAST_DARK
TEST
Colors
enum Colors : size_t
Enumerator
accent_1a
accent_1b
accent_1b_alpha_a
accent_1b_alpha_b
accent_1b_alpha_c
accent_2a
accent_2a_alpha_a
accent_2a_alpha_b
accent_2a_alpha_c
accent_2b
accent_2b_alpha_a
accent_2b_alpha_b
accent_2b_alpha_c
bg_1
bg_2
bg_3
gutter_2
gutter_3
panel_outline_2
panel_outline_3
knob_fill
generic_content_highest
generic_content_high
generic_content_medium
generic_content_low
generic_content_lowest
grid_primary
grid_secondary
warning_1a
warning_1b
Constructor & Destructor Documentation
~ColorMap()
virtual ~ColorMap () virtual default
Member Function Documentation
createColorMap()
std::unique_ptr< ColorMap > createColorMap (BuiltInColorMaps cm) static
References ColorMap::HICONTRAST_DARK, JSONAssetLibrary::jsonForAsset(), ColorMap::jsonToColormap(), ColorMap::LIGHT, ColorMap::TEST, and ColorMap::WIREFRAME.
Referenced by SCXTEditor::addUIThemesMenu(), and SCXTEditor::resetColorsFromUserPreferences().
get()
juce::Colour get (Colors c, float alpha = 1.f) const
References ColorMap::getImpl(), ColorMap::hasKnobs, and ColorMap::knob_fill.
Referenced by ColorMap::getHover().
getHover()
virtual juce::Colour getHover (Colors c, float alpha = 1.f) const virtual
References ColorMap::get(), and ColorMap::hoverFactor.
getImpl()
virtual juce::Colour getImpl (Colors c, float alpha = 1.f) const pure virtual
Implemented in StdMapColormap.
Referenced by ColorMap::get(), and ColorMap::toJson().
toJson()
std::string toJson () const
References ColorMap::getImpl(), ColorMap::hoverFactor, scxt::ui::theme::keyName(), ColorMap::lastColor, and scxt::ui::theme::to_pretty_stream().
jsonToColormap()
std::unique_ptr< ColorMap > jsonToColormap (const std::string & json) static
Referenced by SCXTEditor::addUIThemesMenu(), ColorMap::createColorMap(), and SCXTEditor::resetColorsFromUserPreferences().
Member Data Documentation
WIREFRAME
enum scxt::ui::theme::ColorMap::BuiltInColorMaps WIREFRAME
Referenced by SCXTEditor::addUIThemesMenu(), ColorMap::createColorMap(), and SCXTEditor::resetColorsFromUserPreferences().
FILE_COLORMAP_ID
constexpr uint32_t FILE_COLORMAP_ID {'fcmp'} static constexpr
Referenced by SCXTEditor::addUIThemesMenu(), and SCXTEditor::resetColorsFromUserPreferences().
lastColor
constexpr int lastColor {(int)Colors::warning_1b} static constexpr
Referenced by StdMapColormap::setupFromColormap(), and ColorMap::toJson().
hasKnobs
bool hasKnobs {false}
Referenced by ColorMap::get().
hoverFactor
float hoverFactor {0.1f}
Referenced by ColorMap::getHover(), and ColorMap::toJson().
The documentation for this struct was generated from the following files:
ColorMap.h
ColorMap.cpp