shortcircuit-xt: PartGroupSidebar Struct Reference
PartGroupSidebar Struct Reference
Public Member Functions
PartGroupSidebar (SCXTEditor *)
~PartGroupSidebar ()
void setPartGroupZoneStructure (const engine::Engine::pgzStructure_t &p)
void editorSelectionChanged ()
void selectedPartChanged ()
void selectParts ()
void selectGroups ()
void setSelectedTab (int t)
void partConfigurationChanged (int i)
void resized () override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (const W &widget, const A &attachment)
Public Attributes
engine::Engine::pgzStructure_t pgzStructure
std::unique_ptr< ZoneSidebar > zoneSidebar
std::unique_ptr< GroupSidebar > groupSidebar
std::unique_ptr< PartSidebar > partSidebar
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
PartGroupSidebar()
PartGroupSidebar (SCXTEditor * e)
~PartGroupSidebar()
~PartGroupSidebar ()
Member Function Documentation
setPartGroupZoneStructure()
void setPartGroupZoneStructure (const engine::Engine::pgzStructure_t & p)
References PartGroupSidebar::editorSelectionChanged(), PartGroupSidebar::groupSidebar, PartGroupSidebar::pgzStructure, SCLOG, and PartGroupSidebar::zoneSidebar.
editorSelectionChanged()
void editorSelectionChanged ()
References PartGroupSidebar::groupSidebar, and PartGroupSidebar::zoneSidebar.
Referenced by PartGroupSidebar::selectedPartChanged(), and PartGroupSidebar::setPartGroupZoneStructure().
selectedPartChanged()
void selectedPartChanged ()
References HasEditor::editor, PartGroupSidebar::editorSelectionChanged(), PartGroupSidebar::groupSidebar, SCXTEditor::selectedPart, and PartGroupSidebar::zoneSidebar.
selectParts()
void selectParts ()
selectGroups()
void selectGroups ()
setSelectedTab()
void setSelectedTab (int t)
References ThemeApplier::applyGroupMultiScreenTheme(), ThemeApplier::applyZoneMultiScreenTheme(), HasEditor::editor, SCXTEditor::editScreen, EditScreen::GROUP, PartGroupSidebar::groupSidebar, PartGroupSidebar::partSidebar, SCXTEditor::setTabSelection(), SCXTEditor::themeApplier, EditScreen::ZONE, and PartGroupSidebar::zoneSidebar.
partConfigurationChanged()
void partConfigurationChanged (int i)
References PartGroupSidebar::partSidebar.
resized()
void resized () override
References PartGroupSidebar::groupSidebar, PartGroupSidebar::partSidebar, and PartGroupSidebar::zoneSidebar.
Member Data Documentation
pgzStructure
engine::Engine::pgzStructure_t pgzStructure
Referenced by PartGroupSidebar::setPartGroupZoneStructure().
zoneSidebar
std::unique_ptr<ZoneSidebar> zoneSidebar
Referenced by PartGroupSidebar::editorSelectionChanged(), PartGroupSidebar::resized(), PartGroupSidebar::selectedPartChanged(), PartGroupSidebar::setPartGroupZoneStructure(), and PartGroupSidebar::setSelectedTab().
groupSidebar
std::unique_ptr<GroupSidebar> groupSidebar
Referenced by PartGroupSidebar::editorSelectionChanged(), PartGroupSidebar::resized(), PartGroupSidebar::selectedPartChanged(), PartGroupSidebar::setPartGroupZoneStructure(), and PartGroupSidebar::setSelectedTab().
partSidebar
std::unique_ptr<PartSidebar> partSidebar
Referenced by PartGroupSidebar::partConfigurationChanged(), PartGroupSidebar::resized(), and PartGroupSidebar::setSelectedTab().
The documentation for this struct was generated from the following files:
PartGroupSidebar.h
PartGroupSidebar.cpp