shortcircuit-xt: Group Struct Reference
Group Struct Reference
#include <group.h>
Classes
struct GroupOutputInfo
Public Types
using lipol = sst::basic_blocks::dsp::lipol_sse< blockSize, false >
using lipolOS = sst::basic_blocks::dsp::lipol_sse< blockSize<< 1, false >
typedef std::vector< std::unique_ptr< Zone > > zoneContainer_t
Public Types inherited from HasGroupZoneProcessors< Group >
enum ProcRoutingPath
Public Types inherited from HasModulators< Group, egsPerGroup >
enum LFOEvaluator
typedef sst::basic_blocks::modulators::AHDSRShapedSC< Group, blockSize, sst::basic_blocks::modulators::TwentyFiveSecondExp > ahdsrenv_t
typedef sst::basic_blocks::modulators::AHDSRShapedSC< DoubleRate,(blockSize<< 1), sst::basic_blocks::modulators::TwentyFiveSecondExp > ahdsrenvOS_t
Public Member Functions
Group ()
virtual ~Group ()
Engine * getEngine ()
const Engine * getEngine () const
void attack ()
void resetLFOs (int whichLFO=-1)
void process (Engine &onto)
template<bool OS>
void processWithOS (Engine &onto)
void setupOnUnstream (engine::Engine &e)
std::string getName () const
size_t addZone (std::unique_ptr< Zone > &z)
size_t addZone (std::unique_ptr< Zone > &&z)
void clearZones ()
int getZoneIndex (const ZoneID &zid) const
const std::unique_ptr< Zone > & getZone (int idx) const
const std::unique_ptr< Zone > & getZone (const ZoneID &zid) const
std::unique_ptr< Zone > removeZone (const ZoneID &zid)
void swapZonesByIndex (size_t zoneIndex0, size_t zoneIndex1)
bool isActive () const
void addActiveZone (engine::Zone *zoneWP)
void removeActiveZone (engine::Zone *zoneWP)
void onSampleRateChanged () override
void resetPolyAndPlaymode (engine::Engine &)
void onRoutingChanged ()
void rePrepareAndBindGroupMatrix ()
float envelope_rate_linear_nowrap (float f)
void onProcessorTypeChanged (int w, dsp::processor::ProcessorType t)
bool hasActiveZones () const
bool inRingout () const
bool hasActiveEGs () const
bool updateRingout ()
const zoneContainer_t & getZones () const
zoneContainer_t::iterator begin () noexcept
zoneContainer_t::const_iterator cbegin () const noexcept
zoneContainer_t::iterator end () noexcept
zoneContainer_t::const_iterator cend () const noexcept
bool isInTerminationFadeout () const
Public Member Functions inherited from MoveableOnly< Group >
MoveableOnly (MoveableOnly &&)=default
MoveableOnly (const MoveableOnly &)=delete
MoveableOnly & operator= (const MoveableOnly &)=delete
Public Member Functions inherited from HasGroupZoneProcessors< Group >
DECLARE_ENUM_STRING (ProcRoutingPath)
Group * asT ()
void setProcessorType (int whichProcessor, dsp::processor::ProcessorType type)
void setupProcessorControlDescriptions (int whichProcessor, dsp::processor::ProcessorType, dsp::processor::Processor *tmpProcessor=nullptr, bool reClampFloatValues=false)
dsp::processor::Processor * spawnTempProcessor (int whichProcessor, dsp::processor::ProcessorType type, uint8_t *mem, float *pfp, int *ifp, bool initFromDefaults)
bool checkOrAdjustIntConsistency (int whichProcessor)
bool checkOrAdjustBoolConsistency (int whichProcessor)
void updateRoutingTableAfterProcessorSwap (size_t f, size_t t)
Public Member Functions inherited from HasModulators< Group, egsPerGroup >
HasModulators (Group *that)
void setHasModulatorsSampleRate (double sr, double sri)
void updateRetriggers (Endpoints *endpoints)
Public Member Functions inherited from SampleRateSupport
void setSampleRate (double sr)
void setSampleRate (double sr, double sri)
double getSampleRate () const
double getSampleRateInv () const
void sync ()
bool isSampleRateSet ()
void assertSampleRateSet ()
Public Attributes
GroupID id
std::string name {}
Part * parentPart {nullptr}
struct scxt::engine::Group::GroupOutputInfo outputInfo
GroupTriggerConditions triggerConditions
float output [2][blockSize<< 1]
bool lastOversample {true}
sst::filters::HalfRate::HalfRateFilter osDownFilter
lipol outputAmp
lipolOS outputAmpOS
std::array< modulation::modulators::AdsrStorage, egsPerGroup > gegStorage {}
std::array< modulation::ModulatorStorage, lfosPerGroup > modulatorStorage
modulation::MiscSourceStorage miscSourceStorage
bool initializedLFOs {false}
modulation::GroupMatrix modMatrix
modulation::GroupMatrixEndpoints endpoints
modulation::GroupMatrix::RoutingTable routingTable
std::array< dsp::processor::Processor *, engine::processorCount > processors {}
uint8_t processorPlacementStorage [engine::processorCount][dsp::processor::processorMemoryBufferSize]
int32_t processorIntParams [engine::processorCount][dsp::processor::maxProcessorIntParams]
lipol processorMix [engine::processorCount]
lipolOS processorMixOS [engine::processorCount]
lipol processorLevel [engine::processorCount]
lipolOS processorLevelOS [engine::processorCount]
sst::basic_blocks::dsp::UIComponentLagHandler mUILag
uint32_t activeZones {0}
int32_t ringoutTime {0}
int32_t ringoutMax {0}
bool attackInThisBlock {false}
bool gated {false}
float fGatedCount {0}
float fVoiceCount {0}
float fAnyGated {0}
float fAnySounding {0}
int32_t blocksToTerminate {-1}
int32_t terminationSequence {-1}
Public Attributes inherited from HasGroupZoneProcessors< Group >
std::array< dsp::processor::ProcessorStorage, processorCount > processorStorage
std::array< dsp::processor::ProcessorControlDescription, processorCount > processorDescription
Public Attributes inherited from HasModulators< Group, egsPerGroup >
struct scxt::modulation::shared::HasModulators::DoubleRate doubleRate
enum scxt::modulation::shared::HasModulators::LFOEvaluator lfoEvaluator [lfosPerObject]
std::array< scxt::modulation::modulators::StepLFO, lfosPerObject > stepLfos
std::array< scxt::modulation::modulators::CurveLFO, lfosPerObject > curveLfos
std::array< scxt::modulation::modulators::EnvLFO, lfosPerObject > envLfos
scxt::modulation::modulators::RandomEvaluator randomEvaluator
scxt::modulation::modulators::PhasorEvaluator phasorEvaluator
std::array< ahdsrenv_t, egsPerObject > eg
std::array< ahdsrenvOS_t, egsPerObject > egOS
std::array< bool, lfosPerObject > lfosActive
std::array< bool, egsPerObject > egsActive
bool phasorsActive
std::array< bool, egsPerObject > doEGRetrigger
std::array< float, egsPerObject > lastEGRetrigger
std::array< bool, lfosPerObject > doLFORetrigger
std::array< float, lfosPerObject > lastLFORetrigger
Public Attributes inherited from SampleRateSupport
double dsamplerate
double dsamplerate_inv
double sampleRate {1}
double sampleRateInv {1}
double samplerate
double samplerate_inv
Static Public Attributes
static constexpr int32_t blocksToTerminateAt48k {16}
Static Public Attributes inherited from HasGroupZoneProcessors< Group >
static constexpr bool forGroup
static constexpr bool forZone
static constexpr int processorCount
Static Public Attributes inherited from HasModulators< Group, egsPerGroup >
static constexpr uint16_t lfosPerObject
Additional Inherited Members
Static Public Member Functions inherited from HasGroupZoneProcessors< Group >
static std::string getProcRoutingPathDisplayName (ProcRoutingPath p)
static std::string getProcRoutingPathShortName (ProcRoutingPath p)
Protected Member Functions inherited from MoveableOnly< Group >
MoveableOnly ()
~MoveableOnly ()=default
Member Typedef Documentation
lipol
using lipol = sst::basic_blocks::dsp::lipol_sse<blockSize, false>
lipolOS
using lipolOS = sst::basic_blocks::dsp::lipol_sse<blockSize << 1, false>
zoneContainer_t
typedef std::vector<std::unique_ptr<Zone> > zoneContainer_t
Constructor & Destructor Documentation
Group()
Group ()
~Group()
virtual ~Group () virtual
References Group::processors, and scxt::dsp::processor::unspawnProcessor().
Member Function Documentation
getEngine() [1/2]
engine::Engine * getEngine ()
References Patch::parentEngine, Group::parentPart, and Part::parentPatch.
Referenced by Group::addZone(), Group::addZone(), Group::attack(), scxt::modulation::getGroupMatrixMetadata(), Group::onProcessorTypeChanged(), Group::onSampleRateChanged(), Group::resetLFOs(), and Group::setupOnUnstream().
getEngine() [2/2]
const engine::Engine * getEngine () const
References Patch::parentEngine, Group::parentPart, and Part::parentPatch.
attack()
void attack ()
References Group::attackInThisBlock, HasModulators< Group, egsPerGroup >::eg, GroupMatrixEndpoints::egTarget, Group::endpoints, HasModulators< Group, egsPerGroup >::envLfos, RandomEvaluator::evaluate(), Group::getEngine(), Group::isActive(), GroupMatrixEndpoints::lfo, HasModulators< Group, egsPerGroup >::lfosActive, scxt::engine::lfosPerGroup, ProcessorStorage::maxOutputAmp, Group::miscSourceStorage, Group::modulatorStorage, Group::osDownFilter, Group::processorLevel, Group::processorLevelOS, Group::processorMix, Group::processorMixOS, Group::processors, HasGroupZoneProcessors< Group >::processorStorage, GroupMatrixEndpoints::processorTarget, HasModulators< Group, egsPerGroup >::randomEvaluator, Group::rePrepareAndBindGroupMatrix(), and Group::resetLFOs().
Referenced by Group::addActiveZone(), and Group::processWithOS().
resetLFOs()
void resetLFOs (int whichLFO = -1)
References PhasorEvaluator::attack(), HasModulators< Group, egsPerGroup >::CURVE, HasModulators< Group, egsPerGroup >::curveLfos, Group::endpoints, HasModulators< Group, egsPerGroup >::ENV, HasModulators< Group, egsPerGroup >::envLfos, RandomEvaluator::evaluate(), Group::getEngine(), GroupMatrixEndpoints::lfo, HasModulators< Group, egsPerGroup >::lfoEvaluator, scxt::engine::lfosPerGroup, Group::miscSourceStorage, Group::modulatorStorage, HasModulators< Group, egsPerGroup >::MSEG, HasModulators< Group, egsPerGroup >::phasorEvaluator, HasModulators< Group, egsPerGroup >::randomEvaluator, Engine::rng, SampleRateSupport::sampleRate, SampleRateSupport::sampleRateInv, SCLOG, HasModulators< Group, egsPerGroup >::STEP, HasModulators< Group, egsPerGroup >::stepLfos, and Engine::transport.
Referenced by Group::attack().
process()
void process (Engine & onto)
References Group::outputInfo, and Group::GroupOutputInfo::oversample.
processWithOS()
template<bool OS> void processWithOS (Engine & onto)
References Group::activeZones, GroupMatrixEndpoints::OutputTarget::ampP, SampleRateSupport::assertSampleRateSet(), Group::attack(), Group::attackInThisBlock, Group::blocksToTerminate, Group::blocksToTerminateAt48k, CALL_ROUTE, HasModulators< Group, egsPerGroup >::CURVE, HasModulators< Group, egsPerGroup >::curveLfos, scxt::engine::DEFAULT_BUS, HasModulators< Group, egsPerGroup >::doEGRetrigger, HasModulators< Group, egsPerGroup >::doLFORetrigger, HasModulators< Group, egsPerGroup >::eg, HasModulators< Group, egsPerGroup >::egsActive, GroupMatrixEndpoints::egTarget, Group::endpoints, HasModulators< Group, egsPerGroup >::ENV, HasModulators< Group, egsPerGroup >::envLfos, Group::fAnyGated, Group::fAnySounding, Group::fGatedCount, Group::fVoiceCount, Group::gated, Group::hasActiveEGs(), Group::inRingout(), Group::lastOversample, GroupMatrixEndpoints::lfo, HasModulators< Group, egsPerGroup >::lfoEvaluator, HasModulators< Group, egsPerGroup >::lfosActive, scxt::engine::lfosPerGroup, Group::miscSourceStorage, Group::modMatrix, Group::modulatorStorage, Group::mUILag, Group::onProcessorTypeChanged(), Group::osDownFilter, Group::output, Group::outputAmp, Group::outputAmpOS, Group::outputInfo, GroupMatrixEndpoints::outputTarget, Group::GroupOutputInfo::oversample, GroupMatrixEndpoints::OutputTarget::panP, Group::parentPart, HasModulators< Group, egsPerGroup >::phasorEvaluator, scxt::engine::processorCount, Group::processorIntParams, Group::processors, HasGroupZoneProcessors< Group >::processorStorage, Group::GroupOutputInfo::procRouting, Part::removeActiveGroup(), Group::ringoutMax, Group::ringoutTime, SampleRateSupport::sampleRate, HasModulators< Group, egsPerGroup >::STEP, PhasorEvaluator::step(), HasModulators< Group, egsPerGroup >::stepLfos, Group::terminationSequence, Engine::transport, HasModulators< Group, egsPerGroup >::updateRetriggers(), and Group::updateRingout().
setupOnUnstream()
void setupOnUnstream (engine::Engine & e)
References HasModulators< Group, egsPerGroup >::curveLfos, Group::endpoints, Group::getEngine(), Part::groupTriggerInstrumentState, GroupMatrixEndpoints::lfo, scxt::engine::lfosPerZone, Group::modulatorStorage, Group::onProcessorTypeChanged(), Group::onRoutingChanged(), Group::parentPart, HasGroupZoneProcessors< Group >::processorCount, Group::processors, HasGroupZoneProcessors< Group >::processorStorage, Group::rePrepareAndBindGroupMatrix(), Group::resetPolyAndPlaymode(), SampleRateSupport::sampleRate, SampleRateSupport::sampleRateInv, GroupTriggerConditions::setupOnUnstream(), HasGroupZoneProcessors< Group >::setupProcessorControlDescriptions(), HasModulators< Group, egsPerGroup >::stepLfos, Group::triggerConditions, and scxt::dsp::processor::unspawnProcessor().
Referenced by Group::onSampleRateChanged().
getName()
std::string getName () const
References Group::name.
addZone() [1/2]
size_t addZone (std::unique_ptr< Zone > & z)
References Group::getEngine().
addZone() [2/2]
size_t addZone (std::unique_ptr< Zone > && z)
References Group::getEngine().
clearZones()
void clearZones ()
getZoneIndex()
int getZoneIndex (const ZoneID & zid) const
Referenced by Group::getZone(), and Group::removeZone().
getZone() [1/2]
const std::unique_ptr< Zone > & getZone (int idx) const
getZone() [2/2]
const std::unique_ptr< Zone > & getZone (const ZoneID & zid) const
References Group::getZoneIndex(), and ID< idType_v >::to_string().
removeZone()
std::unique_ptr< Zone > removeZone (const ZoneID & zid)
References Group::getZoneIndex().
swapZonesByIndex()
void swapZonesByIndex (size_t zoneIndex0, size_t zoneIndex1)
isActive()
bool isActive () const
References Group::hasActiveEGs(), Group::hasActiveZones(), Group::inRingout(), and Group::isInTerminationFadeout().
Referenced by Group::attack().
addActiveZone()
void addActiveZone (engine::Zone * zoneWP)
References Group::activeZones, Part::addActiveGroup(), Group::attack(), Group::parentPart, and Group::ringoutTime.
Referenced by Zone::addVoice().
removeActiveZone()
void removeActiveZone (engine::Zone * zoneWP)
References Group::activeZones.
Referenced by Zone::removeVoice().
onSampleRateChanged()
void onSampleRateChanged () override virtual
Reimplemented from SampleRateSupport.
References Group::getEngine(), SampleRateSupport::getSampleRate(), SampleRateSupport::getSampleRateInv(), HasModulators< Group, egsPerGroup >::setHasModulatorsSampleRate(), and Group::setupOnUnstream().
resetPolyAndPlaymode()
void resetPolyAndPlaymode (engine::Engine & e)
References Group::GroupOutputInfo::hasIndependentPolyLimit, Group::outputInfo, Group::GroupOutputInfo::polyLimit, SCLOG_IF, Group::GroupOutputInfo::vmPlayModeFeaturesInt, Group::GroupOutputInfo::vmPlayModeInt, and Engine::voiceManager.
Referenced by Group::setupOnUnstream().
onRoutingChanged()
void onRoutingChanged ()
References Group::rePrepareAndBindGroupMatrix().
Referenced by Group::setupOnUnstream().
rePrepareAndBindGroupMatrix()
void rePrepareAndBindGroupMatrix ()
References GroupMatrixEndpoints::Sources::bind(), GroupMatrixEndpoints::bindTargetBaseValues(), HasModulators< Group, egsPerGroup >::CURVE, HasModulators< Group, egsPerGroup >::egsActive, Group::endpoints, HasModulators< Group, egsPerGroup >::ENV, SampleRateSupport::getSampleRate(), HasModulators< Group, egsPerGroup >::lfoEvaluator, HasModulators< Group, egsPerGroup >::lfosActive, scxt::engine::lfosPerGroup, Group::modMatrix, Group::modulatorStorage, HasModulators< Group, egsPerGroup >::MSEG, Group::routingTable, GroupMatrixEndpoints::sources, and HasModulators< Group, egsPerGroup >::STEP.
Referenced by Group::attack(), Group::onRoutingChanged(), Zone::onRoutingChanged(), and Group::setupOnUnstream().
envelope_rate_linear_nowrap()
float envelope_rate_linear_nowrap (float f)
References SampleRateSupport::sampleRateInv, and scxt::dsp::twoToTheXTable.
onProcessorTypeChanged()
void onProcessorTypeChanged (int w, dsp::processor::ProcessorType t)
References HasGroupZoneProcessors< Group >::asT(), Group::endpoints, Group::getEngine(), Group::outputInfo, Group::GroupOutputInfo::oversample, Group::processorPlacementStorage, Group::processors, HasGroupZoneProcessors< Group >::processorStorage, GroupMatrixEndpoints::processorTarget, scxt::dsp::processor::proct_none, SampleRateSupport::sampleRate, scxt::dsp::processor::spawnProcessorInPlace(), Engine::transport, and scxt::dsp::processor::unspawnProcessor().
Referenced by Group::processWithOS(), and Group::setupOnUnstream().
hasActiveZones()
bool hasActiveZones () const
References Group::activeZones.
Referenced by Group::isActive().
inRingout()
bool inRingout () const
References Group::ringoutMax, and Group::ringoutTime.
Referenced by Group::isActive(), and Group::processWithOS().
hasActiveEGs()
bool hasActiveEGs () const
References HasModulators< Group, egsPerGroup >::eg, HasModulators< Group, egsPerGroup >::egsActive, HasModulators< Group, egsPerGroup >::envLfos, HasModulators< Group, egsPerGroup >::lfosActive, and Group::modulatorStorage.
Referenced by Group::isActive(), and Group::processWithOS().
updateRingout()
bool updateRingout ()
References Group::processors, Group::ringoutMax, Group::ringoutTime, and SampleRateSupport::sampleRate.
Referenced by Group::processWithOS().
getZones()
const zoneContainer_t & getZones () const
begin()
zoneContainer_t::iterator begin () noexcept
cbegin()
zoneContainer_t::const_iterator cbegin () const noexcept
end()
zoneContainer_t::iterator end () noexcept
cend()
zoneContainer_t::const_iterator cend () const noexcept
isInTerminationFadeout()
bool isInTerminationFadeout () const
References Group::blocksToTerminate, and Group::terminationSequence.
Referenced by Group::isActive().
Member Data Documentation
id
GroupID id
name
std::string name {}
Referenced by Group::getName().
parentPart
Part* parentPart {nullptr}
Referenced by Group::addActiveZone(), GroupMatrixEndpoints::Sources::bind(), MatrixEndpoints::Sources::bind(), Voice::calculateGeneratorRatio(), Voice::calculateVoicePitch(), Group::getEngine(), Group::getEngine(), Group::processWithOS(), Group::setupOnUnstream(), Engine::VoiceManagerResponder::setVoiceMIDIMPEChannelPitchBend(), Engine::VoiceManagerResponder::setVoiceMIDIMPEChannelPressure(), Engine::VoiceManagerResponder::setVoiceMIDIMPETimbre(), GTMacro::value(), and GTMIDI1CC::value().
outputInfo
detail::updateGroupMemberValue outputInfo
Referenced by GroupMatrixEndpoints::OutputTarget::bind(), Group::onProcessorTypeChanged(), Group::process(), Zone::process(), Voice::processWithOS(), Group::processWithOS(), Group::resetPolyAndPlaymode(), and Voice::voiceStarted().
triggerConditions
GroupTriggerConditions triggerConditions
Referenced by Group::setupOnUnstream().
output
float output[2][blockSize<< 1]
Referenced by Group::processWithOS().
lastOversample
bool lastOversample {true}
Referenced by Group::processWithOS().
osDownFilter
sst::filters::HalfRate::HalfRateFilter osDownFilter
Referenced by Group::attack(), and Group::processWithOS().
outputAmp
lipol outputAmp
Referenced by Group::processWithOS().
outputAmpOS
lipolOS outputAmpOS
Referenced by Group::processWithOS().
gegStorage
std::array<modulation::modulators::AdsrStorage, egsPerGroup> gegStorage {}
Referenced by GroupMatrixEndpoints::EGTarget::bind().
modulatorStorage
std::array<modulation::ModulatorStorage, lfosPerGroup> modulatorStorage
Referenced by Group::attack(), Group::hasActiveEGs(), Group::processWithOS(), Group::rePrepareAndBindGroupMatrix(), Group::resetLFOs(), and Group::setupOnUnstream().
miscSourceStorage
modulation::MiscSourceStorage miscSourceStorage
Referenced by Group::attack(), Group::processWithOS(), and Group::resetLFOs().
initializedLFOs
bool initializedLFOs {false}
modMatrix
modulation::GroupMatrix modMatrix
Referenced by Group::processWithOS(), and Group::rePrepareAndBindGroupMatrix().
endpoints
modulation::GroupMatrixEndpoints endpoints
Referenced by Group::attack(), Group::onProcessorTypeChanged(), Group::processWithOS(), Group::rePrepareAndBindGroupMatrix(), Group::resetLFOs(), and Group::setupOnUnstream().
routingTable
modulation::GroupMatrix::RoutingTable routingTable
Referenced by Group::rePrepareAndBindGroupMatrix().
processors
std::array<dsp::processor::Processor *, engine::processorCount> processors {}
Referenced by Group::attack(), Group::onProcessorTypeChanged(), Group::processWithOS(), Group::setupOnUnstream(), Group::updateRingout(), and Group::~Group().
processorPlacementStorage
uint8_t processorPlacementStorage[engine::processorCount][dsp::processor::processorMemoryBufferSize]
Referenced by Group::onProcessorTypeChanged().
processorIntParams
int32_t processorIntParams[engine::processorCount][dsp::processor::maxProcessorIntParams]
Referenced by Group::processWithOS().
processorMix
lipol processorMix[engine::processorCount]
Referenced by Group::attack().
processorMixOS
lipolOS processorMixOS[engine::processorCount]
Referenced by Group::attack().
processorLevel
lipol processorLevel[engine::processorCount]
Referenced by Group::attack().
processorLevelOS
lipolOS processorLevelOS[engine::processorCount]
Referenced by Group::attack().
mUILag
sst::basic_blocks::dsp::UIComponentLagHandler mUILag
Referenced by Group::processWithOS().
activeZones
uint32_t activeZones {0}
Referenced by Group::addActiveZone(), Group::hasActiveZones(), Group::processWithOS(), and Group::removeActiveZone().
ringoutTime
int32_t ringoutTime {0}
Referenced by Group::addActiveZone(), Group::inRingout(), Group::processWithOS(), and Group::updateRingout().
ringoutMax
int32_t ringoutMax {0}
Referenced by Group::inRingout(), Group::processWithOS(), and Group::updateRingout().
attackInThisBlock
bool attackInThisBlock {false}
Referenced by Group::attack(), and Group::processWithOS().
gated
bool gated {false}
Referenced by Group::processWithOS().
fGatedCount
float fGatedCount {0}
Referenced by GroupMatrixEndpoints::Sources::bind(), and Group::processWithOS().
fVoiceCount
float fVoiceCount {0}
Referenced by GroupMatrixEndpoints::Sources::bind(), and Group::processWithOS().
fAnyGated
float fAnyGated {0}
Referenced by GroupMatrixEndpoints::Sources::bind(), and Group::processWithOS().
fAnySounding
float fAnySounding {0}
Referenced by GroupMatrixEndpoints::Sources::bind(), and Group::processWithOS().
blocksToTerminateAt48k
constexpr int32_t blocksToTerminateAt48k {16} static constexpr
Referenced by Group::processWithOS().
blocksToTerminate
int32_t blocksToTerminate {-1}
Referenced by Group::isInTerminationFadeout(), and Group::processWithOS().
terminationSequence
int32_t terminationSequence {-1}
Referenced by Group::isInTerminationFadeout(), and Group::processWithOS().
The documentation for this struct was generated from the following files:
group.h
group.cpp
group_messages.h