shortcircuit-xt: SampleWaveform Struct Reference
SampleWaveform Struct Reference
Public Types
enum class MouseState {
NONE , HZ_DRAG_SAMPSTART , HZ_DRAG_SAMPEND , HZ_DRAG_LOOPSTART ,
HZ_DRAG_LOOPEND
}
Public Member Functions
SampleWaveform (SampleDisplay *d)
void paint (juce::Graphics &g) override
void resized () override
juce::Path pathForSample ()
void rebuildHotZones ()
void updateSamplePlaybackPosition (int64_t samplePos)
int64_t sampleForXPixel (float xpos)
int xPixelForSample (int64_t samplePos)
void mouseDown (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseMove (const juce::MouseEvent &e) override
void mouseDoubleClick (const juce::MouseEvent &e) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (const W &widget, const A &attachment)
Public Attributes
SampleDisplay * display {nullptr}
juce::Rectangle< int > startSampleHZ
juce::Rectangle< int > endSampleHZ
juce::Rectangle< int > startLoopHZ
juce::Rectangle< int > endLoopHZ
juce::Rectangle< int > fadeLoopHz
enum scxt::ui::multi::SampleWaveform::MouseState NONE
SampleCursor samplePlaybackPosition
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Member Enumeration Documentation
MouseState
enum MouseState strong
Enumerator
NONE
HZ_DRAG_SAMPSTART
HZ_DRAG_SAMPEND
HZ_DRAG_LOOPSTART
HZ_DRAG_LOOPEND
Constructor & Destructor Documentation
SampleWaveform()
SampleWaveform (SampleDisplay * d)
References SampleWaveform::samplePlaybackPosition.
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References SampleDisplay::active, SampleWaveform::display, HasEditor::editor, SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::fadeLoopHz, SampleManager::getSample(), SampleWaveform::pathForSample(), SCXTEditor::sampleManager, Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, SampleDisplay::selectedVariation, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
resized()
void resized () override
References SampleWaveform::rebuildHotZones(), and SampleWaveform::samplePlaybackPosition.
pathForSample()
juce::Path pathForSample ()
References Sample::BD_F32, Sample::BD_I16, SampleWaveform::display, HasEditor::editor, SampleManager::getSample(), SCXTEditor::sampleManager, Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, SCLOG, and SampleDisplay::selectedVariation.
Referenced by SampleWaveform::paint().
rebuildHotZones()
void rebuildHotZones ()
References SampleWaveform::display, HasEditor::editor, SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::fadeLoopHz, SampleManager::getSample(), SCXTEditor::sampleManager, Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, SampleDisplay::selectedVariation, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
Referenced by SampleWaveform::resized().
updateSamplePlaybackPosition()
void updateSamplePlaybackPosition (int64_t samplePos)
References SampleWaveform::samplePlaybackPosition, and SampleWaveform::xPixelForSample().
sampleForXPixel()
int64_t sampleForXPixel (float xpos)
References SampleWaveform::display, HasEditor::editor, SampleManager::getSample(), SCXTEditor::sampleManager, Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, and SampleDisplay::selectedVariation.
Referenced by SampleWaveform::mouseDrag().
xPixelForSample()
int xPixelForSample (int64_t samplePos)
References SampleWaveform::display, HasEditor::editor, SampleManager::getSample(), SCXTEditor::sampleManager, Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, and SampleDisplay::selectedVariation.
Referenced by SampleWaveform::updateSamplePlaybackPosition().
mouseDown()
void mouseDown (const juce::MouseEvent & e) override
References SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::HZ_DRAG_LOOPEND, SampleWaveform::HZ_DRAG_LOOPSTART, SampleWaveform::HZ_DRAG_SAMPEND, SampleWaveform::HZ_DRAG_SAMPSTART, SampleWaveform::NONE, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
References SampleWaveform::display, SampleWaveform::NONE, and SampleDisplay::onSamplePointChangedFromGUI().
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
References SampleWaveform::display, SampleWaveform::HZ_DRAG_LOOPEND, SampleWaveform::HZ_DRAG_LOOPSTART, SampleWaveform::HZ_DRAG_SAMPEND, SampleWaveform::HZ_DRAG_SAMPSTART, SampleWaveform::NONE, SampleDisplay::onSamplePointChangedFromGUI(), SampleWaveform::sampleForXPixel(), Zone::AssociatedSampleSet::samples, SampleDisplay::sampleView, and SampleDisplay::selectedVariation.
mouseMove()
void mouseMove (const juce::MouseEvent & e) override
References SampleWaveform::endLoopHZ, SampleWaveform::endSampleHZ, SampleWaveform::startLoopHZ, and SampleWaveform::startSampleHZ.
mouseDoubleClick()
void mouseDoubleClick (const juce::MouseEvent & e) override
References SampleWaveform::display, and SampleDisplay::parentPane.
Member Data Documentation
display
SampleDisplay* display {nullptr}
Referenced by SampleWaveform::mouseDoubleClick(), SampleWaveform::mouseDrag(), SampleWaveform::mouseUp(), SampleWaveform::paint(), SampleWaveform::pathForSample(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), and SampleWaveform::xPixelForSample().
startSampleHZ
juce::Rectangle<int> startSampleHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
endSampleHZ
juce::Rectangle<int> endSampleHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
startLoopHZ
juce::Rectangle<int> startLoopHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
endLoopHZ
juce::Rectangle<int> endLoopHZ
Referenced by SampleWaveform::mouseDown(), SampleWaveform::mouseMove(), SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
fadeLoopHz
juce::Rectangle<int> fadeLoopHz
Referenced by SampleWaveform::paint(), and SampleWaveform::rebuildHotZones().
NONE
enum scxt::ui::multi::SampleWaveform::MouseState NONE
samplePlaybackPosition
SampleCursor samplePlaybackPosition
Referenced by SampleWaveform::resized(), SampleWaveform::SampleWaveform(), and SampleWaveform::updateSamplePlaybackPosition().
The documentation for this struct was generated from the following file:
MappingPane.cpp