shortcircuit-xt: LogScreen Struct Reference
LogScreen Struct Reference
Public Member Functions
LogScreen (SCXTEditor *e)
void visibilityChanged () override
void reshowLog ()
void resized () override
void paint (juce::Graphics &g) override
bool keyPressed (const juce::KeyPress &key) override
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (LogScreen)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
Public Attributes
std::unique_ptr< juce::TextEditor > logDisplay
std::unique_ptr< juce::TextButton > copyButton
std::unique_ptr< juce::TextButton > closeButton
juce::Font displayFont {}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
LogScreen()
LogScreen (SCXTEditor * e)
References ThemeApplier::anonmyousProRegularFor(), LogScreen::closeButton, LogScreen::displayFont, HasEditor::editor, scxt::ui::connectors::resources::loadTypeface(), LogScreen::logDisplay, and SCXTEditor::themeApplier.
Member Function Documentation
visibilityChanged()
void visibilityChanged () override
References LogScreen::logDisplay, and LogScreen::reshowLog().
reshowLog()
void reshowLog ()
References scxt::getFullLog(), and LogScreen::logDisplay.
Referenced by LogScreen::visibilityChanged().
resized()
void resized () override
References LogScreen::closeButton, and LogScreen::logDisplay.
paint()
void paint (juce::Graphics & g) override
keyPressed()
bool keyPressed (const juce::KeyPress & key) override
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR()
JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (LogScreen)
Member Data Documentation
logDisplay
std::unique_ptr<juce::TextEditor> logDisplay
Referenced by LogScreen::LogScreen(), LogScreen::reshowLog(), LogScreen::resized(), and LogScreen::visibilityChanged().
copyButton
std::unique_ptr<juce::TextButton> copyButton
closeButton
std::unique_ptr<juce::TextButton> closeButton
Referenced by LogScreen::LogScreen(), and LogScreen::resized().
displayFont
juce::Font displayFont {}
Referenced by LogScreen::LogScreen().
The documentation for this struct was generated from the following files:
LogScreen.h
LogScreen.cpp