shortcircuit-xt: ProcessorPane Struct Reference
ProcessorPane Struct Reference
#include <ProcessorPane.h>
Public Types
typedef connectors::PayloadDataAttachment< dsp::processor::ProcessorStorage > attachment_t
typedef connectors::DiscretePayloadDataAttachment< dsp::processor::ProcessorStorage > int_attachment_t
typedef connectors::BooleanPayloadDataAttachment< dsp::processor::ProcessorStorage > bool_attachment_t
using floatEditor_t = theme::layout::Labeled< sst::jucegui::components::ContinuousParamEditor >
using intEditor_t = theme::layout::Labeled< sst::jucegui::components::DiscreteParamEditor >
using jsonFloatEditor_t = std::unique_ptr< sst::jucegui::components::ContinuousParamEditor >
using jsonIntEditor_t = std::unique_ptr< sst::jucegui::components::DiscreteParamEditor >
Public Member Functions
ProcessorPane (SCXTEditor *, int index, bool)
~ProcessorPane ()
void setProcessorControlDescriptionAndStorage (const dsp::processor::ProcessorControlDescription &pcd, const dsp::processor::ProcessorStorage &ps)
void rebuildControlsFromDescription ()
void attachRebuildToIntAttachment (int idx)
void attachRebuildToDeactivateAttachment (int idx)
void layoutControls ()
void layoutControlsEBWaveforms ()
void layoutControlsEQNBandParm ()
void layoutControlsEQMorph ()
void layoutControlsEQGraphic ()
void layoutControlsWithJsonEngine (const std::string &jsonpath)
template<typename T = sst::jucegui::components::Knob>
std::unique_ptr< theme::layout::Labeled< sst::jucegui::components::ContinuousParamEditor > > createWidgetAttachedTo (const std::unique_ptr< attachment_t > &at, const std::string &label)
template<typename T = sst::jucegui::components::Knob>
std::unique_ptr< T > createWidgetAttachedTo (const std::unique_ptr< int_attachment_t > &at)
template<typename T = sst::jucegui::components::ToggleButton>
std::unique_ptr< T > createWidgetAttachedTo (const std::unique_ptr< bool_attachment_t > &at)
template<typename T = sst::jucegui::components::Knob>
std::unique_ptr< theme::layout::Labeled< sst::jucegui::components::DiscreteParamEditor > > createWidgetAttachedTo (const std::unique_ptr< int_attachment_t > &at, const std::string &label)
template<typename T = sst::jucegui::components::Label>
std::unique_ptr< T > createLabel (const std::string &txt)
void createHamburgerStereo (int attachmentId)
void resetControls ()
void resized () override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
void showProcessorTypeMenu ()
void showPresetsMenu ()
bool isInterestedInDragSource (const SourceDetails &dragSourceDetails) override
void itemDropped (const SourceDetails &dragSourceDetails) override
void itemDragEnter (const SourceDetails &dragSourceDetails) override
void itemDragExit (const SourceDetails &dragSourceDetails) override
void reapplyStyle ()
void toggleBypass ()
void setupJsonTypeMap ()
std::string resolveJsonPath (const std::string &path) const override
void createBindAndPosition (const sst::jucegui::layouts::json_document::Control &, const sst::jucegui::layouts::json_document::Class &) override
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
dsp::processor::ProcessorStorage processorView
dsp::processor::ProcessorControlDescription processorControlDescription
int index {0}
bool forZone {true}
bool isDragging {false}
bool multiZone {false}
std::array< std::unique_ptr< floatEditor_t >, dsp::processor::maxProcessorFloatParams > floatEditors
std::array< std::unique_ptr< intEditor_t >, dsp::processor::maxProcessorFloatParams > floatDeactivateEditors
std::array< std::unique_ptr< attachment_t >, dsp::processor::maxProcessorFloatParams > floatAttachments
std::array< std::unique_ptr< intEditor_t >, dsp::processor::maxProcessorIntParams > intEditors
std::array< std::unique_ptr< int_attachment_t >, dsp::processor::maxProcessorFloatParams > intAttachments
std::array< std::unique_ptr< bool_attachment_t >, dsp::processor::maxProcessorFloatParams > deactivateAttachments
std::unique_ptr< bool_attachment_t > bypassAttachment
std::unique_ptr< bool_attachment_t > keytrackAttackment
std::unique_ptr< bool_attachment_t > temposyncAttachment
std::vector< std::unique_ptr< juce::Component > > otherEditors
std::unique_ptr< theme::layout::Labeled< sst::jucegui::components::ContinuousParamEditor > > mixEditor
std::unique_ptr< attachment_t > mixAttachment
std::unique_ptr< sst::jucegui::components::Label > multiLabel
std::unique_ptr< sst::jucegui::components::TextPushButton > multiButton
std::unordered_map< dsp::processor::ProcessorType, std::string > jsonDefinitions
std::string multiName
std::array< jsonFloatEditor_t, dsp::processor::maxProcessorFloatParams > jsonFloatEditors
std::array< jsonIntEditor_t, dsp::processor::maxProcessorIntParams > jsonIntEditors
std::array< jsonIntEditor_t, dsp::processor::maxProcessorFloatParams > jsonDeactEditors
std::vector< std::unique_ptr< juce::Component > > jsonLabels
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Member Typedef Documentation
attachment_t
typedef connectors::PayloadDataAttachment<dsp::processor::ProcessorStorage> attachment_t
int_attachment_t
typedef connectors::DiscretePayloadDataAttachment<dsp::processor::ProcessorStorage> int_attachment_t
bool_attachment_t
typedef connectors::BooleanPayloadDataAttachment<dsp::processor::ProcessorStorage> bool_attachment_t
floatEditor_t
using floatEditor_t = theme::layout::Labeled<sst::jucegui::components::ContinuousParamEditor>
intEditor_t
using intEditor_t = theme::layout::Labeled<sst::jucegui::components::DiscreteParamEditor>
jsonFloatEditor_t
using jsonFloatEditor_t = std::unique_ptr<sst::jucegui::components::ContinuousParamEditor>
jsonIntEditor_t
using jsonIntEditor_t = std::unique_ptr<sst::jucegui::components::DiscreteParamEditor>
Constructor & Destructor Documentation
ProcessorPane()
ProcessorPane (SCXTEditor * e, int index, bool fz)
References ProcessorPane::setupJsonTypeMap().
~ProcessorPane()
~ProcessorPane ()
References ProcessorPane::resetControls().
Member Function Documentation
setProcessorControlDescriptionAndStorage()
void setProcessorControlDescriptionAndStorage (const dsp::processor::ProcessorControlDescription & pcd, const dsp::processor::ProcessorStorage & ps)
References ProcessorPane::multiName, ProcessorPane::multiZone, ProcessorPane::processorControlDescription, ProcessorPane::processorView, ProcessorStorage::procTypeConsistent, ProcessorPane::rebuildControlsFromDescription(), ProcessorPane::resetControls(), ProcessorPane::resized(), and ProcessorControlDescription::typeDisplayName.
rebuildControlsFromDescription()
void rebuildControlsFromDescription ()
References scxt::ui::connectors::addGuiStep(), scxt::ui::connectors::configureUpdater(), scxt::datamodel::describeValue(), scxt::dsp::processor::proct_eq_3band_parametric_A, scxt::dsp::processor::proct_eq_6band, scxt::dsp::processor::proct_eq_morph, scxt::dsp::processor::proct_none, and scxt::dsp::processor::proct_osc_EBWaveforms.
Referenced by ProcessorPane::resized(), and ProcessorPane::setProcessorControlDescriptionAndStorage().
attachRebuildToIntAttachment()
void attachRebuildToIntAttachment (int idx)
References scxt::ui::connectors::addGuiStep().
attachRebuildToDeactivateAttachment()
void attachRebuildToDeactivateAttachment (int idx)
References scxt::ui::connectors::addGuiStep().
layoutControls()
void layoutControls ()
References Labeled< T >::item.
layoutControlsEBWaveforms()
void layoutControlsEBWaveforms ()
References main().
layoutControlsEQNBandParm()
void layoutControlsEQNBandParm ()
References scxt::ui::theme::layout::columns(), ProcessorPane::createWidgetAttachedTo(), ProcessorPane::floatAttachments, ProcessorPane::floatEditors, ProcessorPane::intAttachments, ProcessorPane::intEditors, and ProcessorPane::otherEditors.
layoutControlsEQMorph()
void layoutControlsEQMorph ()
References scxt::ui::theme::layout::columns(), ProcessorPane::createWidgetAttachedTo(), ProcessorPane::floatAttachments, ProcessorPane::floatEditors, ProcessorPane::intAttachments, ProcessorPane::intEditors, EqDisplaySupport< Proc, nSub >::mPrepareBand, and ProcessorPane::otherEditors.
layoutControlsEQGraphic()
void layoutControlsEQGraphic ()
References scxt::ui::theme::layout::columns(), ProcessorPane::createWidgetAttachedTo(), ProcessorPane::floatAttachments, ProcessorPane::floatEditors, ProcessorPane::otherEditors, and EqDisplaySupport< Proc, nSub >::rebuildCurves().
layoutControlsWithJsonEngine()
void layoutControlsWithJsonEngine (const std::string & jsonpath)
createWidgetAttachedTo() [1/4]
template<typename T = sst::jucegui::components::Knob> std::unique_ptr< theme::layout::Labeled< sst::jucegui::components::ContinuousParamEditor > > createWidgetAttachedTo (const std::unique_ptr< attachment_t > & at, const std::string & label)
References HasEditor::setupWidgetForValueTooltip().
Referenced by ProcessorPane::layoutControlsEQGraphic(), ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
createWidgetAttachedTo() [2/4]
template<typename T = sst::jucegui::components::Knob> std::unique_ptr< T > createWidgetAttachedTo (const std::unique_ptr< int_attachment_t > & at)
createWidgetAttachedTo() [3/4]
template<typename T = sst::jucegui::components::ToggleButton> std::unique_ptr< T > createWidgetAttachedTo (const std::unique_ptr< bool_attachment_t > & at)
createWidgetAttachedTo() [4/4]
template<typename T = sst::jucegui::components::Knob> std::unique_ptr< theme::layout::Labeled< sst::jucegui::components::DiscreteParamEditor > > createWidgetAttachedTo (const std::unique_ptr< int_attachment_t > & at, const std::string & label)
References Labeled< T >::item.
createLabel()
template<typename T = sst::jucegui::components::Label> std::unique_ptr< T > createLabel (const std::string & txt)
createHamburgerStereo()
void createHamburgerStereo (int attachmentId)
resetControls()
void resetControls ()
Referenced by ProcessorPane::setProcessorControlDescriptionAndStorage(), and ProcessorPane::~ProcessorPane().
resized()
void resized () override
References ProcessorPane::rebuildControlsFromDescription().
Referenced by ProcessorPane::setProcessorControlDescriptionAndStorage().
mouseDrag()
void mouseDrag (const juce::MouseEvent & e) override
mouseUp()
void mouseUp (const juce::MouseEvent & e) override
showProcessorTypeMenu()
void showProcessorTypeMenu ()
References SCXTEditor::allProcessors, HasEditor::editor, and ProcessorPane::forZone.
showPresetsMenu()
void showPresetsMenu ()
isInterestedInDragSource()
bool isInterestedInDragSource (const SourceDetails & dragSourceDetails) override
itemDropped()
void itemDropped (const SourceDetails & dragSourceDetails) override
itemDragEnter()
void itemDragEnter (const SourceDetails & dragSourceDetails) override
itemDragExit()
void itemDragExit (const SourceDetails & dragSourceDetails) override
reapplyStyle()
void reapplyStyle ()
toggleBypass()
void toggleBypass ()
setupJsonTypeMap()
void setupJsonTypeMap ()
References scxt::dsp::processor::proct_Chorus, scxt::dsp::processor::proct_comb, scxt::dsp::processor::proct_cutoffwarp, scxt::dsp::processor::proct_CytomicSVF, scxt::dsp::processor::proct_diodeladder, scxt::dsp::processor::proct_eq_tilt, scxt::dsp::processor::proct_fmfilter, scxt::dsp::processor::proct_fx_bitcrusher, scxt::dsp::processor::proct_fx_freqshiftmod, scxt::dsp::processor::proct_fx_microgate, scxt::dsp::processor::proct_fx_ringmod, scxt::dsp::processor::proct_fx_simple_delay, scxt::dsp::processor::proct_fx_waveshaper, scxt::dsp::processor::proct_fx_widener, scxt::dsp::processor::proct_gainmatrix, scxt::dsp::processor::proct_K35, scxt::dsp::processor::proct_lifted_delay, scxt::dsp::processor::proct_noise_am, scxt::dsp::processor::proct_obx4, scxt::dsp::processor::proct_osc_3op, scxt::dsp::processor::proct_osc_correlatednoise, scxt::dsp::processor::proct_osc_phasemod, scxt::dsp::processor::proct_osc_sineplus, scxt::dsp::processor::proct_osc_tiltnoise, scxt::dsp::processor::proct_Phaser, scxt::dsp::processor::proct_reswarp, scxt::dsp::processor::proct_shepard, scxt::dsp::processor::proct_snhfilter, scxt::dsp::processor::proct_StaticPhaser, scxt::dsp::processor::proct_stereotool, scxt::dsp::processor::proct_stringResonator, scxt::dsp::processor::proct_Tremolo, scxt::dsp::processor::proct_tripole, scxt::dsp::processor::proct_utilfilt, scxt::dsp::processor::proct_VemberClassic, scxt::dsp::processor::proct_vintageladder, scxt::dsp::processor::proct_volpan, scxt::ui::connectors::jsonlayout::resolveJsonFile(), and SCLOG_IF.
Referenced by ProcessorPane::ProcessorPane().
resolveJsonPath()
std::string resolveJsonPath (const std::string & path) const override
References scxt::ui::connectors::jsonlayout::resolveJsonFile().
createBindAndPosition()
void createBindAndPosition (const sst::jucegui::layouts::json_document::Control & ctrl, const sst::jucegui::layouts::json_document::Class & cls) override
References scxt::ui::connectors::jsonlayout::attachAndPosition(), scxt::ui::connectors::jsonlayout::createAndPositionNonDataWidget(), scxt::ui::connectors::jsonlayout::createContinuousWidget(), scxt::ui::connectors::jsonlayout::createControlLabel(), scxt::ui::connectors::jsonlayout::createDiscreteWidget(), scxt::ui::connectors::jsonlayout::isEnabled(), scxt::ui::connectors::jsonlayout::isVisible(), and SCLOG_IF.
Member Data Documentation
processorView
dsp::processor::ProcessorStorage processorView
Referenced by EqDisplaySupport< Proc, nSub >::EqDisplaySupport(), and ProcessorPane::setProcessorControlDescriptionAndStorage().
processorControlDescription
dsp::processor::ProcessorControlDescription processorControlDescription
Referenced by ProcessorPane::setProcessorControlDescriptionAndStorage().
index
int index {0}
forZone
bool forZone {true}
Referenced by ProcessorPane::showProcessorTypeMenu().
isDragging
bool isDragging {false}
multiZone
bool multiZone {false}
Referenced by ProcessorPane::setProcessorControlDescriptionAndStorage().
floatEditors
std::array<std::unique_ptr<floatEditor_t>, dsp::processor::maxProcessorFloatParams> floatEditors
Referenced by ProcessorPane::layoutControlsEQGraphic(), ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
floatDeactivateEditors
std::array<std::unique_ptr<intEditor_t>, dsp::processor::maxProcessorFloatParams> floatDeactivateEditors
floatAttachments
std::array<std::unique_ptr<attachment_t>, dsp::processor::maxProcessorFloatParams> floatAttachments
Referenced by ProcessorPane::layoutControlsEQGraphic(), ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
intEditors
std::array<std::unique_ptr<intEditor_t>, dsp::processor::maxProcessorIntParams> intEditors
Referenced by ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
intAttachments
std::array<std::unique_ptr<int_attachment_t>, dsp::processor::maxProcessorFloatParams> intAttachments
Referenced by ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
deactivateAttachments
std::array<std::unique_ptr<bool_attachment_t>, dsp::processor::maxProcessorFloatParams> deactivateAttachments
bypassAttachment
std::unique_ptr<bool_attachment_t> bypassAttachment
keytrackAttackment
std::unique_ptr<bool_attachment_t> keytrackAttackment
temposyncAttachment
std::unique_ptr<bool_attachment_t> temposyncAttachment
otherEditors
std::vector<std::unique_ptr<juce::Component> > otherEditors
Referenced by ProcessorPane::layoutControlsEQGraphic(), ProcessorPane::layoutControlsEQMorph(), and ProcessorPane::layoutControlsEQNBandParm().
mixEditor
std::unique_ptr<theme::layout::Labeled<sst::jucegui::components::ContinuousParamEditor> > mixEditor
mixAttachment
std::unique_ptr<attachment_t> mixAttachment
multiLabel
std::unique_ptr<sst::jucegui::components::Label> multiLabel
multiButton
std::unique_ptr<sst::jucegui::components::TextPushButton> multiButton
jsonDefinitions
std::unordered_map<dsp::processor::ProcessorType, std::string> jsonDefinitions
multiName
std::string multiName
Referenced by ProcessorPane::setProcessorControlDescriptionAndStorage().
jsonFloatEditors
std::array<jsonFloatEditor_t, dsp::processor::maxProcessorFloatParams> jsonFloatEditors
jsonIntEditors
std::array<jsonIntEditor_t, dsp::processor::maxProcessorIntParams> jsonIntEditors
jsonDeactEditors
std::array<jsonIntEditor_t, dsp::processor::maxProcessorFloatParams> jsonDeactEditors
jsonLabels
std::vector<std::unique_ptr<juce::Component> > jsonLabels
The documentation for this struct was generated from the following files:
ProcessorPane.h
ProcessorPane.cpp
ProcessorPaneEQsFilters.cpp