shortcircuit-xt: ThemeApplier Struct Reference
ThemeApplier Struct Reference
Public Member Functions
ThemeApplier ()
void recolorStylesheet (const sst::jucegui::style::StyleSheet::ptr_t &)
void recolorStylesheetWith (std::unique_ptr< ColorMap > &&, const sst::jucegui::style::StyleSheet::ptr_t &)
void applyMultiScreenSidebarTheme (juce::Component *toThis)
void applyZoneMultiScreenTheme (juce::Component *toThis)
void applyZoneMultiScreenModulationTheme (juce::Component *toThis)
void applyGroupMultiScreenTheme (juce::Component *toThis)
void applyGroupMultiScreenModulationTheme (juce::Component *toThis)
void applyMixerEffectTheme (juce::Component *toThis)
void applyMixerChannelTheme (juce::Component *toThis)
void applyHeaderTheme (juce::Component *toThis)
void applyHeaderSCButtonTheme (sst::jucegui::style::StyleConsumer *)
void setLabelToHighlight (sst::jucegui::style::StyleConsumer *)
juce::Font interBoldFor (int ht) const
juce::Font interMediumFor (int ht) const
juce::Font interRegularFor (int ht) const
juce::Font interLightFor (int ht) const
Constructor & Destructor Documentation
ThemeApplier()
ThemeApplier ()
References SCLOG.
Member Function Documentation
recolorStylesheet()
void recolorStylesheet (const sst::jucegui::style::StyleSheet::ptr_t & s)
Referenced by ThemeApplier::recolorStylesheetWith().
recolorStylesheetWith()
void recolorStylesheetWith (std::unique_ptr< ColorMap > && , const sst::jucegui::style::StyleSheet::ptr_t &)
References ThemeApplier::recolorStylesheet().
Referenced by SCXTEditor::SCXTEditor().
applyMultiScreenSidebarTheme()
void applyMultiScreenSidebarTheme (juce::Component * toThis)
applyZoneMultiScreenTheme()
void applyZoneMultiScreenTheme (juce::Component * toThis)
Referenced by MultiScreen::ZoneOrGroupElements< ZGTrait >::ZoneOrGroupElements().
applyZoneMultiScreenModulationTheme()
void applyZoneMultiScreenModulationTheme (juce::Component * toThis)
Referenced by LfoPane::rebuildPanelComponents().
applyGroupMultiScreenTheme()
void applyGroupMultiScreenTheme (juce::Component * toThis)
applyGroupMultiScreenModulationTheme()
void applyGroupMultiScreenModulationTheme (juce::Component * toThis)
Referenced by LfoPane::rebuildPanelComponents().
applyMixerEffectTheme()
void applyMixerEffectTheme (juce::Component * toThis)
applyMixerChannelTheme()
void applyMixerChannelTheme (juce::Component * toThis)
applyHeaderTheme()
void applyHeaderTheme (juce::Component * toThis)
Referenced by HeaderRegion::HeaderRegion().
applyHeaderSCButtonTheme()
void applyHeaderSCButtonTheme (sst::jucegui::style::StyleConsumer * s)
Referenced by HeaderRegion::HeaderRegion().
setLabelToHighlight()
void setLabelToHighlight (sst::jucegui::style::StyleConsumer * s)
Referenced by HeaderRegion::HeaderRegion().
interBoldFor()
juce::Font interBoldFor (int ht) const
References scxt::ui::connectors::resources::loadTypeface().
Referenced by WelcomeScreen::paint().
interMediumFor()
juce::Font interMediumFor (int ht) const
References scxt::ui::connectors::resources::loadTypeface().
interRegularFor()
juce::Font interRegularFor (int ht) const
References scxt::ui::connectors::resources::loadTypeface().
Referenced by Keyboard::paint(), and MappingZones::paint().
interLightFor()
juce::Font interLightFor (int ht) const
References scxt::ui::connectors::resources::loadTypeface().
Referenced by WelcomeScreen::paint().
The documentation for this struct was generated from the following files:
ThemeApplier.h
ThemeApplier.cpp