shortcircuit-xt: SCXTEditor Struct Reference
SCXTEditor Struct Reference
#include <SCXTEditor.h>
Inherits WindowPanel, DragAndDropContainer, and ScreenHolder< SCXTEditor >.
Classes
struct IdleTimer
struct UISideClipboard
Public Types
enum ActiveScreen { PLAY , MULTI , MIXER }
Public Member Functions
juce::Colour themeColor (scxt::ui::theme::ColorMap::Colors, float alpha=1.f) const
void resetColorsFromUserPreferences ()
void onStyleChanged () override
void showMissingResolutionScreen ()
SCXTEditor (messaging::MessageController &e, infrastructure::DefaultsProvider &d, const sample::SampleManager &s, const scxt::browser::Browser &b, const engine::Engine::SharedUIMemoryState &state)
virtual ~SCXTEditor () noexcept
void setActiveScreen (ActiveScreen s)
void showAboutOverlay ()
void showLogOverlay ()
void showWelcomeOverlay ()
void setZoomFactor (float zoomFactor)
void resized () override
void parentHierarchyChanged () override
void idle ()
void drainCallbackQueue ()
juce::PopupMenu::Options defaultPopupMenuOptions (juce::Component *on=nullptr)
void configureHasDiscreteMenuBuilder (sst::jucegui::components::HasDiscreteParamMenuBuilder *)
void popupMenuForContinuous (sst::jucegui::components::ContinuousParamEditor *e)
bool supressPopupMenuForContinuous (sst::jucegui::components::ContinuousParamEditor *e) const
void onErrorFromEngine (const scxt::messaging::client::s2cError_t &)
void onEngineStatus (const engine::Engine::EngineStatusMessage &e)
void onMappingUpdated (const scxt::messaging::client::mappingSelectedZoneViewResposne_t &)
void onSamplesUpdated (const scxt::messaging::client::sampleSelectedZoneViewResposne_t &)
void onStructureUpdated (const engine::Engine::pgzStructure_t &)
void onGroupOrZoneEnvelopeUpdated (const scxt::messaging::client::adsrViewResponsePayload_t &payload)
void onGroupOrZoneProcessorDataAndMetadata (const scxt::messaging::client::processorDataResponsePayload_t &d)
void onZoneVoiceMatrixMetadata (const scxt::voice::modulation::voiceMatrixMetadata_t &)
void onZoneVoiceMatrix (const scxt::voice::modulation::Matrix::RoutingTable &)
void onGroupMatrixMetadata (const scxt::modulation::groupMatrixMetadata_t &)
void onGroupMatrix (const scxt::modulation::GroupMatrix::RoutingTable &)
void onGroupTriggerConditions (const scxt::engine::GroupTriggerConditions &)
void onGroupOrZoneModulatorStorageUpdated (const scxt::messaging::client::indexedModulatorStorageUpdate_t &)
void onGroupOrZoneMiscModStorageUpdated (const scxt::messaging::client::gzMiscStorageUpdate_t &)
void onZoneOutputInfoUpdated (const scxt::messaging::client::zoneOutputInfoUpdate_t &p)
void onGroupOutputInfoUpdated (const scxt::messaging::client::groupOutputInfoUpdate_t &p)
void onGroupZoneMappingSummary (const scxt::engine::Part::zoneMappingSummary_t &)
void onSelectionState (const scxt::messaging::client::selectedStateMessage_t &)
void onSelectedPart (const int16_t)
int16_t getSelectedPart () const
void onPartConfiguration (const scxt::messaging::client::partConfigurationPayload_t &)
void onOtherTabSelection (const scxt::selection::SelectionManager::otherTabSelection_t &p)
std::string queryTabSelection (const std::string &k)
void setTabSelection (const std::string &k, const std::string &t)
void onBusOrPartEffectFullData (const scxt::messaging::client::busEffectFullData_t &)
void onBusOrPartSendData (const scxt::messaging::client::busSendData_t &)
void onBrowserRefresh (const bool)
void onBrowserQueueLengthRefresh (const std::pair< int32_t, int32_t >)
void onDebugInfoGenerated (const scxt::messaging::client::debugResponse_t &)
void onAllProcessorDescriptions (const std::vector< dsp::processor::ProcessorDescription > &v)
void onActivityNotification (const scxt::messaging::client::activityNotificationPayload_t &)
void onTuningStatus (const scxt::messaging::client::tuningStatusPayload_t &)
void onMacroFullState (const scxt::messaging::client::macroFullState_t &)
void onMacroValue (const scxt::messaging::client::macroValue_t &)
void onMissingResolutionWorkItemList (const std::vector< engine::MissingResolutionWorkItem > &)
void onClipboardType (const scxt::engine::Clipboard::ContentType &s)
void doSelectionAction (const selection::SelectionManager::ZoneAddress &, bool selecting, bool distinct, bool asLead)
void doSelectionAction (const selection::SelectionManager::SelectActionContents &)
void doSelectionAction (const std::vector< selection::SelectionManager::SelectActionContents > &)
bool isAnyZoneFromGroupSelected (int groupIdx)
bool isSelected (const selection::SelectionManager::ZoneAddress &a)
void showTooltip (const juce::Component &relativeTo)
void showTooltip (const juce::Component &relativeTo, const juce::Point< int > &internalPosition)
void repositionTooltip (const juce::Component &relativeTo, const juce::Point< int > &internalPosition)
void hideTooltip ()
void setTooltipContents (const std::string &title, const std::vector< sst::jucegui::components::ToolTip::Row > &rows)
void setTooltipContents (const std::string &title, const std::vector< std::string > &display)
void setTooltipContents (const std::string &title, const std::string &display)
void showMainMenu ()
void addTuningMenu (juce::PopupMenu &into, bool addTitle=true)
void addZoomMenu (juce::PopupMenu &into, bool addTitle=true)
void addUIThemesMenu (juce::PopupMenu &p, bool addTitle=true)
void processorBypassToggled (int which)
std::function< void()> makeComingSoon (const std::string &feature="This feature")
void promptOKCancel (const std::string &title, const std::string &message, std::function< void()> onOK, std::function< void()> onCancel=[]() {})
void displayError (const std::string &title, const std::string &message)
bool keyPressed (const juce::KeyPress &key) override
void switchGroupOrZoneFocus ()
Public Attributes
messaging::MessageController & msgCont
const sample::SampleManager & sampleManager
infrastructure::DefaultsProvider & defaultsProvider
const scxt::browser::Browser & browser
const engine::Engine::SharedUIMemoryState & sharedUiMemoryState
theme::ThemeApplier themeApplier
SCXTEditorDataCache editorDataCache
sst::basic_blocks::dsp::RNG rng
std::unique_ptr< sst::jucegui::style::LookAndFeelManager > lnf
std::unique_ptr< IdleTimer > idleTimer
std::unique_ptr< shared::HeaderRegion > headerRegion
std::unique_ptr< edit_screen::EditScreen > editScreen
std::unique_ptr< mixer_screen::MixerScreen > mixerScreen
std::unique_ptr< play_screen::PlayScreen > playScreen
std::unique_ptr< other_screens::AboutScreen > aboutScreen
std::unique_ptr< other_screens::WelcomeScreen > welcomeScreen
std::unique_ptr< other_screens::LogScreen > logScreen
std::unique_ptr< missing_resolution::MissingResolutionScreen > missingResolutionScreen
bool hasMissingSamples {false}
std::unique_ptr< sst::jucegui::components::ToolTip > toolTip
std::unique_ptr< sst::jucegui::accessibility::FocusDebugger > focusDebugger
enum scxt::ui::app::SCXTEditor::ActiveScreen MULTI
int32_t checkWelcomeCountdown {20}
float zoomFactor {1.f}
std::function< void(float)> onZoomChanged {nullptr}
uint64_t inboundMessageCount {0}
uint64_t inboundMessageBytes {0}
std::array< scxt::engine::Part::PartConfiguration, scxt::numParts > partConfigurations
selection::SelectionManager::otherTabSelection_t otherTabSelection
std::vector< dsp::processor::ProcessorDescription > allProcessors
scxt::messaging::client::tuningStatusPayload_t tuningStatus
std::array< std::array< scxt::engine::Macro, scxt::macrosPerPart >, scxt::numParts > macroCache
scxt::engine::Clipboard::ContentType clipboardType {scxt::engine::Clipboard::ContentType::NONE}
struct scxt::ui::app::SCXTEditor::UISideClipboard clipboard
std::optional< selection::SelectionManager::ZoneAddress > currentLeadZoneSelection
std::optional< selection::SelectionManager::ZoneAddress > currentLeadGroupSelection
selection::SelectionManager::selectedZones_t allZoneSelections
selection::SelectionManager::selectedZones_t allGroupSelections
int16_t selectedPart {0}
std::set< int > groupsWithSelectedZones
std::mutex callbackMutex
std::queue< std::string > callbackQueue
engine::Engine::EngineStatusMessage engineStatus
int64_t lastVoiceDisplayWriteCounter {-1}
float lastProcessMemoryInMegabytes {0}
std::unique_ptr< KeyBindings > keyBindings
std::unique_ptr< juce::FileChooser > fileChooser
const clap_host_t * clapHost {nullptr}
Static Public Attributes
static constexpr int edWidth {1286}
static constexpr int edHeight {816}
Protected Member Functions
template<typename T >
void sendToSerialization (const T &msg)
template<typename A >
void beginEditNotifyEngine (const A &a)
template<typename A >
void endEditNotifyEngine (const A &a)
Member Enumeration Documentation
ActiveScreen
enum ActiveScreen
Enumerator
PLAY
MULTI
MIXER
Constructor & Destructor Documentation
SCXTEditor()
SCXTEditor (messaging::MessageController & e, infrastructure::DefaultsProvider & d, const sample::SampleManager & s, const scxt::browser::Browser & b, const engine::Engine::SharedUIMemoryState & state)
References SCXTEditor::aboutScreen, ThreadingChecker::addAsAClientThread(), SCXTEditor::callbackMutex, SCXTEditor::callbackQueue, SCXTEditor::defaultsProvider, SCXTEditor::editScreen, SCXTEditor::focusDebugger, SCXTEditor::headerRegion, SCXTEditor::idleTimer, SCXTEditor::keyBindings, SCXTEditor::lnf, SCXTEditor::logScreen, SCXTEditor::missingResolutionScreen, SCXTEditor::mixerScreen, SCXTEditor::msgCont, scxt::infrastructure::octave0, SCXTEditor::playScreen, MessageController::registerClient(), SCXTEditor::resetColorsFromUserPreferences(), SCXTEditor::setZoomFactor(), MessageController::threadingChecker, SCXTEditor::toolTip, SCXTEditor::welcomeScreen, and scxt::infrastructure::zoomLevel.
~SCXTEditor()
~SCXTEditor () virtual noexcept
References SCXTEditor::idleTimer, SCXTEditor::msgCont, and MessageController::unregisterClient().
Member Function Documentation
themeColor()
juce::Colour themeColor (scxt::ui::theme::ColorMap::Colors c, float alpha = 1.f) const
References SCXTEditor::themeApplier.
Referenced by StepLFOPane::StepRender::StepMenuTypein::getValueColour(), ModRow< GZTrait >::ModDepthTypein::getValueColour(), ZoneLayoutDisplay::labelZoneRectangle(), ViewportComponent::paint(), ActivityDisplay::paint(), GroupSettingsCard::paint(), GroupTriggersCard::paint(), StepLFOPane::StepRender::paint(), SampleWaveform::paint(), NoSelection::paint(), VariantDisplay::FileInfos::paint(), ZoneLayoutDisplay::paint(), ZoneLayoutKeyboard::paint(), PartSettingsDisplay::paint(), RoutingPaneContents< RPTraits >::RoutingBox::paint(), WorkItemLineItem::paint(), DraggableMenuButton::paint(), AboutLink::paint(), AboutScreen::paint(), WelcomeScreen::paint(), PartSidebarCard::paint(), NarrowVerticalMenu::paint(), VariantDisplay::rebuildForSelectedVariation(), RoutingPaneContents< RPTraits >::SvgPaths::setSvg(), and MenuValueTypeinBase::setupTextEditorStyle().
resetColorsFromUserPreferences()
void resetColorsFromUserPreferences ()
References scxt::infrastructure::colormapId, scxt::infrastructure::colormapPathIfFile, ColorMap::createColorMap(), SCXTEditor::defaultsProvider, ColorMap::FILE_COLORMAP_ID, ColorMap::jsonToColormap(), ThemeApplier::recolorStylesheetWith(), SCLOG_IF, scxt::infrastructure::showKnobs, SCXTEditor::themeApplier, and ColorMap::WIREFRAME.
Referenced by SCXTEditor::SCXTEditor().
onStyleChanged()
void onStyleChanged () override
References SCXTEditor::lnf.
showMissingResolutionScreen()
void showMissingResolutionScreen ()
References SCXTEditor::missingResolutionScreen.
setActiveScreen()
void setActiveScreen (ActiveScreen s)
References SCXTEditor::aboutScreen, SCXTEditor::editScreen, SCXTEditor::logScreen, SCXTEditor::MIXER, SCXTEditor::mixerScreen, SCXTEditor::MULTI, SCXTEditor::PLAY, SCXTEditor::playScreen, SCXTEditor::resized(), and SCXTEditor::setTabSelection().
Referenced by SCXTEditor::keyPressed(), SCXTEditor::onOtherTabSelection(), spData::setValueFromGUI(), and SCXTEditor::switchGroupOrZoneFocus().
showAboutOverlay()
void showAboutOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
showLogOverlay()
void showLogOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
showWelcomeOverlay()
void showWelcomeOverlay ()
References SCXTEditor::aboutScreen, SCXTEditor::logScreen, SCXTEditor::resized(), and SCXTEditor::welcomeScreen.
Referenced by SCXTEditor::idle().
setZoomFactor()
void setZoomFactor (float zoomFactor)
References SCXTEditor::defaultsProvider, SCXTEditor::onZoomChanged, SCXTEditor::zoomFactor, and scxt::infrastructure::zoomLevel.
Referenced by SCXTEditor::parentHierarchyChanged(), and SCXTEditor::SCXTEditor().
resized()
void resized () override
References SCXTEditor::aboutScreen, SCXTEditor::edHeight, SCXTEditor::editScreen, SCXTEditor::edWidth, SCXTEditor::headerRegion, SCXTEditor::logScreen, SCXTEditor::mixerScreen, SCXTEditor::playScreen, and SCXTEditor::welcomeScreen.
Referenced by SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
parentHierarchyChanged()
void parentHierarchyChanged () override
References SCXTEditor::defaultsProvider, SCLOG_IF, SCXTEditor::setZoomFactor(), scxt::infrastructure::useSoftwareRenderer, and SCXTEditor::zoomFactor.
idle()
void idle ()
References Engine::SharedUIMemoryState::busVULevels, SCXTEditor::checkWelcomeCountdown, Engine::SharedUIMemoryState::cpuLevel, SCXTEditor::currentLeadZoneSelection, SCXTEditor::defaultsProvider, SCXTEditor::editScreen, SCXTEditor::headerRegion, SCXTEditor::lastVoiceDisplayWriteCounter, SCXTEditor::mixerScreen, SCXTEditor::sampleManager, SampleManager::sampleMemoryInBytes, SCXTEditor::sharedUiMemoryState, SCXTEditor::showWelcomeOverlay(), Engine::SharedUIMemoryState::voiceCount, Engine::SharedUIMemoryState::voiceDisplayItems, Engine::SharedUIMemoryState::voiceDisplayStateWriteCounter, scxt::infrastructure::welcomeScreenSeen, and WelcomeScreen::welcomeVersion.
Referenced by SCXTEditor::IdleTimer::timerCallback().
drainCallbackQueue()
void drainCallbackQueue ()
References SCXTEditor::callbackMutex, SCXTEditor::callbackQueue, scxt::messaging::client::clientThreadExecuteSerializationMessage(), SCXTEditor::inboundMessageBytes, SCXTEditor::inboundMessageCount, ThreadingChecker::isClientThread(), SCXTEditor::msgCont, SCLOG_IF, and MessageController::threadingChecker.
defaultPopupMenuOptions()
juce::PopupMenu::Options defaultPopupMenuOptions (juce::Component * on = nullptr)
Referenced by RoutingPaneContents< RPTraits >::selectNewRouting(), ChannelStrip::showAuxRouting(), ModRow< GZTrait >::showCurveMenu(), ModRow< GZTrait >::showDepthPopup(), MiscPanel::showDivisionMenu(), VariantDisplay::showHamburgerMenu(), VariantDisplay::showLoopModeMenu(), SCXTEditor::showMainMenu(), ZoneLayoutDisplay::showMappingNonZoneMenu(), PlayScreen::showMenu(), PartSidebarCard::showMidiModeMenu(), LfoPane::showModulatorShapeMenu(), PartSidebarCard::showPartIOMenu(), GroupZoneSidebarBase< T, forZone >::showPartSelectorMenu(), VariantDisplay::showPlayModeMenu(), ChannelStrip::showPluginOutput(), PartSidebarCard::showPolyMenu(), DriveArea::DriveAreaRow::showPopup(), MiscPanel::showQuantValueMenu(), MiscPanel::showRandomModeMenu(), PartSidebarCard::showRoutingMenu(), ModRow< GZTrait >::showSourceMenu(), VariantDisplay::showSRCMenu(), MiscPanel::showSyncMenu(), ModRow< GZTrait >::showTargetMenu(), StepLFOPane::StepRender::showTypeinPopup(), GroupTriggersCard::ConditionRow::showTypeMenu(), VariantDisplay::showVariantPlaymodeMenu(), VariantDisplay::showVariantTabMenu(), and ZoneLayoutDisplay::showZoneMenu().
configureHasDiscreteMenuBuilder()
void configureHasDiscreteMenuBuilder (sst::jucegui::components::HasDiscreteParamMenuBuilder * wss)
popupMenuForContinuous()
void popupMenuForContinuous (sst::jucegui::components::ContinuousParamEditor * e)
References SCLOG_IF.
Referenced by HasEditor::setupIntAttachedWidgetForValueMenu(), HasEditor::setupWidgetForValueTooltip(), and SingleMacroEditor::SingleMacroEditor().
supressPopupMenuForContinuous()
bool supressPopupMenuForContinuous (sst::jucegui::components::ContinuousParamEditor * e) const
onErrorFromEngine()
void onErrorFromEngine (const scxt::messaging::client::s2cError_t & e)
References SCXTEditor::displayError().
onEngineStatus()
void onEngineStatus (const engine::Engine::EngineStatusMessage & e)
References SCXTEditor::aboutScreen, and SCXTEditor::engineStatus.
onMappingUpdated()
void onMappingUpdated (const scxt::messaging::client::mappingSelectedZoneViewResposne_t & payload)
References SCXTEditor::editScreen.
onSamplesUpdated()
void onSamplesUpdated (const scxt::messaging::client::sampleSelectedZoneViewResposne_t & payload)
References SCXTEditor::editScreen.
onStructureUpdated()
void onStructureUpdated (const engine::Engine::pgzStructure_t & s)
References SCXTEditor::editScreen.
onGroupOrZoneEnvelopeUpdated()
void onGroupOrZoneEnvelopeUpdated (const scxt::messaging::client::adsrViewResponsePayload_t & payload)
References SCXTEditor::editScreen.
onGroupOrZoneProcessorDataAndMetadata()
void onGroupOrZoneProcessorDataAndMetadata (const scxt::messaging::client::processorDataResponsePayload_t & d)
References SCXTEditor::editScreen, and EditScreen::numProcessorDisplays.
onZoneVoiceMatrixMetadata()
void onZoneVoiceMatrixMetadata (const scxt::voice::modulation::voiceMatrixMetadata_t & d)
References SCXTEditor::editScreen.
onZoneVoiceMatrix()
void onZoneVoiceMatrix (const scxt::voice::modulation::Matrix::RoutingTable & rt)
References SCXTEditor::editScreen.
onGroupMatrixMetadata()
void onGroupMatrixMetadata (const scxt::modulation::groupMatrixMetadata_t & d)
References SCXTEditor::editScreen.
onGroupMatrix()
void onGroupMatrix (const scxt::modulation::GroupMatrix::RoutingTable & t)
References SCXTEditor::editScreen.
onGroupTriggerConditions()
void onGroupTriggerConditions (const scxt::engine::GroupTriggerConditions & g)
References SCXTEditor::editScreen.
onGroupOrZoneModulatorStorageUpdated()
void onGroupOrZoneModulatorStorageUpdated (const scxt::messaging::client::indexedModulatorStorageUpdate_t & payload)
References SCXTEditor::editScreen.
onGroupOrZoneMiscModStorageUpdated()
void onGroupOrZoneMiscModStorageUpdated (const scxt::messaging::client::gzMiscStorageUpdate_t & payload)
References SCXTEditor::editScreen.
onZoneOutputInfoUpdated()
void onZoneOutputInfoUpdated (const scxt::messaging::client::zoneOutputInfoUpdate_t & p)
References SCXTEditor::editorDataCache, SCXTEditor::editScreen, SCXTEditorDataCache::fireAllNotificationsFor(), and SCXTEditorDataCache::zoneOutputInfo.
onGroupOutputInfoUpdated()
void onGroupOutputInfoUpdated (const scxt::messaging::client::groupOutputInfoUpdate_t & p)
References SCXTEditor::editorDataCache, SCXTEditor::editScreen, SCXTEditorDataCache::fireAllNotificationsFor(), and SCXTEditorDataCache::groupOutputInfo.
onGroupZoneMappingSummary()
void onGroupZoneMappingSummary (const scxt::engine::Part::zoneMappingSummary_t & d)
References SCXTEditor::editScreen, and SCLOG_IF.
onSelectionState()
void onSelectionState (const scxt::messaging::client::selectedStateMessage_t & a)
References SCXTEditor::allGroupSelections, SCXTEditor::allZoneSelections, SCXTEditor::currentLeadGroupSelection, SCXTEditor::currentLeadZoneSelection, SCXTEditor::editScreen, SCXTEditor::groupsWithSelectedZones, and SCLOG_IF.
onSelectedPart()
void onSelectedPart (const int16_t p)
References SCXTEditor::editScreen, and SCXTEditor::selectedPart.
getSelectedPart()
int16_t getSelectedPart () const
References SCXTEditor::selectedPart.
Referenced by PartSidebarCard::paint().
onPartConfiguration()
void onPartConfiguration (const scxt::messaging::client::partConfigurationPayload_t & payload)
References SCXTEditor::editScreen, SCXTEditor::partConfigurations, and SCXTEditor::playScreen.
onOtherTabSelection()
void onOtherTabSelection (const scxt::selection::SelectionManager::otherTabSelection_t & p)
References SCXTEditor::editScreen, SCXTEditor::MIXER, SCXTEditor::mixerScreen, SCXTEditor::MULTI, SCXTEditor::otherTabSelection, SCXTEditor::PLAY, SCXTEditor::queryTabSelection(), SCLOG_IF, and SCXTEditor::setActiveScreen().
queryTabSelection()
std::string queryTabSelection (const std::string & k)
References SCXTEditor::otherTabSelection.
Referenced by EditScreen::onOtherTabSelection(), MixerScreen::onOtherTabSelection(), and SCXTEditor::onOtherTabSelection().
setTabSelection()
void setTabSelection (const std::string & k, const std::string & t)
References SCXTEditor::otherTabSelection, and SCXTEditor::sendToSerialization().
Referenced by PartEditScreen::PartEditScreen(), MixerScreen::selectBus(), BrowserPane::selectPane(), SCXTEditor::setActiveScreen(), MacroMappingVariantPane::setSelectedTab(), PartGroupSidebar::setSelectedTab(), LfoPane::tabChanged(), and AdsrPane::tabChanged().
onBusOrPartEffectFullData()
void onBusOrPartEffectFullData (const scxt::messaging::client::busEffectFullData_t & d)
References SCXTEditor::editScreen, and SCXTEditor::mixerScreen.
onBusOrPartSendData()
void onBusOrPartSendData (const scxt::messaging::client::busSendData_t & d)
References SCXTEditor::mixerScreen.
onBrowserRefresh()
void onBrowserRefresh (const bool)
References SCXTEditor::editScreen, SCXTEditor::mixerScreen, and SCXTEditor::playScreen.
onBrowserQueueLengthRefresh()
void onBrowserQueueLengthRefresh (const std::pair< int32_t, int32_t > v)
References SCXTEditor::editScreen, SCXTEditor::mixerScreen, and SCXTEditor::playScreen.
onDebugInfoGenerated()
void onDebugInfoGenerated (const scxt::messaging::client::debugResponse_t & resp)
References SCLOG_IF.
onAllProcessorDescriptions()
void onAllProcessorDescriptions (const std::vector< dsp::processor::ProcessorDescription > & v)
References SCXTEditor::allProcessors.
onActivityNotification()
void onActivityNotification (const scxt::messaging::client::activityNotificationPayload_t & payload)
References SCXTEditor::headerRegion.
onTuningStatus()
void onTuningStatus (const scxt::messaging::client::tuningStatusPayload_t & t)
References SCXTEditor::tuningStatus.
onMacroFullState()
void onMacroFullState (const scxt::messaging::client::macroFullState_t & s)
References SCXTEditor::editScreen, SCXTEditor::macroCache, SCXTEditor::playScreen, and SCXTEditor::selectedPart.
onMacroValue()
void onMacroValue (const scxt::messaging::client::macroValue_t & s)
References SCXTEditor::editScreen, SCXTEditor::macroCache, and SCXTEditor::playScreen.
onMissingResolutionWorkItemList()
void onMissingResolutionWorkItemList (const std::vector< engine::MissingResolutionWorkItem > & items)
References SCXTEditor::hasMissingSamples, SCXTEditor::missingResolutionScreen, and SCLOG_IF.
onClipboardType()
void onClipboardType (const scxt::engine::Clipboard::ContentType & s)
References SCXTEditor::clipboardType.
doSelectionAction() [1/3]
void doSelectionAction (const selection::SelectionManager::ZoneAddress & a, bool selecting, bool distinct, bool asLead)
References SCXTEditor::doSelectionAction(), SelectionManager::ZoneAddress::group, SelectionManager::ZoneAddress::part, and SelectionManager::ZoneAddress::zone.
Referenced by SCXTEditor::doSelectionAction(), ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseUp(), GroupSidebar::onRowClicked(), and ZoneSidebar::onRowClicked().
doSelectionAction() [2/3]
void doSelectionAction (const selection::SelectionManager::SelectActionContents & p)
References SCXTEditor::sendToSerialization().
doSelectionAction() [3/3]
void doSelectionAction (const std::vector< selection::SelectionManager::SelectActionContents > & p)
References SCXTEditor::sendToSerialization().
isAnyZoneFromGroupSelected()
bool isAnyZoneFromGroupSelected (int groupIdx)
References SCXTEditor::currentLeadZoneSelection, and SCXTEditor::groupsWithSelectedZones.
Referenced by ZoneLayoutDisplay::createEmptyZoneAt(), ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseUp(), and ZoneLayoutDisplay::paint().
isSelected()
bool isSelected (const selection::SelectionManager::ZoneAddress & a)
References SCXTEditor::allZoneSelections, and SCXTEditor::currentLeadZoneSelection.
Referenced by ZoneLayoutDisplay::mouseDown(), and ZoneLayoutDisplay::paint().
showTooltip() [1/2]
void showTooltip (const juce::Component & relativeTo)
References SCXTEditor::toolTip.
Referenced by HasEditor::setupWidgetForValueTooltip(), and PartSidebarCard::showPartBlurbTooltip().
showTooltip() [2/2]
void showTooltip (const juce::Component & relativeTo, const juce::Point< int > & internalPosition)
References SCXTEditor::toolTip.
repositionTooltip()
void repositionTooltip (const juce::Component & relativeTo, const juce::Point< int > & internalPosition)
References SCXTEditor::toolTip.
Referenced by ZoneLayoutDisplay::updateTooltipContents().
hideTooltip()
void hideTooltip ()
References SCXTEditor::toolTip.
Referenced by PartSidebarCard::hidePartBlurbTooltip(), ZoneLayoutDisplay::mouseUp(), HasEditor::setupWidgetForValueTooltip(), and SingleMacroEditor::SingleMacroEditor().
setTooltipContents() [1/3]
void setTooltipContents (const std::string & title, const std::vector< sst::jucegui::components::ToolTip::Row > & rows)
References SCXTEditor::toolTip.
Referenced by SCXTEditor::setTooltipContents(), MacroValueAttachment::setValueFromGUI(), PartSidebarCard::showPartBlurbTooltip(), ModRow< GZTrait >::updateTooltip(), ZoneLayoutDisplay::updateTooltipContents(), and HasEditor::updateValueTooltip().
setTooltipContents() [2/3]
void setTooltipContents (const std::string & title, const std::vector< std::string > & display)
References SCXTEditor::toolTip.
setTooltipContents() [3/3]
void setTooltipContents (const std::string & title, const std::string & display)
References SCXTEditor::setTooltipContents().
showMainMenu()
void showMainMenu ()
References SCXTEditor::addTuningMenu(), SCXTEditor::addUIThemesMenu(), SCXTEditor::addZoomMenu(), SCXTEditor::defaultPopupMenuOptions(), SCXTEditor::headerRegion, SCLOG_IF, and SCXTEditor::themeApplier.
addTuningMenu()
void addTuningMenu (juce::PopupMenu & into, bool addTitle = true)
References SCXTEditor::editScreen, and Engine::TWELVE_TET.
Referenced by SCXTEditor::showMainMenu().
addZoomMenu()
void addZoomMenu (juce::PopupMenu & into, bool addTitle = true)
References scxt::infrastructure::invertScroll.
Referenced by SCXTEditor::showMainMenu().
addUIThemesMenu()
void addUIThemesMenu (juce::PopupMenu & p, bool addTitle = true)
References scxt::infrastructure::colormapId, scxt::infrastructure::colormapPathIfFile, ColorMap::createColorMap(), ColorMap::FILE_COLORMAP_ID, ColorMap::HICONTRAST_DARK, ColorMap::jsonToColormap(), ColorMap::LIGHT, scxt::infrastructure::octave0, scxt::infrastructure::showKnobs, ColorMap::TEST, scxt::infrastructure::useSoftwareRenderer, and ColorMap::WIREFRAME.
Referenced by SCXTEditor::showMainMenu().
processorBypassToggled()
void processorBypassToggled (int which)
References SCXTEditor::editScreen.
makeComingSoon()
std::function< void()> makeComingSoon (const std::string & feature = "This feature")
Referenced by GroupTriggersCard::ConditionRow::ConditionRow(), MappingDisplay::doZoneRename(), GroupSettingsCard::GroupSettingsCard(), HeaderRegion::HeaderRegion(), MappingZoneHeader::MappingZoneHeader(), VariantDisplay::rebuildForSelectedVariation(), LfoPane::showModulatorShapeMenu(), VariantDisplay::showVariantTabMenu(), and VariantDisplay::VariantDisplay().
promptOKCancel()
void promptOKCancel (const std::string & title, const std::string & message, std::function< void()> onOK, std::function< void()> onCancel = []() {})
Referenced by PartSidebarCard::filesDropped().
displayError()
void displayError (const std::string & title, const std::string & message)
References SCLOG_IF.
Referenced by RoutingPaneContents< RPTraits >::createBindAndPosition(), VariantDisplay::MyTabbedComponent::itemDropped(), PresetReceiverAdapter< forBus >::onError(), PresetReceiverAdapter::onError(), SCXTEditor::onErrorFromEngine(), MappingDisplay::promptForMultiInstrument(), DriveFSArea::recalcContents(), RoutingPaneContents< RPTraits >::resolveJsonPath(), VariantDisplay::selectNextFile(), ModRow< GZTrait >::ModDepthTypein::setValueString(), LfoPane::streamToJSON(), LfoPane::unstreamFromJSON(), and RoutingPaneContents< RPTraits >::updateFromProcessorPanes().
keyPressed()
bool keyPressed (const juce::KeyPress & key) override
References SCXTEditor::editScreen, scxt::ui::app::FOCUS_GROUPS, scxt::ui::app::FOCUS_MIXER, scxt::ui::app::FOCUS_PARTS, scxt::ui::app::FOCUS_PLAY, scxt::ui::app::FOCUS_ZONES, SCXTEditor::keyBindings, SCXTEditor::MIXER, SCXTEditor::MULTI, scxt::ui::app::numKeyCommands, SCXTEditor::PLAY, SCXTEditor::setActiveScreen(), scxt::ui::app::SWITCH_GROUP_ZONE_SELECTION, and SCXTEditor::switchGroupOrZoneFocus().
switchGroupOrZoneFocus()
void switchGroupOrZoneFocus ()
References SCXTEditor::editScreen, SCXTEditor::MULTI, and SCXTEditor::setActiveScreen().
Referenced by SCXTEditor::keyPressed().
sendToSerialization()
template<typename T > void sendToSerialization (const T & msg) protected
References scxt::messaging::client::clientSendToSerialization(), and SCXTEditor::msgCont.
Referenced by SCXTEditor::beginEditNotifyEngine(), SCXTEditor::doSelectionAction(), SCXTEditor::doSelectionAction(), SCXTEditor::endEditNotifyEngine(), HasEditor::sendToSerialization(), and SCXTEditor::setTabSelection().
beginEditNotifyEngine()
template<typename A > void beginEditNotifyEngine (const A & a) protected
References SCXTEditor::sendToSerialization().
Referenced by HasEditor::setupWidgetForValueTooltip().
endEditNotifyEngine()
template<typename A > void endEditNotifyEngine (const A & a) protected
References SCXTEditor::sendToSerialization().
Referenced by HasEditor::setupWidgetForValueTooltip().
Member Data Documentation
msgCont
messaging::MessageController& msgCont
Referenced by GroupZoneSidebarBase< T, forZone >::addGroup(), SCXTEditor::drainCallbackQueue(), SCXTEditor::SCXTEditor(), SCXTEditor::sendToSerialization(), and SCXTEditor::~SCXTEditor().
sampleManager
const sample::SampleManager& sampleManager
Referenced by SCXTEditor::idle(), SampleWaveform::paint(), VariantDisplay::rebuild(), SampleWaveform::rebuildEnvelopePaths(), SampleWaveform::rebuildHotZones(), SampleWaveform::sampleForXPixel(), VariantDisplay::selectNextFile(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
defaultsProvider
infrastructure::DefaultsProvider& defaultsProvider
Referenced by BrowserPane::BrowserPane(), SCXTEditor::idle(), WelcomeScreen::okGotItDontShowAgain(), SCXTEditor::parentHierarchyChanged(), PartSidebar::PartSidebar(), PlayScreen::PlayScreen(), SCXTEditor::resetColorsFromUserPreferences(), SCXTEditor::SCXTEditor(), SCXTEditor::setZoomFactor(), PartSidebar::visibilityChanged(), and PlayScreen::visibilityChanged().
browser
const scxt::browser::Browser& browser
Referenced by LfoPane::doLoadPreset(), LfoPane::doSavePreset(), KeyBindings::KeyBindings(), DriveFSArea::recalcContents(), and BrowserPane::resetRoots().
sharedUiMemoryState
const engine::Engine::SharedUIMemoryState& sharedUiMemoryState
Referenced by SCXTEditor::idle(), EditScreen::onVoiceInfoChanged(), and ZoneLayoutKeyboard::paint().
themeApplier
theme::ThemeApplier themeApplier
Referenced by AboutLink::AboutLink(), AboutScreen::AboutScreen(), ChannelStrip::ChannelStrip(), HeaderRegion::HeaderRegion(), ZoneLayoutDisplay::labelZoneRectangle(), LogScreen::LogScreen(), ActivityDisplay::paint(), GroupSettingsCard::paint(), GroupTriggersCard::paint(), SampleWaveform::paint(), NoSelection::paint(), VariantDisplay::FileInfos::paint(), ZoneLayoutKeyboard::paint(), PartSettingsDisplay::paint(), RoutingPaneContents< RPTraits >::RoutingBox::paint(), WorkItemLineItem::paint(), WelcomeScreen::paint(), PartSidebarCard::paint(), VariantDisplay::rebuildForSelectedVariation(), LfoPane::rebuildPanelComponents(), AdsrPane::rebuildPanelComponents(), SCXTEditor::resetColorsFromUserPreferences(), PartGroupSidebar::setSelectedTab(), MenuValueTypeinBase::setupTextEditorStyle(), SCXTEditor::showMainMenu(), SCXTEditor::themeColor(), and EditScreen::ZoneOrGroupElements< ZGTrait >::ZoneOrGroupElements().
editorDataCache
SCXTEditorDataCache editorDataCache
Referenced by HasEditor::addSubscription(), GroupSettingsCard::GroupSettingsCard(), SCXTEditor::onGroupOutputInfoUpdated(), SCXTEditor::onZoneOutputInfoUpdated(), RoutingPaneZoneTraits::outputInfo(), and RoutingPaneGroupTraits::outputInfo().
rng
sst::basic_blocks::dsp::RNG rng
edWidth
constexpr int edWidth {1286} static constexpr
Referenced by SCXTPlugin::createEditor(), and SCXTEditor::resized().
edHeight
constexpr int edHeight {816} static
Referenced by SCXTPlugin::createEditor(), and SCXTEditor::resized().
lnf
std::unique_ptr<sst::jucegui::style::LookAndFeelManager> lnf
Referenced by SCXTEditor::onStyleChanged(), and SCXTEditor::SCXTEditor().
idleTimer
std::unique_ptr<IdleTimer> idleTimer
Referenced by SCXTEditor::SCXTEditor(), and SCXTEditor::~SCXTEditor().
headerRegion
std::unique_ptr<shared::HeaderRegion> headerRegion
Referenced by SCXTEditor::idle(), SCXTEditor::onActivityNotification(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::showMainMenu().
editScreen
std::unique_ptr<edit_screen::EditScreen> editScreen
Referenced by SCXTEditor::addTuningMenu(), SCXTEditor::idle(), ZoneLayoutDisplay::isEditorInGroupMode(), SCXTEditor::keyPressed(), SCXTEditor::onBrowserQueueLengthRefresh(), SCXTEditor::onBrowserRefresh(), SCXTEditor::onBusOrPartEffectFullData(), SCXTEditor::onGroupMatrix(), SCXTEditor::onGroupMatrixMetadata(), SCXTEditor::onGroupOrZoneEnvelopeUpdated(), SCXTEditor::onGroupOrZoneMiscModStorageUpdated(), SCXTEditor::onGroupOrZoneModulatorStorageUpdated(), SCXTEditor::onGroupOrZoneProcessorDataAndMetadata(), SCXTEditor::onGroupOutputInfoUpdated(), SCXTEditor::onGroupTriggerConditions(), SCXTEditor::onGroupZoneMappingSummary(), SCXTEditor::onMacroFullState(), SCXTEditor::onMacroValue(), SCXTEditor::onMappingUpdated(), SCXTEditor::onOtherTabSelection(), SCXTEditor::onPartConfiguration(), SCXTEditor::onSamplesUpdated(), SCXTEditor::onSelectedPart(), SCXTEditor::onSelectionState(), SCXTEditor::onStructureUpdated(), SCXTEditor::onZoneOutputInfoUpdated(), SCXTEditor::onZoneVoiceMatrix(), SCXTEditor::onZoneVoiceMatrixMetadata(), PartEditScreen::PartEditScreen(), SCXTEditor::processorBypassToggled(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::setActiveScreen(), MacroMappingVariantPane::setSelectedTab(), PartGroupSidebar::setSelectedTab(), SCXTEditor::switchGroupOrZoneFocus(), LfoPane::tabChanged(), AdsrPane::tabChanged(), and MappingDisplay::voiceCountFor().
mixerScreen
std::unique_ptr<mixer_screen::MixerScreen> mixerScreen
Referenced by SCXTEditor::idle(), SCXTEditor::onBrowserQueueLengthRefresh(), SCXTEditor::onBrowserRefresh(), SCXTEditor::onBusOrPartEffectFullData(), SCXTEditor::onBusOrPartSendData(), SCXTEditor::onOtherTabSelection(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::setActiveScreen().
playScreen
std::unique_ptr<play_screen::PlayScreen> playScreen
Referenced by SCXTEditor::onBrowserQueueLengthRefresh(), SCXTEditor::onBrowserRefresh(), SCXTEditor::onMacroFullState(), SCXTEditor::onMacroValue(), SCXTEditor::onPartConfiguration(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), and SCXTEditor::setActiveScreen().
aboutScreen
std::unique_ptr<other_screens::AboutScreen> aboutScreen
Referenced by SCXTEditor::onEngineStatus(), SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
welcomeScreen
std::unique_ptr<other_screens::WelcomeScreen> welcomeScreen
Referenced by SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
logScreen
std::unique_ptr<other_screens::LogScreen> logScreen
Referenced by SCXTEditor::resized(), SCXTEditor::SCXTEditor(), SCXTEditor::setActiveScreen(), SCXTEditor::showAboutOverlay(), SCXTEditor::showLogOverlay(), and SCXTEditor::showWelcomeOverlay().
missingResolutionScreen
std::unique_ptr<missing_resolution::MissingResolutionScreen> missingResolutionScreen
Referenced by SCXTEditor::onMissingResolutionWorkItemList(), SCXTEditor::SCXTEditor(), and SCXTEditor::showMissingResolutionScreen().
hasMissingSamples
bool hasMissingSamples {false}
Referenced by SCXTEditor::onMissingResolutionWorkItemList().
toolTip
std::unique_ptr<sst::jucegui::components::ToolTip> toolTip
Referenced by SCXTEditor::hideTooltip(), SCXTEditor::repositionTooltip(), SCXTEditor::SCXTEditor(), SCXTEditor::setTooltipContents(), SCXTEditor::setTooltipContents(), SCXTEditor::showTooltip(), and SCXTEditor::showTooltip().
focusDebugger
std::unique_ptr<sst::jucegui::accessibility::FocusDebugger> focusDebugger
Referenced by SCXTEditor::SCXTEditor().
MULTI
enum scxt::ui::app::SCXTEditor::ActiveScreen MULTI
Referenced by spData::getValueAsStringFor(), SCXTEditor::onOtherTabSelection(), and SCXTEditor::setActiveScreen().
checkWelcomeCountdown
int32_t checkWelcomeCountdown {20}
Referenced by SCXTEditor::idle().
zoomFactor
float zoomFactor {1.f}
Referenced by SCXTEditor::parentHierarchyChanged(), and SCXTEditor::setZoomFactor().
onZoomChanged
std::function<void(float)> onZoomChanged {nullptr}
Referenced by SCXTEditor::setZoomFactor().
inboundMessageCount
uint64_t inboundMessageCount {0}
Referenced by SCXTEditor::drainCallbackQueue().
inboundMessageBytes
uint64_t inboundMessageBytes {0}
Referenced by SCXTEditor::drainCallbackQueue().
partConfigurations
std::array<scxt::engine::Part::PartConfiguration, scxt::numParts> partConfigurations
Referenced by PartNameMenuTypein::getInitialText(), SCXTEditor::onPartConfiguration(), ViewportComponent::paint(), PartSidebarCard::paint(), PartSidebarCard::PartSidebarCard(), PlayScreen::rebuildPositionsAndVisibilites(), PartSidebarCard::resetFromEditorCache(), PlayScreen::resized(), PartSidebar::restackForActive(), PartSidebarCard::setMidiChannel(), PartSidebarCard::showMidiModeMenu(), PartSidebarCard::showPartBlurbTooltip(), GroupZoneSidebarBase< T, forZone >::showPartSelectorMenu(), PartSidebarCard::showPolyMenu(), PartSidebarCard::showRoutingMenu(), and PartSidebarCard::textEditorTextChanged().
otherTabSelection
selection::SelectionManager::otherTabSelection_t otherTabSelection
Referenced by SCXTEditor::onOtherTabSelection(), SCXTEditor::queryTabSelection(), and SCXTEditor::setTabSelection().
allProcessors
std::vector<dsp::processor::ProcessorDescription> allProcessors
Referenced by SCXTEditor::onAllProcessorDescriptions(), and ProcessorPane::showProcessorTypeMenu().
tuningStatus
scxt::messaging::client::tuningStatusPayload_t tuningStatus
Referenced by SCXTEditor::onTuningStatus().
macroCache
std::array<std::array<scxt::engine::Macro, scxt::macrosPerPart>, scxt::numParts> macroCache
Referenced by MacroValueAttachment::macro(), MacroValueAttachment::macro(), SCXTEditor::onMacroFullState(), SCXTEditor::onMacroValue(), and SingleMacroEditor::showMenu().
clipboardType
scxt::engine::Clipboard::ContentType clipboardType {scxt::engine::Clipboard::ContentType::NONE}
Referenced by SCXTEditor::onClipboardType().
clipboard
struct scxt::ui::app::SCXTEditor::UISideClipboard clipboard
currentLeadZoneSelection
std::optional<selection::SelectionManager::ZoneAddress> currentLeadZoneSelection
Referenced by ZoneLayoutDisplay::createEmptyZoneAt(), MacroMappingVariantPane::editorSelectionChanged(), VariantDisplay::MyTabbedComponent::filesDropped(), SCXTEditor::idle(), SCXTEditor::isAnyZoneFromGroupSelected(), GroupZoneSidebarBase< T, forZone >::isLeadZone(), SCXTEditor::isSelected(), VariantDisplay::MyTabbedComponent::itemDropped(), MappingDisplay::keyPressed(), ZoneLayoutDisplay::mouseDown(), ZoneLayoutDisplay::mouseUp(), ZoneSidebar::onRowClicked(), SCXTEditor::onSelectionState(), ZoneLayoutDisplay::paint(), VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::selectNextFile(), MappingDisplay::setGroupZoneMappingSummary(), VariantDisplay::showFileBrowser(), and ZoneSidebar::updateSelection().
currentLeadGroupSelection
std::optional<selection::SelectionManager::ZoneAddress> currentLeadGroupSelection
Referenced by GroupZoneSidebarBase< T, forZone >::isLeadGroup(), MappingDisplay::keyPressed(), and SCXTEditor::onSelectionState().
allZoneSelections
selection::SelectionManager::selectedZones_t allZoneSelections
Referenced by SCXTEditor::isSelected(), SCXTEditor::onSelectionState(), and ZoneSidebar::updateSelection().
allGroupSelections
selection::SelectionManager::selectedZones_t allGroupSelections
Referenced by SCXTEditor::onSelectionState(), and GroupSidebar::updateSelection().
selectedPart
int16_t selectedPart {0}
Referenced by GroupZoneSidebarBase< T, forZone >::addGroup(), SCXTEditor::getSelectedPart(), MacroMappingVariantPane::macroDataChanged(), MacroDisplay::macroDataChanged(), MacroDisplay::MacroDisplay(), SCXTEditor::onMacroFullState(), SCXTEditor::onSelectedPart(), ViewportComponent::paint(), MacroDisplay::selectedPartChanged(), PartEditScreen::selectedPartChanged(), PartGroupSidebar::selectedPartChanged(), and GroupZoneSidebarBase< T, forZone >::showPartSelectorMenu().
groupsWithSelectedZones
std::set<int> groupsWithSelectedZones
Referenced by SCXTEditor::isAnyZoneFromGroupSelected(), and SCXTEditor::onSelectionState().
callbackMutex
std::mutex callbackMutex
Referenced by SCXTEditor::drainCallbackQueue(), and SCXTEditor::SCXTEditor().
callbackQueue
std::queue<std::string> callbackQueue
Referenced by SCXTEditor::drainCallbackQueue(), and SCXTEditor::SCXTEditor().
engineStatus
engine::Engine::EngineStatusMessage engineStatus
Referenced by SCXTEditor::onEngineStatus(), and AboutScreen::resetInfo().
lastVoiceDisplayWriteCounter
int64_t lastVoiceDisplayWriteCounter {-1}
Referenced by SCXTEditor::idle().
lastProcessMemoryInMegabytes
float lastProcessMemoryInMegabytes {0}
keyBindings
std::unique_ptr<KeyBindings> keyBindings
Referenced by SCXTEditor::keyPressed(), and SCXTEditor::SCXTEditor().
fileChooser
std::unique_ptr<juce::FileChooser> fileChooser
clapHost
const clap_host_t* clapHost {nullptr}
The documentation for this struct was generated from the following files:
SCXTEditor.h
SCXTEditor.cpp
SCXTEditorMenus.cpp
SCXTEditorResponseHandlers.cpp