shortcircuit-xt: VariantDisplay Struct Reference
VariantDisplay Struct Reference
#include <VariantDisplay.h>
Classes
struct FileInfos
struct MyTabbedComponent
struct ZoomableWaveform
Public Types
enum Ctrl {
startP , endP , startL , endL ,
fadeL , curve , src , volume ,
pan , tune
}
using floatAttachment_t = scxt::ui::connectors::PayloadDataAttachment< engine::Zone::SingleVariant >
typedef connectors::PayloadDataAttachment< engine::Zone::Variants, int > sample_attachment_t
using boolToggle_t = sst::jucegui::component_adapters::DiscreteToValueReference< sst::jucegui::components::ToggleButton, bool >
Public Member Functions
VariantDisplay (MacroMappingVariantPane *p)
void rebuildForSelectedVariation (size_t sel, bool rebuildTabs=true)
~VariantDisplay ()
void reset ()
void onSamplePointChangedFromGUI ()
juce::Rectangle< int > sampleDisplayRegion ()
void resized () override
void setActive (bool b)
void rebuild ()
void selectNextFile (bool selectForward)
void showFileBrowser ()
void showFileInfos ()
void showPlayModeMenu ()
void showLoopModeMenu ()
void showVariantPlaymodeMenu ()
void showSRCMenu ()
void showVariantTabMenu (int variantIdx)
void showHamburgerMenu ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::unordered_map< Ctrl, std::unique_ptr< connectors::SamplePointDataAttachment > > sampleAttachments
std::unordered_map< Ctrl, std::unique_ptr< sst::jucegui::components::DraggableTextEditableValue > > sampleEditors
std::unordered_map< Ctrl, std::unique_ptr< floatAttachment_t > > sampleFloatAttachments
std::unordered_map< Ctrl, std::unique_ptr< sst::jucegui::components::Label > > labels
std::unordered_map< Ctrl, std::unique_ptr< sst::jucegui::components::GlyphPainter > > glyphLabels
std::unique_ptr< sample_attachment_t > loopCntAttachment
std::unique_ptr< sst::jucegui::components::DraggableTextEditableValue > loopCnt
std::unique_ptr< connectors::BooleanPayloadDataAttachment< engine::Zone::Variants > > loopAttachment
std::unique_ptr< connectors::BooleanPayloadDataAttachment< engine::Zone::Variants > > reverseAttachment
std::unique_ptr< sst::jucegui::components::ToggleButton > loopActive
std::unique_ptr< sst::jucegui::components::ToggleButton > reverseActive
std::array< ZoomableWaveform, maxVariantsPerZone > waveforms
std::unique_ptr< sst::jucegui::components::NamedPanelDivider > divider
std::unique_ptr< MyTabbedComponent > waveformsTabbedGroup
size_t selectedVariation {0}
std::unique_ptr< juce::FileChooser > fileChooser
bool active {false}
bool fileInfoShowing {false}
std::unique_ptr< sst::jucegui::components::MenuButton > variantPlaymodeButton
std::unique_ptr< sst::jucegui::components::MenuButton > fileButton
std::unique_ptr< sst::jucegui::components::Label > variantPlayModeLabel
std::unique_ptr< sst::jucegui::components::Label > fileLabel
std::unique_ptr< boolToggle_t > fileInfoButton
std::unique_ptr< sst::jucegui::components::TextPushButton > editAllButton
std::unique_ptr< sst::jucegui::components::GlyphButton > nextFileButton
std::unique_ptr< sst::jucegui::components::GlyphButton > prevFileButton
std::unique_ptr< sst::jucegui::components::Label > playModeLabel
std::unique_ptr< sst::jucegui::components::MenuButton > playModeButton
std::unique_ptr< sst::jucegui::components::MenuButton > loopModeButton
std::unique_ptr< sst::jucegui::components::MenuButton > srcButton
std::unique_ptr< sst::jucegui::components::GlyphButton > zoomButton
std::unique_ptr< juce::Component > noSelectionOverlay
std::unique_ptr< FileInfos > fileInfos
engine::Zone::Variants & variantView
MacroMappingVariantPane * parentPane {nullptr}
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Static Public Attributes
static constexpr int sidePanelWidth {136}
static constexpr int sidePanelDividerPad {10}
Member Typedef Documentation
floatAttachment_t
using floatAttachment_t = scxt::ui::connectors::PayloadDataAttachment<engine::Zone::SingleVariant>
sample_attachment_t
typedef connectors::PayloadDataAttachment<engine::Zone::Variants, int> sample_attachment_t
boolToggle_t
using boolToggle_t = sst::jucegui::component_adapters::DiscreteToValueReference< sst::jucegui::components::ToggleButton, bool>
Member Enumeration Documentation
Ctrl
enum Ctrl
Enumerator
startP
endP
startL
endL
fadeL
curve
src
volume
pan
tune
Constructor & Destructor Documentation
VariantDisplay()
VariantDisplay (MacroMappingVariantPane * p)
References VariantDisplay::editAllButton, HasEditor::editor, VariantDisplay::fileButton, VariantDisplay::fileInfoButton, VariantDisplay::fileInfos, VariantDisplay::fileInfoShowing, VariantDisplay::fileLabel, SCXTEditor::makeComingSoon(), VariantDisplay::nextFileButton, VariantDisplay::noSelectionOverlay, VariantDisplay::prevFileButton, VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::selectedVariation, VariantDisplay::selectNextFile(), VariantDisplay::showFileBrowser(), VariantDisplay::showVariantPlaymodeMenu(), VariantDisplay::variantPlaymodeButton, VariantDisplay::variantPlayModeLabel, VariantDisplay::waveforms, and VariantDisplay::waveformsTabbedGroup.
~VariantDisplay()
~VariantDisplay ()
References VariantDisplay::reset().
Member Function Documentation
rebuildForSelectedVariation()
void rebuildForSelectedVariation (size_t sel, bool rebuildTabs = true)
References ThemeApplier::applyVariantLoopTheme(), ColorMap::bg_2, SCXTEditor::currentLeadZoneSelection, VariantDisplay::curve, scxt::datamodel::describeValue(), VariantDisplay::divider, HasEditor::editor, VariantDisplay::endL, VariantDisplay::endP, VariantDisplay::fadeL, VariantDisplay::glyphLabels, VariantDisplay::labels, VariantDisplay::loopActive, VariantDisplay::loopAttachment, VariantDisplay::loopCnt, VariantDisplay::loopCntAttachment, VariantDisplay::loopModeButton, SCXTEditor::makeComingSoon(), VariantDisplay::noSelectionOverlay, VariantDisplay::onSamplePointChangedFromGUI(), VariantDisplay::pan, VariantDisplay::playModeButton, VariantDisplay::playModeLabel, VariantDisplay::rebuild(), VariantDisplay::resized(), VariantDisplay::reverseActive, VariantDisplay::reverseAttachment, VariantDisplay::sampleAttachments, VariantDisplay::sampleEditors, VariantDisplay::sampleFloatAttachments, VariantDisplay::selectedVariation, VariantDisplay::showLoopModeMenu(), VariantDisplay::showPlayModeMenu(), VariantDisplay::showSRCMenu(), VariantDisplay::src, VariantDisplay::srcButton, VariantDisplay::startL, VariantDisplay::startP, SCXTEditor::themeApplier, SCXTEditor::themeColor(), VariantDisplay::tune, Zone::Variants::variants, VariantDisplay::variantView, VariantDisplay::volume, VariantDisplay::waveforms, VariantDisplay::waveformsTabbedGroup, withLinearScaleFormatting(), withName(), and VariantDisplay::zoomButton.
Referenced by VariantDisplay::MyTabbedComponent::currentTabChanged(), and VariantDisplay::VariantDisplay().
reset()
void reset ()
References VariantDisplay::sampleEditors.
Referenced by VariantDisplay::~VariantDisplay().
onSamplePointChangedFromGUI()
void onSamplePointChangedFromGUI ()
References VariantDisplay::selectedVariation, HasEditor::sendToSerialization(), Zone::Variants::variants, VariantDisplay::variantView, and VariantDisplay::waveforms.
Referenced by SampleWaveform::mouseDrag(), SampleWaveform::mouseUp(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::showPlayModeMenu().
sampleDisplayRegion()
juce::Rectangle< int > sampleDisplayRegion ()
References VariantDisplay::sidePanelDividerPad, and VariantDisplay::sidePanelWidth.
Referenced by VariantDisplay::resized().
resized()
void resized () override
References VariantDisplay::curve, VariantDisplay::divider, VariantDisplay::editAllButton, VariantDisplay::endL, VariantDisplay::endP, VariantDisplay::fadeL, VariantDisplay::fileButton, VariantDisplay::fileInfoButton, VariantDisplay::fileInfos, VariantDisplay::fileLabel, VariantDisplay::glyphLabels, VariantDisplay::labels, Zone::LOOP_COUNT, VariantDisplay::loopActive, VariantDisplay::loopCnt, VariantDisplay::loopModeButton, VariantDisplay::nextFileButton, VariantDisplay::noSelectionOverlay, VariantDisplay::pan, VariantDisplay::playModeButton, VariantDisplay::playModeLabel, VariantDisplay::prevFileButton, VariantDisplay::reverseActive, VariantDisplay::sampleDisplayRegion(), VariantDisplay::sampleEditors, SCLOG_IF, VariantDisplay::selectedVariation, VariantDisplay::sidePanelDividerPad, VariantDisplay::sidePanelWidth, VariantDisplay::src, VariantDisplay::srcButton, VariantDisplay::startL, VariantDisplay::startP, VariantDisplay::tune, VariantDisplay::variantPlaymodeButton, VariantDisplay::variantPlayModeLabel, Zone::Variants::variants, VariantDisplay::variantView, VariantDisplay::volume, VariantDisplay::waveformsTabbedGroup, and VariantDisplay::zoomButton.
Referenced by VariantDisplay::rebuild(), and VariantDisplay::rebuildForSelectedVariation().
setActive()
void setActive (bool b)
References VariantDisplay::active, VariantDisplay::labels, VariantDisplay::loopActive, VariantDisplay::loopModeButton, VariantDisplay::playModeButton, VariantDisplay::rebuild(), VariantDisplay::reverseActive, and VariantDisplay::sampleEditors.
rebuild()
void rebuild ()
References Zone::ALTERNATE_DIRECTIONS, VariantDisplay::curve, HasEditor::editor, VariantDisplay::endL, VariantDisplay::fadeL, VariantDisplay::fileButton, VariantDisplay::fileInfos, Zone::FORWARD_RR, SampleManager::getSample(), VariantDisplay::glyphLabels, VariantDisplay::labels, scxt::dsp::Linear, Zone::LOOP_COUNT, Zone::LOOP_DURING_VOICE, Zone::LOOP_WHILE_GATED, VariantDisplay::loopCnt, VariantDisplay::loopModeButton, Zone::NORMAL, Zone::ON_RELEASE, Zone::ONE_SHOT, VariantDisplay::playModeButton, Zone::RANDOM_CYCLE, Zone::RANDOM_NOREPEAT, VariantDisplay::resized(), VariantDisplay::sampleAttachments, VariantDisplay::sampleEditors, SCXTEditor::sampleManager, VariantDisplay::selectedVariation, scxt::dsp::Sinc, VariantDisplay::srcButton, VariantDisplay::startL, Zone::TRUE_RANDOM, Zone::UNISON, Zone::Variants::variantPlaybackMode, VariantDisplay::variantPlaymodeButton, Zone::Variants::variants, VariantDisplay::variantView, VariantDisplay::waveforms, scxt::dsp::ZeroOrderHold, scxt::dsp::ZOHAA, and VariantDisplay::zoomButton.
Referenced by VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::setActive(), VariantDisplay::showPlayModeMenu(), VariantDisplay::showSRCMenu(), and VariantDisplay::showVariantPlaymodeMenu().
selectNextFile()
void selectNextFile (bool selectForward)
References SCXTEditor::currentLeadZoneSelection, SCXTEditor::displayError(), HasEditor::editor, SampleManager::getSample(), Browser::isLoadableSingleSample(), SCXTEditor::sampleManager, VariantDisplay::selectedVariation, HasEditor::sendToSerialization(), Zone::Variants::variants, and VariantDisplay::variantView.
Referenced by VariantDisplay::VariantDisplay().
showFileBrowser()
void showFileBrowser ()
References SCXTEditor::currentLeadZoneSelection, HasEditor::editor, VariantDisplay::fileChooser, scxt::ui::app::shared::juceFileToFsPath(), VariantDisplay::selectedVariation, HasEditor::sendToSerialization(), and Browser::LoadableFile::singleSample.
Referenced by VariantDisplay::VariantDisplay().
showFileInfos()
void showFileInfos ()
References VariantDisplay::fileInfos, and VariantDisplay::fileInfoShowing.
showPlayModeMenu()
void showPlayModeMenu ()
References SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, Zone::NORMAL, Zone::ON_RELEASE, Zone::ONE_SHOT, VariantDisplay::onSamplePointChangedFromGUI(), VariantDisplay::rebuild(), VariantDisplay::selectedVariation, Zone::Variants::variants, and VariantDisplay::variantView.
Referenced by VariantDisplay::rebuildForSelectedVariation().
showLoopModeMenu()
void showLoopModeMenu ()
References Zone::ALTERNATE_DIRECTIONS, SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, Zone::FORWARD_ONLY, Zone::LOOP_COUNT, Zone::LOOP_DURING_VOICE, Zone::LOOP_WHILE_GATED, VariantDisplay::loopModeButton, VariantDisplay::selectedVariation, Zone::Variants::variants, and VariantDisplay::variantView.
Referenced by VariantDisplay::rebuildForSelectedVariation().
showVariantPlaymodeMenu()
void showVariantPlaymodeMenu ()
References SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, Zone::FORWARD_RR, Zone::RANDOM_CYCLE, Zone::RANDOM_NOREPEAT, VariantDisplay::rebuild(), Zone::TRUE_RANDOM, Zone::UNISON, Zone::Variants::variantPlaybackMode, and VariantDisplay::variantView.
Referenced by VariantDisplay::VariantDisplay().
showSRCMenu()
void showSRCMenu ()
References SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, scxt::dsp::Linear, VariantDisplay::rebuild(), VariantDisplay::selectedVariation, scxt::dsp::Sinc, Zone::Variants::variants, VariantDisplay::variantView, scxt::dsp::ZeroOrderHold, and scxt::dsp::ZOHAA.
Referenced by VariantDisplay::rebuildForSelectedVariation().
showVariantTabMenu()
void showVariantTabMenu (int variantIdx)
References SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, SCXTEditor::makeComingSoon(), Zone::Variants::variants, and VariantDisplay::variantView.
showHamburgerMenu()
void showHamburgerMenu ()
References SCXTEditor::defaultPopupMenuOptions(), and HasEditor::editor.
Member Data Documentation
sidePanelWidth
constexpr int sidePanelWidth {136} static constexpr
Referenced by VariantDisplay::resized(), and VariantDisplay::sampleDisplayRegion().
sidePanelDividerPad
constexpr int sidePanelDividerPad {10} static constexpr
Referenced by VariantDisplay::resized(), and VariantDisplay::sampleDisplayRegion().
sampleAttachments
std::unordered_map<Ctrl, std::unique_ptr<connectors::SamplePointDataAttachment> > sampleAttachments
Referenced by VariantDisplay::rebuild(), and VariantDisplay::rebuildForSelectedVariation().
sampleEditors
std::unordered_map<Ctrl, std::unique_ptr<sst::jucegui::components::DraggableTextEditableValue> > sampleEditors
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::reset(), VariantDisplay::resized(), and VariantDisplay::setActive().
sampleFloatAttachments
std::unordered_map<Ctrl, std::unique_ptr<floatAttachment_t> > sampleFloatAttachments
Referenced by VariantDisplay::rebuildForSelectedVariation().
labels
std::unordered_map<Ctrl, std::unique_ptr<sst::jucegui::components::Label> > labels
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::setActive().
glyphLabels
std::unordered_map<Ctrl, std::unique_ptr<sst::jucegui::components::GlyphPainter> > glyphLabels
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
loopCntAttachment
std::unique_ptr<sample_attachment_t> loopCntAttachment
Referenced by VariantDisplay::rebuildForSelectedVariation().
loopCnt
std::unique_ptr<sst::jucegui::components::DraggableTextEditableValue> loopCnt
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
loopAttachment
std::unique_ptr<connectors::BooleanPayloadDataAttachment<engine::Zone::Variants> > loopAttachment
Referenced by VariantDisplay::rebuildForSelectedVariation().
reverseAttachment
std::unique_ptr<connectors::BooleanPayloadDataAttachment<engine::Zone::Variants> > reverseAttachment
Referenced by VariantDisplay::rebuildForSelectedVariation().
loopActive
std::unique_ptr<sst::jucegui::components::ToggleButton> loopActive
Referenced by VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::setActive().
reverseActive
std::unique_ptr<sst::jucegui::components::ToggleButton> reverseActive
Referenced by VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::setActive().
waveforms
std::array<ZoomableWaveform, maxVariantsPerZone> waveforms
Referenced by VariantDisplay::onSamplePointChangedFromGUI(), VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::VariantDisplay().
divider
std::unique_ptr<sst::jucegui::components::NamedPanelDivider> divider
Referenced by VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
waveformsTabbedGroup
std::unique_ptr<MyTabbedComponent> waveformsTabbedGroup
Referenced by VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
selectedVariation
size_t selectedVariation {0}
Referenced by SampleWaveform::mouseDrag(), VariantDisplay::onSamplePointChangedFromGUI(), SampleWaveform::paint(), VariantDisplay::rebuild(), SampleWaveform::rebuildEnvelopePaths(), VariantDisplay::rebuildForSelectedVariation(), SampleWaveform::rebuildHotZones(), VariantDisplay::resized(), SampleWaveform::sampleForXPixel(), VariantDisplay::selectNextFile(), VariantDisplay::showFileBrowser(), VariantDisplay::showLoopModeMenu(), VariantDisplay::showPlayModeMenu(), VariantDisplay::showSRCMenu(), VariantDisplay::VariantDisplay(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
fileChooser
std::unique_ptr<juce::FileChooser> fileChooser
Referenced by VariantDisplay::showFileBrowser().
active
bool active {false}
Referenced by SampleWaveform::paint(), and VariantDisplay::setActive().
fileInfoShowing
bool fileInfoShowing {false}
Referenced by VariantDisplay::showFileInfos(), and VariantDisplay::VariantDisplay().
variantPlaymodeButton
std::unique_ptr<sst::jucegui::components::MenuButton> variantPlaymodeButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
fileButton
std::unique_ptr<sst::jucegui::components::MenuButton> fileButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
variantPlayModeLabel
std::unique_ptr<sst::jucegui::components::Label> variantPlayModeLabel
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
fileLabel
std::unique_ptr<sst::jucegui::components::Label> fileLabel
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
fileInfoButton
std::unique_ptr<boolToggle_t> fileInfoButton
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
editAllButton
std::unique_ptr<sst::jucegui::components::TextPushButton> editAllButton
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
nextFileButton
std::unique_ptr<sst::jucegui::components::GlyphButton> nextFileButton
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
prevFileButton
std::unique_ptr<sst::jucegui::components::GlyphButton> prevFileButton
Referenced by VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
playModeLabel
std::unique_ptr<sst::jucegui::components::Label> playModeLabel
Referenced by VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
playModeButton
std::unique_ptr<sst::jucegui::components::MenuButton> playModeButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::setActive().
loopModeButton
std::unique_ptr<sst::jucegui::components::MenuButton> loopModeButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), VariantDisplay::setActive(), and VariantDisplay::showLoopModeMenu().
srcButton
std::unique_ptr<sst::jucegui::components::MenuButton> srcButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
zoomButton
std::unique_ptr<sst::jucegui::components::GlyphButton> zoomButton
Referenced by VariantDisplay::rebuild(), VariantDisplay::rebuildForSelectedVariation(), and VariantDisplay::resized().
noSelectionOverlay
std::unique_ptr<juce::Component> noSelectionOverlay
Referenced by VariantDisplay::rebuildForSelectedVariation(), VariantDisplay::resized(), and VariantDisplay::VariantDisplay().
fileInfos
std::unique_ptr<FileInfos> fileInfos
Referenced by VariantDisplay::rebuild(), VariantDisplay::resized(), VariantDisplay::showFileInfos(), and VariantDisplay::VariantDisplay().
variantView
engine::Zone::Variants& variantView
Referenced by SampleWaveform::mouseDrag(), VariantDisplay::onSamplePointChangedFromGUI(), SampleWaveform::paint(), VariantDisplay::rebuild(), SampleWaveform::rebuildEnvelopePaths(), VariantDisplay::rebuildForSelectedVariation(), SampleWaveform::rebuildHotZones(), VariantDisplay::resized(), SampleWaveform::sampleForXPixel(), VariantDisplay::selectNextFile(), VariantDisplay::showLoopModeMenu(), VariantDisplay::showPlayModeMenu(), VariantDisplay::showSRCMenu(), VariantDisplay::showVariantPlaymodeMenu(), VariantDisplay::showVariantTabMenu(), SampleWaveform::xPixelForSample(), and SampleWaveform::xPixelForSampleDistance().
parentPane
MacroMappingVariantPane* parentPane {nullptr}
Referenced by SampleWaveform::mouseDoubleClick().
The documentation for this struct was generated from the following files:
VariantDisplay.h
VariantDisplay.cpp