shortcircuit-xt: KernelOp< InterpolationTypes::ZeroOrderHold, T > Struct Template Reference
KernelOp< InterpolationTypes::ZeroOrderHold, T > Struct Template Reference
Static Public Member Functions
template<int NUM_CHANNELS, bool LOOP_ACTIVE>
static void Process (GeneratorState *__restrict GD, KernelProcessor< InterpolationTypes::ZeroOrderHold, T, NUM_CHANNELS, LOOP_ACTIVE > &ks)
Member Function Documentation
Process()
template<typename T > template<int NUM_CHANNELS, bool LOOP_ACTIVE> void Process (GeneratorState *__restrict GD, KernelProcessor< InterpolationTypes::ZeroOrderHold, T, NUM_CHANNELS, LOOP_ACTIVE > & ks) static
References KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::fadeActive, scxt::dsp::getFadeGain(), scxt::dsp::getFadeGainToAmp(), KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::i, KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::loopFade, scxt::dsp::NormalizeSampleToF32(), KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::Output, KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::ReadFadeSample, KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::ReadSample, and KernelProcessor< KT, T, NUM_CHANNELS, LOOP_ACTIVE >::SamplePos.
The documentation for this struct was generated from the following file:
generator.cpp