shortcircuit-xt: CurveLFOPane::CurveDataSource Struct Reference
CurveLFOPane::CurveDataSource Struct Reference
Inherits CompactPlotSource.
Public Member Functions
CurveDataSource (LfoPane *p)
bool curvePathIsValid () const override
void recalculateCurvePath (plotData_t &into) override
Public Attributes
LfoPane * parent {nullptr}
sst::basic_blocks::modulators::Transport dummyTransport
modulation::ModulatorStorage ms
Constructor & Destructor Documentation
CurveDataSource()
CurveDataSource (LfoPane * p)
References CurveLFOPane::CurveDataSource::dummyTransport.
Member Function Documentation
curvePathIsValid()
bool curvePathIsValid () const override
References LfoPane::modulatorStorageData, CurveLFOPane::CurveDataSource::ms, and CurveLFOPane::CurveDataSource::parent.
recalculateCurvePath()
void recalculateCurvePath (plotData_t & into) override
References CurveLFO::assign(), CurveLFO::attack(), CurveLFOPane::CurveDataSource::dummyTransport, LfoPane::modulatorStorageData, CurveLFOPane::CurveDataSource::ms, CurveLFO::output, CurveLFOPane::CurveDataSource::parent, CurveLFO::process(), SampleRateSupport::setSampleRate(), and CurveLFO::simpleLfo.
Member Data Documentation
parent
LfoPane* parent {nullptr}
Referenced by CurveLFOPane::CurveDataSource::curvePathIsValid(), and CurveLFOPane::CurveDataSource::recalculateCurvePath().
dummyTransport
sst::basic_blocks::modulators::Transport dummyTransport
Referenced by CurveLFOPane::CurveDataSource::CurveDataSource(), and CurveLFOPane::CurveDataSource::recalculateCurvePath().
ms
modulation::ModulatorStorage ms
Referenced by CurveLFOPane::CurveDataSource::curvePathIsValid(), and CurveLFOPane::CurveDataSource::recalculateCurvePath().
The documentation for this struct was generated from the following file:
LFOPane.cpp