shortcircuit-xt: MatrixEndpoints::OutputTarget Struct Reference
MatrixEndpoints::OutputTarget Struct Reference
Public Member Functions
OutputTarget (engine::Engine *e)
void bind (Matrix &m, engine::Zone &z)
Public Attributes
TG panT
TG ampT
const float * panP {nullptr}
const float * ampP {nullptr}
Constructor & Destructor Documentation
OutputTarget()
OutputTarget (engine::Engine * e)
References MatrixEndpoints::OutputTarget::ampT, MatrixEndpoints::OutputTarget::panT, MatrixEndpoints::registerVoiceModTarget(), and MatrixConfig::setIsMultiplicative().
Member Function Documentation
bind()
void bind (Matrix & m, engine::Zone & z)
References scxt::modulation::shared::bindEl(), and Zone::outputInfo.
Referenced by MatrixEndpoints::bindTargetBaseValues().
Member Data Documentation
panT
TG panT
Referenced by MatrixEndpoints::OutputTarget::OutputTarget().
ampT
TG ampT
Referenced by MatrixEndpoints::OutputTarget::OutputTarget().
panP
const float* panP {nullptr}
ampP
const float * ampP {nullptr}
The documentation for this struct was generated from the following files:
voice_matrix.h
voice_matrix.cpp