shortcircuit-xt: CurveLFOPane::CurveDraw Struct Reference
CurveLFOPane::CurveDraw Struct Reference
Inherits Component.
Public Member Functions
CurveDraw (LfoPane *p)
void paint (juce::Graphics &g) override
Public Attributes
LfoPane * parent {nullptr}
sst::basic_blocks::modulators::Transport dummyTransport
modulation::ModulatorStorage ms
juce::Path curvePath {}
Constructor & Destructor Documentation
CurveDraw()
CurveDraw (LfoPane * p)
References CurveLFOPane::CurveDraw::dummyTransport.
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References CurveLFO::assign(), CurveLFO::attack(), CurveLFOPane::CurveDraw::curvePath, CurveLFOPane::CurveDraw::dummyTransport, HasEditor::editor, ColorMap::generic_content_high, LfoPane::modulatorStorageData, CurveLFOPane::CurveDraw::ms, CurveLFO::output, CurveLFOPane::CurveDraw::parent, CurveLFO::process(), SampleRateSupport::setSampleRate(), CurveLFO::simpleLfo, and SCXTEditor::themeColor().
Member Data Documentation
parent
LfoPane* parent {nullptr}
Referenced by CurveLFOPane::CurveDraw::paint().
dummyTransport
sst::basic_blocks::modulators::Transport dummyTransport
Referenced by CurveLFOPane::CurveDraw::CurveDraw(), and CurveLFOPane::CurveDraw::paint().
ms
modulation::ModulatorStorage ms
Referenced by CurveLFOPane::CurveDraw::paint().
curvePath
juce::Path curvePath {}
Referenced by CurveLFOPane::CurveDraw::paint().
The documentation for this struct was generated from the following file:
LFOPane.cpp