shortcircuit-xt: SFZParser Struct Reference
SFZParser Struct Reference
#include <sfz_parse.h>
Classes
struct Header
struct OpCode
Public Types
typedef std::vector< OpCode > opCodes_t
typedef std::pair< Header, opCodes_t > section_t
typedef std::vector< section_t > document_t
Public Member Functions
document_t parse (const std::string &contents)
document_t parse (const fs::path &file)
Member Typedef Documentation
opCodes_t
typedef std::vector<OpCode> opCodes_t
section_t
typedef std::pair<Header, opCodes_t> section_t
document_t
typedef std::vector<section_t> document_t
Member Function Documentation
parse() [1/2]
SFZParser::document_t parse (const std::string & contents)
References HDR_HELPER, SFZParser::OpCode::name, and SFZParser::OpCode::value.
Referenced by scxt::sfz_support::importSFZ(), main(), and SFZParser::parse().
parse() [2/2]
SFZParser::document_t parse (const fs::path & file)
References SFZParser::parse().
The documentation for this struct was generated from the following files:
sfz_parse.h
sfz_parse.cpp