shortcircuit-xt: DriveFSArea Struct Reference
DriveFSArea Struct Reference
Classes
struct RowContents
Public Member Functions
DriveFSArea (BrowserPane *b, SCXTEditor *e)
void paint (juce::Graphics &g) override
void setRootRow (const fs::path &p)
void setCurrentPath (const fs::path &p)
void upOneLevel ()
void recalcContents ()
void resized () override
void setupListView ()
void expandMultifile (int row)
void collapsMultifile (int row)
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename W , typename A >
void setupIntAttachedWidgetForValueMenu (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
BrowserPane * browserPane {nullptr}
std::unique_ptr< jcmp::ListView > listView
std::set< DriveFSRowComponent * > selectedRows
fs::path rootPath
fs::path currentPath
std::vector< RowContents > contents
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Constructor & Destructor Documentation
DriveFSArea()
DriveFSArea (BrowserPane * b, SCXTEditor * e)
References DriveFSArea::listView, and DriveFSArea::setupListView().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
References DriveFSArea::browserPane.
setRootRow()
void setRootRow (const fs::path & p)
References DriveFSArea::currentPath, DriveFSArea::recalcContents(), and DriveFSArea::rootPath.
setCurrentPath()
void setCurrentPath (const fs::path & p)
References DriveFSArea::currentPath, and DriveFSArea::recalcContents().
Referenced by DriveFSArea::upOneLevel().
upOneLevel()
void upOneLevel ()
References DriveFSArea::currentPath, DriveFSArea::rootPath, and DriveFSArea::setCurrentPath().
recalcContents()
void recalcContents ()
References SCXTEditor::browser, DriveFSArea::contents, DriveFSArea::currentPath, HasEditor::editor, Browser::isLoadableFile(), and SCLOG.
Referenced by DriveFSArea::setCurrentPath(), and DriveFSArea::setRootRow().
resized()
void resized () override
setupListView()
void setupListView ()
References DriveFSRowComponent::isSelected, and DriveFSRowComponent::rowNumber.
Referenced by DriveFSArea::DriveFSArea().
expandMultifile()
void expandMultifile (int row)
References Browser::expandForBrowser().
collapsMultifile()
void collapsMultifile (int row)
Member Data Documentation
browserPane
BrowserPane* browserPane {nullptr}
Referenced by DriveFSArea::paint().
listView
std::unique_ptr<jcmp::ListView> listView
Referenced by DriveFSArea::DriveFSArea().
selectedRows
std::set<DriveFSRowComponent *> selectedRows
rootPath
fs::path rootPath
Referenced by DriveFSArea::setRootRow(), and DriveFSArea::upOneLevel().
currentPath
fs::path currentPath
Referenced by DriveFSArea::recalcContents(), DriveFSArea::setCurrentPath(), DriveFSArea::setRootRow(), and DriveFSArea::upOneLevel().
contents
std::vector<RowContents> contents
Referenced by DriveFSArea::recalcContents().
The documentation for this struct was generated from the following file:
BrowserPane.cpp