shortcircuit-xt: OutputTab< OTTraits > Struct Template Reference
OutputTab< OTTraits > Struct Template Reference
Public Types
typedef connectors::PayloadDataAttachment< typename OTTraits::info_t > attachment_t
typedef connectors::BooleanPayloadDataAttachment< typename OTTraits::info_t > bool_attachment_t
Public Member Functions
OutputTab (SCXTEditor *e, OutputPane< OTTraits > *p)
void resized ()
std::string getRoutingLabel (scxt::engine::BusAddress rt)
void updateRoutingLabel ()
void selectNewRouting ()
Public Member Functions inherited from HasEditor
HasEditor (SCXTEditor *e)
HasEditor (HasEditor *e)
virtual ~HasEditor ()=default
template<typename T >
void sendToSerialization (const T &msg)
template<typename T , typename P , typename V >
void sendSingleToSerialization (const P &payload, const V &value)
template<typename T >
void updateValueTooltip (const T &attachment)
template<typename W , typename A >
void setupWidgetForValueTooltip (W *widget, const A &attachment)
template<typename P , typename A >
void addSubscription (const P &, A &)
Public Attributes
std::unique_ptr< attachment_t > outputAttachment
std::unique_ptr< attachment_t > panAttachment
std::unique_ptr< attachment_t > velocitySensitivityAttachment
std::unique_ptr< jcmp::MenuButton > outputRouting
OutputPane< OTTraits > * parent {nullptr}
std::unique_ptr< jcmp::Labeled< jcmp::Knob > > outputKnob
std::unique_ptr< jcmp::Labeled< jcmp::Knob > > panKnob
std::unique_ptr< jcmp::Labeled< jcmp::HSliderFilled > > velocitySensitivitySlider
std::unique_ptr< bool_attachment_t > oversampleAttachment
std::unique_ptr< jcmp::ToggleButton > oversampleButton
OTTraits::info_t & info
Public Attributes inherited from HasEditor
SCXTEditor * editor {nullptr}
Member Typedef Documentation
attachment_t
template<typename OTTraits > typedef connectors::PayloadDataAttachment<typename OTTraits::info_t> attachment_t
bool_attachment_t
template<typename OTTraits > typedef connectors::BooleanPayloadDataAttachment<typename OTTraits::info_t> bool_attachment_t
Constructor & Destructor Documentation
OutputTab()
template<typename OTTraits > OutputTab (SCXTEditor * e, OutputPane< OTTraits > * p)
References OutputTab< OTTraits >::info, OutputTab< OTTraits >::outputAttachment, OutputTab< OTTraits >::outputKnob, OutputTab< OTTraits >::outputRouting, OutputTab< OTTraits >::oversampleAttachment, OutputTab< OTTraits >::oversampleButton, OutputTab< OTTraits >::panAttachment, OutputTab< OTTraits >::panKnob, OutputTab< OTTraits >::updateRoutingLabel(), OutputTab< OTTraits >::velocitySensitivityAttachment, and OutputTab< OTTraits >::velocitySensitivitySlider.
Member Function Documentation
resized()
template<typename OTTraits > void resized ()
References scxt::ui::theme::layout::columnCenterX(), OutputTab< OTTraits >::outputKnob, OutputTab< OTTraits >::outputRouting, OutputTab< OTTraits >::oversampleButton, OutputTab< OTTraits >::panKnob, and OutputTab< OTTraits >::velocitySensitivitySlider.
getRoutingLabel()
template<typename OTTraits > std::string getRoutingLabel (scxt::engine::BusAddress rt)
References scxt::engine::getBusAddressLabel().
Referenced by OutputTab< OTTraits >::selectNewRouting(), and OutputTab< OTTraits >::updateRoutingLabel().
updateRoutingLabel()
template<typename OTTraits > void updateRoutingLabel ()
References OutputTab< OTTraits >::getRoutingLabel(), OutputTab< OTTraits >::info, and OutputTab< OTTraits >::outputRouting.
Referenced by OutputTab< OTTraits >::OutputTab().
selectNewRouting()
template<typename OTTraits > void selectNewRouting ()
References scxt::engine::AUX_0, scxt::engine::DEFAULT_BUS, SCXTEditor::defaultPopupMenuOptions(), HasEditor::editor, and OutputTab< OTTraits >::getRoutingLabel().
Member Data Documentation
outputAttachment
template<typename OTTraits > std::unique_ptr<attachment_t> outputAttachment
Referenced by OutputTab< OTTraits >::OutputTab().
panAttachment
template<typename OTTraits > std::unique_ptr<attachment_t> panAttachment
Referenced by OutputTab< OTTraits >::OutputTab().
velocitySensitivityAttachment
template<typename OTTraits > std::unique_ptr<attachment_t> velocitySensitivityAttachment
Referenced by OutputTab< OTTraits >::OutputTab().
outputRouting
template<typename OTTraits > std::unique_ptr<jcmp::MenuButton> outputRouting
Referenced by OutputTab< OTTraits >::OutputTab(), OutputTab< OTTraits >::resized(), and OutputTab< OTTraits >::updateRoutingLabel().
parent
template<typename OTTraits > OutputPane<OTTraits>* parent {nullptr}
outputKnob
template<typename OTTraits > std::unique_ptr<jcmp::Labeled<jcmp::Knob> > outputKnob
Referenced by OutputTab< OTTraits >::OutputTab(), and OutputTab< OTTraits >::resized().
panKnob
template<typename OTTraits > std::unique_ptr<jcmp::Labeled<jcmp::Knob> > panKnob
Referenced by OutputTab< OTTraits >::OutputTab(), and OutputTab< OTTraits >::resized().
velocitySensitivitySlider
template<typename OTTraits > std::unique_ptr<jcmp::Labeled<jcmp::HSliderFilled> > velocitySensitivitySlider
Referenced by OutputTab< OTTraits >::OutputTab(), and OutputTab< OTTraits >::resized().
oversampleAttachment
template<typename OTTraits > std::unique_ptr<bool_attachment_t> oversampleAttachment
Referenced by OutputTab< OTTraits >::OutputTab().
oversampleButton
template<typename OTTraits > std::unique_ptr<jcmp::ToggleButton> oversampleButton
Referenced by OutputTab< OTTraits >::OutputTab(), and OutputTab< OTTraits >::resized().
info
template<typename OTTraits > OTTraits::info_t& info
Referenced by OutputTab< OTTraits >::OutputTab(), and OutputTab< OTTraits >::updateRoutingLabel().
The documentation for this struct was generated from the following file:
OutputPane.cpp