shortcircuit-xt: MatrixEndpoints::SampleTarget Struct Reference
MatrixEndpoints::SampleTarget Struct Reference
#include <voice_matrix.h>
Public Member Functions
SampleTarget (engine::Engine *e)
void bind (Matrix &m, engine::Zone &z)
Public Attributes
TG startPosT
const float * startPosP {nullptr}
float zeroBase {0.f}
Constructor & Destructor Documentation
SampleTarget()
SampleTarget (engine::Engine * e)
References MatrixEndpoints::registerVoiceModTarget(), and MatrixEndpoints::SampleTarget::startPosT.
Member Function Documentation
bind()
void bind (Matrix & m, engine::Zone & z)
References scxt::modulation::shared::bindEl(), and Zone::mapping.
Referenced by MatrixEndpoints::bindTargetBaseValues().
Member Data Documentation
startPosT
TG startPosT
Referenced by MatrixEndpoints::SampleTarget::SampleTarget().
startPosP
const float* startPosP {nullptr}
zeroBase
float zeroBase {0.f}
The documentation for this struct was generated from the following files:
voice_matrix.h
voice_matrix.cpp