shortcircuit-xt: zone.h File Reference
zone.h File Reference
Classes
struct Zone
struct Zone::SingleVariant
struct Zone::Variants
struct Zone::ZoneOutputInfo
struct Zone::ZoneMappingData
Namespaces
namespace scxt
namespace scxt::voice
namespace scxt::engine
Functions
SC_DESCRIBE(scxt::engine::Zone::ZoneOutputInfo, SC_FIELD(amplitude, pmd().asCubicDecibelAttenuationWithUpperDBBound(12).withName("Amplitude"));SC_FIELD(pan, pmd().asPan().withName("Pan"));SC_FIELD(procRouting, pmd().asInt().withRange(0, 6).withUnorderedMapFormatting({ {scxt::engine::Zone::ProcRoutingPath::procRoute_linear, "LIN"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_ser2, "S2"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_ser3, "S3"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par1, "P1"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par2, "P2"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par3, "P3"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_bypass, "BYP"}, }));) SC_DESCRIBE(scxt SC_FIELD (pitchOffset, pmd().asSemitoneRange(-36, 36).withName("Pitch Offset}"))
SC_FIELD (pan, pmd().asPan().withName("Pan"))
SC_DESCRIBE (scxt::engine::Zone::ZoneMappingData, SC_FIELD(rootKey, pmd().asMIDINote().withName("Root Key"));SC_FIELD(keyboardRange.keyStart, pmd().asMIDINote().withName("Key Start"));SC_FIELD(keyboardRange.keyEnd, pmd().asMIDINote().withName("Key End"));SC_FIELD(keyboardRange.fadeStart, pmd().asMIDIPitch().withUnit("").withName("Fade Start"));SC_FIELD(keyboardRange.fadeEnd, pmd().asMIDIPitch().withUnit("").withName("Fade End"));SC_FIELD(velocityRange.velStart, pmd().asMIDIPitch().withUnit("").withName("Velocity Start"));SC_FIELD(velocityRange.velEnd, pmd().asMIDIPitch().withUnit("").withName("Velocity End"));SC_FIELD(velocityRange.fadeStart, pmd().asMIDIPitch().withUnit("").withName("Velocity Fade Start"));SC_FIELD(velocityRange.fadeEnd, pmd().asMIDIPitch().withUnit("").withName("Velocity Fade End"));.asInt() .withRange(-1, 48) .withLinearScaleFormatting("") .withDefault(-1) .withName("Pitch Bend Down") .withCustomMinDisplay("GRP"))
asInt () .withRange(-1
withLinearScaleFormatting ("") .withDefault(-1) .withName("Pitch Bend Down") .withCustomMinDisplay("GRP"))
SC_FIELD (amplitude, pmd().asDecibelWithRange(-36, 36).withName("Amplitude").withDefault(0.f))
SC_FIELD (pitchOffset, pmd().asSemitoneRange().withName("Pitch").withDefault(0.0))
asFloat () .withRange(-2
withName ("Tracking") .withLinearScaleFormatting("x") .withDecimalPlaces(2))
Variables
constexpr int lfosPerZone {scxt::lfosPerZone}
Function Documentation
SC_FIELD() [1/4]
SC_DESCRIBE(scxt::engine::Zone::ZoneOutputInfo, SC_FIELD(amplitude, pmd().asCubicDecibelAttenuationWithUpperDBBound(12).withName("Amplitude"));SC_FIELD(pan, pmd().asPan().withName("Pan"));SC_FIELD(procRouting, pmd().asInt().withRange(0, 6).withUnorderedMapFormatting({ {scxt::engine::Zone::ProcRoutingPath::procRoute_linear, "LIN"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_ser2, "S2"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_ser3, "S3"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par1, "P1"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par2, "P2"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_par3, "P3"}, {scxt::engine::Zone::ProcRoutingPath::procRoute_bypass, "BYP"}, }));) SC_DESCRIBE(scxt SC_FIELD (pitchOffset , pmd().asSemitoneRange(-36, 36).withName("Pitch Offset}"))
SC_FIELD() [2/4]
SC_FIELD (pan , pmd().asPan().withName("Pan"))
SC_DESCRIBE()
SC_DESCRIBE (scxt::engine::Zone::ZoneMappingData , SC_FIELD(rootKey, pmd().asMIDINote().withName("Root Key"));SC_FIELD(keyboardRange.keyStart, pmd().asMIDINote().withName("Key Start"));SC_FIELD(keyboardRange.keyEnd, pmd().asMIDINote().withName("Key End"));SC_FIELD(keyboardRange.fadeStart, pmd().asMIDIPitch().withUnit("").withName("Fade Start"));SC_FIELD(keyboardRange.fadeEnd, pmd().asMIDIPitch().withUnit("").withName("Fade End"));SC_FIELD(velocityRange.velStart, pmd().asMIDIPitch().withUnit("").withName("Velocity Start"));SC_FIELD(velocityRange.velEnd, pmd().asMIDIPitch().withUnit("").withName("Velocity End"));SC_FIELD(velocityRange.fadeStart, pmd().asMIDIPitch().withUnit("").withName("Velocity Fade Start"));SC_FIELD(velocityRange.fadeEnd, pmd().asMIDIPitch().withUnit("").withName("Velocity Fade End"));.asInt() .withRange(-1, 48) .withLinearScaleFormatting("") .withDefault(-1) .withName("Pitch Bend Down") .withCustomMinDisplay("GRP"))
asInt()
asInt ()
withLinearScaleFormatting()
withLinearScaleFormatting ("")
Referenced by MatrixEndpoints::MappingTarget::bind(), and VariantDisplay::rebuildForSelectedVariation().
SC_FIELD() [3/4]
SC_FIELD (amplitude , pmd().asDecibelWithRange(-36, 36).withName("Amplitude").withDefault(0.f))
SC_FIELD() [4/4]
SC_FIELD (pitchOffset , pmd().asSemitoneRange().withName("Pitch").withDefault(0.0))
asFloat()
asFloat ()
Referenced by MatrixEndpoints::MappingTarget::bind().
withName()
withName ("Tracking")
Referenced by EGTargetEndpointData< TG, gn >::baseBind(), LFOTargetEndpointData< TG, gn >::baseBind(), MatrixEndpoints::SampleTarget::bind(), ChannelStrip::ChannelStrip(), VariantDisplay::rebuildForSelectedVariation(), and SC_DESCRIBE().